import {assertCompatibleAcceptedTargetBatch,type FrozenAcceptedTarget,type CommittedAcceptedTarget,type UnbornAcceptedTarget} from "../core/accepted-target";
import {z} from "zod";
import {isSafeRef} from "../core/sanitize";
import type {FlareGitProjectState,CommittedAcceptedState,UnbornAcceptedState} from "../core/types";
import {AcceptedBranchRoots,type AcceptedBranchRoot,type AcceptedBranchScope,type UnbornAcceptedBranchRoot} from "./accepted-branch-roots";
export type AcceptedTargetBinding=FrozenAcceptedTarget;
type RecordedPrimary=Pick<FlareGitProjectState,"projectId"|"canonicalRepoName"|"defaultBranch"|"acceptedState"|"policyVersion"|"verificationPolicy">;
function primaryScope(state:RecordedPrimary,incarnation:string):AcceptedBranchScope{z.uuid().parse(incarnation);if(!state.defaultBranch||!isSafeRef(state.defaultBranch))throw Error("Recorded primary branch unavailable");return{projectId:state.projectId,incarnation,canonicalRepoName:state.canonicalRepoName,ref:`refs/heads/${state.defaultBranch}`};}
/** Bootstrap only from the repository ledger. Never takes provider HEAD/inventory input. */
export function initializeRecordedPrimary(roots:AcceptedBranchRoots,state:RecordedPrimary&{acceptedState:CommittedAcceptedState},incarnation:string,validate:()=>void):AcceptedBranchRoot;
export function initializeRecordedPrimary(roots:AcceptedBranchRoots,state:RecordedPrimary&{acceptedState:UnbornAcceptedState},incarnation:string,validate:()=>void):UnbornAcceptedBranchRoot;
export function initializeRecordedPrimary(roots:AcceptedBranchRoots,state:RecordedPrimary,incarnation:string,validate:()=>void):AcceptedBranchRoot|UnbornAcceptedBranchRoot;
export function initializeRecordedPrimary(roots:AcceptedBranchRoots,state:RecordedPrimary,incarnation:string,validate:()=>void):AcceptedBranchRoot|UnbornAcceptedBranchRoot{const scope=primaryScope(state,incarnation);if(state.acceptedState.kind==="unborn")return roots.initializeUnborn(scope,validate);if(!/^[a-f0-9]{40}$/.test(state.acceptedState.currentCommit)||/^0{40}$/.test(state.acceptedState.currentCommit))throw Error("Recorded primary history is not initialized");return roots.initializePrimary(scope,{commit:state.acceptedState.currentCommit,requirements:state.acceptedState.activeRequirements},validate);}
/** Frozen input for future target-specific review/publication. Does not grant publication authority. */
export function freezeAcceptedTarget(roots:AcceptedBranchRoots,state:RecordedPrimary&{acceptedState:CommittedAcceptedState},incarnation:string,targetRef:string):CommittedAcceptedTarget;
export function freezeAcceptedTarget(roots:AcceptedBranchRoots,state:RecordedPrimary,incarnation:string,targetRef:string):AcceptedTargetBinding;
export function freezeAcceptedTarget(roots:AcceptedBranchRoots,state:RecordedPrimary,incarnation:string,targetRef:string):AcceptedTargetBinding{const primary=primaryScope(state,incarnation);if(!targetRef.startsWith("refs/heads/")||!isSafeRef(targetRef))throw Error("Exact accepted target ref required");if(state.acceptedState.kind==="unborn"){const missing=roots.getUnborn({...primary,ref:targetRef});if(!missing||missing.kind!=="unborn"||missing.state!=="unborn"||missing.history.length!==0||missing.requirementsSnapshot!==null||targetRef!==primary.ref||missing.head!==null||missing.version!==0||!Number.isSafeInteger(state.policyVersion)||state.policyVersion<0)throw Error("Explicit unborn accepted root coverage unavailable");return{...primary,kind:"unborn",ref:targetRef,branch:targetRef.slice("refs/heads/".length),acceptedCommit:null,acceptedVersion:0,requirements:[],policyVersion:state.policyVersion,policy:structuredClone(state.verificationPolicy)} satisfies UnbornAcceptedTarget;}const root=roots.get({...primary,ref:targetRef});if(!root||root.status!=="ready"||!root.requirementsSnapshot||root.requirementsSnapshot.commit!==root.head)throw Error("Accepted target history or requirements are unverified");if(root.kind==="primary"&&(targetRef!==primary.ref||root.head!==state.acceptedState.currentCommit||JSON.stringify(root.requirementsSnapshot.requirements)!==JSON.stringify(state.acceptedState.activeRequirements)))throw Error("Primary branch ledger requires explicit publication reconciliation");if(!Number.isSafeInteger(state.policyVersion)||state.policyVersion<0)throw Error("Repository policy version unavailable");return{...primary,ref:targetRef,branch:targetRef.slice("refs/heads/".length),acceptedCommit:root.head,acceptedVersion:root.version,requirements:structuredClone(root.requirementsSnapshot.requirements),policyVersion:state.policyVersion,policy:structuredClone(state.verificationPolicy)};}
export function assertSameAcceptedTarget(expected:AcceptedTargetBinding,current:AcceptedTargetBinding):void{try{assertCompatibleAcceptedTargetBatch([expected,current]);}catch{throw Error("Accepted target, base, requirements or policy changed; a fresh candidate and review are required");}}
