import {z} from "zod";
const nameSchema=z.string().min(1).max(200).regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/),operationSchema=z.string().uuid();
export type PendingArtifactAllocation={name:string;operationId:string;projectId:string;accountKey:string;phase:"reserved"|"allocating"};
/** No expiry can erase unknown provider outcomes. Lifecycle check and insertion
 * occur in one DO SQLite transaction, the same DO that seals deletion. */
export class ArtifactAllocationFence{
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec("CREATE TABLE IF NOT EXISTS artifact_allocation_fences(name TEXT PRIMARY KEY,operation_id TEXT NOT NULL,project_id TEXT NOT NULL,account_key TEXT NOT NULL,phase TEXT NOT NULL)");}
 begin(input:Omit<PendingArtifactAllocation,"phase">,active:()=>boolean):void{nameSchema.parse(input.name);operationSchema.parse(input.operationId);nameSchema.parse(input.projectId);nameSchema.parse(input.accountKey);this.storage.transactionSync(()=>{if(!active())throw new Error("Artifact allocation is sealed for deletion");const previous=this.storage.sql.exec<{operation_id:string;phase:string}>("SELECT operation_id,phase FROM artifact_allocation_fences WHERE name=?",input.name).toArray()[0];if(previous&&previous.phase!=="settled")throw new Error("Artifact allocation is pending; reconcile its saved provider outcome");this.storage.sql.exec("INSERT INTO artifact_allocation_fences VALUES(?,?,?,?, 'reserved') ON CONFLICT(name) DO UPDATE SET operation_id=excluded.operation_id,project_id=excluded.project_id,account_key=excluded.account_key,phase='reserved'",input.name,input.operationId,input.projectId,input.accountKey);});}
 activate(name:string,operationId:string,active:()=>boolean):void{this.storage.transactionSync(()=>{if(!active())throw new Error("Artifact allocation is sealed for deletion");const row=this.storage.sql.exec<{operation_id:string;phase:string}>("SELECT operation_id,phase FROM artifact_allocation_fences WHERE name=?",name).toArray()[0];if(!row||row.operation_id!==operationId||row.phase!=="reserved")throw new Error("Allocation lease changed");this.storage.sql.exec("UPDATE artifact_allocation_fences SET phase='allocating' WHERE name=?",name);});}
 settle(name:string,operationId:string):void{operationSchema.parse(operationId);this.storage.sql.exec("UPDATE artifact_allocation_fences SET phase='settled' WHERE name=? AND operation_id=?",name,operationId);}
 pending():PendingArtifactAllocation[]{return this.storage.sql.exec<PendingArtifactAllocation>("SELECT name,operation_id AS operationId,project_id AS projectId,account_key AS accountKey,phase FROM artifact_allocation_fences WHERE phase!='settled' ORDER BY name").toArray();}
}
