import {z} from "zod";
const nameSchema=z.string().min(1).max(200).regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/),operationSchema=z.string().uuid();
/** Allocation dispatch evidence only: provider readiness does not prove Git publication.
 * Null preserves legacy or explicitly reconciled outcomes without inferred provenance. */
export type ArtifactAllocationOutcome="not_dispatched"|"provider_confirmed";
export type ArtifactAllocationInspection={name:string;operationId:string;projectId:string;accountKey:string;phase:"reserved"|"allocating"|"settled";outcome:ArtifactAllocationOutcome|null};
export type PendingArtifactAllocation={name:string;operationId:string;projectId:string;accountKey:string;phase:"reserved"|"allocating"};
/** No expiry can erase unknown provider outcomes. Lifecycle check and insertion
 * occur in one DO SQLite transaction, the same DO that seals deletion. */
export class ArtifactAllocationFence{
 constructor(private readonly storage:DurableObjectStorage){
  storage.sql.exec("CREATE TABLE IF NOT EXISTS artifact_allocation_fences(name TEXT PRIMARY KEY,operation_id TEXT NOT NULL,project_id TEXT NOT NULL,account_key TEXT NOT NULL,phase TEXT NOT NULL)");
  storage.sql.exec("CREATE TABLE IF NOT EXISTS artifact_allocation_attempts(name TEXT PRIMARY KEY,operation_id TEXT NOT NULL,attempt_id TEXT NOT NULL)");
  storage.sql.exec("CREATE TABLE IF NOT EXISTS artifact_allocation_receipts(attempt_id TEXT PRIMARY KEY,name TEXT NOT NULL,operation_id TEXT NOT NULL,outcome TEXT)");
  // Old producers can reuse the five-column INSERT contract. Their new holds
  // must not inherit a previous producer's dispatch evidence, even for one UUID.
  storage.sql.exec("CREATE TRIGGER IF NOT EXISTS artifact_allocation_insert_attempt AFTER INSERT ON artifact_allocation_fences BEGIN DELETE FROM artifact_allocation_attempts WHERE name=NEW.name; END");
  storage.sql.exec("CREATE TRIGGER IF NOT EXISTS artifact_allocation_update_attempt AFTER UPDATE ON artifact_allocation_fences WHEN NEW.phase='reserved' OR NEW.operation_id!=OLD.operation_id BEGIN DELETE FROM artifact_allocation_attempts WHERE name=NEW.name; END");
 }
 begin(input:Omit<PendingArtifactAllocation,"phase">&{attemptId?:string},active:()=>boolean):void{nameSchema.parse(input.name);operationSchema.parse(input.operationId);nameSchema.parse(input.projectId);nameSchema.parse(input.accountKey);if(input.attemptId)operationSchema.parse(input.attemptId);this.storage.transactionSync(()=>{if(!active())throw new Error("Artifact allocation is sealed for deletion");const previous=this.storage.sql.exec<{operation_id:string;phase:string}>("SELECT operation_id,phase FROM artifact_allocation_fences WHERE name=?",input.name).toArray()[0];if(previous&&previous.phase!=="settled")throw new Error("Artifact allocation is pending; reconcile its saved provider outcome");if(input.attemptId&&this.storage.sql.exec("SELECT attempt_id FROM artifact_allocation_receipts WHERE attempt_id=?",input.attemptId).toArray().length)throw new Error("Artifact allocation attempt already has a receipt");this.storage.sql.exec("INSERT INTO artifact_allocation_fences VALUES(?,?,?,?, 'reserved') ON CONFLICT(name) DO UPDATE SET operation_id=excluded.operation_id,project_id=excluded.project_id,account_key=excluded.account_key,phase='reserved'",input.name,input.operationId,input.projectId,input.accountKey);if(input.attemptId)this.storage.sql.exec("INSERT INTO artifact_allocation_attempts VALUES(?,?,?)",input.name,input.operationId,input.attemptId);});}
 activate(name:string,operationId:string,active:()=>boolean):void{this.storage.transactionSync(()=>{if(!active())throw new Error("Artifact allocation is sealed for deletion");const row=this.storage.sql.exec<{operation_id:string;phase:string}>("SELECT operation_id,phase FROM artifact_allocation_fences WHERE name=?",name).toArray()[0];if(!row||row.operation_id!==operationId||row.phase!=="reserved")throw new Error("Allocation lease changed");this.storage.sql.exec("UPDATE artifact_allocation_fences SET phase='allocating' WHERE name=?",name);});}
 settle(name:string,operationId:string,outcome?:ArtifactAllocationOutcome,attemptId?:string):void{operationSchema.parse(operationId);const reason=z.enum(["not_dispatched","provider_confirmed"]).optional().parse(outcome);if(attemptId)operationSchema.parse(attemptId);this.storage.transactionSync(()=>{const row=this.storage.sql.exec<{operation_id:string;phase:string;attempt_id:string|null}>("SELECT f.operation_id,f.phase,a.attempt_id FROM artifact_allocation_fences f LEFT JOIN artifact_allocation_attempts a ON a.name=f.name AND a.operation_id=f.operation_id WHERE f.name=?",name).toArray()[0];if(!row||row.operation_id!==operationId||(attemptId&&row.attempt_id!==attemptId))return;
   if(row.phase==="settled"){if(attemptId&&reason){const receipt=this.storage.sql.exec<{outcome:ArtifactAllocationOutcome|null}>("SELECT outcome FROM artifact_allocation_receipts WHERE attempt_id=?",attemptId).toArray()[0];if(receipt?.outcome&&receipt.outcome!==reason)throw new Error("Artifact allocation settlement outcome conflicts with its recorded receipt");}return;}
   // A legacy settlement has no attempt proof. It may close the hold but cannot
   // assign a known outcome to the current producer's attempt.
   if(row.attempt_id)this.storage.sql.exec("INSERT INTO artifact_allocation_receipts VALUES(?,?,?,?)",row.attempt_id,name,operationId,attemptId?reason??null:null);
   this.storage.sql.exec("UPDATE artifact_allocation_fences SET phase='settled' WHERE name=? AND operation_id=?",name,operationId);
  });}
 inspect(name:string):ArtifactAllocationInspection|null{nameSchema.parse(name);return this.storage.sql.exec<ArtifactAllocationInspection>("SELECT f.name,f.operation_id AS operationId,f.project_id AS projectId,f.account_key AS accountKey,f.phase,CASE WHEN f.phase='settled' THEN r.outcome ELSE NULL END AS outcome FROM artifact_allocation_fences f LEFT JOIN artifact_allocation_attempts a ON a.name=f.name AND a.operation_id=f.operation_id LEFT JOIN artifact_allocation_receipts r ON r.attempt_id=a.attempt_id WHERE f.name=?",name).toArray()[0]??null;}
 pending():PendingArtifactAllocation[]{return this.storage.sql.exec<PendingArtifactAllocation>("SELECT name,operation_id AS operationId,project_id AS projectId,account_key AS accountKey,phase FROM artifact_allocation_fences WHERE phase!='settled' ORDER BY name").toArray();}
}
