import {z} from 'zod';
import {createHash} from 'node:crypto';
import {acceptedTargetSchema,assertCompatibleAcceptedTargetBatch} from '../core/accepted-target';
import {acceptanceScopeSchema,acceptancePolicyConfigSchema,protectedAcceptanceAdapters} from './acceptance-policy';
const id=z.string().min(1).max(200),sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value));
const policySchema=z.object({config:acceptancePolicyConfigSchema,version:z.number().int().nonnegative().safe(),authorizedBy:id.nullable()}).strict();
const task=z.object({id,inputDigest:z.string().regex(/^[a-f0-9]{64}$/),status:z.enum(['ready','working','integrating','verifying','accepted','cancelled','needs_decision','blocked','checkpointed']),currentCommit:sha.nullable(),baseCommit:sha.nullable(),target:acceptedTargetSchema.nullable(),checkpoint:z.object({id,commit:sha,ready:z.boolean()}).strict().nullable(),dependsOn:id.optional()}).strict();
export const autoIntegrationFactsSchema=z.object({scope:acceptanceScopeSchema,target:acceptedTargetSchema.nullable(),policy:policySchema,origin:z.enum(['platform-fixture','imported','ordinary']),protectedAdapter:z.enum(protectedAcceptanceAdapters).nullable(),tasks:z.array(task).max(8),dependencies:z.array(z.object({id,status:z.enum(['ready','accepted','working','cancelled','unknown']),commit:sha.nullable(),target:acceptedTargetSchema.nullable()}).strict()).max(16),contradictions:z.enum(['resolved','unresolved']),preceding:z.array(z.object({workflowId:id,dispatch:z.enum(['possible','observed','held']),terminal:z.boolean(),nativeCleanup:z.enum(['confirmed','unknown'])}).strict()).max(100)}).strict().refine(value=>new Set(value.tasks.map(item=>item.id)).size===value.tasks.length&&new Set(value.dependencies.map(item=>item.id)).size===value.dependencies.length&&!value.dependencies.some(dependency=>value.tasks.some(task=>task.id===dependency.id)),'Task identities repeat');
export type AutoIntegrationFacts=z.infer<typeof autoIntegrationFactsSchema>;
export interface AutoIntegrationFence {readReadyFacts():Promise<AutoIntegrationFacts>;assertCurrent(expected?:AutoIntegrationFacts):void}
export interface AutoIntegrationDispatchRecord {requestId:string;workflowId:string;batchDigest:string;facts:AutoIntegrationFacts;phase:'saved'|'possible'|'observed'|'held';createdAt:number;heldReason?:'create_ack_unknown'|'workflow_unconfirmed';observedStatus?:string;observedAt?:number}
const observation=z.object({workflowId:id,status:z.enum(['queued','running','waiting','waitingForPause','paused','complete','errored','terminated','rollingBack'])}).strict();
export type AutoIntegrationWorkflowObservation=z.infer<typeof observation>;
function stable(value:unknown):string{if(Array.isArray(value))return'['+value.map(stable).join(',')+']';if(value!==null&&typeof value==='object')return'{'+Object.entries(value).filter(([,field])=>field!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([key,field])=>JSON.stringify(key)+':'+stable(field)).join(',')+'}';return JSON.stringify(value);}
function sync(fence:AutoIntegrationFence,expected?:AutoIntegrationFacts){const returned:unknown=fence.assertCurrent(expected?structuredClone(expected):undefined);if(returned!==undefined){if(returned instanceof Promise)void returned.catch(()=>{});throw Error('Automatic dispatch fence must be synchronous');}}
function normalize(value:AutoIntegrationFacts){const facts=autoIntegrationFactsSchema.parse(structuredClone(value));facts.tasks.sort((a,b)=>a.id.localeCompare(b.id));facts.dependencies.sort((a,b)=>a.id.localeCompare(b.id));return facts;}
function snapshot(facts:AutoIntegrationFacts){return stable({scope:facts.scope,target:facts.target?{...facts.target,kind:facts.target.kind??'committed'}:null,policy:facts.policy,tasks:facts.tasks.map(item=>({...item,target:item.target?{...item.target,kind:item.target.kind??'committed'}:null})),dependencies:facts.dependencies.map(item=>({...item,target:item.target?{...item.target,kind:item.target.kind??'committed'}:null}))});}
function eligible(facts:AutoIntegrationFacts,ownWorkflowId?:string){if(facts.policy.config.mode!=='verified-auto-accept'||facts.policy.version<1||!facts.policy.authorizedBy||facts.origin!=='platform-fixture'||facts.protectedAdapter!==facts.policy.config.protectedAdapter)throw Error('Explicit supported automatic acceptance policy required');if(!facts.target||facts.tasks.length===0)throw Error('Complete ready target scope required');if(facts.scope.projectId!==facts.target.projectId||facts.scope.incarnation!==facts.target.incarnation||facts.scope.canonicalRepoName!==facts.target.canonicalRepoName)throw Error('Automatic target repository differs');if(facts.contradictions!=='resolved')throw Error('Unresolved product decisions block automatic dispatch');if(facts.preceding.some(item=>item.workflowId!==ownWorkflowId&&(item.dispatch!=='observed'||!item.terminal||item.nativeCleanup!=='confirmed')))throw Error('Preceding dispatch or native cleanup is unconfirmed');assertCompatibleAcceptedTargetBatch([facts.target,...facts.tasks.map(item=>{if(!item.target)throw Error('Explicit ready task target required');return item.target;})]);for(const item of facts.tasks){if(item.status!=='ready'||!item.currentCommit||!item.checkpoint?.ready||item.checkpoint.commit!==item.currentCommit)throw Error('Ready checkpoint changed');if(!item.dependsOn){if(item.baseCommit!==facts.target.acceptedCommit)throw Error('Ready contribution base is stale');continue;}const parent=facts.tasks.find(parent=>parent.id===item.dependsOn)??facts.dependencies.find(parent=>parent.id===item.dependsOn);if(!parent)throw Error('Complete ready dependency scope required');if('currentCommit'in parent){if(item.baseCommit!==parent.currentCommit)throw Error('Stack checkpoint base differs');}else{if(parent.status!=='accepted'||parent.commit!==item.baseCommit||item.baseCommit!==facts.target.acceptedCommit)throw Error('Accepted dependency is incomplete or stale');if(!parent.target||parent.target.projectId!==facts.target.projectId||parent.target.incarnation!==facts.target.incarnation||parent.target.canonicalRepoName!==facts.target.canonicalRepoName||parent.target.ref!==facts.target.ref)throw Error('Stack dependency target differs');}}for(const item of facts.tasks){const seen=new Set<string>();let node:typeof item|undefined=item;while(node){if(seen.has(node.id))throw Error('Ready dependency cycle');seen.add(node.id);const dependency:AutoIntegrationFacts['tasks'][number]['dependsOn']=node.dependsOn;node=dependency?facts.tasks.find(parent=>parent.id===dependency):undefined;}}}
async function bounded<T>(read:()=>Promise<T>){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([Promise.resolve().then(read),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Automatic dispatch trusted read deadline')),5000);})]);}finally{if(timer!==undefined)clearTimeout(timer);}}
/** Scheduling only; observation never approves candidate verification or Git history.
 * A possible/held create has exactly one immutable workflow ID for readback. */
export class AutoIntegrationDispatch {
 constructor(private storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS auto_integration_dispatches(request_id TEXT PRIMARY KEY,batch_digest TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS auto_integration_requests(request_id TEXT PRIMARY KEY,dispatch_request_id TEXT NOT NULL)');}
 private read(requestId:string){z.uuid().parse(requestId);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM auto_integration_dispatches WHERE request_id=COALESCE((SELECT dispatch_request_id FROM auto_integration_requests WHERE request_id=?),?)',requestId,requestId).toArray()[0];return row?JSON.parse(row.doc) as AutoIntegrationDispatchRecord:null;}
 private save(row:AutoIntegrationDispatchRecord){this.storage.sql.exec('UPDATE auto_integration_dispatches SET doc=? WHERE request_id=?',JSON.stringify(row),row.requestId);}
 private async current(fence:AutoIntegrationFence){sync(fence);const facts=normalize(await bounded(()=>fence.readReadyFacts()));sync(fence,facts);return facts;}
 async prepare(requestId:string,fence:AutoIntegrationFence):Promise<AutoIntegrationDispatchRecord>{z.uuid().parse(requestId);const guarded={readReadyFacts:fence.readReadyFacts,assertCurrent:fence.assertCurrent},facts=await this.current(guarded),old=this.read(requestId);if(old){if(stable(old.facts.scope)!==stable(facts.scope))throw Error('Original automatic dispatch repository changed');return structuredClone(old);}const frozen=snapshot(facts);if(new TextEncoder().encode(stable(facts)).byteLength>262144)throw Error('Automatic dispatch snapshot exceeds safe bound');const batchDigest=createHash('sha256').update(frozen).digest('hex'),fresh=await this.current(guarded);if(snapshot(fresh)!==frozen)throw Error('Automatic ready snapshot changed');return this.storage.transactionSync(()=>{sync(guarded,fresh);const duplicate=this.read(requestId);if(duplicate){if(duplicate.batchDigest!==batchDigest)throw Error('Automatic request identity changed');return structuredClone(duplicate);}const same=this.storage.sql.exec<{request_id:string;doc:string}>('SELECT request_id,doc FROM auto_integration_dispatches WHERE batch_digest=?',batchDigest).toArray()[0];const sameRecord=same?JSON.parse(same.doc) as AutoIntegrationDispatchRecord:null;eligible(fresh,sameRecord?.workflowId);if(!sameRecord&&fresh.target&&this.storage.sql.exec("SELECT request_id FROM auto_integration_dispatches WHERE json_extract(doc,'$.facts.scope.projectId')=? AND json_extract(doc,'$.facts.scope.incarnation')=? AND json_extract(doc,'$.facts.scope.canonicalRepoName')=? AND json_extract(doc,'$.facts.target.ref')=? AND json_extract(doc,'$.phase') IN ('possible','held') LIMIT 1",fresh.scope.projectId,fresh.scope.incarnation,fresh.scope.canonicalRepoName,fresh.target.ref).toArray().length)throw Error('Original automatic dispatch remains possible or held');if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM auto_integration_requests').toArray()[0]!.n>=10000)throw Error('Automatic dispatch audit capacity reached');this.storage.sql.exec('INSERT INTO auto_integration_requests VALUES(?,?)',requestId,same?.request_id??requestId);if(same)return JSON.parse(same.doc) as AutoIntegrationDispatchRecord;const record:AutoIntegrationDispatchRecord={requestId,workflowId:`auto-${crypto.randomUUID()}`,batchDigest,facts,phase:'saved',createdAt:Date.now()};this.storage.sql.exec('INSERT INTO auto_integration_dispatches VALUES(?,?,?)',requestId,batchDigest,JSON.stringify(record));return structuredClone(record);});}
 async markPossible(requestId:string,fence:AutoIntegrationFence):Promise<{dispatch:boolean;record:AutoIntegrationDispatchRecord}>{const guarded={readReadyFacts:fence.readReadyFacts,assertCurrent:fence.assertCurrent},facts=await this.current(guarded),old=this.read(requestId);if(!old)throw Error('Saved automatic intent required');if(stable(facts.scope)!==stable(old.facts.scope))throw Error('Automatic intent scope changed');if(old.phase!=='saved')return{dispatch:false,record:structuredClone(old)};eligible(facts,old.workflowId);if(snapshot(facts)!==snapshot(old.facts))throw Error('Automatic checkpoint or policy changed before dispatch');return this.storage.transactionSync(()=>{sync(guarded,facts);const latest=this.read(requestId);if(!latest)throw Error('Saved automatic intent vanished');if(latest.phase!=='saved')return{dispatch:false,record:structuredClone(latest)};latest.phase='possible';this.save(latest);return{dispatch:true,record:structuredClone(latest)};});}
 async hold(requestId:string,fence:AutoIntegrationFence){const guarded={readReadyFacts:fence.readReadyFacts,assertCurrent:fence.assertCurrent},facts=await this.current(guarded);return this.storage.transactionSync(()=>{sync(guarded,facts);const row=this.read(requestId);if(!row||stable(row.facts.scope)!==stable(facts.scope))throw Error('Original automatic intent required');if(row.phase==='possible'){row.phase='held';row.heldReason='create_ack_unknown';this.save(row);}return structuredClone(row);});}
 async inspect(requestId:string,fence:AutoIntegrationFence,readWorkflow:(workflowId:string)=>Promise<AutoIntegrationWorkflowObservation|null>){const guarded={readReadyFacts:fence.readReadyFacts,assertCurrent:fence.assertCurrent},facts=await this.current(guarded),row=this.read(requestId);if(!row||stable(row.facts.scope)!==stable(facts.scope))throw Error('Original automatic intent required');if(row.phase==='saved')return structuredClone(row);let native:AutoIntegrationWorkflowObservation|null=null;try{const result=await bounded(()=>readWorkflow(row.workflowId));native=result===null?null:observation.parse(structuredClone(result));}catch{/* Opaque provider failure never grants replacement workflow. */}const fresh=await this.current(guarded);if(stable(fresh.scope)!==stable(row.facts.scope))throw Error('Automatic readback scope changed');if(native&&native.workflowId!==row.workflowId)throw Error('Automatic workflow readback identity differs');return this.storage.transactionSync(()=>{sync(guarded,fresh);const current=this.read(requestId);if(!current)throw Error('Saved automatic intent vanished');if(native){current.phase='observed';current.observedStatus=native.status;current.observedAt=Date.now();delete current.heldReason;}else{current.phase='held';current.heldReason='workflow_unconfirmed';}this.save(current);return structuredClone(current);});}
}
