import{branchNativeAttemptSchema,type BranchNativeAttemptIdentity}from'./branch-creation-operations';
import{z}from'zod';
const stageSchema=z.enum(['intent','funding','provider_metadata','metadata_validation','credential_issuance','credential_validation','http_transport','packet_validation','metadata_readback','credential_cleanup','final_authority','complete']);
export type BranchHttpStage=z.infer<typeof stageSchema>;
export interface BranchHttpAttempt{identity:BranchNativeAttemptIdentity;createdAt:number;ended:boolean}
/** HTTP read credential ownership, never a container allocation or stop receipt. */
export class BranchHttpAttempts{
 constructor(private storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS branch_http_attempts(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL,ended INTEGER NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS branch_http_results(attempt_id TEXT PRIMARY KEY,stage TEXT NOT NULL,failure_stage TEXT,outcome TEXT NOT NULL)');}
 begin(identity:BranchNativeAttemptIdentity,validate:()=>void){const input=branchNativeAttemptSchema.parse(identity);if(input.kind!=='inventory')throw Error('HTTP inspection is read-only');this.storage.transactionSync(()=>{validate();if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM branch_http_attempts').one().n>=10000)throw Error('Branch HTTP audit capacity reached');this.storage.sql.exec('INSERT INTO branch_http_attempts VALUES(?,?,?,?,0)',input.attemptId,input.operationId,JSON.stringify(input),Date.now());});}
 get(id:string):BranchHttpAttempt|null{const row=this.storage.sql.exec<{payload:string;created_at:number;ended:number}>('SELECT payload,created_at,ended FROM branch_http_attempts WHERE id=?',id).toArray()[0];return row?{identity:branchNativeAttemptSchema.parse(JSON.parse(row.payload)),createdAt:row.created_at,ended:row.ended===1}:null;}
 end(id:string){this.storage.sql.exec('UPDATE branch_http_attempts SET ended=1 WHERE id=?',id);}
 stage(id:string,stage:BranchHttpStage){stageSchema.parse(stage);this.storage.sql.exec("INSERT INTO branch_http_results VALUES(?,?,NULL,'pending') ON CONFLICT(attempt_id) DO UPDATE SET stage=excluded.stage",id,stage);}
 failed(id:string){this.storage.sql.exec("UPDATE branch_http_results SET failure_stage=COALESCE(failure_stage,stage),outcome='failed' WHERE attempt_id=?",id);}
 complete(id:string){this.storage.sql.exec("UPDATE branch_http_results SET stage='complete',outcome='complete' WHERE attempt_id=? AND failure_stage IS NULL",id);}
 inspections(projectId:string,incarnation:string){const rows=this.storage.sql.exec<{id:string;operation_id:string;created_at:number;ended:number;stage:string|null;failure_stage:string|null;outcome:string|null}>("SELECT a.id,a.operation_id,a.created_at,a.ended,r.stage,r.failure_stage,r.outcome FROM branch_http_attempts a LEFT JOIN branch_http_results r ON r.attempt_id=a.id WHERE json_extract(a.payload,'$.projectId')=? AND json_extract(a.payload,'$.incarnation')=? ORDER BY a.created_at DESC,a.rowid DESC LIMIT 10",projectId,incarnation).toArray();return rows.map(row=>({attemptId:row.id,operationId:row.operation_id,createdAt:row.created_at,executionEnded:row.ended===1,nativeState:'not_allocated' as const,stage:stageSchema.safeParse(row.stage).data??null,failureStage:stageSchema.safeParse(row.failure_stage).data??null,outcome:row.outcome==='complete'?'complete' as const:row.outcome==='failed'?'failed' as const:row.outcome==='pending'?'pending' as const:'legacy_unknown' as const}));}
}
