import {z} from "zod";
import {isSafeRef} from "../core/sanitize";
export const branchCreationSchema=z.object({operationId:z.uuid(),projectId:z.string().min(1).max(128),incarnation:z.uuid(),canonicalRepoName:z.string().min(1).max(200),actorId:z.string().min(1).max(256),accountKey:z.string().min(1).max(200),branch:z.string().refine(value=>isSafeRef(value)&&!value.startsWith("refs/")),sourceCommit:z.string().regex(/^[a-f0-9]{40}$/),acceptedCommit:z.string().regex(/^[a-f0-9]{40}$/)}).strict();
export type BranchCreationIdentity=z.infer<typeof branchCreationSchema>;
export interface BranchCreationOperation extends BranchCreationIdentity{phase:"prepared"|"unknown"|"confirmed"|"refused";reason?:"existing_ref"|"different_ref"|"owner_abandoned_prepared";createdAt:number;observedCommit?:string}
/** Native/credential ownership remains separate; this ledger never grants Git authority. */
export class BranchCreationOperations{
 constructor(private storage:DurableObjectStorage){storage.sql.exec("CREATE TABLE IF NOT EXISTS branch_creation_operations(id TEXT PRIMARY KEY,payload TEXT NOT NULL,doc TEXT NOT NULL)");}
 get(id:string):BranchCreationOperation|null{z.uuid().parse(id);const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM branch_creation_operations WHERE id=?",id).toArray()[0];return row?JSON.parse(row.doc) as BranchCreationOperation:null;}
 prepare(identity:BranchCreationIdentity,validate:()=>void,now=Date.now()):BranchCreationOperation{const value=branchCreationSchema.parse(identity);if(!Number.isSafeInteger(now)||now<0)throw Error("Invalid branch operation clock");return this.storage.transactionSync(()=>{validate();const row=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM branch_creation_operations WHERE id=?",value.operationId).toArray()[0],payload=JSON.stringify(value);if(row){if(row.payload!==payload)throw Error("Branch operation identity changed");return JSON.parse(row.doc) as BranchCreationOperation;}if(this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM branch_creation_operations").toArray()[0]!.n>=10000)throw Error("Branch operation audit capacity reached");const operation:BranchCreationOperation={...value,phase:"prepared",createdAt:now};this.storage.sql.exec("INSERT INTO branch_creation_operations VALUES(?,?,?)",value.operationId,payload,JSON.stringify(operation));return operation;});}
 abandon(identity:BranchCreationIdentity,validate:()=>void):BranchCreationOperation{return this.update(identity,validate,value=>{if(value.phase==="refused"&&value.reason==="owner_abandoned_prepared")return;if(value.phase!=="prepared")throw Error("Only undispatched prepared branch operations can be abandoned");value.phase="refused";value.reason="owner_abandoned_prepared";});}
 markDispatch(identity:BranchCreationIdentity,validate:()=>void):BranchCreationOperation{return this.update(identity,validate,value=>{if(value.phase==="prepared")value.phase="unknown";else if(value.phase!=="unknown")throw Error("Branch operation is terminal");});}
 observe(identity:BranchCreationIdentity,commit:string|null,validate:()=>void):BranchCreationOperation{if(commit!==null&&!/^[a-f0-9]{40}$/.test(commit))throw Error("Invalid branch readback");return this.update(identity,validate,value=>{if(value.phase==="confirmed"||value.phase==="refused")return;if(commit===null)return;value.observedCommit=commit;if(value.phase==="unknown"&&commit===value.sourceCommit)value.phase="confirmed";else{value.phase="refused";value.reason=commit===value.sourceCommit?"existing_ref":"different_ref";}});}
 private update(identity:BranchCreationIdentity,validate:()=>void,change:(value:BranchCreationOperation)=>void){const parsed=branchCreationSchema.parse(identity);return this.storage.transactionSync(()=>{validate();const row=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM branch_creation_operations WHERE id=?",parsed.operationId).toArray()[0];if(!row||row.payload!==JSON.stringify(parsed))throw Error("Branch operation scope changed");const value=JSON.parse(row.doc) as BranchCreationOperation;change(value);this.storage.sql.exec("UPDATE branch_creation_operations SET doc=? WHERE id=?",JSON.stringify(value),parsed.operationId);return value;});}
}

export const branchNativeAttemptSchema=z.object({attemptId:z.uuid(),nativeId:z.uuid(),operationId:z.uuid(),kind:z.enum(["inventory","create"]),projectId:z.string().min(1).max(128),incarnation:z.uuid(),canonicalRepoName:z.string().min(1).max(200),actorId:z.string().min(1).max(256),accountKey:z.string().min(1).max(200),snapshotDigest:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
export type BranchNativeAttemptIdentity=z.infer<typeof branchNativeAttemptSchema>;
export interface BranchNativeAttempt extends BranchNativeAttemptIdentity{state:"possible"|"stopped";createdAt:number;stoppedAt?:number;executionEndedAt?:number}
/** Exact native attempt tracking for real inventory/create operations; never a stop observer itself. */
export class BranchNativeAttempts{
 constructor(private storage:DurableObjectStorage){storage.sql.exec("CREATE TABLE IF NOT EXISTS branch_native_attempts(id TEXT PRIMARY KEY,native_id TEXT UNIQUE NOT NULL,operation_id TEXT NOT NULL,payload TEXT NOT NULL,doc TEXT NOT NULL)");}
 get(id:string):BranchNativeAttempt|null{z.uuid().parse(id);const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM branch_native_attempts WHERE id=?",id).toArray()[0];return row?JSON.parse(row.doc) as BranchNativeAttempt:null;}
 begin(identity:BranchNativeAttemptIdentity,validate:()=>void,now=Date.now()):BranchNativeAttempt{const input=branchNativeAttemptSchema.parse(identity);if(!Number.isSafeInteger(now)||now<0)throw Error("Invalid branch native clock");return this.storage.transactionSync(()=>{validate();const payload=JSON.stringify(input),existing=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM branch_native_attempts WHERE id=?",input.attemptId).toArray()[0];if(existing){if(existing.payload!==payload)throw Error("Branch native attempt scope changed");const value=JSON.parse(existing.doc) as BranchNativeAttempt;if(value.state==="stopped")throw Error("Stopped branch attempt cannot provision again");return value;}if(this.storage.sql.exec("SELECT id FROM branch_native_attempts WHERE operation_id=? AND json_extract(doc,'$.state')!='stopped' LIMIT 1",input.operationId).toArray().length)throw Error("Branch workspace shutdown remains unconfirmed");if(this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM branch_native_attempts").toArray()[0]!.n>=10000)throw Error("Branch native audit capacity reached");const value:BranchNativeAttempt={...input,state:"possible",createdAt:now};this.storage.sql.exec("INSERT INTO branch_native_attempts VALUES(?,?,?,?,?)",input.attemptId,input.nativeId,input.operationId,payload,JSON.stringify(value));return value;});}
 markExecutionEnded(identity:BranchNativeAttemptIdentity,validate:()=>void,now=Date.now()):BranchNativeAttempt{const input=branchNativeAttemptSchema.parse(identity);if(!Number.isSafeInteger(now)||now<0)throw Error("Invalid execution completion clock");return this.storage.transactionSync(()=>{validate();const row=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM branch_native_attempts WHERE id=?",input.attemptId).toArray()[0];if(!row||row.payload!==JSON.stringify(input))throw Error("Branch execution scope changed");const current=JSON.parse(row.doc) as BranchNativeAttempt;if(current.executionEndedAt!==undefined)return current;const ended:BranchNativeAttempt={...current,executionEndedAt:now};this.storage.sql.exec("UPDATE branch_native_attempts SET doc=? WHERE id=?",JSON.stringify(ended),input.attemptId);return ended;});}
 pendingSummary(limit=20){const page=this.pending(limit);return{attempts:page.attempts.map(value=>({attemptId:value.attemptId,operationId:value.operationId,kind:value.kind,state:value.state,executionEnded:value.executionEndedAt!==undefined,createdAt:value.createdAt})),truncated:page.truncated};}
 confirmStopped(identity:BranchNativeAttemptIdentity,receipt:{nativeId:string;state:"stopped"},now=Date.now()):BranchNativeAttempt{const input=branchNativeAttemptSchema.parse(identity);if(receipt.nativeId!==input.nativeId||receipt.state!=="stopped"||!Number.isSafeInteger(now)||now<0)throw Error("Branch shutdown receipt unavailable");return this.storage.transactionSync(()=>{const row=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM branch_native_attempts WHERE id=?",input.attemptId).toArray()[0];if(!row||row.payload!==JSON.stringify(input))throw Error("Branch shutdown scope changed");const value=JSON.parse(row.doc) as BranchNativeAttempt;if(value.state==="stopped")return value;const stopped:BranchNativeAttempt={...value,state:"stopped",stoppedAt:now};this.storage.sql.exec("UPDATE branch_native_attempts SET doc=? WHERE id=?",JSON.stringify(stopped),input.attemptId);return stopped;});}
 pending(limit=20):{attempts:BranchNativeAttempt[];truncated:boolean}{z.number().int().min(1).max(20).parse(limit);const rows=this.storage.sql.exec<{doc:string}>("SELECT doc FROM branch_native_attempts WHERE json_extract(doc,'$.state')!='stopped' ORDER BY rowid LIMIT ?",limit+1).toArray();return{attempts:rows.slice(0,limit).map(row=>JSON.parse(row.doc) as BranchNativeAttempt),truncated:rows.length>limit};}
 hasUnconfirmed(){return this.storage.sql.exec("SELECT id FROM branch_native_attempts WHERE json_extract(doc,'$.state')!='stopped' LIMIT 1").toArray().length>0;}
}
