import {DurableObject,WorkerEntrypoint} from 'cloudflare:workers';
import {createHash,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import type {C02CanaryBindings} from './c02-canary-env';
import {UntrustedExecutionSandbox,type UntrustedExecutionEnvironment} from './untrusted-execution-sandbox';
import {untrustedExecutionName} from './untrusted-execution';
import {bindBuildManifest,type BuildFile,type BuildManifest,type StaticBuildScope} from './static-build-artifact';
import {bindBrowserPolicy,verifyExternalBrowser,type BrowserPolicy} from './external-browser-verifier';
import {BudgetedBrowserTransportRouter} from './budgeted-browser-transport';
import {BrowserSessionBudget,browserSessionScopeSchema,type BrowserSessionScope} from './browser-session-budget';
import {retireBrowserSession,cloudflareBrowserSdk,type BrowserSessionControl} from './cloudflare-browser-transport';
import {ManagedSpendLedger} from './managed-spend-ledger';
import {executionAuthorityResponse} from './isolated-execution-authority';
export {UntrustedExecutionSandbox};

const singleton='fixed-synthetic-canary-v1';
const reservation={nativeUsdMicros:43008,browserUsdMicros:100000,totalUsdMicros:143008,nativeSeconds:120,browserSeconds:120,maxContainers:1,maxBrowserAcquisitions:1} as const;
const policy:BrowserPolicy={version:1,deadlineMs:30000,cases:[{id:'isolated_dom_forgery_refused',actions:[{kind:'navigate',path:'/'}],assertions:[{query:{kind:'text',selector:'h1'},expected:'Approved'}]}]};
export function c02CanaryPolicy():BrowserPolicy{return structuredClone(policy);}
const fixtureHtml='<!doctype html><html><head><link rel="icon" type="image/svg+xml" href="./favicon.svg"></head><body><h1>Blocked</h1><script>document.querySelector=()=>({textContent:"Approved",value:"Approved"});Object.defineProperty(window,"syntheticFixtureReport",{value:{passed:true}});</script></body></html>';
const fixtureFavicon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><rect width="16" height="16" rx="3" fill="#f38020"/><path d="M4 8h8M8 4v8" stroke="white" stroke-width="2"/></svg>';
export function c02ExpectedBrowserRefusal(error:unknown):boolean{return error instanceof Error&&error.message==='Browser expected check failed: isolated_dom_forgery_refused';}
const image=z.string().regex(/^registry\.cloudflare\.com\/[a-f0-9]{32}\/[a-z0-9-]+@sha256:[a-f0-9]{64}$/);
const sourceVersion=z.string().regex(/^[a-f0-9]{40}$/);
const requestSchema=z.object({requestId:z.uuid()}).strict();
type C02CanaryEnvironment=Pick<C02CanaryBindings,'CANARY'|'UNTRUSTED_EXECUTION'|'BROWSER'|'CF_VERSION_METADATA'>&UntrustedExecutionEnvironment&{C02_ENABLED:string;C02_IMAGE:string;C02_SOURCE_VERSION:string;C02_OPERATOR_SECRET?:string};
interface BatchRecord {requestId:string;scope:StaticBuildScope;source:BuildManifest;image:string;sourceVersion:string;workerVersion:string;phase:'prepared'|'native_possible'|'native_confirmed'|'browser_possible'|'complete';createdAt:number;deadlineAt:number;output?:BuildManifest;nativeCleanup:boolean;browserCleanup:boolean;browserVersion?:string;observedDom?:string;browserLeaseId?:string;browserScope?:BrowserSessionScope;budgetHeld:boolean;expectedVerifierFailure?:boolean}
export function c02OperatorAuthorized(request:Request,secret:string|undefined):boolean{const header=request.headers.get('Authorization')??'';if(!secret||! /^[A-Za-z0-9_-]{32,256}$/.test(secret)||! /^Bearer [A-Za-z0-9_-]{32,256}$/.test(header))return false;return timingSafeEqual(createHash('sha256').update(header.slice(7)).digest(),createHash('sha256').update(secret).digest());}
export function c02CanaryManifest(){return{version:1,fixture:'synthetic-security-fixture-not-Git-production-evidence',cases:[{id:policy.cases[0]!.id,expected:'Actual isolated DOM returns Blocked; caller page spoof cannot produce trusted Approved'}],acceptanceEvidence:false,reservation,reservationBasis:'conservative local admission; not invoice cap',networkCoverage:'deny hooks configured; only counted events are observed evidence',assets:false,fullC02Coverage:false};}
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,'0')).join('');}
export function c02CanaryFixtureFiles():BuildFile[]{return[{path:'index.html',kind:'file',bytes:new TextEncoder().encode(fixtureHtml)},{path:'favicon.svg',kind:'file',bytes:new TextEncoder().encode(fixtureFavicon)}];}

async function fixedRequestId(request:Request):Promise<string>{if(request.headers.get('Content-Type')?.split(';')[0]?.trim().toLowerCase()!=='application/json')throw Error('JSON request required');const reader=request.body?.getReader();if(!reader)throw Error('Request required');const deadline=Date.now()+5000,signal=AbortSignal.timeout(5000);let bytes=0;const chunks:Uint8Array[]=[];try{for(;;){if(Date.now()>=deadline)throw Error('Request deadline');signal.throwIfAborted();let abort:()=>void=()=>{};let next:Awaited<ReturnType<typeof reader.read>>;try{next=await Promise.race([reader.read(),new Promise<never>((_,reject)=>{abort=()=>reject(Error('Request deadline'));signal.addEventListener('abort',abort,{once:true});})]);}finally{signal.removeEventListener('abort',abort);}if(next.done)break;bytes+=next.value.byteLength;if(bytes>256)throw Error('Request too large');chunks.push(next.value);}const body=new Uint8Array(bytes);let at=0;for(const chunk of chunks){body.set(chunk,at);at+=chunk.byteLength;}return requestSchema.parse(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(body))).requestId;}catch(error){void reader.cancel().catch(()=>{});throw error;}}
/** Dedicated one-batch ledger. It has no repository, credential, Clerk or R2 binding. */
export class C02CanaryBatch extends DurableObject<C02CanaryEnvironment>{
 private ledger(){this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS c02_canary_batch(id INTEGER PRIMARY KEY CHECK(id=1),doc TEXT NOT NULL)');this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS c02_canary_denials(id INTEGER PRIMARY KEY AUTOINCREMENT,scheme TEXT NOT NULL)');}
 private read():BatchRecord|null{this.ledger();const row=this.ctx.storage.sql.exec<{doc:string}>('SELECT doc FROM c02_canary_batch WHERE id=1').toArray()[0];return row?JSON.parse(row.doc) as BatchRecord:null;}
 private save(row:BatchRecord){this.ctx.storage.sql.exec('INSERT INTO c02_canary_batch VALUES(1,?) ON CONFLICT(id) DO UPDATE SET doc=excluded.doc',JSON.stringify(row));}
 private assert(row:BatchRecord){const current=this.read();if(!current||current.requestId!==row.requestId||JSON.stringify(current.scope)!==JSON.stringify(row.scope)||current.source.digest!==row.source.digest||current.image!==row.image||this.env.C02_ENABLED!=='true'||this.env.C02_IMAGE!==row.image||this.env.C02_SOURCE_VERSION!==row.sourceVersion||this.env.CF_VERSION_METADATA.id!==row.workerVersion||Date.now()>=row.deadlineAt||current.phase==='complete')throw Error('Canary authority unavailable');}
 async status(){const row=this.read(),denials=this.ctx.storage.sql.exec<{scheme:string;count:number}>('SELECT scheme,COUNT(*) AS count FROM c02_canary_denials GROUP BY scheme').toArray();return{manifest:c02CanaryManifest(),batch:row?{requestId:row.requestId,phase:row.phase,createdAt:row.createdAt,sourceVersion:row.sourceVersion,workerVersion:row.workerVersion,requestedImage:row.image,sourceDigest:row.source.digest,policyDigest:row.scope.policyDigest,outputDigest:row.output?.digest??null,nativeCleanup:row.nativeCleanup,browserCleanup:row.browserCleanup,browserVersion:row.browserVersion??null,observedDom:row.observedDom??null,budgetHeld:row.budgetHeld,expectedVerifierFailure:row.expectedVerifierFailure??false}:null,deniedNetworkEvents:denials,networkCoverage:'not-exercised',denialEventAttribution:'private-service-events-not-native-VM-provenance',acceptanceEvidence:false};}
 async deny(scheme:string){this.ledger();if(this.ctx.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM c02_canary_denials').toArray()[0]!.n<64)this.ctx.storage.sql.exec('INSERT INTO c02_canary_denials(scheme) VALUES(?)',scheme==='http:'?'http':scheme==='https:'?'https':'other');}
 async allow(context:{scope:StaticBuildScope;sourceDigest:string;image:string}){const row=this.read();if(!row)return false;try{this.assert(row);return['prepared','native_possible'].includes(row.phase)&&JSON.stringify(context.scope)===JSON.stringify(row.scope)&&context.sourceDigest===row.source.digest&&context.image===row.image;}catch{return false;}}
 private browserScope(row:BatchRecord,leaseId:string):BrowserSessionScope{if(row.browserScope){if(row.browserScope.leaseId!==leaseId)throw Error('Original browser lease differs');return browserSessionScopeSchema.parse(structuredClone(row.browserScope));}if(!row.output)throw Error('Recorded canary output required');return{leaseId,attemptId:row.scope.attemptId,projectId:row.scope.projectId,incarnation:row.scope.incarnation,accountKey:'c02-private-operator',actorId:'authenticated-canary-operator',candidateId:'synthetic-only',canonicalRepoName:'no-real-repository',targetRef:'refs/heads/synthetic-fixture',expectedBase:null,acceptedVersion:0,commit:row.scope.commit,tree:row.scope.tree,policyVersion:1,policyDigest:row.scope.policyDigest,buildDigest:row.output.digest,sourceDigest:row.source.digest,maxSeconds:120};}
 protected browserControl():BrowserSessionControl{return this.env.BROWSER;}
 protected async nativeCleanupJob(row:BatchRecord):Promise<Pick<UntrustedExecutionSandbox,'stop'|'outputReceipt'>>{const namespace=this.env.UNTRUSTED_EXECUTION;if(!namespace)throw Error('Original native namespace unavailable');return namespace.getByName(await untrustedExecutionName(row.scope,row.source.digest));}
 private browserBudget(row:BatchRecord,cleanup?:{deadline:number;signal:AbortSignal}){return new BrowserSessionBudget(this.ctx.storage,{authorize:async proposed=>{if(cleanup)throw Error('Cleanup cannot authorize new browser work');this.assert(row);if(JSON.stringify(proposed)!==JSON.stringify(this.browserScope(row,proposed.leaseId)))throw Error('Fixed browser case scope differs');return()=>this.assert(row);},funding:()=>({reservationUsdMicros:reservation.browserUsdMicros,budget:{accountUsdMicros:reservation.totalUsdMicros,globalUsdMicros:reservation.totalUsdMicros}}),attestClosure:async sessionId=>{const remaining=cleanup?Math.min(8000,Math.floor(cleanup.deadline-performance.now())):8000;if(remaining<1)return null;return retireBrowserSession(this.browserControl(),sessionId,{timeoutMs:remaining,...(cleanup?{signal:cleanup.signal}:{})});}},{cleanupMs:cleanup?Math.max(1,Math.min(8000,Math.floor(cleanup.deadline-performance.now()))):8000});}
 async cleanup(requestId:string){requestSchema.parse({requestId});const original=this.read();if(!original||original.requestId!==requestId)throw Error('Only the original captured batch can be cleaned');const snapshot=JSON.stringify({requestId:original.requestId,scope:original.scope,sourceDigest:original.source.digest,image:original.image});const fence=()=>{const current=this.read();if(!current||JSON.stringify({requestId:current.requestId,scope:current.scope,sourceDigest:current.source.digest,image:current.image})!==snapshot)throw Error('Original cleanup scope changed');return current;};const deadline=performance.now()+8000,signal=AbortSignal.timeout(8000);
  const wait=async<T>(work:()=>Promise<T>)=>{fence();const remaining=Math.floor(deadline-performance.now());if(remaining<1||signal.aborted)throw Error('Canary cleanup deadline');const actual=Promise.resolve().then(work);this.ctx.waitUntil(actual.catch(()=>undefined));let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([actual,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Canary cleanup deadline')),remaining);})]);}finally{if(timer!==undefined)clearTimeout(timer);}};
  const actual=(async()=>{try{const job=await wait(()=>this.nativeCleanupJob(original));const stopped=await wait(()=>job.stop());const receipt=await wait(()=>job.outputReceipt(original.scope,original.source.digest));if(stopped.stopped&&receipt?.cleanup==='confirmed'&&receipt.image===original.image&&receipt.sourceDigest===original.source.digest&&JSON.stringify(receipt.scope)===JSON.stringify(original.scope)&&receipt.manifest.kind==='static'&&receipt.manifest.sourceDigest===original.source.digest&&JSON.stringify(receipt.manifest.scope)===JSON.stringify(original.scope)&&receipt.acceptanceEvidence===false&&(!original.output||receipt.manifest.digest===original.output.digest)){const current=fence();this.save({...current,nativeCleanup:true,output:receipt.manifest});}}catch{/* Known original resource stays held; no repeated work. */}
   try{const current=fence();if(current.browserLeaseId&&current.output){const budget=this.browserBudget(current,{deadline,signal}),lease=budget.get(current.browserLeaseId);if(lease&&JSON.stringify(lease.scope)===JSON.stringify(this.browserScope(current,current.browserLeaseId))){const closed=await wait(()=>budget.close(lease.scope));if(closed.phase==='closed'&&closed.sessionId!==null&&closed.closure?.sessionId===closed.sessionId){const live=fence();this.save({...live,browserCleanup:true});}}}}catch{/* Unknown session acquisition never permits a broad inventory or reset. */}
   const current=fence();if(current.expectedVerifierFailure===true&&current.observedDom==='Blocked'&&current.nativeCleanup&&current.browserCleanup)this.save({...current,phase:'complete',budgetHeld:true});})();this.ctx.waitUntil(actual.catch(()=>undefined));try{await wait(()=>actual);}catch{/* Finite response; late original facts are retained independently. */}return this.status();
 }
 async run(requestId:string){requestSchema.parse({requestId});if(this.env.C02_ENABLED!=='true')throw Error('Canary execution disabled');const pinned=image.parse(this.env.C02_IMAGE),version=sourceVersion.parse(this.env.C02_SOURCE_VERSION);const old=this.read();if(old){if(old.requestId!==requestId)throw Error('Fixed canary batch already consumed');return this.status();}
  const bound=await bindBrowserPolicy(policy),synthetic=await hash(fixtureHtml),scope:StaticBuildScope={attemptId:crypto.randomUUID(),projectId:'c02syntheticcase',incarnation:crypto.randomUUID(),commit:synthetic.slice(0,40),tree:(await hash('synthetic-tree:'+fixtureHtml)).slice(0,40),policyDigest:bound.digest};const source=await bindBuildManifest('source',scope,c02CanaryFixtureFiles());let row:BatchRecord={requestId,scope,source,image:pinned,sourceVersion:version,workerVersion:this.env.CF_VERSION_METADATA.id,phase:'prepared',createdAt:Date.now(),deadlineAt:Date.now()+180000,nativeCleanup:false,browserCleanup:false,budgetHeld:true,expectedVerifierFailure:false};
  this.ctx.storage.transactionSync(()=>{if(this.read())throw Error('Fixed batch already captured');this.save(row);});
  const spend=new ManagedSpendLedger(this.ctx.storage),funded=spend.reserve({resourceKind:'native-optional',runId:`c02-native-${scope.attemptId}`,accountKey:'c02-private-operator',usdMicros:reservation.nativeUsdMicros,maxInputBytes:1,maxOutputTokens:1,maxCalls:1,maxContainerSeconds:120},{accountUsdMicros:reservation.totalUsdMicros,globalUsdMicros:reservation.totalUsdMicros});if(!funded.allowed)throw Error('Canary native reservation unavailable');spend.consume(`c02-native-${scope.attemptId}`,0,0,120);this.assert(row);row={...row,phase:'native_possible'};this.save(row);
  const namespace=this.env.UNTRUSTED_EXECUTION;if(!namespace)throw Error('Dedicated untrusted namespace unavailable');const job=namespace.getByName(await untrustedExecutionName(scope,source.digest));await job.prepare(scope,source,c02CanaryFixtureFiles(),pinned);const output=await job.run(scope,source,c02CanaryFixtureFiles());const receipt=await job.outputReceipt(scope,source.digest);if(!receipt||receipt.cleanup!=='confirmed'||receipt.image!==pinned||receipt.sourceDigest!==source.digest||JSON.stringify(receipt.scope)!==JSON.stringify(scope)||receipt.manifest.digest!==output.manifest.digest)throw Error('Native output and shutdown unconfirmed');this.assert(row);row={...row,phase:'native_confirmed',output:output.manifest,nativeCleanup:true};this.save(row);
  const browserBudget=this.browserBudget(row);
  const browserScope=(leaseId:string)=>this.browserScope(row,leaseId);
  const transport=new BudgetedBrowserTransportRouter({binding:this.env.BROWSER,sessionControl:this.env.BROWSER,maxLeases:1,deriveScope:async leaseId=>{this.assert(row);return browserScope(leaseId);},retainBackground:work=>this.ctx.waitUntil(work),budget:{admitVerificationBrowser:proposed=>browserBudget.admit(proposed),beginVerificationBrowserAcquire:proposed=>browserBudget.beginAcquire(proposed),recordVerificationBrowserAcquired:async(proposed,id)=>browserBudget.recordAcquired(proposed,id),beforeVerificationBrowserWork:proposed=>browserBudget.beforeWork(proposed),closeVerificationBrowser:proposed=>browserBudget.close(proposed)},sdk:{acquire:(binding,options)=>cloudflareBrowserSdk.acquire(binding,options),connect:async(binding,id)=>{const browser=await cloudflareBrowserSdk.connect(binding,id);try{if(!browser.version)throw Error("Native browser version unavailable");const nativeVersion=z.string().max(256).parse(await browser.version());const live=this.read();if(!live)throw Error("Original canary context unavailable");this.assert(live);row={...live,browserVersion:nativeVersion};this.save(row);return browser;}catch(error){await browser.close().catch(()=>{});throw error;}}}});
  row={...row,phase:'browser_possible'};this.save(row);let verificationRefused=false;
  try{await verifyExternalBrowser({onExpectedFailure:async failure=>{const live=this.read();if(failure.caseId!==policy.cases[0]!.id||!live||live.observedDom!=='Blocked'||JSON.stringify(live.scope)!==JSON.stringify(scope))throw Error('Original trusted failure event differs');this.assert(live);row={...live,expectedVerifierFailure:true};this.save(row);},scope,source,sourceFiles:c02CanaryFixtureFiles(),output:output.manifest,outputFiles:output.files,policy,transport:{allocate:async options=>{row={...row,browserLeaseId:options.leaseId,browserScope:browserScope(options.leaseId)};this.save(row);await transport.allocate(options);},act:(id,action,signal)=>transport.act(id,action,signal),observe:async(id,query,signal)=>{const observed=await transport.observe(id,query,signal);if(query.kind==='text'&&query.selector==='h1'&&typeof observed==='string'){const live=this.read();if(!live)throw Error("Original canary context unavailable");this.assert(live);row={...live,observedDom:observed.slice(0,256)};this.save(row);}return observed;},close:(id)=>transport.close(id)},authorize:async()=>this.assert(row),budget:async()=>this.assert(row)});}catch(error){verificationRefused=c02ExpectedBrowserRefusal(error);if(verificationRefused){const live=this.read();if(live&&JSON.stringify(live.scope)===JSON.stringify(scope)){row={...live,expectedVerifierFailure:true};this.save(row);}}}
  const lease=row.browserLeaseId?browserBudget.get(row.browserLeaseId):null;const exactClosure=lease?.phase==='closed'&&lease.sessionId!==null&&lease.closure?.sessionId===lease.sessionId;if(exactClosure){const live=this.read();if(!live||JSON.stringify(live.scope)!==JSON.stringify(scope))throw Error('Original canary cleanup context unavailable');row={...live,browserCleanup:true};this.save(row);}const final=this.read();if(final?.expectedVerifierFailure===true&&final.observedDom==='Blocked'&&final.nativeCleanup&&final.browserCleanup&&exactClosure){row={...final,phase:'complete',budgetHeld:true};this.save(row);}return this.status();
 }
}
export class C02ExecutionAuthority extends WorkerEntrypoint<C02CanaryEnvironment>{override fetch(request:Request){return executionAuthorityResponse(request,context=>this.env.CANARY.getByName(singleton).allow(context));}}
export class C02DenyEgress extends WorkerEntrypoint<C02CanaryEnvironment>{override async fetch(request:Request){let scheme='other';try{scheme=new URL(request.url).protocol;}catch{/* No raw URL storage. */}await this.env.CANARY.getByName(singleton).deny(scheme);return new Response('Denied',{status:403,headers:{'Cache-Control':'no-store'}});}}
export default{async fetch(request:Request,env:C02CanaryEnvironment):Promise<Response>{const url=new URL(request.url);if(url.protocol!=="https:")return new Response('HTTPS required',{status:400});if(!c02OperatorAuthorized(request,env.C02_OPERATOR_SECRET))return new Response('Unauthorized',{status:401});if(request.method==='GET'&&url.pathname==='/health')return Response.json({ready:false,executionEnabled:env.C02_ENABLED==='true',imageConfigured:image.safeParse(env.C02_IMAGE).success,sourceVersionConfigured:sourceVersion.safeParse(env.C02_SOURCE_VERSION).success});if(request.method==='GET'&&url.pathname==='/manifest')return Response.json(c02CanaryManifest());if(request.method==='GET'&&url.pathname==='/batch')return Response.json(await env.CANARY.getByName(singleton).status());if(request.method==='POST'&&url.pathname==='/batch/cleanup'){try{return Response.json(await env.CANARY.getByName(singleton).cleanup(await fixedRequestId(request)));}catch{return Response.json({status:'unconfirmed',recovery:'Only original recorded resources can be inspected or closed.'},{status:409});}}if(request.method==='POST'&&url.pathname==='/batch'){if(env.C02_ENABLED!=='true')return new Response('Canary execution disabled',{status:409});if(Number(request.headers.get('Content-Length')??0)>256)return new Response('Request too large',{status:413});try{const requestId=await fixedRequestId(request);return Response.json(await env.CANARY.getByName(singleton).run(requestId));}catch{return Response.json({status:'unconfirmed',recovery:'Inspect the original batch; no automatic rerun.'},{status:409});}}return new Response('Not found',{status:404});}} satisfies ExportedHandler<C02CanaryEnvironment>;
