import {z} from 'zod';
import {ContainerLifetime} from './container-lifetime';
import {c02BoundaryPlanSchema,prepareC02BoundaryInputs,C02_BOUNDARY_SETUP_PROGRAM,C02_BOUNDARY_ATTACK_PROGRAM,C02_BOUNDARY_INSPECT_PROGRAM,type C02BoundaryPlan} from './c02-boundary-programs';
type Storage=Pick<DurableObjectStorage,'sql'|'transactionSync'|'setAlarm'|'deleteAlarm'>;
type Native=Pick<Container,'running'|'start'|'exec'|'destroy'|'inspect'|'interceptAllOutboundHttp'|'interceptOutboundHttps'>;
type CommandKind='setup'|'inspect-initial'|'attacker'|'inspect-b'|'inspect-final';
export interface C02BoundaryCommand{commandId:string;kind:CommandKind;source:'trusted-fixed-command'|'untrusted-native-stdout';settled:boolean;exitCode:number|null;settledAt:number|null;output:string|null}
export interface C02BoundaryStartupAudit{launchId:string;environmentDigest:string;syntheticCredentialTransmitted:boolean;issuedAt:number;returnedAt:number|null}
export interface C02BoundaryRuntimeState{startup:C02BoundaryStartupAudit|null;plan:C02BoundaryPlan;role:'task-a'|'task-b';image:string;phase:'prepared'|'dispatched'|'ready'|'inspected'|'held'|'stopped';commands:C02BoundaryCommand[];nativeStopped:boolean;inspectedAt:number|null}
/** One role, one actual VM. Only fixed programs may run; attacker bytes are
 * explicitly diagnostic and never promoted to trusted inspection evidence. */
export class C02BoundaryRuntime{
 constructor(private readonly storage:Storage,private readonly container:()=>Native|undefined,private readonly interceptor:Fetcher|undefined,private readonly instanceId:string,private readonly role:'task-a'|'task-b',private readonly image:string,private readonly now=()=>Date.now()){
  z.enum(['task-a','task-b']).parse(role);z.string().regex(/^registry\.cloudflare\.com\/[a-f0-9]{32}\/[a-z0-9-]+@sha256:[a-f0-9]{64}$/).parse(image);storage.sql.exec('CREATE TABLE IF NOT EXISTS c02_boundary_runtime(id INTEGER PRIMARY KEY CHECK(id=1),doc TEXT NOT NULL)');
 }
 status():C02BoundaryRuntimeState|null{const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM c02_boundary_runtime WHERE id=1').toArray()[0];return row?JSON.parse(row.doc) as C02BoundaryRuntimeState:null;}
 private save(state:C02BoundaryRuntimeState){this.storage.sql.exec('INSERT INTO c02_boundary_runtime VALUES(1,?) ON CONFLICT(id) DO UPDATE SET doc=excluded.doc',JSON.stringify(state));}
 private lifetime(){return new ContainerLifetime(this.storage,this.container,120000,this.now);}
 async prepare(input:C02BoundaryPlan){const plan=c02BoundaryPlanSchema.parse(structuredClone(input));await prepareC02BoundaryInputs(plan,this.now());const scope=this.role==='task-a'?plan.taskA:plan.taskB;if(scope.instanceId!==this.instanceId)throw Error('Boundary registered instance differs');const state:C02BoundaryRuntimeState={startup:null,plan,role:this.role,image:this.image,phase:'prepared',commands:[],nativeStopped:false,inspectedAt:null};this.storage.transactionSync(()=>{const prior=this.status();if(prior){if(JSON.stringify(prior)!==JSON.stringify(state))throw Error('Boundary attempt differs or consumed');return;}this.save(state);});}
 private allowed(signal:AbortSignal){signal.throwIfAborted();this.lifetime().assertWorkAllowed();const state=this.status();if(!state||state.phase!=='dispatched'||state.plan.deadlineAt<=this.now()||state.image!==this.image||state.role!==this.role)throw Error('Boundary attempt sealed');}
 private async bounded<T>(operation:()=>Promise<T>,signal:AbortSignal){signal.throwIfAborted();let abort=()=>{};try{return await Promise.race([operation(),new Promise<never>((_,reject)=>{abort=()=>reject(Error('Boundary execution deadline'));signal.addEventListener('abort',abort,{once:true});})]);}finally{signal.removeEventListener('abort',abort);}}
 private async read(stream:ReadableStream|null,signal:AbortSignal){if(!stream)throw Error('Boundary command output unavailable');const reader=stream.getReader();let size=0;const chunks:Uint8Array[]=[];try{for(;;){const part=await this.bounded(()=>reader.read(),signal);if(part.done)break;size+=part.value.byteLength;if(size>8192)throw Error('Boundary command output exceeds bound');chunks.push(part.value);}const output=new Uint8Array(size);let offset=0;for(const part of chunks){output.set(part,offset);offset+=part.length;}return new TextDecoder('utf-8',{fatal:true}).decode(output);}catch(error){void reader.cancel().catch(()=>{});throw error;}}
 private async command(kind:CommandKind,program:string,input:unknown,signal:AbortSignal){this.allowed(signal);const active=this.status()!,live=await this.bounded(()=>this.container()!.inspect(),signal),scope=this.role==='task-a'?active.plan.taskA:active.plan.taskB;if(!live||!this.container()!.running||live.image!==active.image||live.labels.c02_request!==active.plan.requestId||live.labels.c02_task!==scope.taskId||live.labels.c02_launch!==active.startup?.launchId)throw Error('Original live boundary instance unavailable');this.allowed(signal);const state=this.status()!;if(state.commands.some(command=>command.kind===kind))throw Error('Boundary command consumed');const command:C02BoundaryCommand={commandId:crypto.randomUUID(),kind,source:kind==='attacker'?'untrusted-native-stdout':'trusted-fixed-command',settled:false,exitCode:null,settledAt:null,output:null};this.save({...state,commands:[...state.commands,command]});const process=await this.bounded(()=>this.container()!.exec(['/usr/local/bin/bun','-e',program],{stdin:new Response(JSON.stringify(input)).body!,stdout:'pipe',stderr:'ignore',signal,env:{CI:'1'}}),signal);
  const exit=this.bounded(()=>process.exitCode,signal).then(exitCode=>{if(!Number.isSafeInteger(exitCode))throw Error('Boundary native settlement invalid');const current=this.status()!;this.save({...current,commands:current.commands.map(item=>item.commandId===command.commandId?{...item,settled:true,exitCode,settledAt:this.now()}:item)});return exitCode;});
  const [output,exitCode]=await Promise.all([this.read(process.stdout,signal),exit]);const current=this.status()!;this.save({...current,commands:current.commands.map(item=>item.commandId===command.commandId?{...item,output}:item)});if(exitCode!==0)throw Error('Boundary native command failed');this.allowed(signal);
 }
 private begin(expected:'prepared'|'ready'){const state=this.status();if(!state||state.phase!==expected||state.role!==this.role||state.plan.deadlineAt<=this.now())throw Error('Boundary attempt unavailable or consumed');this.save({...state,phase:'dispatched'});return{state,signal:AbortSignal.timeout(Math.max(1,state.plan.deadlineAt-this.now()))};}
 private async start(signal:AbortSignal,environment:Record<string,string>){const container=this.container();if(!container||!this.interceptor)throw Error('Boundary native bindings unavailable');await this.bounded(()=>this.lifetime().beforeWork(),signal);await this.storage.setAlarm(this.status()!.plan.deadlineAt);this.allowed(signal);await this.bounded(()=>container.interceptAllOutboundHttp(this.interceptor!),signal);this.allowed(signal);await this.bounded(()=>container.interceptOutboundHttps('*',this.interceptor!),signal);this.allowed(signal);if(container.running||await this.bounded(()=>container.inspect(),signal)!==null)throw Error('Fresh boundary instance required');this.allowed(signal);const fixedEnvironment=Object.freeze({...environment}),bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(fixedEnvironment))),environmentDigest=Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,'0')).join('');this.allowed(signal);this.save({...this.status()!,startup:{launchId:crypto.randomUUID(),environmentDigest,syntheticCredentialTransmitted:Object.hasOwn(fixedEnvironment,'C02_SYNTHETIC_CREDENTIAL'),issuedAt:this.now(),returnedAt:null}});container.start({image:this.image,entrypoint:['sleep','infinity'],enableInternet:false,env:fixedEnvironment,labels:{c02_request:this.status()!.plan.requestId,c02_task:this.role==='task-a'?this.status()!.plan.taskA.taskId:this.status()!.plan.taskB.taskId,c02_launch:this.status()!.startup!.launchId}});this.save({...this.status()!,startup:{...this.status()!.startup!,returnedAt:this.now()}});this.allowed(signal);}
 async startA(){if(this.role!=='task-a')throw Error('Boundary role differs');const{state,signal}=this.begin('prepared');try{const input=await prepareC02BoundaryInputs(state.plan,this.now());await this.start(signal,{CI:'1',...input.setupEnvironment});await this.command('setup',C02_BOUNDARY_SETUP_PROGRAM,input.setup,signal);await this.command('inspect-initial',C02_BOUNDARY_INSPECT_PROGRAM,input.inspectA,signal);this.save({...this.status()!,phase:'ready'});return this.status()!;}catch(error){await this.stop();throw error;}}
 async runB(){if(this.role!=='task-b')throw Error('Boundary role differs');const{state,signal}=this.begin('prepared');try{const input=await prepareC02BoundaryInputs(state.plan,this.now());await this.start(signal,{CI:'1'});await this.command('attacker',C02_BOUNDARY_ATTACK_PROGRAM,input.attacker,signal);await this.command('inspect-b',C02_BOUNDARY_INSPECT_PROGRAM,input.inspectB,signal);this.save({...this.status()!,phase:'inspected'});}finally{await this.stop();}return this.status()!;}
 async inspectA(){if(this.role!=='task-a')throw Error('Boundary role differs');const{state,signal}=this.begin('ready');try{const input=await prepareC02BoundaryInputs(state.plan,this.now());await this.command('inspect-final',C02_BOUNDARY_INSPECT_PROGRAM,input.inspectA,signal);this.save({...this.status()!,phase:'inspected'});return this.status()!;}catch(error){await this.stop();throw error;}}
 async stop(){const state=this.status();if(!state)return null;this.save({...state,phase:'held'});const lifetime=this.lifetime();lifetime.seal();await lifetime.stop();const current=this.status()!,nativeStopped=lifetime.status()?.state==='stopped';this.save({...current,nativeStopped,inspectedAt:nativeStopped?this.now():null,phase:nativeStopped&&current.commands.every(command=>command.settled)?'stopped':'held'});return this.status();}
 async alarm(){const state=this.status();if(!state)return;if(this.now()<state.plan.deadlineAt&&['dispatched','ready'].includes(state.phase)){await this.storage.setAlarm(state.plan.deadlineAt);return;}await this.stop();}
}
