import {z} from 'zod';
import {c02BoundaryPlanSchema as runtimePlanSchema,c02BoundaryInspectionSchema,type C02BoundaryPlan as RuntimePlan} from './c02-boundary-programs';
import {type C02BoundaryRuntimeState,type C02BoundaryCommand} from './c02-boundary-runtime';
import {c02BoundaryPlanSchema,c02BoundaryEvidenceSchema,type C02BoundaryEvidence} from './c02-boundary-evidence';
export interface C02BoundaryAssemblyInput{plan:RuntimePlan;image:string;taskA:C02BoundaryRuntimeState;taskB:C02BoundaryRuntimeState;supervisor:{initialDigest:string;finalDigest:string;readAt:number};refusals:C02BoundaryEvidence['refusals'];inventory:C02BoundaryEvidence['inventory'];expectedInventoryDigest:string}
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,'0')).join('');}
/** Input states are read directly from the owned runtime and supervisor ledgers,
 * never an operator HTTP body. Parsing tags cannot authenticate their source. */
export async function assembleC02BoundaryEvidence(input:C02BoundaryAssemblyInput){
 const original=runtimePlanSchema.parse(input.plan),a=input.taskA,b=input.taskB;
 for(const[state,role]of [[a,'task-a'],[b,'task-b']] as const){if(JSON.stringify(state.plan)!==JSON.stringify(original)||state.role!==role||state.image!==input.image||state.phase!=='stopped'||!state.nativeStopped||state.inspectedAt===null)throw Error('Original stopped boundary runtime required');if(!state.startup||!z.uuid().safeParse(state.startup.launchId).success||state.startup.returnedAt===null||state.startup.returnedAt<state.startup.issuedAt)throw Error('Actual startup audit required');const expectedEnv=role==='task-a'?{CI:'1',C02_SYNTHETIC_CREDENTIAL:original.syntheticCredential}:{CI:'1'};if(state.startup.environmentDigest!==await hash(JSON.stringify(expectedEnv))||state.startup.syntheticCredentialTransmitted!==(role==='task-a'))throw Error('Native startup environment differs');}
 const command=(state:C02BoundaryRuntimeState,kind:C02BoundaryCommand['kind'])=>{const rows=state.commands.filter(value=>value.kind===kind);if(rows.length!==1)throw Error('Registered native command required');const value=rows[0]!;if(!value.settled||value.exitCode!==0||value.settledAt===null||value.source!==(kind==='attacker'?'untrusted-native-stdout':'trusted-fixed-command'))throw Error('Positive native command settlement required');return value;};
 const setup=command(a,'setup'),attack=command(b,'attacker');
 const inspect=(state:C02BoundaryRuntimeState,kind:C02BoundaryCommand['kind'],phase:'initial-a'|'final-a'|'final-b')=>{const actual=command(state,kind);if(!actual.output||actual.output.length>8192)throw Error('Trusted inspection output unavailable');const result=c02BoundaryInspectionSchema.parse(JSON.parse(actual.output)),scope=state.role==='task-a'?original.taskA:original.taskB;if(result.requestId!==original.requestId||result.instanceId!==scope.instanceId||result.taskId!==scope.taskId||result.role!==state.role||!result.satisfied)throw Error('Trusted inspection scope differs');const isA=state.role==='task-a';if(isA&&(result.taskMarker.state!=='present'||result.rootMarker.state!=='present'||result.credential.state!=='present')||!isA&&(result.taskMarker.state!=='absent'||result.rootMarker.state!=='absent'||result.credential.state!=='absent'))throw Error('Trusted marker inspection unavailable');return{source:'trusted-native-inspector' as const,scope,commandId:actual.commandId,phase,exitCode:0 as const,observedAt:actual.settledAt!,taskMarkerDigest:result.taskMarker.state==='present'?result.taskMarker.digest:null,rootMarkerDigest:result.rootMarker.state==='present'?result.rootMarker.digest:null,credentialDigest:result.credential.state==='present'?result.credential.digest:null,credentialPresent:result.credential.state==='present'};};
 const initial=inspect(a,'inspect-initial','initial-a'),final=inspect(a,'inspect-final','final-a'),lastB=inspect(b,'inspect-b','final-b');
 if(initial.rootMarkerDigest!==await hash(original.rootMarker+'\n')||final.rootMarkerDigest!==initial.rootMarkerDigest||initial.observedAt>attack.settledAt!||final.observedAt<attack.settledAt!)throw Error('Original A post-attack readback required');
 const plan=c02BoundaryPlanSchema.parse({requestId:original.requestId,taskA:original.taskA,taskB:original.taskB,taskAMarkerDigest:await hash(original.taskMarker+'\n'),supervisorMarkerDigest:input.supervisor.initialDigest,syntheticCredentialDigest:await hash(original.syntheticCredential),expectedInventoryDigest:input.expectedInventoryDigest,createdAt:original.createdAt,deadlineAt:original.deadlineAt});
 const evidence=c02BoundaryEvidenceSchema.parse({markers:[{source:'trusted-marker-store',owner:'task-a',initialDigest:initial.taskMarkerDigest,finalDigest:final.taskMarkerDigest,readAt:final.observedAt},{source:'trusted-marker-store',owner:'supervisor',...input.supervisor}],refusals:input.refusals,native:[{source:'native-container-api',scope:original.taskA,commandId:setup.commandId,exitCode:0,commandSettledAt:setup.settledAt,inspection:'absent',inspectedAt:a.inspectedAt},{source:'native-container-api',scope:original.taskB,commandId:attack.commandId,exitCode:0,commandSettledAt:attack.settledAt,inspection:'absent',inspectedAt:b.inspectedAt}],inspections:[initial,final,lastB],environments:[a,b].map(state=>({source:'trusted-worker-environment-audit',scope:state.role==='task-a'?original.taskA:original.taskB,approvedNativeEnvDigest:state.startup!.environmentDigest,syntheticCredentialDigest:plan.syntheticCredentialDigest,credentialValueTransmitted:state.startup!.syntheticCredentialTransmitted,observedAt:state.startup!.returnedAt})),inventory:input.inventory});
 return{plan,evidence};
}
