/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.c02-canary.jsonc --include-runtime=false --env-interface=C02CanaryBindings src/server/c02-canary-env.d.ts` (hash: 675c0f7fbc696c5ced14af335c8be499)
interface __BaseEnv_C02CanaryBindings {
	BROWSER: BrowserRun;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	C02_ENABLED: "false";
	C02_IMAGE: "";
	C02_SOURCE_VERSION: "";
	CANARY: DurableObjectNamespace<import("./c02-canary-worker").C02CanaryBatch>;
	UNTRUSTED_EXECUTION: DurableObjectNamespace<import("./c02-canary-worker").UntrustedExecutionSandbox>;
	EXECUTION_AUTHORITY: Service<typeof import("./c02-canary-worker").C02ExecutionAuthority>;
	UNTRUSTED_EGRESS: Service<typeof import("./c02-canary-worker").C02DenyEgress>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./c02-canary-worker");
		durableNamespaces: "C02CanaryBatch" | "UntrustedExecutionSandbox";
	}
	interface Env extends __BaseEnv_C02CanaryBindings {}
}
interface C02CanaryBindings extends __BaseEnv_C02CanaryBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "C02_ENABLED" | "C02_IMAGE" | "C02_SOURCE_VERSION">> {}
}

// Keep this standalone worker's generated ambient names local to its module.
export type { C02CanaryBindings };
