import {DurableObject} from 'cloudflare:workers';
import {z} from 'zod';
import {c02BoundaryNativeNames,type C02BoundaryNativeEnvironment} from './c02-boundary-native';
import {C02BoundarySupervisorLedger,c02BoundaryTrustedPolicy,type C02BoundaryCallbackProps} from './c02-boundary-supervisor';
import {type C02BoundaryPlan as ProgramPlan} from './c02-boundary-programs';
import {deriveC02BoundaryEvidence,type C02BoundaryEvidence,type C02BoundaryPlan as EvidencePlan} from './c02-boundary-evidence';
import type {C02BoundaryRuntimeState} from './c02-boundary-runtime';
import {assembleC02BoundaryEvidence} from './c02-boundary-assembly';
import {refuseC02BoundaryInventory} from './c02-boundary-inventory';
import {CloudflareBrowserTransport} from './cloudflare-browser-transport';
import {bindBrowserPolicy,type BrowserPolicy} from './external-browser-verifier';
import {bindBuildManifest,type StaticBuildScope} from './static-build-artifact';
import {ManagedSpendLedger} from './managed-spend-ledger';
export interface C02BoundaryBatchEnvironment extends C02BoundaryNativeEnvironment {
 BROWSER:BrowserRun;
 C02_SOURCE_VERSION:string;
 CF_VERSION_METADATA:WorkerVersionMetadata;
}
interface Snapshot {supervisorMarkerDigest:string;expectedInventoryDigest:string;publicationDigest:string;readAt:number}
interface BoundaryRow {
 requestId:string;programPlan:ProgramPlan;supervisorMarker:string;image:string;sourceVersion:string;workerVersion:string;
 phase:'prepared'|'a_possible'|'a_ready'|'b_possible'|'inspection_possible'|'held'|'complete';
 initial:Snapshot|null;final:Snapshot|null;a:C02BoundaryRuntimeState|null;b:C02BoundaryRuntimeState|null;
 inventory:C02BoundaryEvidence['inventory'];assembled:{plan:EvidencePlan;evidence:C02BoundaryEvidence}|null;
 inventoryAttemptId:string;inventoryIncarnation:string;failureStage?:BoundaryRow['phase'];
}
const image=z.string().regex(/^registry\.cloudflare\.com\/[a-f0-9]{32}\/[a-z0-9-]+@sha256:[a-f0-9]{64}$/),sha=z.string().regex(/^[a-f0-9]{40}$/);
function marker(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),byte=>byte.toString(16).padStart(2,'0')).join('');}
async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,'0')).join('');}
async function bounded<T>(work:Promise<T>,deadline:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([work,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Boundary provider deadline')),Math.max(1,deadline-Date.now()));})]);}finally{clearTimeout(timer);}}
/** Dedicated owned canary controller. No repository/publisher credentials. */
export class C02BoundaryBatch extends DurableObject<C02BoundaryBatchEnvironment>{
 private read():BoundaryRow|null{this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS c02_boundary_batch(id INTEGER PRIMARY KEY CHECK(id=1),doc TEXT NOT NULL)');const row=this.ctx.storage.sql.exec<{doc:string}>('SELECT doc FROM c02_boundary_batch WHERE id=1').toArray()[0];return row?JSON.parse(row.doc) as BoundaryRow:null;}
 private save(row:BoundaryRow){this.ctx.storage.sql.exec('INSERT INTO c02_boundary_batch VALUES(1,?) ON CONFLICT(id) DO UPDATE SET doc=excluded.doc',JSON.stringify(row));}
 private ledger(){return new C02BoundarySupervisorLedger(this.ctx.storage);}
 private jobs(row:BoundaryRow){const ns=this.env.BOUNDARY_NATIVE;if(!ns||ns.idFromName(c02BoundaryNativeNames.taskA).toString()!==row.programPlan.taskA.instanceId||ns.idFromName(c02BoundaryNativeNames.taskB).toString()!==row.programPlan.taskB.instanceId)throw Error('Original boundary namespace unavailable');return{a:ns.getByName(c02BoundaryNativeNames.taskA),b:ns.getByName(c02BoundaryNativeNames.taskB)};}
 private assert(row:BoundaryRow){const current=this.read();if(!current||current.phase==='held'||current.phase==='complete'||current.requestId!==row.requestId||JSON.stringify(current.programPlan)!==JSON.stringify(row.programPlan)||this.env.C02_BOUNDARY_ENABLED!=='true'||this.env.C02_BOUNDARY_IMAGE!==row.image||this.env.C02_SOURCE_VERSION!==row.sourceVersion||this.env.CF_VERSION_METADATA.id!==row.workerVersion||Date.now()>=row.programPlan.deadlineAt)throw Error('Boundary authority unavailable');}
 status(){const row=this.read();return{batch:row?{requestId:row.requestId,phase:row.phase,failureStage:row.failureStage??null,taskA:row.programPlan.taskA,taskB:row.programPlan.taskB,deadlineAt:row.programPlan.deadlineAt,sourceVersion:row.sourceVersion,workerVersion:row.workerVersion,image:row.image,nativeCleanupA:row.a?.nativeStopped??false,nativeCleanupB:row.b?.nativeStopped??false,commandIdsA:row.a?.commands.map(command=>({commandId:command.commandId,kind:command.kind,source:command.source,settled:command.settled,exitCode:command.exitCode}))??[],commandIdsB:row.b?.commands.map(command=>({commandId:command.commandId,kind:command.kind,source:command.source,settled:command.settled,exitCode:command.exitCode}))??[],results:row.assembled?deriveC02BoundaryEvidence(row.assembled.plan,row.assembled.evidence):null,evidence:row.assembled}:null,syntheticCanaries:true,productionGitEvidence:false,acceptanceEvidence:false};}
 async start(requestId:string){z.uuid().parse(requestId);if(this.env.C02_BOUNDARY_ENABLED!=='true'||!this.env.BOUNDARY_NATIVE)throw Error('Boundary disabled/unconfigured');const old=this.read();if(old){if(old.requestId!==requestId)throw Error('Fixed boundary batch consumed');return this.status();}const ns=this.env.BOUNDARY_NATIVE,createdAt=Date.now();
  const programPlan:ProgramPlan={requestId,taskA:{taskId:crypto.randomUUID(),instanceId:ns.idFromName(c02BoundaryNativeNames.taskA).toString()},taskB:{taskId:crypto.randomUUID(),instanceId:ns.idFromName(c02BoundaryNativeNames.taskB).toString()},createdAt,deadlineAt:createdAt+120000,taskMarker:marker(),rootMarker:marker(),syntheticCredential:marker(),tamperMarker:marker(),actionNonces:{supervisor:marker(),foreignTask:marker(),credentialAction:marker()}};
  const row:BoundaryRow={requestId,programPlan,supervisorMarker:marker(),image:image.parse(this.env.C02_BOUNDARY_IMAGE),sourceVersion:sha.parse(this.env.C02_SOURCE_VERSION),workerVersion:this.env.CF_VERSION_METADATA.id,phase:'prepared',initial:null,final:null,a:null,b:null,inventory:null,assembled:null,inventoryAttemptId:crypto.randomUUID(),inventoryIncarnation:crypto.randomUUID()};
  this.ctx.storage.transactionSync(()=>{if(this.read())throw Error('Boundary already captured');const spend=new ManagedSpendLedger(this.ctx.storage);const admission=spend.reserve({resourceKind:'native-optional',runId:'c02-boundary-'+requestId,accountKey:'c02-private-operator',usdMicros:86016,maxInputBytes:1,maxOutputTokens:1,maxCalls:1,maxContainerSeconds:240},{accountUsdMicros:86016,globalUsdMicros:86016});if(!admission.allowed)throw Error('Boundary reservation unavailable');spend.consume('c02-boundary-'+requestId,0,0,240);this.save(row);});const actual=this.execute(row);this.ctx.waitUntil(actual.catch(()=>undefined));return this.status();
 }
 async recordNativeRefusal(props:C02BoundaryCallbackProps,url:string,method:string){const row=this.read();if(!row||row.phase!=='b_possible')return false;this.assert(row);return this.ledger().refuse(props,new Request(url,{method}))!==null;}
 private async inventory(row:BoundaryRow,b:C02BoundaryRuntimeState){const attack=b.commands.find(command=>command.kind==='attacker'&&command.source==='untrusted-native-stdout'&&command.settled&&command.exitCode===0);if(!attack?.output)throw Error('Original attacker output unavailable');const submitted=z.object({policy:z.unknown()}).passthrough().parse(JSON.parse(attack.output));const policy=c02BoundaryTrustedPolicy(),bound=await bindBrowserPolicy(policy),html='<h1>Trusted boundary</h1>',scope:StaticBuildScope={attemptId:row.inventoryAttemptId,projectId:'c02boundaryfx',incarnation:row.inventoryIncarnation,commit:(await digest('owned-synthetic-source:'+html)).slice(0,40),tree:(await digest('owned-synthetic-tree:'+html)).slice(0,40),policyDigest:bound.digest};const files=[{path:'index.html',kind:'file' as const,bytes:new TextEncoder().encode(html)}],source=await bindBuildManifest('source',scope,files),output=await bindBuildManifest('static',scope,files,source.digest),expected={scope,sourceDigest:source.digest,buildDigest:output.digest,policyDigest:bound.digest,cases:policy.cases.map(item=>({id:item.id,assertions:item.assertions.length}))};const guards={expected:async()=>expected,authorize:async()=>this.assert(row),assertCurrent:()=>this.assert(row)};
  const proof=await refuseC02BoundaryInventory({storage:this.ctx.storage,trusted:{scope,source,sourceFiles:files,output,outputFiles:files,policy,guards},submittedPolicy:submitted.policy as BrowserPolicy,transport:new CloudflareBrowserTransport({binding:this.env.BROWSER,authorize:async()=>this.assert(row),funding:async()=>{throw Error('Boundary inventory probe cannot allocate a browser');}})});if(!proof.receiptGuardRefused)throw Error('Production inventory guard unconfirmed');const refusal=await this.ledger().rejectAttackerInventory(row.programPlan.taskB,attack.commandId,attack.output);return{...refusal,receiptGuard:'TrustedBrowserReceipts.verifyAndRecord' as const,receiptGuardRefused:true as const,verifiedReceiptAbsent:true as const};
 }
 private async execute(original:BoundaryRow){let row=original;try{this.assert(row);await this.ledger().register(row.programPlan,row.supervisorMarker);this.assert(row);const initial=await this.ledger().trustedSnapshot();this.assert(row);row={...this.read()!,initial,phase:'a_possible'};this.save(row);const jobs=this.jobs(row);await bounded(jobs.a.prepare(row.programPlan,'task-a'),row.programPlan.deadlineAt);this.assert(row);const initialA=await bounded(jobs.a.startA(),row.programPlan.deadlineAt);this.assert(row);row={...this.read()!,a:initialA,phase:'a_ready'};this.save(row);
  await bounded(jobs.b.prepare(row.programPlan,'task-b'),row.programPlan.deadlineAt);this.assert(row);row={...this.read()!,phase:'b_possible'};this.save(row);const b=await bounded(jobs.b.runB(),row.programPlan.deadlineAt);this.assert(row);row={...this.read()!,b,phase:'inspection_possible'};this.save(row);const a=await bounded(jobs.a.inspectA(),row.programPlan.deadlineAt);this.assert(row);const inventory=await this.inventory(row,b);this.assert(row);const final=await this.ledger().trustedSnapshot();this.assert(row);row={...this.read()!,a,b,inventory,final};this.save(row);
 }catch{const current=this.read();if(current?.requestId===original.requestId)this.save({...current,failureStage:current.phase,phase:'held'});}finally{await this.cleanup(original.requestId);}}
 private async cleanup(requestId:string){const row=this.read();if(!row||row.requestId!==requestId)throw Error('Original boundary batch required');const jobs=this.jobs(row);let a=row.a,b=row.b;for(const [role,job] of [['a',jobs.a],['b',jobs.b]] as const){try{const stopped=await bounded(job.stop(),Date.now()+10000);if(role==='a')a=stopped;else b=stopped;}catch{/* Original unknown resource stays held; no execution retry. */}try{const state=await bounded(job.status(),Date.now()+10000);if(role==='a')a=state;else b=state;}catch{/* Never infer absence from a missing observation. */}}
  const current=this.read();if(!current||current.requestId!==requestId)throw Error('Boundary scope changed');let assembled=current.assembled;try{if(a&&b&&current.initial&&current.final&&current.inventory)assembled=await assembleC02BoundaryEvidence({plan:current.programPlan,image:current.image,taskA:a,taskB:b,supervisor:{initialDigest:current.initial.supervisorMarkerDigest,finalDigest:current.final.supervisorMarkerDigest,readAt:current.final.readAt},refusals:this.ledger().refusals(),inventory:current.inventory,expectedInventoryDigest:current.initial.expectedInventoryDigest});}catch{/* Invalid observations remain unconfirmed. */}const complete=assembled&&Object.values(deriveC02BoundaryEvidence(assembled.plan,assembled.evidence)).every(value=>value==='proven');this.save({...current,a,b,assembled,phase:complete?'complete':'held'});return this.status();
 }
 async recover(requestId:string){z.uuid().parse(requestId);const row=this.read();if(!row||row.requestId!==requestId)throw Error('Original boundary batch required');this.save({...row,phase:'held'});return this.cleanup(requestId);}
}
