import {z} from 'zod';
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>value!=='0'.repeat(40));
export const c03PublicationScopeSchema=z.object({caseId:z.uuid(),projectId:z.string().regex(/^[a-z0-9]{12,16}$/),incarnation:z.uuid(),candidateId:z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),ref:z.string().regex(/^refs\/heads\/[A-Za-z0-9][A-Za-z0-9_/-]*$/).refine(value=>!value.includes('..')&&!value.endsWith('/')&&!value.includes('//')),commit:sha,tree:sha,workerVersion:z.uuid(),sourceVersion:sha}).strict();
export type C03PublicationScope=z.infer<typeof c03PublicationScopeSchema>;
const checkpoint=z.enum(['before-ref-update','after-ref-update']);
type Point=z.infer<typeof checkpoint>;
interface State{scope:C03PublicationScope;invocationId:string;requestId:string;phase:'registered'|'dispatched'|'held'|'resumed'|'cancelled';reached:Point[];pauseAt:Point;resumeRequestId:string|null}
export interface C03CheckpointSql{transactionSync<T>(operation:()=>T):T;exec(query:string,...bindings:(string|number|null)[]):{toArray():{doc:string}[]}}
/** Private orchestration only. Reached means a trusted publisher callback ran;
 * it never proves the repository ref landed. Readback remains independent. */
export class C03PublicationCheckpoints{
 constructor(private readonly sql:C03CheckpointSql){sql.exec('CREATE TABLE IF NOT EXISTS c03_checkpoints(id INTEGER PRIMARY KEY CHECK(id=1),doc TEXT NOT NULL)');}
 private read():State|null{const row=this.sql.exec('SELECT doc FROM c03_checkpoints WHERE id=1').toArray()[0];return row?JSON.parse(row.doc) as State:null;}
 private save(state:State){this.sql.exec('INSERT INTO c03_checkpoints VALUES(1,?) ON CONFLICT(id) DO UPDATE SET doc=excluded.doc',JSON.stringify(state));}
 private exact(scope:C03PublicationScope,invocationId:string,requestId:string){const state=this.read();if(!state||JSON.stringify(state.scope)!==JSON.stringify(c03PublicationScopeSchema.parse(scope))||state.invocationId!==z.uuid().parse(invocationId)||state.requestId!==z.uuid().parse(requestId))throw Error('Original publication checkpoint context required');return state;}
 register(scope:C03PublicationScope,invocationId:string,requestId:string,pauseAt:Point){const state:State={scope:c03PublicationScopeSchema.parse(scope),invocationId:z.uuid().parse(invocationId),requestId:z.uuid().parse(requestId),pauseAt:checkpoint.parse(pauseAt),phase:'registered',reached:[],resumeRequestId:null};return this.sql.transactionSync(()=>{const prior=this.read();if(prior){if(JSON.stringify(prior.scope)!==JSON.stringify(state.scope)||prior.invocationId!==invocationId||prior.requestId!==requestId||prior.pauseAt!==pauseAt)throw Error('Checkpoint registration differs');return structuredClone(prior);}this.save(state);return structuredClone(state);});}
 dispatch(scope:C03PublicationScope,invocationId:string,requestId:string){return this.sql.transactionSync(()=>{const state=this.exact(scope,invocationId,requestId);if(state.phase!=='registered')throw Error('Publication dispatch consumed or unknown');state.phase='dispatched';this.save(state);return structuredClone(state);});}
 reached(scope:C03PublicationScope,invocationId:string,requestId:string,point:Point){return this.sql.transactionSync(()=>{const state=this.exact(scope,invocationId,requestId);checkpoint.parse(point);if(state.reached.includes(point))return{duplicate:true,pause:state.phase==='held'};if(state.phase==='cancelled'||state.phase==='registered')throw Error('Publication callback unavailable');if(point==='after-ref-update'&&!state.reached.includes('before-ref-update'))throw Error('Publication callback order differs');if(state.phase==='held')throw Error('Original checkpoint awaits explicit resume');state.reached.push(point);const pause=point===state.pauseAt&&state.resumeRequestId===null;if(pause)state.phase='held';this.save(state);return{duplicate:false,pause};});}
 resume(scope:C03PublicationScope,invocationId:string,requestId:string,resumeRequestId:string){return this.sql.transactionSync(()=>{const state=this.exact(scope,invocationId,requestId);z.uuid().parse(resumeRequestId);if(state.resumeRequestId){if(state.resumeRequestId!==resumeRequestId)throw Error('Resume request differs');return{duplicate:true};}if(state.phase!=='held')throw Error('Original reached checkpoint required');state.resumeRequestId=resumeRequestId;state.phase='resumed';this.save(state);return{duplicate:false};});}
 cancelUndispatched(scope:C03PublicationScope,invocationId:string,requestId:string){return this.sql.transactionSync(()=>{const state=this.exact(scope,invocationId,requestId);if(state.phase==='cancelled')return{duplicate:true};if(state.phase!=='registered'||state.reached.length)throw Error('Dispatched outcome requires readback; cancellation forbidden');state.phase='cancelled';this.save(state);return{duplicate:false};});}
 status(){return structuredClone(this.read());}
}
