import { z } from "zod";
import { safeSearchText } from "./metadata-search.js";
import type {Env} from "./env.js";
import {accountOf,globalOf,projectOf} from "./projects.js";
import {discoveredProfile,peopleQuerySchema,followInputSchema,discoveryInputSchema,type PeopleRegistration,type FollowingRecord} from "./community-people.js";
const response=(value:unknown,status=200)=>Response.json(value,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
async function target(env:Env,handle:string){const registry=globalOf(env),key=await registry.accountForHandle(handle);if(!key)return null;const account=accountOf(env,key);if(await registry.accountForHandle(handle)!==key)return null;const snapshot=await account.peopleSnapshot(),registration:PeopleRegistration={accountKey:key,handle,version:snapshot.discovery.version,publicationVersion:snapshot.discovery.publicationVersion,enabled:true};const profile=discoveredProfile(registration,snapshot);if(!profile||!snapshot.profile.ownerId)return null;return {key,profile,snapshot,registration,owner:snapshot.profile.ownerId};}
export async function publicPeople(env:Env,url:URL){const query=peopleQuerySchema.safeParse(Object.fromEntries(url.searchParams));if(!query.success||[...url.searchParams.keys()].some(key=>url.searchParams.getAll(key).length!==1))return response({error:"Invalid people query"},400);try{const page=await globalOf(env).peoplePage(query.data.cursor),people=[];let incomplete=false;for(const registration of page.rows){try{const account=accountOf(env,registration.accountKey),profile=discoveredProfile(registration,await account.peopleSnapshot());if(!profile)continue;if(!`${profile.handle} ${profile.displayName} ${profile.bio}`.toLowerCase().includes(query.data.q.toLowerCase()))continue;const registered=await globalOf(env).accountForHandle(profile.handle)===registration.accountKey;const final=discoveredProfile(registration,await account.peopleSnapshot());if(!registered||!final||JSON.stringify(final)!==JSON.stringify(profile)){incomplete=true;continue;}people.push({...profile,href:`/#/profile/${profile.handle}`});}catch{incomplete=true;}}return response({people,nextCursor:page.nextCursor,incomplete,checked:page.rows.length,scope:"Up to 20 explicitly discoverable public profiles on this page"});}catch{return response({people:[],nextCursor:null,incomplete:true,checked:0},503);}}
async function privatePeopleUnchecked(input:{env:Env;url:URL;accountKey:string;userId:string;viaToken:boolean;method:string;body():Promise<unknown>}){
 const {env,url,accountKey,userId}=input,path=url.pathname.slice(4);
 const account=accountOf(env,accountKey);
 if(path==="/profile/discovery"){
  if(input.viaToken)return response({error:"Manage profile discovery from the web app"},403);
  if(!["GET","PUT"].includes(requestMethod(input)))return response({error:"Not found"},404);
  let state=requestMethod(input)==="PUT"?await account.configureDiscovery(discoveryInputSchema.parse(await input.body()),userId):(await account.peopleSnapshot()).discovery;
  if(state.delivery==="pending"&&state.handle){try{await globalOf(env).registerPerson({accountKey,handle:state.handle,version:state.version,publicationVersion:state.publicationVersion,enabled:state.enabled});await account.deliveredDiscovery(state.version);state=(await account.peopleSnapshot()).discovery;}catch{/* Durable pending state is retryable by rereading settings. */}}
  const snapshot=await account.peopleSnapshot();return response({enabled:state.enabled,version:state.version,delivery:state.delivery,outdated:state.enabled&&(state.publicationVersion!==snapshot.profile.version||state.handle!==snapshot.profile.profile.handle||snapshot.profile.visibility!=="public"||snapshot.profile.moderation?.suppressed===true||!snapshot.active)});
 }
 const follow=/^\/following\/([a-z0-9](?:[a-z0-9-]{0,37}[a-z0-9])?)$/.exec(path);
 if(follow){
  if(input.viaToken)return response({error:"Manage following from the web app"},403);
  const saved=await account.followingForHandle(follow[1]!);
  if(requestMethod(input)==="PUT"){
    const value=followInputSchema.parse(await input.body());
    const replay=await account.replayFollowing(follow[1]!,value);if(replay)return response({following:replay.record.following,version:replay.record.version,replayed:true});
    if(!value.following&&saved){const receipt=await account.setFollowing({accountKey:saved.targetAccount,ownerId:saved.targetOwner,handle:saved.handle},value);return response({following:receipt.record.following,version:receipt.record.version,replayed:receipt.replayed});}
    const selected=await target(env,follow[1]!);if(!selected)return response({error:"Public person unavailable"},404);
    if(selected.key===accountKey)return response({error:"You cannot follow yourself"},400);
    if(saved&&(saved.targetAccount!==selected.key||saved.targetOwner!==selected.owner))return response({error:"This handle now belongs to another person. Remove the saved follow first."},409);
    const current=await target(env,follow[1]!);if(!current||current.key!==selected.key||current.owner!==selected.owner||current.profile.version!==selected.profile.version)return response({error:"Person publication changed; refresh"},409);
    const receipt=await account.setFollowing({accountKey:selected.key,ownerId:selected.owner,handle:selected.profile.handle},value),now=await account.followingRecord(selected.key);return response({following:now?.following??false,version:now?.version??0,replayed:receipt.replayed});
  }
  if(requestMethod(input)!=="GET")return response({error:"Not found"},404);
  const selected=await target(env,follow[1]!);
  if(saved&&(!selected||saved.targetAccount!==selected.key||saved.targetOwner!==selected.owner))return response({following:true,version:saved.version,canFollow:false,person:null,unavailable:true});
  if(!selected)return response({error:"Public person unavailable"},404);
  const old=await account.followingRecord(selected.key),fresh=await target(env,follow[1]!);if(!fresh||fresh.key!==selected.key||fresh.owner!==selected.owner||fresh.profile.version!==selected.profile.version)return response({following:old?.following??false,version:old?.version??0,canFollow:false,person:null,unavailable:true});return response({following:old?.following??false,version:old?.version??0,canFollow:selected.key!==accountKey,person:{...fresh.profile,href:`/#/profile/${fresh.profile.handle}`}});
 }

 if(path!=="/following"&&path!=="/community/following-activity")return null;
 if(requestMethod(input)!=="GET"||input.viaToken)return response({error:"Open following from the web app"},403);
 const query=peopleQuerySchema.safeParse(Object.fromEntries(url.searchParams));if(!query.success||query.data.q||[...url.searchParams.keys()].some(key=>url.searchParams.getAll(key).length!==1))return response({error:"Invalid following query"},400);
 const page=await account.followingPage(query.data.cursor);let incomplete=false;const following=[];const items:Array<{kind:"accepted-contribution";actor:{handle:string;displayName:string;href:string};repository:{id:string;name:string;href:string};commit:string;acceptedAt:string;href:string}>=[];
 for(const relation of page.rows){try{const selected=await target(env,relation.handle);if(!selected||selected.key!==relation.targetAccount||selected.owner!==relation.targetOwner){incomplete=true;if(path==="/following"&&sameFollowing(await account.followingRecord(relation.targetAccount),relation))following.push({handle:relation.handle,displayName:relation.handle,bio:"",version:0,href:`/#/profile/${relation.handle}`,relationshipVersion:relation.version,unavailable:true});continue;}if(path==="/following"){const fresh=await target(env,relation.handle),current=await account.followingRecord(relation.targetAccount);if(!fresh||fresh.key!==selected.key||fresh.owner!==selected.owner||fresh.profile.version!==selected.profile.version||!sameFollowing(current,relation)){incomplete=true;continue;}const final=await target(env,relation.handle);if(!final||final.key!==selected.key||final.owner!==selected.owner||final.profile.version!==selected.profile.version){incomplete=true;continue;}following.push({...final.profile,href:`/#/profile/${final.profile.handle}`,relationshipVersion:relation.version});continue;}
 const references=await accountOf(env,selected.key).publicActivityProjects();
 const pending:typeof items=[];const observed=new Map<string,string>();
 for(const reference of references){const repository=projectOf(env,reference.id),snapshot=await repository.publicAcceptedActivity(selected.owner);if(!snapshot.grant||!snapshot.directory.enabled)continue;const current=await repository.publicAcceptedActivity(selected.owner);if(JSON.stringify(current)!==JSON.stringify(snapshot)){incomplete=true;continue;}observed.set(reference.id,JSON.stringify(snapshot));for(const record of snapshot.contributions)pending.push({kind:"accepted-contribution",actor:{handle:selected.profile.handle,displayName:selected.profile.displayName,href:`/#/profile/${selected.profile.handle}`},repository:{id:reference.id,name:safeSearchText(snapshot.grant.name,160),href:`/#/public/${reference.id}`},commit:record.commit,acceptedAt:record.acceptedAt,href:`/#/public/${reference.id}?commit=${record.commit}`});}
 const fresh=await target(env,relation.handle),currentRelation=await account.followingRecord(relation.targetAccount);if(!fresh||fresh.key!==selected.key||fresh.owner!==selected.owner||fresh.profile.version!==selected.profile.version||!sameFollowing(currentRelation,relation)){incomplete=true;continue;}const verified:typeof items=[];for(const reference of references){if(!observed.has(reference.id))continue;const final=await projectOf(env,reference.id).publicAcceptedActivity(selected.owner);if(JSON.stringify(final)!==observed.get(reference.id)){incomplete=true;continue;}verified.push(...pending.filter(item=>item.repository.id===reference.id));}if(!sameFollowing(await account.followingRecord(relation.targetAccount),relation)){incomplete=true;continue;}const finalPerson=await target(env,relation.handle);if(!finalPerson||finalPerson.key!==selected.key||finalPerson.owner!==selected.owner||finalPerson.profile.version!==selected.profile.version||!sameFollowing(await account.followingRecord(relation.targetAccount),relation)){incomplete=true;continue;}items.push(...verified.sort((a,b)=>b.acceptedAt.localeCompare(a.acceptedAt)).slice(0,3));
 }catch{incomplete=true;}}
 return response(path==="/following"?{following,nextCursor:page.nextCursor,incomplete,checked:page.rows.length}:{items:items.sort((a,b)=>b.acceptedAt.localeCompare(a.acceptedAt)),nextCursor:page.nextCursor,incomplete,checked:page.rows.length,scope:"Up to 3 accepted human contribution records per followed person, from 3 currently listed public member repositories and their latest 100 acceptance records; up to 5 people on this page"});
}
function sameFollowing(current:FollowingRecord|null,old:FollowingRecord){return current?.following&&current.version===old.version&&current.targetOwner===old.targetOwner;}
function requestMethod(input:{method?:string}){return input.method??"GET";}

export async function privatePeople(input:Parameters<typeof privatePeopleUnchecked>[0]){try{return await privatePeopleUnchecked(input);}catch(error){if(error instanceof z.ZodError)return response({error:"Invalid social settings"},400);if(error instanceof Error&&/settings changed|Profile owner changed|Publish your profile|Following changed|Retry key belongs|capacity reached|Account unavailable/.test(error.message))return response({error:error.message},409);throw error;}}
