import { z } from "zod";
import { publicProfileProjection, type PublicProfileState } from "./public-profile.js";
const handle=z.string().regex(/^[a-z0-9](?:[a-z0-9-]{0,37}[a-z0-9])?$/);
export const peopleQuerySchema=z.object({q:z.string().max(200).default(""),cursor:z.string().regex(/^[1-9][0-9]{0,12}$/).optional()}).strict();
export const discoveryInputSchema=z.object({enabled:z.boolean(),confirmed:z.literal(true),expectedVersion:z.number().int().nonnegative()}).strict();
export const followInputSchema=z.object({following:z.boolean(),expectedVersion:z.number().int().nonnegative(),idempotencyKey:z.string().uuid()}).strict();
export interface DiscoveryState {enabled:boolean;version:number;delivery:"pending"|"delivered";publicationVersion:number;handle:string}
export interface PeopleRegistration {accountKey:string;handle:string;version:number;publicationVersion:number;enabled:boolean}
export interface FollowingRecord {targetAccount:string;targetOwner:string;handle:string;version:number;following:boolean}
export class CommunityPeople {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec(`CREATE TABLE IF NOT EXISTS people_discovery(id INTEGER PRIMARY KEY CHECK(id=1),doc TEXT NOT NULL);CREATE TABLE IF NOT EXISTS people_directory(account_key TEXT PRIMARY KEY,handle TEXT NOT NULL,version INTEGER NOT NULL,publication_version INTEGER NOT NULL,enabled INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS people_directory_handle ON people_directory(handle,account_key);CREATE TABLE IF NOT EXISTS private_following(target_account TEXT PRIMARY KEY,doc TEXT NOT NULL);CREATE TABLE IF NOT EXISTS private_following_receipts(event_key TEXT PRIMARY KEY,payload TEXT NOT NULL,doc TEXT NOT NULL);`);}
 state():DiscoveryState{const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM people_discovery WHERE id=1").toArray()[0];return row?JSON.parse(row.doc) as DiscoveryState:{enabled:false,version:0,delivery:"delivered",publicationVersion:0,handle:""};}
 configure(input:unknown,publication:PublicProfileState){const value=discoveryInputSchema.parse(input);return this.storage.transactionSync(()=>{const current=this.state();if(current.version!==value.expectedVersion)throw new Error("Discovery settings changed; refresh before saving");if(value.enabled&&!publicProfileProjection(publication.profile.handle,publication))throw new Error("Publish your profile before joining discovery");const next:DiscoveryState={enabled:value.enabled,version:current.version+1,delivery:"pending",publicationVersion:publication.version,handle:publication.profile.handle};this.storage.sql.exec("INSERT INTO people_discovery VALUES(1,?) ON CONFLICT(id) DO UPDATE SET doc=excluded.doc",JSON.stringify(next));return next;});}
 delivered(version:number){const current=this.state();if(current.version===version)this.storage.sql.exec("UPDATE people_discovery SET doc=? WHERE id=1",JSON.stringify({...current,delivery:"delivered"}));}
 register(value:PeopleRegistration){handle.parse(value.handle);if(!value.accountKey||!Number.isSafeInteger(value.version)||value.version<1)throw new Error("Invalid discovery registration");this.storage.sql.exec("INSERT INTO people_directory VALUES(?,?,?,?,?) ON CONFLICT(account_key) DO UPDATE SET handle=excluded.handle,version=excluded.version,publication_version=excluded.publication_version,enabled=excluded.enabled WHERE excluded.version>people_directory.version",value.accountKey,value.handle,value.version,value.publicationVersion,Number(value.enabled));}
 page(cursor?:string){if(cursor&&!/^[1-9][0-9]{0,12}$/.test(cursor))throw new Error("Invalid cursor");const rows=this.storage.sql.exec<{position:number;account_key:string;handle:string;version:number;publication_version:number}>("SELECT rowid AS position,account_key,handle,version,publication_version FROM people_directory WHERE enabled=1 AND rowid>? ORDER BY rowid LIMIT 21",Number(cursor??0)).toArray();return {rows:rows.slice(0,20).map(row=>({accountKey:row.account_key,handle:row.handle,version:row.version,publicationVersion:row.publication_version,enabled:true})),nextCursor:rows.length>20?String(rows[19]!.position):null};}
 followingRecord(targetAccount:string){const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM private_following WHERE target_account=?",targetAccount).toArray()[0];return row?JSON.parse(row.doc) as FollowingRecord:null;}
 followingPage(cursor?:string){if(cursor&&!/^[1-9][0-9]{0,12}$/.test(cursor))throw new Error("Invalid cursor");const records=this.storage.sql.exec<{position:number;doc:string}>("SELECT rowid AS position,doc FROM private_following WHERE json_extract(doc,'$.following')=1 AND rowid>? ORDER BY rowid LIMIT 6",Number(cursor??0)).toArray();return {rows:records.slice(0,5).map(row=>JSON.parse(row.doc) as FollowingRecord),nextCursor:records.length>5?String(records[4]!.position):null};}
 followingForHandle(value:string){handle.parse(value);const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM private_following WHERE json_extract(doc,'$.handle')=? AND json_extract(doc,'$.following')=1 ORDER BY rowid LIMIT 1",value).toArray()[0];return row?JSON.parse(row.doc) as FollowingRecord:null;}
 replayFollowing(value:string,input:unknown){const parsed=followInputSchema.parse(input),row=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM private_following_receipts WHERE event_key=?",parsed.idempotencyKey).toArray()[0];if(!row)return null;const old=JSON.parse(row.payload) as {target:{handle:string};value:unknown};if(old.target.handle!==value||JSON.stringify(old.value)!==JSON.stringify(parsed))throw new Error("Retry key belongs to a different follow change");const record=JSON.parse(row.doc) as FollowingRecord;return {record:this.followingRecord(record.targetAccount)??record,replayed:true};}
 setFollowing(target:{accountKey:string;ownerId:string;handle:string},input:unknown){const value=followInputSchema.parse(input);handle.parse(target.handle);if(!target.accountKey||!target.ownerId)throw new Error("Published target required");return this.storage.transactionSync(()=>{const payload=JSON.stringify({target,value});const old=this.storage.sql.exec<{payload:string;doc:string}>("SELECT payload,doc FROM private_following_receipts WHERE event_key=?",value.idempotencyKey).toArray()[0];if(old){if(old.payload!==payload)throw new Error("Retry key belongs to a different follow change");return {record:JSON.parse(old.doc) as FollowingRecord,replayed:true};}const current=this.followingRecord(target.accountKey);if((current?.version??0)!==value.expectedVersion)throw new Error("Following changed; refresh before saving");if(this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM private_following_receipts").toArray()[0]!.n>=2000)throw new Error("Following change capacity reached");if(value.following&&!current?.following&&this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM private_following WHERE json_extract(doc,'$.following')=1").toArray()[0]!.n>=100)throw new Error("Following capacity reached");const record:FollowingRecord={targetAccount:target.accountKey,targetOwner:target.ownerId,handle:target.handle,version:(current?.version??0)+1,following:value.following};this.storage.sql.exec("INSERT INTO private_following VALUES(?,?) ON CONFLICT(target_account) DO UPDATE SET doc=excluded.doc",target.accountKey,JSON.stringify(record));this.storage.sql.exec("INSERT INTO private_following_receipts VALUES(?,?,?)",value.idempotencyKey,payload,JSON.stringify(record));return {record,replayed:false};});}
}
export interface PeopleSnapshot {profile:PublicProfileState;discovery:DiscoveryState;active:boolean}
export function discoveredProfile(registration:PeopleRegistration,snapshot:PeopleSnapshot){const {profile,discovery}=snapshot;if(!registration.enabled||!snapshot.active||!discovery.enabled||discovery.version!==registration.version||discovery.publicationVersion!==profile.version||registration.publicationVersion!==profile.version||discovery.handle!==registration.handle)return null;return publicProfileProjection(registration.handle,profile);}
