import { z } from "zod";
import { APPEAL_WINDOW_MS } from "../core/moderation.js";
import { safeContent } from "./public-community.js";
const reason = z.string().trim().min(1).max(500);
const reportInput = z.object({reason:z.enum(["spam","harassment","other"]),note:z.string().trim().max(500)}).strict();
const actionInput = z.object({action:z.enum(["dismiss","hide","remove"]),reason,expectedVersion:z.number().int().positive().safe()}).strict();
const appealInput = z.object({reason}).strict();
const decisionInput = z.object({decision:z.enum(["upheld","overturned"]),reason,expectedVersion:z.number().int().positive().safe()}).strict();
export interface CommunityModerationReport {
 id:string;contentId:string;authorId:string;reporterId:string;reason:string;note:string;status:"open"|"resolved";action:"dismiss"|"hide"|"remove"|null;resolvedBy:string|null;resolvedAt:number|null;createdAt:number;version:number;
 canAppeal?:boolean;canResolve?:boolean;canDecide?:boolean;
 appeal:{reason:string;status:"pending"|"upheld"|"overturned";decidedBy:string|null;createdAt:number;decidedAt:number|null}|null;
}
export interface CommunityModerationAudit {reportId:string;actorId:string;action:string;reason:string;at:number}
export interface CanonicalModerationContent {authorId:string;available:boolean}
/** Ledger and visibility changes must share the same Durable Object transaction. */
export class CommunityModeration {
 constructor(private storage:DurableObjectStorage,private namespace:string,private content:(id:string)=>CanonicalModerationContent|null,private apply:(id:string,state:"visible"|"hidden"|"removed")=>void,private now:()=>number=Date.now){
  storage.sql.exec("CREATE TABLE IF NOT EXISTS community_moderation_reports(namespace TEXT NOT NULL,id TEXT NOT NULL,content_id TEXT NOT NULL,reporter_id TEXT NOT NULL,doc TEXT NOT NULL,PRIMARY KEY(namespace,id),UNIQUE(namespace,content_id,reporter_id)); CREATE TABLE IF NOT EXISTS community_moderation_audit(namespace TEXT NOT NULL,id INTEGER PRIMARY KEY AUTOINCREMENT,doc TEXT NOT NULL);");
 }
 private all(){return this.storage.sql.exec<{doc:string}>("SELECT doc FROM community_moderation_reports WHERE namespace=? ORDER BY rowid DESC LIMIT 1000",this.namespace).toArray().map(row=>JSON.parse(row.doc) as CommunityModerationReport);}
 private get(id:string){const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM community_moderation_reports WHERE namespace=? AND id=?",this.namespace,id).toArray()[0];if(!row)throw Error("Report unavailable");return JSON.parse(row.doc) as CommunityModerationReport;}
 private save(value:CommunityModerationReport){this.storage.sql.exec("UPDATE community_moderation_reports SET doc=? WHERE namespace=? AND id=?",JSON.stringify(value),this.namespace,value.id);return value;}
 private audit(reportId:string,actorId:string,action:string,note:string){safeContent(note);this.storage.sql.exec("INSERT INTO community_moderation_audit(namespace,doc) VALUES(?,?)",this.namespace,JSON.stringify({reportId,actorId,action,reason:note,at:this.now()} satisfies CommunityModerationAudit));}
 private independent(report:CommunityModerationReport,actorId:string,moderator:boolean){if(!moderator)throw Error("Moderator capability required");if(actorId===report.authorId||actorId===report.reporterId)throw Error("An independent moderator is required");}
 private refresh(contentId:string){const restrictions=this.storage.sql.exec<{doc:string}>("SELECT doc FROM community_moderation_reports WHERE namespace=? AND content_id=?",this.namespace,contentId).toArray().map(row=>JSON.parse(row.doc) as CommunityModerationReport).filter(report=>report.status==="resolved"&&report.appeal?.status!=="overturned");this.apply(contentId,restrictions.some(report=>report.action==="remove")?"removed":restrictions.some(report=>report.action==="hide")?"hidden":"visible");}
 report(contentId:string,actorId:string,input:unknown){const value=reportInput.parse(input);safeContent(value.note);return this.storage.transactionSync(()=>{if(!actorId)throw Error("Authentication required");const content=this.content(contentId);if(!content?.available)throw Error("Content unavailable");if(content.authorId===actorId)throw Error("Authors cannot report their own content");const existing=this.all().find(report=>report.contentId===contentId&&report.reporterId===actorId);if(existing){if(existing.reason!==value.reason||existing.note!==value.note)throw Error("Content already reported");return {id:existing.id,status:existing.status};}if(this.all().length>=1000)throw Error("Moderation inbox capacity reached");const report:CommunityModerationReport={id:crypto.randomUUID(),contentId,authorId:content.authorId,reporterId:actorId,...value,status:"open",action:null,resolvedBy:null,resolvedAt:null,createdAt:this.now(),version:1,appeal:null};this.storage.sql.exec("INSERT INTO community_moderation_reports VALUES(?,?,?,?,?)",this.namespace,report.id,contentId,actorId,JSON.stringify(report));return {id:report.id,status:report.status};});}
 inbox(actorId:string,moderator:boolean){return this.all().filter(report=>moderator||report.authorId===actorId||report.reporterId===actorId).map(report=>({...report,...(!moderator?{reporterId:undefined,authorId:undefined,note:report.reporterId===actorId?report.note:undefined}:{}),canAppeal:report.authorId===actorId&&report.status==="resolved"&&(report.action==="hide"||report.action==="remove")&&!report.appeal&&report.resolvedAt!==null&&this.now()-report.resolvedAt<=APPEAL_WINDOW_MS,canResolve:moderator&&report.authorId!==actorId&&report.reporterId!==actorId&&report.status==="open",canDecide:moderator&&report.authorId!==actorId&&report.reporterId!==actorId&&report.resolvedBy!==actorId&&report.appeal?.status==="pending"}));}
 history(actorId:string,moderator:boolean){if(!moderator)throw Error("Moderator capability required");if(!actorId)throw Error("Authentication required");return this.storage.sql.exec<{doc:string}>("SELECT doc FROM community_moderation_audit WHERE namespace=? ORDER BY id DESC LIMIT 1000",this.namespace).toArray().map(row=>JSON.parse(row.doc) as CommunityModerationAudit);}
 resolve(id:string,actorId:string,moderator:boolean,input:unknown){const value=actionInput.parse(input);safeContent(value.reason);return this.storage.transactionSync(()=>{const report=this.get(id);this.independent(report,actorId,moderator);if(report.status!=="open"||report.version!==value.expectedVersion)throw Error("Report changed; refresh before deciding");const next=this.save({...report,status:"resolved",action:value.action,resolvedBy:actorId,resolvedAt:this.now(),version:report.version+1});this.audit(id,actorId,value.action,value.reason);this.refresh(report.contentId);return next;});}
 appeal(id:string,actorId:string,input:unknown){const value=appealInput.parse(input);safeContent(value.reason);return this.storage.transactionSync(()=>{const report=this.get(id);if(report.authorId!==actorId)throw Error("Only the content author can appeal");if(report.status!=="resolved"||report.resolvedAt===null||(report.action!=="hide"&&report.action!=="remove"))throw Error("Only a hide or remove can be appealed");if(this.now()-report.resolvedAt>APPEAL_WINDOW_MS)throw Error("The 14-day appeal window has closed");if(report.appeal)throw Error("Action already appealed");const saved=this.save({...report,version:report.version+1,appeal:{reason:value.reason,status:"pending",decidedBy:null,createdAt:this.now(),decidedAt:null}});return {id:saved.id,version:saved.version,appeal:saved.appeal};});}
 decide(id:string,actorId:string,moderator:boolean,input:unknown){const value=decisionInput.parse(input);safeContent(value.reason);return this.storage.transactionSync(()=>{const report=this.get(id);this.independent(report,actorId,moderator);if(report.resolvedBy===actorId)throw Error("A different moderator must decide the appeal");if(report.appeal?.status!=="pending"||report.version!==value.expectedVersion)throw Error("Appeal changed; refresh before deciding");const next=this.save({...report,version:report.version+1,appeal:{...report.appeal,status:value.decision,decidedBy:actorId,decidedAt:this.now()}});this.audit(id,actorId,`appeal_${value.decision}`,value.reason);this.refresh(report.contentId);return next;});}
}
