/** Worker-side egress only. Never serialize credential callbacks into a sandbox. */
export interface ExecutionEgressRule {origin:string;path:string;query?:''|'?service=git-upload-pack'|'?service=git-receive-pack';method:'GET'|'POST';maxRequestBytes:number;maxResponseBytes:number;headers?:()=>Promise<Headers>}
export type ExecutionEgressFetch=(request:Request)=>Promise<Response>;
function exactHttps(value:string){const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port||url.hash||url.hostname.includes(':')||/^\d+(?:\.\d+){3}$/.test(url.hostname))throw Error('Invalid egress destination');return url;}
async function within<T>(promise:Promise<T>,signal:AbortSignal){signal.throwIfAborted();let abort:()=>void=()=>{};try{return await Promise.race([promise,new Promise<never>((_,reject)=>{abort=()=>reject(Error("Egress deadline"));signal.addEventListener("abort",abort,{once:true});})]);}finally{signal.removeEventListener("abort",abort);}}
async function boundedBytes(stream:ReadableStream<Uint8Array>|null,limit:number,signal:AbortSignal){if(!stream)return new Uint8Array();const reader=stream.getReader(),parts:Uint8Array[]=[];let size=0;try{for(;;){signal.throwIfAborted();const next=await within(reader.read(),signal);if(next.done)break;size+=next.value.byteLength;if(size>limit)throw Error('Egress body limit');parts.push(next.value);}const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.byteLength;}return bytes;}catch(error){void reader.cancel().catch(()=>{});throw error;}}
/** Install through interceptAllOutboundHttp and interceptOutboundHttps('*'), with Internet disabled. */
export function executionEgress(rules:readonly ExecutionEgressRule[],fetcher:ExecutionEgressFetch=request=>fetch(request),authorize:()=>Promise<void>=async()=>{}){
 if(rules.length>32)throw Error("Egress rule bound exceeded");
 const validated=rules.map(rule=>{const origin=exactHttps(rule.origin);if(origin.origin!==rule.origin||origin.pathname!=='/'||origin.search||!rule.path.startsWith('/')||rule.path.includes('?')||rule.path.includes('#')||![undefined,'','?service=git-upload-pack','?service=git-receive-pack'].includes(rule.query)||(Boolean(rule.query)&&(rule.method!=='GET'||!rule.path.endsWith('/info/refs')))||!Number.isSafeInteger(rule.maxRequestBytes)||rule.maxRequestBytes<0||rule.maxRequestBytes>1048576||!Number.isSafeInteger(rule.maxResponseBytes)||rule.maxResponseBytes<1||rule.maxResponseBytes>16777216)throw Error('Invalid egress rule');return rule;});
 return {async fetch(request:Request){const signal=AbortSignal.timeout(10000);try{let target:URL;try{target=exactHttps(request.url);}catch{return new Response("Egress denied",{status:403});}const rule=validated.find(rule=>rule.origin===target.origin&&rule.path===target.pathname&&(rule.query??'')===target.search&&rule.method===request.method);if(!rule)return new Response('Egress denied',{status:403});await within(authorize(),signal);signal.throwIfAborted();const bytes=await boundedBytes(request.body,rule.maxRequestBytes,signal);await within(authorize(),signal);signal.throwIfAborted();const headers=new Headers(rule.headers?await within(rule.headers(),signal):undefined);await within(authorize(),signal);signal.throwIfAborted();for(const name of ['cookie','host','proxy-authorization'])headers.delete(name);const upstream=await within(fetcher(new Request(target.href,{method:rule.method,headers,body:rule.method==='POST'?bytes:undefined,redirect:'manual',signal})),signal);if(upstream.status>=300&&upstream.status<400){void upstream.body?.cancel();return new Response('Egress redirect denied',{status:403});}if(upstream.status<200||upstream.status>=300){void upstream.body?.cancel();return new Response("Egress upstream refused",{status:upstream.status>=400&&upstream.status<=599?upstream.status:503});}if(upstream.url&&upstream.url!==target.href)throw Error('Egress destination changed');const output=await boundedBytes(upstream.body,rule.maxResponseBytes,signal);await within(authorize(),signal);signal.throwIfAborted();return new Response(output,{status:upstream.status,headers:{'Content-Type':upstream.headers.get('content-type')??'application/octet-stream','Cache-Control':'no-store'}});}catch{return new Response('Egress unavailable',{status:503});}}};
}
