import {z} from 'zod';
const scopeSchema=z.object({projectId:z.string().min(1).max(128),incarnation:z.uuid(),taskId:z.string().min(1).max(101),repoName:z.string().min(1).max(200),actorId:z.string().min(1).max(256),generationStamp:z.string().min(1).max(1000),maintainerWriteSource:z.object({creatorId:z.string().min(1).max(256),revision:z.number().int().positive().safe()}).strict().optional(),organizationSource:z.object({id:z.string().min(1).max(256),revision:z.number().int().positive().safe()}).strict().optional(),parentTokenHash:z.string().regex(/^[a-f0-9]{64}$/).nullable()}).strict();
const coverageSchema=scopeSchema.pick({projectId:true,incarnation:true,taskId:true,repoName:true});
export type GitGatewayScope=z.infer<typeof scopeSchema>;
export interface GitGatewayAttempt {id:string;scope:GitGatewayScope;credential:'issuance_unknown'|'pending'|'revoked';token?:string;dispatch:'never'|'possible';transport:'open'|'completed'|'unknown'}
/** No expiry, missing records or elapsed time constitutes cleanup proof. */
/** Hard admission boundary retains old replay receipts and every unresolved operation. */
export const GIT_GATEWAY_RECEIPT_LIMIT=100000;
export class GitGatewayLedger {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS git_gateway_attempts(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,settled INTEGER NOT NULL,doc TEXT NOT NULL)');storage.sql.exec('CREATE INDEX IF NOT EXISTS git_gateway_task ON git_gateway_attempts(task_id,settled)');storage.sql.exec('CREATE TABLE IF NOT EXISTS git_gateway_coverage(task_id TEXT PRIMARY KEY,scope TEXT NOT NULL)');}
 declareTask(scope:Pick<GitGatewayScope,'projectId'|'incarnation'|'taskId'|'repoName'>){const encoded=JSON.stringify(coverageSchema.parse({projectId:scope.projectId,incarnation:scope.incarnation,taskId:scope.taskId,repoName:scope.repoName}));this.storage.transactionSync(()=>{const row=this.storage.sql.exec<{scope:string}>('SELECT scope FROM git_gateway_coverage WHERE task_id=?',scope.taskId).toArray()[0];if(row&&row.scope!==encoded)throw Error('Git task coverage scope differs');if(!row)this.storage.sql.exec('INSERT INTO git_gateway_coverage VALUES(?,?)',scope.taskId,encoded);});}
 taskQuiescence(scope:Pick<GitGatewayScope,'projectId'|'incarnation'|'taskId'|'repoName'>){const row=this.storage.sql.exec<{scope:string}>('SELECT scope FROM git_gateway_coverage WHERE task_id=?',scope.taskId).toArray()[0];return !!row&&row.scope===JSON.stringify(coverageSchema.parse({projectId:scope.projectId,incarnation:scope.incarnation,taskId:scope.taskId,repoName:scope.repoName}))&&this.pending(scope.taskId).length===0;}
 get(id:string):GitGatewayAttempt|null{const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM git_gateway_attempts WHERE id=?',id).toArray()[0];return row?JSON.parse(row.doc) as GitGatewayAttempt:null;}
 begin(id:string,scope:GitGatewayScope){z.uuid().parse(id);const parsed=scopeSchema.parse(scope);this.storage.transactionSync(()=>{const old=this.get(id);if(old){if(JSON.stringify(old.scope)!==JSON.stringify(parsed))throw Error('Git transport identity differs');return;}const total=this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM git_gateway_attempts').toArray()[0]!.n;if(total>=GIT_GATEWAY_RECEIPT_LIMIT)throw Error('Git transport audit receipt capacity reached');const pending=this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM git_gateway_attempts WHERE task_id=? AND settled=0',parsed.taskId).toArray()[0]!.n;if(pending>=1000)throw Error('Git transport recovery capacity reached');this.save({id,scope:parsed,credential:'issuance_unknown',dispatch:'never',transport:'open'});});}
 private save(attempt:GitGatewayAttempt){this.storage.sql.exec('INSERT INTO git_gateway_attempts(id,task_id,settled,doc)VALUES(?,?,?,?) ON CONFLICT(id)DO UPDATE SET doc=excluded.doc,settled=excluded.settled',attempt.id,attempt.scope.taskId,attempt.credential==='revoked'&&(attempt.dispatch==='never'||attempt.transport==='completed')?1:0,JSON.stringify(attempt));}
 private change(id:string,update:(attempt:GitGatewayAttempt)=>void){this.storage.transactionSync(()=>{const attempt=this.get(id);if(!attempt)throw Error('Git transport intent is missing');update(attempt);this.save(attempt);});}
 issued(id:string,token:string){if(!token||token.length>8192)throw Error('Invalid Git transport credential');this.change(id,attempt=>{if(attempt.credential==='pending'&&attempt.token===token)return;if(attempt.credential!=='issuance_unknown'||attempt.token)throw Error('Git credential issuance already recorded');attempt.token=token;attempt.credential='pending';});}
 dispatch(id:string,scope:GitGatewayScope){const parsed=scopeSchema.parse(scope);this.change(id,attempt=>{if(JSON.stringify(attempt.scope)!==JSON.stringify(parsed)||attempt.credential!=='pending'||attempt.transport!=='open')throw Error('Git transport scope or lifetime changed');attempt.dispatch='possible';});}
 finish(id:string,completed:boolean,revoked:boolean){this.change(id,attempt=>{if(completed)attempt.transport='completed';else if(attempt.transport!=='completed')attempt.transport='unknown';if(revoked&&attempt.credential==='pending'){attempt.credential='revoked';delete attempt.token;}});return this.settled(id);}
 settled(id:string){const attempt=this.get(id);return !!attempt&&attempt.credential==='revoked'&&(attempt.dispatch==='never'||attempt.transport==='completed');}
 pending(taskId:string){return this.storage.sql.exec<{doc:string}>('SELECT doc FROM git_gateway_attempts WHERE task_id=? AND settled=0 LIMIT 1001',taskId).toArray().map(row=>JSON.parse(row.doc) as GitGatewayAttempt);}
}
