import {z} from 'zod';
import {acceptedTargetSchema,type FrozenAcceptedTarget} from '../core/accepted-target';
const taskId=z.string().regex(/^[a-z0-9][a-z0-9-]{2,100}$/),sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>value!=='0'.repeat(40));
export const integrationRequestExpectedSchema=z.object({acceptedCommit:sha.nullable(),policyVersion:z.number().int().nonnegative().safe(),contributions:z.array(z.object({taskId,commit:sha.nullable(),base:sha.nullable(),acceptedTarget:acceptedTargetSchema.nullable(),targetGeneration:z.object({eventId:z.uuid(),generation:z.number().int().positive().safe()}).strict().nullable()}).strict()).min(1).max(8)}).strict();
export interface IntegrationRequestExpected{acceptedCommit:string|null;policyVersion:number;contributions:{taskId:string;commit:string|null;base:string|null;acceptedTarget:FrozenAcceptedTarget|null;targetGeneration:{eventId:string;generation:number}|null}[]}
export const integrationRequestInputSchema=z.object({taskIds:z.array(taskId).min(1).max(8),idempotencyKey:z.uuid(),expected:integrationRequestExpectedSchema}).strict().refine(value=>new Set(value.taskIds).size===value.taskIds.length&&JSON.stringify(value.taskIds)===JSON.stringify(value.expected.contributions.map(item=>item.taskId)));
export type IntegrationRequestInput=z.infer<typeof integrationRequestInputSchema>;
export interface IntegrationRequestContext{projectId:string;incarnation:string;canonicalRepoName:string;expected:IntegrationRequestExpected;verificationPolicy:Record<string,unknown>;acceptedRequirements:unknown[];acceptancePolicy:unknown}
export interface IntegrationRequestIntent{key:string;actorId:string;eventId:string;input:IntegrationRequestInput;context:IntegrationRequestContext;dispatch:'prepared'|'unknown'|'observed';createdAt:number}
export interface IntegrationRequestProof{key:string;eventId:string;actorId:string;projectId:string;incarnation:string;canonicalRepoName:string;acceptedCommit:string|null;policyVersion:number;taskIds:string[];dispatch:'unknown'|'observed';contributions:{taskId:string;commit:string|null;base:string|null;targetIdentity:Pick<FrozenAcceptedTarget,'projectId'|'incarnation'|'canonicalRepoName'|'ref'|'acceptedCommit'|'acceptedVersion'|'policyVersion'>|null;targetGeneration:{eventId:string;generation:number}|null}[]}
export function integrationRequestProof(intent:IntegrationRequestIntent):IntegrationRequestProof{if(intent.dispatch==='prepared')throw Error('Original integration dispatch intent is missing');return{key:intent.key,eventId:intent.eventId,actorId:intent.actorId,projectId:intent.context.projectId,incarnation:intent.context.incarnation,canonicalRepoName:intent.context.canonicalRepoName,acceptedCommit:intent.context.expected.acceptedCommit,policyVersion:intent.context.expected.policyVersion,taskIds:[...intent.input.taskIds],dispatch:intent.dispatch,contributions:intent.context.expected.contributions.map(item=>{const target=item.acceptedTarget;return{taskId:item.taskId,commit:item.commit,base:item.base,targetGeneration:item.targetGeneration?{...item.targetGeneration}:null,targetIdentity:target?{projectId:target.projectId,incarnation:target.incarnation,canonicalRepoName:target.canonicalRepoName,ref:target.ref,acceptedCommit:target.acceptedCommit,acceptedVersion:target.acceptedVersion,policyVersion:target.policyVersion}:null};})};}
type Storage=Pick<DurableObjectStorage,'sql'|'transactionSync'>;
/** Repository-local immutable queue identity. No credentials or queue delivery
 * result can authorize different contributions under the original request. */
export class IntegrationRequestIntents{
 constructor(private readonly storage:Storage){storage.sql.exec('CREATE TABLE IF NOT EXISTS integration_request_intents(request_key TEXT PRIMARY KEY,event_id TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)');}
 get(key:string):IntegrationRequestIntent|null{z.uuid().parse(key);const row=this.storage.sql.exec('SELECT doc FROM integration_request_intents WHERE request_key=?',key).toArray()[0];return row?JSON.parse(String(row.doc)) as IntegrationRequestIntent:null;}
 forEvent(eventId:string):IntegrationRequestIntent|null{const row=this.storage.sql.exec('SELECT doc FROM integration_request_intents WHERE event_id=?',eventId).toArray()[0];return row?JSON.parse(String(row.doc)) as IntegrationRequestIntent:null;}
 prepare(input:IntegrationRequestInput,actorId:string,context:IntegrationRequestContext,assertCurrent:()=>void){input=integrationRequestInputSchema.parse(input);z.string().min(1).max(256).parse(actorId);z.uuid().parse(context.incarnation);if(JSON.stringify(input.expected)!==JSON.stringify(integrationRequestExpectedSchema.parse(context.expected)))throw Error('Observed integration inputs changed');if(new TextEncoder().encode(JSON.stringify(context)).length>131072)throw Error('Integration request context exceeds bound');return this.storage.transactionSync(()=>{assertCurrent();const old=this.get(input.idempotencyKey);if(old){this.assert(old,input,actorId,context);return{intent:old,replayed:true};}if(Number(this.storage.sql.exec('SELECT COUNT(*) AS count FROM integration_request_intents').toArray()[0]?.count??0)>=10000)throw Error('Integration request recovery capacity reached');const intent:IntegrationRequestIntent={key:input.idempotencyKey,actorId,eventId:`integ-${context.projectId}-${input.idempotencyKey}`,input:structuredClone(input),context:structuredClone(context),dispatch:'prepared',createdAt:Date.now()};this.storage.sql.exec('INSERT INTO integration_request_intents VALUES(?,?,?)',intent.key,intent.eventId,JSON.stringify(intent));return{intent,replayed:false};});}
 assert(intent:IntegrationRequestIntent,input:IntegrationRequestInput,actorId:string,context:IntegrationRequestContext){if(intent.actorId!==actorId||JSON.stringify(intent.input)!==JSON.stringify(integrationRequestInputSchema.parse(input))||JSON.stringify(intent.context)!==JSON.stringify(context))throw Error('Original integration request or frozen context changed');}
 mark(key:string,dispatch:'unknown'|'observed',assertCurrent:(intent:IntegrationRequestIntent)=>void){z.enum(['unknown','observed']).parse(dispatch);return this.storage.transactionSync(()=>{const intent=this.get(key);if(!intent)throw Error('Original integration request unavailable');assertCurrent(intent);if(intent.dispatch==='observed')return intent;const next={...intent,dispatch};this.storage.sql.exec('UPDATE integration_request_intents SET doc=? WHERE request_key=?',JSON.stringify(next),key);return next;});}
}
