import {z} from 'zod';
import type {IntegrationRequestIntent} from './integration-request-intents';
import type {IntegrationNativeRuntimeScope} from './integration-native-runtime';
import {runtimeRelease,type RuntimeReleaseEnvironment} from './runtime-release';
const text=z.string().min(1).max(256),sha=z.string().regex(/^[a-f0-9]{40}$/).refine(v=>v!=='0'.repeat(40)),time=z.number().int().nonnegative().safe();
export const integrationNativePhaseConfigSchema=z.object({projectId:text,incarnation:z.uuid(),expectedEventId:text,actorId:text,sourceVersion:sha,image:z.string().max(512).regex(/^registry\.cloudflare\.com\/[a-f0-9]{32}\/[a-z0-9._-]+@sha256:[a-f0-9]{64}$/),acceptedBase:sha,contributions:z.array(z.object({taskId:text,commit:sha}).strict()).min(1).max(8),activatedAt:time,admissionExpiresAt:time,nativeStopAt:time,maxAllocations:z.literal(1),maxContainerSeconds:z.literal(1200),maxCommands:z.literal(64),kind:z.literal('native-essential')}).strict().refine(p=>new Set(p.contributions.map(c=>c.taskId)).size===p.contributions.length&&p.admissionExpiresAt>p.activatedAt&&p.admissionExpiresAt-p.activatedAt<=3600000&&p.nativeStopAt>p.admissionExpiresAt&&p.nativeStopAt-p.admissionExpiresAt<=1200000);
export type IntegrationNativePhaseConfig=z.infer<typeof integrationNativePhaseConfigSchema>;
export interface IntegrationNativePhaseEnvironment extends RuntimeReleaseEnvironment {INTEGRATION_NATIVE_PHASE_JSON?:string}
export interface IntegrationNativePhaseRecord {config:IntegrationNativePhaseConfig;workerVersion:string;context:string;candidateId:string|null;nativeId:string|null;allocatedAt:number|null;startClaimed:boolean}
/** Trusted bindings only; HTTP request fields cannot install a phase. */
export class IntegrationNativePhases {
 constructor(private readonly storage:DurableObjectStorage,private readonly now=()=>Date.now()){storage.sql.exec('CREATE TABLE IF NOT EXISTS integration_native_phases(workflow_id TEXT PRIMARY KEY,doc TEXT NOT NULL)');}
 get(workflowId:string):IntegrationNativePhaseRecord|null {const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM integration_native_phases WHERE workflow_id=?',workflowId).toArray()[0];return row?JSON.parse(row.doc) as IntegrationNativePhaseRecord:null;}
 private save(record:IntegrationNativePhaseRecord){this.storage.sql.exec('INSERT INTO integration_native_phases VALUES(?,?) ON CONFLICT(workflow_id) DO UPDATE SET doc=excluded.doc',record.config.expectedEventId,JSON.stringify(record));}
 install(intent:IntegrationRequestIntent,env:IntegrationNativePhaseEnvironment){const old=this.get(intent.eventId);if(old){this.assertCurrent(old,env);if(old.context!==JSON.stringify(intent.context))throw Error('Native phase context changed');return old;}if(env.INTEGRATION_NATIVE_PHASE_JSON===undefined)return null;const config=integrationNativePhaseConfigSchema.parse(JSON.parse(env.INTEGRATION_NATIVE_PHASE_JSON)),release=runtimeRelease(env);if(!release.releaseIdentified||release.sourceVersion!==config.sourceVersion||config.expectedEventId!==intent.eventId||config.actorId!==intent.actorId||config.projectId!==intent.context.projectId||config.incarnation!==intent.context.incarnation||config.acceptedBase!==intent.context.expected.acceptedCommit||JSON.stringify(config.contributions)!==JSON.stringify(intent.context.expected.contributions.map(c=>({taskId:c.taskId,commit:c.commit})))||intent.context.verificationPolicy.kind!=='git-integrity'||!intent.context.acceptancePolicy||typeof intent.context.acceptancePolicy!=='object'||!('mode' in intent.context.acceptancePolicy)||intent.context.acceptancePolicy.mode!=='review-required')throw Error('Native phase original intent differs');const record:IntegrationNativePhaseRecord={config,workerVersion:release.workerVersion!,context:JSON.stringify(intent.context),candidateId:null,nativeId:null,allocatedAt:null,startClaimed:false};this.assertCurrent(record,env);this.assertAdmission(record);this.save(record);return record;}
 assertCurrent(record:IntegrationNativePhaseRecord,env:IntegrationNativePhaseEnvironment){const release=runtimeRelease(env),current=env.INTEGRATION_NATIVE_PHASE_JSON===undefined?null:integrationNativePhaseConfigSchema.parse(JSON.parse(env.INTEGRATION_NATIVE_PHASE_JSON));if(!current||JSON.stringify(current)!==JSON.stringify(record.config)||!release.releaseIdentified||release.workerVersion!==record.workerVersion||release.sourceVersion!==record.config.sourceVersion)throw Error('Native phase runtime release or server binding changed');}
 assertAdmission(record:IntegrationNativePhaseRecord){const now=this.now();if(now<record.config.activatedAt||now>=record.config.admissionExpiresAt)throw Error('Native phase allocation admission expired');}
 bind(scope:IntegrationNativeRuntimeScope){const record=this.get(scope.workflowId);if(!record)return;this.assertScope(record,scope);if(record.candidateId!==null&&record.candidateId!==scope.candidateId)throw Error('Native phase candidate changed');this.save({...record,candidateId:scope.candidateId});}
 private assertScope(record:IntegrationNativePhaseRecord,scope:IntegrationNativeRuntimeScope){if(record.config.projectId!==scope.projectId||record.config.incarnation!==scope.incarnation||record.config.actorId!==scope.actorId||record.candidateId!==null&&record.candidateId!==scope.candidateId)throw Error('Native phase scope differs');}
 reserve(scope:IntegrationNativeRuntimeScope,nativeId:string,stage:string){const record=this.get(scope.workflowId);if(!record)return null;this.assertScope(record,scope);this.assertAdmission(record);if(stage!==`integrate-${scope.candidateId}`||record.candidateId!==scope.candidateId)throw Error('Native phase stage is not authorized');if(record.nativeId!==null){if(record.nativeId!==nativeId)throw Error('Native phase allocation limit reached');return record;}const next={...record,nativeId,allocatedAt:this.now()};this.save(next);return next;}
 commandAllowed(scope:IntegrationNativeRuntimeScope,nativeId:string){const record=this.get(scope.workflowId);if(!record)return true;this.assertScope(record,scope);return record.nativeId===nativeId&&record.allocatedAt!==null&&this.now()<Math.min(record.allocatedAt+record.config.maxContainerSeconds*1000,record.config.nativeStopAt);}
 claimStart(scope:IntegrationNativeRuntimeScope,nativeId:string,env:IntegrationNativePhaseEnvironment){const record=this.get(scope.workflowId);if(!record)return null;this.assertCurrent(record,env);this.assertScope(record,scope);this.assertAdmission(record);if(record.nativeId!==nativeId||record.allocatedAt===null||record.startClaimed)throw Error('Native phase start is absent or already consumed');const next={...record,startClaimed:true};this.save(next);return{image:record.config.image,deadline:Math.min(record.allocatedAt+record.config.maxContainerSeconds*1000,record.config.nativeStopAt),admissionExpiresAt:record.config.admissionExpiresAt};}
}
