import {previewExecutionContextSchema,type PreviewExecutionContext} from './preview-execution-authority';
import type {TrustedGitSource,TrustedGitSourceProof} from './trusted-git-source';
import {verifyBuildManifest,type BuildManifest,type BuildFile} from './static-build-artifact';
import {untrustedExecutionName,type UntrustedExecutionNamespace,type UntrustedExecutionRpc} from './untrusted-execution';
import {assertStaticPreviewSource} from './preview-static-capability';
export interface PreviewBuildRequest{projectId:string;commit:string;canonicalRepoName:string;generation?:string;nativeCandidate?:{candidateId:string;workflowId:string}}
export interface IsolatedPreviewBuildLedger{
 preparePreviewExecution(request:PreviewBuildRequest):Promise<PreviewExecutionContext>;
 previewExecutionSnapshot(context:PreviewExecutionContext):Promise<PreviewExecutionContext>;
 claimPreviewExecutionInvocation(context:PreviewExecutionContext,invocationId:string):Promise<{status:'owned'|'recovered';context:PreviewExecutionContext;invocationId?:string}|{status:'busy'}>;
 finishPreviewExecutionInvocation(context:PreviewExecutionContext,invocationId:string):Promise<void>;
 previewExecutionDispatchState(context:PreviewExecutionContext):Promise<'not_dispatched'|'dispatched'|'sealed'>;
 /** Actual controller-owned native object capture with durable key/lifetime closure.
  * Contributor code is never checked out or executed in that source reader. */
 capturePreviewExecutionSource(context:PreviewExecutionContext,invocationId:string):Promise<TrustedGitSource>;
 bindPreviewExecutionSource(context:PreviewExecutionContext,source:TrustedGitSource,invocationId:string):Promise<PreviewExecutionContext>;
 assertPreviewExecutionSource(context:PreviewExecutionContext,proof:TrustedGitSourceProof):Promise<void>;
 preparePreviewExecutionGrant(context:PreviewExecutionContext,invocationId:string):Promise<unknown>;
 authorizePreviewExecution(context:{scope:PreviewExecutionContext['scope'];sourceDigest:string;image:string}):Promise<boolean>;
 claimPreviewExecutionDispatch(context:PreviewExecutionContext,invocationId:string):Promise<{context:PreviewExecutionContext;phase:'dispatched'}>;
 sealPreviewExecution(context:PreviewExecutionContext,invocationId:string):Promise<void>;
}
export interface IsolatedPreviewArtifact{context:PreviewExecutionContext;manifest:BuildManifest;files:BuildFile[];acceptanceEvidence:false}
export class PreviewExecutionBusyError extends Error{constructor(){super('Original preview invocation is busy; no duplicate source or cleanup');this.name='PreviewExecutionBusyError';}}
const equal=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
/** Shared accepted/generation preview builder. The only code execution occurs in
 * the existing deny-egress, pinned-image UntrustedExecution namespace. */
export async function buildIsolatedPreview(request:PreviewBuildRequest,deps:{ledger:IsolatedPreviewBuildLedger;namespace:UntrustedExecutionNamespace;timeoutMs?:number}):Promise<IsolatedPreviewArtifact>{
 const frozen=structuredClone(request);if(!deps.namespace||!deps.ledger)throw Error('Isolated preview authority unavailable');const timeout=deps.timeoutMs??150000;if(!Number.isInteger(timeout)||timeout<1||timeout>150000)throw Error('Preview deadline exceeds bound');const deadline=AbortSignal.timeout(timeout);
 const bounded=async<T>(operation:()=>Promise<T>)=>{deadline.throwIfAborted();let abort=()=>{};try{return await Promise.race([operation(),new Promise<never>((_,reject)=>{abort=()=>reject(Error('Isolated preview deadline exceeded'));deadline.addEventListener('abort',abort,{once:true});})]);}finally{deadline.removeEventListener('abort',abort);}};
 const initial=previewExecutionContextSchema.parse(await bounded(()=>deps.ledger.preparePreviewExecution(frozen)));if(initial.snapshot.projectId!==frozen.projectId||initial.snapshot.commit!==frozen.commit||initial.snapshot.canonicalRepoName!==frozen.canonicalRepoName||initial.snapshot.generation!==(frozen.generation??null)||initial.scope.projectId!==frozen.projectId||initial.scope.commit!==frozen.commit)throw Error('Recorded preview scope differs');const target=initial.snapshot.target;if(frozen.nativeCandidate){if(frozen.generation||target.kind!=='native-candidate'||target.candidateId!==frozen.nativeCandidate.candidateId||target.workflowId!==frozen.nativeCandidate.workflowId)throw Error('Recorded native candidate preview target differs');}else if(target.kind!=='accepted')throw Error('Accepted preview target unavailable');
 const current=async(context:PreviewExecutionContext)=>{const fresh=previewExecutionContextSchema.parse(await bounded(()=>deps.ledger.previewExecutionSnapshot(structuredClone(context))));if(!equal(fresh,context))throw Error('Preview execution authority changed');};
 await current(initial);const invocationId=crypto.randomUUID(),claim=await bounded(()=>deps.ledger.claimPreviewExecutionInvocation(initial,invocationId));if(claim.status==='busy')throw new PreviewExecutionBusyError();if(!equal(claim.context,initial)||claim.status==='owned'&&claim.invocationId!==invocationId)throw Error('Exact preview invocation ownership unavailable');let activeContext=initial;try{const state=await bounded(()=>deps.ledger.previewExecutionDispatchState(initial));await current(initial);if(state!=='not_dispatched'){if(!initial.sourceDigest)throw Error('Original preview dispatch source unavailable');const sourceDigest=initial.sourceDigest,name=await bounded(()=>untrustedExecutionName(initial.scope,sourceDigest));await current(initial);const saved=await bounded(()=>deps.namespace.getByName(name).outputArtifact(initial.scope,sourceDigest));await current(initial);if(!saved||saved.cleanup!=='confirmed'||saved.acceptanceEvidence!==false||saved.image!==initial.snapshot.image||saved.sourceDigest!==sourceDigest||!equal(saved.scope,initial.scope)||saved.manifest.kind!=='static')throw Error('Original preview dispatch remains unresolved; no rebuild permitted');const manifest=structuredClone(saved.manifest),files=saved.files.map(file=>({...file,bytes:file.bytes.slice()}));await bounded(()=>verifyBuildManifest(manifest,initial.scope,files,sourceDigest));await current(initial);return{context:initial,manifest,files,acceptanceEvidence:false};}if(claim.status!=='owned')throw Error('Recovered preview cannot dispatch again');const raw=await bounded(()=>deps.ledger.capturePreviewExecutionSource(structuredClone(initial),invocationId)),source:TrustedGitSource={sourceManifest:structuredClone(raw.sourceManifest),proof:structuredClone(raw.proof),files:raw.files.map(file=>({...file,bytes:file.bytes.slice()}))};await current(initial);
 if(source.sourceManifest.kind!=='source'||source.proof.providerRepoId!==initial.snapshot.providerRepoId||source.proof.canonicalRepoName!==frozen.canonicalRepoName||source.proof.commit!==initial.scope.commit||source.proof.tree!==initial.scope.tree||source.proof.sourceDigest!==source.sourceManifest.digest)throw Error('Native preview source provenance differs');await bounded(()=>verifyBuildManifest(source.sourceManifest,initial.scope,source.files));if(source.proof.blobs.length!==source.files.length||new Set(source.proof.blobs.map(blob=>blob.path)).size!==source.files.length)throw Error('Complete preview blob provenance unavailable');for(const file of source.files){const blob=source.proof.blobs.find(value=>value.path===file.path);if(!blob||!['100644','100755'].includes(blob.mode))throw Error('Preview Git file provenance differs');const header=new TextEncoder().encode(`blob ${file.bytes.length}\0`),bytes=new Uint8Array(header.length+file.bytes.length);bytes.set(header);bytes.set(file.bytes,header.length);const hash=Array.from(new Uint8Array(await bounded(()=>crypto.subtle.digest('SHA-1',bytes))),byte=>byte.toString(16).padStart(2,'0')).join('');if(hash!==blob.hash)throw Error('Preview bytes differ from captured Git blob');}
 assertStaticPreviewSource(source.files);
 const context=previewExecutionContextSchema.parse(await bounded(()=>deps.ledger.bindPreviewExecutionSource(structuredClone(initial),source,invocationId)));activeContext=context;if(!equal(context,{...initial,sourceDigest:source.sourceManifest.digest}))throw Error('Original preview source binding changed');
 const authorize=async()=>{await current(context);await bounded(()=>deps.ledger.assertPreviewExecutionSource(structuredClone(context),structuredClone(source.proof)));const sourceDigest=context.sourceDigest;if(!sourceDigest||!await bounded(()=>deps.ledger.authorizePreviewExecution({scope:context.scope,sourceDigest,image:context.snapshot.image})))throw Error('Funded preview grant unavailable');await current(context);};
 let job:UntrustedExecutionRpc|undefined,ownsDispatch=false,artifact:IsolatedPreviewArtifact|undefined;
 try{await current(context);await bounded(()=>deps.ledger.preparePreviewExecutionGrant(structuredClone(context),invocationId));await authorize();const dispatch=await bounded(()=>deps.ledger.claimPreviewExecutionDispatch(structuredClone(context),invocationId));if(dispatch.phase!=='dispatched'||!equal(dispatch.context,context))throw Error('Exact preview dispatch unavailable');ownsDispatch=true;await authorize();const name=await bounded(()=>untrustedExecutionName(context.scope,source.sourceManifest.digest));job=deps.namespace.getByName(name);await authorize();await bounded(()=>job!.prepare(context.scope,source.sourceManifest,source.files,context.snapshot.image));await authorize();const output=await bounded(()=>job!.run(context.scope,source.sourceManifest,source.files));const manifest=structuredClone(output.manifest),files=output.files.map(file=>({...file,bytes:file.bytes.slice()}));if(output.acceptanceEvidence!==false||manifest.kind!=='static')throw Error('Preview output grants no acceptance authority');await bounded(()=>verifyBuildManifest(manifest,context.scope,files,source.sourceManifest.digest));await authorize();artifact={context,manifest,files,acceptanceEvidence:false};}
 finally{if(ownsDispatch){const cleanup=async<T>(promise:Promise<T>)=>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Preview execution cleanup unconfirmed')),10000);})]);}finally{clearTimeout(timer);}};const closed=await Promise.allSettled([cleanup(deps.ledger.sealPreviewExecution(structuredClone(context),invocationId)),job?cleanup(job.stop()):Promise.resolve({stopped:true})]);if(closed[0]!.status!=='fulfilled'||closed[1]!.status!=='fulfilled'||closed[1]!.value.stopped!==true)throw Error('Preview execution cleanup unconfirmed; no artifact released');}}
 if(!artifact)throw Error('Isolated preview did not produce immutable output');await current(context);return artifact;}finally{if(claim.status==='owned')await deps.ledger.finishPreviewExecutionInvocation(activeContext,invocationId);}
}
