import {z} from 'zod';
import {canonicalTransferJson,issueTransferRequestSchema} from './issue-transfer-api';

const number=z.number().int().positive().safe(),text=z.string().max(256);
const repository=z.object({projectId:text.min(1),incarnation:text.min(1)}).strict();
export const issueTransferAttachmentSchema=z.object({id:z.uuid(),destinationId:z.uuid(),producerIdentity:z.string().min(1).max(2000),name:z.string().min(1).max(255),sha256:z.string().regex(/^[a-f0-9]{64}$/),size:z.number().int().nonnegative().max(5*1024*1024),authorId:text.min(1),author:text,createdAt:z.string().datetime()}).strict();
export const issueTransferManifestSchema=z.object({
 requestId:z.uuid(),actorId:text.min(1),previewDigest:z.string().regex(/^[a-f0-9]{64}$/),audienceVersion:z.literal('repository-members-v1'),
 source:repository.extend({number,createdAt:z.string().min(1).max(128),author:text,stateRevision:z.number().int().nonnegative().safe()}),
 destination:repository.extend({audienceDigest:z.string().regex(/^[a-f0-9]{64}$/),audienceVersion:z.literal('repository-members-v1')}),
 issue:z.object({number,title:z.string().min(1).max(200),body:z.string().max(20000),state:z.enum(['open','closed']),author:text,created_at:z.string().max(128),updated_at:z.string().max(128),closed_by:text.nullable()}).strict(),
 comments:z.array(z.object({id:number,subject:z.string().max(128),author:text,body:z.string().max(10000),path:z.string().max(400).nullable(),line:number.nullable(),commit:z.string().max(40).nullable(),created_at:z.string().max(128)}).strict()).max(1000),
 features:z.json(),attachments:z.array(issueTransferAttachmentSchema).max(10),
 attribution:z.object({issueActorId:text.min(1).nullable(),commentActorIds:z.record(z.string().regex(/^[1-9][0-9]{0,15}$/),text.min(1).nullable()),identity:z.literal('source-origin')}).strict(),
}).strict();
export type IssueTransferManifest=z.infer<typeof issueTransferManifestSchema>;
export type IssueTransferAttachment=z.infer<typeof issueTransferAttachmentSchema>;
export const issueTransferCancellationSchema=z.object({requestId:z.uuid(),cancelId:z.uuid(),expectedManifestDigest:z.string().regex(/^[a-f0-9]{64}$/),expectedDestinationIncarnation:z.uuid(),confirmed:z.literal(true),originalRequest:issueTransferRequestSchema.optional()}).strict().refine(value=>value.requestId!==value.cancelId,{message:'Cancellation requires its own request identity'}).refine(value=>!value.originalRequest||value.originalRequest.requestId===value.requestId&&value.originalRequest.expectedManifestDigest===value.expectedManifestDigest&&value.originalRequest.expectedDestinationIncarnation===value.expectedDestinationIncarnation,{message:'Original transfer confirmation does not match cancellation'});
export type IssueTransferCancellation=z.infer<typeof issueTransferCancellationSchema>;
export function normalizeIssueTransferCancellation(manifest:IssueTransferManifest,value:unknown):IssueTransferCancellation{
 const input=issueTransferCancellationSchema.parse(value);
 const originalRequest={destinationProjectId:manifest.destination.projectId,expectedRevision:manifest.source.stateRevision,requestId:manifest.requestId,confirmed:true as const,expectedManifestDigest:manifest.previewDigest,expectedDestinationIncarnation:manifest.destination.incarnation};
 if(input.requestId!==manifest.requestId||input.expectedManifestDigest!==manifest.previewDigest||input.expectedDestinationIncarnation!==manifest.destination.incarnation)throw new IssueTransferError('Original cancellation scope does not match transfer',409);
 if(input.originalRequest&&canonicalTransferJson(input.originalRequest)!==canonicalTransferJson(originalRequest))throw new IssueTransferError('Original transfer confirmation does not match frozen request',409);
 return{...input,originalRequest};
}
export type IssueTransferPhase='locked'|'frozen'|'reserved'|'copying'|'ready'|'active'|'completed'|'cancelling'|'cancelled';
export interface IssueTransferRecord {version:1;manifest:IssueTransferManifest;phase:IssueTransferPhase;destinationNumber?:number;activatedDestinationNumber?:number;finalized?:boolean;cancelId?:string;destinationFinalization?:{actorId:string;requestId:string;finalizeId?:string}}
export interface IssueTransferCancellationRecord {version:1;requestId:string;cancelId:string;actorId:string;manifest:IssueTransferManifest;input:IssueTransferCancellation;location:'source'|'destination';phase:'cancelling'|'cancelled'|'denied-active';previousPhase?:IssueTransferPhase}
export interface IssueTransferUnfrozenScope {projectId:string;incarnation:string;number:number;createdAt:string;author:string}
export interface IssueTransferUnfrozenCancellation {version:1;scope:IssueTransferUnfrozenScope;input:IssueTransferCancellation;actorId:string;requestId:string;cancelId:string;phase:'cancelled'}
export const issueTransferFinalizationSchema=z.object({requestId:z.uuid(),finalizeId:z.uuid(),expectedManifestDigest:z.string().regex(/^[a-f0-9]{64}$/),expectedDestinationIncarnation:z.uuid(),destinationNumber:number,confirmed:z.literal(true)}).strict().refine(value=>value.requestId!==value.finalizeId,{message:'Finalization requires its own request identity'});
export type IssueTransferFinalization=z.infer<typeof issueTransferFinalizationSchema>;
export interface IssueTransferFinalizationRecord {version:1;requestId:string;finalizeId:string;actorId:string;manifest:IssueTransferManifest;input:IssueTransferFinalization;phase:'prepared'|'source-completed'|'completed'}
type StoredFinalization=Omit<IssueTransferFinalizationRecord,'manifest'>&{manifestBinding:string};
export interface IssueTransferCopyAttempt {nonce:string;phase:'issued'|'unknown'|'verified'}
export class IssueTransferError extends Error{constructor(message:string,readonly status:number){super(message);}}
export class IssueTransferActiveDestinationError extends IssueTransferError{readonly reason='destination-active' as const;constructor(){super('Destination issue is already active',409);}}
export function ensureIssueTransferSchema(storage:Pick<DurableObjectStorage,'sql'>){
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_locks(issue_number INTEGER PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,document TEXT NOT NULL)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_incoming(issue_number INTEGER PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,document TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 0)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_receipts(request_id TEXT PRIMARY KEY,identity TEXT NOT NULL,document TEXT NOT NULL)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_capacity(request_id TEXT PRIMARY KEY,bytes INTEGER NOT NULL)');
 storage.sql.exec('INSERT OR IGNORE INTO issue_transfer_capacity SELECT request_id,length(CAST(identity AS BLOB))*7+16384 FROM issue_transfer_receipts');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_copy_attempts(request_id TEXT NOT NULL,attachment_id TEXT NOT NULL,document TEXT NOT NULL,PRIMARY KEY(request_id,attachment_id))');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_cancellations(request_id TEXT PRIMARY KEY,identity TEXT NOT NULL,document TEXT NOT NULL)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_cancel_requests(actor_id TEXT NOT NULL,cancel_id TEXT NOT NULL,request_id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(actor_id,cancel_id))');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_unfrozen_cancellations(request_id TEXT PRIMARY KEY,identity TEXT NOT NULL,document TEXT NOT NULL)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_finalizations(actor_id TEXT NOT NULL,finalize_id TEXT NOT NULL,request_id TEXT NOT NULL,identity TEXT NOT NULL,document TEXT NOT NULL,PRIMARY KEY(actor_id,finalize_id))');
}
export function assertIssueWritable(storage:Pick<DurableObjectStorage,'sql'>,issueNumber:number,requestId?:string){
 ensureIssueTransferSchema(storage);
 const lock=storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',issueNumber).toArray()[0];
 if(lock&&lock.request_id!==requestId)throw new IssueTransferError('Issue transfer is in progress; original content is preserved',409);
 const incoming=storage.sql.exec<{request_id:string;active:number}>('SELECT request_id,active FROM issue_transfer_incoming WHERE issue_number=?',issueNumber).toArray()[0];
 if(incoming&&incoming.active!==1&&incoming.request_id!==requestId)throw new IssueTransferError('Incoming issue transfer is not active',409);
}
type Verify=(manifest:IssueTransferManifest,destinationNumber:number)=>boolean;
/** Both repositories retain immutable receipts. Destination rows remain hidden
 * until their verified content is ready; a completed source lock stays durable. */
export class IssueTransferLedger {
 constructor(private readonly storage:DurableObjectStorage){ensureIssueTransferSchema(storage);}
 read(requestId:string):IssueTransferRecord|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_transfer_receipts WHERE request_id=?',requestId).toArray()[0];return row?JSON.parse(row.document) as IssueTransferRecord:undefined;}
 private validate(value:IssueTransferManifest){const manifest=issueTransferManifestSchema.parse(value);if(manifest.source.projectId===manifest.destination.projectId)throw new IssueTransferError('Issue transfer requires another repository',400);if(manifest.issue.number!==manifest.source.number||manifest.issue.created_at!==manifest.source.createdAt||manifest.issue.author!==manifest.source.author)throw new IssueTransferError('Original issue identity does not match transfer',409);if(new Set(manifest.attachments.flatMap(row=>[row.id,row.destinationId])).size!==manifest.attachments.length*2)throw new IssueTransferError('Source and destination attachment identities must be distinct',400);if(new Set(manifest.comments.map(row=>row.id)).size!==manifest.comments.length||manifest.comments.some(row=>row.subject!=='issue:'+manifest.source.number))throw new IssueTransferError('Comments are outside the original issue identity',400);const commentIds=new Set(manifest.comments.map(row=>String(row.id)));if(Object.keys(manifest.attribution.commentActorIds).length!==commentIds.size||Object.keys(manifest.attribution.commentActorIds).some(id=>!commentIds.has(id)))throw new IssueTransferError('Original comment attribution identities do not match',400);if(new TextEncoder().encode(JSON.stringify(manifest)).length>2*1024*1024)throw new IssueTransferError('Issue transfer manifest capacity reached',413);return manifest;}
 private existing(manifest:IssueTransferManifest){const row=this.storage.sql.exec<{identity:string;document:string}>('SELECT identity,document FROM issue_transfer_receipts WHERE request_id=?',manifest.requestId).toArray()[0];if(row&&row.identity!==JSON.stringify(manifest))throw new IssueTransferError('Original issue transfer request cannot change',409);return row?JSON.parse(row.document) as IssueTransferRecord:undefined;}
 private save(record:IssueTransferRecord){this.storage.sql.exec('INSERT INTO issue_transfer_receipts VALUES(?,?,?) ON CONFLICT(request_id) DO UPDATE SET document=excluded.document',record.manifest.requestId,JSON.stringify(record.manifest),JSON.stringify(record));return record;}
 private usedCapacity(){
  const reserved=this.storage.sql.exec<{bytes:number}>('SELECT COALESCE(SUM(bytes),0) AS bytes FROM issue_transfer_capacity').toArray()[0]!.bytes;
  const queries=[
   'SELECT COALESCE(SUM(length(CAST(identity AS BLOB))+length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_receipts',
   'SELECT COALESCE(SUM(length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_locks',
   'SELECT COALESCE(SUM(length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_incoming',
   'SELECT COALESCE(SUM(length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_copy_attempts',
   'SELECT COALESCE(SUM(length(CAST(identity AS BLOB))+length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_cancellations',
   'SELECT COALESCE(SUM(length(CAST(payload AS BLOB))),0) AS bytes FROM issue_transfer_cancel_requests',
   'SELECT COALESCE(SUM(length(CAST(identity AS BLOB))+length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_unfrozen_cancellations',
   'SELECT COALESCE(SUM(length(CAST(identity AS BLOB))+length(CAST(document AS BLOB))),0) AS bytes FROM issue_transfer_finalizations',
  ];
  const actual=queries.reduce((sum,query)=>sum+this.storage.sql.exec<{bytes:number}>(query).toArray()[0]!.bytes,0);
  if(!Number.isSafeInteger(reserved)||reserved<0||!Number.isSafeInteger(actual)||actual<0)throw new IssueTransferError('Issue transfer storage accounting is unavailable',413);
  return Math.max(reserved,actual);
 }
 private capacity(manifest:IssueTransferManifest){
  if(this.storage.sql.exec<{count:number}>('SELECT COUNT(*) AS count FROM issue_transfer_capacity').toArray()[0]!.count>=10000)throw new IssueTransferError('Issue transfer receipt capacity reached',413);
  const charge=new TextEncoder().encode(JSON.stringify(manifest)).length*7+16384;
  if(this.usedCapacity()+charge>128*1024*1024)throw new IssueTransferError('Issue transfer storage capacity reached; original issues remain preserved',413);
  this.storage.sql.exec('INSERT INTO issue_transfer_capacity VALUES(?,?)',manifest.requestId,charge);
 }
 private reserveCancellationCapacity(manifest:IssueTransferManifest){
  const previous=this.storage.sql.exec<{bytes:number}>('SELECT bytes FROM issue_transfer_capacity WHERE request_id=?',manifest.requestId).toArray()[0];
  if(!previous||!Number.isSafeInteger(previous.bytes)||previous.bytes<0)throw new IssueTransferError('Original transfer storage reservation is unavailable',413);
  const required=new TextEncoder().encode(JSON.stringify(manifest)).length*7+16384,increment=Math.max(0,required-previous.bytes);
  if(this.usedCapacity()+increment>128*1024*1024)throw new IssueTransferError('Issue transfer cancellation storage capacity reached; original transfer remains preserved',413);
  if(increment)this.storage.sql.exec('UPDATE issue_transfer_capacity SET bytes=? WHERE request_id=? AND bytes=?',required,manifest.requestId,previous.bytes);
 }
 readCancellation(requestId:string):IssueTransferCancellationRecord|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_transfer_cancellations WHERE request_id=?',requestId).toArray()[0];return row?JSON.parse(row.document) as IssueTransferCancellationRecord:undefined;}
 private finalizationBinding(manifest:IssueTransferManifest){return canonicalTransferJson({actorId:manifest.actorId,previewDigest:manifest.previewDigest,source:manifest.source,destination:manifest.destination,audienceVersion:manifest.audienceVersion});}
 readFinalization(requestId:string,finalizeId:string,actorId:string):IssueTransferFinalizationRecord|undefined{
  const row=this.storage.sql.exec<{request_id:string;document:string}>('SELECT request_id,document FROM issue_transfer_finalizations WHERE actor_id=? AND finalize_id=?',actorId,finalizeId).toArray()[0];if(!row)return undefined;if(row.request_id!==requestId)throw new IssueTransferError('Original finalization request cannot change',409);
  const saved=JSON.parse(row.document) as StoredFinalization,source=this.read(requestId);if(!source||source.destinationNumber!==undefined||saved.manifestBinding!==this.finalizationBinding(source.manifest))throw new IssueTransferError('Original finalization manifest is unavailable',409);const {manifestBinding:_binding,...record}=saved;return{...record,manifest:source.manifest};
 }
 private saveFinalization(record:IssueTransferFinalizationRecord){const {manifest,...audit}=record,stored:StoredFinalization={...audit,manifestBinding:this.finalizationBinding(manifest)},document=JSON.stringify(stored);this.storage.sql.exec('INSERT INTO issue_transfer_finalizations VALUES(?,?,?,?,?) ON CONFLICT(actor_id,finalize_id) DO UPDATE SET document=excluded.document',record.actorId,record.finalizeId,record.requestId,canonicalTransferJson({actorId:record.actorId,input:record.input,manifestBinding:stored.manifestBinding}),document);return record;}
 beginFinalization(requestId:string,value:IssueTransferFinalization,actorId:string,assert:()=>void){return this.storage.transactionSync(()=>{
  assert();text.min(1).parse(actorId);const input=issueTransferFinalizationSchema.parse(value);if(input.requestId!==requestId)throw new IssueTransferError('Original finalization request does not match',409);this.assertTransferContinues(requestId);
  const source=this.read(requestId);if(!source||source.destinationNumber!==undefined||source.phase!=='frozen'&&source.phase!=='completed')throw new IssueTransferError('Frozen or completed source transfer is required',409);
  if(input.expectedManifestDigest!==source.manifest.previewDigest||input.expectedDestinationIncarnation!==source.manifest.destination.incarnation||source.activatedDestinationNumber!==undefined&&source.activatedDestinationNumber!==input.destinationNumber)throw new IssueTransferError('Original finalization scope does not match transfer',409);
  const old=this.readFinalization(requestId,input.finalizeId,actorId);if(old){if(canonicalTransferJson(old.input)!==canonicalTransferJson(input))throw new IssueTransferError('Original finalization payload cannot change',409);return old;}
  const record:IssueTransferFinalizationRecord={version:1,requestId,finalizeId:input.finalizeId,actorId,manifest:source.manifest,input,phase:'prepared'},binding=this.finalizationBinding(source.manifest),{manifest:_manifest,...audit}=record,document=JSON.stringify({...audit,manifestBinding:binding}),identity=canonicalTransferJson({actorId,input,manifestBinding:binding});
  if(new TextEncoder().encode(identity+document).length+32>16384||this.storage.sql.exec<{count:number}>('SELECT COUNT(*) AS count FROM issue_transfer_capacity').toArray()[0]!.count>=10000||this.usedCapacity()+16384>128*1024*1024)throw new IssueTransferError('Transfer finalization audit capacity reached',413);
  assert();this.storage.sql.exec('INSERT INTO issue_transfer_capacity VALUES(?,?)',canonicalTransferJson(['finalization',actorId,input.finalizeId]),16384);return this.saveFinalization(record);
 });}
 markFinalizationSourceCompleted(requestId:string,finalizeId:string,actorId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);const record=this.readFinalization(requestId,finalizeId,actorId),source=this.read(requestId);if(!record||!source||source.phase!=='completed'||source.activatedDestinationNumber!==record.input.destinationNumber)throw new IssueTransferError('Positive original source completion is required',409);if(record.phase==='completed'||record.phase==='source-completed')return record;assert();return this.saveFinalization({...record,phase:'source-completed'});});}
 completeFinalization(requestId:string,finalizeId:string,actorId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);const record=this.readFinalization(requestId,finalizeId,actorId),source=this.read(requestId);if(!record||!source||source.phase!=='completed'||source.activatedDestinationNumber!==record.input.destinationNumber||record.phase==='prepared')throw new IssueTransferError('Positive original source and destination finalization are required',409);if(record.phase==='completed')return record;assert();return this.saveFinalization({...record,phase:'completed'});});}
 readUnfrozenCancellation(requestId:string):IssueTransferUnfrozenCancellation|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_transfer_unfrozen_cancellations WHERE request_id=?',requestId).toArray()[0];return row?JSON.parse(row.document) as IssueTransferUnfrozenCancellation:undefined;}
 cancelUnfrozen(scope:IssueTransferUnfrozenScope,value:IssueTransferCancellation,actorId:string,assert:()=>void){return this.storage.transactionSync(()=>{
  assert();if(this.read(value.requestId))return undefined;
  const input=issueTransferCancellationSchema.parse(value);if(!input.originalRequest)throw new IssueTransferError('Original transfer confirmation is required before cancellation',400);
  const source=repository.extend({number,createdAt:z.string().min(1).max(128),author:text}).strict().parse(scope);text.min(1).parse(actorId);
  const identity=canonicalTransferJson({scope:source,input,actorId}),previous=this.storage.sql.exec<{identity:string;document:string}>('SELECT identity,document FROM issue_transfer_unfrozen_cancellations WHERE request_id=?',input.requestId).toArray()[0];
  if(previous){if(previous.identity!==identity)throw new IssueTransferError('Original unfrozen cancellation cannot change',409);return JSON.parse(previous.document) as IssueTransferUnfrozenCancellation;}
  const receipt=this.storage.sql.exec<{request_id:string;payload:string}>('SELECT request_id,payload FROM issue_transfer_cancel_requests WHERE actor_id=? AND cancel_id=?',actorId,input.cancelId).toArray()[0];if(receipt&&(receipt.request_id!==input.requestId||receipt.payload!==identity))throw new IssueTransferError('Original cancellation request cannot change',409);
  const saved:IssueTransferUnfrozenCancellation={version:1,scope:source,input,actorId,requestId:input.requestId,cancelId:input.cancelId,phase:'cancelled'},document=JSON.stringify(saved);
  if(new TextEncoder().encode(identity+document+identity).length>8192)throw new IssueTransferError('Unfrozen cancellation receipt capacity reached',413);
  if(this.storage.sql.exec<{count:number}>('SELECT COUNT(*) AS count FROM issue_transfer_capacity').toArray()[0]!.count>=10000||this.usedCapacity()+8192>128*1024*1024)throw new IssueTransferError('Unfrozen cancellation storage capacity reached',413);
  assert();this.storage.sql.exec('INSERT INTO issue_transfer_capacity VALUES(?,?)',input.requestId,8192);this.storage.sql.exec('INSERT INTO issue_transfer_unfrozen_cancellations VALUES(?,?,?)',input.requestId,identity,document);this.storage.sql.exec('INSERT INTO issue_transfer_cancel_requests VALUES(?,?,?,?)',actorId,input.cancelId,input.requestId,identity);return saved;
 });}
 assertTransferContinues(requestId:string){if(this.readUnfrozenCancellation(requestId))throw new IssueTransferError('Original unfrozen issue transfer was cancelled',410);const cancellation=this.readCancellation(requestId);if(cancellation&&cancellation.phase!=='denied-active')throw new IssueTransferError(cancellation.phase==='cancelled'?'Original issue transfer was cancelled':'Original issue transfer cancellation is pending',cancellation.phase==='cancelled'?410:409);}
 private cancellationIdentity(manifest:IssueTransferManifest,value:IssueTransferCancellation,actorId:string){text.min(1).parse(actorId);const input=normalizeIssueTransferCancellation(manifest,value);const payload=canonicalTransferJson({manifest,input,actorId});const prior=this.storage.sql.exec<{request_id:string;payload:string}>('SELECT request_id,payload FROM issue_transfer_cancel_requests WHERE actor_id=? AND cancel_id=?',actorId,input.cancelId).toArray()[0];if(prior&&(prior.request_id!==manifest.requestId||prior.payload!==payload))throw new IssueTransferError('Original cancellation request cannot change',409);const previous=this.readCancellation(manifest.requestId);if(previous&&canonicalTransferJson({manifest:previous.manifest,input:previous.input,actorId:previous.actorId})!==payload)throw new IssueTransferError('Original transfer cancellation identity cannot change',409);return{input,payload,previous};}
 private saveCancellation(record:IssueTransferCancellationRecord,payload:string){this.storage.sql.exec('INSERT INTO issue_transfer_cancellations VALUES(?,?,?) ON CONFLICT(request_id) DO UPDATE SET document=excluded.document',record.requestId,canonicalTransferJson({manifest:record.manifest,input:record.input,actorId:record.actorId}),JSON.stringify(record));this.storage.sql.exec('INSERT OR IGNORE INTO issue_transfer_cancel_requests VALUES(?,?,?,?)',record.actorId,record.cancelId,record.requestId,payload);return record;}
 beginCancellation(requestId:string,value:IssueTransferCancellation,actorId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const record=this.read(requestId);if(!record||record.destinationNumber!==undefined)throw new IssueTransferError('Original source transfer is unavailable',404);if(record.phase==='completed')throw new IssueTransferActiveDestinationError();const identity=this.cancellationIdentity(record.manifest,value,actorId);if(identity.previous)return identity.previous;if(record.phase!=='locked'&&record.phase!=='frozen')throw new IssueTransferError('Active or completed transfer cannot be cancelled',409);this.reserveCancellationCapacity(record.manifest);const cancellation:IssueTransferCancellationRecord={version:1,requestId,cancelId:identity.input.cancelId,actorId,manifest:record.manifest,input:identity.input,location:'source',phase:'cancelling',previousPhase:record.phase};assert();this.save({...record,phase:'cancelling',cancelId:identity.input.cancelId});return this.saveCancellation(cancellation,identity.payload);});}
 cancelDestination(value:IssueTransferManifest,input:IssueTransferCancellation,actorId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const manifest=this.validate(value),identity=this.cancellationIdentity(manifest,input,actorId);if(identity.previous){if(identity.previous.location!=='destination')throw new IssueTransferError('Cancellation receipt belongs to source',409);return identity.previous;}const record=this.existing(manifest);if(record?.phase==='active'||record?.finalized)throw new IssueTransferActiveDestinationError();if(!record)this.capacity(manifest);else this.reserveCancellationCapacity(manifest);const cancellation:IssueTransferCancellationRecord={version:1,requestId:manifest.requestId,cancelId:identity.input.cancelId,actorId,manifest,input:identity.input,location:'destination',phase:'cancelled'};assert();if(record){if(record.destinationNumber===undefined)throw new IssueTransferError('Cancellation destination identity changed',409);const incoming=this.storage.sql.exec<{active:number;request_id:string}>('SELECT active,request_id FROM issue_transfer_incoming WHERE issue_number=?',record.destinationNumber).toArray()[0];if(!incoming||incoming.active!==0||incoming.request_id!==manifest.requestId)throw new IssueTransferError('Hidden destination ownership changed',409);this.save({...record,phase:'cancelled',cancelId:identity.input.cancelId});this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=? AND request_id=? AND active=0',JSON.stringify({...record,phase:'cancelled',cancelId:identity.input.cancelId}),record.destinationNumber,manifest.requestId);}return this.saveCancellation(cancellation,identity.payload);});}
 denyCancellationActive(requestId:string,cancelId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const cancellation=this.readCancellation(requestId),record=this.read(requestId);if(!cancellation||cancellation.location!=='source'||cancellation.cancelId!==cancelId||!record)throw new IssueTransferError('Original source cancellation is unavailable',404);if(cancellation.phase==='cancelled')throw new IssueTransferError('Completed cancellation cannot be reversed',410);if(cancellation.phase==='denied-active')return cancellation;if(record.phase!=='cancelling'||!cancellation.previousPhase)throw new IssueTransferError('Original cancellation phase changed',409);assert();const {cancelId:_cancelId,...rest}=record;this.save({...rest,phase:cancellation.previousPhase});return this.saveCancellation({...cancellation,phase:'denied-active'},canonicalTransferJson({manifest:cancellation.manifest,input:cancellation.input,actorId:cancellation.actorId}));});}
 completeCancellation(requestId:string,cancelId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const cancellation=this.readCancellation(requestId),record=this.read(requestId);if(!cancellation||cancellation.location!=='source'||cancellation.cancelId!==cancelId||!record||record.destinationNumber!==undefined)throw new IssueTransferError('Original source cancellation is unavailable',404);if(cancellation.phase==='cancelled'){if(record.phase!=='cancelled')throw new IssueTransferError('Cancelled source receipt changed',409);return cancellation;}if(cancellation.phase!=='cancelling'||record.phase!=='cancelling'||record.cancelId!==cancelId||cancellation.previousPhase==='completed')throw new IssueTransferError('Original cancellation phase changed',409);const lock=this.storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',record.manifest.source.number).toArray()[0];if(lock?.request_id!==requestId)throw new IssueTransferError('Original source cancellation lock changed',409);assert();this.save({...record,phase:'cancelled'});this.storage.sql.exec('DELETE FROM issue_transfer_locks WHERE issue_number=? AND request_id=?',record.manifest.source.number,requestId);return this.saveCancellation({...cancellation,phase:'cancelled'},canonicalTransferJson({manifest:cancellation.manifest,input:cancellation.input,actorId:cancellation.actorId}));});}
 lock(value:IssueTransferManifest,assert:()=>void):IssueTransferRecord{return this.storage.transactionSync(()=>{assert();const manifest=this.validate(value);this.assertTransferContinues(manifest.requestId);const old=this.existing(manifest);if(old)return old;this.capacity(manifest);assertIssueWritable(this.storage,manifest.source.number);assert();const record:IssueTransferRecord={version:1,manifest,phase:'locked'};this.storage.sql.exec('INSERT INTO issue_transfer_locks VALUES(?,?,?)',manifest.source.number,manifest.requestId,JSON.stringify(record));return this.save(record);});}
 assertWritable(issueNumber:number,requestId?:string){assertIssueWritable(this.storage,issueNumber,requestId);}
 freeze(value:IssueTransferManifest,assert:()=>void){return this.storage.transactionSync(()=>{const record=this.lock(value,assert);assert();if(record.phase!=='locked')return record;const next={...record,phase:'frozen' as const};this.storage.sql.exec('UPDATE issue_transfer_locks SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.manifest.source.number,record.manifest.requestId);return this.save(next);});}
 reserve(value:IssueTransferManifest,allocate:()=>number,assert:()=>void){return this.storage.transactionSync(()=>{assert();const manifest=this.validate(value);this.assertTransferContinues(manifest.requestId);const old=this.existing(manifest);if(old){if(old.destinationNumber===undefined)throw new IssueTransferError('Transfer receipt belongs to the source repository',409);return old;}this.capacity(manifest);const destinationNumber=allocate();number.parse(destinationNumber);assert();const record:IssueTransferRecord={version:1,manifest,phase:'reserved',destinationNumber};this.storage.sql.exec('INSERT INTO issue_transfer_incoming VALUES(?,?,?,0)',destinationNumber,manifest.requestId,JSON.stringify(record));this.storage.sql.exec('INSERT INTO issue_transfer_locks VALUES(?,?,?)',destinationNumber,manifest.requestId,JSON.stringify(record));return this.save(record);});}
 private destination(requestId:string){const record=this.read(requestId);if(!record||record.destinationNumber===undefined)throw new IssueTransferError('Incoming issue transfer is unavailable',404);return record as IssueTransferRecord&{destinationNumber:number};}
 readCopy(requestId:string,attachmentId:string):IssueTransferCopyAttempt|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_transfer_copy_attempts WHERE request_id=? AND attachment_id=?',requestId,attachmentId).toArray()[0];return row?JSON.parse(row.document) as IssueTransferCopyAttempt:undefined;}
 beginCopy(requestId:string,attachmentId:string,nonce:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);z.uuid().parse(nonce);const record=this.destination(requestId);if(!record.manifest.attachments.some(row=>row.id===attachmentId))throw new IssueTransferError('Attachment is outside original transfer manifest',409);const prior=this.readCopy(requestId,attachmentId);if(prior){if(prior.nonce!==nonce)throw new IssueTransferError('Original attachment copy nonce cannot change',409);return{...prior,newlyIssued:false};}if(record.phase!=='reserved'&&record.phase!=='copying')throw new IssueTransferError('Incoming transfer no longer accepts copy attempts',409);assert();const attempt:IssueTransferCopyAttempt={nonce,phase:'issued'};this.storage.sql.exec('INSERT INTO issue_transfer_copy_attempts VALUES(?,?,?)',requestId,attachmentId,JSON.stringify(attempt));const next={...record,phase:'copying' as const};this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=?',JSON.stringify(next),record.destinationNumber);this.save(next);return{...attempt,newlyIssued:true};});}
 private markCopy(requestId:string,attachmentId:string,nonce:string,phase:'unknown'|'verified',assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);this.destination(requestId);const prior=this.readCopy(requestId,attachmentId);if(!prior||prior.nonce!==nonce)throw new IssueTransferError('Original attachment copy ownership changed',409);if(prior.phase==='verified')return prior;assert();const next:IssueTransferCopyAttempt={nonce,phase};this.storage.sql.exec('UPDATE issue_transfer_copy_attempts SET document=? WHERE request_id=? AND attachment_id=?',JSON.stringify(next),requestId,attachmentId);return next;});}
 markCopyUnknown(requestId:string,attachmentId:string,nonce:string,assert:()=>void){return this.markCopy(requestId,attachmentId,nonce,'unknown',assert);}
 markCopyVerified(requestId:string,attachmentId:string,nonce:string,assert:()=>void){return this.markCopy(requestId,attachmentId,nonce,'verified',assert);}
 markReady(requestId:string,verified:Verify,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);const record=this.destination(requestId);if(record.phase==='active')return record;if(!['reserved','copying','ready'].includes(record.phase))throw new IssueTransferError('Incoming transfer phase changed',409);if(record.manifest.attachments.some(attachment=>this.readCopy(requestId,attachment.id)?.phase!=='verified')||!verified(record.manifest,record.destinationNumber))throw new IssueTransferError('Incoming issue attachments are not fully verified',409);assert();const next={...record,phase:'ready' as const};this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=?',JSON.stringify(next),record.destinationNumber);return this.save(next);});}
 activate(requestId:string,verified:Verify,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);const record=this.destination(requestId);if(record.phase==='active')return record;if(record.phase!=='ready'||record.manifest.attachments.some(attachment=>this.readCopy(requestId,attachment.id)?.phase!=='verified')||!verified(record.manifest,record.destinationNumber))throw new IssueTransferError('Incoming issue transfer is not ready',409);assert();const next={...record,phase:'active' as const};this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=?,active=1 WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.destinationNumber,requestId);return this.save(next);});}
 finishDestination(requestId:string,assert:()=>void,finisher?:{actorId:string;finalizeId?:string}){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);const record=this.destination(requestId);if(record.phase!=='active')throw new IssueTransferError('Incoming issue is not active',409);if(record.finalized)return record;const lock=this.storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',record.destinationNumber).toArray()[0];if(!lock||lock.request_id!==requestId)throw new IssueTransferError('Destination transfer lock ownership changed',409);const actorId=text.min(1).parse(finisher?.actorId??record.manifest.actorId),finalizeId=finisher?.finalizeId===undefined?undefined:z.uuid().parse(finisher.finalizeId);if(finalizeId===requestId)throw new IssueTransferError('Finalization requires its own request identity',400);assert();const next={...record,finalized:true,destinationFinalization:{actorId,requestId,...(finalizeId?{finalizeId}:{})}};this.storage.sql.exec('DELETE FROM issue_transfer_locks WHERE issue_number=? AND request_id=?',record.destinationNumber,requestId);this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.destinationNumber,requestId);return this.save(next);});}
 bindDestination(requestId:string,destinationNumber:number,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);number.parse(destinationNumber);const record=this.read(requestId);if(!record||record.destinationNumber!==undefined||!['frozen','completed'].includes(record.phase))throw new IssueTransferError('Frozen source issue transfer is unavailable',409);if(record.activatedDestinationNumber!==undefined&&record.activatedDestinationNumber!==destinationNumber)throw new IssueTransferError('Original transfer destination number cannot change',409);assert();const next={...record,activatedDestinationNumber:destinationNumber};this.storage.sql.exec('UPDATE issue_transfer_locks SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.manifest.source.number,requestId);return this.save(next);});}
 complete(requestId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();this.assertTransferContinues(requestId);const record=this.read(requestId);if(!record||record.destinationNumber!==undefined||record.activatedDestinationNumber===undefined||!['frozen','completed'].includes(record.phase))throw new IssueTransferError('Frozen source issue transfer and confirmed destination are unavailable',409);const lock=this.storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',record.manifest.source.number).toArray()[0];if(lock?.request_id!==requestId)throw new IssueTransferError('Source transfer lock ownership changed',409);if(record.phase==='completed')return record;assert();const next={...record,phase:'completed' as const};this.storage.sql.exec('UPDATE issue_transfer_locks SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.manifest.source.number,requestId);return this.save(next);});}
}
