import {z} from 'zod';

const number=z.number().int().positive().safe(),text=z.string().max(256);
const repository=z.object({projectId:text.min(1),incarnation:text.min(1)}).strict();
export const issueTransferAttachmentSchema=z.object({id:z.uuid(),destinationId:z.uuid(),producerIdentity:z.string().min(1).max(2000),name:z.string().min(1).max(255),sha256:z.string().regex(/^[a-f0-9]{64}$/),size:z.number().int().nonnegative().max(5*1024*1024),authorId:text.min(1),author:text,createdAt:z.string().datetime()}).strict();
export const issueTransferManifestSchema=z.object({
 requestId:z.uuid(),actorId:text.min(1),previewDigest:z.string().regex(/^[a-f0-9]{64}$/),audienceVersion:z.literal('repository-members-v1'),
 source:repository.extend({number,createdAt:z.string().min(1).max(128),author:text,stateRevision:z.number().int().nonnegative().safe()}),
 destination:repository.extend({audienceDigest:z.string().regex(/^[a-f0-9]{64}$/),audienceVersion:z.literal('repository-members-v1')}),
 issue:z.object({number,title:z.string().min(1).max(200),body:z.string().max(20000),state:z.enum(['open','closed']),author:text,created_at:z.string().max(128),updated_at:z.string().max(128),closed_by:text.nullable()}).strict(),
 comments:z.array(z.object({id:number,subject:z.string().max(128),author:text,body:z.string().max(10000),path:z.string().max(400).nullable(),line:number.nullable(),commit:z.string().max(40).nullable(),created_at:z.string().max(128)}).strict()).max(1000),
 features:z.json(),attachments:z.array(issueTransferAttachmentSchema).max(10),
 attribution:z.object({issueActorId:text.min(1).nullable(),commentActorIds:z.record(z.string().regex(/^[1-9][0-9]{0,15}$/),text.min(1).nullable()),identity:z.literal('source-origin')}).strict(),
}).strict();
export type IssueTransferManifest=z.infer<typeof issueTransferManifestSchema>;
export type IssueTransferAttachment=z.infer<typeof issueTransferAttachmentSchema>;
export type IssueTransferPhase='locked'|'frozen'|'reserved'|'copying'|'ready'|'active'|'completed';
export interface IssueTransferRecord {version:1;manifest:IssueTransferManifest;phase:IssueTransferPhase;destinationNumber?:number;activatedDestinationNumber?:number;finalized?:boolean}
export interface IssueTransferCopyAttempt {nonce:string;phase:'issued'|'unknown'|'verified'}
export class IssueTransferError extends Error{constructor(message:string,readonly status:number){super(message);}}
export function ensureIssueTransferSchema(storage:Pick<DurableObjectStorage,'sql'>){
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_locks(issue_number INTEGER PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,document TEXT NOT NULL)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_incoming(issue_number INTEGER PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,document TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 0)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_receipts(request_id TEXT PRIMARY KEY,identity TEXT NOT NULL,document TEXT NOT NULL)');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_capacity(request_id TEXT PRIMARY KEY,bytes INTEGER NOT NULL)');
 storage.sql.exec('INSERT OR IGNORE INTO issue_transfer_capacity SELECT request_id,length(CAST(identity AS BLOB))*4+8192 FROM issue_transfer_receipts');
 storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_transfer_copy_attempts(request_id TEXT NOT NULL,attachment_id TEXT NOT NULL,document TEXT NOT NULL,PRIMARY KEY(request_id,attachment_id))');
}
export function assertIssueWritable(storage:Pick<DurableObjectStorage,'sql'>,issueNumber:number,requestId?:string){
 ensureIssueTransferSchema(storage);
 const lock=storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',issueNumber).toArray()[0];
 if(lock&&lock.request_id!==requestId)throw new IssueTransferError('Issue transfer is in progress; original content is preserved',409);
 const incoming=storage.sql.exec<{request_id:string;active:number}>('SELECT request_id,active FROM issue_transfer_incoming WHERE issue_number=?',issueNumber).toArray()[0];
 if(incoming&&incoming.active!==1&&incoming.request_id!==requestId)throw new IssueTransferError('Incoming issue transfer is not active',409);
}
type Verify=(manifest:IssueTransferManifest,destinationNumber:number)=>boolean;
/** Both repositories retain immutable receipts. Destination rows remain hidden
 * until their verified content is ready; a completed source lock stays durable. */
export class IssueTransferLedger {
 constructor(private readonly storage:DurableObjectStorage){ensureIssueTransferSchema(storage);}
 read(requestId:string):IssueTransferRecord|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_transfer_receipts WHERE request_id=?',requestId).toArray()[0];return row?JSON.parse(row.document) as IssueTransferRecord:undefined;}
 private validate(value:IssueTransferManifest){const manifest=issueTransferManifestSchema.parse(value);if(manifest.source.projectId===manifest.destination.projectId)throw new IssueTransferError('Issue transfer requires another repository',400);if(manifest.issue.number!==manifest.source.number||manifest.issue.created_at!==manifest.source.createdAt||manifest.issue.author!==manifest.source.author)throw new IssueTransferError('Original issue identity does not match transfer',409);if(new Set(manifest.attachments.flatMap(row=>[row.id,row.destinationId])).size!==manifest.attachments.length*2)throw new IssueTransferError('Source and destination attachment identities must be distinct',400);if(new Set(manifest.comments.map(row=>row.id)).size!==manifest.comments.length||manifest.comments.some(row=>row.subject!=='issue:'+manifest.source.number))throw new IssueTransferError('Comments are outside the original issue identity',400);const commentIds=new Set(manifest.comments.map(row=>String(row.id)));if(Object.keys(manifest.attribution.commentActorIds).length!==commentIds.size||Object.keys(manifest.attribution.commentActorIds).some(id=>!commentIds.has(id)))throw new IssueTransferError('Original comment attribution identities do not match',400);if(new TextEncoder().encode(JSON.stringify(manifest)).length>2*1024*1024)throw new IssueTransferError('Issue transfer manifest capacity reached',413);return manifest;}
 private existing(manifest:IssueTransferManifest){const row=this.storage.sql.exec<{identity:string;document:string}>('SELECT identity,document FROM issue_transfer_receipts WHERE request_id=?',manifest.requestId).toArray()[0];if(row&&row.identity!==JSON.stringify(manifest))throw new IssueTransferError('Original issue transfer request cannot change',409);return row?JSON.parse(row.document) as IssueTransferRecord:undefined;}
 private save(record:IssueTransferRecord){this.storage.sql.exec('INSERT INTO issue_transfer_receipts VALUES(?,?,?) ON CONFLICT(request_id) DO UPDATE SET document=excluded.document',record.manifest.requestId,JSON.stringify(record.manifest),JSON.stringify(record));return record;}
 private capacity(manifest:IssueTransferManifest){
  if(this.storage.sql.exec<{count:number}>('SELECT COUNT(*) AS count FROM issue_transfer_receipts').toArray()[0]!.count>=10000)throw new IssueTransferError('Issue transfer receipt capacity reached',413);
  const charge=new TextEncoder().encode(JSON.stringify(manifest)).length*4+8192;
  const reserved=this.storage.sql.exec<{bytes:number}>('SELECT COALESCE(SUM(bytes),0) AS bytes FROM issue_transfer_capacity').toArray()[0]!.bytes;
  const actual=this.storage.sql.exec<{bytes:number}>(`SELECT COALESCE(SUM(bytes),0) AS bytes FROM (
   SELECT length(CAST(identity AS BLOB))+length(CAST(document AS BLOB)) AS bytes FROM issue_transfer_receipts
   UNION ALL SELECT length(CAST(document AS BLOB)) FROM issue_transfer_locks
   UNION ALL SELECT length(CAST(document AS BLOB)) FROM issue_transfer_incoming
   UNION ALL SELECT length(CAST(document AS BLOB)) FROM issue_transfer_copy_attempts
  )`).toArray()[0]!.bytes;
  if(!Number.isSafeInteger(reserved)||!Number.isSafeInteger(actual)||Math.max(reserved,actual)+charge>128*1024*1024)throw new IssueTransferError('Issue transfer storage capacity reached; original issues remain preserved',413);
  this.storage.sql.exec('INSERT INTO issue_transfer_capacity VALUES(?,?)',manifest.requestId,charge);
 }
 lock(value:IssueTransferManifest,assert:()=>void):IssueTransferRecord{return this.storage.transactionSync(()=>{assert();const manifest=this.validate(value),old=this.existing(manifest);if(old)return old;this.capacity(manifest);assertIssueWritable(this.storage,manifest.source.number);assert();const record:IssueTransferRecord={version:1,manifest,phase:'locked'};this.storage.sql.exec('INSERT INTO issue_transfer_locks VALUES(?,?,?)',manifest.source.number,manifest.requestId,JSON.stringify(record));return this.save(record);});}
 assertWritable(issueNumber:number,requestId?:string){assertIssueWritable(this.storage,issueNumber,requestId);}
 freeze(value:IssueTransferManifest,assert:()=>void){return this.storage.transactionSync(()=>{const record=this.lock(value,assert);assert();if(record.phase!=='locked')return record;const next={...record,phase:'frozen' as const};this.storage.sql.exec('UPDATE issue_transfer_locks SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.manifest.source.number,record.manifest.requestId);return this.save(next);});}
 reserve(value:IssueTransferManifest,allocate:()=>number,assert:()=>void){return this.storage.transactionSync(()=>{assert();const manifest=this.validate(value),old=this.existing(manifest);if(old){if(old.destinationNumber===undefined)throw new IssueTransferError('Transfer receipt belongs to the source repository',409);return old;}this.capacity(manifest);const destinationNumber=allocate();number.parse(destinationNumber);assert();const record:IssueTransferRecord={version:1,manifest,phase:'reserved',destinationNumber};this.storage.sql.exec('INSERT INTO issue_transfer_incoming VALUES(?,?,?,0)',destinationNumber,manifest.requestId,JSON.stringify(record));this.storage.sql.exec('INSERT INTO issue_transfer_locks VALUES(?,?,?)',destinationNumber,manifest.requestId,JSON.stringify(record));return this.save(record);});}
 private destination(requestId:string){const record=this.read(requestId);if(!record||record.destinationNumber===undefined)throw new IssueTransferError('Incoming issue transfer is unavailable',404);return record as IssueTransferRecord&{destinationNumber:number};}
 readCopy(requestId:string,attachmentId:string):IssueTransferCopyAttempt|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_transfer_copy_attempts WHERE request_id=? AND attachment_id=?',requestId,attachmentId).toArray()[0];return row?JSON.parse(row.document) as IssueTransferCopyAttempt:undefined;}
 beginCopy(requestId:string,attachmentId:string,nonce:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();z.uuid().parse(nonce);const record=this.destination(requestId);if(!record.manifest.attachments.some(row=>row.id===attachmentId))throw new IssueTransferError('Attachment is outside original transfer manifest',409);const prior=this.readCopy(requestId,attachmentId);if(prior){if(prior.nonce!==nonce)throw new IssueTransferError('Original attachment copy nonce cannot change',409);return{...prior,newlyIssued:false};}if(record.phase!=='reserved'&&record.phase!=='copying')throw new IssueTransferError('Incoming transfer no longer accepts copy attempts',409);assert();const attempt:IssueTransferCopyAttempt={nonce,phase:'issued'};this.storage.sql.exec('INSERT INTO issue_transfer_copy_attempts VALUES(?,?,?)',requestId,attachmentId,JSON.stringify(attempt));const next={...record,phase:'copying' as const};this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=?',JSON.stringify(next),record.destinationNumber);this.save(next);return{...attempt,newlyIssued:true};});}
 private markCopy(requestId:string,attachmentId:string,nonce:string,phase:'unknown'|'verified',assert:()=>void){return this.storage.transactionSync(()=>{assert();this.destination(requestId);const prior=this.readCopy(requestId,attachmentId);if(!prior||prior.nonce!==nonce)throw new IssueTransferError('Original attachment copy ownership changed',409);if(prior.phase==='verified')return prior;assert();const next:IssueTransferCopyAttempt={nonce,phase};this.storage.sql.exec('UPDATE issue_transfer_copy_attempts SET document=? WHERE request_id=? AND attachment_id=?',JSON.stringify(next),requestId,attachmentId);return next;});}
 markCopyUnknown(requestId:string,attachmentId:string,nonce:string,assert:()=>void){return this.markCopy(requestId,attachmentId,nonce,'unknown',assert);}
 markCopyVerified(requestId:string,attachmentId:string,nonce:string,assert:()=>void){return this.markCopy(requestId,attachmentId,nonce,'verified',assert);}
 markReady(requestId:string,verified:Verify,assert:()=>void){return this.storage.transactionSync(()=>{assert();const record=this.destination(requestId);if(record.phase==='active')return record;if(!['reserved','copying','ready'].includes(record.phase))throw new IssueTransferError('Incoming transfer phase changed',409);if(record.manifest.attachments.some(attachment=>this.readCopy(requestId,attachment.id)?.phase!=='verified')||!verified(record.manifest,record.destinationNumber))throw new IssueTransferError('Incoming issue attachments are not fully verified',409);assert();const next={...record,phase:'ready' as const};this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=?',JSON.stringify(next),record.destinationNumber);return this.save(next);});}
 activate(requestId:string,verified:Verify,assert:()=>void){return this.storage.transactionSync(()=>{assert();const record=this.destination(requestId);if(record.phase==='active')return record;if(record.phase!=='ready'||record.manifest.attachments.some(attachment=>this.readCopy(requestId,attachment.id)?.phase!=='verified')||!verified(record.manifest,record.destinationNumber))throw new IssueTransferError('Incoming issue transfer is not ready',409);assert();const next={...record,phase:'active' as const};this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=?,active=1 WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.destinationNumber,requestId);return this.save(next);});}
 finishDestination(requestId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const record=this.destination(requestId);if(record.phase!=='active')throw new IssueTransferError('Incoming issue is not active',409);if(record.finalized)return record;const lock=this.storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',record.destinationNumber).toArray()[0];if(!lock||lock.request_id!==requestId)throw new IssueTransferError('Destination transfer lock ownership changed',409);assert();const next={...record,finalized:true};this.storage.sql.exec('DELETE FROM issue_transfer_locks WHERE issue_number=? AND request_id=?',record.destinationNumber,requestId);this.storage.sql.exec('UPDATE issue_transfer_incoming SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.destinationNumber,requestId);return this.save(next);});}
 bindDestination(requestId:string,destinationNumber:number,assert:()=>void){return this.storage.transactionSync(()=>{assert();number.parse(destinationNumber);const record=this.read(requestId);if(!record||record.destinationNumber!==undefined||!['frozen','completed'].includes(record.phase))throw new IssueTransferError('Frozen source issue transfer is unavailable',409);if(record.activatedDestinationNumber!==undefined&&record.activatedDestinationNumber!==destinationNumber)throw new IssueTransferError('Original transfer destination number cannot change',409);assert();const next={...record,activatedDestinationNumber:destinationNumber};this.storage.sql.exec('UPDATE issue_transfer_locks SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.manifest.source.number,requestId);return this.save(next);});}
 complete(requestId:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const record=this.read(requestId);if(!record||record.destinationNumber!==undefined||record.activatedDestinationNumber===undefined||!['frozen','completed'].includes(record.phase))throw new IssueTransferError('Frozen source issue transfer and confirmed destination are unavailable',409);const lock=this.storage.sql.exec<{request_id:string}>('SELECT request_id FROM issue_transfer_locks WHERE issue_number=?',record.manifest.source.number).toArray()[0];if(lock?.request_id!==requestId)throw new IssueTransferError('Source transfer lock ownership changed',409);if(record.phase==='completed')return record;assert();const next={...record,phase:'completed' as const};this.storage.sql.exec('UPDATE issue_transfer_locks SET document=? WHERE issue_number=? AND request_id=?',JSON.stringify(next),record.manifest.source.number,requestId);return this.save(next);});}
}
