import {z} from 'zod';
import type {IssueTransferManifest,IssueTransferRecord,IssueTransferPhase} from './issue-transfer';
/** Manifest proof compares values, never insertion order of object properties. */
export function canonicalTransferJson(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value)??'null';if(Array.isArray(value))return '['+value.map(canonicalTransferJson).join(',')+']';return '{'+Object.entries(value).filter(([,item])=>item!==undefined).sort(([left],[right])=>left<right?-1:left>right?1:0).map(([key,item])=>JSON.stringify(key)+':'+canonicalTransferJson(item)).join(',')+'}';}
export const issueTransferRequestSchema=z.object({destinationProjectId:z.string().min(1).max(256),expectedRevision:z.number().int().nonnegative().safe(),requestId:z.uuid(),confirmed:z.literal(true),expectedManifestDigest:z.string().regex(/^[a-f0-9]{64}$/),expectedDestinationIncarnation:z.uuid()}).strict();
export type IssueTransferRequest=z.infer<typeof issueTransferRequestSchema>;
export interface IssueTransferCancellationSuccess {requestId:string;cancelId:string;cancelled:true;replayed:boolean;sourceUnlocked:true;physicalCleanup:'pending'|'confirmed'}
export interface IssueTransferCancellationRefusal {requestId:string;cancelId:string;cancelled:false;reason:'destination-active';phase:'active';sourceUnlocked:false}
export type IssueTransferCancellationResult=IssueTransferCancellationSuccess|IssueTransferCancellationRefusal;
export interface IssueTransferPendingRecovery {originalRequest:IssueTransferRequest;canResumeOriginal:boolean;canCancel:true}
export interface IssueTransferReadonlyCancellationReceipt {requestId:string;cancelId:string;cancelled:true;sourceUnlocked:true;physicalCleanup:'pending'|'confirmed';canReplayCancellation:boolean}
export interface IssueTransferView {requestId:string;phase:IssueTransferPhase;source:{projectId:string;number:number};destination:{projectId:string;number?:number};audience:'repository-members';audienceVersion:'repository-members-v1';manifestDigest:string;completed:boolean;cancelled?:boolean;cancelId?:string;cancellationRefused?:'destination-active';cancellationReceipt?:IssueTransferReadonlyCancellationReceipt}
export interface IssueTransferPreview {manifestDigest:string;source:IssueTransferManifest['source'];destination:IssueTransferManifest['destination']&{audience:'repository-members'};audienceVersion:'repository-members-v1';manifest:{issue:IssueTransferManifest['issue'];comments:IssueTransferManifest['comments'];features:IssueTransferManifest['features'];attribution:IssueTransferManifest['attribution'];attachments:Omit<IssueTransferManifest['attachments'][number],'destinationId'>[]}}
export function issueTransferView(record:IssueTransferRecord):IssueTransferView{return{requestId:record.manifest.requestId,phase:record.phase,source:{projectId:record.manifest.source.projectId,number:record.manifest.source.number},destination:{projectId:record.manifest.destination.projectId,...(record.destinationNumber===undefined&&record.activatedDestinationNumber===undefined?{}:{number:record.destinationNumber??record.activatedDestinationNumber})},audience:'repository-members' as const,audienceVersion:'repository-members-v1' as const,manifestDigest:record.manifest.previewDigest,completed:record.phase==='completed',...(record.phase==='cancelled'?{cancelled:true}:{}),...(record.cancelId?{cancelId:record.cancelId}:{})};}
