import {createHash} from 'node:crypto';
import {z} from 'zod';
import {DurableLfsStore,LfsStorageError,type LfsScope} from './lfs-store';
export const ISSUE_ATTACHMENT_BYTES=5*1024*1024;
export const issueAttachmentInputSchema=z.object({id:z.uuid(),name:z.string().trim().min(1).max(150).refine(value=>!/[\x00-\x1f\x7f/\\]/.test(value)&&value!=='.'&&value!=='..','Invalid filename'),sha256:z.string().regex(/^[a-f0-9]{64}$/),size:z.number().int().nonnegative().safe().max(ISSUE_ATTACHMENT_BYTES)}).strict();
export type IssueAttachmentInput=z.infer<typeof issueAttachmentInputSchema>;
export type IssueAttachmentReply<T>={ok:true;value:T}|{ok:false;status:number;error:string};
export interface IssueAttachmentScope extends LfsScope {issue:number;issueCreatedAt:string;issueAuthor:string}
export interface IssueAttachment extends IssueAttachmentInput {scope:IssueAttachmentScope;authorId:string;author:string;createdAt:string;phase:'pending'|'verified'|'removed';retentionUntil?:number}
export interface IssueAttachmentView extends IssueAttachmentInput {authorId:string;author:string;createdAt:string;phase:IssueAttachment['phase'];canRemove:boolean;canReconcile:boolean}
export function attachmentDisposition(name:string){const fallback=name.replace(/[^A-Za-z0-9._ -]/g,'_').replace(/^[. ]+|[. ]+$/g,'').slice(0,150)||'attachment';const encoded=encodeURIComponent(name).replace(/['()*]/g,value=>'%'+value.charCodeAt(0).toString(16).toUpperCase());return `attachment; filename="${fallback}"; filename*=UTF-8''${encoded}`;}
/** Metadata identities are issue-bound; binary content uses an isolated durable
 * storage profile, sharing the proved streaming/receipt engine, not Git LFS data. */
export class IssueAttachments {
 private readonly blobs:DurableLfsStore;private readonly activeRetirements=new Set<string>();
 constructor(private readonly storage:DurableObjectStorage){this.blobs=new DurableLfsStore(storage,'issue-attachments');storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_attachment_retirements(incarnation TEXT NOT NULL,sha256 TEXT NOT NULL,nonce TEXT NOT NULL,phase TEXT NOT NULL,PRIMARY KEY(incarnation,sha256))');storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_attachment_refs(id TEXT PRIMARY KEY,issue_number INTEGER NOT NULL,document TEXT NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_attachment_input_proofs(attachment_id TEXT PRIMARY KEY,identity TEXT NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS issue_attachment_transfer_cancellations(id TEXT PRIMARY KEY,scope TEXT NOT NULL)');const columns=storage.sql.exec<{name:string}>('PRAGMA table_info(issue_attachment_retirements)').toArray().map(row=>row.name);if(!columns.includes('nonce'))storage.sql.exec("ALTER TABLE issue_attachment_retirements ADD COLUMN nonce TEXT NOT NULL DEFAULT ''");if(!columns.includes('phase'))storage.sql.exec("ALTER TABLE issue_attachment_retirements ADD COLUMN phase TEXT NOT NULL DEFAULT 'uncertain'");}
 private get(id:string):IssueAttachment|undefined{const row=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_attachment_refs WHERE id=?',id).toArray()[0];return row?JSON.parse(row.document) as IssueAttachment:undefined;}
 private save(value:IssueAttachment){this.storage.sql.exec('UPDATE issue_attachment_refs SET document=? WHERE id=?',JSON.stringify(value),value.id);}
 list(scope:IssueAttachmentScope){const rows=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_attachment_refs WHERE issue_number=? ORDER BY id LIMIT 10001',scope.issue).toArray();if(rows.length>10000)throw new LfsStorageError('Attachment reference capacity exceeded',413);return rows.map(row=>JSON.parse(row.document) as IssueAttachment).filter(value=>JSON.stringify(value.scope)===JSON.stringify(scope));}
 current(scope:IssueAttachmentScope,id:string){z.uuid().parse(id);const saved=this.get(id);if(!saved||JSON.stringify(saved.scope)!==JSON.stringify(scope)||saved.phase==='removed')throw new LfsStorageError('Attachment not found',404);return saved;}
 prepare(scope:IssueAttachmentScope,value:unknown,actor:{userId:string;displayName:string},assert:()=>void){const input=issueAttachmentInputSchema.parse(value);return this.storage.transactionSync(()=>{assert();if(this.storage.sql.exec('SELECT id FROM issue_attachment_transfer_cancellations WHERE id=?',input.id).toArray().length)throw new LfsStorageError('This destination transfer attachment was cancelled and cannot be recreated',410);if(this.storage.sql.exec('SELECT sha256 FROM issue_attachment_retirements WHERE incarnation=? AND sha256=?',scope.incarnation,input.sha256).toArray().length)throw new LfsStorageError('Original attachment bytes are being retired; retry after cleanup is confirmed',409);const previous=this.get(input.id);if(previous){if(JSON.stringify(previous.scope)!==JSON.stringify(scope)||previous.authorId!==actor.userId||previous.name!==input.name||previous.sha256!==input.sha256||previous.size!==input.size)throw new LfsStorageError('The original attachment request cannot change',409);if(previous.phase==='removed')throw new LfsStorageError('This attachment request was removed and cannot be recreated',410);if(previous.phase==='pending')this.blobs.admitObject(scope,{oid:input.sha256,size:input.size});return previous;}
  const usage=this.storage.sql.exec<{count:number;active:number}>("SELECT COUNT(*) AS count,COALESCE(SUM(CASE WHEN json_extract(document,'$.phase')!='removed' THEN 1 ELSE 0 END),0) AS active FROM issue_attachment_refs").toArray()[0]!;if(usage.count>=10000)throw new LfsStorageError('Attachment audit capacity reached; original request identities remain preserved',413);if(usage.active>=256||this.list(scope).filter(row=>row.phase!=='removed').length>=10)throw new LfsStorageError('An issue can have up to ten attachments; remove an old file before adding another',413);
  this.blobs.admitObject(scope,{oid:input.sha256,size:input.size});const saved:IssueAttachment={...input,scope,authorId:actor.userId,author:actor.displayName,createdAt:new Date().toISOString(),phase:'pending'};this.storage.sql.exec('INSERT INTO issue_attachment_refs VALUES(?,?,?)',saved.id,scope.issue,JSON.stringify(saved));return saved;
 });}
 private inputIdentity(saved:IssueAttachment){return JSON.stringify([saved.id,saved.scope,saved.authorId,saved.sha256,saved.size]);}
 private recordInputProof(scope:IssueAttachmentScope,id:string,original:IssueAttachment){this.storage.transactionSync(()=>{const current=this.current(scope,id),identity=this.inputIdentity(current);if(identity!==this.inputIdentity(original))throw new LfsStorageError('Original attachment input identity changed',403);const old=this.storage.sql.exec<{identity:string}>('SELECT identity FROM issue_attachment_input_proofs WHERE attachment_id=?',id).toArray()[0];if(old&&old.identity!==identity)throw new LfsStorageError('Original attachment input proof cannot change',409);this.storage.sql.exec('INSERT OR IGNORE INTO issue_attachment_input_proofs VALUES(?,?)',id,identity);});}
 private hasInputProof(saved:IssueAttachment){return this.storage.sql.exec('SELECT attachment_id FROM issue_attachment_input_proofs WHERE attachment_id=? AND identity=?',saved.id,this.inputIdentity(saved)).toArray().length===1;}
 async upload(scope:IssueAttachmentScope,id:string,stream:ReadableStream<Uint8Array>,declaredSize:number|undefined,bucket:R2Bucket,authorize:()=>Promise<void>,actorId:string){await authorize();const saved=this.current(scope,id);if(saved.authorId!==actorId)throw new LfsStorageError('Only the original uploader can resume these bytes',403);if(declaredSize!==undefined&&declaredSize!==saved.size)throw new LfsStorageError('Attachment size differs from its original request',409);
  const check=async()=>{await authorize();const current=this.current(scope,id);if(current.authorId!==actorId||current.sha256!==saved.sha256||current.size!==saved.size)throw new LfsStorageError('Original attachment authority changed',403);};
  await this.blobs.upload(scope,{oid:saved.sha256,size:saved.size},stream,bucket,check,()=>this.recordInputProof(scope,id,saved));await check();return this.storage.transactionSync(()=>{const current=this.current(scope,id);current.phase='verified';this.save(current);return current;});
 }
 async reconcile(scope:IssueAttachmentScope,id:string,bucket:R2Bucket,authorize:()=>Promise<void>){await authorize();const original=this.current(scope,id);if(!this.hasInputProof(original))throw new LfsStorageError('Upload the original file bytes before checking this attachment',409);const result=await this.blobs.reconcile(scope,original.sha256,bucket);await authorize();const confirmed=await this.blobs.confirm(scope,original.sha256,bucket,async()=>{await authorize();this.current(scope,id);});await authorize();const attachment=this.storage.transactionSync(()=>{const current=this.current(scope,id);if(current.sha256!==original.sha256||current.size!==original.size||current.authorId!==original.authorId)throw new LfsStorageError('Original attachment identity changed',409);if(confirmed){current.phase='verified';this.save(current);}return current;});return{attachment,reconciled:result.reconciled};}
 /** Backend-only source snapshot. A verified shared blob is insufficient: this
  * exact issue attachment must own its original, fully checked input proof. */
 transferSource(scope:IssueAttachmentScope,id:string){const saved=this.current(scope,id);if(saved.phase!=='verified'||!this.hasInputProof(saved))throw new LfsStorageError('Original verified attachment producer proof is unavailable',409);return{...saved,producerIdentity:this.inputIdentity(saved)};}
 async downloadForTransfer(scope:IssueAttachmentScope,id:string,producerIdentity:string,bucket:R2Bucket,authorize:()=>Promise<void>){
  await authorize();const original=this.transferSource(scope,id);if(original.producerIdentity!==producerIdentity)throw new LfsStorageError('Original attachment producer identity changed',409);
  const check=async()=>{await authorize();if(this.transferSource(scope,id).producerIdentity!==producerIdentity)throw new LfsStorageError('Original attachment producer proof changed',409);};
  const result=await this.download(scope,id,bucket,check);await check();return{attachment:this.transferSource(scope,id),body:result.body};
 }
 /** Finalization observes an already-verified generation without storage repair. */
 async readbackForFinalization(scope:IssueAttachmentScope,id:string,bucket:R2Bucket,authorize:()=>Promise<void>){
  await authorize();const original=this.transferSource(scope,id),identity=original.producerIdentity;
  const check=async()=>{await authorize();const current=this.transferSource(scope,id);if(current.producerIdentity!==identity||current.name!==original.name||current.createdAt!==original.createdAt)throw new LfsStorageError('Original finalization attachment changed',409);};
  const result=await this.downloadForTransfer(scope,id,identity,bucket,check),reader=result.body.getReader(),hash=createHash('sha256');let size=0;
  try{for(;;){await check();const next=await reader.read();await check();if(next.done)break;size+=next.value.byteLength;if(size>original.size||size>ISSUE_ATTACHMENT_BYTES)throw new LfsStorageError('Finalization attachment exceeds its frozen bound',413);hash.update(next.value);}if(size!==original.size||hash.digest('hex')!==original.sha256)throw new LfsStorageError('Finalization attachment hash or size differs',422);await check();return{attachment:this.transferSource(scope,id)};}
  finally{await reader.cancel().catch(()=>{});reader.releaseLock();}
 }
 async confirmForTransfer(scope:IssueAttachmentScope,id:string,bucket:R2Bucket,authorize:()=>Promise<void>){
  await authorize();const original=this.current(scope,id);if(!this.hasInputProof(original))throw new LfsStorageError('Original transfer bytes have not been validated',409);
  await this.reconcile(scope,id,bucket,authorize);await authorize();const saved=this.transferSource(scope,id);if(saved.sha256!==original.sha256||saved.size!==original.size||saved.authorId!==original.authorId)throw new LfsStorageError('Original transfer attachment changed',409);return{attachment:saved};
 }
 async download(scope:IssueAttachmentScope,id:string,bucket:R2Bucket,authorize:()=>Promise<void>){await authorize();const saved=this.current(scope,id);if(saved.phase!=='verified')throw new LfsStorageError('Attachment upload is not yet confirmed',409);const object=await this.blobs.download(scope,saved.sha256,bucket,async()=>{await authorize();if(this.current(scope,id).phase!=='verified')throw new LfsStorageError('Attachment was removed',404);});return{attachment:saved,body:object.body};}
 remove(scope:IssueAttachmentScope,id:string,assert:()=>void){return this.storage.transactionSync(()=>{assert();const saved=this.get(id);if(!saved||JSON.stringify(saved.scope)!==JSON.stringify(scope))throw new LfsStorageError('Attachment not found',404);if(saved.phase==='removed')return saved;saved.phase='removed';saved.retentionUntil=Date.now()+7*24*60*60*1000;this.save(saved);return saved;});}
 /** Called only after the controller proves its irreversible destination
  * cancellation fence. It never receives or retires the source repository. */
 async cancelTransfer(scope:IssueAttachmentScope,destinationIds:readonly string[],bucket:R2Bucket,authorize:()=>Promise<void>){
  const ids=z.array(z.uuid()).max(10).parse(destinationIds);if(new Set(ids).size!==ids.length)throw new LfsStorageError('Duplicate destination cancellation identity',400);
  await authorize();const now=Date.now(),encoded=JSON.stringify(scope);
  this.storage.transactionSync(()=>{
   const rows=ids.map(id=>{const previous=this.storage.sql.exec<{scope:string}>('SELECT scope FROM issue_attachment_transfer_cancellations WHERE id=?',id).toArray()[0];if(previous&&previous.scope!==encoded)throw new LfsStorageError('Original destination cancellation scope changed',409);const saved=this.get(id);if(saved&&JSON.stringify(saved.scope)!==encoded)throw new LfsStorageError('Destination attachment scope differs',409);return saved;});
   const fresh=ids.filter(id=>!this.storage.sql.exec('SELECT id FROM issue_attachment_transfer_cancellations WHERE id=?',id).toArray().length);if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM issue_attachment_transfer_cancellations').toArray()[0]!.n+fresh.length>100000)throw new LfsStorageError('Destination cancellation audit capacity reached',413);
   for(const id of ids)this.storage.sql.exec('INSERT OR IGNORE INTO issue_attachment_transfer_cancellations VALUES(?,?)',id,encoded);
   for(const saved of rows){if(!saved)continue;saved.phase='removed';saved.retentionUntil=now;this.save(saved);}
   return rows.filter((saved):saved is IssueAttachment=>saved!==undefined);
  });
  await authorize();
  let error:string|undefined;
  try{await this.retention(scope,bucket,authorize,now,ids);}catch{error='Original destination storage execution remains unconfirmed';}
  await authorize();
  const status=this.cancelledTransferCleanupSnapshot(scope,ids,now);return error?{...status,physicalCleanup:'pending' as const,reason:error}:status;
 }
 private cancelledTransferCleanupSnapshot(scope:IssueAttachmentScope,destinationIds:readonly string[],now=Date.now()){
  const ids=z.array(z.uuid()).max(10).parse(destinationIds);if(new Set(ids).size!==ids.length)throw new LfsStorageError('Duplicate cancellation inspection identity',400);const encoded=JSON.stringify(scope);
  const originals=ids.flatMap(id=>{const marker=this.storage.sql.exec<{scope:string}>('SELECT scope FROM issue_attachment_transfer_cancellations WHERE id=?',id).toArray()[0];if(!marker||marker.scope!==encoded)throw new LfsStorageError('Exact permanent destination cancellation marker is unavailable',409);const saved=this.get(id);if(saved&&(JSON.stringify(saved.scope)!==encoded||saved.phase!=='removed'))throw new LfsStorageError('Destination cancellation reference is not fenced',409);return saved?[saved]:[];});
  const all=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_attachment_refs LIMIT 10001').toArray();if(all.length>10000)throw new LfsStorageError('Cancellation reference inventory exceeds its bound',413);
  const refs=all.map(row=>JSON.parse(row.document) as IssueAttachment),hashes=[...new Set(originals.map(saved=>saved.sha256))];let deletedObjects=0,sharedObjectsRetained=0,pendingObjects=0;
  for(const sha256 of hashes){
   const shared=refs.some(saved=>!ids.includes(saved.id)&&saved.scope.incarnation===scope.incarnation&&saved.sha256===sha256&&(saved.phase!=='removed'||(saved.retentionUntil??Infinity)>now));
   const hold=this.storage.sql.exec('SELECT nonce FROM issue_attachment_retirements WHERE incarnation=? AND sha256=?',scope.incarnation,sha256).toArray().length,state=this.blobs.cleanupState(scope,sha256),active=this.activeRetirements.has(scope.incarnation+':'+sha256);
   if(hold||state.pendingWrites||state.activeTransfer||active){pendingObjects++;continue;}
   if(shared){sharedObjectsRetained++;continue;}
   if(!state.objectPresent)deletedObjects++;else pendingObjects++;
  }
  return{logicalCancelled:true as const,physicalCleanup:pendingObjects?'pending' as const:'confirmed' as const,deletedObjects,sharedObjectsRetained,pendingObjects};
 }
 async inspectCancelledTransferCleanup(scope:IssueAttachmentScope,destinationIds:readonly string[],authorize:()=>Promise<void>){await authorize();this.cancelledTransferCleanupSnapshot(scope,destinationIds);await authorize();return this.cancelledTransferCleanupSnapshot(scope,destinationIds);}
 references(scope:IssueAttachmentScope){return{version:1 as const,source:scope,bytesIncluded:false as const,restoreSupported:false as const,attachments:this.list(scope).map(({id,name,sha256,size,authorId,author,createdAt,phase,retentionUntil})=>({id,name,sha256,size,authorId,author,createdAt,phase,...(retentionUntil===undefined?{}:{retentionUntil})}))};}
 async retention(scope:IssueAttachmentScope,bucket:R2Bucket,authorize:()=>Promise<void>,now=Date.now(),onlyIds?:readonly string[]){await authorize();let retired=0;for(const saved of this.list(scope).filter(value=>value.phase==='removed'&&(value.retentionUntil??Infinity)<=now&&(!onlyIds||onlyIds.includes(value.id))).slice(0,10)){
  const key=scope.incarnation+':'+saved.sha256;if(this.activeRetirements.has(key))throw new LfsStorageError('Attachment retention cleanup is already active',409);
  const hold=this.storage.transactionSync(()=>{const rows=this.storage.sql.exec<{document:string}>('SELECT document FROM issue_attachment_refs LIMIT 10001').toArray();if(rows.length>10000)throw new LfsStorageError('Attachment retention inventory exceeds its bound',413);if(rows.map(row=>JSON.parse(row.document) as IssueAttachment).some(value=>value.id!==saved.id&&value.scope.incarnation===scope.incarnation&&value.sha256===saved.sha256&&(value.phase!=='removed'||(value.retentionUntil??Infinity)>now)))return null;
   const old=this.storage.sql.exec<{nonce:string;phase:string}>('SELECT nonce,phase FROM issue_attachment_retirements WHERE incarnation=? AND sha256=?',scope.incarnation,saved.sha256).toArray()[0];if(old){if(old.phase==='deleting'||old.phase==='uncertain'||!old.nonce)throw new LfsStorageError('Original attachment deletion outcome is unconfirmed; its hold remains preserved',409);return old;}
   const nonce=crypto.randomUUID();this.storage.sql.exec("INSERT INTO issue_attachment_retirements(incarnation,sha256,nonce,phase) VALUES(?,?,?,'prepared')",scope.incarnation,saved.sha256,nonce);return{nonce,phase:'prepared'};
  });if(!hold)continue;this.activeRetirements.add(key);
  const setPhase=(phase:string)=>{if(!this.storage.sql.exec('SELECT nonce FROM issue_attachment_retirements WHERE incarnation=? AND sha256=? AND nonce=?',scope.incarnation,saved.sha256,hold.nonce).toArray().length)throw new LfsStorageError('Original attachment retirement owner changed',409);this.storage.sql.exec('UPDATE issue_attachment_retirements SET phase=? WHERE incarnation=? AND sha256=? AND nonce=?',phase,scope.incarnation,saved.sha256,hold.nonce);};
  try{if(hold.phase!=='confirmed'){await authorize();await this.blobs.retire(scope,saved.sha256,bucket,async()=>{await authorize();setPhase('deleting');},()=>{setPhase('prepared');});setPhase('confirmed');}await authorize();this.storage.sql.exec("DELETE FROM issue_attachment_retirements WHERE incarnation=? AND sha256=? AND nonce=? AND phase='confirmed'",scope.incarnation,saved.sha256,hold.nonce);retired++;}
  catch(error){const current=this.storage.sql.exec<{phase:string}>('SELECT phase FROM issue_attachment_retirements WHERE incarnation=? AND sha256=? AND nonce=?',scope.incarnation,saved.sha256,hold.nonce).toArray()[0];if(current?.phase==='deleting')setPhase('uncertain');throw error;}finally{this.activeRetirements.delete(key);}
 }return{retired,bytesDeletionConfirmed:retired>0};}
 async cleanupForDeletion(projectId:string,bucket:R2Bucket){if(this.activeRetirements.size||this.storage.sql.exec("SELECT nonce FROM issue_attachment_retirements WHERE phase IN ('deleting','uncertain') LIMIT 1").toArray().length)throw new LfsStorageError('Original attachment retention execution remains unconfirmed; records preserved',409);await this.blobs.cleanupForDeletion(projectId,bucket);this.storage.sql.exec('DELETE FROM issue_attachment_refs');this.storage.sql.exec('DELETE FROM issue_attachment_input_proofs');this.storage.sql.exec('DELETE FROM issue_attachment_transfer_cancellations');this.storage.sql.exec('DELETE FROM issue_attachment_retirements');}
}
