import {MigrationIssuesLedger,type MigrationConversationManifest,type MigrationIssueOrigin,type MigrationCommentOrigin} from './migration-issues-ledger';
export interface ImportedConversationOrigin {provider:'github';repositoryId:string;providerId:string;nodeId:string;sourceUrl:string;login:string;identity:'external-unclaimed';nativeUserId:null;createdAt:string;updatedAt:string}
export interface ConversationPublicationReceipt {operationId:string;manifestHash:string;revision:number;phase:'issues'|'comments'|'complete';issueCursor:string;commentCursor:string;nativeIssues:number;nativeComments:number;archivedPullRequests:number;archivedPullRequestComments:number;sourceMissing:number;excluded:MigrationConversationManifest['excluded'];atomicSourceSnapshot:false}
type MapRow={source_doc:string;native_id:number|null;kind:string};
/** Owner-confirmed, create-only native publication. Source origins are never native account identities. */
export class MigrationConversationPublication {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec(`CREATE TABLE IF NOT EXISTS migration_conversation_publications(op TEXT PRIMARY KEY,doc TEXT NOT NULL);CREATE TABLE IF NOT EXISTS migration_publication_events(event_id TEXT PRIMARY KEY,payload TEXT NOT NULL,receipt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS migration_native_issue_origins(repository_id TEXT NOT NULL,provider_id TEXT NOT NULL,node_id TEXT NOT NULL,kind TEXT NOT NULL,native_id INTEGER,source_doc TEXT NOT NULL,PRIMARY KEY(repository_id,provider_id),UNIQUE(repository_id,node_id));CREATE TABLE IF NOT EXISTS migration_native_comment_origins(repository_id TEXT NOT NULL,provider_id TEXT NOT NULL,node_id TEXT NOT NULL,kind TEXT NOT NULL,native_id INTEGER,source_doc TEXT NOT NULL,PRIMARY KEY(repository_id,provider_id),UNIQUE(repository_id,node_id));`);}
 get(op:string):ConversationPublicationReceipt|null{const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM migration_conversation_publications WHERE op=?',op).toArray()[0];return row?JSON.parse(row.doc) as ConversationPublicationReceipt:null;}
 begin(manifest:MigrationConversationManifest,expected:{hash:string;revision:number},validate:()=>void):ConversationPublicationReceipt{return this.storage.transactionSync(()=>{validate();if(!/^[a-f0-9]{64}$/.test(expected.hash)||manifest.hash!==expected.hash||manifest.revision!==expected.revision||manifest.status==='pending')throw Error('Confirm this exact finished capture manifest and revision');const previous=this.get(manifest.scope.operationId);if(previous){if(previous.manifestHash!==manifest.hash||previous.revision!==manifest.revision)throw Error('Publication manifest changed');return previous;}const receipt:ConversationPublicationReceipt={operationId:manifest.scope.operationId,manifestHash:manifest.hash,revision:manifest.revision,phase:'issues',issueCursor:'0',commentCursor:'0',nativeIssues:0,nativeComments:0,archivedPullRequests:0,archivedPullRequestComments:0,sourceMissing:manifest.counts.missing,excluded:manifest.excluded,atomicSourceSnapshot:false};this.storage.sql.exec('INSERT INTO migration_conversation_publications VALUES(?,?)',receipt.operationId,JSON.stringify(receipt));return receipt;});}
 batch(manifest:MigrationConversationManifest,validate:()=>void):ConversationPublicationReceipt{return this.storage.transactionSync(()=>{validate();const receipt=this.get(manifest.scope.operationId);if(!receipt||receipt.manifestHash!==manifest.hash||receipt.revision!==manifest.revision)throw Error('Saved owner publication confirmation required');if(receipt.phase==='complete')return receipt;const ledger=new MigrationIssuesLedger(this.storage);const current=ledger.get(receipt.operationId);if(!current||current.revision!==receipt.revision||current.status==='pending')throw Error('Staged capture changed; native records preserved');
 if(receipt.phase==='issues'){const rows=ledger.origins(receipt.operationId,receipt.issueCursor,20);for(const origin of rows){this.publishIssue(origin);receipt.issueCursor=origin.providerId;if(origin.kind==='issue')receipt.nativeIssues++;else receipt.archivedPullRequests++;}if(rows.length<20)receipt.phase='comments';}
 else{const rows=ledger.comments(receipt.operationId,receipt.commentCursor,20);for(const origin of rows){this.publishComment(origin);receipt.commentCursor=origin.providerId;if(origin.parentKind==='issue')receipt.nativeComments++;else receipt.archivedPullRequestComments++;}if(rows.length<20){if(receipt.nativeIssues!==manifest.counts.issues||receipt.archivedPullRequests!==manifest.counts.pullRequests||receipt.nativeComments+receipt.archivedPullRequestComments!==manifest.counts.comments)throw Error('Publication count reconciliation failed; retained progress preserved');receipt.phase='complete';}}
 this.storage.sql.exec('UPDATE migration_conversation_publications SET doc=? WHERE op=?',JSON.stringify(receipt),receipt.operationId);return receipt;});}
 publish(manifest:MigrationConversationManifest,input:{eventId:string;manifestHash:string;expectedRevision:number},validate:()=>void):ConversationPublicationReceipt{return this.storage.transactionSync(()=>{validate();if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(input.eventId))throw Error('Stable publication request identity required');const payload=JSON.stringify({operationId:manifest.scope.operationId,hash:input.manifestHash,revision:input.expectedRevision});const old=this.storage.sql.exec<{payload:string;receipt:string}>('SELECT payload,receipt FROM migration_publication_events WHERE event_id=?',input.eventId).toArray()[0];if(old){if(old.payload!==payload)throw Error('Publication request identity changed');return JSON.parse(old.receipt) as ConversationPublicationReceipt;}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM migration_publication_events').one().n>=10000)throw Error('Publication receipt capacity reached; existing native records preserved');this.begin(manifest,{hash:input.manifestHash,revision:input.expectedRevision},validate);const result=this.batch(manifest,validate);this.storage.sql.exec('INSERT INTO migration_publication_events VALUES(?,?,?)',input.eventId,payload,JSON.stringify(result));return result;});}
 private publishIssue(origin:MigrationIssueOrigin){const doc=JSON.stringify(origin),existing=this.storage.sql.exec<MapRow>('SELECT source_doc,native_id,kind FROM migration_native_issue_origins WHERE repository_id=? AND provider_id=?',origin.repositoryId,origin.providerId).toArray()[0];if(existing){if(existing.source_doc!==doc)throw Error('Previously imported source issue diverged; nothing was overwritten');if(existing.kind==='issue'){const native=this.storage.sql.exec<{title:string;body:string;state:string;author:string;created_at:string;updated_at:string}>('SELECT title,body,state,author,created_at,updated_at FROM issues WHERE number=?',existing.native_id!).toArray()[0];if(!native)throw Error('Imported native issue is missing; no replacement created');if(native.title!==origin.title||native.body!==origin.body||native.state!==origin.state||native.author!==`GitHub @${origin.actor.login} (external, unclaimed)`||native.created_at!==origin.createdAt||native.updated_at!==origin.updatedAt)throw Error('Imported native issue has local changes; nothing was overwritten');}return;}
 let number:number|null=null;if(origin.kind==='issue')number=this.storage.sql.exec<{number:number}>('INSERT INTO issues(title,body,state,author,created_at,updated_at,closed_by) VALUES(?,?,?,?,?,?,?) RETURNING number',origin.title,origin.body,origin.state,`GitHub @${origin.actor.login} (external, unclaimed)`,origin.createdAt,origin.updatedAt,null).one().number;
 this.storage.sql.exec('INSERT INTO migration_native_issue_origins VALUES(?,?,?,?,?,?)',origin.repositoryId,origin.providerId,origin.nodeId,origin.kind,number,doc);}
 private publishComment(origin:MigrationCommentOrigin){const doc=JSON.stringify(origin),existing=this.storage.sql.exec<MapRow>('SELECT source_doc,native_id,kind FROM migration_native_comment_origins WHERE repository_id=? AND provider_id=?',origin.repositoryId,origin.providerId).toArray()[0];if(existing){if(existing.source_doc!==doc)throw Error('Previously imported source comment diverged; nothing was overwritten');if(existing.kind==='issue'){const native=this.storage.sql.exec<{body:string;author:string;created_at:string}>('SELECT body,author,created_at FROM comments WHERE id=?',existing.native_id!).toArray()[0];if(!native)throw Error('Imported native comment is missing; no replacement created');if(native.body!==origin.body||native.author!==`GitHub @${origin.actor.login} (external, unclaimed)`||native.created_at!==origin.createdAt)throw Error('Imported native comment has local changes; nothing was overwritten');}return;}
 const parent=this.storage.sql.exec<MapRow>('SELECT source_doc,native_id,kind FROM migration_native_issue_origins WHERE repository_id=? AND provider_id=?',origin.repositoryId,origin.parentIssueId).toArray()[0];if(!parent||parent.kind!==origin.parentKind)throw Error('Exact imported comment parent unavailable');let id:number|null=null;if(origin.parentKind==='issue'){if(parent.native_id===null)throw Error('Native imported parent unavailable');id=this.storage.sql.exec<{id:number}>('INSERT INTO comments(subject,author,body,path,line,"commit",created_at) VALUES(?,?,?,NULL,NULL,NULL,?) RETURNING id',`issue:${parent.native_id}`,`GitHub @${origin.actor.login} (external, unclaimed)`,origin.body,origin.createdAt).one().id;}
 this.storage.sql.exec('INSERT INTO migration_native_comment_origins VALUES(?,?,?,?,?,?)',origin.repositoryId,origin.providerId,origin.nodeId,origin.parentKind,id,doc);}
 issueOrigin(number:number):ImportedConversationOrigin|null{return this.origin('migration_native_issue_origins',number);}
 commentOrigin(id:number):ImportedConversationOrigin|null{return this.origin('migration_native_comment_origins',id);}
 private origin(table:'migration_native_issue_origins'|'migration_native_comment_origins',id:number):ImportedConversationOrigin|null{const row=this.storage.sql.exec<{source_doc:string}>(`SELECT source_doc FROM ${table} WHERE native_id=?`,id).toArray()[0];if(!row)return null;const value=JSON.parse(row.source_doc) as MigrationIssueOrigin|MigrationCommentOrigin;return{provider:'github',repositoryId:value.repositoryId,providerId:value.providerId,nodeId:value.nodeId,sourceUrl:value.sourceUrl,login:value.actor.login,identity:'external-unclaimed',nativeUserId:null,createdAt:value.createdAt,updatedAt:value.updatedAt};}
}
