import {z} from 'zod';
import {autoAcceptanceFactsSchema,type AutoAcceptanceAuthority} from './acceptance-policy';
import {assertCompatibleAcceptedTargetBatch} from '../core/accepted-target';
import type {PublicationJournalEntry} from '../core/types';
import {createHash} from 'node:crypto';
import {isSafeRef} from '../core/sanitize';
import {validateMirrorTarget,githubAuthEnv,type Exec, type MirrorResult} from './mirror';
import {gitAuthEnv,q} from './shell';
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value));
const principal=z.string().min(1).max(256).refine(value=>!/[\x00-\x1f\x7f]/.test(value));
export const mirrorIntegrationAuthoritySchema=z.object({kind:z.literal("integration"),workflowId:principal,candidateId:principal,journalId:principal,reviewActorId:principal}).strict();
export const mirrorPolicyIntegrationAuthoritySchema=z.object({kind:z.literal("policy-integration"),workflowId:principal,candidateId:principal,journalId:principal,policyAuthorityId:z.uuid(),acceptancePolicyVersion:z.number().int().positive().safe(),verificationPolicyVersion:z.number().int().nonnegative().safe(),configuredById:principal}).strict();
export const mirrorExecutionAuthoritySchema=z.discriminatedUnion("kind",[mirrorIntegrationAuthoritySchema,mirrorPolicyIntegrationAuthoritySchema]);
export type MirrorIntegrationAuthority=z.infer<typeof mirrorIntegrationAuthoritySchema>;
export type MirrorPolicyIntegrationAuthority=z.infer<typeof mirrorPolicyIntegrationAuthoritySchema>;
const scopeSchema=z.object({id:z.uuid(),projectId:z.string().min(1),incarnation:z.uuid(),accountKey:z.string().min(1),actorId:z.string().min(1),sessionExpiresAt:z.number().int().positive().nullable(),credentialHash:z.string().regex(/^[a-f0-9]{64}$/).optional(),journalId:z.string().min(1),canonicalRepoName:z.string().min(1),acceptedRef:z.string().refine(value=>value.startsWith('refs/heads/')&&isSafeRef(value)),commit:sha,tree:sha,target:z.string().refine(value=>validateMirrorTarget(value)===value),configDigest:z.string().regex(/^[a-f0-9]{64}$/),exportApproved:z.literal(true),authority:mirrorExecutionAuthoritySchema.optional()}).strict().refine(value=>value.sessionExpiresAt!==null||value.credentialHash!==undefined||value.authority!==undefined,'A token-backed owner scope is required without session expiry').refine(value=>!value.authority||value.authority.journalId===value.journalId,'Mirror authority belongs to another accepted journal').refine(value=>value.authority?.kind!=="policy-integration"||value.authority.configuredById===value.actorId,'Policy mirror principal must be its recorded configuring owner');
const receiptIds=z.object({native:principal,source:principal,build:principal,browser:principal}).strict();
const digest=z.string().regex(/^[a-f0-9]{64}$/);
const policyAuthoritySchema=z.object({id:z.uuid(),kind:z.literal('verified-auto-accept'),identity:autoAcceptanceFactsSchema.shape.identity,policyVersion:z.number().int().positive().safe(),serviceWorkflowId:principal,authorizedAt:z.number().int().nonnegative().safe(),approvedRequirementIds:autoAcceptanceFactsSchema.shape.approvedRequirementIds,coveredRequirementIds:autoAcceptanceFactsSchema.shape.coveredRequirementIds,proofReceipts:receiptIds,proofDigests:z.object({native:digest,source:digest,build:digest,browser:digest}).strict()}).strict();
function canonical(value:unknown):string{const json=z.json().parse(value);const render=(input:typeof json):string=>Array.isArray(input)?`[${input.map(render).join(',')}]`:input!==null&&typeof input==='object'?`{${Object.keys(input).sort().map(key=>`${JSON.stringify(key)}:${render(input[key]!)}`).join(',')}}`:JSON.stringify(input);return render(json);}
/** Historical policy receipt proves an already ACCEPTED source only. It grants
 * neither a human review nor a new canonical publication. The controller must
 * additionally prove current owner/account/workflow and explicit export consent. */
export function mapPolicyMirrorAuthority(input:{projectId:string;incarnation:string;canonicalRepoName:string;registeredWorkflowId:string;journal:PublicationJournalEntry;candidatePolicyAuthority:AutoAcceptanceAuthority;historicalAuthority:AutoAcceptanceAuthority}):MirrorPolicyIntegrationAuthority{
 const publication=input.journal.publicationAuthority;
 if(input.journal.state!=="ACCEPTED"||publication?.kind!=="maintainer-policy"||input.journal.candidateCommit!==input.journal.newHead||!input.journal.candidateTree||publication.commit!==input.journal.newHead||publication.tree!==input.journal.candidateTree)throw Error("Exact accepted policy publication required for mirroring");
 const historical=policyAuthoritySchema.parse(input.historicalAuthority),candidate=policyAuthoritySchema.parse(input.candidatePolicyAuthority),recorded=policyAuthoritySchema.parse(publication.policyAuthority),identity=historical.identity;
 if(canonical(historical)!==canonical(candidate)||canonical(historical)!==canonical(recorded)||identity.projectId!==input.projectId||identity.incarnation!==input.incarnation||identity.canonicalRepoName!==input.canonicalRepoName||identity.candidateId!==input.journal.candidateId||identity.commit!==input.journal.newHead||identity.tree!==input.journal.candidateTree||identity.expectedBase!==input.journal.expectedHead||historical.serviceWorkflowId!==input.registeredWorkflowId||historical.policyVersion!==identity.acceptancePolicyVersion||publication.acceptancePolicyVersion!==historical.policyVersion||publication.policyVersion!==identity.verificationPolicyVersion)throw Error("Historical policy mirror receipt differs from committed source");
 if(input.journal.acceptedTarget&&publication.acceptedTarget)assertCompatibleAcceptedTargetBatch([input.journal.acceptedTarget,publication.acceptedTarget]);
 const target=input.journal.acceptedTarget??publication.acceptedTarget;
 if(target&&(target.projectId!==identity.projectId||target.incarnation!==identity.incarnation||target.canonicalRepoName!==identity.canonicalRepoName||target.ref!==identity.targetRef||target.acceptedCommit!==identity.expectedBase||target.acceptedVersion!==identity.acceptedTargetVersion||target.policyVersion!==identity.verificationPolicyVersion))throw Error("Policy mirror accepted target binding differs");
 return mirrorPolicyIntegrationAuthoritySchema.parse({kind:"policy-integration",workflowId:input.registeredWorkflowId,candidateId:input.journal.candidateId,journalId:input.journal.id,policyAuthorityId:historical.id,acceptancePolicyVersion:historical.policyVersion,verificationPolicyVersion:identity.verificationPolicyVersion,configuredById:publication.actor.userId});
}

export type MirrorExecutionScope=z.infer<typeof scopeSchema>;
export interface MirrorExecutionRecord {scope:MirrorExecutionScope;admission:'none'|'unknown'|'granted';nativeAdmission:{nativeRunId:string;seconds:1200}|null;phase:'prepared'|'issuance_unknown'|'credential_received'|'push_unknown'|'observed';token:string|null;tokenDigest:string|null;nativePossible:boolean;expiresAt:number|null;credentialRevoked:boolean;nativeStopped:boolean;result:MirrorResult|null}
/** Backend-only secret receipts. Public callers must project fields explicitly. */
export class MirrorExecutions {
 constructor(private storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS mirror_executions(id TEXT PRIMARY KEY,scope TEXT NOT NULL,doc TEXT NOT NULL)');}
 get(id:string):MirrorExecutionRecord|null{z.uuid().parse(id);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM mirror_executions WHERE id=?',id).toArray()[0];return row?JSON.parse(row.doc) as MirrorExecutionRecord:null;}
 private save(row:MirrorExecutionRecord){this.storage.sql.exec('UPDATE mirror_executions SET doc=? WHERE id=?',JSON.stringify(row),row.scope.id);}
 prepare(scope:MirrorExecutionScope,authorize:()=>void){const parsed=scopeSchema.parse(scope);return this.storage.transactionSync(()=>{authorize();const old=this.get(parsed.id);if(old){if(JSON.stringify(old.scope)!==JSON.stringify(parsed))throw Error('Mirror operation scope changed');return old;}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM mirror_executions').toArray()[0]!.n>=1000)throw Error('Mirror operation capacity reached');const row:MirrorExecutionRecord={scope:parsed,admission:'none',nativeAdmission:null,phase:'prepared',token:null,tokenDigest:null,nativePossible:false,expiresAt:null,credentialRevoked:false,nativeStopped:false,result:null};this.storage.sql.exec('INSERT INTO mirror_executions VALUES(?,?,?)',parsed.id,JSON.stringify(parsed),JSON.stringify(row));return row;});}
 beginAdmission(id:string,authorize:()=>void){return this.storage.transactionSync(()=>{authorize();const row=this.get(id);if(!row||row.phase!=='prepared'||row.admission!=='none')return false;row.admission='unknown';row.nativeAdmission={nativeRunId:`mirror-${id}`,seconds:1200};this.save(row);return true;});}
 admissionGranted(id:string,proof:{nativeRunId:string;seconds:1200;allowed:true}){this.storage.transactionSync(()=>{const row=this.get(id);if(!row||row.admission==='none'||!row.nativeAdmission||proof.nativeRunId!==row.nativeAdmission.nativeRunId||proof.seconds!==1200||proof.allowed!==true)throw Error('Mirror native admission proof differs');row.admission='granted';this.save(row);});}
 beginIssue(id:string,authorize:()=>void){return this.storage.transactionSync(()=>{authorize();const row=this.get(id);if(!row)throw Error('Mirror intent unavailable');if(row.phase!=='prepared'||row.admission!=='granted')return false;row.phase='issuance_unknown';this.save(row);return true;});}
 recordCredential(id:string,token:string,expiresAt:number){if(!token||token.length>16384||/[\r\n\0]/.test(token))throw Error('Invalid mirror credential receipt');const recordedExpiry=Number.isSafeInteger(expiresAt)?expiresAt:null;
  this.storage.transactionSync(()=>{const row=this.get(id);if(!row||row.phase==='prepared')throw Error('Mirror issuance intent unavailable');if(row.credentialRevoked){if(row.tokenDigest!==createHash('sha256').update(token).digest('hex')||row.expiresAt!==recordedExpiry)throw Error('Settled mirror receipt differs');return;}if(row.token!==null&&(row.token!==token||row.expiresAt!==recordedExpiry))throw Error('Mirror credential receipt differs');row.token=token;row.expiresAt=recordedExpiry;if(row.phase==='issuance_unknown')row.phase='credential_received';this.save(row);});
  const digest=createHash('sha256').update(token).digest('hex');this.storage.transactionSync(()=>{const row=this.get(id)!;if(row.tokenDigest&&row.tokenDigest!==digest)throw Error('Mirror credential receipt differs');row.tokenDigest=digest;this.save(row);});
 }
 beginNative(id:string,authorize:()=>void){return this.storage.transactionSync(()=>{authorize();const row=this.get(id);if(!row||row.phase!=='credential_received'||row.nativePossible||row.nativeStopped)return false;row.nativePossible=true;this.save(row);return true;});}
 beginPush(id:string,authorize:()=>void){return this.storage.transactionSync(()=>{authorize();const row=this.get(id);if(!row||row.phase!=='credential_received'||!row.nativePossible||row.nativeStopped||!row.token||row.credentialRevoked)return false;row.phase='push_unknown';this.save(row);return true;});}
 observed(id:string,result:MirrorResult){this.storage.transactionSync(()=>{const row=this.get(id);if(!row||row.phase!=='push_unknown')throw Error('Mirror publication intent unavailable');if(row.result&&JSON.stringify(row.result)!==JSON.stringify(result))throw Error('Mirror result differs');row.phase='observed';row.result=result;this.save(row);});}
 credentialRevoked(id:string,token:string,repoName:string,revoked:true){this.storage.transactionSync(()=>{const row=this.get(id);if(!row||row.token!==token||row.scope.canonicalRepoName!==repoName||revoked!==true)throw Error('Mirror revocation proof differs');row.tokenDigest??=createHash("sha256").update(token).digest("hex");row.credentialRevoked=true;row.token=null;this.save(row);});}
 nativeStopped(id:string,name:string,proof:{sealed:true;stopped:true}){this.storage.transactionSync(()=>{const row=this.get(id);if(!row||!row.nativePossible||name!==`mirror-${id}`||proof.sealed!==true||proof.stopped!==true)throw Error('Mirror native closure differs');row.nativeStopped=true;this.save(row);});}
 complete(id:string){const row=this.get(id);return Boolean(row&&row.phase==='observed'&&row.credentialRevoked&&row.nativeStopped);}
}
export interface MirrorExecutionJournal {get():Promise<MirrorExecutionRecord>;beginIssue():Promise<boolean>;recordCredential(token:string,expiresAt:number,scope:unknown):Promise<void>;beginNative():Promise<boolean>;beginPush():Promise<boolean>;observed(result:MirrorResult):Promise<void>;credentialRevoked(token:string):Promise<void>;nativeStopped():Promise<void>}
export interface MirrorExecutionDeps {authorize(mode:'dispatch'|'reconcile'):Promise<void>;admit():Promise<void>;issue():Promise<{plaintext:string;scope:string;expiresAt:string}>;revoke(token:string):Promise<boolean>;stop(name:string):Promise<{sealed:boolean;stopped:boolean}>;exec:Exec;readTarget(ref:string,target:string):Promise<{success:boolean;commit:string|null}>;journal:MirrorExecutionJournal;canonicalRemote:string;githubToken:string}
/** A push is dispatched at most once. Unknown outcomes are inspected through the
 * original exact target; a differing/missing ref never authorizes another write. */
export async function executeMirror(scope:MirrorExecutionScope,deps:MirrorExecutionDeps):Promise<{status:'complete'|'held';result?:MirrorResult}>{
 scopeSchema.parse(scope);let token:string|undefined;const name=`mirror-${scope.id}`;let result:MirrorResult|undefined;let nativePossible=false;
 let authorizationMode:'dispatch'|'reconcile'='reconcile';
 const authorize=async()=>{await deps.authorize(authorizationMode);};
 const run:Exec=async(cmd,env)=>{await authorize();const output=await deps.exec(cmd,env);await authorize();return output;};
 try{await authorize();const saved=await deps.journal.get();if(JSON.stringify(saved.scope)!==JSON.stringify(scope))throw Error('Mirror snapshot changed');authorizationMode=saved.phase==='push_unknown'||saved.phase==='observed'?'reconcile':'dispatch';await authorize();if(saved.phase==='observed'&&saved.credentialRevoked&&saved.nativeStopped)return{status:'complete',...(saved.result?{result:saved.result}:{})};nativePossible=saved.nativePossible;if(saved.phase==='prepared'||saved.phase==='credential_received'){if(saved.admission!=='granted')await deps.admit();await authorize();if((await deps.journal.get()).admission!=='granted')return{status:'held'};}
 if(saved.phase==='prepared'){if(!await deps.journal.beginIssue())return{status:'held'};const issued=await deps.issue();token=issued.plaintext;await deps.journal.recordCredential(token,Date.parse(issued.expiresAt),issued.scope);await authorize();if(issued.scope!=='read'||Date.parse(issued.expiresAt)<=Date.now()||Date.parse(issued.expiresAt)>Date.now()+65000)throw Error('Mirror credential scope or expiry differs');}else token=saved.token??undefined;
 if(saved.phase==='observed'){result=saved.result??undefined;}else if(saved.phase==='push_unknown'){
 await authorize();const readback=await deps.readTarget(scope.acceptedRef,scope.target);await authorize();if(readback.success&&readback.commit===scope.commit){result={status:'ok',detail:`Mirrored ${scope.commit.slice(0,12)} to ${scope.acceptedRef.slice(11)}`};await deps.journal.observed(result);}else return{status:'held'};
 }else{const receipt=await deps.journal.get();if(!token||receipt.expiresAt===null||receipt.expiresAt<=Date.now()||!await deps.journal.beginNative())return{status:'held'};nativePossible=true;const dir='/tmp/mirror';const init=await run(`rm -rf ${q(dir)} && git init --quiet --bare ${q(dir)}`);if(!init.success)throw Error('Mirror workspace unavailable');const fetched=await run(`git -C ${q(dir)} fetch --quiet --no-tags ${q(deps.canonicalRemote)} ${q(`+${scope.acceptedRef}:refs/flaregit/mirror`)}`,gitAuthEnv(token));if(!fetched.success)throw Error('Mirror accepted ref unavailable');const identity=await run(`git -C ${q(dir)} show -s --format=%H:%T refs/flaregit/mirror`);if(!identity.success||identity.stdout.trim()!==`${scope.commit}:${scope.tree}`)throw Error('Mirror accepted Git identity changed');await authorize();if(!await deps.journal.beginPush())return{status:'held'};const pushed=await run(`git -C ${q(dir)} push --porcelain ${q(scope.target)} ${q(`${scope.commit}:${scope.acceptedRef}`)}`,githubAuthEnv(deps.githubToken));if(!pushed.success)return{status:'held'};result={status:'ok',detail:`Mirrored ${scope.commit.slice(0,12)} to ${scope.acceptedRef.slice(11)}`};await deps.journal.observed(result);}
 }catch{return{status:'held'};}finally{if(token){try{if(await deps.revoke(token))await deps.journal.credentialRevoked(token);}catch{/* Exact receipt remains held. */}}if(nativePossible)try{const proof=await deps.stop(name);if(proof.sealed&&proof.stopped)await deps.journal.nativeStopped();}catch{/* Native closure remains held. */}}
 const final=await deps.journal.get();return final.phase==='observed'&&final.credentialRevoked&&final.nativeStopped?{status:'complete',...(result?{result}:{})}:{status:'held'};
}
