import {z} from 'zod';
import {selectPublicationNativePhase} from './publication-native-phase';
import {runtimeRelease} from './runtime-release';
import {accountKeyFor} from './projects';
import type {Env} from './env';
import type {Ledger} from './durable-object';
import type {HumanDecisionActor} from '../core/types';
export const preparedPublicationRequestSchema=z.object({journalId:z.string().regex(/^jrnl_[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/),expectedCommit:z.string().regex(/^[a-f0-9]{40}$/)}).strict();
export class PreparedPublicationDispatchError extends Error{constructor(message:string,readonly status:403|409|503){super(message);}}
type Project=Pick<Ledger,'getState'|'getWorkflowRun'|'acceptedPublicationReceipt'|'authorizeCandidatePublication'|'candidateRuntimeInspection'>;
/** Starts a separate framework-native publisher. Never records review, notifies
 * the old integration, or repeats composition. */
export async function dispatchPreparedPublication(env:Env,project:Project,projectId:string,candidateId:string,input:unknown,actor:HumanDecisionActor,authorize:()=>Promise<number>){
 const request=preparedPublicationRequestSchema.parse(input);if(actor.viaToken)throw new PreparedPublicationDispatchError('Sign in as the repository owner to publish the reviewed candidate',403);
 let expiry=await authorize();const state=structuredClone(await project.getState()),candidate=state.candidates[candidateId],journal=state.journal.find(row=>row.id===request.journalId&&row.candidateId===candidateId);
 if(state.projectId!==projectId||!candidate||!journal||candidate.candidateCommit!==request.expectedCommit||journal.newHead!==request.expectedCommit)throw new PreparedPublicationDispatchError('The saved candidate or publication journal changed',409);
 if(journal.state==='ACCEPTED'){const receipt=await project.acceptedPublicationReceipt(candidateId,journal.id);expiry=await authorize();if(!receipt||receipt.commit!==request.expectedCommit||receipt.candidateId!==candidateId||receipt.journalId!==journal.id||receipt.ref!==candidate.acceptedTarget?.ref||receipt.evidenceId!==candidate.evidenceId||receipt.tree!==journal.candidateTree||expiry<=Date.now())throw new PreparedPublicationDispatchError('Accepted repository history is unconfirmed',409);return{accepted:true,duplicate:true,publicationRequested:false,receipt};}
 if(!env.PUBLICATION_NATIVE_PHASE_JSON&&!(env.C03_PRIVATE_MATRIX_ENABLED==='true'&&env.PUBLICATION_NATIVE_PHASES_JSON))throw new PreparedPublicationDispatchError('Publication is paused until a separate execution grant is configured. Your review and candidate are saved.',503);
 const phase=selectPublicationNativePhase(env,{workflowId:candidate.workflowInstanceId??'',candidateId,journalId:journal.id}),release=runtimeRelease(env),evidence=candidate.evidenceId?state.evidence[candidate.evidenceId]:undefined;
 if(journal.state!=='PREPARED'||!candidate.workflowInstanceId||!candidate.acceptedTarget||!candidate.review?.approved||candidate.review.actor?.userId!==actor.userId||candidate.review.commit!==request.expectedCommit||journal.publicationAuthority?.kind!=='human-review'||journal.publicationAuthority.actor.userId!==actor.userId||!evidence||evidence.status!=='passed'||evidence.candidateCommit!==request.expectedCommit||evidence.candidateTree!==journal.candidateTree)throw new PreparedPublicationDispatchError('Exact prepared human review and verification are required',409);
 const original=await project.getWorkflowRun(candidate.workflowInstanceId);if(original?.kind!=='integration'||!original.actorId)throw new PreparedPublicationDispatchError('Original integration identity is unavailable',409);
 const derived={projectId,incarnation:candidate.acceptedTarget.incarnation,workflowId:candidate.workflowInstanceId,candidateId,actorId:original.actorId,accountKey:await accountKeyFor(original.actorId),journalId:journal.id,commit:request.expectedCommit,tree:journal.candidateTree,evidenceId:evidence.id,reviewActorId:actor.userId};
 for(const key of Object.keys(derived) as (keyof typeof derived)[])if(phase[key]!==derived[key])throw new PreparedPublicationDispatchError('Publication grant differs from the saved review',409);
 const deadline=()=>{if(!release.releaseIdentified||phase.sourceVersion!==release.sourceVersion||Date.now()<phase.activatedAt||Date.now()>=phase.admissionExpiresAt||expiry<=Date.now())throw new PreparedPublicationDispatchError('Publication admission or owner session expired',403);};deadline();
 const runtime=await project.candidateRuntimeInspection(candidateId,actor,undefined,expiry);if(runtime.protocol!==1||!runtime.coverage||!runtime.allocations?.length||runtime.allocations.some(row=>!row.stopped)||!runtime.commands||runtime.commands.pending!==0||runtime.verificationClosure.status!=='closed'||runtime.verificationClosure.credentials.status!=='revoked')throw new PreparedPublicationDispatchError('Verification cleanup must be confirmed before publication',409);
 if(!await project.authorizeCandidatePublication(candidateId,request.expectedCommit))throw new PreparedPublicationDispatchError('Current publication authority is unavailable',403);
 expiry=await authorize();const fresh=await project.getState();if(JSON.stringify(fresh.candidates[candidateId])!==JSON.stringify(candidate)||JSON.stringify(fresh.journal.find(row=>row.id===journal.id))!==JSON.stringify(journal)||!await project.authorizeCandidatePublication(candidateId,request.expectedCommit))throw new PreparedPublicationDispatchError('Prepared publication changed during admission',409);expiry=await authorize();const finalState=await project.getState();if(JSON.stringify(finalState.candidates[candidateId])!==JSON.stringify(candidate)||JSON.stringify(finalState.journal.find(row=>row.id===journal.id))!==JSON.stringify(journal))throw new PreparedPublicationDispatchError('Prepared publication changed before dispatch',409);deadline();
 const id=`pub-${journal.id}`,params={mode:'prepared-publication' as const,projectId,candidateId,journalId:journal.id};
 try{await env.INTEGRATION_WORKFLOW.create({id,params});return{accepted:false,publicationRequested:true,workflowId:id,journalId:journal.id};}
 catch{try{const status=await(await env.INTEGRATION_WORKFLOW.get(id)).status();return{accepted:false,publicationRequested:true,workflowId:id,journalId:journal.id,status:status.status,acknowledgementRecovered:true};}catch{throw new PreparedPublicationDispatchError('Publisher acknowledgement is unconfirmed. Retry only this saved journal.',409);}}
}
