import {z} from 'zod';
import {bindBuildManifest,type StaticBuildScope} from './static-build-artifact';
import type {TrustedGitSource,TrustedGitSourceProof} from './trusted-git-source';
import type {ManagedAdmission,ManagedEnvelope,ManagedReservation} from './managed-spend-ledger';
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value)),digest=z.string().regex(/^[a-f0-9]{64}$/),name=z.string().min(1).max(256);
export const previewExecutionSnapshotSchema=z.object({kind:z.literal('preview-execution'),projectId:z.string().regex(/^[a-z0-9]{12,16}$/),incarnation:z.uuid(),commit:sha,tree:sha,policyDigest:digest,actorId:name,accountKey:z.string().regex(/^[a-f0-9]{12}$/),canonicalRepoName:name,providerRepoId:name,target:z.discriminatedUnion('kind',[z.object({kind:z.literal('accepted'),receiptId:name,ref:name.nullable(),version:z.number().int().nonnegative().nullable()}).strict(),z.object({kind:z.literal('native-candidate'),candidateId:name,workflowId:name,evidenceId:name}).strict()]),generation:z.uuid().nullable(),image:z.string().regex(/^registry\.cloudflare\.com\/[a-f0-9]{32}\/[a-z0-9-]+@sha256:[a-f0-9]{64}$/)}).strict();
export type PreviewExecutionSnapshot=z.infer<typeof previewExecutionSnapshotSchema>;
const scopeSchema=z.object({attemptId:z.uuid(),projectId:z.string().regex(/^[a-z0-9]{12,16}$/),incarnation:z.uuid(),commit:sha,tree:sha,policyDigest:digest}).strict();
export const previewExecutionContextSchema=z.object({snapshot:previewExecutionSnapshotSchema,scope:scopeSchema,sourceDigest:digest.nullable()}).strict().refine(value=>['projectId','incarnation','commit','tree','policyDigest'].every(key=>value.scope[key as keyof StaticBuildScope]===value.snapshot[key as keyof PreviewExecutionSnapshot]));
export type PreviewExecutionContext=z.infer<typeof previewExecutionContextSchema>;
export interface PreviewSourceIntent{nativeRunId:string;credentialIntentId:string;phase:'prepared'|'possible'|'closed';credentialClosed:boolean;nativeClosed:boolean}
export interface PreviewExecutionRecord{context:PreviewExecutionContext;sourceProof:TrustedGitSourceProof|null;source:PreviewSourceIntent|null;phase:'prepared'|'funding_unknown'|'paid'|'dispatched'|'sealed';consumptionAttempted:boolean;ownerId:string|null;fundingKnown:boolean;createdAt:number;expiresAt:number}
export interface PreviewExecutionAuthorityPorts{
 current(snapshot:PreviewExecutionSnapshot):Promise<PreviewExecutionSnapshot>;
 assertCurrent(snapshot:PreviewExecutionSnapshot):void;
 assertSource(context:PreviewExecutionContext,source:TrustedGitSource):Promise<void>;
 readSourceClosure(context:PreviewExecutionContext,intent:PreviewSourceIntent):Promise<{nativeRunId:string;credentialIntentId:string;nativeClosed:boolean;credentialClosed:boolean}>;
 readCompletion?(context:PreviewExecutionContext):Promise<{scope:StaticBuildScope;sourceDigest:string;image:string}|null>;
 funding:{read(id:string):Promise<ManagedReservation|null>;reserve(envelope:ManagedEnvelope):Promise<ManagedAdmission>;consume(id:string):Promise<unknown>};
 now?:()=>number;
}
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
async function bounded<T>(work:()=>Promise<T>):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([work(),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Preview authority read deadline')),10000);})]);}finally{clearTimeout(timer);}}
/** Preview-only authority. It creates no integration candidate, model, review or
 * publication evidence. Uncertain dispatch is retained, never reset by a retry. */
export class PreviewExecutionAuthority{
 constructor(private readonly storage:Pick<DurableObjectStorage,'sql'|'transactionSync'>,private readonly ports:PreviewExecutionAuthorityPorts){storage.sql.exec('CREATE TABLE IF NOT EXISTS preview_execution_attempts(attempt_id TEXT PRIMARY KEY,slot TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)');}
 private now(){return this.ports.now?.()??Date.now();}
 private slot(snapshot:PreviewExecutionSnapshot){return JSON.stringify([snapshot.projectId,snapshot.incarnation,snapshot.commit,snapshot.generation]);}
 get(attemptId:string):PreviewExecutionRecord|null{z.uuid().parse(attemptId);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM preview_execution_attempts WHERE attempt_id=?',attemptId).toArray()[0];return row?structuredClone(JSON.parse(row.doc) as PreviewExecutionRecord):null;}
 private save(record:PreviewExecutionRecord){const doc=JSON.stringify(record);if(new TextEncoder().encode(doc).length>262144)throw Error('Preview authority record bound exceeded');this.storage.sql.exec('UPDATE preview_execution_attempts SET doc=? WHERE attempt_id=?',doc,record.context.scope.attemptId);}
 private local(snapshot:PreviewExecutionSnapshot){const result:unknown=this.ports.assertCurrent(snapshot);if(result!==undefined){if(result instanceof Promise)void result.catch(()=>{});throw Error('Synchronous preview authority fence required');}}
 private async fresh(snapshot:PreviewExecutionSnapshot){const actual=previewExecutionSnapshotSchema.parse(await bounded(()=>this.ports.current(structuredClone(snapshot))));if(!same(actual,snapshot))throw Error('Preview owner, retained source or generation changed');this.local(snapshot);}
 private require(context:PreviewExecutionContext){const parsed=previewExecutionContextSchema.parse(structuredClone(context)),record=this.get(parsed.scope.attemptId);if(!record||!same(record.context,parsed))throw Error('Exact durable preview attempt required');return record;}
 async prepare(input:PreviewExecutionSnapshot){const snapshot=previewExecutionSnapshotSchema.parse(structuredClone(input));await this.fresh(snapshot);return this.storage.transactionSync(()=>{this.local(snapshot);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM preview_execution_attempts WHERE slot=?',this.slot(snapshot)).toArray()[0];if(row){const record=JSON.parse(row.doc) as PreviewExecutionRecord;if(!same(record.context.snapshot,snapshot))throw Error('Original preview operation binding changed');return structuredClone(record.context);}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM preview_execution_attempts').toArray()[0]!.n>=1000)throw Error('Preview attempt audit capacity reached');const now=this.now(),scope={attemptId:crypto.randomUUID(),projectId:snapshot.projectId,incarnation:snapshot.incarnation,commit:snapshot.commit,tree:snapshot.tree,policyDigest:snapshot.policyDigest};const record:PreviewExecutionRecord={context:{snapshot,scope,sourceDigest:null},sourceProof:null,source:null,phase:'prepared',consumptionAttempted:false,ownerId:null,fundingKnown:true,createdAt:now,expiresAt:now+1200000};this.storage.sql.exec('INSERT INTO preview_execution_attempts VALUES(?,?,?)',scope.attemptId,this.slot(snapshot),JSON.stringify(record));return structuredClone(record.context);});}
 async snapshot(context:PreviewExecutionContext){const record=this.require(context);await this.fresh(record.context.snapshot);return this.require(context).context;}
 private owner(context:PreviewExecutionContext,invocationId:string){z.uuid().parse(invocationId);const record=this.require(context);if(record.ownerId!==invocationId)throw Error('Exact preview invocation ownership required');return record;}
 async claimInvocation(context:PreviewExecutionContext,invocationId:string){z.uuid().parse(invocationId);await this.snapshot(context);return this.storage.transactionSync(()=>{this.local(context.snapshot);const record=this.require(context);if(record.ownerId&&record.ownerId!==invocationId)return{status:'busy' as const};if(record.phase==='dispatched'||record.phase==='sealed')return{status:'recovered' as const,context:record.context};record.ownerId=invocationId;this.save(record);return{status:'owned' as const,context:record.context,invocationId};});}
 async finishInvocation(context:PreviewExecutionContext,invocationId:string){const record=this.owner(context,invocationId);if(record.phase==='dispatched'||record.source&&record.source.phase!=='closed'||!record.fundingKnown)throw Error('Original preview invocation quiescence remains unconfirmed');if(record.phase==='sealed'){const completion=await bounded(()=>this.ports.readCompletion?.(context)??Promise.resolve(null));if(!completion||!same(completion.scope,context.scope)||completion.sourceDigest!==context.sourceDigest||completion.image!==context.snapshot.image)throw Error('Original completed preview output required');}return this.storage.transactionSync(()=>{const current=this.owner(context,invocationId);current.ownerId=null;this.save(current);});}
 assertInvocation(context:PreviewExecutionContext,id:string){this.owner(context,id);}
 async sourceIntent(context:PreviewExecutionContext,input:{nativeRunId:string;credentialIntentId:string},invocationId:string){this.owner(context,invocationId);z.uuid().parse(input.nativeRunId);z.uuid().parse(input.credentialIntentId);await this.snapshot(context);return this.storage.transactionSync(()=>{this.local(context.snapshot);const record=this.require(context);if(record.phase!=='prepared')throw Error('Preview source preparation consumed');if(record.source){if(record.source.nativeRunId!==input.nativeRunId||record.source.credentialIntentId!==input.credentialIntentId)throw Error('Original preview source intent differs');return record.source;}record.source={...input,phase:'prepared',nativeClosed:false,credentialClosed:false};this.save(record);return structuredClone(record.source);});}
 async beginSource(context:PreviewExecutionContext,invocationId:string){this.owner(context,invocationId);await this.snapshot(context);return this.storage.transactionSync(()=>{this.local(context.snapshot);const record=this.require(context);if(!record.source||record.source.phase!=='prepared')throw Error('Original preview source dispatch is possible or consumed');record.source.phase='possible';this.save(record);return structuredClone(record.source);});}
 async closeSource(context:PreviewExecutionContext,invocationId:string){this.owner(context,invocationId);const original=this.require(context);if(!original.source)throw Error('Original preview source intent unavailable');const proof=await bounded(()=>this.ports.readSourceClosure(original.context,original.source!));if(proof.nativeRunId!==original.source.nativeRunId||proof.credentialIntentId!==original.source.credentialIntentId||proof.nativeClosed!==true||proof.credentialClosed!==true)throw Error('Original preview source cleanup remains unconfirmed');return this.storage.transactionSync(()=>{const record=this.require(context);if(!record.source||record.source.nativeRunId!==proof.nativeRunId||record.source.credentialIntentId!==proof.credentialIntentId)throw Error('Original source cleanup identity changed');record.source={...record.source,phase:'closed',nativeClosed:true,credentialClosed:true};this.save(record);return structuredClone(record.source);});}
 async bindSource(context:PreviewExecutionContext,input:TrustedGitSource,invocationId:string){this.owner(context,invocationId);const source=structuredClone(input);await this.snapshot(context);const manifest=await bounded(()=>bindBuildManifest('source',context.scope,source.files));if(!same(manifest,source.sourceManifest)||source.proof.commit!==context.scope.commit||source.proof.tree!==context.scope.tree||source.proof.sourceDigest!==manifest.digest||source.proof.providerRepoId!==context.snapshot.providerRepoId||source.proof.canonicalRepoName!==context.snapshot.canonicalRepoName)throw Error('Preview source provenance differs');await bounded(()=>this.ports.assertSource(context,source));await this.snapshot(context);return this.storage.transactionSync(()=>{this.local(context.snapshot);const record=this.owner(context,invocationId);if(context.sourceDigest!==null){if(context.sourceDigest===manifest.digest&&same(record.sourceProof,source.proof))return structuredClone(record.context);throw Error('Preview source already bound');}record.context={...record.context,sourceDigest:manifest.digest};record.sourceProof=source.proof;this.save(record);return structuredClone(record.context);});}
 async assertSourceProof(context:PreviewExecutionContext,proof:TrustedGitSourceProof){await this.snapshot(context);if(!same(this.require(context).sourceProof,proof))throw Error('Recorded preview Git source proof differs');}
 private runId(context:PreviewExecutionContext){return 'c05-preview-build-'+context.scope.attemptId;}
 private funded(context:PreviewExecutionContext,value:ManagedReservation|null,consumed:boolean){return Boolean(value&&value.runId===this.runId(context)&&value.accountKey===context.snapshot.accountKey&&value.resourceKind==='native-optional'&&value.usdMicros===43008&&value.maxInputBytes===1&&value.maxOutputTokens===1&&value.maxCalls===1&&value.maxContainerSeconds===1200&&value.state!=='released'&&value.calls===(consumed?1:0)&&value.containerSeconds===(consumed?1200:0));}
 async prepareGrant(context:PreviewExecutionContext,invocationId:string){this.owner(context,invocationId);await this.snapshot(context);let record=this.require(context);if(!context.sourceDigest||!record.sourceProof||record.source?.phase!=='closed'||!record.source.credentialClosed||!record.source.nativeClosed||record.phase==='sealed'||this.now()>=record.expiresAt)throw Error('Preview source closure or grant unavailable');this.storage.transactionSync(()=>{record=this.require(context);this.local(context.snapshot);if(record.phase==='prepared'){record.phase='funding_unknown';this.save(record);}});let receipt=await bounded(()=>this.ports.funding.read(this.runId(context)));await this.snapshot(context);if(!receipt){this.storage.transactionSync(()=>{record=this.owner(context,invocationId);record.fundingKnown=false;this.save(record);});const admission=await bounded(()=>this.ports.funding.reserve({resourceKind:'native-optional',runId:this.runId(context),accountKey:context.snapshot.accountKey,usdMicros:43008,maxInputBytes:1,maxOutputTokens:1,maxCalls:1,maxContainerSeconds:1200}));await this.snapshot(context);this.storage.transactionSync(()=>{record=this.owner(context,invocationId);record.fundingKnown=true;this.save(record);});if(!admission.allowed)throw Error('Optional preview funding unavailable');receipt=await bounded(()=>this.ports.funding.read(this.runId(context)));await this.snapshot(context);}if(!this.funded(context,receipt,true)){if(!this.funded(context,receipt,false))throw Error('Actual preview reservation differs');this.storage.transactionSync(()=>{record=this.require(context);if(record.consumptionAttempted)throw Error('Preview funding outcome remains unknown');record.consumptionAttempted=true;record.fundingKnown=false;this.save(record);});try{await bounded(()=>this.ports.funding.consume(this.runId(context)));}catch{/* Exact Global receipt readback below settles only this attempt. */}receipt=await bounded(()=>this.ports.funding.read(this.runId(context)));await this.snapshot(context);if(!this.funded(context,receipt,true))throw Error('Preview funding remains unconfirmed');}return this.storage.transactionSync(()=>{this.local(context.snapshot);record=this.require(context);if(record.phase==='sealed')throw Error('Preview dispatch sealed');record.phase=record.phase==='dispatched'?'dispatched':'paid';record.fundingKnown=true;this.owner(context,invocationId);this.save(record);return structuredClone(record);});}
 async authorize(context:PreviewExecutionContext){await this.snapshot(context);const record=this.require(context);if(!['paid','dispatched'].includes(record.phase)||this.now()>=record.expiresAt)throw Error('Preview execution not allowed');const receipt=await bounded(()=>this.ports.funding.read(this.runId(context)));await this.snapshot(context);if(!this.funded(context,receipt,true))throw Error('Actual optional preview funding differs');return this.require(context);}
 async claimDispatch(context:PreviewExecutionContext,invocationId:string){this.owner(context,invocationId);await this.authorize(context);return this.storage.transactionSync(()=>{this.local(context.snapshot);const record=this.owner(context,invocationId);if(record.phase!=='paid')throw Error('Original preview dispatch already possible');record.phase='dispatched';this.save(record);return{context:structuredClone(record.context),phase:'dispatched' as const};});}
 seal(context:PreviewExecutionContext,invocationId:string){const record=this.owner(context,invocationId);record.phase='sealed';this.save(record);}
 async dispatchState(context:PreviewExecutionContext){await this.snapshot(context);const phase=this.require(context).phase;return phase==='sealed'?'sealed' as const:phase==='dispatched'?'dispatched' as const:'not_dispatched' as const;}
}
