import {previewManifestPrefix} from "./preview-storage.js";
import {EVIDENCE_COPY_ID} from "./evidence-copy-id.js";
import {EvidenceStorageLedger} from "./evidence-storage.js";
import type {PreviewStorageManifest,PreviewStorageIdentity} from "./preview-storage-upload.js";
export interface PreviewCopyPlan {physicalKey:string;identity:PreviewStorageIdentity;keys:string[];bytes:number;kind:"preview"|"evidence";sha256?:string}
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
/** PUT dispatch receipts are durable before network dispatch. Unknown writes cannot be inferred absent. */
export class PreviewStorageWriters {
 constructor(private storage:DurableObjectStorage){storage.sql.exec("CREATE TABLE IF NOT EXISTS preview_copy_plans(physical_key TEXT PRIMARY KEY,project_id TEXT NOT NULL,incarnation TEXT NOT NULL,doc TEXT NOT NULL); CREATE INDEX IF NOT EXISTS preview_copy_project ON preview_copy_plans(project_id,incarnation); CREATE TABLE IF NOT EXISTS preview_copy_writers(physical_key TEXT NOT NULL,writer_id TEXT NOT NULL,closed INTEGER NOT NULL,pending TEXT NOT NULL,PRIMARY KEY(physical_key,writer_id)); CREATE TABLE IF NOT EXISTS preview_copy_fences(project_id TEXT NOT NULL,incarnation TEXT NOT NULL,PRIMARY KEY(project_id,incarnation)); CREATE TABLE IF NOT EXISTS preview_copy_retirements(physical_key TEXT PRIMARY KEY,doc TEXT NOT NULL); CREATE TABLE IF NOT EXISTS preview_generation_quarantines(physical_key TEXT PRIMARY KEY)");}
 plan(key:string):PreviewCopyPlan {const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM preview_copy_plans WHERE physical_key=?",key).toArray()[0];if(!row)throw new Error("Unknown preview copy scope");return JSON.parse(row.doc) as PreviewCopyPlan;}
 private writable(plan:PreviewCopyPlan){if(this.storage.sql.exec("SELECT physical_key FROM preview_generation_quarantines WHERE physical_key=?",plan.physicalKey).toArray().length)throw new Error("Preview generation is quarantined");if(this.storage.sql.exec("SELECT project_id FROM preview_copy_fences WHERE project_id=? AND incarnation=?",plan.identity.projectId,plan.identity.incarnation).toArray().length||this.storage.sql.exec("SELECT physical_key FROM preview_copy_retirements WHERE physical_key=?",plan.physicalKey).toArray().length)throw new Error("Preview copy is fenced or retired");}
 registerPreview(key:string):void{
  const row=this.storage.sql.exec<{payload:string}>("SELECT payload FROM preview_storage_reservations WHERE physical_key=?",key).toArray()[0];if(!row)throw new Error("Preview storage was not reserved");
  const manifest=JSON.parse(row.payload) as PreviewStorageManifest;
  if(key!==previewManifestPrefix(manifest.identity))throw new Error("Preview prefix scope changed");
  this.register({physicalKey:key,identity:manifest.identity,keys:manifest.assets.map(asset=>`${key}/${asset.path}`),bytes:manifest.totalBytes,kind:"preview"});
 }
 registerEvidence(identity:PreviewStorageIdentity,id:string,size:number,sha256:string):string{
  if(! /^[a-z0-9]{12,16}$/.test(identity.projectId)||!uuid.test(identity.incarnation)||! /^[a-f0-9]{40}$/.test(identity.commit)||! /^[a-f0-9]{12}$/.test(identity.accountKey)||! EVIDENCE_COPY_ID.test(id)||!Number.isSafeInteger(size)||size<1||size>1024*1024||! /^[a-f0-9]{64}$/.test(sha256))throw new Error("Invalid immutable evidence copy scope");
  const key=`evidence/${identity.projectId}/${identity.incarnation}/${id}.json`;
  new EvidenceStorageLedger(this.storage);
  const reservation=this.storage.sql.exec<{payload:string}>("SELECT payload FROM evidence_storage_reservations WHERE physical_key=?",key).toArray()[0];
  if(!reservation||reservation.payload!==JSON.stringify({identity,id,size,sha256}))throw new Error("Evidence immutable identity was not funded");
  this.register({physicalKey:key,identity,keys:[key],bytes:size,kind:"evidence",sha256});return key;
 }
 private register(plan:PreviewCopyPlan){this.storage.transactionSync(()=>{this.writable(plan);const old=this.storage.sql.exec<{doc:string}>("SELECT doc FROM preview_copy_plans WHERE physical_key=?",plan.physicalKey).toArray()[0];const doc=JSON.stringify(plan);if(old&&old.doc!==doc)throw new Error("Preview copy immutable scope changed");this.storage.sql.exec("INSERT OR IGNORE INTO preview_copy_plans VALUES(?,?,?,?)",plan.physicalKey,plan.identity.projectId,plan.identity.incarnation,doc);});}
 claim(key:string,writerId:string):{status:"owned"|"held"}{if(!uuid.test(writerId))throw new Error("Invalid preview writer");return this.storage.transactionSync(()=>{const plan=this.plan(key);this.writable(plan);const active=this.storage.sql.exec<{writer_id:string}>("SELECT writer_id FROM preview_copy_writers WHERE physical_key=? AND closed=0",key).toArray();if(active.some(row=>row.writer_id!==writerId))return{status:"held"};const old=this.storage.sql.exec<{closed:number}>("SELECT closed FROM preview_copy_writers WHERE physical_key=? AND writer_id=?",key,writerId).toArray()[0];if(old?.closed)throw new Error("Preview writer identity is retired");this.storage.sql.exec("INSERT OR IGNORE INTO preview_copy_writers VALUES(?,?,0,'[]')",key,writerId);return{status:"owned"};});}
 begin(key:string,writerId:string):void{if(this.claim(key,writerId).status==="held")throw new Error("Preview writer remains unresolved");}
 dispatch(key:string,writerId:string,assetKey:string):void{this.storage.transactionSync(()=>{const plan=this.plan(key);this.writable(plan);if(!plan.keys.includes(assetKey))throw new Error("Preview PUT key is outside its manifest");const row=this.storage.sql.exec<{closed:number;pending:string}>("SELECT closed,pending FROM preview_copy_writers WHERE physical_key=? AND writer_id=?",key,writerId).toArray()[0];if(!row||row.closed)throw new Error("Preview writer unavailable");const pending=JSON.parse(row.pending) as string[];if(pending.length)throw new Error("Preview PUT outcome is unresolved");this.storage.sql.exec("UPDATE preview_copy_writers SET pending=? WHERE physical_key=? AND writer_id=?",JSON.stringify([assetKey]),key,writerId);});}
 settled(key:string,writerId:string,assetKey:string):void{const row=this.storage.sql.exec<{pending:string}>("SELECT pending FROM preview_copy_writers WHERE physical_key=? AND writer_id=?",key,writerId).toArray()[0];if(!row||! (JSON.parse(row.pending) as string[]).includes(assetKey))throw new Error("Preview PUT receipt mismatch");this.storage.sql.exec("UPDATE preview_copy_writers SET pending='[]' WHERE physical_key=? AND writer_id=?",key,writerId);}
 finish(key:string,writerId:string):void{const row=this.storage.sql.exec<{pending:string}>("SELECT pending FROM preview_copy_writers WHERE physical_key=? AND writer_id=?",key,writerId).toArray()[0];if(!row||(JSON.parse(row.pending) as string[]).length)throw new Error("Preview writer has unresolved PUTs");this.storage.sql.exec("UPDATE preview_copy_writers SET closed=1 WHERE physical_key=? AND writer_id=?",key,writerId);}
 fence(projectId:string,incarnation:string):PreviewCopyPlan[]{if(! /^[a-z0-9]{12,16}$/.test(projectId)||!uuid.test(incarnation))throw new Error("Invalid preview cleanup scope");this.storage.sql.exec("INSERT OR IGNORE INTO preview_copy_fences VALUES(?,?)",projectId,incarnation);return this.storage.sql.exec<{doc:string}>("SELECT doc FROM preview_copy_plans WHERE project_id=? AND incarnation=?",projectId,incarnation).toArray().map(row=>JSON.parse(row.doc) as PreviewCopyPlan);}
 cleanupReady(key:string):boolean{const plan=this.plan(key);if(!this.storage.sql.exec("SELECT project_id FROM preview_copy_fences WHERE project_id=? AND incarnation=?",plan.identity.projectId,plan.identity.incarnation).toArray().length)return false;return !this.storage.sql.exec<{closed:number;pending:string}>("SELECT closed,pending FROM preview_copy_writers WHERE physical_key=?",key).toArray().some(row=>!row.closed||(JSON.parse(row.pending) as string[]).length>0);}
 retire(key:string):void{if(!this.cleanupReady(key))throw new Error("Preview cleanup writers are unconfirmed");const plan=this.plan(key);this.storage.sql.exec("INSERT OR IGNORE INTO preview_copy_retirements VALUES(?,?)",key,JSON.stringify(plan));}
}
