import {z} from "zod";
import {verifyBuildManifest,type BuildFile,type StaticBuildScope} from "./static-build-artifact";
import {isolatedExecutionContextSchema} from "./isolated-execution-grants";
import type {TrustedGitSource} from "./trusted-git-source";
const CHUNK=65536,MAX_METADATA=524288;
export const PREVIEW_SOURCE_CACHE_BYTES=64*1024*1024;
type Storage=Pick<DurableObjectStorage,"get"|"put"|"delete"|"transaction">;
export interface PreviewSourceIdentity{scope:StaticBuildScope;providerRepoId:string;canonicalRepoName:string}
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value));
const digest=z.string().regex(/^[a-f0-9]{64}$/);
const identitySchema=z.object({scope:isolatedExecutionContextSchema.shape.scope,providerRepoId:z.string().min(1).max(128),canonicalRepoName:z.string().min(1).max(200)}).strict();
const proofSchema=z.object({providerRepoId:identitySchema.shape.providerRepoId,canonicalRepoName:identitySchema.shape.canonicalRepoName,commit:sha,tree:sha,sourceDigest:digest,blobs:z.array(z.object({path:z.string().min(1).max(256),hash:sha,mode:z.enum(["100644","100755"])}).strict()).min(1).max(512)}).strict();
const manifestSchema=z.object({version:z.literal(1),kind:z.literal("source"),scope:identitySchema.shape.scope,files:z.array(z.object({path:z.string().min(1).max(256),size:z.number().int().min(0).max(4194304),digest}).strict()).min(1).max(512),totalBytes:z.number().int().min(0).max(16777216),digest}).strict();
const headerSchema=z.object({version:z.literal(1),sourceDigest:digest,metadataDigest:digest,metadataLength:z.number().int().min(1).max(MAX_METADATA),chunks:z.number().int().min(1).max(MAX_METADATA/CHUNK)}).strict();
const retirementSchema=z.object({version:z.literal(1),sourceDigest:digest,metadataDigest:digest,bytesFreed:z.number().int().min(0).max(PREVIEW_SOURCE_CACHE_BYTES),bytesRemaining:z.number().int().positive().max(PREVIEW_SOURCE_CACHE_BYTES)}).strict();
const reservationSchema=z.object({sourceDigest:digest,metadataDigest:digest,bytes:z.number().int().positive().max(PREVIEW_SOURCE_CACHE_BYTES)}).strict();
async function hash(bytes:Uint8Array,algorithm="SHA-256"){return Array.from(new Uint8Array(await crypto.subtle.digest(algorithm,new Uint8Array(bytes))),byte=>byte.toString(16).padStart(2,"0")).join("");}
async function blobHash(bytes:Uint8Array){const prefix=new TextEncoder().encode(`blob ${bytes.byteLength}\0`),object=new Uint8Array(prefix.byteLength+bytes.byteLength);object.set(prefix);object.set(bytes,prefix.byteLength);return hash(object,"SHA-1");}
async function bounded<T>(operation:Promise<T>,signal:AbortSignal){signal.throwIfAborted();let cancel=()=>{};try{return await Promise.race([operation,new Promise<never>((_,reject)=>{cancel=()=>reject(Error("Preview source storage deadline exceeded"));signal.addEventListener("abort",cancel,{once:true});})]);}finally{signal.removeEventListener("abort",cancel);}}
/** Only trusted source collectors may supply snapshots. Callers independently
 * fence current private repository authority before and after these storage reads.
 * Reservations survive uncertain writes; this helper never evicts or refunds. */
export class PreviewSourceStorage{
 constructor(private readonly storage:Storage){}
 private async prefix(identity:PreviewSourceIdentity){return "preview-source-"+await hash(new TextEncoder().encode(JSON.stringify(identity)));}
 private async validate(identity:PreviewSourceIdentity,source:TrustedGitSource,signal:AbortSignal){
  const proof=proofSchema.parse(source.proof),manifest=manifestSchema.parse(source.sourceManifest);
  if(proof.providerRepoId!==identity.providerRepoId||proof.canonicalRepoName!==identity.canonicalRepoName||proof.commit!==identity.scope.commit||proof.tree!==identity.scope.tree||proof.sourceDigest!==manifest.digest)throw Error("Preview source provenance differs");
  await bounded(verifyBuildManifest(manifest,identity.scope,source.files),signal);
  const blobs=new Map(proof.blobs.map(blob=>[blob.path,blob]));if(blobs.size!==proof.blobs.length||blobs.size!==source.files.length)throw Error("Preview Git blob inventory differs");
  for(const file of source.files){const blob=blobs.get(file.path);if(!blob||await bounded(blobHash(file.bytes),signal)!==blob.hash)throw Error("Preview Git blob bytes differ");}
  return {sourceManifest:manifest,files:source.files,proof} satisfies TrustedGitSource;
 }
 async write(proposed:PreviewSourceIdentity,input:TrustedGitSource):Promise<{sourceDigest:string}>{
  if(input.files.length<1||input.files.length>512)throw Error("Preview source file bound exceeded");let byteCount=0;for(const file of input.files){if(!(file.bytes instanceof Uint8Array)||file.bytes.byteLength>4194304||(byteCount+=file.bytes.byteLength)>16777216)throw Error("Preview source byte bound exceeded");}
  const identity=identitySchema.parse(structuredClone(proposed)),source:TrustedGitSource={sourceManifest:manifestSchema.parse(input.sourceManifest),proof:proofSchema.parse(input.proof),files:input.files.map(file=>({...file,bytes:file.bytes.slice()}))},signal=AbortSignal.timeout(15000),verified=await this.validate(identity,source,signal),prefix=await bounded(this.prefix(identity),signal);
  const metadata=new TextEncoder().encode(JSON.stringify({sourceManifest:verified.sourceManifest,proof:verified.proof}));if(metadata.byteLength>MAX_METADATA)throw Error("Preview source metadata exceeds durable bound");
  const header=headerSchema.parse({version:1,sourceDigest:verified.sourceManifest.digest,metadataDigest:await bounded(hash(metadata),signal),metadataLength:metadata.byteLength,chunks:Math.ceil(metadata.byteLength/CHUNK)}),fileChunks=verified.sourceManifest.files.reduce((count,file)=>count+Math.ceil(file.size/CHUNK),0),reservation=reservationSchema.parse({sourceDigest:header.sourceDigest,metadataDigest:header.metadataDigest,bytes:metadata.byteLength+verified.sourceManifest.totalBytes+(fileChunks+header.chunks)*1024+4096});
  await bounded(this.storage.transaction(async storage=>{signal.throwIfAborted();const previous=await bounded(storage.get(`${prefix}:reservation`),signal);if(previous){if(JSON.stringify(reservationSchema.parse(previous))!==JSON.stringify(reservation))throw Error("Immutable preview source reservation changed");return;}const used=z.number().int().min(0).max(PREVIEW_SOURCE_CACHE_BYTES).parse(await bounded(storage.get("preview-source-cache-bytes"),signal)??0);if(used+reservation.bytes>PREVIEW_SOURCE_CACHE_BYTES)throw Error("Preview source cache capacity reached; saved snapshots remain preserved");await bounded(storage.put(`${prefix}:reservation`,reservation),signal);await bounded(storage.put("preview-source-cache-bytes",used+reservation.bytes),signal);}),signal);
  await bounded(this.storage.transaction(async storage=>{signal.throwIfAborted();if(await bounded(storage.get(`${prefix}:retired`),signal))throw Error("Completed source snapshot retired; use a new scoped attempt");const previous=await bounded(storage.get(`${prefix}:complete`),signal);if(previous){if(JSON.stringify(headerSchema.parse(previous))!==JSON.stringify(header))throw Error("Immutable preview source snapshot changed");return;}for(let part=0;part<header.chunks;part++)await bounded(storage.put(`${prefix}:metadata:${part}`,metadata.slice(part*CHUNK,(part+1)*CHUNK)),signal);const files=new Map(verified.files.map(file=>[file.path,file.bytes]));for(let index=0;index<verified.sourceManifest.files.length;index++){const bytes=files.get(verified.sourceManifest.files[index]!.path)!;for(let part=0;part<Math.ceil(bytes.byteLength/CHUNK);part++)await bounded(storage.put(`${prefix}:file:${index}:${part}`,bytes.slice(part*CHUNK,(part+1)*CHUNK)),signal);}signal.throwIfAborted();await bounded(storage.put(`${prefix}:complete`,header),signal);}),signal);
  return{sourceDigest:header.sourceDigest};
 }
 async read(proposed:PreviewSourceIdentity&{sourceDigest:string}):Promise<TrustedGitSource|null>{
  const frozen=structuredClone(proposed),sourceDigest=digest.parse(frozen.sourceDigest),identity=identitySchema.parse({scope:frozen.scope,providerRepoId:frozen.providerRepoId,canonicalRepoName:frozen.canonicalRepoName}),signal=AbortSignal.timeout(15000),prefix=await bounded(this.prefix(identity),signal),raw=await bounded(this.storage.get(`${prefix}:complete`),signal);if(!raw)return null;
  const header=headerSchema.parse(raw),reservation=reservationSchema.parse(await bounded(this.storage.get(`${prefix}:reservation`),signal));if(header.sourceDigest!==sourceDigest)return null;const retired=await bounded(this.storage.get(`${prefix}:retired`),signal);if(retired){const receipt=retirementSchema.parse(retired);if(receipt.sourceDigest!==header.sourceDigest||receipt.metadataDigest!==header.metadataDigest||receipt.bytesFreed+receipt.bytesRemaining!==reservation.bytes)throw Error("Preview source retirement identity differs");return null;}if(reservation.sourceDigest!==header.sourceDigest||reservation.metadataDigest!==header.metadataDigest||header.chunks!==Math.ceil(header.metadataLength/CHUNK))throw Error("Preview source completion identity differs");
  const metadata=new Uint8Array(header.metadataLength);for(let part=0;part<header.chunks;part++){const chunk=await bounded(this.storage.get<Uint8Array>(`${prefix}:metadata:${part}`),signal),length=Math.min(CHUNK,header.metadataLength-part*CHUNK);if(!(chunk instanceof Uint8Array)||chunk.byteLength!==length)throw Error("Preview source metadata chunk missing or corrupt");metadata.set(chunk,part*CHUNK);}if(await bounded(hash(metadata),signal)!==header.metadataDigest)throw Error("Preview source metadata digest differs");
  const parsed=z.object({sourceManifest:manifestSchema,proof:proofSchema}).strict().parse(JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(metadata))),files:BuildFile[]=[];if(parsed.sourceManifest.files.reduce((bytes,file)=>bytes+file.size,0)!==parsed.sourceManifest.totalBytes)throw Error("Preview source byte inventory differs");for(let index=0;index<parsed.sourceManifest.files.length;index++){const file=parsed.sourceManifest.files[index]!,bytes=new Uint8Array(file.size);for(let part=0;part<Math.ceil(file.size/CHUNK);part++){const chunk=await bounded(this.storage.get<Uint8Array>(`${prefix}:file:${index}:${part}`),signal),length=Math.min(CHUNK,file.size-part*CHUNK);if(!(chunk instanceof Uint8Array)||chunk.byteLength!==length)throw Error("Preview source file chunk missing or corrupt");bytes.set(chunk,part*CHUNK);}files.push({path:file.path,kind:"file",bytes});}
  const recovered=await this.validate(identity,{sourceManifest:parsed.sourceManifest,proof:parsed.proof,files},signal);if(recovered.sourceManifest.digest!==sourceDigest||JSON.stringify(await bounded(this.storage.get(`${prefix}:complete`),signal))!==JSON.stringify(header))throw Error("Preview source changed during recovery");return recovered;
 }
 /** Backend callers must first prove exact retained output and positive native/
  * credential closure. No caller-provided cleanup flag can substitute for that. */
 async retireCompleted(proposed:PreviewSourceIdentity&{sourceDigest:string}):Promise<{retired:true;bytesFreed:number}>{
  const frozen=structuredClone(proposed),identity=identitySchema.parse({scope:frozen.scope,providerRepoId:frozen.providerRepoId,canonicalRepoName:frozen.canonicalRepoName}),sourceDigest=digest.parse(frozen.sourceDigest),signal=AbortSignal.timeout(15000),prefix=await bounded(this.prefix(identity),signal),header=headerSchema.parse(await bounded(this.storage.get(`${prefix}:complete`),signal)),reservation=reservationSchema.parse(await bounded(this.storage.get(`${prefix}:reservation`),signal));if(header.sourceDigest!==sourceDigest||reservation.sourceDigest!==sourceDigest||header.metadataDigest!==reservation.metadataDigest)throw Error("Exact completed source retirement required");
  const previous=await bounded(this.storage.get(`${prefix}:retired`),signal);if(previous){const receipt=retirementSchema.parse(previous);if(receipt.sourceDigest!==sourceDigest||receipt.metadataDigest!==header.metadataDigest||receipt.bytesRemaining+receipt.bytesFreed!==reservation.bytes)throw Error("Source retirement identity changed");return{retired:true,bytesFreed:receipt.bytesFreed};}
  const source=await this.read({...identity,sourceDigest});if(!source)throw Error("Only complete source snapshots may retire");const chunks=source.sourceManifest.files.reduce((count,file)=>count+Math.ceil(file.size/CHUNK),0),receipt=retirementSchema.parse({version:1,sourceDigest,metadataDigest:header.metadataDigest,bytesFreed:source.sourceManifest.totalBytes+chunks*1024,bytesRemaining:header.metadataLength+header.chunks*1024+4096});if(receipt.bytesFreed+receipt.bytesRemaining!==reservation.bytes)throw Error("Source retirement capacity proof differs");
  await bounded(this.storage.transaction(async storage=>{if(JSON.stringify(await bounded(storage.get(`${prefix}:complete`),signal))!==JSON.stringify(header)||JSON.stringify(await bounded(storage.get(`${prefix}:reservation`),signal))!==JSON.stringify(reservation))throw Error("Completed source identity changed before retirement");const duplicate=await bounded(storage.get(`${prefix}:retired`),signal);if(duplicate){if(JSON.stringify(retirementSchema.parse(duplicate))!==JSON.stringify(receipt))throw Error("Source retirement receipt changed");return;}const used=z.number().int().min(reservation.bytes).max(PREVIEW_SOURCE_CACHE_BYTES).parse(await bounded(storage.get("preview-source-cache-bytes"),signal));for(let index=0;index<source.sourceManifest.files.length;index++)for(let part=0;part<Math.ceil(source.sourceManifest.files[index]!.size/CHUNK);part++)if(!await bounded(storage.delete(`${prefix}:file:${index}:${part}`),signal))throw Error("Source chunk deletion remains unconfirmed");await bounded(storage.put(`${prefix}:retired`,receipt),signal);await bounded(storage.put("preview-source-cache-bytes",used-receipt.bytesFreed),signal);}),signal);
  return{retired:true,bytesFreed:receipt.bytesFreed};
 }

}
