import {z} from 'zod';
import {repairDigest} from './protected-model-repair';
import type {ProtectedRepairSource} from './protected-repair-plan';
import type {IntegrationNativeRuntimeScope} from './integration-native-runtime';
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(v=>!/^0{40}$/.test(v)),digest=z.string().regex(/^[a-f0-9]{64}$/);
const safePath=z.string().min(1).max(256).refine(v=>!v.startsWith('/')&&!/[\\\x00-\x20\x7f%?#]/.test(v)&&v.split('/').every(p=>p&&p!=='.'&&p!=='..'&&!/^\.env(?:\.|$)/i.test(p)&&!['.git','.ssh','.aws','.gnupg','credentials','id_rsa','id_ed25519'].includes(p.toLowerCase())&&!/\.(pem|key|p12|pfx|keystore)$/i.test(p)));
const contextSchema=z.object({projectId:z.string().regex(/^[a-z0-9]{12,16}$/),incarnation:z.uuid(),candidateId:z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),workflowId:z.string().min(1).max(200),actorId:z.string().min(1).max(256),accountKey:z.string().min(1).max(256),nativeRunId:z.uuid(),attemptId:z.uuid(),acceptedBase:sha,contributorCommits:z.record(z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),sha).refine(v=>Object.keys(v).length>0&&Object.keys(v).length<=8),policyDigest:digest,requirementsDigest:digest}).strict();
export const protectedConflictContextSchema=contextSchema;
export type ProtectedConflictContext=z.infer<typeof contextSchema>;
const snapshotSchema=z.object({head:sha,mergeHeads:z.array(sha).min(1).max(8),base:sha,contributors:z.record(z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),sha),index:z.array(z.object({path:safePath,mode:z.enum(['100644','100755']),stage:z.number().int().min(0).max(3),object:sha}).strict()).min(1).max(1536),files:z.array(z.object({path:safePath,mode:z.enum(['100644','100755']),digest,size:z.number().int().min(0).max(16777216)}).strict()).min(1).max(512)}).strict();
export type ProtectedConflictSnapshot=z.infer<typeof snapshotSchema>;
/** This fixed program reads native Git and filesystem metadata only. No repository
 * JavaScript, hooks, filters, credential configuration or model commands execute. */
export const PROTECTED_CONFLICT_INSPECTOR=String.raw`const fs=require('node:fs'),crypto=require('node:crypto');const input=JSON.parse(process.argv[1]);const root='/workspace/integration';function git(args){const p=Bun.spawnSync(['git','-c','core.fsmonitor=false','-c','core.hooksPath=/dev/null','-C',root,...args],{env:{PATH:process.env.PATH,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_OPTIONAL_LOCKS:'0'},maxBuffer:2000000});if(p.exitCode)throw Error('Native conflict Git inspection failed');return p.stdout.toString();}const base=git(['rev-parse','--verify',input.acceptedBase+'^{commit}']).trim(),head=git(['rev-parse','--verify','HEAD^{commit}']).trim();git(['merge-base','--is-ancestor',base,head]);const mergePath=git(['rev-parse','--git-path','MERGE_HEAD']).trim();const mergeHeads=fs.readFileSync(require('node:path').resolve(root,mergePath),'utf8').trim().split('\n');const contributors={};for(const [id,commit] of Object.entries(input.contributorCommits))contributors[id]=git(['rev-parse','--verify',commit+'^{commit}']).trim();const indexRaw=git(['ls-files','--stage','-z']);const index=indexRaw.split('\0').filter(Boolean).map(row=>{const m=/^([0-9]{6}) ([a-f0-9]{40}) ([0-3])\t(.+)$/.exec(row);if(!m)throw Error('Malformed native Git index');return{mode:m[1],object:m[2],stage:Number(m[3]),path:m[4]};});const names=[...new Set(index.map(row=>row.path))].sort();if(names.length>512)throw Error('Native conflict inventory exceeds bound');let total=0;const files=names.map(path=>{if(path.length>256||/[\\\x00-\x20\x7f%?#]/.test(path)||path.startsWith('/')||path.split('/').some(p=>!p||p==='.'||p==='..'||/^\.env(?:\.|$)/i.test(p)||['.git','.ssh','.aws','.gnupg','credentials','id_rsa','id_ed25519'].includes(p.toLowerCase())||/\.(pem|key|p12|pfx|keystore)$/i.test(p)))throw Error('Unsafe native path');let full=root;for(const part of path.split('/')){full+='/'+part;if(fs.lstatSync(full).isSymbolicLink())throw Error('Native symlink refused');}const s=fs.lstatSync(full);if(!s.isFile())throw Error('Native nonregular file refused');total+=s.size;if(total>16777216)throw Error('Native conflict bytes exceed bound');const bytes=fs.readFileSync(full);const after=fs.lstatSync(full);if(!after.isFile()||after.isSymbolicLink()||after.ino!==s.ino||after.size!==s.size||after.mtimeMs!==s.mtimeMs||bytes.length!==s.size)throw Error('Native file changed during inspection');return{path,mode:(s.mode&0o111)?'100755':'100644',size:bytes.length,digest:crypto.createHash('sha256').update(bytes).digest('hex')};});if(git(['rev-parse','--verify','HEAD^{commit}']).trim()!==head||git(['ls-files','--stage','-z'])!==indexRaw||fs.readFileSync(require('node:path').resolve(root,mergePath),'utf8').trim().split('\n').join('\n')!==mergeHeads.join('\n'))throw Error('Native conflict state changed during inspection');console.log(JSON.stringify({head,mergeHeads,base,contributors,index,files}));`;
export interface ProtectedConflictPorts{
 assertCurrent(context:ProtectedConflictContext):void;
 /** Actual registered native command admission, never an allowed boolean. */
 admit(context:ProtectedConflictContext):Promise<{scope:IntegrationNativeRuntimeScope;nativeRunId:string;commandId:string}>;
 inspect(permit:{scope:IntegrationNativeRuntimeScope;nativeRunId:string;commandId:string},argv:readonly string[]):Promise<{stdout:string;completedCommandId:string}>;
}
export function validateProtectedConflictSnapshot(context:unknown,raw:unknown){const input=contextSchema.parse(context),snapshot=snapshotSchema.parse(raw);if(snapshot.base!==input.acceptedBase||JSON.stringify(snapshot.contributors)!==JSON.stringify(input.contributorCommits)||snapshot.mergeHeads.some(h=>!Object.values(input.contributorCommits).includes(h))||new Set(snapshot.mergeHeads).size!==snapshot.mergeHeads.length)throw Error('Native conflict frozen Git scope differs');const stages=new Set<string>(),files=new Map(snapshot.files.map(f=>[f.path,f]));if(files.size!==snapshot.files.length||snapshot.files.reduce((n,f)=>n+f.size,0)>16777216)throw Error('Native conflict inventory differs');let conflicts=0;for(const row of snapshot.index){const key=`${row.path}:${row.stage}`;if(stages.has(key)||!files.has(row.path)||row.mode!==files.get(row.path)!.mode)throw Error('Native conflict index differs');stages.add(key);if(row.stage>0)conflicts++;}for(const file of snapshot.files){const rows=snapshot.index.filter(row=>row.path===file.path);if(rows.some(row=>row.stage>0)&&(!rows.some(row=>row.stage===2)||!rows.some(row=>row.stage===3)))throw Error('Modify/delete conflict requires contributor decision');if(new Set(rows.map(row=>row.mode)).size!==1)throw Error('Conflicting file modes require contributor decision');}if(!conflicts||snapshot.files.some(f=>!snapshot.index.some(r=>r.path===f.path))||snapshot.index.some(r=>r.stage===0&&snapshot.index.some(other=>other.path===r.path&&other.stage>0)))throw Error('Native text conflict index unavailable');return snapshot;}
export async function captureProtectedConflictSource(context:ProtectedConflictContext,ports:ProtectedConflictPorts){const input=contextSchema.parse(structuredClone(context));ports.assertCurrent(input);const permit=await ports.admit(input);ports.assertCurrent(input);if(permit.nativeRunId!==input.nativeRunId||permit.scope.projectId!==input.projectId||permit.scope.incarnation!==input.incarnation||permit.scope.candidateId!==input.candidateId||permit.scope.workflowId!==input.workflowId||permit.scope.actorId!==input.actorId||permit.scope.accountKey!==input.accountKey)throw Error('Registered native conflict ownership differs');z.uuid().parse(permit.commandId);const answer=await ports.inspect(permit,['bun','-e',PROTECTED_CONFLICT_INSPECTOR,JSON.stringify({acceptedBase:input.acceptedBase,contributorCommits:input.contributorCommits})]);ports.assertCurrent(input);if(answer.completedCommandId!==permit.commandId||new TextEncoder().encode(answer.stdout).length>2000000)throw Error('Native conflict command completion unavailable');const snapshot=validateProtectedConflictSnapshot(input,JSON.parse(answer.stdout));snapshot.index.sort((a,b)=>a.path.localeCompare(b.path)||a.stage-b.stage);snapshot.files.sort((a,b)=>a.path.localeCompare(b.path));snapshot.mergeHeads.sort();const sourceDigest=await repairDigest(JSON.stringify({context:input,snapshot}));ports.assertCurrent(input);const source:Extract<ProtectedRepairSource,{kind:'uncommitted-conflict-input'}>={kind:'uncommitted-conflict-input',projectId:input.projectId,incarnation:input.incarnation,candidateId:input.candidateId,attemptId:input.attemptId,acceptedBase:input.acceptedBase,contributorCommits:input.contributorCommits,sourceDigest,policyDigest:input.policyDigest,requirementsDigest:input.requirementsDigest};return{source,snapshot,nativeRunId:input.nativeRunId,commandId:permit.commandId,acceptanceEvidence:false as const};}
