import {z} from "zod";
import {isSafeRef} from "../core/sanitize";
const contextSchema=z.object({kind:z.enum(["publication","task-ready","rebase-read"]),operationId:z.string().min(1).max(200),projectId:z.string().min(1).max(128),incarnation:z.string().uuid(),repoName:z.string().min(1).max(200),actorId:z.string().min(1).max(256),accountKey:z.string().min(1).max(200),snapshotDigest:z.string().regex(/^[a-f0-9]{64}$/),ref:z.string().refine(value=>value.startsWith("refs/")&&isSafeRef(value))}).strict();
export type RefReadCredentialContext=z.infer<typeof contextSchema>;
type Status="issuance_unknown"|"pending"|"revoked"|"expired_unverified";
type Row={id:string;context:string;repo_name:string;account_key:string;intent_expires_at:number;token:string|null;fingerprint:string|null;expires_at:number|null;status:Status;attempts:number;automatic_sweeps:number};
const identity=z.string().uuid();
async function fingerprint(token:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token))),v=>v.toString(16).padStart(2,"0")).join("");}
/** Cleanup ownership only. Callers must separately fence genuine operation authority. */
export class RefReadCredentialIncidents {
 constructor(private storage:DurableObjectStorage){storage.sql.exec("CREATE TABLE IF NOT EXISTS ref_read_credential_incidents(id TEXT PRIMARY KEY,context TEXT NOT NULL,repo_name TEXT NOT NULL,account_key TEXT NOT NULL,intent_expires_at INTEGER NOT NULL,token TEXT,fingerprint TEXT,expires_at INTEGER,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,automatic_sweeps INTEGER NOT NULL DEFAULT 0)");if(!storage.sql.exec<{name:string}>("PRAGMA table_info(ref_read_credential_incidents)").toArray().some(row=>row.name==="automatic_sweeps"))storage.sql.exec("ALTER TABLE ref_read_credential_incidents ADD COLUMN automatic_sweeps INTEGER NOT NULL DEFAULT 0");}
 private row(id:string){identity.parse(id);return this.storage.sql.exec<Row>("SELECT * FROM ref_read_credential_incidents WHERE id=?",id).toArray()[0];}
 begin(id:string,context:RefReadCredentialContext,expiresAt:number,validate:()=>void,now=Date.now()):boolean{identity.parse(id);const value=contextSchema.parse(context);if(!Number.isSafeInteger(expiresAt)||expiresAt<=now||expiresAt>now+60000)throw new Error("Invalid read credential intent");return this.storage.transactionSync(()=>{validate();const old=this.row(id),payload=JSON.stringify(value);if(old){if(old.context!==payload||old.intent_expires_at!==expiresAt)throw new Error("Read credential intent changed");return false;}if(this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM ref_read_credential_incidents").one().n>=1000)throw new Error("Read credential audit capacity reached");this.storage.sql.exec("INSERT INTO ref_read_credential_incidents(id,context,repo_name,account_key,intent_expires_at,status) VALUES(?,?,?,?,?,'issuance_unknown')",id,payload,value.repoName,value.accountKey,expiresAt);return true;});}
 async record(id:string,repoName:string,token:string,expiresAt:number){if(!token||token.length>16384||/[\r\n\0]/.test(token))throw new Error("Invalid read credential receipt");const digest=await fingerprint(token);this.storage.transactionSync(()=>{const row=this.row(id);if(!row||row.repo_name!==repoName)throw new Error("Read credential receipt scope changed");if(row.fingerprint){if(row.fingerprint!==digest||row.expires_at!==(Number.isSafeInteger(expiresAt)?expiresAt:null))throw new Error("Read credential receipt changed");return;}this.storage.sql.exec("UPDATE ref_read_credential_incidents SET token=?,fingerprint=?,expires_at=?,status='pending' WHERE id=?",token,digest,Number.isSafeInteger(expiresAt)?expiresAt:null,id);});}
 credentialForRevocation(id:string){const row=this.row(id);return row?.status==='pending'&&row.token?{id:row.id,repoName:row.repo_name,accountKey:row.account_key,token:row.token}:null;}
 markAttempt(id:string){return this.storage.transactionSync(()=>{const row=this.row(id);if(row?.status!=="pending")return false;this.storage.sql.exec("UPDATE ref_read_credential_incidents SET attempts=attempts+1 WHERE id=?",id);return true;});}
 async markRevoked(id:string,token:string){const digest=await fingerprint(token);this.storage.transactionSync(()=>{const row=this.row(id);if(!row||row.fingerprint!==digest)throw new Error("Read credential cleanup receipt changed");this.storage.sql.exec("UPDATE ref_read_credential_incidents SET token=NULL,status='revoked' WHERE id=?",id);});}
 markAutomaticSweep(id:string){return this.storage.transactionSync(()=>{const row=this.row(id);if(row?.status!=="pending"||row.automatic_sweeps>=4)return false;this.storage.sql.exec("UPDATE ref_read_credential_incidents SET automatic_sweeps=automatic_sweeps+1 WHERE id=?",id);return true;});}
 nextWake(now=Date.now()):number|null{if(!Number.isSafeInteger(now))throw new Error("Invalid cleanup clock");return this.storage.sql.exec("SELECT id FROM ref_read_credential_incidents WHERE status='pending' AND automatic_sweeps<4 AND attempts<4 LIMIT 1").toArray().length?now+60000:null;}
 pendingBatch(){return this.storage.sql.exec<Row>("SELECT * FROM ref_read_credential_incidents WHERE status='pending' AND attempts<4 AND automatic_sweeps<4 ORDER BY intent_expires_at,id LIMIT 20").toArray().map(row=>({id:row.id,repoName:row.repo_name,accountKey:row.account_key,token:row.token!}));}
 summary(id:string){const row=this.row(id);return row?{status:row.status,expiresAt:row.expires_at}:null;}
 hasPending(){return this.storage.sql.exec("SELECT id FROM ref_read_credential_incidents WHERE status!='revoked' LIMIT 1").toArray().length>0;}
}
