import {z} from 'zod';
import {createHash} from 'node:crypto';
import {isSafeRef} from '../core/sanitize';
const id=z.string().min(1).max(200),sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value));
const sourceSchema=z.object({name:z.string().min(1).max(200).refine(value=>isSafeRef(value)&&!value.startsWith('refs/')&&value!=='HEAD'),tagOperationId:z.uuid(),acceptedJournalId:id,acceptedRef:z.string().max(220).refine(value=>value.startsWith('refs/heads/')&&isSafeRef(value)),acceptedRootVersion:z.number().int().nonnegative().safe(),commit:sha,tree:sha}).strict().refine(value=>(value.acceptedJournalId==="baseline")===(value.acceptedRootVersion===0),"Baseline provenance requires version zero; reviewed acceptance requires a positive version");
const contentSchema=z.object({prerelease:z.boolean().optional(),title:z.string().trim().min(1).max(200),notes:z.string().max(16000).refine(value=>!value.includes('\0'))}).strict();
const scopeSchema=z.object({id:z.uuid(),projectId:id,incarnation:z.uuid(),canonicalRepoName:id,authorId:z.string().min(1).max(256),source:sourceSchema}).strict();
export type ReleaseScope=z.infer<typeof scopeSchema>;
export type ReleaseContent=z.infer<typeof contentSchema>;
const tagProofSchema=z.object({projectId:id,incarnation:z.uuid(),canonicalRepoName:id,source:sourceSchema,status:z.literal('confirmed'),object:sha,type:z.enum(['commit','tag']),commit:sha,tree:sha}).strict();
export type ConfirmedReleaseTag=z.infer<typeof tagProofSchema>;
export interface ReleaseRecord {prerelease?:boolean;scope:ReleaseScope;title:string;notes:string;revision:number;phase:'draft'|'published';createdAt:string;updatedAt:string;publishedAt?:string;publishedBy?:string;tag?:{object:string;type:'commit'|'tag';commit:string;tree:string}}
export class ReleaseRecordError extends Error {}
function digest(value:unknown){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
/** Metadata only. Authority and actual native tag receipts come from the owning
 * repository controller. Markdown remains text; rendering must escape HTML. */
export class ReleaseRecords {
 constructor(private storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS release_records(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,incarnation TEXT NOT NULL,repo_name TEXT NOT NULL,tag_name TEXT NOT NULL,payload TEXT NOT NULL,doc TEXT NOT NULL,UNIQUE(project_id,incarnation,repo_name,tag_name))');storage.sql.exec('CREATE TABLE IF NOT EXISTS release_edits(id TEXT PRIMARY KEY,release_id TEXT NOT NULL,payload_hash TEXT NOT NULL,revision INTEGER NOT NULL,editor_id TEXT NOT NULL,at TEXT NOT NULL)');}
 get(id:string):ReleaseRecord|null{z.uuid().parse(id);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM release_records WHERE id=?',id).toArray()[0];return row?JSON.parse(row.doc) as ReleaseRecord:null;}
 private save(row:ReleaseRecord){this.storage.sql.exec('UPDATE release_records SET doc=? WHERE id=?',JSON.stringify(row),row.scope.id);}
 create(scope:ReleaseScope,content:ReleaseContent,authorize:()=>void,now=new Date()):ReleaseRecord{const parsed=scopeSchema.parse(scope),body=contentSchema.parse(content),time=now.toISOString(),payload=JSON.stringify({scope:parsed,content:body});return this.storage.transactionSync(()=>{authorize();const old=this.storage.sql.exec<{payload:string;doc:string}>('SELECT payload,doc FROM release_records WHERE id=?',parsed.id).toArray()[0];if(old){if(old.payload!==payload)throw new ReleaseRecordError('Release creation identity changed');return JSON.parse(old.doc) as ReleaseRecord;}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM release_records').toArray()[0]!.n>=1000)throw new ReleaseRecordError('Release metadata capacity reached');const row:ReleaseRecord={scope:parsed,...body,revision:1,phase:'draft',createdAt:time,updatedAt:time};this.storage.sql.exec('INSERT INTO release_records VALUES(?,?,?,?,?,?,?)',parsed.id,parsed.projectId,parsed.incarnation,parsed.canonicalRepoName,parsed.source.name,payload,JSON.stringify(row));return row;});}
 publish(scope:ReleaseScope,proof:ConfirmedReleaseTag,publisherId:string,expectedRevision:number,authorize:()=>void,now=new Date()):ReleaseRecord{const parsed=scopeSchema.parse(scope),receipt=tagProofSchema.parse(proof),publisher=z.string().min(1).max(256).parse(publisherId);return this.storage.transactionSync(()=>{authorize();const row=this.get(parsed.id);if(!row||JSON.stringify(row.scope)!==JSON.stringify(parsed)||receipt.projectId!==parsed.projectId||receipt.incarnation!==parsed.incarnation||receipt.canonicalRepoName!==parsed.canonicalRepoName||JSON.stringify(receipt.source)!==JSON.stringify(parsed.source)||receipt.commit!==parsed.source.commit||receipt.tree!==parsed.source.tree||(receipt.type==='commit'&&receipt.object!==receipt.commit))throw new ReleaseRecordError('Exact scoped confirmed tag receipt required');const tag={object:receipt.object,type:receipt.type,commit:receipt.commit,tree:receipt.tree};if(row.phase==='published'){if(JSON.stringify(row.tag)!==JSON.stringify(tag)||row.publishedBy!==publisher)throw new ReleaseRecordError('Published release binding changed');return row;}if(row.revision!==expectedRevision)throw new ReleaseRecordError('Release revision changed');row.tag=tag;row.phase='published';row.publishedBy=publisher;row.publishedAt=now.toISOString();row.updatedAt=row.publishedAt;row.revision++;this.save(row);return row;});}
 editHistory(scope:ReleaseScope,authorize:()=>void){const parsed=scopeSchema.parse(scope);return this.storage.transactionSync(()=>{authorize();const row=this.get(parsed.id);if(!row||JSON.stringify(row.scope)!==JSON.stringify(parsed))throw new ReleaseRecordError('Release scope changed');return this.storage.sql.exec<{id:string;revision:number;editor_id:string;at:string}>('SELECT id,revision,editor_id,at FROM release_edits WHERE release_id=? ORDER BY revision LIMIT 100',parsed.id).toArray().map(edit=>({id:edit.id,revision:edit.revision,editorId:edit.editor_id,at:edit.at}));});}
 edit(scope:ReleaseScope,editId:string,expectedRevision:number,content:ReleaseContent,editorId:string,authorize:()=>void,now=new Date()):{record:ReleaseRecord;appliedRevision:number;replayed:boolean}{const parsed=scopeSchema.parse(scope),mutation=z.uuid().parse(editId),body=contentSchema.parse(content),editor=z.string().min(1).max(256).parse(editorId);if(!Number.isSafeInteger(expectedRevision)||expectedRevision<1)throw new ReleaseRecordError('Exact release revision required');const hash=digest({scope:parsed,expectedRevision,content:body,editor});return this.storage.transactionSync(()=>{authorize();const row=this.get(parsed.id);if(!row||JSON.stringify(row.scope)!==JSON.stringify(parsed))throw new ReleaseRecordError('Release scope changed');const old=this.storage.sql.exec<{release_id:string;payload_hash:string;revision:number}>('SELECT release_id,payload_hash,revision FROM release_edits WHERE id=?',mutation).toArray()[0];if(old){if(old.release_id!==parsed.id||old.payload_hash!==hash)throw new ReleaseRecordError('Release edit identity changed');return{record:row,appliedRevision:old.revision,replayed:true};}if(row.revision!==expectedRevision)throw new ReleaseRecordError('Release revision changed');if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM release_edits WHERE release_id=?',parsed.id).toArray()[0]!.n>=100)throw new ReleaseRecordError('Release edit receipt capacity reached');Object.assign(row,body);row.revision++;row.updatedAt=now.toISOString();this.save(row);this.storage.sql.exec('INSERT INTO release_edits VALUES(?,?,?,?,?,?)',mutation,parsed.id,hash,row.revision,editor,row.updatedAt);return{record:row,appliedRevision:row.revision,replayed:false};});}
}
