import { z } from 'zod';
import type { ReleaseScope } from './release-records';
export const releaseAssetInputSchema=z.object({id:z.uuid(),name:z.string().min(1).max(150).regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/),sha256:z.string().regex(/^[a-f0-9]{64}$/),size:z.number().int().positive().max(5*1024*1024)}).strict();
export type ReleaseAssetInput=z.infer<typeof releaseAssetInputSchema>;
export interface ReleaseAsset extends ReleaseAssetInput {phase:'pending'|'verified';key:string;scope:ReleaseScope}
/** Private bounded assets: upload identities and names cannot be overwritten, including after lost acknowledgements. */
export class ReleaseAssets {
 constructor(private storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS release_assets(id TEXT PRIMARY KEY,release_id TEXT NOT NULL,name TEXT NOT NULL,doc TEXT NOT NULL,UNIQUE(release_id,name))');}
 list(scope:ReleaseScope){return this.storage.sql.exec<{doc:string}>('SELECT doc FROM release_assets WHERE release_id=? ORDER BY name',scope.id).toArray().map(row=>JSON.parse(row.doc) as ReleaseAsset).map(asset=>{if(JSON.stringify(asset.scope)!==JSON.stringify(scope))throw Error('Asset repository scope changed');return asset;});}
 private save(asset:ReleaseAsset){this.storage.sql.exec('UPDATE release_assets SET doc=? WHERE id=?',JSON.stringify(asset),asset.id);}
 async upload(scope:ReleaseScope,input:ReleaseAssetInput,bytes:ArrayBuffer,bucket:R2Bucket,authorize:()=>void,assertDraft:()=>void){const parsed=releaseAssetInputSchema.parse(input);if(bytes.byteLength!==parsed.size)throw Error('Asset size differs');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(digest!==parsed.sha256)throw Error('Asset digest differs');const asset=this.storage.transactionSync(()=>{authorize();const old=this.storage.sql.exec<{doc:string}>('SELECT doc FROM release_assets WHERE id=?',parsed.id).toArray()[0];if(old){const saved=JSON.parse(old.doc) as ReleaseAsset;if(JSON.stringify({...saved,phase:'pending'})!==JSON.stringify({...parsed,phase:'pending',key:saved.key,scope}))throw Error('Asset upload identity changed');return saved;}assertDraft();if(this.list(scope).length>=20)throw Error('Release asset capacity reached');const saved:ReleaseAsset={...parsed,phase:'pending',key:`release-assets/${encodeURIComponent(scope.projectId)}/${scope.incarnation}/${scope.id}/${parsed.id}/${parsed.sha256}`,scope};this.storage.sql.exec('INSERT INTO release_assets VALUES(?,?,?,?)',parsed.id,scope.id,parsed.name,JSON.stringify(saved));return saved;});if(asset.phase==='verified'){authorize();return asset;}
 authorize();await bucket.put(asset.key,bytes,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/octet-stream'},customMetadata:{sha256:parsed.sha256}});const stored=await bucket.get(asset.key);if(!stored)throw Error('Asset storage outcome unconfirmed');const observed=await stored.arrayBuffer(),observedHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',observed)),b=>b.toString(16).padStart(2,'0')).join('');if(observed.byteLength!==parsed.size||observedHash!==parsed.sha256)throw Error('Stored asset verification failed');return this.storage.transactionSync(()=>{authorize();assertDraft();asset.phase='verified';this.save(asset);return asset;});}
 async download(scope:ReleaseScope,id:string,bucket:R2Bucket,authorize:()=>void){z.uuid().parse(id);authorize();const asset=this.list(scope).find(item=>item.id===id&&item.phase==='verified');if(!asset)throw Error('Verified asset unavailable');const stored=await bucket.get(asset.key);if(!stored)throw Error('Asset unavailable');const bytes=await stored.arrayBuffer(),digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(bytes.byteLength!==asset.size||digest!==asset.sha256)throw Error('Asset digest verification failed');authorize();return{asset,bytes};}
 assertPublishable(scope:ReleaseScope){if(this.list(scope).some(asset=>asset.phase!=='verified'))throw Error('Release asset verification remains pending');}
}
