import {z} from 'zod';
const text=z.string().min(1).max(256),id=z.uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/);
const scopeSchema=z.object({projectId:text,incarnation:id,issuerId:text}).strict();
export type RepositoryInvitationScope=z.infer<typeof scopeSchema>;
export interface InvitationGrant {id:string;scope:RepositoryInvitationScope;tokenHash:string;role:'member';createdAt:number;expiresAt:number;status:'available'|'reserved'|'accepted'|'revoked';recipientId?:string;joinEventId?:string}
export interface InvitationJoinReceipt {invitationId:string;scope:RepositoryInvitationScope;eventId:string;userId:string;role:'owner'|'member';acceptedAt:number;projection:'pending'|'confirmed'}
export const INVITATION_AUDIT_LIMIT=10000;
/** Repository authority is checked by synchronous server callbacks. Tokens are hashed before entry.
 * Cross-account navigation is a separate projection; it never determines repository membership. */
export class RepositoryInvitations {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS repository_invitation_grants(id TEXT PRIMARY KEY,token_hash TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS repository_invitation_events(event_id TEXT PRIMARY KEY,payload TEXT NOT NULL,doc TEXT NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS repository_invitation_receipts(invitation_id TEXT PRIMARY KEY,event_id TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)');}
 private capacity(table:'repository_invitation_grants'|'repository_invitation_events'){if(this.storage.sql.exec<{n:number}>(`SELECT COUNT(*) AS n FROM ${table}`).toArray()[0]!.n>=INVITATION_AUDIT_LIMIT)throw Error('Invitation history capacity reached; saved grants remain recoverable');}
 get(invitationId:string):InvitationGrant|null{id.parse(invitationId);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM repository_invitation_grants WHERE id=?',invitationId).toArray()[0];return row?JSON.parse(row.doc) as InvitationGrant:null;}
 receipt(invitationId:string):InvitationJoinReceipt|null{id.parse(invitationId);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM repository_invitation_receipts WHERE invitation_id=?',invitationId).toArray()[0];return row?JSON.parse(row.doc) as InvitationJoinReceipt:null;}
 private save(grant:InvitationGrant){this.storage.sql.exec('INSERT INTO repository_invitation_grants VALUES(?,?,?) ON CONFLICT(id)DO UPDATE SET doc=excluded.doc',grant.id,grant.tokenHash,JSON.stringify(grant));}
 private event<T>(eventId:string,payload:string,apply:()=>T):T{id.parse(eventId);const prior=this.storage.sql.exec<{payload:string;doc:string}>('SELECT payload,doc FROM repository_invitation_events WHERE event_id=?',eventId).toArray()[0];if(prior){if(prior.payload!==payload)throw Error('Invitation event identity changed');return JSON.parse(prior.doc) as T;}this.capacity('repository_invitation_events');const result=apply();this.storage.sql.exec('INSERT INTO repository_invitation_events VALUES(?,?,?)',eventId,payload,JSON.stringify(result));return result;}
 grant(scope:RepositoryInvitationScope,input:{invitationId:string;eventId:string;tokenHash:string;expiresAt:number;role:'member'},validateIssuer:()=>void,now=Date.now()):InvitationGrant{const parsed=scopeSchema.parse(scope);id.parse(input.invitationId);hash.parse(input.tokenHash);z.literal('member').parse(input.role);if(!Number.isSafeInteger(now)||now<0)throw Error('Invalid invitation time');const payload=JSON.stringify({kind:'grant',scope:parsed,...input});return this.storage.transactionSync(()=>{validateIssuer();return this.event(input.eventId,payload,()=>{if(!Number.isSafeInteger(input.expiresAt)||input.expiresAt<=now||input.expiresAt-now>7*86400000)throw Error('Invitation expiry must be within seven days');this.capacity('repository_invitation_grants');if(this.get(input.invitationId))throw Error('Invitation identity already exists');const result:InvitationGrant={id:input.invitationId,scope:parsed,tokenHash:input.tokenHash,role:'member',createdAt:now,expiresAt:input.expiresAt,status:'available'};this.save(result);return result;});});}
 revoke(invitationId:string,scope:RepositoryInvitationScope,eventId:string,validateOwner:()=>void):InvitationGrant{const parsed=scopeSchema.parse(scope),payload=JSON.stringify({kind:'revoke',invitationId,scope:parsed});return this.storage.transactionSync(()=>{validateOwner();return this.event(eventId,payload,()=>{const grant=this.get(invitationId);if(!grant||JSON.stringify(grant.scope)!==JSON.stringify(parsed))throw Error('Exact invitation scope unavailable');if(grant.status==='accepted')throw Error('Accepted membership requires separate member removal');if(grant.status==='reserved')throw Error('Reserved join must reconcile membership before revocation');grant.status='revoked';this.save(grant);return grant;});});}
 prepareJoin(tokenHash:string,scope:RepositoryInvitationScope,userId:string,eventId:string,validateJoin:()=>void,now=Date.now()):InvitationGrant{hash.parse(tokenHash);text.parse(userId);const parsed=scopeSchema.parse(scope),payload=JSON.stringify({kind:'join',tokenHash,scope:parsed,userId});return this.storage.transactionSync(()=>{validateJoin();return this.event(eventId,payload,()=>{const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM repository_invitation_grants WHERE token_hash=?',tokenHash).toArray()[0];if(!row)throw Error('Invitation unavailable');const grant=JSON.parse(row.doc) as InvitationGrant;if(JSON.stringify(grant.scope)!==JSON.stringify(parsed)||grant.status==='revoked')throw Error('Invitation scope unavailable');if(grant.recipientId){if(grant.recipientId!==userId)throw Error('Invitation already belongs to another recipient');return grant;}if(!Number.isSafeInteger(now)||now>=grant.expiresAt)throw Error('Invitation expired');grant.recipientId=userId;grant.joinEventId=eventId;grant.status='reserved';this.save(grant);return grant;});});}
 confirmJoin(invitationId:string,scope:RepositoryInvitationScope,userId:string,eventId:string,membershipEvidence:()=> 'owner'|'member'|null,now=Date.now()):InvitationJoinReceipt{const parsed=scopeSchema.parse(scope);id.parse(eventId);text.parse(userId);if(!Number.isSafeInteger(now)||now<0)throw Error('Invalid join confirmation time');return this.storage.transactionSync(()=>{const role=membershipEvidence();if(role!=='owner'&&role!=='member')throw Error('Positive current repository membership evidence required');const grant=this.get(invitationId);if(!grant||JSON.stringify(grant.scope)!==JSON.stringify(parsed)||grant.recipientId!==userId||grant.joinEventId!==eventId||!['reserved','accepted'].includes(grant.status))throw Error('Exact reserved invitation required');const prior=this.receipt(invitationId);if(prior){if(prior.userId!==userId||prior.eventId!==eventId)throw Error('Join receipt identity changed');if(prior.role!==role)throw Error('Membership role changed; account projection requires fresh reconciliation');return prior;}const result:InvitationJoinReceipt={invitationId,scope:parsed,eventId,userId,role,acceptedAt:now,projection:'pending'};grant.status='accepted';this.save(grant);this.storage.sql.exec('INSERT INTO repository_invitation_receipts VALUES(?,?,?)',invitationId,eventId,JSON.stringify(result));return result;});}
 confirmProjection(receipt:InvitationJoinReceipt,evidence:()=>boolean):InvitationJoinReceipt{return this.storage.transactionSync(()=>{if(!evidence())throw Error('Positive exact account projection evidence required');const saved=this.receipt(receipt.invitationId);if(!saved||JSON.stringify({...saved,projection:'pending'})!==JSON.stringify({...receipt,projection:'pending'}))throw Error('Exact accepted invitation receipt required');const confirmed={...saved,projection:'confirmed' as const};this.storage.sql.exec('UPDATE repository_invitation_receipts SET doc=? WHERE invitation_id=?',JSON.stringify(confirmed),saved.invitationId);return confirmed;});}
}
