import {z} from "zod";
import {agentNativeAttemptSchema,type AgentNativeAttemptIdentity} from "./agent-runtime-ledger";
import {agentExecutionEgressScopeSchema,type AgentExecutionEgressScope} from "./agent-execution-egress";
import {validateRecoveryRemote} from "./private-recovery-bundle";
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value)),digest=z.string().regex(/^[a-f0-9]{64}$/),id=z.string().min(1).max(256);
const claimSchema=z.object({runId:id,taskId:id,workflowId:id,generation:z.number().int().nonnegative().safe(),snapshotDigest:digest,branchGeneration:z.number().int().nonnegative().safe(),forkRepoName:id,branch:id,startingBranchHead:sha.nullable()}).strict();
const observationSchema=z.object({observationId:z.uuid(),projectId:id,incarnation:z.uuid(),forkRepoName:id,ref:id,tip:sha.nullable()}).strict();
export interface RestrictedAgentBinding {attempt:AgentNativeAttemptIdentity;scope:AgentExecutionEgressScope}
export interface RestrictedAgentCurrent {
 attempt:AgentNativeAttemptIdentity;
 scope:AgentExecutionEgressScope;
 taskSnapshotDigest:string;
 runGeneration:number;
 claim:z.infer<typeof claimSchema>|null;
 remoteObservation:z.infer<typeof observationSchema>|null;
 actorState:"active"|"revoked";
 accountState:"active"|"retired";
 taskState:"active"|"terminal";
 runtimeState:"possible"|"stopped";
}
export interface RestrictedAgentAuthorityCallbacks {
 /** Worker reads real runtime/run-head/claim/task records and fresh native remote proof. */
 current(binding:RestrictedAgentBinding,proposed:AgentExecutionEgressScope):Promise<RestrictedAgentCurrent>;
 assertLocal(binding:RestrictedAgentBinding,current:RestrictedAgentCurrent):void;
 timeoutMs?:number;
}
export interface RestrictedAgentAuthorityRecord extends RestrictedAgentBinding {
 claimTransition:{fromGeneration:number;toGeneration:number;claim:z.infer<typeof claimSchema>}|null;
 writeBinding:{scope:AgentExecutionEgressScope;observation:z.infer<typeof observationSchema>}|null;
}
const shared=["projectId","incarnation","actorId","accountKey","taskId","runId","workflowId"] as const;
const staticScope=(scope:AgentExecutionEgressScope)=>{const{access:_access,expectedTip:_tip,...fixed}=scope;return fixed;};
const currentSchema=z.object({attempt:agentNativeAttemptSchema,scope:agentExecutionEgressScopeSchema,taskSnapshotDigest:digest,runGeneration:z.number().int().nonnegative().safe(),claim:claimSchema.nullable(),remoteObservation:observationSchema.nullable(),actorState:z.enum(["active","revoked"]),accountState:z.enum(["active","retired"]),taskState:z.enum(["active","terminal"]),runtimeState:z.enum(["possible","stopped"])}).strict();
/** Narrow durable authority transitions only; original runtime, funding and credential ledgers remain unchanged. */
export class RestrictedAgentAuthority {
 constructor(private readonly storage:Pick<DurableObjectStorage,"sql"|"transactionSync">,private readonly callbacks:RestrictedAgentAuthorityCallbacks){if(!callbacks?.current||!callbacks.assertLocal)throw Error("Worker-derived current authority required");if(callbacks.timeoutMs!==undefined&&(!Number.isInteger(callbacks.timeoutMs)||callbacks.timeoutMs<1||callbacks.timeoutMs>10000))throw Error("Restricted authority deadline exceeds bound");storage.sql.exec("CREATE TABLE IF NOT EXISTS restricted_agent_authority(attempt_id TEXT PRIMARY KEY,native_id TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)");}
 private binding(attempt:AgentNativeAttemptIdentity,scope:AgentExecutionEgressScope):RestrictedAgentBinding{const value={attempt:agentNativeAttemptSchema.parse(structuredClone(attempt)),scope:agentExecutionEgressScopeSchema.parse(structuredClone(scope))};validateRecoveryRemote(value.scope.remote);if(shared.some(key=>value.attempt[key]!==value.scope[key]))throw Error("Restricted runtime and task scope differ");return value;}
 private read(attemptId:string){const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM restricted_agent_authority WHERE attempt_id=?",attemptId).toArray()[0];if(!row)return null;if(new TextEncoder().encode(row.doc).length>32768)throw Error("Restricted authority record exceeds bound");return structuredClone(JSON.parse(row.doc) as RestrictedAgentAuthorityRecord);}
 private exact(saved:RestrictedAgentAuthorityRecord,binding:RestrictedAgentBinding){if(JSON.stringify(saved.attempt)!==JSON.stringify(binding.attempt)||JSON.stringify(staticScope(saved.scope))!==JSON.stringify(staticScope(binding.scope)))throw Error("Original restricted runtime identity changed");}
 private local(binding:RestrictedAgentBinding,current:RestrictedAgentCurrent){const result:unknown=this.callbacks.assertLocal(structuredClone(binding),structuredClone(current));if(result!==undefined){if(result instanceof Promise)void result.catch(()=>undefined);throw Error("Synchronous restricted authority fence required");}}
 private async fresh(binding:RestrictedAgentBinding,proposed:AgentExecutionEgressScope){let timer:ReturnType<typeof setTimeout>|undefined;try{const value=currentSchema.parse(await Promise.race([this.callbacks.current(structuredClone(binding),structuredClone(proposed)),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error("Restricted authority deadline exceeded")),this.callbacks.timeoutMs??10000);})]));if(value.actorState!=="active"||value.accountState!=="active"||value.taskState!=="active"||value.runtimeState!=="possible"||JSON.stringify(value.attempt)!==JSON.stringify(binding.attempt)||value.taskSnapshotDigest!==binding.attempt.snapshotDigest||JSON.stringify(staticScope(value.scope))!==JSON.stringify(staticScope(binding.scope)))throw Error("Restricted actor, source, task or runtime authority changed");this.local(binding,value);return value;}finally{clearTimeout(timer);}}
 private save(value:RestrictedAgentAuthorityRecord){const doc=JSON.stringify(value);if(new TextEncoder().encode(doc).length>32768)throw Error("Restricted authority record exceeds bound");this.storage.sql.exec("INSERT INTO restricted_agent_authority VALUES(?,?,?) ON CONFLICT(attempt_id) DO UPDATE SET doc=excluded.doc",value.attempt.attemptId,value.attempt.nativeId,doc);}
 async bind(attempt:AgentNativeAttemptIdentity,scope:AgentExecutionEgressScope){const binding=this.binding(attempt,scope);if(scope.access!=="read")throw Error("Initial restricted binding must be readonly");const prior=this.read(attempt.attemptId);if(prior){this.exact(prior,binding);if(JSON.stringify(prior.scope)!==JSON.stringify(binding.scope))throw Error("Original readonly binding changed");return this.authorize(binding.attempt,binding.scope);}const current=await this.fresh(binding,binding.scope);if(current.runGeneration!==attempt.generation||current.scope.access!=="read"||current.scope.expectedTip!==binding.scope.expectedTip)throw Error("Initial runtime generation or readonly tip differs");return this.storage.transactionSync(()=>{this.local(binding,current);const saved=this.read(attempt.attemptId);if(saved){this.exact(saved,binding);if(JSON.stringify(saved.scope)!==JSON.stringify(binding.scope))throw Error("Original readonly binding changed");return saved;}if(this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM restricted_agent_authority").toArray()[0]!.n>=10000)throw Error("Restricted authority audit capacity reached");const record:RestrictedAgentAuthorityRecord={...binding,claimTransition:null,writeBinding:null};this.save(record);return structuredClone(record);});}
 async authorize(attempt:AgentNativeAttemptIdentity,proposedScope:AgentExecutionEgressScope,purpose:"transfer"|"identity"="transfer"){if(purpose!=="transfer"&&purpose!=="identity")throw Error("Unknown restricted authority purpose");const proposed=this.binding(attempt,proposedScope),saved=this.read(attempt.attemptId);if(!saved)throw Error("Original restricted runtime must be bound first");this.exact(saved,proposed);const binding={attempt:saved.attempt,scope:saved.scope},current=await this.fresh(binding,proposed.scope),generation=current.runGeneration;
 if(generation!==attempt.generation&&generation!==attempt.generation+1)throw Error("Unrecorded agent generation cannot use original runtime");if(current.claim&&current.claim.runId!==attempt.runId)throw Error("Another run cannot borrow the restricted runtime");let transition=saved.claimTransition;
 if(generation===attempt.generation+1){const claim=current.claim;if(!claim||claim.runId!==attempt.runId||claim.taskId!==attempt.taskId||claim.workflowId!==attempt.workflowId||claim.generation!==generation||claim.snapshotDigest!==attempt.snapshotDigest||claim.branchGeneration!==saved.scope.branchGeneration||claim.forkRepoName!==saved.scope.forkRepoName||claim.branch!==saved.scope.branch)throw Error("A recorded same-run claim is required for the generation transition");const next={fromGeneration:attempt.generation,toGeneration:generation,claim};if(transition&&JSON.stringify(transition)!==JSON.stringify(next))throw Error("Original claim transition changed");transition=next;}else if(transition)throw Error("Recorded agent generation cannot regress");
 let write=saved.writeBinding;if(proposed.scope.access==="read"){if(proposed.scope.expectedTip!==saved.scope.expectedTip)throw Error("Original readonly tip changed");}else{if(attempt.phase!=="apply"||!current.claim||current.claim.runId!==attempt.runId||current.claim.taskId!==attempt.taskId||current.claim.workflowId!==attempt.workflowId||current.claim.snapshotDigest!==attempt.snapshotDigest||current.claim.branchGeneration!==saved.scope.branchGeneration||current.claim.forkRepoName!==saved.scope.forkRepoName||current.claim.branch!==saved.scope.branch||current.claim.generation!==generation||current.claim.startingBranchHead!==proposed.scope.expectedTip)throw Error("Original recorded claim does not authorize this write tip");if(write&&JSON.stringify(write.scope)!==JSON.stringify(proposed.scope))throw Error("Original write binding changed");if(purpose==="identity"){if(!write)throw Error("Identity checks cannot create write authority");}else{const observation=current.remoteObservation;if(!observation||observation.projectId!==attempt.projectId||observation.incarnation!==attempt.incarnation||observation.forkRepoName!==saved.scope.forkRepoName||observation.ref!==`refs/heads/${saved.scope.branch}`||observation.tip!==proposed.scope.expectedTip)throw Error("Fresh Worker native branch observation differs from the write lease");write??={scope:proposed.scope,observation};}}
 return this.storage.transactionSync(()=>{this.local(binding,current);const latest=this.read(attempt.attemptId);if(!latest||JSON.stringify(latest)!==JSON.stringify(saved))throw Error("Restricted authority changed while awaiting current records");const record={...latest,claimTransition:transition,writeBinding:write};this.save(record);return structuredClone(record);});}
 /** Private ownership lookup; the stored observation is historical and grants no new transfer. */
 originalOwnership(attempt:AgentNativeAttemptIdentity){const parsed=agentNativeAttemptSchema.parse(structuredClone(attempt)),saved=this.read(parsed.attemptId);if(saved&&JSON.stringify(saved.attempt)!==JSON.stringify(parsed))throw Error("Original restricted runtime identity changed");return saved;}
 /** Exact original ownership only, for revocation/stop after authority withdrawal; never grants transfer authority. */
 cleanup(attempt:AgentNativeAttemptIdentity,scope:AgentExecutionEgressScope){const binding=this.binding(attempt,scope),saved=this.read(attempt.attemptId);if(!saved)throw Error("Original cleanup ownership missing");this.exact(saved,binding);if(JSON.stringify(binding.scope)!==JSON.stringify(saved.scope)&&JSON.stringify(binding.scope)!==JSON.stringify(saved.writeBinding?.scope))throw Error("Cleanup scope differs from the original owned runtime");return saved;}
}
