import {z} from 'zod';
import {retainedInputSchema,type RetainedInput} from './retained-inputs';
import type {CoreGitExistingReservationProof} from './core-git-budget';
const purposeSchema=z.enum(['workspace','canonical']);
const recordSchema=z.object({inputId:z.uuid(),purpose:purposeSchema,accountKey:z.string(),repoName:z.string(),inputPayload:z.string(),scope:z.enum(['read','write']),intentExpiresAt:z.number().int().positive().safe(),month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),operationId:z.string(),confirmed:z.boolean()}).strict().refine(value=>value.operationId===`retained-close-${value.inputId}-${value.purpose}-${value.month}`);
export type RetainedCleanupPrepayment=z.infer<typeof recordSchema>;
export interface RetainedCleanupContext{payload:string;scope:'read'|'write';repoName:string;accountKey:string;intentExpiresAt:number}
/** One immutable cleanup envelope per credential acquisition slot. Secrets are
 * stored only in the existing credential incident ledger, never this record. */
export class RetainedCleanupPrepayments{
 constructor(private readonly storage:Pick<DurableObjectStorage,'sql'|'transactionSync'>){storage.sql.exec('CREATE TABLE IF NOT EXISTS retained_cleanup_prepayments(input_id TEXT NOT NULL,purpose TEXT NOT NULL,doc TEXT NOT NULL,PRIMARY KEY(input_id,purpose))');}
 get(inputId:string,purpose:'workspace'|'canonical'){z.uuid().parse(inputId);purposeSchema.parse(purpose);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM retained_cleanup_prepayments WHERE input_id=? AND purpose=?',inputId,purpose).toArray()[0];return row?recordSchema.parse(JSON.parse(row.doc)):null;}
 prepare(input:RetainedInput,purpose:'workspace'|'canonical',expiresAt:number,scope:'read'|'write',assertCurrent:()=>void,now=Date.now()){
  const value=retainedInputSchema.parse(input);z.uuid().parse(value.id);purposeSchema.parse(purpose);if(!Number.isSafeInteger(now)||!Number.isSafeInteger(expiresAt)||expiresAt<=now||expiresAt>now+900000||value.protectedRef!==`refs/flaregit/inputs/${value.incarnation}/${value.taskId}/${value.commit}`||(value.base===null?value.protectedBaseRef!==null:value.protectedBaseRef!==`refs/flaregit/inputs/${value.incarnation}/${value.taskId}/${value.base}`)||value.followup&&(purpose!=='canonical'||scope!=='read'))throw Error('Exact retained credential prepayment scope required');
  const month=new Date(now).toISOString().slice(0,7),record=recordSchema.parse({inputId:value.id,purpose,accountKey:value.accountKey,repoName:purpose==='workspace'?value.workspaceRepoName:value.canonicalRepoName,inputPayload:JSON.stringify(value),scope,intentExpiresAt:expiresAt,month,operationId:`retained-close-${value.id}-${purpose}-${month}`,confirmed:false});
  return this.storage.transactionSync(()=>{assertCurrent();const old=this.get(value.id,purpose);if(old){if(old.month!==month||JSON.stringify({...old,confirmed:false})!==JSON.stringify(record))throw Error('Original credential acquisition prepayment changed');return old;}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM retained_cleanup_prepayments').toArray()[0]!.n>=1000)throw Error('Retained cleanup audit capacity reached');this.storage.sql.exec('INSERT INTO retained_cleanup_prepayments VALUES(?,?,?)',value.id,purpose,JSON.stringify(record));return record;});
 }
 matches(record:RetainedCleanupPrepayment,proof:CoreGitExistingReservationProof|null,context?:RetainedCleanupContext,now=Date.now()){return Number.isSafeInteger(now)&&record.month===new Date(now).toISOString().slice(0,7)&&!!proof&&proof.operationId===record.operationId&&proof.accountKey===record.accountKey&&proof.month===record.month&&proof.category==='core'&&proof.reservedUsdMicros===1200&&proof.maxProviderOperations===8&&proof.basis==='conservative_operation_envelope'&&(!context||context.payload===record.inputPayload&&context.scope===record.scope&&context.repoName===record.repoName&&context.accountKey===record.accountKey&&context.intentExpiresAt===record.intentExpiresAt);}
 confirm(record:RetainedCleanupPrepayment,proof:CoreGitExistingReservationProof|null,assertCurrent:()=>void,now=Date.now()){if(!this.matches(record,proof,undefined,now))throw Error('Original reserved cleanup capacity unavailable');return this.storage.transactionSync(()=>{assertCurrent();const old=this.get(record.inputId,record.purpose);if(!old||JSON.stringify({...old,confirmed:false})!==JSON.stringify({...record,confirmed:false}))throw Error('Original cleanup prepayment changed');const next={...old,confirmed:true};this.storage.sql.exec('UPDATE retained_cleanup_prepayments SET doc=? WHERE input_id=? AND purpose=?',JSON.stringify(next),next.inputId,next.purpose);return next;});}
}
