import {z} from 'zod';
import type {Visibility} from '../core/snippets';
export const snippetWriteSchema=z.object({requestId:z.uuid(),expectedRevision:z.number().int().min(0).safe(),title:z.string().trim().min(1).max(120),visibility:z.enum(['private','public','secret']),content:z.string().max(100_000)}).strict();
export type SnippetWrite=z.infer<typeof snippetWriteSchema>;
export type StoredSnippet={id:string;ownerId:string;title:string;visibility:Visibility;revision:number;content:string;updatedAt:string};
export class SnippetError extends Error{constructor(message:string,readonly status:number){super(message);}}
/** Account-scoped append-only history; visibility is always checked against the current head. */
export class DurableSnippets{
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS snippet_revisions(id TEXT NOT NULL,revision INTEGER NOT NULL,owner_id TEXT NOT NULL,title TEXT NOT NULL,visibility TEXT NOT NULL,content TEXT NOT NULL,updated_at TEXT NOT NULL,request_id TEXT NOT NULL UNIQUE,PRIMARY KEY(id,revision))');}
 private rows(id:string){return this.storage.sql.exec<StoredSnippet>('SELECT id,owner_id AS ownerId,title,visibility,revision,content,updated_at AS updatedAt FROM snippet_revisions WHERE id=? ORDER BY revision DESC',id).toArray();}
 list(viewer:string|undefined){return this.storage.sql.exec<StoredSnippet>('SELECT id,owner_id AS ownerId,title,visibility,revision,content,updated_at AS updatedAt FROM snippet_revisions s WHERE revision=(SELECT MAX(revision) FROM snippet_revisions WHERE id=s.id) AND (visibility=\'public\' OR owner_id=?) ORDER BY updated_at DESC LIMIT 100',viewer??'').toArray().map(({content:_,...item})=>item);}
 read(id:string,viewer:string|undefined,revision?:number){const rows=this.rows(id),head=rows[0];if(!head||head.visibility==='private'&&head.ownerId!==viewer)throw new SnippetError('Snippet not found',404);const found=revision===undefined?head:rows.find(row=>row.revision===revision);if(!found||found.visibility==='private'&&found.ownerId!==viewer)throw new SnippetError('Snippet revision not found',404);return {snippet:found,headRevision:head.revision,currentVisibility:head.visibility,revisions:rows.filter(row=>row.visibility!=='private'||row.ownerId===viewer).map(row=>({revision:row.revision,updatedAt:row.updatedAt}))};}
 save(id:string,ownerId:string,input:SnippetWrite){return this.storage.transactionSync(()=>{const parsed=snippetWriteSchema.parse(input),head=this.rows(id)[0];if(head&&head.ownerId!==ownerId)throw new SnippetError('Snippet not found',404);const retry=this.storage.sql.exec<StoredSnippet&{requestId:string}>('SELECT id,owner_id AS ownerId,title,visibility,revision,content,updated_at AS updatedAt,request_id AS requestId FROM snippet_revisions WHERE request_id=?',parsed.requestId).toArray()[0];if(retry){if(retry.id!==id||retry.ownerId!==ownerId||retry.title!==parsed.title||retry.visibility!==parsed.visibility||retry.content!==parsed.content||retry.revision!==parsed.expectedRevision+1)throw new SnippetError('Request identity already used',409);return retry;}if((head?.revision??0)!==parsed.expectedRevision)throw new SnippetError('Snippet changed; reload before saving',409);const usage=this.storage.sql.exec<{bytes:number;count:number}>('SELECT COALESCE(SUM(length(CAST(content AS BLOB))),0) AS bytes,COUNT(*) AS count FROM snippet_revisions').toArray()[0]!;if(usage.count>=10000||usage.bytes+new TextEncoder().encode(parsed.content).length>5_000_000)throw new SnippetError('Snippet capacity reached',409);const result:StoredSnippet={id,ownerId,title:parsed.title,visibility:parsed.visibility,content:parsed.content,revision:parsed.expectedRevision+1,updatedAt:new Date().toISOString()};this.storage.sql.exec('INSERT INTO snippet_revisions VALUES(?,?,?,?,?,?,?,?)',id,result.revision,ownerId,result.title,result.visibility,result.content,result.updatedAt,parsed.requestId);return result;});}
}
