import {z} from "zod";
import {acceptedTargetSchema} from "../core/accepted-target";
import {taskCreationInputSchema} from "./task-creation";
const id=z.string().min(1).max(200).regex(/^[A-Za-z0-9_-]+$/),sha=z.string().regex(/^[a-f0-9]{40}$/);
export const taskCreationIntentSchema=z.object({eventId:z.uuid(),nativeProtocol:z.literal("sdk-only"),taskId:z.string().regex(/^[a-z0-9][a-z0-9-]{2,100}$/),allocationId:z.uuid(),actor:z.object({userId:z.string().min(1).max(256),viaToken:z.boolean(),credentialHash:z.string().regex(/^[a-f0-9]{64}$/).nullable(),sessionExpiresAt:z.number().int().positive().safe().nullable()}).strict(),accountKey:z.string().regex(/^[a-f0-9]{12}$/),projectId:z.string().regex(/^[a-z0-9]{12,16}$/),incarnation:z.uuid(),canonicalRepoName:id,workspaceRepoName:id,input:taskCreationInputSchema,selection:z.object({acceptedTarget:acceptedTargetSchema.nullable(),baseCommit:sha,sourceRepoName:id,scope:z.string().min(1).max(200000)}).strict()}).strict().refine(value=>value.workspaceRepoName===`t-${value.projectId}-${value.taskId}`&&value.actor.viaToken===(value.actor.credentialHash!==null)&&(value.actor.viaToken||value.actor.sessionExpiresAt!==null)&&(!value.selection.acceptedTarget||(value.selection.acceptedTarget.projectId===value.projectId&&value.selection.acceptedTarget.incarnation===value.incarnation&&value.selection.acceptedTarget.canonicalRepoName===value.canonicalRepoName)),"Creation scope disagrees");
export type TaskCreationIntent=z.infer<typeof taskCreationIntentSchema>;
export type TaskCreationIntentPhase="prepared"|"dispatching"|"fork_unknown"|"fork_confirmed"|"committed";
export interface TaskCreationIntentRecord extends TaskCreationIntent {phase:TaskCreationIntentPhase;createdAt:number;updatedAt:number;providerRepoId?:string}
export interface TaskForkCompletionProof {allocationId:string;workspaceRepoName:string;sourceRepoName:string;sourceCommit:string;providerRepoId:string;nativeState:"not_allocated"|"stopped";credentialsComplete:true}
/** No provider calls or secrets. Validate callbacks must inspect authoritative
 * actor/selection and exclusive allocation provenance, not a matching name alone. */
export class TaskCreationIntents {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec("CREATE TABLE IF NOT EXISTS task_creation_intents(event_id TEXT PRIMARY KEY,task_id TEXT NOT NULL UNIQUE,payload TEXT NOT NULL,doc TEXT NOT NULL)");}
 get(eventId:string):TaskCreationIntentRecord|null{z.uuid().parse(eventId);const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM task_creation_intents WHERE event_id=?",eventId).toArray()[0];return row?JSON.parse(row.doc) as TaskCreationIntentRecord:null;}
 forTask(taskId:string):TaskCreationIntentRecord|null{const row=this.storage.sql.exec<{doc:string}>("SELECT doc FROM task_creation_intents WHERE task_id=?",taskId).toArray()[0];return row?JSON.parse(row.doc) as TaskCreationIntentRecord:null;}
 prepare(raw:TaskCreationIntent,validate:()=>void,now=Date.now()):TaskCreationIntentRecord{
 const input=taskCreationIntentSchema.parse(raw),payload=JSON.stringify(input);if(new TextEncoder().encode(payload).length>256000||!Number.isSafeInteger(now)||now<0)throw Error("Creation intent exceeds supported bounds");
 return this.storage.transactionSync(()=>{validate();const old=this.get(input.eventId)??this.forTask(input.taskId);if(old){if(JSON.stringify((({phase:_phase,createdAt:_createdAt,updatedAt:_updatedAt,providerRepoId:_providerRepoId,...intent})=>intent)(old))!==payload)throw Error("Creation intent changed; preserve the original request");return old;}if(this.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM task_creation_intents").toArray()[0]!.n>=1000)throw Error("Creation audit capacity reached; saved requests remain available");const record:TaskCreationIntentRecord={...input,phase:"prepared",createdAt:now,updatedAt:now};this.storage.sql.exec("INSERT INTO task_creation_intents VALUES(?,?,?,?)",input.eventId,input.taskId,payload,JSON.stringify(record));return record;});
 }
 beginFork(eventId:string,validate:(record:TaskCreationIntentRecord)=>void):TaskCreationIntentRecord{return this.storage.transactionSync(()=>{const record=this.required(eventId);validate(record);if(record.phase!=="prepared")throw Error("Fork dispatch was already recorded; inspect the original allocation");record.phase="dispatching";return this.save(record);});}
 markForkUnknown(eventId:string):TaskCreationIntentRecord{return this.storage.transactionSync(()=>{const record=this.required(eventId);if(record.phase==="dispatching"){record.phase="fork_unknown";return this.save(record);}return record;});}
 confirmFork(eventId:string,proof:TaskForkCompletionProof,validate:(record:TaskCreationIntentRecord,proof:TaskForkCompletionProof)=>void):TaskCreationIntentRecord{return this.storage.transactionSync(()=>{const record=this.required(eventId);if(!["dispatching","fork_unknown","fork_confirmed","committed"].includes(record.phase)||proof.allocationId!==record.allocationId||proof.workspaceRepoName!==record.workspaceRepoName||proof.sourceRepoName!==record.selection.sourceRepoName||proof.sourceCommit!==record.selection.baseCommit||!id.safeParse(proof.providerRepoId).success||proof.nativeState!=="not_allocated"||proof.credentialsComplete!==true||record.providerRepoId&&record.providerRepoId!==proof.providerRepoId)throw Error("Fork completion does not prove the original allocation");validate(record,proof);if(record.phase==="committed")return record;record.providerRepoId=proof.providerRepoId;record.phase="fork_confirmed";return this.save(record);});}
 commit(eventId:string,validate:(record:TaskCreationIntentRecord)=>void,saveTask:(record:TaskCreationIntentRecord)=>void):TaskCreationIntentRecord{return this.storage.transactionSync(()=>{const record=this.required(eventId);if(record.phase!=="fork_confirmed"&&record.phase!=="committed")throw Error("Fork completion remains unconfirmed");validate(record);if(record.phase==="committed")return record;saveTask(record);record.phase="committed";return this.save(record);});}
 private required(eventId:string){const record=this.get(eventId);if(!record)throw Error("Saved creation intent unavailable");return record;}
 private save(record:TaskCreationIntentRecord){const stored=this.storage.sql.exec<{payload:string}>("SELECT payload FROM task_creation_intents WHERE event_id=?",record.eventId).toArray()[0];const {phase:_phase,createdAt:_createdAt,updatedAt:_updatedAt,providerRepoId:_providerRepoId,...intent}=record;if(!stored||stored.payload!==JSON.stringify(taskCreationIntentSchema.parse(intent)))throw Error("Immutable creation intent changed");record.updatedAt=Date.now();this.storage.sql.exec("UPDATE task_creation_intents SET doc=? WHERE event_id=?",JSON.stringify(record),record.eventId);return record;}
}
