import {z} from 'zod';
import {isSafeRef} from '../core/sanitize';
import {taskTargetGenerationIntentSchema,type TaskTargetGenerationIntent} from './task-target-generations';
import type {ForkPermissionSource} from './fork-permissions';
const sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value));
export const taskRetargetRequestSchema=z.object({requestId:z.uuid(),expectedGeneration:z.number().int().nonnegative().safe(),expectedHead:sha,target:z.object({ref:z.string().max(500).refine(value=>value.startsWith('refs/heads/')&&isSafeRef(value)),acceptedCommit:sha,acceptedVersion:z.number().int().nonnegative().safe(),policyVersion:z.number().int().nonnegative().safe()}).strict()}).strict();
export type TaskRetargetRequest=z.infer<typeof taskRetargetRequestSchema>;
export interface TaskRetargetIdentity {requestId:string;intent:TaskTargetGenerationIntent;providerRepoId:string;remote:string;maintainerWriteSource?:ForkPermissionSource}
export interface TaskRetargetRecord extends TaskRetargetIdentity {phase:'prepared'|'requires_rebase'|'verified'|'activated';reason?:'target_object_unavailable'|'target_not_ancestor'|'inspection_unconfirmed';proof?:{head:string;base:string;ancestryVerified:true};createdAt:number}
/** An immutable target change request never claims a fork rewrite or fresh review. */
export class TaskRetargets {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS task_retarget_locks(task_id TEXT PRIMARY KEY,request_id TEXT NOT NULL,execution_id TEXT,native_attempt_id TEXT,credential_state TEXT)');const columns=new Set(storage.sql.exec<{name:string}>('PRAGMA table_info(task_retarget_locks)').toArray().map(column=>column.name));if(!columns.has('execution_id'))storage.sql.exec('ALTER TABLE task_retarget_locks ADD COLUMN execution_id TEXT');if(!columns.has('native_attempt_id'))storage.sql.exec('ALTER TABLE task_retarget_locks ADD COLUMN native_attempt_id TEXT');if(!columns.has('credential_state'))storage.sql.exec('ALTER TABLE task_retarget_locks ADD COLUMN credential_state TEXT');storage.sql.exec('CREATE TABLE IF NOT EXISTS task_retarget_requests(request_id TEXT PRIMARY KEY,task_id TEXT NOT NULL,payload TEXT NOT NULL,doc TEXT NOT NULL)');}
 lockState(taskId:string){return this.storage.sql.exec<{request_id:string;execution_id:string|null;native_attempt_id:string|null;credential_state:string|null}>('SELECT request_id,execution_id,native_attempt_id,credential_state FROM task_retarget_locks WHERE task_id=?',taskId).toArray()[0]??null;}
 lock(taskId:string,requestId:string):string{return this.storage.transactionSync(()=>{if(this.lockState(taskId))throw Error('Original retarget inspection is active; recover its exact execution before retrying');const executionId=crypto.randomUUID();this.storage.sql.exec('INSERT INTO task_retarget_locks(task_id,request_id,execution_id,native_attempt_id) VALUES(?,?,?,NULL)',taskId,requestId,executionId);return executionId;});}
 bindNative(taskId:string,requestId:string,executionId:string,attemptId:string){z.uuid().parse(attemptId);const lock=this.lockState(taskId);if(!lock||lock.request_id!==requestId||lock.execution_id!==executionId||lock.native_attempt_id&&lock.native_attempt_id!==attemptId)throw Error('Original retarget execution ownership changed');this.storage.sql.exec('UPDATE task_retarget_locks SET native_attempt_id=? WHERE task_id=? AND request_id=? AND execution_id=?',attemptId,taskId,requestId,executionId);}
 finished(taskId:string,requestId:string,executionId:string,attemptId:string,credentialState:'not_issued'|'revoked'|'unconfirmed'){const lock=this.lockState(taskId);if(!lock||lock.request_id!==requestId||lock.execution_id!==executionId||lock.native_attempt_id!==attemptId)throw Error('Original retarget completion ownership changed');this.storage.sql.exec('UPDATE task_retarget_locks SET credential_state=? WHERE task_id=? AND request_id=? AND execution_id=?',credentialState,taskId,requestId,executionId);}
 unlock(taskId:string,requestId:string,executionId:string){this.storage.sql.exec('DELETE FROM task_retarget_locks WHERE task_id=? AND request_id=? AND execution_id=?',taskId,requestId,executionId);}
 get(requestId:string):TaskRetargetRecord|null {z.uuid().parse(requestId);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM task_retarget_requests WHERE request_id=?',requestId).toArray()[0];return row?JSON.parse(row.doc) as TaskRetargetRecord:null;}
 prepare(identity:TaskRetargetIdentity,authorize:()=>void){taskTargetGenerationIntentSchema.parse(identity.intent);if(identity.intent.change.kind!=='retarget'||identity.intent.change.receiptId!==identity.requestId||identity.intent.eventId!==identity.requestId)throw Error('Exact retarget intent required');return this.storage.transactionSync(()=>{authorize();const payload=JSON.stringify(identity),old=this.get(identity.requestId);if(old){const {phase:_phase,reason:_reason,proof:_proof,createdAt:_at,...saved}=old;if(JSON.stringify(saved)!==payload)throw Error('Original retarget inputs changed');return old;}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM task_retarget_requests').toArray()[0]!.n>=10000)throw Error('Retarget audit capacity reached');const record:TaskRetargetRecord={...identity,phase:'prepared',createdAt:Date.now()};this.storage.sql.exec('INSERT INTO task_retarget_requests VALUES(?,?,?,?)',identity.requestId,identity.intent.source.taskId,payload,JSON.stringify(record));return record;});}
 record(requestId:string,result:{head:string;base:string;ancestryVerified:true}|'target_object_unavailable'|'target_not_ancestor',authorize:()=>void){return this.storage.transactionSync(()=>{authorize();const record=this.get(requestId);if(!record)throw Error('Saved retarget unavailable');if(record.phase==='activated')return record;if(typeof result==='string'){record.phase='requires_rebase';record.reason=result;}else{if(result.head!==record.intent.source.currentCommit||result.base!==record.intent.target.acceptedCommit||result.ancestryVerified!==true)throw Error('Retarget native proof differs');record.phase='verified';record.proof=result;delete record.reason;}this.storage.sql.exec('UPDATE task_retarget_requests SET doc=? WHERE request_id=?',JSON.stringify(record),requestId);return record;});}
 activated(requestId:string,authorize:()=>void){const record=this.get(requestId);if(!record?.proof||record.phase!=='verified')throw Error('Verified retarget proof required');authorize();record.phase='activated';this.storage.sql.exec('UPDATE task_retarget_requests SET doc=? WHERE request_id=?',JSON.stringify(record),requestId);return record;}
 list(taskId:string){return this.storage.sql.exec<{doc:string}>('SELECT r.doc FROM task_retarget_requests r LEFT JOIN task_retarget_locks l ON l.task_id=r.task_id AND l.request_id=r.request_id WHERE r.task_id=? ORDER BY (l.request_id IS NOT NULL) DESC,r.rowid DESC LIMIT 21',taskId).toArray().map(row=>JSON.parse(row.doc) as TaskRetargetRecord);}
}
