import {z} from 'zod';
import {bindBrowserPolicy,type BrowserPolicy} from './external-browser-verifier';
const name=z.string().min(1).max(200).regex(/^[A-Za-z0-9_-]+$/),sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value)),digest=z.string().regex(/^[a-f0-9]{64}$/);
export const browserFailureIdentitySchema=z.object({projectId:name,incarnation:z.uuid(),candidateId:name,attemptId:z.uuid(),commit:sha,tree:sha,sourceDigest:digest,buildDigest:digest,policyDigest:digest}).strict();
export type BrowserFailureIdentity=z.infer<typeof browserFailureIdentitySchema>;
export interface TrustedBrowserFailureReceipt {id:string;kind:'trusted-browser-failure';identity:BrowserFailureIdentity;caseId:string;recordedAt:number;cleanup:'confirmed'|'unknown'}
export interface TrustedBrowserFailureBinding {identity:BrowserFailureIdentity;adapter:'ticket-booking'|'shipping-calculator';policy:BrowserPolicy}
export interface BrowserFailureFence {assertCurrent():void;readTrustedBinding():Promise<TrustedBrowserFailureBinding>}
export interface BrowserCleanupFence {assertCurrent():void;readTrustedCleanup():Promise<{identity:BrowserFailureIdentity;cleanup:'confirmed'|'unknown'}>}
const failureSchema=z.object({caseId:name}).strict();
const equal=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
async function bounded<T>(read:()=>Promise<T>):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([read(),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Trusted browser fact read timed out')),5000);})]);}finally{if(timer!==undefined)clearTimeout(timer);}}
/** Safe failure facts only. No DOM/text/stdout/expectation values, source data,
 * successful-verification claims, model authority or publication side effects. */
export class TrustedBrowserFailures {
 constructor(private readonly storage:DurableObjectStorage){storage.sql.exec('CREATE TABLE IF NOT EXISTS trusted_browser_failure_receipts(id TEXT PRIMARY KEY,attempt_id TEXT UNIQUE NOT NULL,doc TEXT NOT NULL)');storage.sql.exec('CREATE TABLE IF NOT EXISTS trusted_browser_failure_cleanup(id TEXT PRIMARY KEY,failure_id TEXT NOT NULL,doc TEXT NOT NULL)');}
 private get(id:string):TrustedBrowserFailureReceipt|null{z.uuid().parse(id);const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM trusted_browser_failure_receipts WHERE id=?',id).toArray()[0];return row?JSON.parse(row.doc) as TrustedBrowserFailureReceipt:null;}
 private async binding(identity:BrowserFailureIdentity,fence:BrowserFailureFence){fence.assertCurrent();const first=await bounded(()=>fence.readTrustedBinding());fence.assertCurrent();if(!['ticket-booking','shipping-calculator'].includes(first.adapter)||!equal(browserFailureIdentitySchema.parse(first.identity),identity))throw Error('Trusted browser failure scope is stale or unsupported');const bound=await bindBrowserPolicy(first.policy);fence.assertCurrent();if(bound.digest!==identity.policyDigest)throw Error('Trusted browser policy differs from failure scope');const second=await bounded(()=>fence.readTrustedBinding());fence.assertCurrent();if(!equal(second,first))throw Error('Trusted browser binding changed during failure read');return bound.policy;}
 /** The returned callback is passed directly to the trusted verifier's
  * onExpectedFailure hook. Transport crashes never call it. */
 async openExpectedFailureRecorder(id:string,proposed:BrowserFailureIdentity,fence:BrowserFailureFence){z.uuid().parse(id);const identity=browserFailureIdentitySchema.parse(proposed);await this.binding(identity,fence);let called=false;return{onExpectedFailure:async(payload:{caseId:string})=>{const failure=failureSchema.parse(payload);if(called)throw Error('Expected browser failure callback replayed');const policy=await this.binding(identity,fence);if(!policy.cases.some(testCase=>testCase.id===failure.caseId))throw Error('Failure case is not in the trusted policy inventory');this.storage.transactionSync(()=>{fence.assertCurrent();if(this.get(id)||this.storage.sql.exec('SELECT id FROM trusted_browser_failure_receipts WHERE attempt_id=?',identity.attemptId).toArray().length)throw Error('Original browser failure attempt already recorded');if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM trusted_browser_failure_receipts').toArray()[0]!.n>=10000)throw Error('Browser failure audit capacity reached');const receipt:TrustedBrowserFailureReceipt={id,kind:'trusted-browser-failure',identity,caseId:failure.caseId,recordedAt:Date.now(),cleanup:'unknown'};this.storage.sql.exec('INSERT INTO trusted_browser_failure_receipts VALUES(?,?,?)',id,identity.attemptId,JSON.stringify(receipt));});called=true;}};}
 /** Cleanup is a separate trusted resource receipt. It may settle the original
  * attempt after the active candidate changed, but never grants repair access. */
 async recordCleanup(id:string,eventId:string,fence:BrowserCleanupFence):Promise<TrustedBrowserFailureReceipt>{z.uuid().parse(eventId);const receipt=this.get(id);if(!receipt)throw Error('Original browser failure unavailable');fence.assertCurrent();const observed=await bounded(()=>fence.readTrustedCleanup());fence.assertCurrent();if(!equal(browserFailureIdentitySchema.parse(observed.identity),receipt.identity)||!['confirmed','unknown'].includes(observed.cleanup))throw Error('Cleanup belongs to another browser attempt');return this.storage.transactionSync(()=>{fence.assertCurrent();const prior=this.storage.sql.exec<{doc:string}>('SELECT doc FROM trusted_browser_failure_cleanup WHERE id=?',eventId).toArray()[0],event={failureId:id,identity:receipt.identity,cleanup:observed.cleanup};if(prior){if(!equal(JSON.parse(prior.doc),event))throw Error('Cleanup event identity changed');return this.get(id)!;}if(this.storage.sql.exec<{n:number}>('SELECT COUNT(*) AS n FROM trusted_browser_failure_cleanup').toArray()[0]!.n>=10000)throw Error('Browser cleanup audit capacity reached');const current=this.get(id)!;if(current.cleanup!=='confirmed')current.cleanup=observed.cleanup;this.storage.sql.exec('INSERT INTO trusted_browser_failure_cleanup VALUES(?,?,?)',eventId,id,JSON.stringify(event));this.storage.sql.exec('UPDATE trusted_browser_failure_receipts SET doc=? WHERE id=?',JSON.stringify(current),id);return current;});}
 async readForRepair(id:string,proposed:BrowserFailureIdentity,fence:BrowserFailureFence):Promise<TrustedBrowserFailureReceipt>{const identity=browserFailureIdentitySchema.parse(proposed),receipt=this.get(id);if(!receipt||!equal(receipt.identity,identity))throw Error('Exact browser failure receipt unavailable');const policy=await this.binding(identity,fence);if(receipt.cleanup!=='confirmed'||!policy.cases.some(testCase=>testCase.id===receipt.caseId))throw Error('Known trusted failure and confirmed browser cleanup required before repair');fence.assertCurrent();const current=this.get(id);if(!current||!equal(current,receipt))throw Error('Browser failure receipt changed before repair');return receipt;}
}
