import {z} from "zod";
import type {BrowserPolicy,BrowserAction} from "./external-browser-verifier";
/** Platform-owned inventory: callers bind an already approved policy. Candidate
 * files, stdout and model judgments must never supply these actions or expectations. */
export interface FixtureBrowserInventory{fixture:"ticket-booking"|"shipping-calculator";policy:BrowserPolicy;coveredRequirements:string[];partialCoverage:Array<{requirementId:string;coveredObservation:string}>;unsupportedCoverage:Array<{requirementId:string;reason:string;requiredObservation:string}>;complete:boolean;scope:"browser-visible-behavior"}
const ticketPolicySchema=z.object({groupDiscountPercent:z.number().min(0).max(1).optional(),minTicketsForDiscount:z.number().int().min(2).max(16).optional(),refundFeePerTicket:z.number().min(0).max(10000).optional(),discountAppliesToRefundFee:z.boolean().optional()}).strict();
export type ApprovedTicketBrowserPolicy=z.infer<typeof ticketPolicySchema>;
const text=(selector:string,expected:string)=>({query:{kind:"text" as const,selector},expected});
const count=(selector:string,expected:number)=>({query:{kind:"count" as const,selector},expected});
const value=(selector:string,expected:string)=>({query:{kind:"value" as const,selector},expected});
const dollars=(amount:number)=>`$${amount.toFixed(2)}`;
const ticketActions=(tickets:number,refundable:boolean):BrowserAction[]=>[{kind:"navigate",path:"/"},...(!refundable?[{kind:"click" as const,selector:"#refundable-checkbox"}]:[]),...Array.from({length:Math.abs(tickets-4)},()=>({kind:"click" as const,selector:tickets<4?"#ticket-decrement-btn":"#ticket-increment-btn"}))];
export function ticketBookingBrowserInventory(raw:ApprovedTicketBrowserPolicy):FixtureBrowserInventory{
 const approved=ticketPolicySchema.parse(raw),cases:BrowserPolicy["cases"]=[],coveredRequirements:string[]=[];
 cases.push({id:"ticket_single_standard",actions:ticketActions(1,false),assertions:[text("#ticket-count-display","1"),text("#summary-ticket-subtotal","$40.00"),text("#summary-total-price","$40.00"),count("#summary-discount",0),count("#summary-refund-fee",0),count("#refundable-badge",0)]});coveredRequirements.push("REQ-BASE-SINGLE-TICKET");
 const pct=approved.groupDiscountPercent,min=approved.minTicketsForDiscount,fee=approved.refundFeePerTicket;
 if(pct!==undefined&&min!==undefined){const discounted=40*min*pct;cases.push({id:"ticket_group_threshold",actions:ticketActions(min,false),assertions:[text("#ticket-count-display",String(min)),text("#summary-ticket-subtotal",dollars(40*min)),...(discounted>0?[text("#summary-discount",`-${dollars(discounted)}`)]:[count("#summary-discount",0)]),text("#summary-total-price",dollars(40*min-discounted))]},{id:"ticket_below_group_threshold",actions:ticketActions(min-1,false),assertions:[text("#ticket-count-display",String(min-1)),count("#summary-discount",0),text("#summary-total-price",dollars(40*(min-1)))]});coveredRequirements.push("REQ-GROUP-DISCOUNT");}
 if(fee!==undefined){cases.push({id:"ticket_refund_surcharge",actions:ticketActions(2,true),assertions:[text("#ticket-count-display","2"),...(fee>0?[text("#summary-refund-fee",`+${dollars(2*fee)}`)]:[count("#summary-refund-fee",0)]),text("#summary-total-price",dollars(80+2*fee)),{query:{kind:"visible",selector:"#refundable-badge"},expected:true}]});coveredRequirements.push("REQ-REFUNDABLE-SURCHARGE");}
 if(pct!==undefined&&min!==undefined&&fee!==undefined){const total=approved.discountAppliesToRefundFee?(40*min+min*fee)*(1-pct):40*min*(1-pct)+min*fee;cases.push({id:"ticket_discount_refund_interaction",actions:ticketActions(min,true),assertions:[text("#ticket-count-display",String(min)),text("#summary-total-price",dollars(total)),{query:{kind:"visible",selector:"#refundable-badge"},expected:true}]});coveredRequirements.push("REQ-INTERACTION-DISCOUNT-AND-REFUND");}
 cases.push({id:"ticket_catalog_dollars",actions:[{kind:"navigate",path:"/"}],assertions:[text("#ticket-event-title","Cloudflare Connect 2026"),{query:{kind:"attribute",selector:"#ticket-event-title",attribute:"data-event-id"},expected:"cf-connect-2026"},text("div:has(> div > #ticket-decrement-btn) > div:first-child > div:nth-child(2)","Base price: $40.00 each"),...(pct!==undefined&&min!==undefined&&fee!==undefined?[text("#summary-total-price",dollars(approved.discountAppliesToRefundFee?(4*40+4*fee)*(1-pct):4*40*(1-pct)+4*fee))]:[])]});
 const defaultSubtotal=160,defaultFee=fee===undefined?0:4*fee,defaultPct=pct!==undefined&&min!==undefined&&4>=min?pct:0,defaultTotal=approved.discountAppliesToRefundFee?(defaultSubtotal+defaultFee)*(1-defaultPct):defaultSubtotal*(1-defaultPct)+defaultFee;
 cases.push({id:"ticket_receipt_reconciles",actions:ticketActions(4,true),assertions:[text("#summary-total-price",dollars(defaultTotal)),{kind:"receipt-sum",containerSelector:"#ticket-receipt",rowsSelector:"#ticket-receipt [data-receipt-amount]",totalSelector:"#summary-total-price",totalPrefix:"",optional:true,maxRows:64}]});coveredRequirements.push("REQ-CATALOG-TO-CHECKOUT-DOLLARS","REQ-RECEIPT-RECONCILES");
 return{fixture:"ticket-booking",policy:{version:1,deadlineMs:60000,cases},coveredRequirements,partialCoverage:[],unsupportedCoverage:[],complete:true,scope:"browser-visible-behavior"};
}
const shippingActions=(weight:number,speed:"standard"|"express",hazardous=false):BrowserAction[]=>[{kind:"navigate",path:"/"},{kind:"fill",selector:"#shipping-weight-input",value:String(weight)},...(speed!=="standard"?[{kind:"select" as const,selector:"#shipping-speed-select",value:speed}]:[]),...(hazardous?[{kind:"click" as const,selector:"#shipping-hazardous-checkbox"}]:[])];
const shippingLine=(line:number,expected:string)=>text(`div:has(> #shipping-total-price) > p:nth-of-type(${line})`,expected);
export function shippingCalculatorBrowserInventory():FixtureBrowserInventory{
 const cases:BrowserPolicy["cases"]=[
 {id:"shipping_base_minimum",actions:shippingActions(2,"standard"),assertions:[value("#shipping-weight-input","2"),value("#shipping-speed-select","standard"),shippingLine(1,"Base Rate: $15.00"),text("#shipping-total-price","Total: $15.00")]},
 {id:"shipping_weight_rate",actions:shippingActions(10,"standard"),assertions:[value("#shipping-weight-input","10"),shippingLine(1,"Base Rate: $30.00"),text("#shipping-total-price","Total: $30.00")]},
 {id:"shipping_express_surcharge",actions:shippingActions(10,"express"),assertions:[value("#shipping-speed-select","express"),shippingLine(2,"Speed Surcharge: $15.00"),text("#shipping-total-price","Total: $45.00")]},
 {id:"shipping_hazardous_fee",actions:shippingActions(10,"express",true),assertions:[value("#shipping-speed-select","express"),shippingLine(3,"Hazardous Fee: $12.00"),text("#shipping-total-price","Total: $57.00")]},
 {id:"shipping_bulk_discount",actions:shippingActions(25,"standard"),assertions:[value("#shipping-weight-input","25"),shippingLine(4,"Bulk Discount: -$11.25"),text("#shipping-total-price","Total: $63.75")]},
 ];
 cases.push({id:"shipping_receipt_reconciles",actions:shippingActions(10,"express",true),assertions:[text("#shipping-total-price","Total: $57.00"),{kind:"receipt-sum",containerSelector:"#shipping-receipt",rowsSelector:"#shipping-receipt [data-receipt-amount]",totalSelector:"#shipping-total-price",totalPrefix:"Total: ",optional:true,maxRows:64}]});
 return{fixture:"shipping-calculator",policy:{version:1,deadlineMs:60000,cases},coveredRequirements:["CHECK-SHIPPING-BASE-MINIMUM","CHECK-SHIPPING-WEIGHT-RATE","CHECK-SHIPPING-EXPRESS-SURCHARGE","CHECK-SHIPPING-HAZARDOUS-FEE","CHECK-SHIPPING-BULK-TIER-DISCOUNT","CHECK-SHIPPING-RECEIPT-RECONCILES"],partialCoverage:[],unsupportedCoverage:[],complete:true,scope:"browser-visible-behavior"};
}
