import{bindBuildManifest,type BuildFile,type BuildManifest,type StaticBuildScope}from'./static-build-artifact';
export interface GitSourceObjectReader{readObject(kind:'commit'|'tree'|'blob',hash:string,maxBytes:number,signal:AbortSignal):Promise<Uint8Array>}
export interface TrustedGitSourceProof{providerRepoId:string;canonicalRepoName:string;commit:string;tree:string;sourceDigest:string;blobs:Array<{path:string;hash:string;mode:'100644'|'100755'}>}
export interface TrustedGitSourceCapture{sourceManifest:BuildManifest;files:BuildFile[];proof:TrustedGitSourceProof}
export type TrustedGitSource=TrustedGitSourceCapture;
async function bounded<T>(promise:Promise<T>,signal:AbortSignal){signal.throwIfAborted();let abort:()=>void=()=>{};try{return await Promise.race([promise,new Promise<never>((_,reject)=>{abort=()=>reject(Error('Trusted source deadline exceeded'));signal.addEventListener('abort',abort,{once:true});})]);}finally{signal.removeEventListener('abort',abort);}}
const hash=/^[a-f0-9]{40}$/;
async function objectHash(kind:string,bytes:Uint8Array){const header=new TextEncoder().encode(`${kind} ${bytes.length}\0`),value=new Uint8Array(header.length+bytes.length);value.set(header);value.set(bytes,header.length);return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-1',value)),byte=>byte.toString(16).padStart(2,'0')).join('');}
/** A trusted native Git reader returns raw objects, never checkout paths or shell-selected files.
 * Provider identity must come from the independently recorded canonical/pin scope. */
export async function captureTrustedGitSource(options:{scope:StaticBuildScope;provider:{providerRepoId:string;canonicalRepoName:string};reader:GitSourceObjectReader;authorize:()=>Promise<void>;signal?:AbortSignal}):Promise<TrustedGitSource>{
 const scope=structuredClone(options.scope),provider=structuredClone(options.provider);if(!hash.test(scope.commit)||!hash.test(scope.tree)||scope.commit==='0'.repeat(40)||scope.tree==='0'.repeat(40)||!provider.providerRepoId||provider.providerRepoId.length>128||!provider.canonicalRepoName||provider.canonicalRepoName.length>200)throw Error('Trusted source identity unavailable');const deadline=Date.now()+120000,signal=AbortSignal.any([AbortSignal.timeout(120000),...(options.signal?[options.signal]:[])]);let calls=0,total=0;const files:BuildFile[]=[],blobs:TrustedGitSource['proof']['blobs']=[],seen=new Set<string>();
 const active=()=>{signal.throwIfAborted();if(Date.now()>=deadline)throw Error('Trusted source deadline exceeded');};
 const read=async(kind:'commit'|'tree'|'blob',oid:string,maxBytes:number)=>{active();await bounded(options.authorize(),signal);active();if(!hash.test(oid)||++calls>1025)throw Error('Trusted source object bound exceeded');const bytes=new Uint8Array(await bounded(options.reader.readObject(kind,oid,maxBytes,signal),signal));active();await bounded(options.authorize(),signal);active();if(bytes.byteLength>maxBytes||await bounded(objectHash(kind,bytes),signal)!==oid)throw Error('Trusted source object identity differs');await bounded(options.authorize(),signal);active();return bytes;};
 const commit=await read('commit',scope.commit,262144),newline=commit.indexOf(10);if(newline<0||new TextDecoder('utf-8',{fatal:true}).decode(commit.subarray(0,newline))!==`tree ${scope.tree}`)throw Error('Trusted commit tree differs');
 const walk=async(oid:string,prefix:string,depth:number)=>{if(depth>32)throw Error('Trusted source tree depth exceeded');const tree=await read('tree',oid,262144);let offset=0;while(offset<tree.length){const space=tree.indexOf(32,offset),nul=tree.indexOf(0,space+1);if(space<=offset||nul<=space+1||nul+21>tree.length)throw Error('Unsupported source tree');const decode=new TextDecoder('utf-8',{fatal:true}),mode=decode.decode(tree.subarray(offset,space)),name=decode.decode(tree.subarray(space+1,nul));if(name.includes('/')||name==='.'||name==='..'||name.length===0)throw Error('Unsupported source path');const entryHash=Array.from(tree.subarray(nul+1,nul+21),byte=>byte.toString(16).padStart(2,'0')).join(''),path=prefix+name;if(path.length>256||/[\x00-\x20\x7f\\?#%]/.test(path)||path.split('/').some(part=>part==='.git'||part==='node_modules'||/^\.env(?:\.|$)/i.test(part)))throw Error('Unsupported source path');offset=nul+21;if(mode==='40000'){await walk(entryHash,path+'/',depth+1);continue;}if(mode!=='100644'&&mode!=='100755')throw Error('Source links and gitlinks are unsupported');if(seen.has(path)||files.length>=512)throw Error('Trusted source inventory bound exceeded');seen.add(path);const bytes=await read('blob',entryHash,4194304);total+=bytes.length;if(total>16777216)throw Error('Trusted source byte bound exceeded');files.push({path,kind:'file',bytes});blobs.push({path,hash:entryHash,mode});}};
 await walk(scope.tree,'',0);await bounded(options.authorize(),signal);active();const sourceManifest=await bounded(bindBuildManifest('source',scope,files),signal);await bounded(options.authorize(),signal);active();return {sourceManifest,files,proof:{...provider,commit:scope.commit,tree:scope.tree,sourceDigest:sourceManifest.digest,blobs}};
}
