import {z} from 'zod';
import {ContainerLifetime} from './container-lifetime';
import{bindBuildManifest,verifyBuildManifest,type BuildFile,type BuildManifest,type StaticBuildScope}from'./static-build-artifact';
const scopeSchema=z.object({attemptId:z.uuid(),projectId:z.string().regex(/^[a-z0-9]{12,16}$/),incarnation:z.uuid(),commit:z.string().regex(/^[a-f0-9]{40}$/).refine(value=>value!=='0'.repeat(40)),tree:z.string().regex(/^[a-f0-9]{40}$/).refine(value=>value!=='0'.repeat(40)),policyDigest:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const imageSchema=z.string().regex(/^registry\.cloudflare\.com\/[a-f0-9]{32}\/[a-z0-9-]+@sha256:[a-f0-9]{64}$/);
export interface UntrustedExecutionRpc{prepare(scope:StaticBuildScope,source:BuildManifest,files:BuildFile[],image:string):Promise<void>;run(scope:StaticBuildScope,source:BuildManifest,files:BuildFile[]):Promise<{manifest:BuildManifest;files:BuildFile[];acceptanceEvidence:false}>;stop():Promise<{stopped:boolean}>}
export interface UntrustedExecutionNamespace{getByName(name:string):UntrustedExecutionRpc}
export async function untrustedExecutionName(scope:StaticBuildScope,sourceDigest:string){const parsed=scopeSchema.parse(scope);if(!/^[a-f0-9]{64}$/.test(sourceDigest))throw Error('Source digest required');const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({scope:parsed,sourceDigest})));return 'untrusted-'+Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,'0')).join('');}
export async function untrustedExecutionHandle(namespace:UntrustedExecutionNamespace|undefined,scope:StaticBuildScope,source:BuildManifest,files:BuildFile[],image:string){if(!namespace)throw Error('Untrusted execution binding unavailable');imageSchema.parse(image);if(source.kind!=='source')throw Error('Source manifest required');await verifyBuildManifest(source,scope,files);const name=await untrustedExecutionName(scope,source.digest);const job=namespace.getByName(name);await job.prepare(scope,source,files,image);return {name,job};}
type State={scope:StaticBuildScope;sourceDigest:string;image:string;phase:'prepared'|'dispatched'|'sealed'|'stopped';commandSettled:boolean;nativeStopped:boolean};
type Storage=Pick<DurableObjectStorage,'sql'|'transactionSync'|'setAlarm'|'deleteAlarm'>;
type RuntimeContainer=Pick<Container,'running'|'start'|'exec'|'destroy'|'inspect'|'interceptAllOutboundHttp'|'interceptOutboundHttps'>;
/** This runtime belongs to a separate sandbox, with no trusted checks or publisher credentials. */
export class UntrustedExecutionRuntime implements UntrustedExecutionRpc{
 constructor(private readonly storage:Storage,private readonly container:()=>RuntimeContainer|undefined,private readonly deny:Fetcher|undefined,private readonly authorize:()=>Promise<void>){storage.sql.exec('CREATE TABLE IF NOT EXISTS untrusted_execution(id INTEGER PRIMARY KEY CHECK(id=1),doc TEXT NOT NULL)');}
 private get(){const row=this.storage.sql.exec<{doc:string}>('SELECT doc FROM untrusted_execution WHERE id=1').toArray()[0];return row?JSON.parse(row.doc) as State:null;}
 private save(state:State){this.storage.sql.exec('INSERT INTO untrusted_execution VALUES(1,?) ON CONFLICT(id) DO UPDATE SET doc=excluded.doc',JSON.stringify(state));}
 private lifetime(){return new ContainerLifetime(this.storage,this.container,120000);}
 async prepare(scope:StaticBuildScope,source:BuildManifest,files:BuildFile[],image:string){source=structuredClone(source);files=files.map(file=>({...file,bytes:file.bytes.slice()}));const identity=scopeSchema.parse(scope);imageSchema.parse(image);if(source.kind!=='source')throw Error('Source manifest required');await verifyBuildManifest(source,identity,files);await this.authorize();this.storage.transactionSync(()=>{const previous=this.get();if(previous){if(previous.phase!=='prepared'||JSON.stringify(previous.scope)!==JSON.stringify(identity)||previous.sourceDigest!==source.digest||previous.image!==image)throw Error('Execution attempt differs or is consumed');return;}this.save({scope:identity,sourceDigest:source.digest,image,phase:'prepared',commandSettled:true,nativeStopped:false});});}
 async stop(){const state=this.get();if(!state)return {stopped:false};this.save({...state,phase:'sealed'});const lifetime=this.lifetime();lifetime.seal();await lifetime.stop();const current=this.get()!;const confirmed=lifetime.status()?.state==='stopped';this.save({...current,nativeStopped:confirmed,phase:confirmed&&current.commandSettled?'stopped':'sealed'});return {stopped:confirmed&&current.commandSettled};}
 async run(scope:StaticBuildScope,source:BuildManifest,files:BuildFile[]){scope=scopeSchema.parse(scope);source=structuredClone(source);files=files.map(file=>({...file,bytes:file.bytes.slice()}));if(!this.deny)throw Error('Deny egress binding unavailable');const container=this.container();if(!container)throw Error('Untrusted container binding unavailable');await verifyBuildManifest(source,scope,files);await this.authorize();const state=this.get();if(!state||state.phase!=='prepared'||JSON.stringify(state.scope)!==JSON.stringify(scope)||state.sourceDigest!==source.digest)throw Error('Execution attempt differs or is consumed');this.save({...state,phase:'dispatched',commandSettled:false});const signal=AbortSignal.timeout(120000),lifetime=this.lifetime();const bounded=<T>(operation:()=>Promise<T>)=>{signal.throwIfAborted();return within(operation(),signal);};let commandIssued=false;let result:{manifest:BuildManifest;files:BuildFile[];acceptanceEvidence:false}|undefined;
 try{await bounded(()=>lifetime.beforeWork());await bounded(()=>this.authorize());lifetime.assertWorkAllowed();await bounded(()=>container.interceptAllOutboundHttp(this.deny!));await bounded(()=>container.interceptOutboundHttps('*',this.deny!));await bounded(()=>this.authorize());signal.throwIfAborted();lifetime.assertWorkAllowed();if(container.running||await bounded(()=>container.inspect())!==null)throw Error('Fresh execution sandbox required');lifetime.assertWorkAllowed();container.start({image:state.image,entrypoint:['sleep','infinity'],enableInternet:false});await bounded(()=>this.authorize());signal.throwIfAborted();lifetime.assertWorkAllowed();const payload=JSON.stringify(files.map(file=>({path:file.path,data:base64(file.bytes)})));commandIssued=true;const process=await within(container.exec(['/usr/local/bin/bun','-e',OFFLINE_BUILD],{stdin:new Response(payload).body!,stdout:'pipe',stderr:'ignore',signal,env:{HOME:'/job/home',TMPDIR:'/job/tmp',CI:'1',NODE_ENV:'production'}}),signal);const text=await readOutput(process.stdout,signal);const exit=await within(process.exitCode,signal);this.save({...this.get()!,commandSettled:true});if(exit!==0)throw Error('Untrusted build failed');const parsed=outputSchema.parse(JSON.parse(text)),output=parsed.map(file=>({path:file.path,kind:'file' as const,bytes:Uint8Array.from(atob(file.data),char=>char.charCodeAt(0))}));const manifest=await bindBuildManifest('static',scope,output,source.digest);await bounded(()=>this.authorize());signal.throwIfAborted();lifetime.assertWorkAllowed();result={manifest,files:output,acceptanceEvidence:false};}finally{if(!commandIssued)this.save({...this.get()!,commandSettled:true});const stopped=await this.stop();if(!stopped.stopped)throw Error('Execution cleanup remains unconfirmed');}if(!result)throw Error('No immutable output');return result;
 }
}
function base64(bytes:Uint8Array){let text='';for(let offset=0;offset<bytes.length;offset+=8192)text+=String.fromCharCode(...bytes.subarray(offset,offset+8192));return btoa(text);}
async function within<T>(promise:Promise<T>,signal:AbortSignal){signal.throwIfAborted();let abort:()=>void=()=>{};try{return await Promise.race([promise,new Promise<never>((_,reject)=>{abort=()=>reject(Error('Execution deadline'));signal.addEventListener('abort',abort,{once:true});})]);}finally{signal.removeEventListener('abort',abort);}}
const outputSchema=z.array(z.object({path:z.string().max(256),data:z.string().max(5592408)}).strict()).max(512);
async function readOutput(stream:ReadableStream|null,signal:AbortSignal){if(!stream)throw Error('Build output unavailable');const reader=stream.getReader();let count=0;const parts:Uint8Array[]=[];try{for(;;){signal.throwIfAborted();const next=await within(reader.read(),signal);if(next.done)break;const bytes=next.value as Uint8Array;count+=bytes.byteLength;if(count>24*1024*1024)throw Error('Build output bound exceeded');parts.push(bytes);}const all=new Uint8Array(count);let offset=0;for(const part of parts){all.set(part,offset);offset+=part.byteLength;}return new TextDecoder('utf-8',{fatal:true}).decode(all);}catch(error){void reader.cancel().catch(()=>{});throw error;}}
const OFFLINE_BUILD=String.raw`const fs=await import('node:fs/promises');const path=await import('node:path');const input=JSON.parse(await Bun.stdin.text());await fs.mkdir('/job/source',{recursive:true});await fs.mkdir('/job/home',{recursive:true});await fs.mkdir('/job/tmp',{recursive:true});await fs.symlink('/opt/execution-deps/node_modules','/job/source/node_modules');for(const file of input){const target='/job/source/'+file.path;await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,Buffer.from(file.data,'base64'));}const child=Bun.spawn(['/usr/local/bin/bun','build','index.html','--outdir','/job/output','--minify','--env=disable','--define','process.env.NODE_ENV="production"'],{cwd:'/job/source',env:{PATH:'/usr/local/bin:/usr/bin:/bin',HOME:'/job/home',TMPDIR:'/job/tmp',NODE_ENV:'production',CI:'1'},stdout:'ignore',stderr:'ignore'});if(await child.exited!==0)process.exit(1);const output=[];async function walk(dir,prefix=''){for(const name of await fs.readdir(dir)){const location=dir+'/'+name,stat=await fs.lstat(location),relative=prefix+name;if(stat.isSymbolicLink()||!stat.isFile()&&!stat.isDirectory())throw Error('Unsupported output');if(stat.isDirectory())await walk(location,relative+'/');else{if(stat.size>4194304||output.length>=512)throw Error('Output bound');output.push({path:relative,data:(await fs.readFile(location)).toString('base64')});}}}await walk('/job/output');console.log(JSON.stringify(output));`;
