// Loopback export shape generated by `wrangler types --include-runtime false`.
// The module path is relative so the declaration remains reproducible in clones.
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
    durableNamespaces: 'RepositoryController' | 'IntegratorSandbox' | 'AgentSandbox';
  }
}
