import {createHash} from 'node:crypto';
import type {FlareGitProjectState,Contributor} from '../core/types';
import {safeSearchText} from './metadata-search';
export interface WorkspaceAttentionRow{id:string;kind:'review'|'decision'|'change';projectId:string;projectName:string;purpose:string;contributors:Array<Pick<Contributor,'id'|'name'|'type'>>;status:string;taskIds:string[];candidateId?:string;decisionId?:string;commit:string|null;updatedAt:string;href:string}
export interface WorkspaceAttentionSnapshot{projectId:string;projectName:string;role:'owner'|'member';rows:WorkspaceAttentionRow[];truncated:boolean;epoch:string}
const validId=(value:string)=>/^[A-Za-z0-9_-]{1,200}$/.test(value),sha=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{40}$/.test(value)&&!/^0{40}$/.test(value);
const attentionOrder=(a:WorkspaceAttentionRow,b:WorkspaceAttentionRow)=>({review:0,decision:1,change:2}[a.kind]-{review:0,decision:1,change:2}[b.kind])||(Date.parse(b.updatedAt)||0)-(Date.parse(a.updatedAt)||0)||a.id.localeCompare(b.id);
/** Current actionable metadata only. Inbox events remain historical and are never consumed here. */
export function buildWorkspaceAttention(state:FlareGitProjectState,userId:string,role:'owner'|'member',acceptancePolicyVersion=0):WorkspaceAttentionSnapshot{
 const rows:WorkspaceAttentionRow[]=[],projectName=safeSearchText(state.projectName,120),base='/p/'+encodeURIComponent(state.projectId),candidates=Object.values(state.candidates),decisions=Object.values(state.decisions),tasks=Object.values(state.tasks);let truncated=candidates.length>1000||decisions.length>1000||tasks.length>1000;
 const contributors=(ids:string[])=>{const values=new Map<string,Pick<Contributor,'id'|'name'|'type'>>();for(const id of ids.slice(0,8)){const actor=state.tasks[id]?.contributor;if(actor&&actor.id.length>0&&actor.id.length<=256&&!/[\x00-\x1f\x7f]/.test(actor.id))values.set(actor.id,{id:actor.id,name:safeSearchText(actor.name,80)|| (actor.type==='agent'?'Coding agent':'Contributor'),type:actor.type});}return [...values.values()];};
 const add=(input:Omit<WorkspaceAttentionRow,'projectId'|'projectName'>)=>{if(!Number.isFinite(Date.parse(input.updatedAt))){truncated=true;return;}rows.push({...input,updatedAt:new Date(input.updatedAt).toISOString(),projectId:state.projectId,projectName});};
 if(role==='owner')for(const candidate of candidates.slice(-1000)){
  if(candidate.status!=='awaiting_review'||!validId(candidate.id)||!sha(candidate.candidateCommit)||state.journal.some(journal=>journal.candidateId===candidate.id&&['ACCEPTED','ABORTED','PREPARED'].includes(journal.state)))continue;
  if(candidate.policyAuthorization?.identity.candidateId===candidate.id&&candidate.policyAuthorization.identity.projectId===state.projectId&&candidate.policyAuthorization.identity.commit===candidate.candidateCommit&&candidate.policyAuthorization.policyVersion===acceptancePolicyVersion)continue;
  if(candidate.review?.commit===candidate.candidateCommit&&(candidate.review.acceptancePolicyVersion??0)===acceptancePolicyVersion)continue;
  const evidence=candidate.evidenceId?state.evidence[candidate.evidenceId]:null;if(!evidence||evidence.status!=='passed'||evidence.candidateCommit!==candidate.candidateCommit)continue;
  if(candidate.participatingTaskIds.length>8)truncated=true;const taskIds=candidate.participatingTaskIds.filter(id=>validId(id)&&!!state.tasks[id]).slice(0,8);if(taskIds.length===0)continue;
  add({id:state.projectId+':review:'+candidate.id,kind:'review',candidateId:candidate.id,taskIds,purpose:safeSearchText(taskIds.slice(0,3).map(id=>state.tasks[id]!.goal).join(' · '),200)||'Review proposed contribution',contributors:contributors(taskIds),status:'awaiting_review',commit:candidate.candidateCommit,updatedAt:candidate.updatedAt,href:base+'/review?candidate='+encodeURIComponent(candidate.id)});
 }
 const decisionTasks=new Set<string>();
 if(role==='owner')for(const decision of decisions.slice(-1000)){if(decision.status!=='pending'||!validId(decision.id))continue;if((decision.scope?.participants.length??0)>8)truncated=true;const taskIds=(decision.scope?.participants.map(row=>row.taskId)??[]).filter(id=>validId(id)&&!!state.tasks[id]&&!['accepted','cancelled'].includes(state.tasks[id]!.status)).slice(0,8);if(decision.scope&&taskIds.length===0)continue;for(const id of taskIds)decisionTasks.add(id);add({id:state.projectId+':decision:'+decision.id,kind:'decision',decisionId:decision.id,taskIds,purpose:safeSearchText(decision.question,200)||'Resolve contribution decision',contributors:contributors(taskIds),status:'pending',commit:null,updatedAt:decision.createdAt,href:base+'/integration?decision='+encodeURIComponent(decision.id)});}
 for(const task of tasks.slice(-1000)){if(!validId(task.id)||!['blocked','needs_decision'].includes(task.status)||decisionTasks.has(task.id)||role==='member'&&task.contributor.id!==userId&&task.initiatedBy?.id!==userId)continue;add({id:state.projectId+':change:'+task.id,kind:'change',taskIds:[task.id],purpose:safeSearchText(task.goal,200)||'Continue contribution',contributors:contributors([task.id]),status:task.status,commit:sha(task.currentCommit)?task.currentCommit:null,updatedAt:task.updatedAt,href:base+'/changes?task='+encodeURIComponent(task.id)});}
 rows.sort(attentionOrder);if(rows.length>60)truncated=true;const bounded=rows.slice(0,60),epoch=createHash('sha256').update(JSON.stringify({projectId:state.projectId,role,rows:bounded,truncated})).digest('hex');return{projectId:state.projectId,projectName,role,rows:bounded,truncated,epoch};
}
export function workspaceAttentionPage(snapshots:WorkspaceAttentionSnapshot[],incompleteRepositories:number,cursor:string|null){const rows=snapshots.flatMap(snapshot=>snapshot.rows).sort(attentionOrder),epoch=createHash('sha256').update(JSON.stringify({snapshots:snapshots.map(value=>[value.projectId,value.epoch,value.truncated]),orderedRows:rows.map(row=>row.id),incompleteRepositories})).digest('hex');let offset=0;if(cursor){const match=/^([0-9]{1,6}):([a-f0-9]{64})$/.exec(cursor);if(!match||match[2]!==epoch||Number(match[1])>rows.length)throw Error('Workspace attention changed; refresh from the first page');offset=Number(match[1]);}return{rows:rows.slice(offset,offset+20),nextCursor:offset+20<rows.length?`${offset+20}:${epoch}`:null,complete:incompleteRepositories===0&&snapshots.every(snapshot=>!snapshot.truncated),incompleteRepositories,observedAt:new Date().toISOString()};}
