import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {CandidateGeneration,PublicationJournalEntry} from '../src/core/types';
import type {DeploymentRecord} from '../src/server/deployments';
test('native deployment selection pins exact accepted branch receipt, refuses missing or mismatched proof, and preserves legacy primary replay',async()=>{
 if(await workerdChild('tests/accepted-deployment-native.test.ts'))return;
 const output=`/tmp/flaregit-accepted-deployment-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/accepted-deployment-native-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:'1000000',MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:'2000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'deployment',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'AcceptedDeploymentFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('deployment'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})}),json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body),value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 await json('/seed');await json('/create',{operationId:crypto.randomUUID(),name:'release',sourceCommit:'a'.repeat(40)});const service=await json<{id:string}>('/deployment-service');
 async function accept(taskId:string,ref:string,commit:string){await json('/target-task',{id:taskId,ref});const {candidate}=await json<{candidate:CandidateGeneration}>('/landing',{tasks:[taskId],holder:`landing-${taskId}`});await json('/verify-target',{id:candidate.id,bind:true,commit});const target=candidate.acceptedTarget!;await json('/review-target',{id:candidate.id,commit,target:{ref:target.ref,acceptedCommit:target.acceptedCommit,acceptedVersion:target.acceptedVersion}});const prepared=await json<{ok:boolean;journal:PublicationJournalEntry}>('/prepare?id='+candidate.id);if(!prepared.ok)throw Error('Publication preparation unavailable');await json('/complete-target',{journalId:prepared.journal.id});return prepared.journal;}
 const branch=await accept('release-task','refs/heads/release','b'.repeat(40));expect(await json('/deployment-target?journal='+branch.id)).toMatchObject({target:{acceptedRef:'refs/heads/release',acceptedRootVersion:1,commit:branch.newHead,tree:branch.candidateTree}});
 for(const mode of ['missing','wrong-ref','wrong-tree']){expect((await call('/deployment-request',{journalId:branch.id,serviceId:service.id,key:`bad-${mode}`,mode})).ok).toBe(false);}expect(await json<unknown[]>('/deployment-events')).toEqual([]);
 const created=await json<{kind:string;deployment:DeploymentRecord}>('/deployment-request',{journalId:branch.id,serviceId:service.id,key:'branch-request',mode:'trusted'});expect(created.kind).toBe('created');expect(created.deployment.target.acceptedRef).toBe('refs/heads/release');expect(await json('/deployment-request',{journalId:branch.id,serviceId:service.id,key:'branch-request',mode:'missing'})).toMatchObject({kind:'duplicate',deployment:{id:created.deployment.id}});const events=await json<Array<{data:{commit:string;tree:string;acceptedRef:string;recoverableRef:string}}>>('/deployment-events');expect(events).toHaveLength(1);expect(events[0]?.data).toMatchObject({commit:branch.newHead,tree:branch.candidateTree,acceptedRef:'refs/heads/release',recoverableRef:created.deployment.target.recoverableRef});
 const primary=await accept('primary-task','refs/heads/main','d'.repeat(40));expect(await json('/deployment-target?journal='+primary.id)).toMatchObject({target:{acceptedRef:'refs/heads/main',commit:primary.newHead}});const old=await json<{deployment:DeploymentRecord}>('/deployment-legacy-seed',{journalId:primary.id,serviceId:service.id,key:'legacy-primary'});expect(old.deployment.target.acceptedRef).toBeUndefined();const replay=await json<{kind:string;deployment:DeploymentRecord}>('/deployment-request',{journalId:primary.id,serviceId:service.id,key:'legacy-primary',mode:'missing'});expect(replay).toEqual({kind:'duplicate',deployment:old.deployment});expect((await json<unknown[]>('/deployment-events')).length).toBe(1);
 }finally{await mf.dispose();}
},30000);
