import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {AcceptedBranchRoots} from '../src/server/accepted-branch-roots';
import {bindTaskAcceptedTarget,boundTaskCreationPayload,assertTaskTargetRetry} from '../src/server/accepted-task-target';
import {taskCreationPayload} from '../src/server/task-creation';
import type {FlareGitProjectState,Task} from '../src/core/types';
function fixture(){const db=new Database(':memory:');const storage={sql:{exec(query:string,...bindings:Array<string|number>){if(query.includes(';')){db.exec(query);return{toArray:()=>[],one:()=>({})};}const rows=db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}};const roots=new AcceptedBranchRoots(storage as unknown as DurableObjectStorage),incarnation=crypto.randomUUID();const scope={projectId:'p123456789abc',incarnation,canonicalRepoName:'canonical',ref:'refs/heads/main'};roots.initializePrimary(scope,{commit:'a'.repeat(40),requirements:[]},()=>{});const operation={operationId:crypto.randomUUID(),projectId:scope.projectId,incarnation,canonicalRepoName:scope.canonicalRepoName,actorId:'owner',accountKey:'account',branch:'release',sourceCommit:'a'.repeat(40),acceptedCommit:'a'.repeat(40),phase:'confirmed' as const,createdAt:1,observedCommit:'a'.repeat(40)};roots.createRoot(operation,{observedHead:operation.sourceCommit,sourceCommit:operation.sourceCommit,acceptedCommit:operation.acceptedCommit,ancestryVerified:true,nativeStopped:true,credentialsRevoked:true},{commit:'a'.repeat(40),requirements:[]},()=>{});const state={projectId:scope.projectId,canonicalRepoName:scope.canonicalRepoName,defaultBranch:'main',acceptedState:{currentCommit:'a'.repeat(40),activeRequirements:[]},policyVersion:1,verificationPolicy:{},tasks:{}} as unknown as FlareGitProjectState;const task:Task={id:'task-new',goal:'Improve source',contributor:{id:'human',name:'Human',type:'human'},baseCommit:'a'.repeat(40),currentCommit:'a'.repeat(40),status:'ready',allowedScope:['src/'],requirements:[],workspace:{repoName:'workspace',remote:'https://fixture.invalid',branch:'task/new'},checkpoints:[],createdAt:'now',updatedAt:'now'};return{db,roots,state,task,incarnation};}
test('internal registered target binding is exact and leaves unbound legacy bytes unchanged',()=>{const {db,roots,state,task,incarnation}=fixture();try{expect(bindTaskAcceptedTarget(roots,state,incarnation,task)).toBe(task);const input={goal:task.goal,dependsOn:null,issue:null};expect(boundTaskCreationPayload(input)).toBe(taskCreationPayload(input));const bound=bindTaskAcceptedTarget(roots,state,incarnation,task,{acceptedTargetRef:'refs/heads/release'});expect(bound.acceptedTarget).toMatchObject({ref:'refs/heads/release',acceptedVersion:0,acceptedCommit:'a'.repeat(40)});expect(boundTaskCreationPayload(input,bound.acceptedTarget)).not.toBe(taskCreationPayload(input));expect(()=>assertTaskTargetRetry(bound)).toThrow('omitted');expect(()=>assertTaskTargetRetry(bound,{acceptedTargetRef:'refs/heads/main'})).toThrow('changed');assertTaskTargetRetry(bound,{acceptedTargetRef:'refs/heads/release'});expect(()=>bindTaskAcceptedTarget(roots,state,incarnation,{...task,baseCommit:'b'.repeat(40)},{acceptedTargetRef:'refs/heads/release'})).toThrow('workspace');}finally{db.close();}});
test('stacks inherit exactly one frozen target and reject cross-target dependencies',()=>{const {db,roots,state,task,incarnation}=fixture();try{const parent=bindTaskAcceptedTarget(roots,state,incarnation,task,{acceptedTargetRef:'refs/heads/release'});parent.currentCommit='b'.repeat(40);state.tasks[parent.id]=parent;const child={...task,id:'task-child',dependsOn:parent.id,baseCommit:parent.currentCommit,currentCommit:parent.currentCommit};expect(bindTaskAcceptedTarget(roots,state,incarnation,child).acceptedTarget?.ref).toBe('refs/heads/release');expect(()=>bindTaskAcceptedTarget(roots,state,incarnation,child,{acceptedTargetRef:'refs/heads/main'})).toThrow('mixes');}finally{db.close();}});
