import {test,expect} from 'bun:test';
import {acceptanceRuntimeReleaseSchema,pinAcceptanceRelease,type AcceptanceReleasePin} from '../src/cli/acceptance-release';
function release():AcceptanceReleasePin{return{workerVersion:crypto.randomUUID(),sourceVersion:'a'.repeat(40),releaseIdentified:true};}
test('release pin requires both identified versions and exact repetition retains the first pin object',()=>{const runtime=release(),first=pinAcceptanceRelease(runtime);expect(first).toEqual(runtime);expect(Object.isFrozen(first)).toBe(true);expect(pinAcceptanceRelease({...runtime},first)).toBe(first);expect(Object.keys(first).sort()).toEqual(['releaseIdentified','sourceVersion','workerVersion']);});
test('unidentified null or partial runtime identities cannot establish a pin',()=>{for(const runtime of [{workerVersion:null,sourceVersion:null,releaseIdentified:false},{workerVersion:crypto.randomUUID(),sourceVersion:null,releaseIdentified:false},{workerVersion:null,sourceVersion:'a'.repeat(40),releaseIdentified:false}]){expect(acceptanceRuntimeReleaseSchema.safeParse(runtime).success).toBe(true);expect(()=>pinAcceptanceRelease(runtime)).toThrow('not identified');}});
test('missing, malformed, inconsistent and extra runtime fields are refused',()=>{const valid=release();for(const runtime of [{}, {...valid,workerVersion:undefined},{...valid,sourceVersion:undefined},{...valid,workerVersion:'not-a-uuid'},{...valid,sourceVersion:'0'.repeat(40)},{...valid,sourceVersion:'A'.repeat(40)},{...valid,sourceVersion:'b'.repeat(41)},{...valid,releaseIdentified:false},{...valid,workerVersion:null},{...valid,sourceVersion:null},{...valid,releaseIdentified:'true'},{...valid,timestamp:'not-retained'}])expect(()=>pinAcceptanceRelease(runtime)).toThrow();});
test('worker deployment mismatch never overwrites the original source and worker pin',()=>{const first=pinAcceptanceRelease(release()),snapshot={...first};expect(()=>pinAcceptanceRelease({...first,workerVersion:crypto.randomUUID()},first)).toThrow('original pin is retained');expect(first).toEqual(snapshot);});
test('source mismatch never overwrites the original deployment pin',()=>{const first=pinAcceptanceRelease(release()),snapshot={...first};expect(()=>pinAcceptanceRelease({...first,sourceVersion:'b'.repeat(40)},first)).toThrow('original pin is retained');expect(first).toEqual(snapshot);});
test('a malformed previous pin cannot be repaired or silently replaced',()=>{const current=release();for(const previous of [{...current,workerVersion:'invalid'},{...current,sourceVersion:'0'.repeat(40)},{...current,extra:'untrusted'}])expect(()=>pinAcceptanceRelease(current,previous)).toThrow();});

test('native Git clone carries origin-scoped release headers and refuses redirects',async()=>{
 const {acceptanceCloneEnvironment}=await import('../src/cli/acceptance-release');
 const pin={workerVersion:crypto.randomUUID(),sourceVersion:'a'.repeat(40),releaseIdentified:true as const},remote='https://owned.example/git/p/abcdef123456/canonical';
 const env=acceptanceCloneEnvironment(remote,'https://owned.example','synthetic-unit-token',pin);
 expect(env.GIT_CONFIG_COUNT).toBe('4');expect(env.GIT_CONFIG_KEY_0).toBe('http.https://owned.example/.extraHeader');expect(env.GIT_CONFIG_VALUE_1).toContain(pin.workerVersion);expect(env.GIT_CONFIG_VALUE_2).toContain(pin.sourceVersion);expect(env.GIT_CONFIG_VALUE_3).toBe('false');
 const child=Bun.spawn(['git','config','--get-all',env.GIT_CONFIG_KEY_0!],{env:{...process.env,...env,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'},stdout:'pipe',stderr:'ignore'});const output=await new Response(child.stdout).text();expect(await child.exited).toBe(0);expect(output).toContain('X-FlareGit-Expected-Worker-Version: '+pin.workerVersion);expect(output).toContain('X-FlareGit-Expected-Source-Version: '+pin.sourceVersion);expect(env.GIT_CONFIG_KEY_3).toBe('http.followRedirects');
 expect(()=>acceptanceCloneEnvironment('https://foreign.example/git/p/abcdef123456/canonical','https://owned.example','synthetic-unit-token',pin)).toThrow();expect(()=>acceptanceCloneEnvironment(remote,'https://owned.example','bad\nheader',pin)).toThrow();
});
