import { expect,test } from "bun:test";
import { Miniflare,convertV4MiniflareOptions } from "miniflare";
import { workerdChild } from "./support/workerd-child";
import type { AgentRunInput,AgentRunClaim,AgentRunRecord } from "../src/server/agent-run-ledger";

test("durable run SQL freezes context/proposals and rejects stale generations without expiry takeover",async()=>{
  if(await workerdChild("tests/agent-run-ledger.test.ts"))return;
  const bundle=`/tmp/flaregit-agent-ledger-${crypto.randomUUID()}.js`;
  const build=Bun.spawn([process.execPath,"build","tests/support/agent-run-ledger-worker.ts","--target=browser","--external=cloudflare:workers",`--outfile=${bundle}`],{stdout:"ignore",stderr:"pipe"});
  const [error,code]=await Promise.all([new Response(build.stderr).text(),build.exited]);if(code!==0)throw new Error(error);
  const script=await Bun.file(bundle).text();await Bun.file(bundle).delete();
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"agent-ledger",modules:true,script,compatibilityDate:"2026-10-02",durableObjects:{TEST:{className:"AgentRunFixture",useSQLite:true}}}]}));
  const request=async(route:string,body:unknown)=>(await mf.getWorker("agent-ledger")).fetch(`http://test${route}`,{method:"POST",body:JSON.stringify(body)});
  const input:AgentRunInput={runId:"workflow-one",taskId:"task-one",startingCommit:"a".repeat(40),startingBranchHead:null,branch:"task/task-one",goal:"Implement source change",context:{issue:{number:1,title:"Issue",summary:"API_KEY=synthetic-credential-value"},comments:[{id:1,summary:"Saved human task context"}]},allowedScope:["src/"],protectedPaths:["src/protected.ts"]};
  try{
    const claims=await Promise.all([request("/claim",input),request("/claim",{...input,runId:"competing-run"})]);
    const values=await Promise.all(claims.map(async(response)=>await response.json() as AgentRunClaim));
    expect(values.map(value=>value.kind).sort()).toEqual(["busy","claimed"]);
    const active=values.find(value=>value.kind==="claimed")!.run;
    const activeIdentity={runId:active.runId,taskId:active.taskId};
    expect(JSON.stringify(active.context)).not.toContain("synthetic-credential-value");
    expect((await(await request("/claim",{...input,runId:active.runId,goal:"Later goal"})).json() as AgentRunClaim).run.goal).toBe(input.goal);
    expect((await request("/propose",{...activeIdentity,files:{"src/protected.ts":"protected write"}})).status).toBe(409);
    expect((await request("/propose",{...activeIdentity,files:{"src/file.ts":"const api_key='synthetic-secret-value';"}})).status).toBe(409);
    expect((await request("/propose",{...activeIdentity,files:{"../escape":"unsafe"}})).status).toBe(409);
    expect((await request("/propose",{...activeIdentity,files:{"src/file.ts":"x".repeat(120001)}})).status).toBe(409);
    const files={"src/file.ts":"export const value=1;"};
    expect(await(await request("/propose",{...activeIdentity,files})).json()).toBe(true);
    const saved=await(await request("/get",activeIdentity)).json() as AgentRunRecord;
    expect(saved.phase).toBe("proposed");expect(saved.proposal?.files).toEqual(files);expect(saved.proposal?.digest).toMatch(/^[a-f0-9]{64}$/);
    expect(await(await request("/propose",{...activeIdentity,files:{"src/file.ts":"different"}})).json()).toBe(false);
    expect(await(await request("/push",{...activeIdentity,commit:"b".repeat(40)})).json()).toBe(true);
    expect(await(await request("/push",{...activeIdentity,commit:"c".repeat(40)})).json()).toBe(false);
    expect(await(await request("/checkpoint",{...activeIdentity,eventId:"checkpoint-one",commit:"b".repeat(40)})).json()).toBe(true);
    expect(await(await request("/checkpoint",{...activeIdentity,eventId:"checkpoint-one",commit:"b".repeat(40)})).json()).toBe(true);
    const replacement=await(await request("/claim",{...input,runId:"replacement"})).json() as AgentRunClaim;
    expect(replacement.run.generation).toBe(active.generation+1);
    expect(await(await request("/fail",{...activeIdentity,reason:"Late failure"})).json()).toBe(false);
    expect((await(await request("/claim",{...input,runId:active.runId})).json() as AgentRunClaim).kind).toBe("busy");
    expect(await(await request("/fail",{runId:"replacement",taskId:input.taskId,reason:"Stopped"})).json()).toBe(true);
    await request("/claim",{...input,taskId:"resume-task",runId:"resume-original"});
    const original={runId:"resume-original",taskId:"resume-task"};
    await request("/propose",{...original,files});
    const originalSaved=await(await request("/get",original)).json() as AgentRunRecord;
    const recovery={newRunId:"resume-replacement",taskId:"resume-task",previousRunId:"resume-original",allowedScope:["src/"],protectedPaths:[],goal:input.goal};
    expect((await request("/resume",recovery)).status).toBe(409);
    await request("/fail",{...original,reason:"Stopped"});
    expect((await request("/resume",{...recovery,goal:"Changed purpose"})).status).toBe(409);
    expect((await request("/resume",{...recovery,allowedScope:["other/"]})).status).toBe(409);
    expect((await request("/resume",{...recovery,protectedPaths:["src/file.ts"]})).status).toBe(409);
    const recovered=await(await request("/resume",recovery)).json() as AgentRunClaim;
    expect(recovered.run.phase).toBe("proposed");
    expect(recovered.run.proposal).toEqual(originalSaved.proposal);
    expect(recovered.run.proposal?.commitDate).toBe(originalSaved.createdAt);
    expect(recovered.run.startingCommit).toBe(originalSaved.startingCommit);
    expect(recovered.run.startingBranchHead).toBe(originalSaved.startingBranchHead);
    expect(recovered.run.generation).toBe(originalSaved.generation+1);
    expect(recovered.run.resumedFrom).toBe(original.runId);
    expect((await(await request("/get",original)).json() as AgentRunRecord).phase).toBe("failed");
    expect(await(await request("/fail",{...original,reason:"Late failure"})).json()).toBe(false);
    expect((await request("/resume",{...recovery,newRunId:"second-recovery"})).status).toBe(409);
    expect((await(await request("/claim",{...input,runId:"after-failure"})).json() as AgentRunClaim).kind).toBe("claimed");
  }finally{await mf.dispose();}
},30000);
