import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {ArtifactAllocationFence} from "../src/server/allocation-fence";
const input=()=>({name:"artifact",projectId:"p123456789abc",accountKey:"abcdef123456",operationId:crypto.randomUUID()});
function fence(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}};return new ArtifactAllocationFence(storage as unknown as DurableObjectStorage);}
test("sealed account/project lifecycle rejects admission and dispatch atomically",()=>{const ledger=fence(),operation=input();let active=true;ledger.begin(operation,()=>active);active=false;expect(()=>ledger.activate(operation.name,operation.operationId,()=>active)).toThrow("sealed");expect(ledger.pending()).toEqual([{...operation,phase:"reserved"}]);expect(()=>ledger.begin(input(),()=>active)).toThrow("sealed");ledger.settle(operation.name,operation.operationId);expect(ledger.pending()).toEqual([]);});
test("unknown dispatched allocation remains pending without expiry and blocks replacement",()=>{const ledger=fence(),operation=input();ledger.begin(operation,()=>true);ledger.activate(operation.name,operation.operationId,()=>true);expect(ledger.pending()).toEqual([{...operation,phase:"allocating"}]);expect(()=>ledger.begin({...operation,operationId:crypto.randomUUID()},()=>true)).toThrow("pending");ledger.settle(operation.name,crypto.randomUUID());expect(ledger.pending()).toHaveLength(1);ledger.settle(operation.name,operation.operationId);expect(ledger.pending()).toHaveLength(0);});
test("late settlement cannot erase a replacement allocation lease",()=>{const ledger=fence(),first=input(),second={...first,operationId:crypto.randomUUID()};ledger.begin(first,()=>true);ledger.settle(first.name,first.operationId);ledger.begin(second,()=>true);ledger.settle(first.name,first.operationId);expect(ledger.pending()).toEqual([{...second,phase:"reserved"}]);});
test('named inspection distinguishes absent reserved allocating and settled without reopening a hold',()=>{const ledger=fence(),operation=input();expect(ledger.inspect(operation.name)).toBeNull();ledger.begin(operation,()=>true);expect(ledger.inspect(operation.name)).toEqual({...operation,phase:'reserved',outcome:null});ledger.activate(operation.name,operation.operationId,()=>true);expect(ledger.inspect(operation.name)).toEqual({...operation,phase:'allocating',outcome:null});ledger.settle(operation.name,operation.operationId);expect(ledger.pending()).toEqual([]);expect(ledger.inspect(operation.name)).toEqual({...operation,phase:'settled',outcome:null});expect(ledger.inspect(operation.name)).toEqual({...operation,phase:'settled',outcome:null});});

test("same operation UUID can record distinct attempts without late settlement corrupting replacement",()=>{const ledger=fence(),first={...input(),attemptId:crypto.randomUUID()},second={...first,attemptId:crypto.randomUUID()};ledger.begin(first,()=>true);ledger.settle(first.name,first.operationId,"not_dispatched",first.attemptId);expect(ledger.inspect(first.name)?.outcome).toBe("not_dispatched");expect(()=>ledger.settle(first.name,first.operationId,"provider_confirmed",first.attemptId)).toThrow("conflicts");ledger.settle(first.name,first.operationId);expect(ledger.inspect(first.name)?.outcome).toBe("not_dispatched");ledger.begin(second,()=>true);ledger.settle(first.name,first.operationId,"provider_confirmed",first.attemptId);expect(ledger.inspect(first.name)?.phase).toBe("reserved");expect(ledger.inspect(first.name)?.outcome).toBeNull();ledger.activate(second.name,second.operationId,()=>true);ledger.settle(second.name,second.operationId,"provider_confirmed",second.attemptId);expect(ledger.inspect(second.name)?.outcome).toBe("provider_confirmed");});
test("legacy settled SQLite rows migrate without fabricated dispatch evidence",()=>{const db=new Database(":memory:"),operation=input();db.exec("CREATE TABLE artifact_allocation_fences(name TEXT PRIMARY KEY,operation_id TEXT NOT NULL,project_id TEXT NOT NULL,account_key TEXT NOT NULL,phase TEXT NOT NULL)");db.query("INSERT INTO artifact_allocation_fences VALUES(?,?,?,?, 'settled')").run(operation.name,operation.operationId,operation.projectId,operation.accountKey);const storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};try{const ledger=new ArtifactAllocationFence(storage as unknown as DurableObjectStorage);expect(ledger.inspect(operation.name)).toEqual({...operation,phase:"settled",outcome:null});ledger.settle(operation.name,operation.operationId,"not_dispatched");expect(ledger.inspect(operation.name)?.outcome).toBeNull();new ArtifactAllocationFence(storage as unknown as DurableObjectStorage);expect(ledger.pending()).toEqual([]);}finally{db.close();}});

test("legacy five-column SQL producers invalidate prior same UUID evidence",()=>{const db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};try{const ledger=new ArtifactAllocationFence(storage as unknown as DurableObjectStorage),operation={...input(),attemptId:crypto.randomUUID()};ledger.begin(operation,()=>true);ledger.settle(operation.name,operation.operationId,"not_dispatched",operation.attemptId);db.query("INSERT INTO artifact_allocation_fences VALUES(?,?,?,?, 'reserved') ON CONFLICT(name) DO UPDATE SET phase='reserved'").run(operation.name,operation.operationId,operation.projectId,operation.accountKey);expect(ledger.inspect(operation.name)?.outcome).toBeNull();db.query("UPDATE artifact_allocation_fences SET phase='settled' WHERE name=?").run(operation.name);expect(ledger.inspect(operation.name)?.outcome).toBeNull();expect(db.query("SELECT outcome FROM artifact_allocation_receipts").all()).toEqual([{outcome:"not_dispatched"}]);}finally{db.close();}});

test("workerd SQLite preserves legacy producers and exact retry attempt receipts",async()=>{
 const {workerdChild}=await import("./support/workerd-child");if(await workerdChild("tests/allocation-fence.test.ts","workerd SQLite preserves legacy producers and exact retry attempt receipts"))return;
 const {Miniflare,convertV4MiniflareOptions}=await import("miniflare");const source=`/tmp/flaregit-allocation-${crypto.randomUUID()}.ts`;
 await Bun.write(source,`import {DurableObject} from "cloudflare:workers";import {ArtifactAllocationFence} from ${JSON.stringify(`${process.cwd()}/src/server/allocation-fence.ts`)};export class Fixture extends DurableObject{async fetch(){const ledger=new ArtifactAllocationFence(this.ctx.storage),value={name:"artifact",projectId:"p123",accountKey:"owner",operationId:crypto.randomUUID(),attemptId:crypto.randomUUID()};ledger.begin(value,()=>true);ledger.settle(value.name,value.operationId,"not_dispatched",value.attemptId);const first=ledger.inspect(value.name);this.ctx.storage.sql.exec("INSERT INTO artifact_allocation_fences VALUES(?,?,?,?, 'reserved') ON CONFLICT(name) DO UPDATE SET phase='reserved'",value.name,value.operationId,value.projectId,value.accountKey);this.ctx.storage.sql.exec("UPDATE artifact_allocation_fences SET phase='settled' WHERE name=?",value.name);const legacy=ledger.inspect(value.name),next={...value,attemptId:crypto.randomUUID()};ledger.begin(next,()=>true);ledger.settle(value.name,value.operationId,"provider_confirmed",value.attemptId);const pending=ledger.inspect(value.name);ledger.activate(next.name,next.operationId,()=>true);ledger.settle(next.name,next.operationId,"provider_confirmed",next.attemptId);return Response.json({first,legacy,pending,last:ledger.inspect(next.name),receipts:this.ctx.storage.sql.exec("SELECT outcome FROM artifact_allocation_receipts ORDER BY rowid").toArray()});}}export default{fetch(request,env){return env.FENCE.get(env.FENCE.idFromName("case")).fetch(request);}};`);
 let mf:InstanceType<typeof Miniflare>|undefined;try{const build=await Bun.build({entrypoints:[source],target:"browser",external:["cloudflare:workers"]});if(!build.success)throw Error("Allocation fixture build failed");mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"allocation",modules:true,script:await build.outputs[0]!.text(),compatibilityDate:"2026-10-02",durableObjects:{FENCE:{className:"Fixture",useSQLite:true}}}]}));const body=await(await(await mf.getWorker("allocation")).fetch("http://fixture/")).json() as {first:{outcome:string};legacy:{outcome:null};pending:{phase:string;outcome:null};last:{outcome:string};receipts:Array<{outcome:string}>};expect(body.first.outcome).toBe("not_dispatched");expect(body.legacy.outcome).toBeNull();expect(body.pending.phase).toBe("reserved");expect(body.pending.outcome).toBeNull();expect(body.last.outcome).toBe("provider_confirmed");expect(body.receipts).toEqual([{outcome:"not_dispatched"},{outcome:"provider_confirmed"}]);}finally{await mf?.dispose();await Bun.file(source).delete();}
},30000);
