import{expect,test}from'bun:test';import{Miniflare,convertV4MiniflareOptions}from'miniflare';import{workerdChild}from'./support/workerd-child';
interface Snapshot{creates:Array<{id:string;params:{taskIds:string[]}}>;inspections:Array<{id:string}>;dispatches:Array<{workflowId:string;phase:string;observedStatus?:string}>;activities:Array<{type:string}>;tasks:Array<{id:string;status:string}>}
test('actual task-ready controller schedules only complete supported cohorts once, preserves unknown ACK identity, and isolates optional webhook failure',async()=>{
 if(await workerdChild('tests/auto-integration-controller.test.ts'))return;
 const output=`/private/tmp/c04-controller-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/auto-integration-controller-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});if(await build.exited!==0)throw Error(await new Response(build.stderr).text());const script=await Bun.file(output).text();await Bun.file(output).delete();const base={RUNS_ENABLED:'true',FREE_RUNS_PER_DAY:'100',GLOBAL_RUNS_PER_DAY:'100'},mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'c04-controller',modules:true,script,bindings:{...base,ISOLATED_EXECUTION_IMAGE:`registry.cloudflare.com/${'a'.repeat(32)}/synthetic@sha256:${'b'.repeat(64)}`},compatibilityDate:'2026-10-04',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'AutoIntegrationControllerFixture',useSQLite:true},UNTRUSTED_EXECUTION:{className:'UntrustedExecutionSandbox',useSQLite:true}},serviceBindings:{VERIFICATION_BROWSER:{name:'c04-controller',entrypoint:'NoBrowser'}}},{name:'c04-missing-resources',modules:true,script,bindings:base,compatibilityDate:'2026-10-04',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'AutoIntegrationControllerFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('c04-controller'),missing=await mf.getWorker('c04-missing-resources');const call=(client:typeof api,name:string,path:string)=>client.fetch(`https://test${path}${path.includes('?')?'&':'?'}case=${name}`);const snapshot=async(client:typeof api,name:string)=>(await(await call(client,name,'/snapshot')).json()) as Snapshot;const settled=async(client:typeof api,name:string,predicate:(value:Snapshot)=>boolean)=>{const deadline=Date.now()+5000;while(Date.now()<deadline){const value=await snapshot(client,name);if(predicate(value))return value;await new Promise(resolve=>setTimeout(resolve,20));}throw Error('Actual controller scheduling did not settle');};
 const seed=async(client:typeof api,name:string)=>{const response=await call(client,name,'/seed');if(!response.ok)throw Error(await response.text());};
 await seed(api,'default');await call(api,'default','/ready?task=one');await call(api,'default','/ready?task=two');expect((await snapshot(api,'default')).creates).toHaveLength(0);
 await seed(api,'cohort');expect((await call(api,'cohort','/configure?actor=member')).status).toBe(409);expect((await call(api,'cohort','/configure')).status).toBe(200);await call(api,'cohort','/ready?task=one');const held=await settled(api,'cohort',value=>value.activities.some(item=>item.type==='integration.not_started'));expect(held.creates).toHaveLength(0);await call(api,'cohort','/ready?task=two');const complete=await settled(api,'cohort',value=>value.creates.length===1&&value.dispatches[0]?.phase==='observed');expect(complete.creates[0]?.params.taskIds).toEqual(['one','two']);await call(api,'cohort','/ready?task=one');await call(api,'cohort','/ready?task=two');expect((await snapshot(api,'cohort')).creates.map(item=>item.id)).toEqual([complete.creates[0]!.id]);
 await seed(api,'unknown');await call(api,'unknown','/mode?unknown');await call(api,'unknown','/configure');await call(api,'unknown','/ready?task=one');await call(api,'unknown','/ready?task=two');const unknown=await settled(api,'unknown',value=>value.creates.length===1&&value.dispatches[0]?.phase==='held');await call(api,'unknown','/ready?task=one');expect((await snapshot(api,'unknown')).creates).toHaveLength(1);expect(unknown.inspections.every(item=>item.id===unknown.creates[0]!.id)).toBe(true);
 for(const mode of['withdraw','review','missing']){const client=mode==='missing'?missing:api;await seed(client,mode);await call(client,mode,'/configure');if(mode==='withdraw')await call(client,mode,'/withdraw-owner');if(mode==='review')await call(client,mode,'/configure?review');await call(client,mode,'/ready?task=one');await call(client,mode,'/ready?task=two');if(mode!=='review')await settled(client,mode,value=>value.activities.some(item=>item.type==='integration.not_started'));expect((await snapshot(client,mode)).creates).toHaveLength(0);}
 await seed(api,'observed-predecessor');await call(api,'observed-predecessor','/mode?queued');await call(api,'observed-predecessor','/configure');await call(api,'observed-predecessor','/ready?task=one');await call(api,'observed-predecessor','/ready?task=two');const observedPrior=await settled(api,'observed-predecessor',value=>value.creates.length===1&&value.dispatches[0]?.phase==='observed');expect(observedPrior.dispatches[0]?.observedStatus).toBe('queued');const observedWaits=observedPrior.activities.filter(item=>item.type==='integration.not_started').length;await call(api,'observed-predecessor','/requirements');await call(api,'observed-predecessor','/ready?task=one');await call(api,'observed-predecessor','/ready?task=two');const blockedObserved=await settled(api,'observed-predecessor',value=>value.creates.length>1||value.activities.filter(item=>item.type==='integration.not_started').length>observedWaits);expect(blockedObserved.creates.map(item=>item.id)).toEqual([observedPrior.creates[0]!.id]);expect(blockedObserved.dispatches[0]?.phase).toBe('observed');
 await seed(api,'requirements-race');await call(api,'requirements-race','/mode?requirements');await call(api,'requirements-race','/configure');await call(api,'requirements-race','/ready?task=one');await call(api,'requirements-race','/ready?task=two');const reqRace=await settled(api,'requirements-race',value=>value.creates.length===1&&value.activities.some(item=>item.type==='integration.not_started'));const waits=reqRace.activities.filter(item=>item.type==='integration.not_started').length;await call(api,'requirements-race','/ready?task=one');await call(api,'requirements-race','/ready?task=two');await settled(api,'requirements-race',value=>value.creates.length>1||value.activities.filter(item=>item.type==='integration.not_started').length>waits);expect((await snapshot(api,'requirements-race')).creates.map(item=>item.id)).toEqual([reqRace.creates[0]!.id]);
 await seed(api,'webhook');await call(api,'webhook','/configure');await call(api,'webhook','/webhook');await call(api,'webhook','/mode?webhook');expect((await call(api,'webhook','/ready?task=one')).status).toBe(409);expect((await call(api,'webhook','/ready?task=two')).status).toBe(409);const independent=await settled(api,'webhook',value=>value.creates.length===1&&value.dispatches[0]?.phase==='observed');expect(independent.creates[0]?.params.taskIds).toEqual(['one','two']);
 }finally{await mf.dispose();}
},30000);
