import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
test('native branch authority preserves primary history, denies unauthorized creation, and holds cleanup without claiming success',async()=>{
 if(await workerdChild('tests/branch-authority-native.test.ts'))return;
 const output=`/tmp/flaregit-branch-authority-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/branch-authority-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'branch-authority',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'BranchAuthorityFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('branch-authority'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})});expect((await call('/seed')).status).toBe(200);
 const request={operationId:crypto.randomUUID(),name:'feature',sourceCommit:'a'.repeat(40)};expect((await call('/create?actor=member',request)).status).toBe(409);
 const inventory=await call('/inventory?actor=member');if(!inventory.ok)throw Error(await inventory.text());expect(await inventory.json()).toMatchObject({providerVerified:true,branches:[{name:'main',ref:'refs/heads/main',commit:'a'.repeat(40)}]});
 const created=await(await call('/create',request)).json();expect(created).toMatchObject({phase:'confirmed',cleanup:{nativeState:'stopped',credentialStatus:'revoked',recoveryRequired:false}});expect(await(await call('/state')).json()).toEqual({accepted:'a'.repeat(40),pushes:1});expect(await(await call('/create',request)).json()).toEqual(created);expect((await call('/reconcile?id='+request.operationId)).status).toBe(200);
 const beforeRace=await(await call('/stats')).json();await call('/race');const stoppedRequest={operationId:crypto.randomUUID(),name:'stopped-before-token',sourceCommit:'a'.repeat(40)};expect(await(await call('/create',stoppedRequest)).json()).toMatchObject({phase:'prepared',cleanup:{nativeState:'stopped',credentialStatus:'not_issued'}});expect(await(await call('/stats')).json()).toEqual(beforeRace);expect(await(await call('/abandon?id='+stoppedRequest.operationId)).json()).toMatchObject({phase:'refused',reason:'owner_abandoned_prepared'});
 const invalid={operationId:crypto.randomUUID(),name:'invalid-source',sourceCommit:'b'.repeat(40)};expect(await(await call('/create',invalid)).json()).toMatchObject({phase:'prepared',cleanup:{recoveryRequired:false}});expect(await(await call('/abandon?id='+invalid.operationId)).json()).toMatchObject({phase:'refused',reason:'owner_abandoned_prepared'});
 await call('/mode?stop=false&revoke=false');expect((await call('/inventory?actor=member')).status).toBe(409);const held=await(await call('/recoveries')).json() as {attempts:Array<{attemptId:string;operationId:string;kind:string}>};const pending=held.attempts.find(row=>row.kind==='inventory');expect(pending).toBeDefined();await call('/mode');const cleanup=await(await call('/cleanup',pending)).json();expect(cleanup).toMatchObject({nativeStopped:true,credentialsComplete:true});expect(await(await call('/state')).json()).toEqual({accepted:'a'.repeat(40),pushes:1});
 await call('/mode?stop=false&revoke=false');const uncertain={operationId:crypto.randomUUID(),name:'pending',sourceCommit:'a'.repeat(40)};expect(await(await call('/create',uncertain)).json()).toMatchObject({phase:'unknown',cleanup:{recoveryRequired:true}});expect((await call('/abandon?id='+uncertain.operationId)).status).toBe(409);expect(await(await call('/reconcile?id='+uncertain.operationId)).json()).toMatchObject({phase:'unknown'});
 await call('/mode');const recovered=await(await call('/reconcile?id='+uncertain.operationId)).json();expect(recovered).toMatchObject({phase:'confirmed',cleanup:{recoveryRequired:false}});expect(await(await call('/state')).json()).toEqual({accepted:'a'.repeat(40),pushes:2});
 const unfinished={operationId:crypto.randomUUID(),name:'unfinished-source',sourceCommit:'b'.repeat(40)};await call('/create',unfinished);await call('/finished-history');const collection=await(await call('/operations')).json() as {operations:Array<{operationId:string}>;pendingTruncated:boolean;historyHasMore:boolean};expect(collection).toMatchObject({pendingTruncated:false,historyHasMore:true});expect(collection.operations[0]?.operationId).toBe(unfinished.operationId);
 }finally{await mf.dispose();}
},30000);
