import {afterEach,expect,test} from 'bun:test';import {acceptedBranchSelection,branchIntent,checkedBranchInventory,checkedBranchOperation,createBranchReference,observedBranchSelection,readBranchOperation} from '../src/web/branch-browser';
const originalFetch=globalThis.fetch;afterEach(()=>{globalThis.fetch=originalFetch;});
const accepted='a'.repeat(40),observed='b'.repeat(40),value={branches:[{name:'main',ref:'refs/heads/main',commit:observed},{name:'feature/topic',ref:'refs/heads/feature/topic',commit:observed}],truncated:false,defaultBranch:'main',acceptedCommit:accepted,providerVerified:true};
const operation={operationId:'12345678-1234-4234-8234-123456789abc',projectId:'repository',branch:'feature/new',sourceCommit:accepted,acceptedCommit:accepted,phase:'unknown' as const,createdAt:1000,cleanup:{nativeState:'stopped' as const,credentialStatus:'revoked' as const,recoveryRequired:false}};
test('observed branch tips pin browsing without replacing primary accepted history',()=>{const inventory=checkedBranchInventory(value);expect(acceptedBranchSelection(inventory)).toEqual({name:'main',commit:accepted,accepted:true});expect(observedBranchSelection(inventory,inventory.branches[0]!)).toEqual({name:'main',commit:observed,accepted:false});expect(observedBranchSelection(inventory,inventory.branches[1]!).commit).toBe(observed);expect(inventory.acceptedCommit).toBe(accepted);expect(()=>observedBranchSelection(inventory,{...inventory.branches[0]!,commit:'c'.repeat(40)})).toThrow();expect(()=>checkedBranchInventory({...value,branches:[{...value.branches[0]!,ref:'refs/heads/another'}]})).toThrow();expect(()=>checkedBranchInventory({...value,providerVerified:false})).toThrow();});
test('creation intent is exact and stable while changed source or repository receives a new ID',()=>{const intent=branchIntent(null,'repository','feature/new',accepted);expect(branchIntent(intent,'repository','feature/new',accepted)).toBe(intent);expect(branchIntent(intent,'repository','feature/new',observed).operationId).not.toBe(intent.operationId);expect(branchIntent(intent,'another','feature/new',accepted).operationId).not.toBe(intent.operationId);for(const name of ['refs/heads/new','bad..name','name with spaces'])expect(()=>branchIntent(null,'repository',name,accepted)).toThrow();expect(()=>checkedBranchOperation({...operation,phase:'confirmed'},undefined,'repository')).toThrow();expect(()=>checkedBranchOperation(operation,undefined,'another')).toThrow();});
test('read-only saved status never repeats a branch creation push',async()=>{globalThis.fetch=Object.assign(async(url:string|URL|Request,init?:RequestInit)=>{expect(url).toBe('/api/p/repository/branch-operations/'+operation.operationId);expect(init?.method??'GET').toBe('GET');expect(init?.body).toBeUndefined();return Response.json(operation);},{preconnect:originalFetch.preconnect});expect((await readBranchOperation('repository',operation,AbortSignal.timeout(15000))).phase).toBe('unknown');});
test('unknown creation acknowledgements reuse exact operation IDs without changing accepted history',async()=>{const intent=branchIntent(null,'repository',operation.branch,accepted),requests:unknown[]=[];globalThis.fetch=Object.assign(async(url:string|URL|Request,init?:RequestInit)=>{expect(url).toBe('/api/p/repository/branches');expect(init?.method).toBe('POST');requests.push(JSON.parse(String(init?.body)));throw Error('Lost acknowledgement');},{preconnect:originalFetch.preconnect});for(let index=0;index<2;index++)await expect(createBranchReference('repository',intent,AbortSignal.timeout(30000))).rejects.toThrow();expect(requests).toEqual([{operationId:intent.operationId,name:operation.branch,sourceCommit:accepted},{operationId:intent.operationId,name:operation.branch,sourceCommit:accepted}]);expect(JSON.stringify(requests)).not.toContain('defaultBranch');});

import {reconcileBranchReference} from '../src/web/branch-browser';
test('uncertain branch reconciliation sends only the unknown-phase guard, never another creation payload',async()=>{globalThis.fetch=Object.assign(async(url:string|URL|Request,init?:RequestInit)=>{expect(url).toBe('/api/p/repository/branch-operations/'+operation.operationId+'/reconcile');expect(init?.method).toBe('POST');expect(JSON.parse(String(init?.body))).toEqual({expectedPhase:'unknown'});return Response.json(operation);},{preconnect:originalFetch.preconnect});expect((await reconcileBranchReference('repository',operation,AbortSignal.timeout(30000))).phase).toBe('unknown');await expect(reconcileBranchReference('repository',{...operation,phase:'prepared'},AbortSignal.timeout(30000))).rejects.toThrow('uncertain');});

import {abandonPreparedBranch,cleanupBranchExecution} from '../src/web/branch-browser';
test('prepared abandonment and explicit cleanup retain exact recorded IDs and reject uncertain abandonment',async()=>{const prepared={...operation,phase:'prepared' as const};globalThis.fetch=Object.assign(async(url:string|URL|Request,init?:RequestInit)=>{expect(url).toBe('/api/p/repository/branch-operations/'+operation.operationId+'/abandon');expect(JSON.parse(String(init?.body))).toEqual({expectedPhase:'prepared'});return Response.json({...prepared,phase:'refused',reason:'owner_abandoned_prepared'});},{preconnect:originalFetch.preconnect});expect((await abandonPreparedBranch('repository',prepared,AbortSignal.timeout(15000))).reason).toBe('owner_abandoned_prepared');await expect(abandonPreparedBranch('repository',operation,AbortSignal.timeout(15000))).rejects.toThrow('undispatched');const attempt={attemptId:'22345678-1234-4234-8234-123456789abc',operationId:operation.operationId,kind:'create' as const,nativeState:'possible' as const,executionEnded:false,createdAt:1000,credentialStatus:'pending' as const};globalThis.fetch=Object.assign(async(url:string|URL|Request,init?:RequestInit)=>{expect(url).toBe('/api/p/repository/branch-runtime/recovery');expect(JSON.parse(String(init?.body))).toEqual({attemptId:attempt.attemptId,operationId:attempt.operationId,confirmStop:true});return Response.json({attemptId:attempt.attemptId,operationId:attempt.operationId,nativeStopped:false,credentialsComplete:true},{status:202});},{preconnect:originalFetch.preconnect});expect((await cleanupBranchExecution('repository',attempt,AbortSignal.timeout(30000))).nativeStopped).toBe(false);});
