import{expect,test}from'bun:test';import{Miniflare,convertV4MiniflareOptions}from'miniflare';
import{workerdChild}from'./support/workerd-child';import type{CoreGitCapacity}from'../src/server/core-git-budget';
test('fresh HTTP branch reads and credential cleanup use protected read capacity with write fully exhausted',async()=>{
 if(await workerdChild('tests/branch-read-budget-native.test.ts'))return;
 const build=await Bun.build({entrypoints:['tests/support/branch-authority-worker.ts'],target:'browser',external:['cloudflare:workers','node:*']});if(!build.success)throw Error('Fixture build failed');
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'branch-read-budget',modules:true,script:await build.outputs[0]!.text(),compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],bindings:{CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'13200',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'13200',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'12000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'12000'},durableObjects:{REPOSITORY_CONTROLLER:{className:'BranchAuthorityFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('branch-read-budget'),call=(path:string)=>api.fetch(`https://fixture${path}`,{method:'POST'}),capacity=async()=>await(await call('/budget-capacity')).json() as CoreGitCapacity;
 expect((await call('/seed')).status).toBe(200);expect(await(await call('/fund-core')).json()).toMatchObject({allowed:true});const before=await capacity();expect(before.core).toMatchObject({remainingUsdMicros:0,accountReserved:1200});expect(before.read.accountReserved).toBe(0);
 const inventory=await call('/inventory');if(!inventory.ok)throw Error(await inventory.text());expect(await inventory.json()).toMatchObject({providerVerified:true,branches:[{name:'main',ref:'refs/heads/main',commit:'a'.repeat(40)}]});
 const after=await capacity();expect(after.core).toEqual(before.core);expect(after.read.accountReserved).toBe(6000);expect(after.accountReserved).toBe(before.accountReserved+6000);expect(await(await call('/stats')).json()).toEqual({minted:1,commands:0});expect(await(await call('/recoveries')).json()).toMatchObject({attempts:[],inspections:[{outcome:'complete',credentialStatus:'revoked',nativeState:'not_allocated'}]});expect(await(await call('/fund-core')).json()).toMatchObject({allowed:false});
 await call('/exhaust-read');const exhausted=await capacity();expect(exhausted.read.remainingUsdMicros).toBe(0);expect((await call('/inventory')).status).toBe(409);expect(await capacity()).toEqual(exhausted);expect(await(await call('/stats')).json()).toEqual({minted:1,commands:0});expect(await(await call('/recoveries')).json()).toMatchObject({attempts:[],inspections:[{outcome:'failed',failureStage:'funding',credentialStatus:'not_issued',nativeState:'not_allocated'},{outcome:'complete',credentialStatus:'revoked',nativeState:'not_allocated'}]});
 }finally{await mf.dispose();}
},30000);
