import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {CandidateGeneration,PublicationJournalEntry,FlareGitProjectState} from '../src/core/types';
import type {PrivateRecoveryTarget,PrivateRecoveryOperation} from '../src/server/private-recovery';
test('native branch recovery separates equal commits by exact accepted journal/ref, preserves old receipt scope, and never grants public primary consent',async()=>{
 if(await workerdChild('tests/branch-private-recovery-native.test.ts'))return;
 const output=`/tmp/flaregit-branch-private-recovery-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/branch-private-recovery-native-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:'1000000',MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:'2000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'recovery',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'BranchPrivateRecoveryFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('recovery'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})}),json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body),value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 await json('/seed');for(const name of ['release','staging'])await json('/create',{operationId:crypto.randomUUID(),name,sourceCommit:'a'.repeat(40)});const before=(await json<FlareGitProjectState>('/state-full')).acceptedState;
 async function accept(taskId:string,ref:string){await json('/target-task',{id:taskId,ref});const {candidate}=await json<{candidate:CandidateGeneration}>('/landing',{tasks:[taskId],holder:`landing-${taskId}`});await json('/verify-target',{id:candidate.id,bind:true,commit:'b'.repeat(40)});const target=candidate.acceptedTarget!;await json('/review-target',{id:candidate.id,commit:'b'.repeat(40),target:{ref:target.ref,acceptedCommit:target.acceptedCommit,acceptedVersion:target.acceptedVersion}});const prepared=await json<{ok:boolean;journal:PublicationJournalEntry}>('/prepare?id='+candidate.id);if(!prepared.ok)throw Error('Publication preparation unavailable');await json('/complete-target',{journalId:prepared.journal.id});return prepared.journal;}
 const release=await accept('release-task','refs/heads/release'),staging=await accept('staging-task','refs/heads/staging');expect((await json<FlareGitProjectState>('/state-full')).acceptedState).toEqual(before);const targets=await json<PrivateRecoveryTarget[]>('/recovery-targets');expect(targets.filter(target=>target.commit===release.newHead)).toHaveLength(2);const id=crypto.randomUUID();expect((await call('/prepare-recovery',{id,commit:release.newHead,tree:release.candidateTree})).ok).toBe(false);
 const releaseScope={journalId:release.id,acceptedRef:'refs/heads/release',acceptedRootVersion:1},stagingScope={journalId:staging.id,acceptedRef:'refs/heads/staging',acceptedRootVersion:1};const operation=await json<PrivateRecoveryOperation>('/prepare-recovery',{id,commit:release.newHead,tree:release.candidateTree,selected:releaseScope});expect(operation).toMatchObject(releaseScope);expect(await json<boolean>('/authorize-recovery?id='+id)).toBe(true);expect((await call('/prepare-recovery',{id,commit:release.newHead,tree:release.candidateTree,selected:stagingScope})).ok).toBe(false);expect((await call('/complete-recovery',{id,wrongRef:true})).ok).toBe(false);const ready=await json<PrivateRecoveryOperation>('/complete-recovery',{id});expect(ready.receipt).toMatchObject(releaseScope);expect(await json<boolean>('/readable-recovery?id='+id)).toBe(true);expect(await json<unknown>('/prepare-recovery',{id,commit:release.newHead,tree:release.candidateTree,selected:releaseScope})).toEqual(ready);
 const stagingId=crypto.randomUUID();expect(await json('/prepare-recovery',{id:stagingId,commit:staging.newHead,tree:staging.candidateTree,selected:stagingScope})).toMatchObject(stagingScope);
 const primary=await accept('primary-task','refs/heads/main');expect(await json('/public-sharing-proof')).toMatchObject({target:null});await json('/retire-recovery?id='+stagingId);const legacyId=crypto.randomUUID();const legacy=await json<PrivateRecoveryOperation>('/legacy-recovery',{id:legacyId,journalId:primary.id});expect(legacy.acceptedRef).toBeUndefined();const replay=await json<PrivateRecoveryOperation>('/prepare-recovery',{id:legacyId,commit:legacy.commit,tree:legacy.tree,selected:{journalId:primary.id}});expect(replay).toEqual(legacy);expect(await json<boolean>('/authorize-recovery?id='+legacyId)).toBe(true);
 }finally{await mf.dispose();}
},30000);
