import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {BranchCredentialIncidents,type BranchCredentialIdentity} from "../src/server/branch-credential-incidents";
function fixture(){const db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};return{db,ledger:new BranchCredentialIncidents(storage as unknown as DurableObjectStorage)};}
function identity(kind:"inventory"|"create"="inventory"):BranchCredentialIdentity{return{attemptId:crypto.randomUUID(),operationId:crypto.randomUUID(),nativeId:crypto.randomUUID(),kind,projectId:"p123456789abc",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical-fixture",actorId:"owner",accountKey:"a".repeat(12),snapshotDigest:"b".repeat(64)};}
test("branch issuance requires exact genuine operation/native context and current authority before provider issuance",async()=>{
 const{db,ledger}=fixture(),scope=identity();expect(()=>ledger.begin(scope,61000,()=>{throw Error("Owner withdrew");},1000)).toThrow("Owner withdrew");expect(db.query("SELECT COUNT(*) AS n FROM branch_credential_incidents").get()).toEqual({n:0});await expect(ledger.record(scope.attemptId,scope.canonicalRepoName,"synthetic-secret",61000,"read")).rejects.toThrow("issuance intent");expect(ledger.begin(scope,61000,()=>{},1000)).toBe(true);expect(ledger.begin(scope,61000,()=>{},1000)).toBe(false);for(const change of [{nativeId:crypto.randomUUID()},{operationId:crypto.randomUUID()},{incarnation:crypto.randomUUID()},{actorId:"different"},{canonicalRepoName:"other"},{accountKey:"other"},{snapshotDigest:"c".repeat(64)},{kind:"create" as const}])expect(()=>ledger.begin({...scope,...change},61000,()=>{},1000)).toThrow("intent changed");expect(()=>ledger.begin(scope,61001,()=>{},1000)).toThrow("intent");expect(ledger.summary(scope.attemptId)?.status).toBe("issuance_unknown");expect(ledger.hasPending()).toBe(true);expect(ledger.credentialForUse(scope,1000)).toBeNull();db.close();
});
test("branch receipts survive authority withdrawal, enforce scope before use and require exact revocation proof",async()=>{
 const{db,ledger}=fixture(),scope=identity("create");ledger.begin(scope,61000,()=>{},1000);await ledger.record(scope.attemptId,scope.canonicalRepoName,"synthetic-secret",61000,"write");expect(ledger.credentialForUse(scope,2000)?.scope).toBe("write");expect(ledger.credentialForUse({...scope,nativeId:crypto.randomUUID()},2000)).toBeNull();expect(JSON.stringify(ledger.summary(scope.attemptId))).not.toContain("synthetic-secret");expect(JSON.stringify(ledger.summary(scope.attemptId))).not.toContain(scope.accountKey);expect(ledger.credentialForUse(scope,61000)).toBeNull();expect(ledger.credentialForRevocation(scope.attemptId)?.token).toBe("synthetic-secret");await expect(ledger.markRevoked(scope.attemptId,"wrong")).rejects.toThrow("receipt differs");await ledger.markRevoked(scope.attemptId,"synthetic-secret");expect(ledger.hasPending()).toBe(false);expect(db.query("SELECT token FROM branch_credential_incidents").get()).toEqual({token:null});await ledger.record(scope.attemptId,scope.canonicalRepoName,"synthetic-secret",61000,"write");expect(ledger.summary(scope.attemptId)?.status).toBe("revoked");expect(ledger.credentialForUse(scope,2000)).toBeNull();db.close();
});
test("malformed provider expiry or mismatched scope stays recoverable but never usable",async()=>{
 const{db,ledger}=fixture();for(const [expiry,providerScope] of [[NaN,"read"],[61000,"write"],[1000000,"read"],[61000,"unknown"]] as const){const scope=identity();ledger.begin(scope,61000,()=>{},1000);await ledger.record(scope.attemptId,scope.canonicalRepoName,"synthetic-secret",expiry,providerScope);expect(ledger.credentialForUse(scope,2000)).toBeNull();expect(ledger.credentialForRevocation(scope.attemptId)?.repoName).toBe(scope.canonicalRepoName);expect(ledger.summary(scope.attemptId)?.status).toBe("pending");}expect(ledger.hasPending()).toBe(true);db.close();
});
test("bounded automatic cleanup preserves unknown outcomes and the unresolved audit after exhausted retries",async()=>{
 const{db,ledger}=fixture(),scope=identity();ledger.begin(scope,61000,()=>{},1000);await ledger.record(scope.attemptId,scope.canonicalRepoName,"synthetic-secret",61000,"read");for(let attempt=0;attempt<4;attempt++){expect(ledger.markAutomaticSweep(scope.attemptId)).toBe(true);expect(ledger.markAttempt(scope.attemptId)).toBe(true);}expect(ledger.markAutomaticSweep(scope.attemptId)).toBe(false);expect(ledger.pendingBatch()).toEqual([]);expect(ledger.nextWake(1000000)).toBeNull();expect(ledger.hasPending()).toBe(true);expect(ledger.markAttempt(scope.attemptId)).toBe(false);expect(ledger.credentialForRevocation(scope.attemptId)).toBeNull();await ledger.markRevoked(scope.attemptId,"synthetic-secret");expect(ledger.hasPending()).toBe(false);db.close();
});

test('fingerprint failure cannot lose returned branch key or its positive revocation after authority withdrawal',async()=>{const{db,ledger}=fixture(),scope=identity('create'),original=crypto.subtle.digest.bind(crypto.subtle);let allowed=true;const authorize=()=>{if(!allowed)throw Error('owner withdrawn');};ledger.begin(scope,61000,authorize,1000);allowed=false;expect(()=>ledger.begin(scope,61000,authorize,1000)).toThrow('owner withdrawn');try{crypto.subtle.digest=async()=>{throw Error('owned digest interruption');};await expect(ledger.record(scope.attemptId,scope.canonicalRepoName,'synthetic-fault-key',61000,'write')).rejects.toThrow('digest interruption');expect(ledger.credentialForRevocation(scope.attemptId)?.token).toBe('synthetic-fault-key');await ledger.markRevoked(scope.attemptId,'synthetic-fault-key');expect(ledger.summary(scope.attemptId)?.status).toBe('revoked');expect(ledger.credentialForUse(scope,2000)).toBeNull();crypto.subtle.digest=original;await ledger.record(scope.attemptId,scope.canonicalRepoName,'synthetic-fault-key',61000,'write');expect(db.query('SELECT token,status FROM branch_credential_incidents').get()).toEqual({token:null,status:'revoked'});await expect(ledger.record(scope.attemptId,scope.canonicalRepoName,'other-key',61000,'write')).rejects.toThrow('receipt changed');}finally{crypto.subtle.digest=original;db.close();}});
