import {test,expect} from "bun:test";
import {Database} from "bun:sqlite";
import {mkdtemp,mkdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {gitOrThrow,PLATFORM_IDENTITY} from "../src/core/pipeline/git";
import {BranchCreationOperations,type BranchCreationIdentity} from "../src/server/branch-creation-operations";
import {createNativeBranch,inspectNativeBranches,parseBranchInventory} from "../src/server/branch-git";
test("real Git create-only branches prove accepted ancestry, preserve existing refs and recover a lost push response",async()=>{
 const root=await mkdtemp(join(tmpdir(),"flaregit-branch-create-")),seed=join(root,"seed"),canonical=join(root,"repo.git"),db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage,ledger=new BranchCreationOperations(storage);
 try{await mkdir(seed);gitOrThrow(seed,["init","-b","codex/imported"]);await Bun.write(join(seed,"README.md"),"Accepted\n");gitOrThrow(seed,["add","."]);gitOrThrow(seed,[...PLATFORM_IDENTITY,"commit","-m","Base"]);const accepted=gitOrThrow(seed,["rev-parse","HEAD"]);gitOrThrow(root,["init","--bare",canonical]);gitOrThrow(seed,["push",canonical,`${accepted}:refs/heads/codex/imported`]);const remote="https://"+"a".repeat(32)+".artifacts.cloudflare.net/repo.git";const identity:BranchCreationIdentity={operationId:crypto.randomUUID(),projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"repo",actorId:"owner",accountKey:"account",branch:"release/one",sourceCommit:accepted,acceptedCommit:accepted};let losePush=true;const executor={beforeCommand:async()=>{},exec:async(command:string)=>{const child=Bun.spawn(["sh","-c",command.replaceAll(remote,canonical)],{stdout:"pipe",stderr:"pipe"});const [stdout,code]=await Promise.all([new Response(child.stdout).text(),child.exited]);if(command.includes(" push ")&&losePush){losePush=false;return{success:false,stdout:""};}return{success:code===0,stdout};}};ledger.prepare(identity,()=>{});const markDispatch=async()=>{ledger.markDispatch(identity,()=>{});};const result=await createNativeBranch(executor,{identity,remote,token:"synthetic",directory:join(root,"create.git"),dispatch:"prepared",markDispatch});expect(result.status).toBe("confirmed");ledger.observe(identity,result.observedCommit!,()=>{});expect(ledger.get(identity.operationId)?.phase).toBe("confirmed");expect((await inspectNativeBranches(executor,remote,"synthetic",1)).truncated).toBe(true);expect((await inspectNativeBranches(executor,remote,"synthetic")).branches.map(row=>row.name)).toEqual(["codex/imported","release/one"]);expect((await inspectNativeBranches(executor,remote,"synthetic")).branches.every(row=>row.ref===`refs/heads/${row.name}`)).toBe(true);expect((await createNativeBranch(executor,{identity,remote,token:"synthetic",directory:join(root,"retry.git"),dispatch:"unknown",markDispatch})).status).toBe("confirmed");expect((await createNativeBranch(executor,{identity,remote,token:"synthetic",directory:join(root,"retry.git"),dispatch:"prepared",markDispatch})).status).toBe("existing");expect((await createNativeBranch(executor,{identity:{...identity,branch:"unknown-missing"},remote,token:"synthetic",directory:join(root,"never.git"),dispatch:"unknown",markDispatch:async()=>{throw Error("No redispatch");}})).status).toBe("unknown");expect(()=>ledger.prepare({...identity,branch:"changed"},()=>{})).toThrow("identity");
 const unrelated=gitOrThrow(seed,[...PLATFORM_IDENTITY,"commit-tree",gitOrThrow(seed,["rev-parse","HEAD^{tree}"]),"-m","Outside accepted closure"]);gitOrThrow(seed,["push",canonical,`${unrelated}:refs/heads/unaccepted`]);const unaccepted={...identity,operationId:crypto.randomUUID(),branch:"forbidden",sourceCommit:unrelated};await expect(createNativeBranch(executor,{identity:unaccepted,remote,token:"synthetic",directory:join(root,"unrelated.git"),dispatch:"prepared",markDispatch:async()=>{throw Error("Should never dispatch");}})).rejects.toThrow("unavailable");expect(gitOrThrow(canonical,["rev-parse","refs/heads/codex/imported"],{gitDir:true})).toBe(accepted);expect(gitOrThrow(canonical,["rev-parse","refs/heads/release/one"],{gitDir:true})).toBe(accepted);expect(gitOrThrow(canonical,["for-each-ref","--format=%(refname)","refs/heads/forbidden"],{gitDir:true})).toBe("");
 }finally{db.close();await rm(root,{recursive:true,force:true});}
});
test("inventory is bounded and refuses malformed/duplicate ref evidence",()=>{const head="a".repeat(40);expect(parseBranchInventory(`${head}\trefs/heads/a\n${head}\trefs/heads/b\n`,1)).toEqual({branches:[{name:"a",ref:"refs/heads/a",commit:head}],truncated:true});expect(()=>parseBranchInventory(`${head}\trefs/heads/a\n${head}\trefs/heads/a\n`)).toThrow();expect(()=>parseBranchInventory(`${head}\trefs/tags/v1\n`)).toThrow();expect(()=>parseBranchInventory("x".repeat(1024*1024+1))).toThrow("limit");});
