import {test,expect} from 'bun:test';
import {Database} from 'bun:sqlite';
import {BrowserEdits,browserEditBytes,browserEditSchema,publishBrowserEdit,type BrowserEditIdentity,type BrowserEditRecord} from '../src/server/browser-edit';
import type {BranchGitExecutor} from '../src/server/branch-git';
import {ForkPermissions,type ForkPermissionScope} from '../src/server/fork-permissions';
const sha='a'.repeat(40),tree='b'.repeat(40),blob='c'.repeat(40),commit='d'.repeat(40);
function identity():BrowserEditIdentity{return {projectId:'project',incarnation:crypto.randomUUID(),canonicalRepoName:'canonical',taskId:'browser-contribution',workspaceRepoName:'private-fork',providerRepoId:'original-provider-repository',remote:'https://0123456789abcdef0123456789abcdef.artifacts.cloudflare.net/repository.git',branch:'task/browser-contribution',actorId:'human',authorName:'Human',authorEmail:'human@users.flaregit.invalid',createdAt:'2026-10-08T12:00:00.000Z',input:{requestId:crypto.randomUUID(),expectedHead:sha,expectedTree:tree,path:'src/app.ts',expectedBlob:null,contentBase64:'aGVsbG8=',contentSha256:'2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824',message:'Edit source'}};}
function storage(db:Database){return {sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(action:()=>T){return db.transaction(action)();}} as unknown as DurableObjectStorage;}
test('browser upload binds content bytes and rejects unsafe Git metadata paths',async()=>{const original=identity().input;expect((await browserEditBytes(original)).bytes).toEqual(new TextEncoder().encode('hello'));await expect(browserEditBytes({...original,contentBase64:'dGFtcGVyZWQ='})).rejects.toThrow('digest differs');await expect(browserEditBytes({...original,path:'.git/config'})).rejects.toThrow('Unsafe');expect(browserEditSchema.safeParse({...original,force:true}).success).toBe(false);});
test('saved browser edit identity prevents actor, target and lost-ack content substitution',()=>{const db=new Database(':memory:');try{const ledger=new BrowserEdits(storage(db)),original=identity();ledger.prepare(original,blob,()=>{});expect(ledger.prepare(original,blob,()=>{}).phase).toBe('prepared');for(const changed of [{...original,actorId:'intruder'},{...original,workspaceRepoName:'canonical'},{...original,input:{...original.input,message:'Replace original'}}])expect(()=>ledger.prepare(changed,blob,()=>{})).toThrow();ledger.update(original,value=>{value.commit=commit;value.tree=tree;value.phase='push_unknown';},()=>{});expect(ledger.get(original.input.requestId)?.commit).toBe(commit);expect(()=>ledger.update(original,value=>{value.phase='confirmed';},()=>{throw Error('Access revoked');})).toThrow('revoked');expect(ledger.get(original.input.requestId)?.phase).toBe('push_unknown');}finally{db.close();}});
test('unknown browser push only observes original task ref and never writes another commit',async()=>{const original=identity(),commands:string[]=[],record:BrowserEditRecord={identity:original,blob,commit,tree,phase:'push_unknown'},executor:BranchGitExecutor={async beforeCommand(){},async exec(command){commands.push(command);return {success:true,stdout:`${commit}\trefs/heads/${original.branch}\n`};}};const result=await publishBrowserEdit(executor,record,'private-token',async()=>{throw Error('No proposal on retry');},async()=>{throw Error('No dispatch on retry');});expect(result.confirmed).toBe(true);expect(commands).toHaveLength(1);expect(commands[0]).toContain('ls-remote');expect(commands[0]).not.toContain('private-token');expect(commands[0]).not.toContain('refs/heads/main');});
test('edited content is committed in a bare fork then marked unknown before a leased push',async()=>{const original=identity(),commands:string[]=[],events:string[]=[],record:BrowserEditRecord={identity:original,blob,phase:'prepared'};let pushed=false;const executor:BranchGitExecutor={async beforeCommand(){},async exec(command){commands.push(command);if(command.includes('ls-remote'))return {success:true,stdout:pushed?`${commit}\trefs/heads/${original.branch}\n`:''};if(command.includes('rev-parse'))return {success:true,stdout:tree};if(command.includes('ls-tree'))return {success:true,stdout:''};if(command.includes('hash-object'))return {success:true,stdout:blob};if(command.includes('write-tree'))return {success:true,stdout:tree};if(command.includes('commit-tree'))return {success:true,stdout:commit};if(command.includes('push ')){events.push('push');pushed=true;return {success:false,stdout:''};}return {success:true,stdout:''};}};const result=await publishBrowserEdit(executor,record,'private-token',async(saved)=>{expect(saved).toBe(commit);events.push('proposal');},async()=>{events.push('unknown');});expect(result.confirmed).toBe(true);expect(events).toEqual(['proposal','unknown','push']);expect(commands.join('\n')).toContain('init --quiet --bare');expect(commands.join('\n')).not.toContain('checkout');expect(commands.join('\n')).not.toContain('refs/heads/main');expect(commands.find(command=>command.includes('push '))).toContain('--force-with-lease=');});
test('maintainer browser intent preserves its original consent epoch across revocation and regrant',async()=>{
  const db=new Database(':memory:');
  try{
    const database=storage(db),permissions=new ForkPermissions(database),edits=new BrowserEdits(database),original=identity();
    const scope:ForkPermissionScope={projectId:original.projectId,incarnation:original.incarnation,taskId:original.taskId,repoName:original.workspaceRepoName,branch:original.branch,creatorId:'original-creator'};
    permissions.update(scope,scope.creatorId,0,true,()=>{});
    const source=permissions.source(scope)!;
    const maintainer={...original,actorId:'maintainer',maintainerWriteSource:source},record=edits.prepare(maintainer,blob,()=>permissions.assert(scope,source)),commands:string[]=[];
    const executor:BranchGitExecutor={async beforeCommand(){permissions.assert(scope,record.identity.maintainerWriteSource!);},async exec(command){commands.push(command);permissions.update(scope,scope.creatorId,source.revision,false,()=>{});permissions.update(scope,scope.creatorId,source.revision+1,true,()=>{});return {success:true,stdout:''};}};
    await expect(publishBrowserEdit(executor,record,'private-token',async()=>{throw Error('Revoked epoch cannot save a proposal');},async()=>{throw Error('Revoked epoch cannot dispatch');})).rejects.toThrow('revoked or changed');
    expect(commands).toHaveLength(1);expect(commands[0]).toContain('ls-remote');
    expect(permissions.read(scope)).toEqual({enabled:true,revision:3});
    const uncertain:BrowserEditRecord={...record,phase:'push_unknown',commit};
    await expect(publishBrowserEdit(executor,uncertain,'private-token',async()=>{throw Error('Unknown retry cannot propose');},async()=>{throw Error('Unknown retry cannot dispatch');})).rejects.toThrow('revoked or changed');
    expect(commands).toHaveLength(1);
    expect(edits.get(maintainer.input.requestId)?.identity.maintainerWriteSource).toEqual(source);
    expect(()=>edits.update(maintainer,value=>{value.phase='confirmed';value.commit=commit;},()=>permissions.assert(scope,source))).toThrow('revoked or changed');
    expect(edits.get(maintainer.input.requestId)?.phase).toBe('prepared');
    const replacement={...maintainer,maintainerWriteSource:permissions.source(scope)!};
    expect(()=>edits.prepare(replacement,blob,()=>{})).toThrow('different content or contribution');
    permissions.assert(scope,replacement.maintainerWriteSource);
    expect(edits.prepare({...replacement,input:{...replacement.input,requestId:crypto.randomUUID()}},blob,()=>permissions.assert(scope,replacement.maintainerWriteSource)).phase).toBe('prepared');
  }finally{db.close();}
});
