import {test,expect} from 'bun:test';
import {forwardC02NetworkControl,matchC02NetworkControl} from '../src/server/c02-network-control';
import {type C02NetworkProbePlan} from '../src/server/c02-network-probe';
const scope={requestId:'3480027c-e83e-4227-8818-72f15b25e0e6',instanceId:'native_1',probeId:'4480027c-e83e-4227-8818-72f15b25e0e6'},props={scope,interceptorId:'hook_1'};
const plan:C02NetworkProbePlan={scope,createdAt:1000,deadlineAt:2000,maxContainers:1,maxNativeSeconds:120,endpoints:[{channel:'https',receiverId:'owned',url:'https://flaregit-owned-delivery-verifier.simo-988.workers.dev/c02-network/probe',controlNonce:'a'.repeat(64),probeNonce:'b'.repeat(64)}]};
const receipt={scope,channel:'https',receiverId:'owned',nonce:'a'.repeat(64),receivedAt:1400,kind:'control',source:'owned-receiver'} as const;
function request(nonce='a'.repeat(64)){const url=new URL(plan.endpoints[0]!.url);for(const[k,v]of Object.entries({...scope,channel:'https',nonce}))url.searchParams.set(k,v);return new Request(url,{headers:{Authorization:'never-forward',Cookie:'secret'}});}
test('control forwards exact route without caller credentials and validates actual ack',async()=>{const result=await forwardC02NetworkControl(plan,props,props,request(),async (req,options)=>{expect(req.headers.get('Authorization')).toBeNull();expect(req.headers.get('Cookie')).toBeNull();expect(req.redirect).toBe('manual');expect(options.credentials).toBe('omit');return Response.json({acknowledged:true,receipt});},()=>1500);expect(result.receipt).toEqual(receipt);expect(result.response.status).toBe(200);});
test('probe nonce and foreign registration never call fetch',async()=>{let calls=0;for(const [context,req]of [[props,request('b'.repeat(64))],[{...props,interceptorId:'foreign'},request()]] as const){const result=await forwardC02NetworkControl(plan,props,context,req,async()=>{calls++;return Response.json({});},()=>1500);expect(result.receipt).toBeNull();}expect(calls).toBe(0);});
test('duplicate query and expiry rejected',()=>{const url=new URL(request().url);url.searchParams.append('nonce','a'.repeat(64));expect(matchC02NetworkControl(plan,props,props,new Request(url),1500)).toBeNull();expect(matchC02NetworkControl(plan,props,props,request(),2000)).toBeNull();});
test('wrong ack identity, oversized body and redirects cannot become control proof',async()=>{for(const response of [Response.json({acknowledged:true,receipt:{...receipt,nonce:'b'.repeat(64)}}),new Response('x'.repeat(8193)),new Response('',{status:302,headers:{Location:'https://example.com'}})]){const result=await forwardC02NetworkControl(plan,props,props,request(),async()=>response,()=>1500);expect(result.receipt).toBeNull();expect(result.response.status).toBe(403);}});
