import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {refuseC02BoundaryInventory} from '../src/server/c02-boundary-inventory';
import {bindBrowserPolicy,type BrowserPolicy,type BrowserVerificationTransport} from '../src/server/external-browser-verifier';
import {bindBuildManifest,type StaticBuildScope} from '../src/server/static-build-artifact';
async function fixture(){const db=new Database(':memory:');const storage={sql:{exec:(query:string,...bindings:(string|number)[])=>{const rows=db.query(query).all(...bindings);return{toArray:()=>rows}}},transactionSync:<T>(operation:()=>T)=>db.transaction(operation)()} as unknown as DurableObjectStorage;const policy:BrowserPolicy={version:1,deadlineMs:1000,cases:[{id:'required-case',actions:[{kind:'navigate',path:'/'}],assertions:[{query:{kind:'text',selector:'h1'},expected:'Required'}]}]};const{digest}=await bindBrowserPolicy(policy);const scope:StaticBuildScope={attemptId:crypto.randomUUID(),incarnation:crypto.randomUUID(),projectId:'p123456789abc',commit:'a'.repeat(40),tree:'b'.repeat(40),policyDigest:digest};const files=[{path:'index.html',kind:'file' as const,bytes:new TextEncoder().encode('<h1>Wrong</h1>')}];const source=await bindBuildManifest('source',scope,files),output=await bindBuildManifest('static',scope,files,source.digest);let allocations=0,failAuthority=false;const expected={scope,sourceDigest:source.digest,buildDigest:output.digest,policyDigest:digest,cases:[{id:'required-case',assertions:1}]};const guards={expected:async()=>expected,authorize:async()=>{if(failAuthority)throw Error('Authority unavailable')},assertCurrent:()=>{}};const transport:BrowserVerificationTransport={allocate:async()=>{allocations++;throw Error('Must never allocate')},act:async()=>{throw Error('Must never act')},observe:async()=>{throw Error('Must never observe')},close:async()=>{throw Error('Must never close')}};return{db,storage,trusted:{scope,source,sourceFiles:files,output,outputFiles:files,policy,guards},transport,allocations:()=>allocations,failAuthority:()=>{failAuthority=true}};}
test('actual production receipt inventory guard refuses tampered cases before browser allocation and leaves durable table empty',async()=>{const f=await fixture();try{const submittedPolicy={...f.trusted.policy,cases:[{...f.trusted.policy.cases[0]!,id:'fabricated-case'}]};expect(await refuseC02BoundaryInventory({...f,submittedPolicy})).toEqual({receiptGuardRefused:true,untrustedOriginRefused:true,proof:'production-receipt-inventory-guard',productionGitEvidence:false});expect(f.allocations()).toBe(0);expect(f.db.query('SELECT * FROM trusted_browser_receipts').all()).toHaveLength(0);}finally{f.db.close();}});
test('equal untrusted policy remains origin refusal and never claims inventory mismatch proof',async()=>{const f=await fixture();try{expect(await refuseC02BoundaryInventory({...f,submittedPolicy:f.trusted.policy})).toEqual({receiptGuardRefused:false,untrustedOriginRefused:true,proof:'untrusted-origin-admission',productionGitEvidence:false});expect(f.allocations()).toBe(0);expect(f.db.query('SELECT * FROM trusted_browser_receipts').all()).toHaveLength(0);}finally{f.db.close();}});
test('authority failures and inconsistent independent expectation are errors rather than fabricated guard refusal',async()=>{const f=await fixture();try{f.failAuthority();await expect(refuseC02BoundaryInventory({...f,submittedPolicy:f.trusted.policy})).rejects.toThrow('Authority unavailable');expect(f.allocations()).toBe(0);}finally{f.db.close();}const g=await fixture();try{g.trusted.guards.expected=async()=>({scope:g.trusted.scope,sourceDigest:g.trusted.source.digest,buildDigest:g.trusted.output.digest,policyDigest:g.trusted.scope.policyDigest,cases:[{id:'untrusted',assertions:1}]});await expect(refuseC02BoundaryInventory({...g,submittedPolicy:g.trusted.policy})).rejects.toThrow('expected inventory differs');expect(g.allocations()).toBe(0);}finally{g.db.close();}});
