import {test,expect} from 'bun:test';
import {c02BoundaryPlanSchema,deriveC02BoundaryEvidence,type C02BoundaryEvidence,type C02BoundaryPlan} from '../src/server/c02-boundary-evidence';
const taskA={taskId:'3480027c-e83e-4227-8818-72f15b25e0e6',instanceId:'native_a'},taskB={taskId:'4480027c-e83e-4227-8818-72f15b25e0e6',instanceId:'native_b'};
const plan:C02BoundaryPlan={requestId:'5480027c-e83e-4227-8818-72f15b25e0e6',taskA,taskB,taskAMarkerDigest:'a'.repeat(64),supervisorMarkerDigest:'b'.repeat(64),syntheticCredentialDigest:'f'.repeat(64),expectedInventoryDigest:'c'.repeat(64),createdAt:1000,deadlineAt:2000};
function evidence():C02BoundaryEvidence{return{markers:[{source:'trusted-marker-store',owner:'task-a',initialDigest:plan.taskAMarkerDigest,finalDigest:plan.taskAMarkerDigest,readAt:1900},{source:'trusted-marker-store',owner:'supervisor',initialDigest:plan.supervisorMarkerDigest,finalDigest:plan.supervisorMarkerDigest,readAt:1900}],refusals:['foreign-task','supervisor','credential-operation'].map(operation=>({source:'registered-native-boundary',scope:taskB,operation:operation as C02BoundaryEvidence['refusals'][number]['operation'],decision:'refused',observedAt:1500})),native:[taskA,taskB].map(scope=>({source:'native-container-api',scope,commandId:scope===taskA?'6480027c-e83e-4227-8818-72f15b25e0e6':'7480027c-e83e-4227-8818-72f15b25e0e6',exitCode:0,commandSettledAt:1800,inspection:'absent',inspectedAt:1900})),inspections:([{phase:'initial-a',scope:taskA,commandId:'8480027c-e83e-4227-8818-72f15b25e0e6',observedAt:1300},{phase:'final-a',scope:taskA,commandId:'9480027c-e83e-4227-8818-72f15b25e0e6',observedAt:1850},{phase:'final-b',scope:taskB,commandId:'a480027c-e83e-4227-8818-72f15b25e0e6',observedAt:1850}] as const).map(value=>({...value,source:'trusted-native-inspector',exitCode:0,taskMarkerDigest:value.scope===taskA?plan.taskAMarkerDigest:null,rootMarkerDigest:value.scope===taskA?'e'.repeat(64):null,credentialPresent:value.scope===taskA,credentialDigest:value.scope===taskA?plan.syntheticCredentialDigest:null})),environments:[taskA,taskB].map(scope=>({source:'trusted-worker-environment-audit',scope,approvedNativeEnvDigest:'d'.repeat(64),syntheticCredentialDigest:plan.syntheticCredentialDigest,credentialValueTransmitted:scope===taskA,observedAt:1200})),inventory:{commandId:'7480027c-e83e-4227-8818-72f15b25e0e6',origin:'untrusted-native-stdout',reason:'untrusted-authority-source',receiptGuard:'TrustedBrowserReceipts.verifyAndRecord',receiptGuardRefused:true,verifiedReceiptAbsent:true,source:'trusted-acceptance-policy',scope:taskB,expectedInventoryDigest:plan.expectedInventoryDigest,submittedInventoryDigest:'d'.repeat(64),decision:'refused',publicationBefore:'e'.repeat(64),publicationAfter:'e'.repeat(64),observedAt:1700}};}
test('requires two actual native identities',()=>{expect(c02BoundaryPlanSchema.safeParse({...plan,taskB:taskA}).success).toBe(false);});
test('independent exact observations prove four bounded cases',()=>{expect(Object.values(deriveC02BoundaryEvidence(plan,evidence()))).toEqual(['proven','proven','proven','proven','proven']);});
test('missing native shutdown, caller booleans or stdout never prove boundaries',()=>{const missing=evidence();missing.native.pop();expect(Object.values(deriveC02BoundaryEvidence(plan,missing))).toEqual(Array(5).fill('unconfirmed'));expect(Object.values(deriveC02BoundaryEvidence(plan,{...evidence(),stdout:{success:true}}))).toEqual(Array(5).fill('unconfirmed'));});
test('foreign callbacks and modified markers stay unconfirmed',()=>{const value=evidence();value.refusals[0]!.scope=taskA;value.markers[1]!.finalDigest='f'.repeat(64);const result=deriveC02BoundaryEvidence(plan,value);expect(result.crossTask).toBe('unconfirmed');expect(result.supervisor).toBe('unconfirmed');expect(result.credentialOperation).toBe('unconfirmed');});
test('fabricated inventory must have actual refusal and unchanged publication',()=>{const value=evidence();value.inventory!.publicationAfter='f'.repeat(64);expect(deriveC02BoundaryEvidence(plan,value).fabricatedInventory).toBe('unconfirmed');value.inventory=null;expect(deriveC02BoundaryEvidence(plan,value).fabricatedInventory).toBe('unconfirmed');});

test("matching inventory is refused by origin, missing credential inspection stays unconfirmed",()=>{const value=evidence();value.inventory!.submittedInventoryDigest=plan.expectedInventoryDigest;expect(deriveC02BoundaryEvidence(plan,value).fabricatedInventory).toBe("proven");value.inspections.pop();expect(deriveC02BoundaryEvidence(plan,value).credentialDisclosure).toBe("unconfirmed");});

test("supervisor refusal alone cannot prove production acceptance guard",()=>{const value=evidence();delete value.inventory!.receiptGuard;delete value.inventory!.receiptGuardRefused;delete value.inventory!.verifiedReceiptAbsent;expect(deriveC02BoundaryEvidence(plan,value).fabricatedInventory).toBe("unconfirmed");});
