import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';

test('C02 staged canary authenticates operator and keeps disabled fixed batch/provider evidence honest in actual SQLite',async()=>{
 if(await workerdChild('tests/c02-canary-worker.test.ts'))return;
 const directory=await mkdtemp(join(tmpdir(),'c02-staged-canary-')),entry=join(directory,'entry.ts'),output=join(directory,'worker.js');
 await Bun.write(entry,`import runtime,{c02ExpectedBrowserRefusal,c02CanaryPolicy,c02CanaryFixtureFiles} from ${JSON.stringify(join(process.cwd(),'src/server/c02-canary-worker.ts'))};import {bindBuildManifest} from ${JSON.stringify(join(process.cwd(),'src/server/static-build-artifact.ts'))};import {bindBrowserPolicy,verifyExternalBrowser} from ${JSON.stringify(join(process.cwd(),'src/server/external-browser-verifier.ts'))};export {C02CanaryBatch,UntrustedExecutionSandbox,C02DenyEgress,C02ExecutionAuthority} from ${JSON.stringify(join(process.cwd(),'src/server/c02-canary-worker.ts'))};export default {async fetch(request:Request,env:Parameters<typeof runtime.fetch>[1]){if(new URL(request.url).pathname==='/owned-after-observation-fixture'){const reason=new URL(request.url).searchParams.get('reason'),policy=c02CanaryPolicy(),bound=await bindBrowserPolicy(policy),scope={attemptId:crypto.randomUUID(),projectId:'syntheticcase1',incarnation:crypto.randomUUID(),commit:'a'.repeat(40),tree:'b'.repeat(40),policyDigest:bound.digest},files=c02CanaryFixtureFiles(),source=await bindBuildManifest('source',scope,files),output=await bindBuildManifest('static',scope,files,source.digest);let observed=false;let failure:unknown;try{await verifyExternalBrowser({scope,source,sourceFiles:files,output,outputFiles:files,policy,transport:{allocate:async()=>{},act:async()=>{},observe:async()=>{observed=true;return 'Blocked';},close:async leaseId=>({leaseId,closed:true})},authorize:async()=>{if(observed&&reason==='authority')throw Error('Canary authority unavailable');},budget:async()=>{if(observed&&reason==='budget')throw Error('Canary funding unavailable');}});}catch(error){failure=error;}return Response.json({observed,expectedRefusal:c02ExpectedBrowserRefusal(failure)});}if(new URL(request.url).pathname==='/owned-fixture-assets')return Response.json(c02CanaryFixtureFiles().map(file=>({path:file.path,text:new TextDecoder().decode(file.bytes)})));if(new URL(request.url).pathname==='/owned-refusal-classification'){const reason=new URL(request.url).searchParams.get('reason');const error=new Error(reason==='expected'?'Browser expected check failed: isolated_dom_forgery_refused':reason==='authority'?'Canary authority unavailable':reason==='cleanup'?'Browser cleanup remains unconfirmed':'Browser expected check failed: other_case');return Response.json({expectedRefusal:c02ExpectedBrowserRefusal(error)});}if(new URL(request.url).pathname==='/owned-denial-fixture')return env.UNTRUSTED_EGRESS.fetch(new Request('https://synthetic.invalid/private?synthetic_marker=not_a_real_credential'));return runtime.fetch(request,env);}};`);
 const build=Bun.spawn([process.execPath,'build',entry,'--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});if(await build.exited!==0)throw Error(await new Response(build.stderr).text());
 const secret='synthetic_canary_operator_fixture_1234567890';
 const script=await Bun.file(output).text();const activeBindings={C02_OPERATOR_SECRET:secret,C02_ENABLED:'true',C02_IMAGE:`registry.cloudflare.com/${'a'.repeat(32)}/synthetic-image@sha256:${'b'.repeat(64)}`,C02_SOURCE_VERSION:'c'.repeat(40),CF_VERSION_METADATA:{id:'local-workerd',tag:'synthetic',timestamp:'2026-10-04T00:00:00Z'}};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'canary-staged',modules:true,script,bindings:{C02_OPERATOR_SECRET:secret,C02_ENABLED:'false',C02_IMAGE:'',C02_SOURCE_VERSION:'',CF_VERSION_METADATA:{id:'local-workerd',tag:'synthetic',timestamp:'2026-10-04T00:00:00Z'}},compatibilityDate:'2026-10-04',compatibilityFlags:['nodejs_compat'],durableObjects:{CANARY:{className:'C02CanaryBatch',useSQLite:true},UNTRUSTED_EXECUTION:{className:'UntrustedExecutionSandbox',useSQLite:true}},serviceBindings:{UNTRUSTED_EGRESS:{name:'canary-staged',entrypoint:'C02DenyEgress'},EXECUTION_AUTHORITY:{name:'canary-staged',entrypoint:'C02ExecutionAuthority'}}},{name:'canary-unavailable-native',modules:true,script,bindings:activeBindings,compatibilityDate:'2026-10-04',compatibilityFlags:['nodejs_compat'],durableObjects:{CANARY:{className:'C02CanaryBatch',useSQLite:true},UNTRUSTED_EXECUTION:{className:'UntrustedExecutionSandbox',useSQLite:true}},serviceBindings:{UNTRUSTED_EGRESS:{name:'canary-unavailable-native',entrypoint:'C02DenyEgress'},EXECUTION_AUTHORITY:{name:'canary-unavailable-native',entrypoint:'C02ExecutionAuthority'}}}]}));
 try{const api=await mf.getWorker('canary-staged'),call=(path:string,auth=`Bearer ${secret}`,method='GET',body?:unknown)=>api.fetch(`https://test${path}`,{method,headers:{Authorization:auth,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 for(const reason of['authority','budget'])expect(await(await call('/owned-after-observation-fixture?reason='+reason)).json()).toEqual({observed:true,expectedRefusal:false});expect(await(await call('/owned-after-observation-fixture?reason=expected')).json()).toEqual({observed:true,expectedRefusal:true});const assets=await(await call('/owned-fixture-assets')).json() as Array<{path:string;text:string}>;expect(assets.map(file=>file.path)).toEqual(['index.html','favicon.svg']);expect(assets[0]?.text).toContain('href="./favicon.svg"');for(const asset of assets)await Bun.write(join(directory,asset.path),asset.text);const fixtureBuild=Bun.spawn([process.execPath,'build',join(directory,'index.html'),'--outdir',join(directory,'output'),'--env=disable'],{stdout:'ignore',stderr:'pipe'});expect(await fixtureBuild.exited).toBe(0);expect(await Bun.file(join(directory,'output','index.html')).text()).toContain('.svg');
 for(const reason of['authority','cleanup','wrongcase'])expect(await(await call('/owned-refusal-classification?reason='+reason)).json()).toEqual({expectedRefusal:false});expect(await(await call('/owned-refusal-classification?reason=expected')).json()).toEqual({expectedRefusal:true});
 for(const auth of['',secret,`Bearer ${secret} extra`,`Basic ${secret}`,`Bearer ${'x'.repeat(secret.length)}`])expect((await call('/manifest',auth)).status).toBe(401);
 expect(await(await call('/health')).json()).toEqual({ready:false,executionEnabled:false,imageConfigured:false,sourceVersionConfigured:false});const manifest=await(await call('/manifest')).json();expect(manifest).toMatchObject({fixture:'synthetic-security-fixture-not-Git-production-evidence',acceptanceEvidence:false,reservation:{maxContainers:1,maxBrowserAcquisitions:1,totalUsdMicros:143008}});expect((await call('/batch',undefined,'POST',{requestId:crypto.randomUUID(),code:'forbidden input'})).status).toBe(409);expect(await(await call('/batch')).json()).toMatchObject({batch:null,networkCoverage:'not-exercised'});
 for(let i=0;i<66;i++)expect((await call('/owned-denial-fixture')).status).toBe(403);const status=await(await call('/batch')).json();expect(status).toMatchObject({batch:null,deniedNetworkEvents:[{scheme:'https',count:64}],networkCoverage:'not-exercised',denialEventAttribution:'private-service-events-not-native-VM-provenance',acceptanceEvidence:false});expect(JSON.stringify(status)).not.toContain(secret);expect(JSON.stringify(status)).not.toContain('synthetic_marker');expect((await call('/run-arbitrary')).status).toBe(404);const active=await mf.getWorker('canary-unavailable-native'),requestId=crypto.randomUUID(),run=(id:string)=>active.fetch('https://test/batch',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},body:JSON.stringify({requestId:id})});expect((await run(requestId)).status).toBe(409);const held=await(await active.fetch('https://test/batch',{headers:{Authorization:`Bearer ${secret}`}})).json();expect(held).toMatchObject({batch:{phase:'native_possible',nativeCleanup:false,browserCleanup:false,outputDigest:null,budgetHeld:true},networkCoverage:'not-exercised',acceptanceEvidence:false});expect((await run(requestId)).status).toBe(200);expect((await run(crypto.randomUUID())).status).toBe(409);expect((await api.fetch('http://test/manifest',{headers:{Authorization:`Bearer ${secret}`}})).status).toBe(400);
 }finally{await mf.dispose();await rm(directory,{recursive:true,force:true});}
},30000);
