import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {C02NetworkRuntime} from '../src/server/c02-network-runtime';
import {C02_NETWORK_PROBE_PROGRAM,type C02NetworkProbePlan,type C02NetworkReceiverReceipt} from '../src/server/c02-network-probe';
const image=`registry.cloudflare.com/${'a'.repeat(32)}/c02@sha256:${'b'.repeat(64)}`;
function fixture(twoPhase=false){
 const db=new Database(':memory:'),now=Date.now(),calls:string[]=[];let running=false,unknown=false,stopUnknown=false,alarm=0;const payloads:unknown[]=[];const deny={} as Fetcher,control={} as Fetcher,hookBindings:Fetcher[]=[];
 const storage={sql:{exec:(query:string,...args:(string|number)[])=>{const rows=db.query(query).all(...args);return{toArray:()=>rows}}},transactionSync:<T>(operation:()=>T)=>db.transaction(operation)(),setAlarm:async(value:number)=>{alarm=value;calls.push('alarm')},deleteAlarm:async()=>{alarm=0}} as unknown as DurableObjectStorage;
 const plan:C02NetworkProbePlan={scope:{requestId:crypto.randomUUID(),instanceId:'registered-instance',probeId:crypto.randomUUID()},createdAt:now,deadlineAt:now+120000,maxContainers:1,maxNativeSeconds:120,endpoints:[{channel:'https',receiverId:'receiver',url:'https://flaregit-owned-delivery-verifier.simo-988.workers.dev/c02-network/probe',controlNonce:'c'.repeat(64),probeNonce:'d'.repeat(64)}]};
 const controls:C02NetworkReceiverReceipt[]=[{scope:plan.scope,channel:'https',receiverId:'receiver',nonce:'c'.repeat(64),receivedAt:now,kind:'control',source:'owned-receiver'}];
 let runtime:C02NetworkRuntime;
 const container={get running(){return running},start:(options:ContainerStartupOptions)=>{calls.push('start');expect(runtime.status()?.phase).toBe('dispatched');expect(alarm).toBe(plan.deadlineAt);expect(options.enableInternet).toBe(false);expect(options.image).toBe(image);running=true},interceptAllOutboundHttp:async(binding:Fetcher)=>{calls.push('http');hookBindings.push(binding)},interceptOutboundHttps:async(host:string,binding:Fetcher)=>{expect(host).toBe('*');calls.push('https');hookBindings.push(binding)},inspect:async()=>running?{image,labels:{}}:null,destroy:async()=>{calls.push('destroy');if(stopUnknown)throw Error('Local unknown stop');running=false},exec:async(argv:string[],options?:ContainerExecOptions)=>{calls.push('exec');if(options?.stdin)payloads.push(await new Response(options.stdin).json());expect(argv).toEqual(['/usr/local/bin/bun','-e',C02_NETWORK_PROBE_PROGRAM]);expect(options?.stdout).toBe('ignore');expect(options?.stderr).toBe('ignore');expect(runtime.status()?.commandSettled).toBe(false);if(unknown)throw Error('Local unknown dispatch');return{exitCode:Promise.resolve(0)} as ExecProcess}};
 const make=()=>new C02NetworkRuntime(storage,()=>container,deny,plan.scope.instanceId,image,()=>now,twoPhase?{interceptor:control,readReceipts:async()=>{calls.push('receipts');return controls}}:undefined);runtime=make();return{db,plan,controls,calls,payloads,hookBindings,deny,control,make,runtime,setUnknown:()=>{unknown=true},setStopUnknown:(value:boolean)=>{stopUnknown=value}};
}
test('local native API doubles: registered one-shot dispatch ignores stdout and persists confirmed settlement',async()=>{const f=fixture();try{f.runtime.prepare(f.plan,f.controls,crypto.randomUUID());const result=await f.runtime.run(f.plan.scope);expect(result).toMatchObject({phase:'stopped',commandSettled:true,nativeStopped:true,exitCode:0});expect(f.calls.indexOf('http')).toBeLessThan(f.calls.indexOf('start'));expect(f.calls.indexOf('https')).toBeLessThan(f.calls.indexOf('start'));expect(f.make().status()).toEqual(result);await expect(f.make().run(f.plan.scope)).rejects.toThrow('consumed');expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);}finally{f.db.close();}});
test('local unknown exec remains held after positive shutdown and cannot replay',async()=>{const f=fixture();try{f.runtime.prepare(f.plan,f.controls,crypto.randomUUID());f.setUnknown();await expect(f.runtime.run(f.plan.scope)).rejects.toThrow('unknown dispatch');expect(f.runtime.status()).toMatchObject({phase:'held',commandSettled:false,nativeStopped:true,exitCode:null});await expect(f.make().run(f.plan.scope)).rejects.toThrow('consumed');expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);}finally{f.db.close();}});
test('local shutdown failure remains held and cleanup retry never executes again',async()=>{const f=fixture();try{f.runtime.prepare(f.plan,f.controls,crypto.randomUUID());f.setStopUnknown(true);await expect(f.runtime.run(f.plan.scope)).rejects.toThrow('not be confirmed');expect(f.runtime.status()).toMatchObject({phase:'held',commandSettled:true,nativeStopped:false});f.setStopUnknown(false);expect(await f.make().stop()).toMatchObject({phase:'stopped',nativeStopped:true});expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);}finally{f.db.close();}});
test('local wrong instance, missing controls and mutable registration are refused before native start',async()=>{const f=fixture();try{expect(()=>f.runtime.prepare({...f.plan,scope:{...f.plan.scope,instanceId:'other'}},f.controls,crypto.randomUUID())).toThrow('instance differs');expect(()=>f.runtime.prepare(f.plan,[],crypto.randomUUID())).toThrow('controlled');const command=crypto.randomUUID();f.runtime.prepare(f.plan,f.controls,command);f.runtime.prepare(f.plan,f.controls,command);expect(()=>f.runtime.prepare(f.plan,f.controls,crypto.randomUUID())).toThrow('differs');await expect(f.runtime.run({...f.plan.scope,probeId:crypto.randomUUID()})).rejects.toThrow('unavailable');expect(f.calls).toHaveLength(0);}finally{f.db.close();}});

test('local native controls share one VM and both deny hooks replace control hooks before the admitted probe',async()=>{const f=fixture(true);try{f.plan.endpoints.push({channel:'raw-tls',receiverId:'receiver',url:f.plan.endpoints[0]!.url,controlNonce:'e'.repeat(64),probeNonce:'f'.repeat(64)});f.runtime.prepare(f.plan,[],crypto.randomUUID());expect(f.runtime.status()?.input).toBeNull();const result=await f.runtime.run(f.plan.scope);expect(f.calls).toEqual(['alarm','alarm','http','https','start','exec','receipts','http','https','exec','alarm','destroy']);expect(f.hookBindings).toEqual([f.control,f.control,f.deny,f.deny]);expect(f.payloads).toHaveLength(2);expect(f.payloads[0]).toMatchObject({endpoints:[{channel:'https'},{channel:'raw-tls'}]});expect(f.payloads[1]).toMatchObject({endpoints:[{channel:'https'}]});expect(result).toMatchObject({controlSettled:true,controlExitCode:0,hookMode:'deny',commandSettled:true,nativeStopped:true});expect(f.calls.filter(value=>value==='start')).toHaveLength(1);}finally{f.db.close();}});
test('local unknown native control seals the single attempt and never dispatches probe',async()=>{const f=fixture(true);try{f.runtime.prepare(f.plan,[],crypto.randomUUID());f.setUnknown();await expect(f.runtime.run(f.plan.scope)).rejects.toThrow('unknown dispatch');expect(f.runtime.status()).toMatchObject({phase:'held',controlSettled:false,controlExitCode:null,commandSettled:false,nativeStopped:true,hookMode:'control'});expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);expect(f.calls).not.toContain('receipts');await expect(f.make().run(f.plan.scope)).rejects.toThrow('consumed');}finally{f.db.close();}});
test('local missing independent native control receipt stops before deny or probe dispatch',async()=>{const f=fixture(true);try{f.controls.length=0;f.runtime.prepare(f.plan,[],crypto.randomUUID());await expect(f.runtime.run(f.plan.scope)).rejects.toThrow('controlled');expect(f.runtime.status()).toMatchObject({phase:'stopped',controlSettled:true,commandSettled:true,hookMode:'control',input:null});expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);expect(f.calls.filter(value=>value==='https')).toHaveLength(1);}finally{f.db.close();}});
