import {test,expect} from 'bun:test';
import {matchC02NetworkInterception,type C02NetworkInterceptorProps} from '../src/server/c02-network-interceptor';
import {type C02NetworkProbePlan} from '../src/server/c02-network-probe';
const scope={requestId:'3480027c-e83e-4227-8818-72f15b25e0e6',instanceId:'native_1',probeId:'4480027c-e83e-4227-8818-72f15b25e0e6'};
const props:C02NetworkInterceptorProps={scope,interceptorId:'hook_1'};
const plan:C02NetworkProbePlan={scope,createdAt:1000,deadlineAt:2000,maxContainers:1,maxNativeSeconds:120,endpoints:[{channel:'https',receiverId:'owned',url:'https://flaregit-owned-delivery-verifier.simo-988.workers.dev/c02-network/probe',controlNonce:'a'.repeat(64),probeNonce:'b'.repeat(64)}]};
function request(delta:Record<string,string>={},path=plan.endpoints[0]!.url){const url=new URL(path);for(const[key,value]of Object.entries({...scope,channel:'https',nonce:'b'.repeat(64),...delta}))url.searchParams.set(key,value);return new Request(url);}
test('registered native props produce exact trusted receipt; headers cannot change attribution',()=>{const req=request();req.headers.set('instanceId','forged');req.headers.set('source','owned-receiver');expect(matchC02NetworkInterception(plan,props,props,req,1500)).toEqual({scope,channel:'https',nonce:'b'.repeat(64),receivedAt:1500,source:'registered-native-interceptor',interceptorId:'hook_1'});});
test('reject foreign props and persisted registration',()=>{expect(matchC02NetworkInterception(plan,props,{...props,interceptorId:'other'},request(),1500)).toBeNull();expect(matchC02NetworkInterception(plan,{...props,scope:{...scope,instanceId:'other'}},props,request(),1500)).toBeNull();expect(matchC02NetworkInterception(plan,props,{...props,source:'registered-native-interceptor'},request(),1500)).toBeNull();});
test('reject every query scope mismatch and control nonce',()=>{for(const key of ['requestId','instanceId','probeId','channel','nonce'])expect(matchC02NetworkInterception(plan,props,props,request({[key]:'foreign'}),1500)).toBeNull();expect(matchC02NetworkInterception(plan,props,props,request({nonce:'a'.repeat(64)}),1500)).toBeNull();});
test('reject duplicate, extra and absent query parameters',()=>{const duplicate=new URL(request().url);duplicate.searchParams.append('nonce','b'.repeat(64));expect(matchC02NetworkInterception(plan,props,props,new Request(duplicate),1500)).toBeNull();expect(matchC02NetworkInterception(plan,props,props,request({source:'registered-native-interceptor'}),1500)).toBeNull();expect(matchC02NetworkInterception(plan,props,props,new Request(plan.endpoints[0]!.url),1500)).toBeNull();});
test('reject foreign destination, scheme, path, method and expired trusted clock',()=>{for(const url of ['http://flaregit-owned-delivery-verifier.simo-988.workers.dev/c02-network/probe','https://example.com/c02-network/probe','https://flaregit-owned-delivery-verifier.simo-988.workers.dev/c02-network/other'])expect(matchC02NetworkInterception(plan,props,props,request({},url),1500)).toBeNull();expect(matchC02NetworkInterception(plan,props,props,new Request(request(),{method:'POST'}),1500)).toBeNull();for(const now of [999,2000,2001,NaN])expect(matchC02NetworkInterception(plan,props,props,request(),now)).toBeNull();});
