import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {C02BoundaryRuntime} from '../src/server/c02-boundary-runtime';
import {C02_BOUNDARY_SETUP_PROGRAM,C02_BOUNDARY_ATTACK_PROGRAM,C02_BOUNDARY_INSPECT_PROGRAM,type C02BoundaryPlan} from '../src/server/c02-boundary-programs';
const image=`registry.cloudflare.com/${'a'.repeat(32)}/boundary@sha256:${'b'.repeat(64)}`;
function fixture(role:'task-a'|'task-b'){
 const db=new Database(':memory:'),now=Date.now(),calls:string[]=[],starts:ContainerStartupOptions[]=[],environments:Record<string,string>[]=[];let running=false,unknown=false,stopUnknown=false,oversized=false;
 const plan:C02BoundaryPlan={requestId:crypto.randomUUID(),taskA:{taskId:crypto.randomUUID(),instanceId:'native-a'},taskB:{taskId:crypto.randomUUID(),instanceId:'native-b'},createdAt:now,deadlineAt:now+120000,taskMarker:'1'.repeat(64),rootMarker:'2'.repeat(64),syntheticCredential:'3'.repeat(64),tamperMarker:'4'.repeat(64),actionNonces:{supervisor:'5'.repeat(64),foreignTask:'6'.repeat(64),credentialAction:'7'.repeat(64)}};
 const storage={sql:{exec:(query:string,...args:(string|number)[])=>{const rows=db.query(query).all(...args);return{toArray:()=>rows}}},transactionSync:<T>(operation:()=>T)=>db.transaction(operation)(),setAlarm:async()=>{calls.push('alarm')},deleteAlarm:async()=>{}} as unknown as DurableObjectStorage;
 let runtime:C02BoundaryRuntime;
 const container={get running(){return running},start:(options:ContainerStartupOptions)=>{expect(runtime.status()?.phase).toBe('dispatched');starts.push(options);calls.push('start');running=true},interceptAllOutboundHttp:async()=>{calls.push('http')},interceptOutboundHttps:async()=>{calls.push('https')},inspect:async()=>running?{image,labels:starts.at(-1)?.labels??{}}:null,destroy:async()=>{calls.push('destroy');if(stopUnknown)throw Error('Synthetic stop unknown');running=false},exec:async(argv:string[],options?:ContainerExecOptions)=>{const program=argv[2];if(program===undefined)throw Error('Missing fixed program');expect([C02_BOUNDARY_SETUP_PROGRAM,C02_BOUNDARY_ATTACK_PROGRAM,C02_BOUNDARY_INSPECT_PROGRAM]).toContain(program);expect(runtime.status()?.commands.at(-1)?.settled).toBe(false);expect(runtime.status()?.commands.at(-1)?.commandId).toMatch(/^[a-f0-9-]{36}$/);calls.push('exec');environments.push(options?.env??{});if(unknown)throw Error('Synthetic command unknown');return{stdout:new Response(oversized?'x'.repeat(8193):program===C02_BOUNDARY_ATTACK_PROGRAM?'{"passed":true,"acceptanceEvidence":true}':'{"trustedInspectionDiagnostic":true}').body,exitCode:Promise.resolve(0)} as ExecProcess}};
 const make=()=>new C02BoundaryRuntime(storage,()=>container,{} as Fetcher,role==='task-a'?'native-a':'native-b',role,image,()=>now);runtime=make();return{db,runtime,make,plan,calls,starts,environments,setUnknown:()=>{unknown=true},setOversized:()=>{oversized=true},setStopUnknown:(value:boolean)=>{stopUnknown=value}};
}
test('local trusted A persists distinct setup/initial/final command provenance while retained through B interval',async()=>{const f=fixture('task-a');try{await f.runtime.prepare(f.plan);const initial=await f.runtime.startA();expect(initial.phase).toBe('ready');expect(initial.commands.map(command=>command.kind)).toEqual(['setup','inspect-initial']);expect(f.starts[0]).toMatchObject({image,enableInternet:false,env:{CI:'1',C02_SYNTHETIC_CREDENTIAL:f.plan.syntheticCredential}});expect(f.environments).toEqual([{CI:'1'},{CI:'1'}]);expect(f.calls.indexOf('https')).toBeLessThan(f.calls.indexOf('start'));expect(f.calls).not.toContain('destroy');const final=await f.make().inspectA();expect(final.commands.at(-1)).toMatchObject({kind:'inspect-final',source:'trusted-fixed-command',settled:true,exitCode:0});expect(new Set(final.commands.map(command=>command.commandId)).size).toBe(3);expect(await f.runtime.stop()).toMatchObject({phase:'stopped',nativeStopped:true});await expect(f.make().inspectA()).rejects.toThrow('consumed');expect(f.starts).toHaveLength(1);}finally{f.db.close();}});
test('local B attacker stdout remains separate from trusted inspector and has no selected credential environment',async()=>{const f=fixture('task-b');try{await f.runtime.prepare(f.plan);const result=await f.runtime.runB();expect(result).toMatchObject({phase:'stopped',nativeStopped:true});expect(result.commands[0]).toMatchObject({kind:'attacker',source:'untrusted-native-stdout',output:'{"passed":true,"acceptanceEvidence":true}'});expect(result.commands[1]).toMatchObject({kind:'inspect-b',source:'trusted-fixed-command',settled:true,exitCode:0});expect(f.starts[0]?.env).toEqual({CI:'1'});expect(result.startup).toMatchObject({syntheticCredentialTransmitted:false,returnedAt:f.plan.createdAt});expect(result.startup?.environmentDigest).toMatch(/^[a-f0-9]{64}$/);expect(f.environments).toEqual([{CI:'1'},{CI:'1'}]);await expect(f.make().runB()).rejects.toThrow('consumed');}finally{f.db.close();}});
test('local unknown command remains held despite positive shutdown with no execution replay',async()=>{const f=fixture('task-b');try{await f.runtime.prepare(f.plan);f.setUnknown();await expect(f.runtime.runB()).rejects.toThrow('command unknown');expect(f.make().status()).toMatchObject({phase:'held',nativeStopped:true,commands:[{settled:false,exitCode:null}]});await expect(f.make().runB()).rejects.toThrow('consumed');expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);}finally{f.db.close();}});
test('local bounded output failure prevents trusted inspection and cleanup retries never rerun commands',async()=>{const f=fixture('task-b');try{await f.runtime.prepare(f.plan);f.setOversized();f.setStopUnknown(true);await expect(f.runtime.runB()).rejects.toThrow('not be confirmed');expect(f.runtime.status()?.phase).toBe('held');f.setStopUnknown(false);await f.runtime.stop();expect(f.runtime.status()?.commands).toHaveLength(1);expect(f.calls.filter(value=>value==='exec')).toHaveLength(1);}finally{f.db.close();}});
test('local role, exact instance and changed plan refuse before provisioning',async()=>{const f=fixture('task-b');try{await expect(f.runtime.prepare({...f.plan,taskB:{...f.plan.taskB,instanceId:'foreign'}})).rejects.toThrow('instance differs');await f.runtime.prepare(f.plan);await expect(f.runtime.prepare({...f.plan,tamperMarker:'8'.repeat(64)})).rejects.toThrow('consumed');await expect(f.runtime.startA()).rejects.toThrow('role differs');await expect(f.runtime.inspectA()).rejects.toThrow('role differs');expect(f.starts).toHaveLength(0);}finally{f.db.close();}});
