import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {C03PublicationDriver} from '../src/server/c03-publication-driver';
import type {C03CheckpointSql,C03PublicationScope} from '../src/server/c03-publication-checkpoints';
import {publicationInHistory} from '../src/server/publication';
async function fixture(){const directory=await mkdtemp(join(tmpdir(),'c03-driver-')),work=join(directory,'source'),canonical=join(directory,'canonical.git'),db=new Database(':memory:');const git=async(...args:string[])=>{const child=Bun.spawn(['git',...args],{stdout:'pipe',stderr:'pipe'});const[out,err,exit]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(exit)throw Error(err);return out.trim();};await git('init','--initial-branch=main',work);await git('-C',work,'config','user.email','local-fixture@example.invalid');await git('-C',work,'config','user.name','Authorized local fixture');await Bun.write(join(work,'file.txt'),'base');await git('-C',work,'add','.');await git('-C',work,'commit','-m','base');const base=await git('-C',work,'rev-parse','HEAD');await git('clone','--bare',work,canonical);await Bun.write(join(work,'file.txt'),'candidate');await git('-C',work,'add','.');await git('-C',work,'commit','-m','candidate');const commit=await git('-C',work,'rev-parse','HEAD'),tree=await git('-C',work,'rev-parse','HEAD^{tree}');await git('-C',work,'push',canonical,'HEAD:refs/flaregit/candidate');let publications=0,loseAck=false,authorized=true;const scope:C03PublicationScope={caseId:crypto.randomUUID(),projectId:'p123456789abc',incarnation:crypto.randomUUID(),candidateId:'owned-local-candidate',ref:'refs/heads/main',commit,tree,workerVersion:crypto.randomUUID(),sourceVersion:'c'.repeat(40)},invocationId=crypto.randomUUID(),requestId=crypto.randomUUID();const sql:C03CheckpointSql={transactionSync:<T>(callback:()=>T)=>db.transaction(callback)(),exec:(query,...args)=>{const rows=db.query(query).all(...args) as {doc:string}[];return{toArray:()=>rows}}};
 const callbacks={authorize:async()=>{if(!authorized)throw Error('Owner authorization withdrawn')},publish:async(current:C03PublicationScope)=>{if(!authorized)throw Error('Actual publisher authorization withdrawn');publications++;await git('--git-dir',canonical,'update-ref',current.ref,current.commit,base);if(loseAck)throw Error('Local ACK lost after ref update')},readback:async(current:C03PublicationScope)=>publicationInHistory(async(command,env)=>{const child=Bun.spawn(['sh','-c',command],{env:{...process.env,...env},stdout:'pipe',stderr:'ignore'});const[stdout,exitCode]=await Promise.all([new Response(child.stdout).text(),child.exited]);return{success:exitCode===0,exitCode,stdout};},work,canonical,'synthetic-local-unused','main',current.commit)};
 const make=()=>new C03PublicationDriver(sql,callbacks);return{directory,db,work,canonical,git,scope,invocationId,requestId,make,sql,callbacks,publications:()=>publications,loseAck:()=>{loseAck=true},withdraw:()=>{authorized=false},close:async()=>{db.close();await rm(directory,{recursive:true,force:true})}};}
test('real local Git before pause makes zero writes; exact resumed invocation publishes once and clone contains candidate',async()=>{const f=await fixture();try{const driver=f.make();expect(await driver.run(f.scope,f.invocationId,f.requestId,'before-ref-update')).toMatchObject({phase:'held-before',commandId:null});expect(f.publications()).toBe(0);const resume=crypto.randomUUID();expect(await f.make().resume(f.scope,f.invocationId,f.requestId,resume)).toMatchObject({phase:'acknowledged'});expect(await driver.resume(f.scope,f.invocationId,f.requestId,resume)).toMatchObject({phase:'acknowledged'});expect(f.publications()).toBe(1);expect((await driver.reconcile(f.scope,f.invocationId,f.requestId)).landed).toBe(true);const clone=join(f.directory,'fresh-clone');await f.git('clone',f.canonical,clone);expect(await f.git('-C',clone,'rev-parse','HEAD')).toBe(f.scope.commit);}finally{await f.close();}},30000);
test('real local Git after pause is only an ACK checkpoint; independent production history readback proves landing',async()=>{const f=await fixture();try{const driver=f.make();expect(await driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).toMatchObject({phase:'held-after'});expect(f.publications()).toBe(1);expect(await driver.resume(f.scope,f.invocationId,f.requestId,crypto.randomUUID())).toMatchObject({phase:'held-after'});expect((await f.make().reconcile(f.scope,f.invocationId,f.requestId)).state.phase).toBe('readback-landed');expect(f.publications()).toBe(1);}finally{await f.close();}},30000);
test('lost local publisher ACK preserves actual landed commit without callback replay; readback recovers',async()=>{const f=await fixture();try{f.loseAck();const driver=f.make();await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('ACK lost');expect(driver.status()).toMatchObject({phase:'unknown'});await expect(f.make().run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('consumed');expect((await f.make().reconcile(f.scope,f.invocationId,f.requestId)).landed).toBe(true);expect(f.publications()).toBe(1);}finally{await f.close();}},30000);
test('withdrawn owner blocks resumed publish; only undispatched registration may cancel',async()=>{const f=await fixture();try{const driver=f.make();driver.register(f.scope,f.invocationId,f.requestId,'before-ref-update');expect(driver.cancelUndispatched(f.scope,f.invocationId,f.requestId).phase).toBe('cancelled');await expect(driver.run(f.scope,f.invocationId,f.requestId,'before-ref-update')).rejects.toThrow('consumed');expect(f.publications()).toBe(0);}finally{await f.close();}const g=await fixture();try{const driver=g.make();await driver.run(g.scope,g.invocationId,g.requestId,'before-ref-update');g.withdraw();await expect(driver.resume(g.scope,g.invocationId,g.requestId,crypto.randomUUID())).rejects.toThrow('withdrawn');expect(g.publications()).toBe(0);expect(()=>driver.cancelUndispatched(g.scope,g.invocationId,g.requestId)).toThrow('readback');}finally{await g.close();}},30000);

test('concurrent duplicate continuation acquires one durable publisher intent',async()=>{const f=await fixture();try{const driver=f.make();await driver.run(f.scope,f.invocationId,f.requestId,'before-ref-update');const resume=crypto.randomUUID();const outcomes=await Promise.allSettled([driver.resume(f.scope,f.invocationId,f.requestId,resume),f.make().resume(f.scope,f.invocationId,f.requestId,resume)]);expect(outcomes.filter(item=>item.status==='fulfilled')).toHaveLength(1);expect(f.publications()).toBe(1);expect((await driver.reconcile(f.scope,f.invocationId,f.requestId)).landed).toBe(true);}finally{await f.close();}},30000);

test('bounded authorization timeout never issues publisher or execution identity',async()=>{const f=await fixture();try{const driver=new C03PublicationDriver(f.sql,{...f.callbacks,authorize:async()=>new Promise<void>(()=>{})},{authorizeMs:10});await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('authorization deadline');expect(driver.status()).toMatchObject({commandId:null,phase:'authorization-held'});expect(f.publications()).toBe(0);}finally{await f.close();}},30000);
test('bounded publisher timeout retains exact unknown identity; late success or error cannot replace independent landed readback',async()=>{for(const lateError of [false,true]){const f=await fixture();try{const gate=Promise.withResolvers<void>(),sent=Promise.withResolvers<void>(),retained:Promise<void>[]=[];const driver=new C03PublicationDriver(f.sql,{...f.callbacks,publish:async(scope,commandId)=>{await f.callbacks.publish(scope);sent.resolve();await gate.promise;if(lateError)throw Error('Late publisher ACK failed');},retainBackground:work=>{retained.push(work)}},{publishMs:10});await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('publisher deadline');const identity=driver.status()?.commandId;expect(identity).toMatch(/^[a-f0-9-]{36}$/);expect(driver.status()?.phase).toBe('unknown');await sent.promise;expect((await driver.reconcile(f.scope,f.invocationId,f.requestId)).landed).toBe(true);gate.resolve();await Promise.all(retained);expect(driver.status()).toMatchObject({phase:'readback-landed',commandId:identity});expect(f.publications()).toBe(1);await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('consumed');}finally{await f.close();}}},30000);
test('bounded independent readback timeout preserves unknown outcome and allows later exact history readback',async()=>{const f=await fixture();try{f.loseAck();const driver=f.make();await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('ACK lost');const original=driver.status();const gate=Promise.withResolvers<boolean>();const reader=new C03PublicationDriver(f.sql,{...f.callbacks,readback:()=>gate.promise},{readbackMs:10});await expect(reader.reconcile(f.scope,f.invocationId,f.requestId)).rejects.toThrow('readback deadline');expect(reader.status()).toEqual(original);gate.resolve(false);await gate.promise;expect(reader.status()).toEqual(original);expect((await driver.reconcile(f.scope,f.invocationId,f.requestId)).landed).toBe(true);expect(f.publications()).toBe(1);}finally{await f.close();}},30000);
test('callback bounds reject unbounded or invalid durations',async()=>{const f=await fixture();try{for(const bounds of [{publishMs:0},{authorizeMs:30001},{readbackMs:1.5}])expect(()=>new C03PublicationDriver(f.sql,f.callbacks,bounds)).toThrow();}finally{await f.close();}},30000);

test('authorization rejection leaves truthful original held scope and cannot reopen its dispatched checkpoint',async()=>{const f=await fixture();try{let authorizations=0;const driver=new C03PublicationDriver(f.sql,{...f.callbacks,authorize:async()=>{authorizations++;throw Error('Approved requirement or policy refused');}});await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('policy refused');expect(driver.status()).toMatchObject({scope:f.scope,invocationId:f.invocationId,requestId:f.requestId,phase:'authorization-held',commandId:null});await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('consumed');await expect(driver.resume(f.scope,f.invocationId,f.requestId,crypto.randomUUID())).rejects.toThrow('checkpoint');expect(()=>driver.cancelUndispatched(f.scope,f.invocationId,f.requestId)).toThrow('readback');expect(authorizations).toBe(1);expect(f.publications()).toBe(0);}finally{await f.close();}},30000);

test('late authorization after deadline cannot publish and duplicate resume cannot invoke authorization twice',async()=>{const f=await fixture();try{let authorizations=0;const gate=Promise.withResolvers<void>(),entered=Promise.withResolvers<void>(),driver=new C03PublicationDriver(f.sql,{...f.callbacks,authorize:async()=>{authorizations++;entered.resolve();await gate.promise;}},{authorizeMs:10});await driver.run(f.scope,f.invocationId,f.requestId,'before-ref-update');const resume=crypto.randomUUID(),first=driver.resume(f.scope,f.invocationId,f.requestId,resume);const outcome=first.then(()=>null,(error:unknown)=>error);await entered.promise;expect(driver.status()).toMatchObject({phase:'authorization-intent',commandId:null});await expect(f.make().resume(f.scope,f.invocationId,f.requestId,resume)).rejects.toThrow('checkpoint');const failure=await outcome;if(!(failure instanceof Error))throw Error('Expected original authorization deadline');expect(failure.message).toContain('authorization deadline');const held=driver.status();expect(held).toMatchObject({phase:'authorization-held',commandId:null});gate.resolve();await gate.promise;await Promise.resolve();expect(driver.status()).toEqual(held);expect(authorizations).toBe(1);expect(f.publications()).toBe(0);}finally{await f.close();}},30000);

test('late negative readback cannot return failure after independent exact publication history already landed',async()=>{const f=await fixture();try{f.loseAck();const driver=f.make();await expect(driver.run(f.scope,f.invocationId,f.requestId,'after-ref-update')).rejects.toThrow('ACK lost');const gate=Promise.withResolvers<boolean>(),entered=Promise.withResolvers<void>(),reader=new C03PublicationDriver(f.sql,{...f.callbacks,readback:async()=>{entered.resolve();return gate.promise;}});const pending=reader.reconcile(f.scope,f.invocationId,f.requestId);await entered.promise;expect((await driver.reconcile(f.scope,f.invocationId,f.requestId)).landed).toBe(true);gate.resolve(false);expect(await pending).toMatchObject({landed:true,state:{phase:'readback-landed'}});expect(f.publications()).toBe(1);}finally{await f.close();}},30000);
