import {Database} from 'bun:sqlite';
import {test,expect,mock} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import type {CandidateGeneration,PublicationJournalEntry} from '../src/core/types';
import type {Ledger} from '../src/server/durable-object';
import type {Env} from '../src/server/env';
import type {C03CheckpointSql,C03PublicationScope} from '../src/server/c03-publication-checkpoints';
mock.module('cloudflare:workers',()=>({WorkflowEntrypoint:class{constructor(_ctx:unknown,public env:Env){}},DurableObject:class{}}));
const{FlareGitIntegrationWorkflow}=await import('../src/server/workflow');
const{createC03PublicationAdapter}=await import('../src/server/c03-publication-adapter');
async function fixture(){const directory=await mkdtemp(join(tmpdir(),'c03-prod-cas-')),seed=join(directory,'seed'),canonical=join(directory,'canonical.git'),workspace=join(directory,'ephemeral'),reader=join(directory,'reader'),db=new Database(':memory:');const git=async(...args:string[])=>{const child=Bun.spawn(['git',...args],{stdout:'pipe',stderr:'pipe',env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});const[out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(code)throw Error(err);return out.trim();};await git('init','--initial-branch=main',seed);await git('-C',seed,'config','user.name','Authorized synthetic fixture');await git('-C',seed,'config','user.email','fixture@example.invalid');await Bun.write(join(seed,'file.txt'),'base');await git('-C',seed,'add','.');await git('-C',seed,'commit','-m','accepted base');const base=await git('-C',seed,'rev-parse','HEAD');await git('clone','--bare',seed,canonical);await Bun.write(join(seed,'file.txt'),'reviewed candidate');await git('-C',seed,'commit','-am','candidate');const commit=await git('-C',seed,'rev-parse','HEAD'),tree=await git('-C',seed,'rev-parse','HEAD^{tree}');await git('-C',seed,'push',canonical,commit+':refs/flaregit/candidates/candidate');await git('init',reader);
 const incarnation=crypto.randomUUID(),target={projectId:'p123456789abc',incarnation,canonicalRepoName:'owned-local',ref:'refs/heads/main',branch:'main',acceptedCommit:base,acceptedVersion:1,requirements:[],policyVersion:1,policy:{test:'bun test'}};
 const candidate:CandidateGeneration={attemptNumber:1,createdAt:'now',updatedAt:'now',id:'candidate',acceptedTarget:target,candidateCommit:commit,expectedAcceptedBase:base,participatingTaskIds:['task'],participatingCommits:{task:commit},frozenPolicyVersion:1,frozenVerificationPolicy:{test:'bun test'},frozenRequirements:[],repairAttempts:[],status:'awaiting_review'};
 const journal={id:'journal',candidateId:'candidate',acceptedTarget:target,candidateCommit:commit,candidateTree:tree,expectedHead:base,newHead:commit,state:'PREPARED',timestamp:'now',outputDigest:'synthetic',publicationAuthority:{acceptedTarget:target,commit,tree,policyVersion:1,actor:{userId:'owner',displayName:'Synthetic owner',viaToken:false},reviewedAt:'now',authorizedAt:'now'}} as PublicationJournalEntry;
 const scope:C03PublicationScope={caseId:crypto.randomUUID(),projectId:target.projectId,incarnation,candidateId:'candidate',ref:target.ref,commit,tree,workerVersion:crypto.randomUUID(),sourceVersion:'c'.repeat(40)};let authorized=true,pushes=0,publisherCalls=0,loseAck=false,dispatches=0,credentialClosed=0,withdrawAtDispatch=false,releaseDrift=false;
 const exec=async(command:string,env?:Record<string,string>,beforeDispatch?:()=>Promise<void>)=>{const isPush=command.includes(' push --quiet --force-with-lease=');if(isPush&&withdrawAtDispatch)authorized=false;await beforeDispatch?.();if(isPush)pushes++;const child=Bun.spawn(['sh','-c',command.replaceAll('/workspace/publish',workspace)],{stdout:'pipe',stderr:'pipe',env:{...process.env,...env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});const[stdout,stderr,exitCode]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return{success:exitCode===0,stdout,stderr,exitCode};};
 const ledger={getState:async()=>({projectId:target.projectId,canonicalRepoName:target.canonicalRepoName,defaultBranch:'main'}),observeCandidatePublicationReadback:async()=>({status:'not_landed',ref:target.ref,commit}),authorizeCandidatePublication:async()=>authorized,markCandidatePublicationDispatch:async()=>{dispatches++;return authorized},prepareRetainedInput:async()=>({id:'synthetic-retained-input'})} as unknown as Ledger;
 const workflow=new FlareGitIntegrationWorkflow({} as ExecutionContext,{} as Env);Object.assign(workflow,{computeWorkflowId:'synthetic-workflow',sandbox:async()=>({exec,destroy:async()=>{await rm(workspace,{recursive:true,force:true})}}),canonicalRemote:async()=>({remote:canonical,token:'synthetic-local-unused',close:async()=>{credentialClosed++}}),fundedRetainedCommand:async()=>{}});
 // Test-only access to the existing private method; its actual CAS/dispatch body is unchanged.
 const native=workflow as unknown as {casPush(candidate:CandidateGeneration,commit:string,ledger:Ledger,branch:string,journal:PublicationJournalEntry):Promise<{ok:true;readbackScope?:string}|{ok:false;error:string;stale?:boolean}>};
 const sql:C03CheckpointSql={transactionSync:<T>(operation:()=>T)=>db.transaction(operation)(),exec:(query,...bindings)=>{const rows=db.query(query).all(...bindings) as {doc:string}[];return{toArray:()=>rows}}};const make=()=>createC03PublicationAdapter(sql,{scope,candidate,journal,state:{projectId:target.projectId,canonicalRepoName:target.canonicalRepoName,defaultBranch:'main'},ledger,runtimeRelease:()=>({workerVersion:releaseDrift?crypto.randomUUID():scope.workerVersion,sourceVersion:scope.sourceVersion}),publish:async(...args)=>{publisherCalls++;const result=await native.casPush(...args);if(result.ok&&loseAck)throw Error('Lost synthetic caller ACK');return result;},readback:{exec,directory:reader,remote:canonical,token:'synthetic-local-unused'}});return{directory,seed,canonical,git,scope,make,invocation:crypto.randomUUID(),request:crypto.randomUUID(),base,journal,originalJournal:JSON.stringify(journal),driftRelease:()=>{releaseDrift=true},pushes:()=>pushes,calls:()=>publisherCalls,dispatches:()=>dispatches,closed:()=>credentialClosed,loseAck:()=>{loseAck=true},withdrawDispatch:()=>{withdrawAtDispatch=true},withdraw:()=>{authorized=false},close:async()=>{db.close();await rm(directory,{recursive:true,force:true})}};}
test('owner-bound actual production casPush pauses before writing and preserves exact CAS, dispatch fence and clone',async()=>{const f=await fixture();try{const driver=f.make();await driver.run(f.scope,f.invocation,f.request,'before-ref-update');expect(f.calls()).toBe(0);await driver.resume(f.scope,f.invocation,f.request,crypto.randomUUID());expect(f.pushes()).toBe(1);expect(f.dispatches()).toBe(1);expect(f.closed()).toBe(1);expect((await driver.reconcile(f.scope,f.invocation,f.request)).landed).toBe(true);const clone=join(f.directory,'clone');await f.git('clone',f.canonical,clone);expect(await f.git('-C',clone,'rev-parse','HEAD')).toBe(f.scope.commit);}finally{await f.close();}},30000);
test('after interruption plus lost caller ACK use independent production history readback without second casPush',async()=>{for(const lost of [false,true]){const f=await fixture();try{if(lost)f.loseAck();const driver=f.make();if(lost)await expect(driver.run(f.scope,f.invocation,f.request,'after-ref-update')).rejects.toThrow('Lost');else expect(await driver.run(f.scope,f.invocation,f.request,'after-ref-update')).toMatchObject({phase:'held-after'});let preservedHead=f.scope.commit;if(lost){await f.git('-C',f.seed,'checkout','main');await Bun.write(join(f.seed,'later.txt'),'later accepted contributor');await f.git('-C',f.seed,'add','later.txt');await f.git('-C',f.seed,'commit','-m','later contributor');preservedHead=await f.git('-C',f.seed,'rev-parse','HEAD');await f.git('-C',f.seed,'push',f.canonical,preservedHead+':refs/heads/main');}f.withdraw();f.driftRelease();expect((await f.make().reconcile(f.scope,f.invocation,f.request)).landed).toBe(true);expect(f.calls()).toBe(1);expect(f.pushes()).toBe(1);expect(JSON.stringify(f.journal)).toBe(f.originalJournal);expect(await f.git('--git-dir',f.canonical,'rev-parse','refs/heads/main')).toBe(preservedHead);}finally{await f.close();}}},30000);
test('actual final dispatch authority withdrawal refuses production push and preserves accepted ref',async()=>{const f=await fixture();try{f.withdrawDispatch();await expect(f.make().run(f.scope,f.invocation,f.request,'after-ref-update')).rejects.toThrow('authority changed');expect(f.pushes()).toBe(0);expect(await f.git('--git-dir',f.canonical,'rev-parse','refs/heads/main')).toBe(f.base);expect(f.closed()).toBe(1);}finally{await f.close();}},30000);
test('actual force-with-lease refuses stale canonical base without losing newer contributor commit',async()=>{const f=await fixture();try{await f.git('-C',f.seed,'checkout','-b','concurrent',f.base);await Bun.write(join(f.seed,'other.txt'),'new contributor');await f.git('-C',f.seed,'add','other.txt');await f.git('-C',f.seed,'commit','-m','concurrent');const concurrent=await f.git('-C',f.seed,'rev-parse','HEAD');await f.git('-C',f.seed,'push',f.canonical,concurrent+':refs/heads/main');await expect(f.make().run(f.scope,f.invocation,f.request,'after-ref-update')).rejects.toThrow('unconfirmed');expect(await f.git('--git-dir',f.canonical,'rev-parse','refs/heads/main')).toBe(concurrent);expect(f.pushes()).toBe(1);}finally{await f.close();}},30000);

test('trusted server release drift refuses new writes while preserving original prepared journal',async()=>{const f=await fixture();try{const driver=f.make();await driver.run(f.scope,f.invocation,f.request,'before-ref-update');f.driftRelease();await expect(driver.resume(f.scope,f.invocation,f.request,crypto.randomUUID())).rejects.toThrow('runtime release changed');expect(f.calls()).toBe(0);expect(f.pushes()).toBe(0);expect(JSON.stringify(f.journal)).toBe(f.originalJournal);expect(await f.git('--git-dir',f.canonical,'rev-parse','refs/heads/main')).toBe(f.base);}finally{await f.close();}},30000);
