import {test,expect} from 'bun:test';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {gitOrThrow,PLATFORM_IDENTITY} from '../src/core/pipeline/git';
import {publishAcceptedCandidate,type PublishResult} from '../src/core/pipeline/accept';
import {type CandidateGeneration,type VerificationEvidence,type PublicationJournalEntry} from '../src/core/types';
// Deterministic overlapping production publisher invocations at the real CAS
// boundary. Local Git proof only; no hosted concurrency or human-review claim.
test('two publishers prepared on one base land once and preserve both candidate histories',async()=>{const root=await mkdtemp(join(tmpdir(),'flaregit-c03-race-')),work=join(root,'work'),canonical=join(root,'canonical.git');try{await mkdir(work);gitOrThrow(work,['init','-b','main']);await Bun.write(join(work,'base.txt'),'base');gitOrThrow(work,['add','.']);gitOrThrow(work,[...PLATFORM_IDENTITY,'commit','-m','base']);const base=gitOrThrow(work,['rev-parse','HEAD']);gitOrThrow(root,['init','--bare',canonical]);gitOrThrow(work,['push',canonical,`${base}:refs/heads/main`]);const make=async(id:string)=>{gitOrThrow(work,['checkout','--detach',base]);await Bun.write(join(work,`${id}.txt`),id);gitOrThrow(work,['add','.']);gitOrThrow(work,[...PLATFORM_IDENTITY,'commit','-m',id]);const commit=gitOrThrow(work,['rev-parse','HEAD']),tree=gitOrThrow(work,['rev-parse','HEAD^{tree}']),ref=`refs/flaregit/candidates/${id}`;gitOrThrow(work,['update-ref',ref,commit]);const candidate:CandidateGeneration={id,attemptNumber:1,participatingTaskIds:[id],participatingCommits:{[id]:commit},expectedAcceptedBase:base,frozenPolicyVersion:1,frozenVerificationPolicy:{},frozenRequirements:[],candidateCommit:commit,repairAttempts:[],status:'verified',createdAt:'now',updatedAt:'now'};const evidence:VerificationEvidence={id:`proof-${id}`,candidateCommit:commit,candidateTree:tree,expectedAcceptedBase:base,requirementsVersion:1,policy:{},testBundleDigest:'fixture',toolchainDigest:'fixture',builtOutputDigest:'fixture',verifierIdentity:'synthetic-native',testResults:[],timestamp:'now',status:'passed'};return{canonicalRepoDir:canonical,defaultBranch:'main',candidate,evidence,candidateRepoDir:work,candidateRef:ref};};const a=await make('publisher-a'),b=await make('publisher-b'),journals:PublicationJournalEntry[]=[];let winner:PublishResult|undefined;const loser=publishAcceptedCandidate({...a,onJournal:entry=>{journals.push(entry);if(entry.state==='PREPARED')winner=publishAcceptedCandidate({...b,onJournal:row=>journals.push(row)});}});expect(winner?.success).toBe(true);expect(loser.success).toBe(false);expect(loser.staleBase).toBe(true);expect(journals.filter(row=>row.state==='ACCEPTED')).toHaveLength(1);expect(journals.filter(row=>row.state==='PREPARED')).toHaveLength(2);expect(gitOrThrow(canonical,['rev-parse','refs/heads/main'],{gitDir:true})).toBe(b.candidate.candidateCommit!);for(const candidate of [a,b]){expect(gitOrThrow(canonical,['rev-parse',candidate.candidateRef],{gitDir:true})).toBe(candidate.candidate.candidateCommit!);expect(gitOrThrow(canonical,['cat-file','-t',candidate.candidate.candidateCommit!],{gitDir:true})).toBe('commit');}const clone=join(root,'fresh');gitOrThrow(root,['clone','--branch','main',canonical,clone]);expect(gitOrThrow(clone,['rev-parse','HEAD'])).toBe(b.candidate.candidateCommit!);expect(gitOrThrow(clone,['show','HEAD:publisher-b.txt'])).toBe('publisher-b');}finally{await rm(root,{recursive:true,force:true});}});
