import {test,expect} from 'bun:test';import {checkedCandidateRuntimeInspection,runtimeRecordSummary,canRecordVerificationClosure} from '../src/web/candidate-runtime-inspection';
const report={candidateId:'candidate',workflowId:'workflow',incarnation:'11111111-1111-4111-8111-111111111111',protocol:1,checkedAt:1,verificationClosure:{status:'absent',credentials:{status:'absent',count:null}},coverage:true,sealed:false,status:'held',allocations:[{nativeRunId:'22222222-2222-4222-8222-222222222222',stage:'integrate-candidate',stopped:false}],commands:{total:1,pending:1,completed:0,refused:0},source:'recorded-ledger',providerVerified:false};
test('pending acknowledgements never claim live execution or cleanup',()=>{expect(runtimeRecordSummary(checkedCandidateRuntimeInspection(report,'candidate','workflow'))).toBe('Waiting for the check workspace to confirm its last steps');});
test('recorded cleanup requires sealed stopped allocations and settled commands',()=>{const settled={...report,sealed:true,status:'stopped',allocations:report.allocations.map(value=>({...value,stopped:true})),commands:{total:1,pending:0,completed:1,refused:0}};expect(runtimeRecordSummary(checkedCandidateRuntimeInspection(settled,'candidate','workflow'))).toBe('Checks finished and their workspaces were cleaned up');expect(()=>checkedCandidateRuntimeInspection({...settled,allocations:report.allocations},'candidate','workflow')).toThrow();});
test('wrong run, misleading provider claims and inconsistent totals are refused',()=>{for(const raw of [{...report,candidateId:'other'},{...report,workflowId:'other'},{...report,providerVerified:true},{...report,commands:{...report.commands,total:2}}])expect(()=>checkedCandidateRuntimeInspection(raw,'candidate','workflow')).toThrow();});

test('closure recovery remains unavailable until stopped allocations and command acknowledgements are recorded',()=>{const pending=checkedCandidateRuntimeInspection(report,'candidate','workflow');expect(canRecordVerificationClosure(pending,'b'.repeat(40),'evidence')).toBe(false);const ready=checkedCandidateRuntimeInspection({...report,allocations:report.allocations.map(value=>({...value,stopped:true})),commands:{total:1,pending:0,completed:1,refused:0}},'candidate','workflow');expect(canRecordVerificationClosure(ready,'b'.repeat(40),'evidence')).toBe(true);expect(canRecordVerificationClosure({...ready,verificationClosure:{status:'closed',credentials:{status:'revoked',count:0}}},'b'.repeat(40),'evidence')).toBe(false);});

test('verified stopped composition is distinct from an unsealed workflow and a later publisher allocation',()=>{const verified=checkedCandidateRuntimeInspection({...report,verificationClosure:{status:'closed',credentials:{status:'revoked',count:3}},allocations:report.allocations.map(value=>({...value,stopped:true})),commands:{total:33,pending:0,completed:33,refused:0}},'candidate','workflow');expect(runtimeRecordSummary(verified)).toBe('Checks finished; cleanup is still running');const publisher={...verified,allocations:[...verified.allocations!,{nativeRunId:'33333333-3333-4333-8333-333333333333',stage:'publish-candidate',stopped:false}]};expect(runtimeRecordSummary(checkedCandidateRuntimeInspection(publisher,'candidate','workflow'))).toBe('A check workspace has not confirmed that it stopped');expect(runtimeRecordSummary(checkedCandidateRuntimeInspection({...publisher,commands:{total:34,pending:1,completed:33,refused:0}},'candidate','workflow'))).toBe('Waiting for the check workspace to confirm its last steps');expect(runtimeRecordSummary(checkedCandidateRuntimeInspection({...verified,sealed:true,status:'stopped'},'candidate','workflow'))).toBe('Checks finished and their workspaces were cleaned up');});
