import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {CommunityPeople,discoveredProfile,type PeopleSnapshot} from "../src/server/community-people";
import {publicPeople,privatePeople} from "../src/server/community-people-http";
import type {Env} from "../src/server/env";
function ledger(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){if(query.startsWith("CREATE TABLE")){db.exec(query);return {toArray:()=>[]};}const rows=db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};return new CommunityPeople(storage as unknown as DurableObjectStorage);}
const published:PeopleSnapshot={active:true,profile:{profile:{handle:"ada",displayName:"Ada",bio:"Public biography",joinedAt:"2026-10-03"},visibility:"public",version:1,ownerId:"private-owner"},discovery:{enabled:true,version:1,delivery:"delivered",publicationVersion:1,handle:"ada"}};
const registration={accountKey:"private-account",handle:"ada",version:1,publicationVersion:1,enabled:true};
test("discovery requires separate consent and CAS, and rejects private/moderated/version changed publication",()=>{const saved=ledger();expect(saved.state().enabled).toBe(false);expect(()=>saved.configure({enabled:true,confirmed:false,expectedVersion:0},published.profile)).toThrow();expect(()=>saved.configure({enabled:true,confirmed:true,expectedVersion:0},{...published.profile,visibility:"private"})).toThrow();expect(saved.configure({enabled:true,confirmed:true,expectedVersion:0},published.profile).delivery).toBe("pending");saved.delivered(1);expect(saved.state().delivery).toBe("delivered");expect(()=>saved.configure({enabled:false,confirmed:true,expectedVersion:0},published.profile)).toThrow();expect(discoveredProfile(registration,published)?.handle).toBe("ada");expect(discoveredProfile(registration,{...published,active:false})).toBeNull();expect(discoveredProfile(registration,{...published,profile:{...published.profile,version:2}})).toBeNull();expect(discoveredProfile(registration,{...published,discovery:{...published.discovery,enabled:false}})).toBeNull();});
test("directory replay cannot revive withdrawn index and pagination does not skip reused handles",()=>{const saved=ledger();for(let index=0;index<22;index++)saved.register({...registration,accountKey:`account-${index}`});const first=saved.page();expect(first.rows).toHaveLength(20);expect(first.nextCursor).toBe("20");expect(saved.page(first.nextCursor!).rows).toHaveLength(2);saved.register({...registration,version:2,enabled:false});saved.register(registration);expect(saved.page().rows.some(row=>row.accountKey===registration.accountKey)).toBe(false);});
test("private following records bind original identities and stable replay reports current state",()=>{const saved=ledger(),target={accountKey:"private-target",ownerId:"private-owner",handle:"ada"};const input={following:true,expectedVersion:0,idempotencyKey:crypto.randomUUID()};const first=saved.setFollowing(target,input);expect(first.record.version).toBe(1);expect(saved.setFollowing(target,input).replayed).toBe(true);expect(()=>saved.setFollowing({...target,accountKey:"hijacker"},input)).toThrow();expect(()=>saved.setFollowing(target,{...input,idempotencyKey:crypto.randomUUID()})).toThrow();saved.setFollowing(target,{following:false,expectedVersion:1,idempotencyKey:crypto.randomUUID()});expect(saved.replayFollowing("ada",input)?.record.following).toBe(false);expect(saved.followingForHandle("ada")).toBeNull();});
function environment(stubs:Record<string,object>){return {REPOSITORY_CONTROLLER:{idFromName:(name:string)=>name,get:(name:string)=>{const stub=stubs[name];if(!stub)throw new Error("Unexpected metadata scope");return stub;}}} as unknown as Env;}
test("public discovery rechecks withdrawal after registry await and returns no internal identities",async()=>{let active=true;const env=environment({global:{peoplePage:async()=>({rows:[registration],nextCursor:null}),accountForHandle:async()=>{active=false;return registration.accountKey;}},[`account:${registration.accountKey}`]:{peopleSnapshot:async()=>({...published,active})}});const reply=await publicPeople(env,new URL("https://flaregit.test/api/community/people"));const body=await reply.json() as {people:unknown[];incomplete:boolean};expect(body.people).toEqual([]);expect(body.incomplete).toBe(true);expect(reply.headers.get("cache-control")).toBe("no-store");expect(JSON.stringify(body)).not.toContain("private-");expect((await publicPeople(env,new URL("https://flaregit.test/api/community/people?q=a&q=b"))).status).toBe(400);});
test("owner can remove withdrawn followed person and replay without resolving a reassigned handle",async()=>{const saved=ledger(),target={accountKey:"original-account",ownerId:"original-owner",handle:"ada"};saved.setFollowing(target,{following:true,expectedVersion:0,idempotencyKey:crypto.randomUUID()});const input={following:false,expectedVersion:1,idempotencyKey:crypto.randomUUID()};let lookups=0;const account={followingForHandle:async(handle:string)=>saved.followingForHandle(handle),replayFollowing:async(handle:string,input:unknown)=>saved.replayFollowing(handle,input),setFollowing:async(target:Parameters<CommunityPeople["setFollowing"]>[0],input:unknown)=>saved.setFollowing(target,input),followingRecord:async(key:string)=>saved.followingRecord(key)};const env=environment({"account:viewer":account,global:{accountForHandle:async()=>{lookups++;return null;}}});const call=()=>privatePeople({env,url:new URL("https://flaregit.test/api/following/ada"),accountKey:"viewer",userId:"viewer-owner",viaToken:false,method:"PUT",body:async()=>input});expect((await call())!.status).toBe(200);expect((await (await call())!.json() as {replayed:boolean}).replayed).toBe(true);expect(saved.followingRecord(target.accountKey)?.following).toBe(false);expect(lookups).toBe(0);});
function feedFixture(repositoryName="Public project"){const saved=ledger();saved.setFollowing({accountKey:registration.accountKey,ownerId:published.profile.ownerId!,handle:"ada"},{following:true,expectedVersion:0,idempotencyKey:crypto.randomUUID()});let listed=true;let active=true;let repositoryReads=0;const repository={publicAcceptedActivity:async()=>{repositoryReads++;return {directory:{enabled:listed,version:1,delivery:"delivered"},grant:listed?{name:repositoryName,version:1,acceptedCommit:"a".repeat(40)}:null,contributions:listed?[{commit:"b".repeat(40),acceptedAt:"2026-10-03T00:00:00Z"}]:[]};}};const env=environment({global:{accountForHandle:async()=>registration.accountKey},"account:viewer":{followingPage:async()=>saved.followingPage(),followingRecord:async(key:string)=>saved.followingRecord(key)},[`account:${registration.accountKey}`]:{peopleSnapshot:async()=>({...published,active}),publicActivityProjects:async()=>[{id:"p123456abcdef"}]},"project:p123456abcdef":repository});const call=()=>privatePeople({env,url:new URL("https://flaregit.test/api/community/following-activity"),accountKey:"viewer",userId:"viewer-owner",viaToken:false,method:"GET",body:async()=>({})});return {call,env,saved,repository,setListed:(value:boolean)=>{listed=value;},setActive:(value:boolean)=>{active=value;},reads:()=>repositoryReads};}
test("followed acceptance feed exposes recorded public metadata only and excludes private/unlisted repositories",async()=>{const fixture=feedFixture(),reply=(await fixture.call())!,body=await reply.json() as {items:Array<{kind:string;actor:{handle:string};commit:string}>;incomplete:boolean};expect(body.items).toHaveLength(1);expect(body.items[0]!.kind).toBe("accepted-contribution");expect(body.items[0]!.actor.handle).toBe("ada");expect(body.items[0]!.commit).toBe("b".repeat(40));expect(JSON.stringify(body)).not.toContain("private-");expect(fixture.reads()).toBe(3);fixture.setListed(false);expect((await (await fixture.call())!.json() as {items:unknown[]}).items).toEqual([]);});
test("repository withdrawal during final profile recheck excludes previously read accepted commits",async()=>{const fixture=feedFixture();let reads=0;const namespace=fixture.env.REPOSITORY_CONTROLLER as unknown as {get(name:string):object};const account=namespace.get(`account:${registration.accountKey}`) as {peopleSnapshot():Promise<PeopleSnapshot>};account.peopleSnapshot=async()=>{if(++reads>=2)fixture.setListed(false);return published;};const body=await (await fixture.call())!.json() as {items:unknown[];incomplete:boolean};expect(body.items).toEqual([]);expect(body.incomplete).toBe(true);});
test("private API tokens cannot manage social preferences or read private following",async()=>{const fixture=feedFixture();expect((await privatePeople({env:fixture.env,url:new URL("https://flaregit.test/api/following"),accountKey:"viewer",userId:"viewer-owner",viaToken:true,method:"GET",body:async()=>({})}))!.status).toBe(403);});

test("accepted activity redacts credential-bearing repository names without changing committed identity",async()=>{const fixture=feedFixture("Project https://example.test/?token=sensitive-fixture"),body=await (await fixture.call())!.json() as {items:Array<{repository:{name:string};commit:string}>};expect(body.items[0]!.repository.name).toBe("Project [REDACTED URL]");expect(body.items[0]!.commit).toBe("b".repeat(40));expect(JSON.stringify(body)).not.toContain("sensitive-fixture");});
