import {afterEach,expect,test} from 'bun:test';import {checkedMigrationManifest,checkedMigrationState,migrationPublishIntent,publishConversationManifest} from '../src/web/conversation-migration';
const originalFetch=globalThis.fetch;afterEach(()=>{globalThis.fetch=originalFetch;});
const excluded=['inline-review-comments','timelines','discussions','reactions','attachments'] as const;
const scope={operationId:'saved-operation',projectId:'p123456789abc',incarnation:'12345678-1234-4234-8234-123456789abc',ownerId:'owner',provider:'github' as const,repositoryId:'9007199254740993',repositoryNodeId:'R_source',sourceUrl:'https://github.com/example/repo'};
const snapshot={scope,status:'complete' as const,revision:2,cursor:null,issues:1,pullRequests:1,comments:2,missing:1,capturedPages:2,scopeOfCompletion:'supplied-issues-and-issue-comments-pagination-only' as const,published:false as const};
const state={snapshot,publication:null};
const manifest={manifest:{hash:'a'.repeat(64),revision:2,scope,status:'complete' as const,counts:{issues:1,pullRequests:1,comments:2,missing:1},scopeOfCompletion:snapshot.scopeOfCompletion,excluded:[...excluded],atomicSourceSnapshot:false as const,published:false as const},missing:[{kind:'comment',sourceId:'7',reason:'Unavailable'}],issuePreview:[],commentPreview:[]};
test('migration state and manifest preserve exact source identities, staging scope and missing records',()=>{const saved=checkedMigrationState(state,scope.projectId,scope.operationId);const checked=checkedMigrationManifest(manifest,saved);expect(checked.manifest.scope.repositoryId).toBe('9007199254740993');expect(checked.manifest.published).toBe(false);expect(checked.manifest.atomicSourceSnapshot).toBe(false);expect(checked.missing).toHaveLength(1);expect(()=>checkedMigrationManifest({...manifest,issuePreview:[{providerId:'12',kind:'issue',sourceUrl:'https://github.com/other/repo/issues/12',actor:{login:'external'},title:'Wrong repository',body:'',createdAt:'2026-10-04T00:00:00Z',updatedAt:'2026-10-04T00:00:00Z',identity:'external-unclaimed',nativeUserId:null}]},saved)).toThrow('Preview origin');expect(()=>checkedMigrationState(state,'pabcdef123456')).toThrow();expect(()=>checkedMigrationManifest({...manifest,manifest:{...manifest.manifest,revision:3}},saved)).toThrow();expect(()=>checkedMigrationManifest({...manifest,manifest:{...manifest.manifest,scope:{...scope,sourceUrl:'https://secret@github.com/example/repo'}}},saved)).toThrow();});
test('publication request stays stable after lost ACK and changes only with confirmed progress or manifest',()=>{const parsedState=checkedMigrationState(state,scope.projectId);const parsedManifest=checkedMigrationManifest(manifest,parsedState);const intent=migrationPublishIntent(null,parsedState,parsedManifest);expect(migrationPublishIntent(intent,parsedState,parsedManifest)).toBe(intent);const publication={operationId:scope.operationId,manifestHash:manifest.manifest.hash,revision:2,phase:'comments' as const,issueCursor:'11',commentCursor:'0',nativeIssues:1,nativeComments:0,archivedPullRequests:1,archivedPullRequestComments:0,sourceMissing:1,excluded:[...excluded],atomicSourceSnapshot:false as const};const progressed=checkedMigrationState({...state,publication},scope.projectId);expect(migrationPublishIntent(intent,progressed,parsedManifest).eventId).not.toBe(intent.eventId);expect(()=>checkedMigrationState({...state,publication:{...publication,phase:'complete'}},scope.projectId)).toThrow();});
test('lost acknowledgement retry sends same exact manifest, never Git content or provider credentials',async()=>{const saved=checkedMigrationState(state,scope.projectId),parsed=checkedMigrationManifest(manifest,saved),intent=migrationPublishIntent(null,saved,parsed),requests:unknown[]=[];globalThis.fetch=Object.assign(async(url:string|URL|Request,init?:RequestInit)=>{expect(url).toBe('/api/p/p123456789abc/conversation-migrations/saved-operation/publish');requests.push(JSON.parse(String(init?.body)));throw Error('lost ACK');},{preconnect:originalFetch.preconnect});for(let n=0;n<2;n++)await expect(publishConversationManifest(scope.projectId,parsed,intent.eventId,AbortSignal.timeout(15000))).rejects.toThrow();expect(requests).toEqual([{eventId:intent.eventId,expectedRevision:2,manifestHash:'a'.repeat(64)},{eventId:intent.eventId,expectedRevision:2,manifestHash:'a'.repeat(64)}]);});

import {beginConversationMigration,ConversationMigrationError,migrationActionSignal,migrationReadSignal,migrationFailureMessage} from '../src/web/conversation-migration';
test('migration actions allow metadata plus authority overhead while reads retain shorter deadlines',()=>{const timeout=AbortSignal.timeout,delays:number[]=[];AbortSignal.timeout=(ms:number)=>{delays.push(ms);return new AbortController().signal;};try{const abort=new AbortController(),deadline=new AbortController();const action=migrationActionSignal(abort.signal,deadline.signal),read=migrationReadSignal(abort.signal);expect(delays).toEqual([30000,15000]);deadline.abort();expect(action.aborted).toBe(true);expect(read.aborted).toBe(false);abort.abort();expect(read.aborted).toBe(true);}finally{AbortSignal.timeout=timeout;}});
test('safe rate and budget failures preserve retry-after without exposing provider detail or asking for credentials',async()=>{globalThis.fetch=Object.assign(async()=>Response.json({category:'read_budget_exhausted',error:'https://user:secret@provider.invalid/token',retryAfterSeconds:30},{status:429,headers:{'Retry-After':'30'}}),{preconnect:originalFetch.preconnect});try{await beginConversationMigration(scope.projectId,'saved-operation',AbortSignal.timeout(30000));throw Error('Expected bounded failure');}catch(error){expect(error).toBeInstanceOf(ConversationMigrationError);const message=migrationFailureMessage(error);expect(message).toContain('read budget is exhausted');expect(message).toContain('Retry after 30 seconds');expect(message).not.toContain('secret');expect(message).not.toContain('token');}expect(migrationFailureMessage(new DOMException('timeout','TimeoutError'))).toContain('did not finish in time');expect(migrationFailureMessage(new ConversationMigrationError('source_inaccessible',404,null))).not.toContain('private');});

test('unknown HTTP throttling is not presented as proof of a GitHub rate limit',async()=>{globalThis.fetch=Object.assign(async()=>Response.json({error:'Unknown limiter'},{status:429,headers:{'Retry-After':'10'}}),{preconnect:originalFetch.preconnect});try{await beginConversationMigration(scope.projectId,'saved-operation',AbortSignal.timeout(30000));throw Error('Expected failure');}catch(error){expect(error).toBeInstanceOf(ConversationMigrationError);expect(migrationFailureMessage(error)).not.toContain('GitHub has limited');}});

 test('existing publication binds the preview to its exact manifest hash',()=>{const publication={operationId:scope.operationId,manifestHash:manifest.manifest.hash,revision:2,phase:'comments' as const,issueCursor:'11',commentCursor:'0',nativeIssues:1,nativeComments:0,archivedPullRequests:1,archivedPullRequestComments:0,sourceMissing:1,excluded:[...excluded],atomicSourceSnapshot:false as const};const saved=checkedMigrationState({...state,publication},scope.projectId);expect(checkedMigrationManifest(manifest,saved).manifest.hash).toBe(publication.manifestHash);expect(()=>checkedMigrationManifest({...manifest,manifest:{...manifest.manifest,hash:'b'.repeat(64)}},saved)).toThrow('Published manifest identity changed');});
