import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {workerdChild} from './support/workerd-child';
test('native Worker capture preserves safe rate and timeout categories across DO RPC without staging failed reads',async()=>{
 if(await workerdChild('tests/conversation-migration-http.test.ts'))return;
 const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'migration-http',alg:'RS256',use:'sig'},issuer=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({keys:[jwk]})});let mf:Miniflare|undefined;
 try{const build=await Bun.build({entrypoints:['tests/support/conversation-migration-http-worker.ts'],target:'browser',external:['cloudflare:workers','node:*']});if(!build.success)throw Error('Fixture build failed');mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'migration-http',unsafeDirectSockets:[{host:'127.0.0.1'}],modules:true,script:await build.outputs[0]!.text(),compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],bindings:{FIXTURE_ISSUER:issuer.url.origin},durableObjects:{REPOSITORY_CONTROLLER:{className:'ConversationMigrationFixture',useSQLite:true}}}]}));
 const direct=await mf.unsafeGetDirectURL('migration-http'),token=await new SignJWT({azp:'https://fixture.example'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer.url.origin).setSubject('owner').setIssuedAt().setExpirationTime('5m').sign(pair.privateKey);
 const call=(path:string,body?:unknown)=>fetch(new URL(path,direct),{method:body===undefined?'GET':'POST',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.26',Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
 expect((await call('/fixture/seed')).status).toBe(200);const operation='/api/p/p123456789abc/conversation-migrations/migration-one';
 for(const [reason,status,category] of [['unconfigured',503,'read_budget_unconfigured'],['account_budget',429,'read_budget_exhausted'],['global_budget',429,'read_budget_exhausted']] as const){await call('/fixture/budget?reason='+reason);const response=await call(operation+'/capture',{expectedRevision:0});expect(response.status).toBe(status);expect(await response.json() as {category:string}).toMatchObject({category});expect(await(await call('/fixture/reads')).json() as {reads:number}).toEqual({reads:0});const saved=await(await call(operation)).json() as {snapshot:{revision:number;cursor:string|null}};expect(saved.snapshot).toMatchObject({revision:0,cursor:null});}await call('/fixture/budget?reason=none');
 for(const [mode,status,category] of [['rate_limited',429,'source_rate_limited'],['timeout',504,'source_timeout']] as const){await call('/fixture/mode?failure='+mode);const result=await call(operation+'/capture',{expectedRevision:0});expect(result.status).toBe(status);expect(result.headers.get('cache-control')).toBe('no-store');if(mode==='rate_limited')expect(result.headers.get('retry-after')).toBe('5');const body=await result.text();expect(JSON.parse(body) as {category:string}).toMatchObject({category});expect(body).not.toContain('untrusted provider body');const saved=await(await call(operation)).json() as {snapshot:{revision:number;issues:number;comments:number;status:string}};expect(saved.snapshot).toMatchObject({revision:0,issues:0,comments:0,status:'pending'});}
 await call('/fixture/mode?failure=none');const recovered=await call(operation+'/capture',{expectedRevision:0});expect(recovered.status).toBe(200);expect(await recovered.json() as {snapshot:{revision:number}}).toMatchObject({snapshot:{revision:1}});
 }finally{await mf?.dispose();issuer.stop(true);}
},40000);
