import {expect,test} from 'bun:test';
import {conversationMigrationFailure,conversationCaptureFailure,ConversationMigrationAuthorityError,ConversationMigrationCapacityError} from '../src/server/conversation-migration-failure';
import {GithubMigrationReadError} from '../src/server/github-migration-reader';
test('unknown failure diagnostics never enter owner responses',()=>{const result=conversationMigrationFailure(Error('Authorization Bearer SYNTHETIC_PRIVATE_TOKEN https://private.test/?secret=fixture'));expect(result.category).toBe('migration_unconfirmed');expect(JSON.stringify(result)).not.toContain('SYNTHETIC_PRIVATE_TOKEN');expect(JSON.stringify(result)).not.toContain('private.test');});
test('known capacity and authority outcomes remain distinct without inferring provider throttling',()=>{expect(conversationMigrationFailure(new ConversationMigrationCapacityError('unconfigured'))).toMatchObject({status:503,category:'read_budget_unconfigured'});expect(conversationMigrationFailure(new ConversationMigrationCapacityError('account_budget'))).toMatchObject({status:429,category:'read_budget_exhausted'});expect(conversationMigrationFailure(new ConversationMigrationAuthorityError())).toMatchObject({status:403,category:'owner_scope_changed'});});

test('verified source status and bounded retry delay become safe response categories',()=>{expect(conversationMigrationFailure(new GithubMigrationReadError('rate_limited',429,30))).toMatchObject({status:429,category:'source_rate_limited',retryAfterSeconds:30});expect(conversationMigrationFailure(new GithubMigrationReadError('auth',403))).toMatchObject({status:403,category:'source_inaccessible'});expect(conversationMigrationFailure(new GithubMigrationReadError('timeout'))).toMatchObject({status:504,category:'source_timeout'});expect(conversationMigrationFailure(new GithubMigrationReadError('rate_limited',429,9999))).not.toHaveProperty('retryAfterSeconds');});

test('RPC DTO categories are allowlisted without error name or message heuristics',()=>{const dto=JSON.parse(JSON.stringify({ok:false,failure:{code:'rate_limited',retryAfterSeconds:30}}));const failure=conversationCaptureFailure(dto);expect(conversationMigrationFailure(failure)).toMatchObject({status:429,category:'source_rate_limited',retryAfterSeconds:30});for(const value of [{ok:false,failure:{code:'invented'}},{ok:false,failure:{code:'timeout',message:'synthetic-token'}},{ok:false,failure:{code:'rate_limited',retryAfterSeconds:9999}},{name:'GithubMigrationReadError',code:'timeout',message:'synthetic-token'}])expect(conversationCaptureFailure(value)).toBeNull();});

test('capture budget DTO preserves known denial without inventing provider rate limits',()=>{for(const [code,status] of [['read_budget_unconfigured',503],['read_budget_exhausted',429]] as const){const dto=JSON.parse(JSON.stringify({ok:false,failure:{code}}));expect(conversationMigrationFailure(conversationCaptureFailure(dto))).toMatchObject({category:code,status});}expect(conversationCaptureFailure({ok:false,failure:{code:'read_budget_exhausted',retryAfterSeconds:30}})).toBeNull();});
