import {Database} from 'bun:sqlite';
import {test,expect} from 'bun:test';
import {CoreGitOperationLedger} from '../src/server/core-git-budget';
function fixture(){const db=new Database(':memory:'),queries:string[]=[];const storage={sql:{exec(query:string,...args:Array<string|number>){queries.push(query);const rows=db.query(query).all(...args);return{toArray:()=>rows};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}} as unknown as DurableObjectStorage;return{db,queries,ledger:new CoreGitOperationLedger(storage)};}
const paidMonth='2026-10',paidAt=new Date('2026-10-05T12:00:00Z'),caps={accountUsdMicros:1200,globalUsdMicros:1200};
test('exact original core reservation remains readable after caps exhaust without creating or changing any reservation',()=>{const f=fixture();try{expect(f.ledger.reserve('cleanup-original','account-original',caps,paidAt)).toMatchObject({allowed:true,existing:false});expect(f.ledger.reserve('unfunded-new','account-original',caps,paidAt)).toEqual({allowed:false,reason:'account_budget'});const before=f.db.query('SELECT * FROM core_git_operations').all();f.queries.length=0;const proof=f.ledger.existingCoreReservation('cleanup-original','account-original',paidMonth);expect(proof).toEqual({operationId:'cleanup-original',accountKey:'account-original',month:paidMonth,category:'core',reservedUsdMicros:1200,maxProviderOperations:8,basis:'conservative_operation_envelope'});expect(Object.isFrozen(proof)).toBe(true);expect(f.ledger.existingCoreReservation('cleanup-original','account-original',paidMonth)).toEqual(proof);expect(f.queries.every(query=>query.startsWith('SELECT '))).toBe(true);expect(f.db.query('SELECT * FROM core_git_operations').all()).toEqual(before);}finally{f.db.close();}});
test('historical exact proof reads never backdate or reset an original envelope into a later month',()=>{const f=fixture();try{f.ledger.reserve('cleanup-original','account-original',caps,paidAt);const before=f.db.query('SELECT * FROM core_git_operations').all();expect(()=>f.ledger.reserve('cleanup-original','account-original',caps,new Date('2026-11-01'))).toThrow('identity changed');expect(f.ledger.existingCoreReservation('cleanup-original','account-original',paidMonth)?.month).toBe(paidMonth);expect(f.ledger.existingCoreReservation('cleanup-original','account-original','2026-11')).toBeNull();expect(f.ledger.used('2026-11')).toBe(0);expect(f.db.query('SELECT * FROM core_git_operations').all()).toEqual(before);}finally{f.db.close();}});
test('absent foreign malformed and read-category rows cannot prove original core cleanup funding',()=>{const f=fixture();try{f.ledger.reserve('core-original','account-original',caps,paidAt);f.ledger.reserve('read-original','read-account',{accountUsdMicros:2400,globalUsdMicros:2400,readAccountUsdMicros:1200,readGlobalUsdMicros:1200},paidAt,'read');for(const [operation,account,month] of [['missing','account-original',paidMonth],['core-original','foreign-account',paidMonth],['core-original','account-original','2026-13'],['../bad','account-original',paidMonth],['core-original','',paidMonth],['read-original','read-account',paidMonth]] as const)expect(f.ledger.existingCoreReservation(operation,account,month)).toBeNull();expect(f.db.query('SELECT COUNT(*) AS n FROM core_git_operations').get()).toEqual({n:2});}finally{f.db.close();}});
test('malformed persisted reservation amount and category fail closed and reveal no global usage',()=>{const f=fixture();try{f.ledger.reserve('cleanup-original','account-original',caps,paidAt);for(const amount of[0,1199,1201,-1]){f.db.exec('UPDATE core_git_operations SET reserved='+amount);expect(f.ledger.existingCoreReservation('cleanup-original','account-original',paidMonth)).toBeNull();}f.db.exec("UPDATE core_git_operations SET reserved=1200,category='unknown'");expect(f.ledger.existingCoreReservation('cleanup-original','account-original',paidMonth)).toBeNull();f.db.exec("UPDATE core_git_operations SET category='core'");const proof=f.ledger.existingCoreReservation('cleanup-original','account-original',paidMonth);expect(Object.keys(proof??{}).sort()).toEqual(['accountKey','basis','category','maxProviderOperations','month','operationId','reservedUsdMicros']);}finally{f.db.close();}});
