import { Database } from "bun:sqlite";
import { expect,test } from "bun:test";
import { EvidenceStorageLedger } from "../src/server/evidence-storage.js";
const identity={projectId:"p123456789012",incarnation:"a".repeat(36),commit:"b".repeat(40),accountKey:"c".repeat(12)};
const sha="d".repeat(64);
function fixture(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...args:Array<string|number>){if(query.includes(";")){db.exec(query);return{toArray:()=>[],one:()=>({})};}const rows=db.query(query).all(...args);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}};return{db,ledger:new EvidenceStorageLedger(storage as unknown as DurableObjectStorage)};}
test("evidence reservations are immutable and jointly bound account/global bytes",()=>{const {db,ledger}=fixture();const budget={globalBytes:15,accountBytes:10};ledger.reserve(identity,"ev_11111111-111",10,sha,budget);ledger.reserve(identity,"ev_11111111-111",10,sha,budget);expect(db.query("SELECT SUM(bytes) AS bytes FROM evidence_storage_reservations").get()).toEqual({bytes:10});expect(()=>ledger.reserve(identity,"ev_22222222-222",1,sha,budget)).toThrow("allowance is exhausted");expect(()=>ledger.reserve({...identity,accountKey:"e".repeat(12)},"ev_33333333-333",6,sha,budget)).toThrow("allowance is exhausted");expect(()=>ledger.reserve(identity,"ev_11111111-111",9,sha,budget)).toThrow("identity changed");});
test("unknown uploads remain reserved and retired evidence cannot re-charge or write",()=>{const {db,ledger}=fixture();ledger.reserve(identity,"ev_44444444-444",8,sha,{globalBytes:8,accountBytes:8});expect(()=>ledger.reserve(identity,"ev_55555555-555",1,sha,{globalBytes:8,accountBytes:8})).toThrow();const key=`evidence/${identity.projectId}/${identity.incarnation}/ev_44444444-444.json`;db.query("INSERT INTO preview_copy_retirements VALUES(?,?)").run(key,"confirmed-absence-test-receipt");db.query("DELETE FROM evidence_storage_reservations WHERE physical_key=?").run(key);expect(()=>ledger.reserve(identity,"ev_44444444-444",8,sha,{globalBytes:8,accountBytes:8})).toThrow("Retired");expect(db.query("SELECT COUNT(*) AS n FROM evidence_storage_reservations").get()).toEqual({n:0});});
test("unconfigured evidence funding and oversized copies fail before reservation",()=>{const {ledger}=fixture();expect(()=>ledger.reserve(identity,"ev_44444444-444",1,sha,{globalBytes:null,accountBytes:10})).toThrow("not configured");expect(()=>ledger.reserve(identity,"ev_44444444-444",1024*1024+1,sha,{globalBytes:9000000,accountBytes:9000000})).toThrow("Invalid");});

test("unsupported evidence IDs are rejected before any byte reservation",()=>{const {db,ledger}=fixture();for(const id of ["proof1","ev_12345678-abcd","ev_12345678-ABc","../ev_12345678-abc"]){expect(()=>ledger.reserve(identity,id,1,sha,{globalBytes:100,accountBytes:100})).toThrow("Invalid");}expect(db.query("SELECT COUNT(*) AS n FROM evidence_storage_reservations").get()).toEqual({n:0});});
