import {expect,test} from 'bun:test';
import {freezeCandidateGeneration,type FreezeCandidateOptions} from '../src/core/pipeline/freeze';
import type {FrozenAcceptedTarget} from '../src/core/accepted-target';
import type {Task,Requirement} from '../src/core/types';
const requirement={id:'requirement',title:'Retain contribution',description:'Preserve checked work',version:1,status:'approved',assertions:[],originTaskId:'source',approvedAt:'2026-10-04T00:00:00Z'} satisfies Requirement;
function target():FrozenAcceptedTarget{return{projectId:'project',incarnation:'12345678-1234-4234-8234-123456789abc',canonicalRepoName:'canonical',ref:'refs/heads/release',branch:'release',acceptedCommit:'a'.repeat(40),acceptedVersion:4,requirements:[structuredClone(requirement)],policyVersion:3,policy:{checks:{test:'bun test'}}};}
function task(id:string,binding?:FrozenAcceptedTarget):Task{return{id,goal:'Preserve useful work',contributor:{id:'person',name:'Person',type:'human'},baseCommit:'a'.repeat(40),allowedScope:['src/'],status:'ready',requirements:[],workspace:{repoName:'workspace',remote:'https://fixture.test/repository',branch:'task/'+id},checkpoints:[],currentCommit:'b'.repeat(40),createdAt:'now',updatedAt:'now',...(binding?{acceptedTarget:binding}:{})};}
function options(binding=target()):FreezeCandidateOptions{return{tasks:[task('first',binding),task('second',structuredClone(binding))],acceptedTarget:binding,acceptedBaseCommit:binding.acceptedCommit,policyVersion:binding.policyVersion,verificationPolicy:structuredClone(binding.policy),approvedRequirements:structuredClone(binding.requirements)};}
test('explicit candidate freeze retains a fresh immutable target snapshot',()=>{const input=options(),candidate=freezeCandidateGeneration(input);expect(candidate.acceptedTarget).toEqual(input.acceptedTarget);expect(candidate.acceptedTarget).not.toBe(input.acceptedTarget);input.acceptedTarget!.requirements[0]!.title='Changed later';input.acceptedTarget!.policy.changed=true;input.verificationPolicy.changed=true;expect(candidate.acceptedTarget!.requirements[0]!.title).toBe('Retain contribution');expect(candidate.acceptedTarget!.policy).not.toHaveProperty('changed');expect(candidate.frozenVerificationPolicy).not.toHaveProperty('changed');expect(candidate.expectedAcceptedBase).toBe('a'.repeat(40));});
test('mixed scope, base, accepted version, requirements, or policy refuses a single candidate',()=>{expect(()=>freezeCandidateGeneration(options())).not.toThrow();for(const patch of [{branch:'other',ref:'refs/heads/other'},{incarnation:crypto.randomUUID()},{acceptedCommit:'c'.repeat(40)},{acceptedVersion:5},{policyVersion:4},{policy:{checks:{test:'other'}}},{requirements:[]}]){const input=options();input.tasks[1]=task('second',{...target(),...patch});expect(()=>freezeCandidateGeneration(input)).toThrow();}});
test('freeze options must match the accepted target base, policy, and requirements exactly',()=>{expect(()=>freezeCandidateGeneration(options())).not.toThrow();for(const patch of [{acceptedBaseCommit:'c'.repeat(40)},{policyVersion:4},{verificationPolicy:{checks:{test:'different'}}},{approvedRequirements:[]}])expect(()=>freezeCandidateGeneration({...options(),...patch})).toThrow();const input=options();input.tasks[1]=task('unbound');expect(()=>freezeCandidateGeneration(input)).toThrow('Every contribution');expect(()=>freezeCandidateGeneration({...options(),tasks:[]})).toThrow('requires contributions');});
test('legacy primary freeze is unchanged and explicit tasks cannot lose their target',()=>{const legacy=freezeCandidateGeneration({tasks:[task('legacy')],acceptedBaseCommit:'legacy-base',policyVersion:3,verificationPolicy:{x:1},approvedRequirements:[]});expect(legacy).not.toHaveProperty('acceptedTarget');expect(legacy.expectedAcceptedBase).toBe('legacy-base');expect(()=>freezeCandidateGeneration({...options(),acceptedTarget:undefined})).toThrow('cannot fall back');});

test('new approved task requirements join the frozen candidate without altering its accepted base binding',()=>{const input=options();const additional:Requirement={...structuredClone(requirement),id:'new-requirement',title:'New behavior',originTaskId:'first'};input.tasks[0]!.requirements.push(additional);input.approvedRequirements.push(structuredClone(additional));const candidate=freezeCandidateGeneration(input);expect(candidate.frozenRequirements.map(value=>value.id)).toEqual(['requirement','new-requirement']);expect(candidate.acceptedTarget!.requirements.map(value=>value.id)).toEqual(['requirement']);for(const requirements of [[requirement],[requirement,{...additional,title:'Substituted behavior'}],[requirement,{...additional,version:2}]])expect(()=>freezeCandidateGeneration({...input,approvedRequirements:requirements})).toThrow();});
