import {Database} from "bun:sqlite";
import {test,expect} from "bun:test";
import {ImportHistoryInspection,type HistoryChunk,type HistoryInspectionScope} from "../src/server/import-history-inspection.js";
const hash=(n:number)=>n.toString(16).padStart(40,"0"),tree="f".repeat(40);
const scope:HistoryInspectionScope={operationId:"import-history-11111111-1111-4111-8111-111111111111",projectId:"p123456789abc",incarnation:"11111111-1111-4111-8111-111111111111",ownerId:"owner",accountKey:"a".repeat(12),canonicalRepoName:"flaregit-p123456789abc",source:"https://github.com/acme/repo.git",branch:"main",head:hash(4)};
function fixture(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...args:Array<string|number>){if(query.includes(";")){db.exec(query);return{toArray:()=>[],one:()=>({})};}const rows=db.query(query).all(...args);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}};return{db,ledger:new ImportHistoryInspection(storage as unknown as DurableObjectStorage)};}
const graph=[{hash:hash(4),tree,parents:[hash(3),hash(2)]},{hash:hash(3),tree,parents:[hash(1)]},{hash:hash(2),tree,parents:[hash(1)]},{hash:hash(1),tree,parents:[]}];
const chunk=(ledger:ImportHistoryInspection,side:"source"|"destination",commits=graph):HistoryChunk=>{const batch=ledger.batch(scope.operationId,side);return{batchId:batch.batchId,revision:batch.revision,requested:batch.requested,commits};};
test("connected ancestry chunks deduplicate replay and compare only complete frontiers",async()=>{const {ledger,db}=fixture();ledger.begin(scope);const first=chunk(ledger,"source");expect((await ledger.commit(scope.operationId,"source",first)).kind).toBe("applied");expect((await ledger.commit(scope.operationId,"source",first)).kind).toBe("duplicate");expect(()=>ledger.finish(scope.operationId)).toThrow("incomplete");await ledger.commit(scope.operationId,"destination",chunk(ledger,"destination"));const result=ledger.finish(scope.operationId);expect(result.status).toBe("verified");expect(result.result?.commitsCompared).toBe(4);expect(result.result?.scope).toBe("selected-ref-reachable-commit-history");expect(db.query("SELECT MAX(length(payload)) AS n FROM history_chunks").get()).toEqual({n:64});expect(ledger.serializedBytes(scope.operationId)).toBeLessThan(8*1024*1024);});
test("fault before chunk commit rolls back nodes frontier revision and receipt",async()=>{const {ledger,db}=fixture();ledger.begin(scope);db.exec(`CREATE TRIGGER fail_history BEFORE INSERT ON history_nodes WHEN NEW.hash='${hash(2)}' BEGIN SELECT RAISE(ABORT,'synthetic history fault'); END`);const before=ledger.get(scope.operationId);await expect(ledger.commit(scope.operationId,"source",chunk(ledger,"source"))).rejects.toThrow("synthetic history fault");expect(ledger.get(scope.operationId)).toEqual(before);db.exec("DROP TRIGGER fail_history");await ledger.commit(scope.operationId,"source",chunk(ledger,"source"));expect(ledger.get(scope.operationId)?.source.count).toBe(4);});
test("replay changes arbitrary nodes and stale authority refuse without progress",async()=>{const {ledger}=fixture();ledger.begin(scope);const first=chunk(ledger,"source");await expect(ledger.commit(scope.operationId,"source",{...first,commits:[...graph,{hash:hash(99),tree,parents:[]}]})).rejects.toThrow("Unreachable");await expect(ledger.commit(scope.operationId,"source",first,async()=>{},()=>{throw new Error("attempt replaced");})).rejects.toThrow("attempt replaced");expect(ledger.get(scope.operationId)?.source.revision).toBe(0);await ledger.commit(scope.operationId,"source",first);await expect(ledger.commit(scope.operationId,"source",{...first,commits:graph.map(node=>({...node,tree:hash(88)}))})).rejects.toThrow("replay changed");});
test("ordered parent mismatch reports only matching commits as compared",async()=>{const {ledger}=fixture();ledger.begin(scope);await ledger.commit(scope.operationId,"source",chunk(ledger,"source"));await ledger.commit(scope.operationId,"destination",chunk(ledger,"destination",graph.map(node=>({...node,parents:[...node.parents].reverse()}))));const result=ledger.finish(scope.operationId);expect(result.status).toBe("mismatch");expect(result.result?.differentCommits).toEqual([hash(4)]);expect(result.result?.commitsCompared).toBe(3);});
test("frontier capacity rolls back then durably pauses without false verification",async()=>{const {ledger}=fixture();ledger.begin({...scope,head:hash(1000)});const commits=Array.from({length:256},(_,i)=>({hash:hash(1000+i),tree,parents:[...(i<255?[hash(1001+i)]:[]),...Array.from({length:128},(_,j)=>hash(100000+i*128+j))]}));const batch=ledger.batch(scope.operationId,"source"),result=await ledger.commit(scope.operationId,"source",{batchId:batch.batchId,revision:batch.revision,requested:batch.requested,commits});expect(result.kind).toBe("paused");expect(result.snapshot.reason).toBe("inspection_capacity");expect(result.snapshot.source.count).toBe(0);expect(result.snapshot.source.pending).toBe(1);expect(result.snapshot.source.revision).toBe(0);expect(()=>ledger.finish(scope.operationId)).toThrow("incomplete");});
