import {expect,test} from "bun:test";
import {rm} from "node:fs/promises";
import {readSourceHistoryChunk,readSourceHistoryTraversalChunk,preparePublicSourceHistoryClone,type HistoryExecutor} from "../src/server/import-source-history";
const env={...process.env,GIT_AUTHOR_NAME:"Synthetic source test",GIT_AUTHOR_EMAIL:"synthetic@localhost",GIT_COMMITTER_NAME:"Synthetic source test",GIT_COMMITTER_EMAIL:"synthetic@localhost"};
async function git(args:string[],input?:string){const child=Bun.spawn(["git",...args],{env,stdin:input===undefined?"ignore":"pipe",stdout:"pipe",stderr:"pipe"});if(input!==undefined){if(!child.stdin)throw Error("Missing native Git stdin");child.stdin.write(input);child.stdin.end();}const[out,error,exit]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(exit)throw Error(error);return out.trim();}
test("explicit native source frontier traverses 1101 commits and preserves ordered merge parents",async()=>{
 const directory=`/tmp/flaregit-import-history-${crypto.randomUUID()}`;
 try{
  await git(["init","--bare",directory]);const tree=await git(["--git-dir",directory,"mktree"],"");let stream="";for(let index=1;index<=1101;index++){const message=`Synthetic ${index}`;stream+=`commit refs/heads/main\nmark :${index}\ncommitter Synthetic <synthetic@localhost> ${1700000000+index} +0000\ndata ${message.length}\n${message}\n${index>1?`from :${index-1}\n`:""}\n`;}await git(["--git-dir",directory,"fast-import","--quiet"],stream);const head=await git(["--git-dir",directory,"rev-parse","main"]);
  const side=await git(["--git-dir",directory,"commit-tree",tree,"-p",head,"-m","Synthetic side"]),merge=await git(["--git-dir",directory,"commit-tree",tree,"-p",head,"-p",side,"-m","Synthetic merge"]);
  let reads=0,maxBatch=0;const executor:HistoryExecutor={exec:async(command)=>{expect(command).not.toContain("checkout");const child=Bun.spawn(["sh","-c",command],{env,stdout:"pipe",stderr:"pipe"});const[stdout,stderr,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return{success:code===0,stdout,stderr};}};
  const first=await readSourceHistoryChunk(executor,directory,[merge],async()=>{reads++;});expect(first.commits[merge]?.parents).toEqual([head,side]);expect(first.shallow).toBe(false);
  const seen=new Set<string>();let chunks=0;const frontier=[merge];const records:Record<string,{tree:string;parents:string[]}>= {};
  while(frontier.length){const batch=frontier.splice(0,256).filter(hash=>!seen.has(hash));if(!batch.length)continue;maxBatch=Math.max(maxBatch,batch.length);const result=await readSourceHistoryTraversalChunk(executor,directory,batch);chunks++;Object.assign(records,result.commits);for(const hash of Object.keys(result.commits))seen.add(hash);for(const record of Object.values(result.commits))for(const parent of record.parents)if(!seen.has(parent)&&!frontier.includes(parent))frontier.push(parent);for(const root of batch)if(!seen.has(root)&&!frontier.includes(root))frontier.push(root);}
  for(const record of Object.values(records))expect(record.parents.every(parent=>seen.has(parent))).toBe(true);
  expect(seen.size).toBe(1103);expect(chunks).toBe(5);expect(maxBatch).toBeLessThanOrEqual(256);expect(reads).toBe(4);
 }finally{await rm(directory,{recursive:true,force:true});}
},30000);
test("invalid or oversized explicit frontier is refused before native reads",async()=>{let calls=0;const executor:HistoryExecutor={exec:async()=>{calls++;return{success:true,stdout:"",stderr:""};}},directory=`/tmp/flaregit-import-history-${crypto.randomUUID()}`;for(const frontier of [[],["a".repeat(40),"a".repeat(40)],Array.from({length:257},(_,i)=>i.toString(16).padStart(40,"0")),["HEAD"]])await expect(readSourceHistoryChunk(executor,directory,frontier)).rejects.toThrow();expect(calls).toBe(0);});
test("source snapshot preparation pins SHA and refuses unsupported hosts before dispatch",async()=>{let calls=0;const executor:HistoryExecutor={exec:async()=>{calls++;return{success:true,stdout:"",stderr:""};}};expect(await preparePublicSourceHistoryClone(executor,"https://example.org/owner/repository.git","main","a".repeat(40),`/tmp/flaregit-import-history-${crypto.randomUUID()}`)).toBeNull();expect(calls).toBe(0);});
test("revoked owner callback and unexpected records stop source traversal",async()=>{const directory=`/tmp/flaregit-import-history-${crypto.randomUUID()}`,hash="a".repeat(40);let calls=0;const executor:HistoryExecutor={exec:async(command)=>{calls++;return{success:true,stdout:command.includes("is-shallow")?"false":`${"b".repeat(40)} ${"c".repeat(40)}`,stderr:""};}};await expect(readSourceHistoryChunk(executor,directory,[hash],async()=>{throw Error("Owner revoked");})).rejects.toThrow("Owner revoked");expect(calls).toBe(0);await expect(readSourceHistoryChunk(executor,directory,[hash])).rejects.toThrow("Invalid source history chunk");});
