import {test,expect} from "bun:test";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {workerdChild} from "./support/workerd-child";
test("native import readiness uses genuine saved ownership and repairs only untouched branch metadata",async()=>{
 if(await workerdChild("tests/import-read-lifecycle.test.ts"))return;
 const file=`/tmp/flaregit-import-read-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,"build","tests/support/import-read-lifecycle-worker.ts","--target=browser","--external=cloudflare:workers","--external=node:*",`--outfile=${file}`],{stdout:"ignore",stderr:"pipe"});if(await build.exited)throw new Error(await new Response(build.stderr).text());
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"import-read",modules:true,script:await Bun.file(file).text(),compatibilityDate:"2026-10-02",compatibilityFlags:["nodejs_compat"],bindings:{CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:"100000000",CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:"100000000",REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:"1000000",REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:"1000000",MANAGED_ACCOUNT_MONTHLY_USD_MICROS:"100000000",MANAGED_GLOBAL_MONTHLY_USD_MICROS:"100000000",MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:"1000000",MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:"2000000"},durableObjects:{REPOSITORY_CONTROLLER:{className:"ImportReadFixture",useSQLite:true}}}]}));
 try{const worker=await mf.getWorker("import-read");for(const mode of ["success","contribution","expired","storage","credential-cleanup","native-cleanup"]){const response=await worker.fetch(`https://fixture/?mode=${mode}`);expect(response.status).toBe(200);const result=await response.json() as {ready:string;repaired:boolean;branch:string;savedBranch:string;head:string;historyUnchanged:boolean;commands:number;revoked:number;nativeActive:boolean};expect(result.head).toBe("a".repeat(40));expect(result.historyUnchanged).toBe(true);expect(result.repaired).toBe(mode==="success");expect(result.branch).toBe(mode==="success"?"codex/docs-community-and-delivery":"main");expect(result.savedBranch).toBe(result.branch);expect(result.ready).toBe(["success","contribution"].includes(mode)?"ready":"pending");if(["expired","storage"].includes(mode))expect(result.commands).toBe(0);expect(result.nativeActive).toBe(mode==="native-cleanup");}}
 finally{await mf.dispose();await Bun.file(file).delete();}
},30000);
