import {Database} from 'bun:sqlite';
import {test,expect} from 'bun:test';
import {IntegrationNativePhases,integrationNativePhaseConfigSchema} from '../src/server/integration-native-phase';
import {IntegrationNativeRuntimeLedger} from '../src/server/integration-native-runtime';
import type{IntegrationRequestIntent}from'../src/server/integration-request-intents';
function fixture(){const db=new Database(':memory:');let now=Date.now();const storage={sql:{exec(q:string,...args:(string|number)[]){const rows=db.query(q).all(...args);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;const scope={workflowId:'integ-project-key',candidateId:'candidate',projectId:'project',incarnation:crypto.randomUUID(),actorId:'owner',accountKey:'account'};const commit='1'.repeat(40),config={projectId:scope.projectId,incarnation:scope.incarnation,expectedEventId:scope.workflowId,actorId:scope.actorId,sourceVersion:'2'.repeat(40),image:`registry.cloudflare.com/${'a'.repeat(32)}/verifier@sha256:${'b'.repeat(64)}`,acceptedBase:commit,contributions:[{taskId:'alpha',commit}],activatedAt:now-10,admissionExpiresAt:now+60000,nativeStopAt:now+1260000,maxAllocations:1 as const,maxContainerSeconds:1200 as const,maxCommands:64 as const,kind:'native-essential' as const};const intent:IntegrationRequestIntent={key:crypto.randomUUID(),eventId:scope.workflowId,actorId:scope.actorId,input:{taskIds:['alpha'],idempotencyKey:crypto.randomUUID(),expected:{acceptedCommit:commit,policyVersion:1,contributions:[{taskId:'alpha',commit,base:commit,acceptedTarget:null,targetGeneration:null}]}},context:{projectId:scope.projectId,incarnation:scope.incarnation,canonicalRepoName:'canonical',expected:{acceptedCommit:commit,policyVersion:1,contributions:[{taskId:'alpha',commit,base:commit,acceptedTarget:null,targetGeneration:null}]},verificationPolicy:{kind:'git-integrity'},acceptedRequirements:[],acceptancePolicy:{mode:'review-required',version:0}},dispatch:'prepared',createdAt:now};const env={INTEGRATION_NATIVE_PHASE_JSON:JSON.stringify(config),FLAREGIT_SOURCE_VERSION:config.sourceVersion,CF_VERSION_METADATA:{id:crypto.randomUUID()}};return{db,storage,scope,config,intent,env,phase:new IntegrationNativePhases(storage,()=>now),setNow:(v:number)=>{now=v;}};}
test('phase installation freezes actual release and original full context, no HTTP supplied grant',()=>{const f=fixture();try{const saved=f.phase.install(f.intent,f.env)!;expect(saved.workerVersion).toBe(f.env.CF_VERSION_METADATA.id);expect(f.phase.install(f.intent,f.env)).toEqual(saved);expect(()=>f.phase.install(f.intent,{...f.env,CF_VERSION_METADATA:{id:crypto.randomUUID()}})).toThrow();expect(()=>f.phase.install(f.intent,{...f.env,INTEGRATION_NATIVE_PHASE_JSON:undefined})).toThrow();expect(()=>f.phase.install({...f.intent,context:{...f.intent.context,acceptedRequirements:['changed']}},f.env)).toThrow();expect(integrationNativePhaseConfigSchema.safeParse({...f.config,workerVersion:crypto.randomUUID()}).success).toBe(false);}finally{f.db.close();}});
test('one allocation stays consumed across unknown outcome, restart and fresh native ID',()=>{const f=fixture();try{f.phase.install(f.intent,f.env);f.phase.bind(f.scope);const id=crypto.randomUUID();f.phase.reserve(f.scope,id,'integrate-candidate');const restarted=new IntegrationNativePhases(f.storage);expect(restarted.reserve(f.scope,id,'integrate-candidate')?.nativeId).toBe(id);expect(()=>restarted.reserve(f.scope,crypto.randomUUID(),'integrate-candidate')).toThrow();expect(()=>restarted.reserve(f.scope,id,'publish-candidate')).toThrow();expect(f.phase.claimStart(f.scope,id,f.env)?.image).toBe(f.config.image);expect(()=>restarted.claimStart(f.scope,id,f.env)).toThrow();}finally{f.db.close();}});
test('allocation expiry differs from hard command stop and cannot extend lifetime',()=>{const f=fixture();try{f.phase.install(f.intent,f.env);f.phase.bind(f.scope);const id=crypto.randomUUID();f.phase.reserve(f.scope,id,'integrate-candidate');f.setNow(f.config.admissionExpiresAt);expect(()=>f.phase.claimStart(f.scope,id,f.env)).toThrow();expect(()=>f.phase.reserve(f.scope,id,'integrate-candidate')).toThrow();expect(f.phase.commandAllowed(f.scope,id)).toBe(true);f.setNow(f.config.activatedAt+10+1200000);expect(f.phase.commandAllowed(f.scope,id)).toBe(false);expect(()=>f.phase.bind({...f.scope,candidateId:'new'})).toThrow();}finally{f.db.close();}});
test('actual native ledger caps total commands at64 and retains cleanup after sealing',()=>{const f=fixture();try{f.phase.install(f.intent,f.env);const ledger=new IntegrationNativeRuntimeLedger(f.storage);ledger.declareCoverage(f.scope);const id=crypto.randomUUID();ledger.reserve(f.scope,id,'integrate-candidate');for(let i=0;i<64;i++){const command=crypto.randomUUID();ledger.admitCommand(f.scope,id,command);ledger.finishCommand(f.scope,id,command,{outcome:'completed'});}expect(()=>ledger.admitCommand(f.scope,id,crypto.randomUUID())).toThrow();expect(()=>ledger.reserve(f.scope,crypto.randomUUID(),'integrate-candidate')).toThrow();ledger.seal(f.scope);ledger.confirmStopped(f.scope,id,{nativeRunId:id,state:'stopped'});expect(ledger.recovery(f.scope)).toBe('stopped');expect(f.db.query('SELECT COUNT(*) AS count FROM integration_native_commands').get()).toEqual({count:64});}finally{f.db.close();}});
