import {expect,test} from 'bun:test';
import {mergeMappingPrincipalPage,checkedMappingPreview,createMappingRequest,persistMapping,recoverMapping,clearConfirmedMapping} from '../src/web/issue-transfer-mapping-intent';
import {prepareTransferMappingCommand} from '../src/cli/issue-transfer-mapping-command';
const projectId='p123456789abd',requestId='12345678-1234-4234-8234-123456789abc';
const preview={canMap:true,origin:{version:1,labels:['source-label'],assignees:['source-user'],milestone:{id:4,title:'Source milestone'},relations:[{kind:'sub-issue-of',from:7,to:2}]},originDigest:'a'.repeat(64),featureRevision:3,principalGeneration:'b'.repeat(64),principalPage:{complete:true,nextCursor:null,generation:'b'.repeat(64)},catalog:{labels:['destination-label'],principals:['current-destination-user'],milestones:[{id:9,title:'Destination milestone'}]},applied:{labels:[],assignees:[],milestone:null},mappingAvailability:{labels:[],assignees:[],milestone:null},currentTriage:{labels:['keep-existing'],assignees:['existing-user'],milestone:5},effects:{labels:'add-and-retain-existing',assignees:'add-and-retain-existing',milestone:'replace-only-when-selected'},unmapped:{labels:['source-label'],assignees:['source-user'],milestone:{id:4,title:'Source milestone'},relations:[{}]}};
test('mapping selects exact existing or explicit new labels and current principal/milestone IDs without inference',()=>{
 const context=checkedMappingPreview(preview),none=createMappingRequest(context,{labels:[],assignees:[],milestone:null},requestId);expect(none.labels).toEqual([]);expect(none.assignees).toEqual([]);expect(none.milestone).toBeNull();
 const explicit=createMappingRequest(context,{labels:[{source:'source-label',destination:'new destination label',targetKind:'create'}],assignees:[{source:'source-user',destination:'current-destination-user'}],milestone:9},requestId);expect(explicit).toMatchObject({originDigest:'a'.repeat(64),expectedRevision:3,principalGeneration:'b'.repeat(64),confirmed:true});expect(()=>createMappingRequest(context,{labels:[{source:'source-label',destination:'unknown',targetKind:'existing'}],assignees:[],milestone:null},requestId)).toThrow();expect(()=>createMappingRequest(context,{labels:[],assignees:[{source:'source-user',destination:'source-user'}],milestone:null},requestId)).toThrow();expect(()=>createMappingRequest(context,{labels:[],assignees:[],milestone:4},requestId)).toThrow();
 const remap=checkedMappingPreview({...preview,applied:{labels:[{source:'source-label',destination:'removed',targetKind:'existing'}],assignees:[],milestone:null},mappingAvailability:{labels:[{source:'source-label',destination:'removed',targetKind:'existing',available:false}],assignees:[],milestone:null},unmapped:{...preview.unmapped,labels:[]}});expect(createMappingRequest(remap,{labels:[{source:'source-label',destination:'destination-label',targetKind:'existing'}],assignees:[],milestone:null},crypto.randomUUID()).labels[0]?.destination).toBe('destination-label');
});
test('mapping recovery preserves original UUID/scope/choices and clears only its verified receipt',()=>{
 const data=new Map<string,string>(),storage={getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>{data.set(key,value);},removeItem:(key:string)=>{data.delete(key);}},scope={identity:'admin',projectId,number:12},request=createMappingRequest(checkedMappingPreview(preview),{labels:[{source:'source-label',destination:'destination-label',targetKind:'existing'}],assignees:[],milestone:null},requestId);persistMapping(storage,scope,request);expect(recoverMapping(storage,scope)).toEqual(request);expect(recoverMapping(storage,{...scope,identity:'other'})).toBeNull();expect(()=>persistMapping(storage,scope,{...request,expectedRevision:4})).toThrow('cannot change');expect(()=>clearConfirmedMapping(storage,scope,request,{requestId:crypto.randomUUID(),featureRevision:4})).toThrow();expect(recoverMapping(storage,scope)).toEqual(request);clearConfirmedMapping(storage,scope,request,{requestId,featureRevision:4});expect(recoverMapping(storage,scope)).toBeNull();
});
test('CLI mapping preview leaves every source unmapped and exact-file replay never reads replacement catalog',async()=>{
 let reads=0;const input={repositoryId:projectId,issue:'12',confirmed:false},read=async()=>{reads++;return preview;},result=await prepareTransferMappingCommand(input,read);expect(result.kind).toBe('preview');if(result.kind!=='preview')throw Error('Preview required');expect(result.file.choices).toEqual({labels:[],assignees:[],milestone:null});const file={...result.file,choices:{labels:[{source:'source-label',destination:'destination-label',targetKind:'existing'}],assignees:[],milestone:null}};const first=await prepareTransferMappingCommand({...input,confirmed:true,file,request:requestId},read),retry=await prepareTransferMappingCommand({...input,confirmed:true,file,request:requestId},read);expect(first).toEqual(retry);expect(reads).toBe(1);await expect(prepareTransferMappingCommand({...input,issue:'13',confirmed:true,file,request:requestId},read)).rejects.toThrow('another');
});

test('compact principal pages append eligible UIDs only under unchanged frozen mapping proof',()=>{
 const first=checkedMappingPreview({...preview,catalog:{...preview.catalog,principals:Array.from({length:50},(_,index)=>`current-${index}`)},principalPage:{complete:false,nextCursor:'opaque/next',generation:'b'.repeat(64)}}),page={canMap:true,originDigest:first.originDigest,featureRevision:first.featureRevision,principalGeneration:first.principalGeneration,catalog:{principals:['later-eligible-user','current-0']},principalPage:{complete:true,nextCursor:null,generation:first.principalGeneration}};
 const combined=mergeMappingPrincipalPage(first,page);expect(combined.catalog.principals).toHaveLength(51);expect(combined.catalog.principals[0]).toBe('current-0');expect(combined.catalog.principals[50]).toBe('later-eligible-user');expect(combined.principalPage.complete).toBe(true);expect(createMappingRequest(combined,{labels:[],assignees:[{source:'source-user',destination:'later-eligible-user'}],milestone:null},requestId).assignees[0]?.destination).toBe('later-eligible-user');
 for(const invalid of [{...page,originDigest:'c'.repeat(64)},{...page,featureRevision:4},{...page,principalGeneration:'c'.repeat(64)},{...page,principalPage:{complete:true,nextCursor:null,generation:'c'.repeat(64)}},{...page,principalPage:{complete:false,nextCursor:'opaque/next',generation:first.principalGeneration}}])expect(()=>mergeMappingPrincipalPage(first,invalid)).toThrow();expect(first.catalog.principals).toHaveLength(50);expect(first.principalPage.complete).toBe(false);
});
test('CLI assembles later compact principal pages before review and never refreshes frozen confirmation replay',async()=>{
 const calls:string[]=[],first={...preview,catalog:{...preview.catalog,principals:['page-one-user']},principalPage:{complete:false,nextCursor:'opaque/next',generation:'b'.repeat(64)}},later={canMap:true,originDigest:preview.originDigest,featureRevision:preview.featureRevision,principalGeneration:preview.principalGeneration,catalog:{principals:['page-two-user']},principalPage:{complete:true,nextCursor:null,generation:'b'.repeat(64)}},input={repositoryId:projectId,issue:'12',confirmed:false},read=async(route:string)=>{calls.push(route);return calls.length===1?first:later;};
 const result=await prepareTransferMappingCommand(input,read);expect(result.kind).toBe('preview');if(result.kind!=='preview')throw Error('Preview required');expect(calls).toEqual([`/p/${projectId}/issues/12/transfer-mapping`,`/p/${projectId}/issues/12/transfer-mapping?principalCursor=opaque%2Fnext`]);expect(result.file.preview.catalog.principals).toEqual(['page-one-user','page-two-user']);expect(result.file.preview.principalPage.complete).toBe(true);
 const file={...result.file,choices:{labels:[],assignees:[{source:'source-user',destination:'page-two-user'}],milestone:null}},request=await prepareTransferMappingCommand({...input,confirmed:true,file,request:requestId},async()=>{throw Error('Replay cannot read a replacement page');});expect(request.kind).toBe('dispatch');
 let count=0;await expect(prepareTransferMappingCommand(input,async()=>++count===1?first:{...later,featureRevision:99})).rejects.toThrow('changed');
});
