import {Database} from 'bun:sqlite';
import {test,expect} from 'bun:test';
import {IssueLifecycleStore,isIssueActive} from '../src/server/issue-lifecycle';
import {IssueStateLedger} from '../src/server/issue-state';
import {IssueFeatureStore,issueFilterSchema,issueFeatureAction} from '../src/server/issue-feature-store';
import {PlanningStore,planningMutationSchema} from '../src/server/planning-store';
import {MetadataArchives} from '../src/server/metadata-archive';
import {checkedEnvelope} from '../src/web/metadata-archive-envelope';
import {searchAccountMetadata} from '../src/server/metadata-search';
import type {FlareGitProjectState} from '../src/core/types';
function storage(db:Database){return {sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=query.split(';').filter(part=>part.trim()).length>1?(db.exec(query),[]):db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(action:()=>T){return db.transaction(action)();}} as unknown as DurableObjectStorage;}
function database(){const db=new Database(':memory:');db.exec(`CREATE TABLE issues(number INTEGER PRIMARY KEY,title TEXT,body TEXT,state TEXT,author TEXT,created_at TEXT,updated_at TEXT,closed_by TEXT);CREATE TABLE comments(id INTEGER PRIMARY KEY,subject TEXT,author TEXT,body TEXT,path TEXT,line INTEGER,"commit" TEXT,created_at TEXT);`);return db;}
function seed(db:Database){for(const [number,title] of [[1,'Visible issue'],[2,'Removed private title']] as const)db.query('INSERT INTO issues VALUES(?,?,?,?,?,?,?,?)').run(number,title,number===2?'Removed private body':'Visible body','open',number===2?'Original author':'Visible author','2026-10-08T12:00:00Z','2026-10-08T12:00:00Z',null);db.query('INSERT INTO comments VALUES(?,?,?,?,?,?,?,?)').run(1,'issue:2','Original commenter','Removed private conversation',null,null,null,'2026-10-08T12:00:00Z');}
function remove(durable:DurableObjectStorage,incarnation:string){const scope={projectId:'source-project',incarnation,number:2,createdAt:'2026-10-08T12:00:00Z',author:'Original author'},revision=new IssueStateLedger(durable).snapshot(scope).stateRevision;new IssueLifecycleStore(durable).delete(scope,{requestId:crypto.randomUUID(),expectedRevision:revision,confirmed:true},'source-owner',()=>{});}
test('pending incoming transfer never exports content, descendants or opaque history even to an owner',async()=>{const db=database();try{
 seed(db);const durable=storage(db),features=new IssueFeatureStore(durable),archives=new MetadataArchives(durable),plan=new PlanningStore(durable);
 features.update({expectedRevision:0,action:{kind:'bulk-label',numbers:[2],label:'PENDING_LABEL_SECRET'}},[],true);
 plan.mutate(planningMutationSchema.parse({operation:'addItem',issueNumber:2,expectedVersion:0}),true);
 db.query('INSERT INTO issue_transfer_incoming VALUES(?,?,?,?)').run(2,crypto.randomUUID(),'{}',0);
 db.query('INSERT INTO metadata_archive_history VALUES(?,?,?)').run('issues','pending-history','PENDING_HISTORY_SECRET');
 db.query('INSERT INTO metadata_archive_origins VALUES(?,?,?)').run('comments','1','PENDING_ORIGIN_SECRET');
 features.transferOrigin(2,{version:1,labels:['PENDING_FEATURE_SECRET'],assignees:[],milestone:null,relations:[]},()=>{});
 expect(features.transferContext(2)).toBeNull();expect((await features.filteredIssues('scope','reader',issueFilterSchema.parse({state:'all'}))).issues.map(issue=>issue.number)).toEqual([1]);expect(plan.snapshot().plan.project.items).toEqual([]);
 for(const fullHistory of [false,true]){const exported=await archives.export({projectId:'source',incarnation:crypto.randomUUID(),head:'a'.repeat(40)},fullHistory),serialized=JSON.stringify(exported.archive);for(const secret of ['Removed private title','Removed private body','Removed private conversation','PENDING_LABEL_SECRET','PENDING_HISTORY_SECRET','PENDING_ORIGIN_SECRET','PENDING_FEATURE_SECRET'])expect(serialized).not.toContain(secret);expect(exported.archive.tables.find(table=>table.name==='issues')?.rows.map(row=>row.number)).toEqual([1]);expect(exported.archive.tables.find(table=>table.name==='comments')?.rows).toEqual([]);expect(JSON.stringify(archives.history(fullHistory))).not.toContain('PENDING_HISTORY_SECRET');}
 db.query('UPDATE issue_transfer_incoming SET active=1 WHERE issue_number=2').run();expect(features.transferContext(2)).toMatchObject({mapped:false,context:{labels:['PENDING_FEATURE_SECRET']}});expect(features.view().triage['2']?.assignees??[]).toEqual([]);
 }finally{db.close();}});
test('transfer freezes copied feature context while unrelated changes remain possible',()=>{const db=database();try{
 seed(db);const durable=storage(db),features=new IssueFeatureStore(durable);
 expect(features.update({expectedRevision:0,action:{kind:'milestone-create',title:'Original milestone'}},[],true).ok).toBe(true);
 expect(features.update({expectedRevision:1,action:{kind:'milestone-assign',number:2,milestone:1}},[],true).ok).toBe(true);
 const original=features.transferSnapshot(2);db.query('INSERT INTO issue_transfer_locks VALUES(?,?,?)').run(2,crypto.randomUUID(),'{}');
 for(const action of [{kind:'bulk-label',numbers:[2],label:'changed'},{kind:'milestone-delete',id:1},{kind:'relation-add',relation:'duplicate-of',from:1,to:2}])expect(features.update({expectedRevision:2,action:issueFeatureAction.parse(action)},[],true)).toMatchObject({ok:false,status:409});
 expect(features.update({expectedRevision:2,action:{kind:'bulk-label',numbers:[1],label:'unrelated'}},[],true).ok).toBe(true);expect(features.transferSnapshot(2)).toEqual(original);
 features.transferOrigin(2,original,()=>{});expect(()=>features.transferOrigin(2,{...original,labels:['changed']},()=>{})).toThrow();
 }finally{db.close();}});
test('real tombstone excludes native filter/triage/relationships/planning and cannot execute accepted automation',async()=>{const db=database();try{
 seed(db);const durable=storage(db),features=new IssueFeatureStore(durable),plan=new PlanningStore(durable),incarnation=crypto.randomUUID();
 features.update({expectedRevision:0,action:{kind:'bulk-label',numbers:[2],label:'private-label'}},[],true);features.update({expectedRevision:1,action:{kind:'relation-add',relation:'duplicate-of',from:1,to:2}},[],true);
 const act=(input:Record<string,unknown>)=>plan.mutate(planningMutationSchema.parse({...input,expectedVersion:plan.snapshot().version}),true);act({operation:'configure',statuses:['Todo','Done'],fieldTypes:{note:'text'}});act({operation:'addItem',issueNumber:1});act({operation:'addItem',issueNumber:2});act({operation:'updateItem',issueNumber:2,expectedItemVersion:1,fields:{note:'Removed private title'}});act({operation:'setAcceptedStatus',acceptedIssueStatus:'Done'});
 remove(durable,incarnation);expect(isIssueActive(durable,2)).toBe(false);
 const filtered=await features.filteredIssues('scope','reader',issueFilterSchema.parse({state:'all'}));expect(filtered.issues.map(issue=>issue.number)).toEqual([1]);expect(filtered.facets.labels).not.toContain('private-label');expect(JSON.stringify(features.view())).not.toContain('private-label');expect(features.view().unavailableIssueNumbers).toContain(2);
 const relations=await features.issueRelationships('scope','reader',1);expect(relations.items[0]).toMatchObject({number:2,issue:null,available:false});expect(JSON.stringify(relations)).not.toContain('Removed private title');await expect(features.issueRelationships('scope','reader',2)).rejects.toThrow('unavailable');
 expect(features.update({expectedRevision:2,action:{kind:'bulk-label',numbers:[1,2],label:'should-not-apply'}},[],true).ok).toBe(false);expect(features.view().triage['1']?.labels??[]).not.toContain('should-not-apply');
 expect(plan.snapshot().plan.project.items.map(item=>item.issueNumber)).toEqual([1]);expect(plan.snapshot().inactiveReferences).toEqual([{issueNumber:2,available:false}]);expect(JSON.stringify(plan.snapshot())).not.toContain('Removed private title');expect(JSON.stringify(plan.export())).not.toContain('Removed private title');expect(()=>act({operation:'addItem',issueNumber:2})).toThrow('inactive');expect(()=>act({operation:'bulkStatus',issueNumbers:[1,2],status:'Done',expectedVersions:[1,2]})).toThrow('inactive');expect(plan.recordAccepted('accepted-after-removal',2,'a'.repeat(40)).phase).toBe('ignored');
 }finally{db.close();}});
test('v2 portable tombstone archive preserves owner audit, redacts member export, restores fresh inactive identity and accepts legacy v1',async()=>{
 const source=database(),destination=database(),legacy=database(),redactedDestination=database();try{
 seed(source);source.exec('CREATE TABLE migration_native_issue_origins(repository_id TEXT,provider_id TEXT,node_id TEXT,kind TEXT,native_id INTEGER,source_doc TEXT);CREATE TABLE migration_native_comment_origins(repository_id TEXT,provider_id TEXT,node_id TEXT,kind TEXT,native_id INTEGER,source_doc TEXT)');
 source.query('INSERT INTO migration_native_issue_origins VALUES(?,?,?,?,?,?)').run('external-repo','original-issue','issue-node','issue',2,JSON.stringify({title:'MIGRATED_DELETED_TITLE',body:'MIGRATED_DELETED_BODY',actor:{login:'MIGRATED_DELETED_ACTOR'}}));source.query('INSERT INTO migration_native_comment_origins VALUES(?,?,?,?,?,?)').run('external-repo','original-comment','comment-node','issue',1,JSON.stringify({body:'MIGRATED_DELETED_COMMENT',actor:{login:'MIGRATED_COMMENT_ACTOR'}}));
 const durable=storage(source),incarnation=crypto.randomUUID();remove(durable,incarnation);const scope={projectId:'source-project',incarnation,head:'a'.repeat(40)},archives=new MetadataArchives(durable),owner=await archives.export(scope,true),member=await archives.export(scope,false);
 expect(owner.archive.version).toBe(2);expect(JSON.stringify(owner.archive)).toContain('Removed private body');expect(JSON.stringify(owner.archive)).toContain('MIGRATED_DELETED_BODY');expect(JSON.stringify(member.archive)).not.toContain('Removed private title');expect(JSON.stringify(member.archive)).not.toContain('Removed private conversation');expect(JSON.stringify(member.archive)).not.toContain('Original author');expect(JSON.stringify(member.archive)).not.toContain('Original commenter');expect(JSON.stringify(member.archive)).not.toContain('source-owner');const masked=JSON.parse(String(member.archive.tables.find(table=>table.name==='issue_lifecycle_history')?.rows[0]?.document));expect(masked.sourceActorId).toBe('historical-unknown');expect(masked.sourceIdentity).toBe('historical-unknown');for(const privateValue of ['MIGRATED_DELETED_TITLE','MIGRATED_DELETED_BODY','MIGRATED_DELETED_ACTOR','MIGRATED_DELETED_COMMENT','MIGRATED_COMMENT_ACTOR'])expect(JSON.stringify(member.archive)).not.toContain(privateValue);expect(member.archive.omissions.some(note=>note.includes('redacted'))).toBe(true);expect(owner.archive.tables.find(table=>table.name==='issue_lifecycle_history')?.rows).toHaveLength(1);expect(await checkedEnvelope(owner)).toEqual(owner);
 for(const database of [destination,legacy,redactedDestination])database.exec('CREATE TABLE migration_native_issue_origins(repository_id TEXT,provider_id TEXT,node_id TEXT,kind TEXT,native_id INTEGER,source_doc TEXT);CREATE TABLE migration_native_comment_origins(repository_id TEXT,provider_id TEXT,node_id TEXT,kind TEXT,native_id INTEGER,source_doc TEXT)');
 const maskedStore=storage(redactedDestination),maskedTarget={projectId:'redacted-destination',incarnation:crypto.randomUUID(),head:scope.head};await new MetadataArchives(maskedStore).restore(member.archive,maskedTarget,crypto.randomUUID(),member.sha256,()=>{},undefined,'restoring-owner');expect(isIssueActive(maskedStore,2)).toBe(false);expect(new IssueLifecycleStore(maskedStore).tombstone(2)?.provenance).toMatchObject({sourceActorId:'historical-unknown',sourceIdentity:'historical-unknown'});expect(redactedDestination.query('SELECT title,body FROM issues WHERE number=2').get()).toEqual({title:'Removed issue',body:''});
 const target={projectId:'destination-project',incarnation:crypto.randomUUID(),head:scope.head},restored=storage(destination),restoreId=crypto.randomUUID();const receipt=await new MetadataArchives(restored).restore(owner.archive,target,restoreId,owner.sha256,()=>{},undefined,'restoring-owner');expect(receipt.restoredRows).toBeGreaterThan(0);expect(isIssueActive(restored,2)).toBe(false);expect(destination.query('SELECT title FROM issues WHERE number=2').get()).toEqual({title:'Removed private title'});const tombstone=new IssueLifecycleStore(restored).tombstone(2)!;expect(tombstone.actorId).toBe('restoring-owner');expect(tombstone.requestId).toBe(restoreId);expect(JSON.parse(tombstone.identity)).toMatchObject({projectId:target.projectId,incarnation:target.incarnation,author:'Imported archive contributor (unverified)'});expect(tombstone.provenance?.sourceActorId).toBe('source-owner');expect(destination.query('SELECT COUNT(*) AS count FROM issue_tombstone_requests').get()).toEqual({count:0});
 const reexport=await new MetadataArchives(restored).export(target,true);expect(JSON.parse(String(reexport.archive.tables.find(table=>table.name==='issue_lifecycle_history')?.rows[0]?.document)).sourceActorId).toBe('source-owner');
 const activeOnly={...member.archive,version:1 as const,tables:member.archive.tables.filter(table=>table.name!=='issue_lifecycle_history').map(table=>table.name==='issues'?{...table,rows:table.rows.filter(row=>row.number===1)}:table.name==='comments'?{...table,rows:[]}:table)},digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(activeOnly)))),byte=>byte.toString(16).padStart(2,'0')).join('');await new MetadataArchives(storage(legacy)).restore(activeOnly,{projectId:'legacy-target',incarnation:crypto.randomUUID(),head:scope.head},crypto.randomUUID(),digest,()=>{});expect(isIssueActive(storage(legacy),1)).toBe(true);
 }finally{source.close();destination.close();legacy.close();redactedDestination.close();}
});
test('metadata search rechecks canonical active issue instead of returning a pre-removal listing title',async()=>{const id='p123456abcdef',state={projectId:id,projectName:'Visible project',tasks:{}} as FlareGitProjectState,issue={number:2,title:'Removed private title',body:'private',state:'open' as const,author:'Author',created_at:'',updated_at:'',closed_by:null,comments:0};const result=await searchAccountMetadata({query:'Removed private',userId:'reader',references:[{id,name:'Visible project',role:'member',kind:'empty',created_at:''}],repository:()=>({roleOf:async()=> 'member',getState:async()=>state,listIssues:async filter=>filter==='open'?[issue]:[],getIssue:async()=>null}),lifecycle:async()=> 'active'});expect(result.results).toEqual([]);});
