import {expect,test} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {issueTransferMappingSchema} from '../src/server/issue-feature-store';
test('actual CLI mapping confirms explicit reviewed choices and replays original UUID after503 without source requests',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'flaregit-transfer-map-cli-')),projectId='p123456789abd',token='synthetic-destination-admin',file=join(directory,'mapping.json');let gets=0,posts=0,original:string|undefined;
 const preview={canMap:true,origin:{version:1,labels:['source-label'],assignees:['source-user'],milestone:null,relations:[]},originDigest:'a'.repeat(64),featureRevision:3,principalGeneration:'b'.repeat(64),principalPage:{complete:false,nextCursor:'page-2',generation:'b'.repeat(64)},catalog:{labels:[],principals:Array.from({length:50},(_,index)=>`first-page-${index}`),milestones:[]},applied:{labels:[],assignees:[],milestone:null},mappingAvailability:{labels:[],assignees:[],milestone:null},currentTriage:{labels:[],assignees:[],milestone:null},effects:{labels:'add-and-retain-existing',assignees:'add-and-retain-existing',milestone:'replace-only-when-selected'},unmapped:{labels:['source-label'],assignees:['source-user'],milestone:null,relations:[]}};
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){if(request.headers.get('Authorization')!=='Bearer '+token)return new Response('Unauthorized',{status:401});if(new URL(request.url).pathname!==`/api/p/${projectId}/issues/12/transfer-mapping`)return new Response('No source/identity inference endpoint',{status:404});if(request.method==='GET'){gets++;return new URL(request.url).searchParams.get('principalCursor')==='page-2'?Response.json({canMap:true,originDigest:preview.originDigest,featureRevision:preview.featureRevision,principalGeneration:preview.principalGeneration,catalog:{principals:['dest-user']},principalPage:{complete:true,nextCursor:null,generation:'b'.repeat(64)}}):Response.json(preview);}const input=issueTransferMappingSchema.parse(await request.json()),payload=JSON.stringify(input);posts++;if(original&&original!==payload)return new Response('Original mapping changed',{status:409});if(!original){original=payload;return new Response('Unknown mapping acknowledgement',{status:503});}return Response.json({requestId:input.requestId,featureRevision:4});}});
 const run=async(...flags:string[])=>{const child=Bun.spawn([process.execPath,resolve(import.meta.dir,'../cli/flaregit.ts'),'issue','transfer','map',projectId,'12',...flags],{cwd:directory,env:{PATH:process.env.PATH,FLAREGIT_API:server.url.origin,FLAREGIT_TOKEN:token,XDG_CONFIG_HOME:directory},stdout:'pipe',stderr:'pipe'}),timer=setTimeout(()=>child.kill(),10000);try{const [stdout,stderr,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return{stdout,stderr,code};}finally{clearTimeout(timer);}};
 try{const discovery=await run();expect(discovery.code).toBe(0);const review=JSON.parse(discovery.stdout);expect(review.choices).toEqual({labels:[],assignees:[],milestone:null});review.choices={labels:[{source:'source-label',destination:'explicit new label',targetKind:'create'}],assignees:[{source:'source-user',destination:'dest-user'}],milestone:null};await Bun.write(file,JSON.stringify(review));const first=await run('--confirm','--mapping',file);expect(first.code).not.toBe(0);const marker=JSON.parse(first.stderr.split('\n')[0]!) as {requestId:string;originalRequest:unknown};expect(marker.originalRequest).toEqual(JSON.parse(original!));expect(first.stderr).not.toContain(token);const retry=await run('--confirm','--mapping',file,'--request',marker.requestId);expect(retry.code).toBe(0);expect(JSON.parse(retry.stdout)).toEqual({requestId:marker.requestId,featureRevision:4});expect(posts).toBe(2);expect(gets).toBe(2);}finally{server.stop(true);await rm(directory,{recursive:true,force:true});}
},30000);
