import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {workerdChild} from './support/workerd-child';
test('actual Worker legacy rerun preserves predecessor and retries one saved successor under exact owner scope',async()=>{
 if(await workerdChild('tests/legacy-candidate-rerun-http.test.ts'))return;
 const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'rerun-test',alg:'RS256',use:'sig'},issuer=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({keys:[jwk]})});
 const file=`/tmp/legacy-rerun-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/legacy-candidate-rerun-http-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${file}`],{stdout:'ignore',stderr:'pipe'});const [error,code]=await Promise.all([new Response(build.stderr).text(),build.exited]);if(code)throw Error(error);const script=await Bun.file(file).text();await Bun.file(file).delete();
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'rerun-http',unsafeDirectSockets:[{host:'127.0.0.1'}],modules:true,script,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],bindings:{FIXTURE_ISSUER:issuer.url.origin,CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'5000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'2500000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'2000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000'},durableObjects:{REPOSITORY_CONTROLLER:{className:'LegacyRerunHttpFixture',useSQLite:true}}}]}));
 const direct=await mf.unsafeGetDirectURL('rerun-http');
 const call=(path:string,token?:string,body?:unknown)=>fetch(new URL(path,direct),{method:body?'POST':'GET',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.30',...(token?{Authorization:`Bearer ${token}`} :{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const session=(who:string)=>new SignJWT({azp:'https://fixture.example'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer.url.origin).setSubject(who).setIssuedAt().setExpirationTime('5m').sign(pair.privateKey),route='/api/p/p123456789abc/candidates/legacy/rerun';
 try{const seeded=await(await call('/fixture/seed')).json() as {token:string;fullToken:string},owner=await session('owner'),member=await session('member');expect((await call(route)).status).toBe(401);expect((await call(route,member)).status).toBe(403);expect((await call(route,seeded.token)).status).toBe(403);expect((await call(route,seeded.fullToken)).status).toBe(200);
 const runtime='/api/p/p123456789abc/candidates/legacy/runtime';expect((await call(runtime)).status).toBe(401);expect((await call(runtime,member)).status).toBe(403);expect((await call(runtime,seeded.fullToken)).status).toBe(403);const prior=await(await call('/fixture/snapshot')).json();const inspected=await call(runtime,owner);expect(inspected.status).toBe(200);const inventory=await inspected.json() as {status:string;allocations:unknown;commands:unknown};expect(inventory.status).toBe('recovery_required');expect(inventory.allocations).toBeNull();expect(inventory.commands).toBeNull();expect(JSON.stringify(await(await call('/fixture/snapshot')).json())).toBe(JSON.stringify(prior));for(const race of ['inspection-withdraw','inspection-incarnation']){await call('/fixture/group?name='+race);await call('/fixture/seed');await call('/fixture/mode?value='+race);expect((await call(runtime,owner)).status).toBe(409);await call('/fixture/group?name=initial');}await call('/fixture/mode?value=normal');
 const report=await call(route,owner);if(!report.ok)throw Error(await report.text());const body=await report.json() as {eligible:boolean;expectedCommit:string;inputs:Record<string,{commit:string;base:string}>};expect(body.eligible).toBe(true);expect(body.inputs).toEqual({one:{commit:'b'.repeat(40),base:'a'.repeat(40)}});
 const before=await(await call('/fixture/snapshot')).json() as {state:{candidates:unknown;acceptedState:unknown;tasks:{one:{goal:string;checkpoints:unknown}}}};
 expect((await call(route,owner,{expectedCommit:body.expectedCommit,expectedInputs:{one:{commit:'b'.repeat(40),base:'d'.repeat(40)}},requestId:crypto.randomUUID()})).status).toBe(409);

 for(const value of ['prepared','assignment','head']){await call(`/fixture/change?value=${value}`);expect((await call(route,owner)).status).toBe(200);const refused=await call(route,owner,{expectedCommit:body.expectedCommit,expectedInputs:body.inputs,requestId:crypto.randomUUID()});expect(refused.status).toBe(409);await call('/fixture/change?value=restore');}
 const request={expectedCommit:body.expectedCommit,expectedInputs:body.inputs,requestId:crypto.randomUUID()};await call('/fixture/coverage?present=0');const missingReport=await(await call(route,owner)).json() as {eligible:boolean;detail:string};expect(missingReport.eligible).toBe(false);expect(missingReport.detail).toContain('not recorded');const untracked=await call(route,owner,request);expect(untracked.status).toBe(409);const missing=await(await call('/fixture/snapshot')).json() as typeof before&{created:string[]};expect(missing.created).toEqual([]);expect(missing.state).toEqual(before.state);expect(await(await call('/fixture/old-writes')).json() as {verificationDenied:boolean;unchanged:boolean}).toEqual({verificationDenied:true,unchanged:true});await call('/fixture/coverage');
 for(const [mode,detail] of [["missing-head","tip is unavailable"],["newer","tip differs from the saved input"]]){
  await call(`/fixture/mode?value=${mode}`);const refused=await call(route,owner,request);expect(refused.status).toBe(409);expect(await refused.text()).toContain(detail!);
  const preserved=await(await call('/fixture/snapshot')).json() as typeof before&{created:string[];calls:string[];operations:Array<{doc:string}>};expect(preserved.state).toEqual(before.state);expect(preserved.created).toEqual([]);expect(preserved.calls.some(value=>/^(destroy:|terminate:|workflow:|createBatch)/.test(value))).toBe(false);
  const attempt=JSON.parse(preserved.operations[0]!.doc) as {phase:string;dispatch:string;snapshot:{tasks:Array<{currentCommit:string;baseCommit:string}>}};expect(attempt.phase).toBe("prepared");expect(attempt.dispatch).toBe("not_started");expect(attempt.snapshot.tasks[0]!.currentCommit).toBe(body.inputs.one!.commit);expect(attempt.snapshot.tasks[0]!.baseCommit).toBe(body.inputs.one!.base);
 }
 const afterRefusal=await(await call('/fixture/snapshot')).json() as typeof before;expect(afterRefusal.state).toEqual(before.state);

 for(const value of ['withdraw','incarnation','assignment','account']){await call(`/fixture/mode?value=${value}`);const raced=await call(route,owner,request);expect([409,503]).toContain(raced.status);const snapshot=await(await call('/fixture/snapshot')).json() as typeof before&{created:string[]};expect(snapshot.created).toEqual([]);expect(snapshot.state.candidates).toEqual(before.state.candidates);expect(snapshot.state.acceptedState).toEqual(before.state.acceptedState);await call('/fixture/restore-race');}
 await call('/fixture/mode?value=lost-ack');const uncertain=await call(route,owner,request);expect(uncertain.status).toBe(503);const replay=await call(route,owner,request);if(!replay.ok)throw Error(await replay.text());expect(replay.status).toBe(202);
 const after=await(await call('/fixture/snapshot')).json() as typeof before&{created:string[];calls:string[]};expect(after.created).toEqual([`legacy-${request.requestId}`]);expect(after.state.candidates).toEqual(before.state.candidates);expect(after.state.acceptedState).toEqual(before.state.acceptedState);expect(after.state.tasks.one.goal).toBe(before.state.tasks.one.goal);expect(after.state.tasks.one.checkpoints).toEqual(before.state.tasks.one.checkpoints);
 const attached=await(await call(`/fixture/attach?id=legacy-${request.requestId}`)).json() as {candidate?:{id:string;preservationProtocolVersion:number;predecessorCandidateId:string}};expect(attached.candidate?.preservationProtocolVersion).toBe(1);expect(attached.candidate?.predecessorCandidateId).toBe('legacy');expect(await(await call('/fixture/old-writes')).json() as {verificationDenied:boolean;unchanged:boolean}).toEqual({verificationDenied:true,unchanged:true});const attachedReplay=await(await call(route,owner,request)).json() as {successorCandidateId:string};expect(attachedReplay.successorCandidateId).toBe(attached.candidate!.id);expect((await call(route,owner,{...request,requestId:crypto.randomUUID()})).status).toBe(409);

 expect((await call(`${route}/abandon`,owner,{requestId:request.requestId,confirm:'abandon pending rerun'})).status).toBe(409);
 await call('/fixture/group?name=abandon');await call('/fixture/seed');const pending={expectedCommit:'c'.repeat(40),expectedInputs:{one:{commit:'b'.repeat(40),base:'a'.repeat(40)}},requestId:crypto.randomUUID()};
 await call('/fixture/mode?value=newer');expect((await call(route,owner,pending)).status).toBe(409);await call('/fixture/coverage?present=0');expect((await call(`${route}/abandon`,owner,{requestId:pending.requestId,confirm:'abandon pending rerun'})).status).toBe(409);let held=await(await call('/fixture/snapshot')).json() as {state:{candidates:unknown;acceptedState:unknown;tasks:unknown};reservations:unknown[];created:string[];calls:string[];operations:Array<{doc:string}>};expect(held.reservations).toHaveLength(1);expect(held.created).toEqual([]);
 await call('/fixture/coverage');await call('/fixture/change?value=new-checkpoint');const advanced=await(await call('/fixture/snapshot')).json() as typeof held;const abandonRequest={requestId:pending.requestId,confirm:'abandon pending rerun'};expect((await call(`${route}/abandon`,member,abandonRequest)).status).toBe(403);const abandoned=await call(`${route}/abandon`,owner,abandonRequest);if(!abandoned.ok)throw Error(await abandoned.text());expect((await abandoned.json() as {phase:string}).phase).toBe('abandoned');held=await(await call('/fixture/snapshot')).json() as typeof held;expect(held.state).toEqual(advanced.state);expect(held.calls).toContain('destroy:native-12345678-1234-4234-8234-123456789abc');expect(held.calls).toContain('workflow:original');expect(held.reservations).toEqual([]);expect(held.created).toEqual([]);
 await call('/fixture/change?value=restore');const later={...pending,requestId:crypto.randomUUID()};expect((await call(route,owner,later)).status).toBe(409);const reservedLater=await(await call('/fixture/snapshot')).json() as typeof held;expect(reservedLater.reservations).toHaveLength(1);expect((await call(`${route}/abandon`,owner,abandonRequest)).status).toBe(200);expect((await(await call('/fixture/snapshot')).json() as typeof held).reservations).toEqual(reservedLater.reservations);
 await call('/fixture/change?value=new-checkpoint');expect((await call(`${route}/abandon`,owner,{requestId:later.requestId,confirm:'abandon pending rerun'})).status).toBe(200);const fresh=await(await call('/fixture/attach?id=normal-fresh-holder')).json() as {candidate?:{participatingCommits:Record<string,string>}};expect(fresh.candidate?.participatingCommits.one).toBe('d'.repeat(40));
 await call('/fixture/group?name=uncertain');await call('/fixture/seed');await call('/fixture/mode?value=unknown-dispatch');const uncertainRequest={...pending,requestId:crypto.randomUUID()};expect((await call(route,owner,uncertainRequest)).status).toBe(202);const uncertainBefore=await(await call('/fixture/snapshot')).json() as typeof held;expect((JSON.parse(uncertainBefore.operations[0]!.doc) as {dispatch:string}).dispatch).toBe('unknown');expect(uncertainBefore.reservations).toHaveLength(1);expect((await call(`${route}/abandon`,owner,{requestId:uncertainRequest.requestId,confirm:'abandon pending rerun'})).status).toBe(409);expect((await(await call('/fixture/snapshot')).json() as typeof held).state).toEqual(uncertainBefore.state);

 await call('/fixture/group?name=decision');await call('/fixture/seed');const decisionRerun={...pending,expectedInputs:{...pending.expectedInputs,two:{commit:'b'.repeat(40),base:'a'.repeat(40)}},requestId:crypto.randomUUID()};expect((await call(route,owner,decisionRerun)).status).toBe(202);
 const decisionClaim=await(await call(`/fixture/attach?id=legacy-${decisionRerun.requestId}`)).json() as {decision:{id:string;legacyRerunId:string;options:Array<{id:string}>}};expect(decisionClaim.decision.legacyRerunId).toBe(decisionRerun.requestId);const decisionId=decisionClaim.decision.id,choice={decisionId,selectedOptionId:decisionClaim.decision.options[0]!.id};const decisionRoute='/api/p/p123456789abc/decisions/resolve';
 type DecisionSnapshot={state:{candidates:Record<string,{review?:unknown;legacyRerunId?:string;predecessorCandidateId?:string}>;tasks:Record<string,{status:string;requirements:unknown}>;decisions:Record<string,{resolvedAt?:string;resolvedBy?:unknown;status:string}>};operations:Array<{doc:string}>;reservations:unknown[];queued:Array<{eventId?:string;taskIds?:string[]}>;created:string[];calls:string[]};
 const waiting=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;expect(waiting.reservations).toEqual([]);expect((JSON.parse(waiting.operations[0]!.doc) as {phase:string}).phase).toBe('awaiting_decision');const rerunReplay=await call(route,owner,decisionRerun);expect(rerunReplay.status).toBe(202);expect((await(await call('/fixture/snapshot')).json() as DecisionSnapshot).created).toEqual(waiting.created);
 await call('/fixture/change?value=head');const changedChoice=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;expect((await call(decisionRoute,owner,choice)).status).toBe(409);expect((await(await call('/fixture/snapshot')).json() as DecisionSnapshot).state).toEqual(changedChoice.state);await call('/fixture/change?value=restore');
 // Restoring only the synthetic Git tuple must preserve the real pending decision state.
 await call('/fixture/change?value=decision-wait');await call('/fixture/mode?value=missing-head');const missingChoiceBefore=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;const missingChoice=await call(decisionRoute,owner,choice);expect(missingChoice.status).toBe(409);expect(await missingChoice.text()).toContain("tip is unavailable");const missingChoiceAfter=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;expect(missingChoiceAfter.state).toEqual(missingChoiceBefore.state);expect(missingChoiceAfter.queued).toEqual(missingChoiceBefore.queued);expect(missingChoiceAfter.created).toEqual(missingChoiceBefore.created);expect(missingChoiceAfter.calls.some(value=>/^(destroy:|terminate:|workflow:|createBatch)/.test(value))).toBe(false);await call('/fixture/mode?value=newer');const remoteChoiceBefore=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;const differentChoice=await call(decisionRoute,owner,choice);expect(differentChoice.status).toBe(409);expect(await differentChoice.text()).toContain('tip differs from the saved input');const differentChoiceAfter=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;expect(differentChoiceAfter.state).toEqual(remoteChoiceBefore.state);expect(differentChoiceAfter.queued).toEqual(remoteChoiceBefore.queued);expect(differentChoiceAfter.created).toEqual(remoteChoiceBefore.created);await call('/fixture/mode?value=normal');expect((await call(decisionRoute,member,choice)).status).toBe(403);expect((await call(decisionRoute,owner,choice)).status).toBe(200);const resolved=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;const continuation=`decision-p123456789abc-${decisionId}`;expect(resolved.queued.at(-1)?.eventId).toBe(continuation);expect(resolved.queued.at(-1)?.taskIds).toEqual(['one','two']);expect(resolved.state.tasks.outside!.status).toBe('needs_decision');expect(resolved.state.tasks.outside!.requirements).toEqual(waiting.state.tasks.outside!.requirements);expect(resolved.reservations).toHaveLength(2);expect(resolved.calls.filter(value=>value.startsWith('log:'))).toEqual(['log:synthetic-workspace:refs/heads/task/one','log:synthetic-workspace-two:refs/heads/task/two']);await call('/fixture/mode?value=newer');expect((await call(decisionRoute,owner,choice)).status).toBe(200);const choiceReplay=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;expect(choiceReplay.state.decisions[decisionId]).toEqual(resolved.state.decisions[decisionId]);expect(choiceReplay.queued.at(-1)?.eventId).toBe(continuation);expect(choiceReplay.calls).toEqual([]);await call('/fixture/mode?value=normal');
 const freshDecision=await(await call(`/fixture/attach?id=${continuation}`)).json() as {candidate:{id:string;review?:unknown;legacyRerunId:string;predecessorCandidateId:string;preservationProtocolVersion:number}};expect(freshDecision.candidate.predecessorCandidateId).toBe('legacy');expect(freshDecision.candidate.legacyRerunId).toBe(decisionRerun.requestId);expect(freshDecision.candidate.preservationProtocolVersion).toBe(1);expect(freshDecision.candidate.review).toBeUndefined();const finalDecision=await(await call('/fixture/snapshot')).json() as DecisionSnapshot;expect(finalDecision.state.candidates.legacy).toEqual(waiting.state.candidates.legacy);

 for(const incomplete of [false,true]){await call(`/fixture/group?name=modern-${incomplete}`);await call('/fixture/seed?coverage=0');const seededModern=await call(`/fixture/modern?incomplete=${incomplete?'1':'0'}`);if(!seededModern.ok)throw Error(await seededModern.text());const modern=await seededModern.json() as {id:string;workflowId:string};const modernRoute=`/api/p/p123456789abc/candidates/${modern.id}/rerun`;const modernBefore=await(await call('/fixture/snapshot')).json() as {state:{candidates:Record<string,{preservationProtocolVersion:number;candidateCommit?:string;review?:unknown}>;evidence:unknown};created:string[];calls:string[]};const commentsBefore=await(await call(`/fixture/comments?id=${modern.id}`)).json() as Record<string,unknown>[];expect(modernBefore.state.candidates[modern.id]!.preservationProtocolVersion).toBe(1);expect(modernBefore.state.candidates[modern.id]!.candidateCommit).toBe(incomplete?undefined:'c'.repeat(40));const modernReport=await(await call(modernRoute,owner)).json() as {eligible:boolean;expectedCommit:string|null;inputs:Record<string,{commit:string;base:string}>};expect(modernReport.eligible).toBe(true);expect(modernReport.expectedCommit).toBe(incomplete?null:'c'.repeat(40));expect((await call(modernRoute,owner,{expectedInputs:modernReport.inputs,requestId:crypto.randomUUID()})).status).toBe(400);expect((await call(modernRoute,owner,{expectedCommit:incomplete?'f'.repeat(40):null,expectedInputs:modernReport.inputs,requestId:crypto.randomUUID()})).status).toBe(409);const modernRequest={expectedCommit:modernReport.expectedCommit,expectedInputs:modernReport.inputs,requestId:crypto.randomUUID()};const modernStarted=await call(modernRoute,owner,modernRequest);if(!modernStarted.ok)throw Error(await modernStarted.text());expect(modernStarted.status).toBe(202);const modernAfter=await(await call('/fixture/snapshot')).json() as typeof modernBefore;expect(modernAfter.state.candidates[modern.id]).toEqual(modernBefore.state.candidates[modern.id]);expect(modernAfter.state.evidence).toEqual(modernBefore.state.evidence);expect(await(await call(`/fixture/comments?id=${modern.id}`)).json() as Record<string,unknown>[]).toEqual(commentsBefore);expect(modernAfter.calls).toContain(`workflow:${modern.workflowId}`);expect(modernAfter.calls).toContain('destroy:native-12345678-1234-4234-8234-123456789abc');const modernFresh=await(await call(`/fixture/attach?id=legacy-${modernRequest.requestId}&predecessor=${modern.id}`)).json() as {candidate:{predecessorCandidateId:string;legacyRerunId:string;preservationProtocolVersion:number;review?:unknown}};expect(modernFresh.candidate.predecessorCandidateId).toBe(modern.id);expect(modernFresh.candidate.legacyRerunId).toBe(modernRequest.requestId);expect(modernFresh.candidate.preservationProtocolVersion).toBe(1);expect(modernFresh.candidate.review).toBeUndefined();}
 }finally{await mf.dispose();issuer.stop(true);}
},30000);
