import { Database } from "bun:sqlite";
import { expect,test } from "bun:test";
import { LegacyCandidateReruns,assertLegacyRerunEligible,type LegacyRerunSnapshot } from "../src/server/legacy-candidate-rerun";
const expectedInputs={one:{commit:"b".repeat(40),base:"a".repeat(40)}};
const actor={userId:"owner",displayName:"Maintainer",viaToken:false};
function fixture(){
 const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}} as unknown as DurableObjectStorage;
 const snapshot:LegacyRerunSnapshot={projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",publicationBlocked:false,busy:false,candidate:{id:"legacy",attemptNumber:1,participatingTaskIds:["one"],participatingCommits:{one:"b".repeat(40)},expectedAcceptedBase:"a".repeat(40),frozenPolicyVersion:1,frozenVerificationPolicy:{},frozenRequirements:[],frozenContributorProofs:[{id:"one",commit:"b".repeat(40),baseCommit:"a".repeat(40),ref:"refs/flaregit/tasks/one",allowedScope:["src"]}],repairAttempts:[],status:"awaiting_review",candidateCommit:"c".repeat(40),workflowInstanceId:"original",review:{approved:true,by:"Old owner",at:"2026-10-01",commit:"c".repeat(40)},createdAt:"2026-10-01",updatedAt:"2026-10-01"},tasks:[{id:"one",currentCommit:"b".repeat(40),baseCommit:"a".repeat(40),workspace:{repoName:"workspace",branch:"task/one"},status:"integrating",activeCandidateId:"legacy"}]};return {db,ledger:new LegacyCandidateReruns(storage),snapshot};
}
test("rerun intent retains frozen review and inputs without changing predecessor; exact UUID replay is stable",()=>{
 const f=fixture();try{const before=structuredClone(f.snapshot),id=crypto.randomUUID();const input={id,expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot};const saved=f.ledger.prepare(input);expect(f.snapshot).toEqual(before);expect(saved.snapshot).toEqual(before);expect(saved.phase).toBe("prepared");expect(saved.successorCandidateId).toBeUndefined();expect(saved.successorWorkflowId).toBe(`legacy-${id}`);expect(f.ledger.prepare({...input,actor:{...actor,displayName:"Changed name"}})).toEqual(saved);expect(()=>f.ledger.prepare({...input,actor:{...actor,userId:"other"}})).toThrow("another rerun");expect(()=>f.ledger.prepare({...input,expectedCommit:"d".repeat(40)})).toThrow("another rerun");expect(()=>f.ledger.prepare({...input,expectedInputs:{one:{commit:"b".repeat(40),base:"d".repeat(40)}}})).toThrow("another rerun");expect(f.ledger.prepare({...input,expectedInputs:{one:{base:"a".repeat(40),commit:"b".repeat(40)}}})).toEqual(saved);expect(f.ledger.reservedForTasks(["one"])).toEqual([saved]);expect(f.ledger.forWorkflow(saved.successorWorkflowId)).toEqual(saved);expect(()=>f.ledger.prepare({...input,id:crypto.randomUUID()})).toThrow("already exists");}finally{f.db.close();}
});
test("accepted, prepared publication, live agent, missing frozen base and changed task tuple forbid rerun",()=>{
 const f=fixture();try{for(const variation of ["accepted","prepared","busy","protocol","missing","base","head","assignment","status","workflow"]){const snapshot=structuredClone(f.snapshot);switch(variation){case "accepted":snapshot.candidate.status="accepted";break;case "prepared":snapshot.publicationBlocked=true;break;case "busy":snapshot.busy=true;break;case "protocol":snapshot.candidate.preservationProtocolVersion=1;break;case "missing":delete snapshot.candidate.frozenContributorProofs;break;case "base":snapshot.tasks[0]!.baseCommit="d".repeat(40);break;case "head":snapshot.tasks[0]!.currentCommit="d".repeat(40);break;case "assignment":snapshot.tasks[0]!.activeCandidateId="other";break;case "status":snapshot.tasks[0]!.status="working";break;case "workflow":delete snapshot.candidate.workflowInstanceId;}
 expect(()=>assertLegacyRerunEligible(snapshot,snapshot.candidate.candidateCommit!)).toThrow();expect(()=>f.ledger.prepare({id:crypto.randomUUID(),expectedCommit:snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot})).toThrow();}expect(f.db.query("SELECT COUNT(*) AS count FROM legacy_candidate_reruns").get()).toEqual({count:0});}finally{f.db.close();}
});
test("saved scope is detached from caller mutations and receipt save rolls back with surrounding transaction",()=>{
 const f=fixture();try{const id=crypto.randomUUID(),saved=f.ledger.prepare({id,expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot});f.snapshot.candidate.review!.approved=false;f.snapshot.tasks[0]!.currentCommit="e".repeat(40);expect(f.ledger.get(id)).toEqual(saved);expect(()=>f.db.transaction(()=>{saved.phase="reassigned";f.ledger.save(saved);throw new Error("interruption");})()).toThrow("interruption");expect(f.ledger.get(id)?.phase).toBe("prepared");}finally{f.db.close();}
});
test("indexed lookup and exact replay survive audit capacity without loading unrelated snapshots",()=>{
 const f=fixture();try{const id=crypto.randomUUID(),input={id,expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot},saved=f.ledger.prepare(input);
 f.db.transaction(()=>{const insert=f.db.query("INSERT INTO legacy_candidate_reruns VALUES(?,?,?,?,?)");for(let i=0;i<9999;i++)insert.run(`historical-${i}`,`candidate-${i}`,`workflow-${i}`,"{}","unparsed unrelated history");})();
 expect(f.ledger.forWorkflow(saved.successorWorkflowId)).toEqual(saved);expect(f.ledger.forWorkflow("absent")).toBeNull();expect(f.ledger.reservedForTasks(["one"])).toEqual([saved]);expect(f.ledger.prepare(input)).toEqual(saved);
 const snapshot=structuredClone(f.snapshot);snapshot.candidate.id="another";snapshot.tasks[0]!.activeCandidateId="another";expect(()=>f.ledger.prepare({...input,id:crypto.randomUUID(),snapshot})).toThrow("audit capacity");expect(f.db.query("SELECT COUNT(*) AS count FROM legacy_candidate_reruns").get()).toEqual({count:10000});
 saved.phase="attached";f.ledger.save(saved);expect(f.ledger.reservedForTasks(["one"])).toEqual([]);expect(f.ledger.get(id)?.phase).toBe("attached");expect(f.ledger.hasCandidate("legacy")).toBe(true);expect(f.ledger.hasCandidate("unrelated")).toBe(false);expect(f.db.query("SELECT COUNT(*) AS count FROM legacy_candidate_reruns").get()).toEqual({count:10000});
 }finally{f.db.close();}
});
test("oversized row is refused before parsing and oversized new context never saves intent or reservations",()=>{
 const f=fixture();try{const input={id:crypto.randomUUID(),expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot};const snapshot=structuredClone(f.snapshot);snapshot.candidate.frozenVerificationPolicy={large:"x".repeat(128*1024)};
 expect(()=>f.ledger.prepare({...input,snapshot})).toThrow("safe review limit");expect(f.db.query("SELECT COUNT(*) AS count FROM legacy_candidate_reruns").get()).toEqual({count:0});expect(f.db.query("SELECT COUNT(*) AS count FROM legacy_candidate_rerun_reservations").get()).toEqual({count:0});
 const saved=f.ledger.prepare(input);f.db.query("UPDATE legacy_candidate_reruns SET doc=? WHERE id=?").run("not-json".repeat(20000),saved.id);expect(()=>f.ledger.get(saved.id)).toThrow("safe review limit");expect(()=>f.ledger.forWorkflow(saved.successorWorkflowId)).toThrow("safe review limit");expect(()=>f.ledger.reservedForTasks(["one"])).toThrow("safe review limit");expect(()=>f.ledger.reservedForTasks(Array.from({length:9},(_,i)=>String(i)))).toThrow("eight distinct");
 }finally{f.db.close();}
});
test("predispatch abandonment keeps immutable audit, permits a new generation, and cannot release its reservations on replay",()=>{
 const f=fixture();try{const input={id:crypto.randomUUID(),expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot},saved=f.ledger.prepare(input),original=structuredClone(saved);
 expect(()=>f.ledger.abandon(saved.id,{...actor,userId:"new-owner"})).toThrow("Stopped execution");saved.phase="stopped";saved.terminalState="terminated";saved.vmStopped=true;f.ledger.save(saved);
 const newOwner={...actor,userId:"new-owner"};const abandoned=f.ledger.abandon(saved.id,newOwner);expect(abandoned.phase).toBe("abandoned");expect(abandoned.abandoned?.by).toEqual(newOwner);expect(abandoned.actor).toEqual(original.actor);expect(abandoned.snapshot).toEqual(original.snapshot);expect(abandoned.createdAt).toBe(original.createdAt);expect(f.ledger.hasCandidate("legacy")).toBe(true);expect(f.ledger.reservedForTasks(["one"])).toEqual([]);
 const successor=f.ledger.prepare({...input,id:crypto.randomUUID()});expect(successor.id).not.toBe(saved.id);expect(f.ledger.forCandidate("legacy")?.id).toBe(successor.id);expect(f.ledger.abandon(saved.id,actor)).toEqual(abandoned);expect(f.ledger.reservedForTasks(["one"])[0]?.id).toBe(successor.id);expect(f.db.query("SELECT COUNT(*) AS count FROM legacy_candidate_reruns").get()).toEqual({count:2});
 }finally{f.db.close();}
});
test("unknown and observed dispatch block abandonment and dispatch observations never regress",()=>{
 for(const dispatch of ["unknown","observed"] as const){const f=fixture();try{const saved=f.ledger.prepare({id:crypto.randomUUID(),expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot});saved.phase="reassigned";saved.terminalState="terminated";saved.vmStopped=true;f.ledger.save(saved);expect(f.ledger.markDispatch(saved.id,dispatch).dispatch).toBe(dispatch);expect(()=>f.ledger.abandon(saved.id,actor)).toThrow("uncertain rerun");expect(f.ledger.reservedForTasks(["one"]).length).toBe(1);if(dispatch==="observed")expect(f.ledger.markDispatch(saved.id,"unknown").dispatch).toBe("observed");}finally{f.db.close();}}
});
test("product decision releases its exact reservation and continuation keeps immutable lineage with separate resolver",()=>{
 const f=fixture();try{const saved=f.ledger.prepare({id:crypto.randomUUID(),expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot}),original=structuredClone(saved);saved.phase="reassigned";saved.dispatch="observed";saved.vmStopped=true;saved.terminalState="terminated";f.ledger.save(saved);
 const pending=f.ledger.awaitDecision(saved.id,"choice-one");expect(pending.phase).toBe("awaiting_decision");expect(pending.successorDecisionId).toBe("choice-one");expect(f.ledger.reservedForTasks(["one"])).toEqual([]);expect(f.ledger.forWorkflow(saved.successorWorkflowId)?.id).toBe(saved.id);expect(f.ledger.markDispatch(saved.id,"observed").phase).toBe("awaiting_decision");
 const resolver={userId:"new-owner",displayName:"New maintainer",viaToken:true},workflow="decision-project-choice-one",continued=f.ledger.continueDecision(saved.id,"choice-one",workflow,resolver,"server-hash");expect(continued.phase).toBe("reassigned");expect(continued.actor).toEqual(original.actor);expect(continued.snapshot).toEqual(original.snapshot);expect(continued.createdAt).toBe(original.createdAt);expect(continued.continuationActor).toEqual(resolver);expect(continued.continuationCredentialHash).toBe("server-hash");expect(f.ledger.forWorkflow(workflow)).toEqual(continued);expect(f.ledger.reservedForTasks(["one"])[0]?.id).toBe(saved.id);expect(()=>f.ledger.continueDecision(saved.id,"choice-one",workflow,actor)).toThrow("no longer owns");
 }finally{f.db.close();}
});
test("wrong decision identity and competing reservations do not alter awaiting decision lineage",()=>{
 const f=fixture();try{const saved=f.ledger.prepare({id:crypto.randomUUID(),expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot});saved.phase="reassigned";f.ledger.save(saved);const pending=f.ledger.awaitDecision(saved.id,"choice-one");expect(()=>f.ledger.continueDecision(saved.id,"different-choice","different-workflow",actor)).toThrow("no longer owns");f.db.query("INSERT INTO legacy_candidate_rerun_reservations VALUES(?,?)").run("one",saved.id);expect(()=>f.ledger.continueDecision(saved.id,"choice-one","new-workflow",actor)).toThrow("assigned to other work");expect(f.ledger.get(saved.id)).toEqual(pending);expect(f.ledger.forWorkflow("new-workflow")).toBeNull();
 }finally{f.db.close();}
});
test("tracked modern failed and incomplete candidates rebuild from exact saved inputs without a marker downgrade",()=>{
 for(const status of ["composing","repairing","verifying","failed","stale"] as const){const f=fixture();try{f.snapshot.candidate.preservationProtocolVersion=1;f.snapshot.candidate.status=status;const before=structuredClone(f.snapshot);const saved=f.ledger.prepare({id:crypto.randomUUID(),expectedCommit:f.snapshot.candidate.candidateCommit!,actor,expectedInputs,snapshot:f.snapshot});expect(saved.snapshot).toEqual(before);expect(saved.snapshot.candidate.preservationProtocolVersion).toBe(1);expect(f.snapshot).toEqual(before);}finally{f.db.close();}}
 for(const status of ["verified","awaiting_review","accepted"] as const){const f=fixture();try{f.snapshot.candidate.preservationProtocolVersion=1;f.snapshot.candidate.status=status;expect(()=>assertLegacyRerunEligible(f.snapshot,f.snapshot.candidate.candidateCommit!)).toThrow();}finally{f.db.close();}}
});
test("missing composed SHA binds explicit null and preserved full snapshot; null cannot mask a known commit",()=>{
 const f=fixture();try{f.snapshot.candidate.preservationProtocolVersion=1;f.snapshot.candidate.status="failed";delete f.snapshot.candidate.candidateCommit;delete f.snapshot.candidate.review;const input={id:crypto.randomUUID(),expectedCommit:null,actor,expectedInputs,snapshot:f.snapshot};const saved=f.ledger.prepare(input);expect(saved.expectedCommit).toBeNull();expect(saved.snapshot.candidate.candidateCommit).toBeUndefined();expect(saved.snapshot.candidate.review).toBeUndefined();expect(f.ledger.prepare(input)).toEqual(saved);expect(()=>f.ledger.prepare({...input,expectedCommit:"c".repeat(40)})).toThrow("another rerun");
 const changed=structuredClone(f.snapshot);changed.candidate.frozenVerificationPolicy={newPolicy:true};expect(()=>f.ledger.prepare({...input,snapshot:changed})).toThrow("context changed");const changedTask=structuredClone(f.snapshot);changedTask.tasks[0]!.workspace.branch="other";expect(()=>f.ledger.prepare({...input,snapshot:changedTask})).toThrow("context changed");
 const row=f.db.query("SELECT payload FROM legacy_candidate_reruns WHERE id=?").get(saved.id) as {payload:string};const payload=JSON.parse(row.payload) as {snapshotFingerprint:string;expectedCommit:null};expect(payload.expectedCommit).toBeNull();expect(payload.snapshotFingerprint).toMatch(/^[a-f0-9]{64}$/);
 const known=structuredClone(f.snapshot);known.candidate.candidateCommit="c".repeat(40);expect(()=>assertLegacyRerunEligible(known,null)).toThrow();expect(()=>assertLegacyRerunEligible(known,"")).toThrow();expect(()=>assertLegacyRerunEligible(known,"c".repeat(64))).toThrow();expect(()=>assertLegacyRerunEligible(f.snapshot,"c".repeat(40))).toThrow();
 }finally{f.db.close();}
});
