import {test,expect} from 'bun:test';
import {Database} from 'bun:sqlite';
import {ManagedSpendLedger} from '../src/server/managed-spend-ledger';
import {MirrorExecutions,executeMirror,type MirrorExecutionScope,type MirrorExecutionDeps} from '../src/server/mirror-execution';
function fixture(options:{originalExpired?:boolean;denyBudget?:boolean;withdraw?:boolean;unknownPush?:boolean;cleanupUnknown?:boolean}={}){
 const db=new Database(':memory:');const storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T):T{return db.transaction(fn)();}} as unknown as DurableObjectStorage;
 const scope:MirrorExecutionScope={id:crypto.randomUUID(),projectId:'project',incarnation:crypto.randomUUID(),accountKey:'account',actorId:'owner',sessionExpiresAt:Date.now()+(options.originalExpired?-1000:60000),journalId:'accepted',canonicalRepoName:'canonical',acceptedRef:'refs/heads/main',commit:'a'.repeat(40),tree:'b'.repeat(40),target:'https://github.com/owned/repo.git',configDigest:'c'.repeat(64),exportApproved:true};
 const ledger=new MirrorExecutions(storage);ledger.prepare(scope,()=>{});let allowed=true,issued=0,pushes=0,reads=0,revokes=0,stops=0;
 const deps:MirrorExecutionDeps={authorize:async()=>{if(!allowed)throw Error('authority or config changed');},admit:async()=>{if(options.denyBudget)throw Error('budget refused');if(ledger.beginAdmission(scope.id,()=>{}))ledger.admissionGranted(scope.id,{nativeRunId:`mirror-${scope.id}`,seconds:1200,allowed:true});},issue:async()=>{issued++;expect(ledger.get(scope.id)?.phase).toBe('issuance_unknown');return{plaintext:'synthetic-owned-key',scope:'read',expiresAt:new Date(Date.now()+60000).toISOString()};},revoke:async()=>{revokes++;return !options.cleanupUnknown;},stop:async()=>{stops++;return{sealed:true,stopped:!options.cleanupUnknown};},readTarget:async()=>{reads++;return{success:true,commit:scope.commit};},exec:async(cmd)=>{expect(ledger.get(scope.id)?.nativePossible).toBe(true);if(cmd.includes('show -s')){if(options.withdraw)allowed=false;return{success:true,stdout:`${scope.commit}:${scope.tree}`,stderr:''};}if(cmd.includes('push --porcelain')){pushes++;if(options.unknownPush)throw Error('lost ACK');}return{success:true,stdout:'',stderr:''};},journal:{get:async()=>ledger.get(scope.id)!,beginIssue:async()=>ledger.beginIssue(scope.id,()=>{if(!allowed)throw Error('changed');}),recordCredential:async(token,expiry)=>ledger.recordCredential(scope.id,token,expiry),beginNative:async()=>ledger.beginNative(scope.id,()=>{if(!allowed)throw Error('changed');}),beginPush:async()=>ledger.beginPush(scope.id,()=>{if(!allowed)throw Error('changed');}),observed:async(result)=>ledger.observed(scope.id,result),credentialRevoked:async(token)=>ledger.credentialRevoked(scope.id,token,scope.canonicalRepoName,true),nativeStopped:async()=>ledger.nativeStopped(scope.id,`mirror-${scope.id}`,{sealed:true,stopped:true})},canonicalRemote:'https://owned.example/repo.git',githubToken:'synthetic-github-key'};
 return{scope,ledger,deps,storage,counts:()=>({issued,pushes,reads,revokes,stops}),close:()=>db.close()};
}
test('mirror budget denial issues no credentials and allocates no native execution',async()=>{const f=fixture({denyBudget:true});try{expect(await executeMirror(f.scope,f.deps)).toEqual({status:'held'});expect(f.counts()).toEqual({issued:0,pushes:0,reads:0,revokes:0,stops:0});expect(f.ledger.get(f.scope.id)?.phase).toBe('prepared');}finally{f.close();}});
test('withdrawal after source read refuses private export but cleans exact credentials/native',async()=>{const f=fixture({withdraw:true});try{expect((await executeMirror(f.scope,f.deps)).status).toBe('held');expect(f.counts().pushes).toBe(0);expect(f.ledger.get(f.scope.id)).toMatchObject({credentialRevoked:true,nativeStopped:true,token:null});}finally{f.close();}});
test('lost push ACK remains held then exact readonly observation completes without a second push',async()=>{const f=fixture({unknownPush:true});try{expect((await executeMirror(f.scope,f.deps)).status).toBe('held');expect(f.ledger.get(f.scope.id)?.phase).toBe('push_unknown');expect((await executeMirror(f.scope,f.deps)).status).toBe('complete');expect(f.counts()).toMatchObject({issued:1,pushes:1,reads:1});}finally{f.close();}});
test('positive mirror delivery cannot hide unconfirmed cleanup',async()=>{const f=fixture({cleanupUnknown:true});try{expect((await executeMirror(f.scope,f.deps)).status).toBe('held');expect(f.ledger.get(f.scope.id)?.result?.status).toBe('ok');expect(f.ledger.complete(f.scope.id)).toBe(false);}finally{f.close();}});
test('missing readback never authorizes a second push or changes frozen export target',async()=>{const f=fixture({unknownPush:true});try{await executeMirror(f.scope,f.deps);f.deps.readTarget=async()=>({success:true,commit:null});expect((await executeMirror(f.scope,f.deps)).status).toBe('held');expect(f.counts().pushes).toBe(1);expect(()=>f.ledger.prepare({...f.scope,target:'https://github.com/other/repo.git'},()=>{})).toThrow('scope changed');expect(()=>f.ledger.recordCredential(f.scope.id,'different-key',Date.now()+60000)).toThrow();}finally{f.close();}});

test('native owned Git mirror selects recorded main despite different HEAD and reconciles lost ACK without repush',async()=>{
 const {mkdtemp,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const root=await mkdtemp(join(tmpdir(),'mirror-native-')),source=join(root,'source.git'),target=join(root,'target.git'),seed=join(root,'seed'),work=join(root,'mirror');const f=fixture({unknownPush:true});let pushCount=0,closed=0,lostAck=true;
 const git=async(args:string[])=>{const child=Bun.spawn(['git',...args],{stdout:'pipe',stderr:'pipe',env:{...process.env,GIT_AUTHOR_NAME:'Owned fixture',GIT_AUTHOR_EMAIL:'fixture@localhost',GIT_COMMITTER_NAME:'Owned fixture',GIT_COMMITTER_EMAIL:'fixture@localhost'}});const [stdout,stderr,exitCode]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return{success:exitCode===0,stdout,stderr};};
 try{for(const repo of[source,target])expect((await git(['init','--bare','--initial-branch=main',repo])).success).toBe(true);await git(['clone',source,seed]);await Bun.write(join(seed,'README.md'),'Accepted main\n');await git(['-C',seed,'add','.']);await git(['-C',seed,'commit','-m','accepted']);await git(['-C',seed,'push','origin','main']);const commit=(await git(['-C',seed,'rev-parse','HEAD'])).stdout.trim(),tree=(await git(['-C',seed,'rev-parse','HEAD^{tree}'])).stdout.trim();await git(['-C',seed,'checkout','-b','different']);await Bun.write(join(seed,'README.md'),'Different provider HEAD\n');await git(['-C',seed,'commit','-am','different']);await git(['-C',seed,'push','origin','different']);await git(['--git-dir',source,'symbolic-ref','HEAD','refs/heads/different']);
 const scope={...f.scope,id:crypto.randomUUID(),commit,tree};f.ledger.prepare(scope,()=>{});f.deps.canonicalRemote=source;f.deps.admit=async()=>{if(f.ledger.beginAdmission(scope.id,()=>{}))f.ledger.admissionGranted(scope.id,{nativeRunId:`mirror-${scope.id}`,seconds:1200,allowed:true});};
 f.deps.journal={get:async()=>f.ledger.get(scope.id)!,beginIssue:async()=>f.ledger.beginIssue(scope.id,()=>{}),recordCredential:async(token,expiry)=>f.ledger.recordCredential(scope.id,token,expiry),beginNative:async()=>f.ledger.beginNative(scope.id,()=>{}),beginPush:async()=>f.ledger.beginPush(scope.id,()=>{}),observed:async(result)=>f.ledger.observed(scope.id,result),credentialRevoked:async(token)=>f.ledger.credentialRevoked(scope.id,token,scope.canonicalRepoName,true),nativeStopped:async()=>f.ledger.nativeStopped(scope.id,`mirror-${scope.id}`,{sealed:true,stopped:true})};
 f.deps.issue=async()=>({plaintext:'synthetic-owned-key',scope:'read',expiresAt:new Date(Date.now()+60000).toISOString()});
 f.deps.exec=async(cmd,env)=>{const local=cmd.replaceAll("'/tmp/mirror'",`'${work}'`).replaceAll(`'${scope.target}'`,`'${target}'`);const child=Bun.spawn(['sh','-c',local],{stdout:'pipe',stderr:'pipe',env:{...process.env,...env}});const [stdout,stderr,exitCode]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(cmd.includes('push --porcelain')){pushCount++;if(lostAck){expect(exitCode).toBe(0);lostAck=false;throw Error('owned receiver ACK lost');}}return{success:exitCode===0,stdout,stderr};};
 f.deps.readTarget=async(ref)=>{const observed=await git(['ls-remote','--heads',target,ref]);return{success:observed.success,commit:observed.stdout.trim().split(/\s+/)[0]||null};};f.deps.stop=async()=>{closed++;return{sealed:true,stopped:true};};
 expect((await executeMirror(scope,f.deps)).status).toBe('held');expect((await git(['--git-dir',target,'rev-parse','main'])).stdout.trim()).toBe(commit);expect((await git(['--git-dir',target,'show-ref','--verify','refs/heads/different'])).success).toBe(false);expect((await executeMirror(scope,f.deps)).status).toBe('complete');expect(pushCount).toBe(1);expect(closed).toBe(2);
 const unrelated=(await git(['-C',seed,'rev-parse','HEAD'])).stdout.trim();await git(['-C',seed,'push',target,'HEAD:refs/heads/main']);const next={...scope,id:crypto.randomUUID()};f.ledger.prepare(next,()=>{});f.deps.admit=async()=>{if(f.ledger.beginAdmission(next.id,()=>{}))f.ledger.admissionGranted(next.id,{nativeRunId:`mirror-${next.id}`,seconds:1200,allowed:true});};f.deps.journal={get:async()=>f.ledger.get(next.id)!,beginIssue:async()=>f.ledger.beginIssue(next.id,()=>{}),recordCredential:async(token,expiry)=>f.ledger.recordCredential(next.id,token,expiry),beginNative:async()=>f.ledger.beginNative(next.id,()=>{}),beginPush:async()=>f.ledger.beginPush(next.id,()=>{}),observed:async(result)=>f.ledger.observed(next.id,result),credentialRevoked:async(token)=>f.ledger.credentialRevoked(next.id,token,next.canonicalRepoName,true),nativeStopped:async()=>f.ledger.nativeStopped(next.id,`mirror-${next.id}`,{sealed:true,stopped:true})};expect((await executeMirror(next,f.deps)).status).toBe('held');expect((await git(['--git-dir',target,'rev-parse','main'])).stdout.trim()).toBe(unrelated);expect((await executeMirror(next,f.deps)).status).toBe('held');expect(pushCount).toBe(2);
 }finally{f.close();await rm(root,{recursive:true,force:true});}
});
test('old original session and changed configuration do not block owner-only readonly lost ACK recovery',async()=>{const f=fixture({unknownPush:true,originalExpired:true});try{await executeMirror(f.scope,f.deps);const modes:string[]=[];f.deps.authorize=async(mode)=>{modes.push(mode);if(mode==='dispatch')throw Error('configuration withdrawn');};expect((await executeMirror(f.scope,f.deps)).status).toBe('complete');expect(modes.length).toBeGreaterThan(0);expect(modes.every(mode=>mode==='reconcile')).toBe(true);expect(f.counts().pushes).toBe(1);}finally{f.close();}});
test('completed mirror replay returns original receipt after fresh authority without budget or provider work',async()=>{const f=fixture();try{const first=await executeMirror(f.scope,f.deps);expect(first.status).toBe('complete');const counts=f.counts();let authorization=0;f.deps.authorize=async(mode)=>{expect(mode).toBe('reconcile');authorization++;};f.deps.admit=async()=>{throw Error('exhausted');};expect(await executeMirror(f.scope,f.deps)).toEqual(first);expect(authorization).toBeGreaterThan(0);expect(f.counts()).toEqual(counts);}finally{f.close();}});
test('owner API token provenance has no invented session expiry and requires its real credential binding',()=>{const f=fixture();try{expect(()=>f.ledger.prepare({...f.scope,id:crypto.randomUUID(),sessionExpiresAt:null},()=>{})).toThrow();const tokenScope={...f.scope,id:crypto.randomUUID(),sessionExpiresAt:null,credentialHash:'d'.repeat(64)};expect(f.ledger.prepare(tokenScope,()=>{}).scope.sessionExpiresAt).toBeNull();}finally{f.close();}});
test('actual managed spend receipt is reused after paid admission interruption and never consumed on lost ACK reconcile',async()=>{const f=fixture({unknownPush:true}),spend=new ManagedSpendLedger(f.storage),runId=`mirror-${f.scope.id}`;try{const admitted=spend.reserve({resourceKind:'native-optional',runId,accountKey:f.scope.accountKey,usdMicros:43008,maxInputBytes:1,maxOutputTokens:1,maxCalls:1,maxContainerSeconds:1200},{accountUsdMicros:100000,globalUsdMicros:100000});expect(admitted.allowed).toBe(true);expect(f.ledger.beginAdmission(f.scope.id,()=>{})).toBe(true);spend.consume(runId,0,0,1200);let admissionCallbacks=0;f.deps.admit=async()=>{admissionCallbacks++;const paid=spend.get(runId)!;expect(paid.calls).toBe(1);expect(paid.containerSeconds).toBe(1200);f.ledger.admissionGranted(f.scope.id,{nativeRunId:runId,seconds:1200,allowed:true});};expect((await executeMirror(f.scope,f.deps)).status).toBe('held');expect(admissionCallbacks).toBe(1);f.deps.admit=async()=>{throw Error('original paid admission must not repeat');};expect((await executeMirror(f.scope,f.deps)).status).toBe('complete');expect(spend.get(runId)).toMatchObject({calls:1,containerSeconds:1200});expect(f.counts().pushes).toBe(1);}finally{f.close();}});
