import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {CandidateGeneration,PublicationJournalEntry,FlareGitProjectState,Task} from '../src/core/types';
import type {AcceptedBranchRoot} from '../src/server/accepted-branch-roots';
test('native nonprimary acceptance isolates two roots, rejects a stale target, and replays exact original journal without changing primary history',async()=>{
 if(await workerdChild('tests/nonprimary-publication-native.test.ts'))return;
 const output=`/tmp/flaregit-nonprimary-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/accepted-target-binding-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'nonprimary',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'AcceptedTargetFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('nonprimary'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})});const json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body);const value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 await call('/seed');for(const name of ['release','staging'])await call('/create',{operationId:crypto.randomUUID(),name,sourceCommit:'a'.repeat(40)});
 await json('/legacy-baseline');
 const primaryBefore=(await json<FlareGitProjectState>('/state-full')).acceptedState;
 for(const [id,ref] of [['task-release','release'],['task-stale','release'],['task-staging','staging']] as const)await json<Task>('/target-task',{id,ref:`refs/heads/${ref}`});
 async function prepare(id:string,holder:string,commit:string){const {candidate}=await json<{candidate:CandidateGeneration}>('/landing',{tasks:[id],holder});await json('/verify-target',{id:candidate.id,bind:true,commit});const target=candidate.acceptedTarget!;const review=await json<{ok:boolean;error?:string}>('/review-target',{id:candidate.id,commit,target:{ref:target.ref,acceptedCommit:target.acceptedCommit,acceptedVersion:target.acceptedVersion}});if(!review.ok)throw Error(review.error);const result=await json<{ok:boolean;error?:string;journal:PublicationJournalEntry}>('/prepare?id='+candidate.id);if(!result.ok)throw Error(result.error);expect(await json<boolean>('/authorize?id='+candidate.id+'&commit='+commit)).toBe(true);return result.journal;}
 const release=await prepare('task-release','release-holder','b'.repeat(40));await json('/cancel-target?id=task-release');expect(await json<boolean>('/authorize?id='+release.candidateId+'&commit='+release.newHead)).toBe(false);expect(await json<boolean>('/authorize-readback?id='+release.candidateId+'&journal='+release.id+'&commit='+release.newHead)).toBe(true);await json('/mutate-root');expect(await json<boolean>('/authorize?id='+release.candidateId+'&commit='+release.newHead)).toBe(false);expect(await json<boolean>('/authorize-readback?id='+release.candidateId+'&journal='+release.id+'&commit='+release.newHead)).toBe(true);expect(await json('/observe-readback?id='+release.candidateId+'&journal='+release.id+'&commit='+release.newHead)).toMatchObject({status:'landed',ref:'refs/heads/release',observedRef:'refs/heads/release'});expect(await json('/observe-readback?id='+release.candidateId+'&journal='+release.id+'&commit='+release.newHead+'&mode=missing')).toMatchObject({status:'not_landed'});expect(await json('/observe-readback?id='+release.candidateId+'&journal='+release.id+'&commit='+release.newHead+'&mode=absent')).toMatchObject({status:'unavailable'});const pending=await json<FlareGitProjectState>('/abort-target',{id:release.candidateId,journal:release.id});expect(pending.journal.find(row=>row.id===release.id)?.state).toBe('PREPARED');const first=await json<FlareGitProjectState>('/complete-target',{journalId:release.id});await json('/restore-policy?id='+release.candidateId);expect(first.acceptedState).toEqual(primaryBefore);expect(await json('/recovery-targets')).toMatchObject([{journalId:'baseline',commit:'a'.repeat(40)}]);expect(first.journal.find(row=>row.id===release.id)?.acceptedTarget?.ref).toBe('refs/heads/release');
 const roots1=await json<{roots:AcceptedBranchRoot[]}>('/registry');expect(roots1.roots.find(root=>root.ref==='refs/heads/release')).toMatchObject({head:'b'.repeat(40),version:1});expect(roots1.roots.find(root=>root.ref==='refs/heads/staging')).toMatchObject({head:'a'.repeat(40),version:0});
 const stale=await json<{reason:string}>('/landing',{tasks:['task-stale'],holder:'stale-holder'});expect(stale.reason).toContain('target');
 const staging=await prepare('task-staging','staging-holder','b'.repeat(40));const second=await json<FlareGitProjectState>('/complete-target',{journalId:staging.id});expect(second.acceptedState).toEqual(primaryBefore);
 await json<Task>('/target-task',{id:'task-release-next',ref:'refs/heads/release'});const next=await prepare('task-release-next','next-holder','d'.repeat(40));await json('/complete-target',{journalId:next.id});const advanced=await json<{roots:AcceptedBranchRoot[]}>('/registry');expect(advanced.roots.find(root=>root.ref==='refs/heads/release')).toMatchObject({head:'d'.repeat(40),version:2});
 await json('/mutate-default?branch=release');
 await json('/complete-target',{journalId:release.id});const replay=await json<{roots:AcceptedBranchRoot[]}>('/registry');expect(replay.roots.find(root=>root.ref==='refs/heads/release')).toEqual(advanced.roots.find(root=>root.ref==='refs/heads/release'));expect((await json<FlareGitProjectState>('/state-full')).acceptedState).toEqual(primaryBefore);
 await json<Task>('/target-task',{id:'task-cancel-safe',ref:'refs/heads/staging'});const safe=await prepare('task-cancel-safe','safe-cancel-holder','f'.repeat(40));const cancelId=crypto.randomUUID();expect((await call('/cancel-publication',{id:safe.candidateId,journal:safe.id,eventId:cancelId})).ok).toBe(false);await json('/seal-target-runtime?id='+safe.candidateId);expect(await json('/cancel-publication',{id:safe.candidateId,journal:safe.id,eventId:cancelId})).toMatchObject({cancelled:true,journalId:safe.id});expect(await json('/cancel-publication',{id:safe.candidateId,journal:safe.id,eventId:cancelId})).toMatchObject({cancelled:true});expect((await json<FlareGitProjectState>('/state-full')).acceptedState).toEqual(primaryBefore);
 await json<Task>('/target-task',{id:'task-cancel-unknown',ref:'refs/heads/staging'});const unknown=await prepare('task-cancel-unknown','unknown-cancel-holder','f'.repeat(40));expect(await json<boolean>('/mark-dispatch?id='+unknown.candidateId+'&journal='+unknown.id+'&commit='+unknown.newHead)).toBe(true);await json('/seal-target-runtime?id='+unknown.candidateId);expect((await call('/cancel-publication',{id:unknown.candidateId,journal:unknown.id,eventId:crypto.randomUUID()})).ok).toBe(false);expect((await json<FlareGitProjectState>('/state-full')).journal.find(row=>row.id===unknown.id)?.state).toBe('PREPARED');
 }finally{await mf.dispose();}
},30000);
