import {expect,test} from "bun:test";
import {renderToStaticMarkup} from "react-dom/server";
import {PendingTaskCreations} from "../src/web/components/PendingTaskCreations";
import {parseTaskCreationRecovery,restoreTaskCreationRequest,type PendingTaskCreation} from "../src/web/task-creation-recovery";
const record:PendingTaskCreation={taskId:"original-request",input:{goal:"Original purpose",dependsOn:null,issue:null,expectedTarget:{ref:"refs/heads/release",acceptedCommit:"a".repeat(40),acceptedVersion:3,policyVersion:2}},phase:"fork_unknown",canRestore:false,canRetry:false};
const render=(records:PendingTaskCreation[])=>renderToStaticMarkup(<PendingTaskCreations records={records} busy={false} error={null} onRefresh={()=>{}} onRestore={()=>{}} defaultOpen/>);
test("real pending intent context is separate from tasks and unknown fork cannot offer a replacement retry",()=>{const html=render([record]);expect(html).toContain("Original purpose");expect(html).toContain(record.taskId);expect(html).toContain("a".repeat(40));expect(html).toContain("Fork outcome unconfirmed");expect(html).toContain("not currently safe to retry");expect(html).not.toContain("Restore saved request");expect(html).not.toContain("Changes (1)");expect(render([])).toBe("");});
test("safe original creator can restore context while owner viewing another creator remains readonly",()=>{expect(render([{...record,phase:"fork_confirmed",canRestore:true,canRetry:true}])).toContain("Restore saved request");expect(render([{...record,phase:"committed"}])).toBe("");const base={...record,eventId:crypto.randomUUID(),credentialState:"issuance_unknown",providerAcknowledgementKnown:false,isCreator:false,hasTask:false,sourceCurrent:true,canRetryOriginal:false,createdAt:1,updatedAt:1};const {canRetry:_canRetry,...dto}=base;expect(parseTaskCreationRecovery({creations:[dto],nextCursor:null,complete:true}).creations[0]?.canRestore).toBe(false);expect(()=>parseTaskCreationRecovery({creations:[{...dto,canRestore:true}],nextCursor:null,complete:true})).toThrow();expect(()=>parseTaskCreationRecovery({creations:[{...dto,token:"private-token"}],nextCursor:null,complete:true})).toThrow();});

test("known fork acknowledgement remains distinct from verification and aggregate credential cleanup",()=>{const html=render([{...record,phase:"dispatching",providerAcknowledgementKnown:true}]);expect(html).toContain("Fork recorded · verification pending");expect(html).not.toContain("Fork acknowledgement pending");expect(html).not.toContain("Restore saved request");expect(html).toContain("not currently safe to retry");expect(render([{...record,phase:"dispatching",providerAcknowledgementKnown:false}])).toContain("Fork acknowledgement pending");});

test("captured default target is display context and never changes original retry input",()=>{const capturedTarget={ref:"refs/heads/trunk",branch:"trunk",acceptedCommit:null,acceptedVersion:0,policyVersion:1},input={goal:"First work",dependsOn:null,issue:null},dto={taskId:record.taskId,eventId:crypto.randomUUID(),input,capturedTarget,phase:"dispatching",credentialState:"revoked",providerAcknowledgementKnown:true,isCreator:true,hasTask:false,sourceCurrent:true,canRetryOriginal:false,canRestore:false,createdAt:1,updatedAt:1};const parsed=parseTaskCreationRecovery({creations:[dto],nextCursor:null,complete:true}).creations[0]!;const html=render([{...parsed,canRetry:parsed.canRetryOriginal}]);expect(html).toContain("Captured accepted branch");expect(html).toContain(capturedTarget.ref);expect(html).toContain("No accepted commit yet");expect(html).not.toContain("No explicit accepted branch");const restored=restoreTaskCreationRequest(parsed.taskId,parsed.input);expect(restored.intent.taskId).toBe(record.taskId);expect(restored.target).toBeNull();expect(restored.intent.payload.expectedTarget).toBeUndefined();expect(()=>parseTaskCreationRecovery({creations:[{...dto,capturedTarget:{...capturedTarget,branch:"main"}}],nextCursor:null,complete:true})).toThrow();});
