import {test,expect} from 'bun:test';
import {dispatchPreparedPublication} from '../src/server/prepared-publication-dispatch';
import {accountKeyFor} from '../src/server/projects';
import type {Env} from '../src/server/env';
test.each(['normal','lost-ack','changed','accepted','foreign-receipt','last-auth-change'] as const)('production dispatcher uses one journal-derived Workflow identity with local controller ports: %s',async mode=>{
 const actor={userId:'owner',displayName:'Owner',viaToken:false},id='jrnl_11111111-1111-4111-8111-111111111111',commit='b'.repeat(40),tree='d'.repeat(40),projectId='p123456abcdef',incarnation='22222222-2222-4222-8222-222222222222',candidate={id:'candidate',candidateCommit:commit,evidenceId:'evidence',workflowInstanceId:'original',acceptedTarget:{incarnation,ref:'refs/heads/main'},review:{approved:true,commit,actor}},journal={id,candidateId:'candidate',newHead:commit,candidateTree:tree,state:['accepted','foreign-receipt'].includes(mode)?'ACCEPTED':'PREPARED',publicationAuthority:{kind:'human-review',actor}},state={projectId,candidates:{candidate},journal:[journal],evidence:{evidence:{id:'evidence',status:'passed',candidateCommit:commit,candidateTree:tree}}};
 let creates=0,reads=0;const project={getState:async()=>state,getWorkflowRun:async()=>({kind:'integration',actorId:'owner'}),acceptedPublicationReceipt:async()=>({commit,candidateId:mode==='foreign-receipt'?'foreign':'candidate',journalId:id,ref:'refs/heads/main',evidenceId:'evidence',tree}),authorizeCandidatePublication:async()=>mode!=='changed',candidateRuntimeInspection:async()=>({protocol:1,coverage:true,allocations:[{stopped:true}],commands:{pending:0},verificationClosure:{status:'closed',credentials:{status:'revoked'}}})} as unknown as Parameters<typeof dispatchPreparedPublication>[1],now=Date.now(),source='c'.repeat(40),phase={projectId,incarnation,workflowId:'original',candidateId:'candidate',actorId:'owner',accountKey:await accountKeyFor('owner'),journalId:id,commit,tree,evidenceId:'evidence',reviewActorId:'owner',sourceVersion:source,image:'registry.cloudflare.com/'+'a'.repeat(32)+'/verifier@sha256:'+'b'.repeat(64),activatedAt:now-1000,admissionExpiresAt:now+60000,nativeStopAt:now+120000,maxAllocations:1,maxContainerSeconds:1200,maxCommands:64,kind:'native-essential'},env={FLAREGIT_SOURCE_VERSION:source,CF_VERSION_METADATA:{id:'33333333-3333-4333-8333-333333333333'},PUBLICATION_NATIVE_PHASE_JSON:JSON.stringify(phase),INTEGRATION_WORKFLOW:{create:async(input:{id:string;params:unknown})=>{creates++;expect(input).toEqual({id:`pub-${id}`,params:{mode:'prepared-publication',projectId,candidateId:'candidate',journalId:id}});if(mode==='lost-ack')throw Error('Synthetic response lost');},get:async(requested:string)=>{reads++;expect(requested).toBe(`pub-${id}`);return{status:async()=>({status:'running'})};}}} as unknown as Env;
 let authCalls=0;const operation=dispatchPreparedPublication(env,project,projectId,'candidate',{journalId:id,expectedCommit:commit},actor,async()=>{authCalls++;if(mode==='last-auth-change'&&authCalls===3)candidate.review={...candidate.review,approved:false};return Date.now()+60000;});if(['changed','foreign-receipt','last-auth-change'].includes(mode)){await expect(operation).rejects.toThrow();expect(creates).toBe(0);}else{const result=await operation;expect(result.accepted).toBe(mode==='accepted');expect(creates).toBe(mode==='accepted'?0:1);expect(reads).toBe(mode==='lost-ack'?1:0);}
});
