import {test,expect} from 'bun:test';import {preparedPublicationFailure,preparedPublicationRequest,checkedPreparedPublicationReceipt,savePreparedPublicationIntent,readPreparedPublicationIntent,type PreparedPublicationRequest} from '../src/web/prepared-publication-recovery';import type {CandidateGeneration,PublicationJournalEntry} from '../src/core/types';
const id='jrnl_11111111-1111-4111-8111-111111111111',commit='b'.repeat(40),request:PreparedPublicationRequest={journalId:id,expectedCommit:commit},actor={userId:'owner',displayName:'Owner',viaToken:false};
const candidate:CandidateGeneration={id:'candidate',attemptNumber:1,participatingTaskIds:[],participatingCommits:{},expectedAcceptedBase:'a'.repeat(40),frozenPolicyVersion:1,frozenVerificationPolicy:{},frozenRequirements:[],repairAttempts:[],status:'verified',preservationProtocolVersion:1,candidateCommit:commit,review:{approved:true,by:'Owner',at:'now',commit,actor},createdAt:'now',updatedAt:'now'};
const journal:PublicationJournalEntry={id,candidateId:'candidate',candidateCommit:commit,newHead:commit,expectedHead:'a'.repeat(40),state:'PREPARED',timestamp:'now',outputDigest:'d'.repeat(64),publicationAuthority:{kind:'human-review',actor,commit,tree:'c'.repeat(40),policyVersion:1,authorizedAt:'now',reviewedAt:'now'}};
test('only the existing approved exact human journal becomes publication identity',()=>{expect(preparedPublicationRequest(candidate,[journal])).toEqual(request);for(const rows of [undefined,[{...journal,newHead:'e'.repeat(40)}],[{...journal,state:'ACCEPTED' as const}],[journal,journal]])expect(preparedPublicationRequest(candidate,rows)).toBeNull();expect(preparedPublicationRequest({...candidate,review:{...candidate.review!,approved:false}},[journal])).toBeNull();expect(preparedPublicationRequest({...candidate,preservationProtocolVersion:undefined},[journal])).toBeNull();});
test('unknown acknowledgement reload and retry retain exact journal and commit; identities never overwrite',()=>{const values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);}};savePreparedPublicationIntent(storage,'owner','repo','candidate',{request,state:'unknown'});expect(readPreparedPublicationIntent(storage,'owner','repo','candidate',request)).toEqual({request,state:'unknown'});expect(readPreparedPublicationIntent(storage,'other','repo','candidate',request)).toBeNull();expect(()=>savePreparedPublicationIntent(storage,'owner','repo','candidate',{request:{...request,expectedCommit:'f'.repeat(40)},state:'unknown'})).toThrow();expect(readPreparedPublicationIntent(storage,'owner','repo','candidate',request)?.request).toEqual(request);});
test('requested job does not imply acceptance and altered receipt cannot settle recovery',()=>{const receipt=checkedPreparedPublicationReceipt({publicationRequested:true,workflowId:'pub-'+id,journalId:id,accepted:false},'candidate',request);expect(receipt.accepted).toBe(false);expect(()=>checkedPreparedPublicationReceipt({publicationRequested:true,workflowId:'integration-original',journalId:id,accepted:false},'candidate',request)).toThrow();const accepted={publicationRequested:false,accepted:true,duplicate:true,receipt:{commit,ref:'refs/heads/main',journalId:id,candidateId:'candidate',evidenceId:'evidence',tree:'c'.repeat(40)}};expect(checkedPreparedPublicationReceipt(accepted,'candidate',request).accepted).toBe(true);expect(()=>checkedPreparedPublicationReceipt({...accepted,receipt:{...accepted.receipt,commit:'e'.repeat(40)}},'candidate',request)).toThrow();});

test('explicit no-grant pause is distinct from a missing publication acknowledgement',()=>{expect(preparedPublicationFailure({status:503,message:'Publication is paused until a separate execution grant is configured. Your review and candidate are saved.'})).toBe('paused');expect(preparedPublicationFailure({status:409,message:'Publisher acknowledgement is unconfirmed.'})).toBe('unknown');expect(preparedPublicationFailure({status:503,message:'Network unavailable'})).toBe('unknown');});
