import {previewOnboardingViewSchema} from '../src/core/preview-onboarding-view';
import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {workerdChild} from './support/workerd-child';
test('actual preview onboarding HTTP enforces owner intent and preserves isolated provisioning authority',async()=>{
 if(await workerdChild('tests/preview-onboarding-http.test.ts'))return;
 const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'replay-local',alg:'RS256',use:'sig'},issuer=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({keys:[jwk]})});
 const build=await Bun.build({entrypoints:['tests/support/preview-onboarding-http-worker.ts'],target:'browser',external:['cloudflare:workers','node:*']});if(!build.success)throw Error(build.logs.map(String).join('\n'));
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'replay-http',unsafeDirectSockets:[{host:'127.0.0.1'}],modules:true,script:await build.outputs[0]!.text(),bindings:{FIXTURE_ISSUER:issuer.url.origin,PREVIEW_PROVISIONING_ENABLED:'false',PREVIEW_PROVISIONING_GLOBAL_LIMIT:'0',PREVIEW_PROVISIONING_ACCOUNT_ID:'a'.repeat(32),PREVIEW_PROVISIONING_API_TOKEN:'synthetic-local-only',PREVIEW_PROVISIONING_SUBDOMAIN:'isolated',PREVIEW_PROVISIONING_BROKER_SERVICE:'asset-broker',PREVIEW_PROVISIONING_MODULE:'x',PREVIEW_PROVISIONING_MODULE_SHA256:'2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881',PREVIEW_PROVISIONING_COMPATIBILITY_DATE:'2026-10-02'},compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'PreviewOnboardingFixture',useSQLite:true}}}]}));
 try{const direct=await mf.unsafeGetDirectURL('replay-http'),call=(path:string,token?:string,body?:unknown)=>fetch(new URL(path,direct),{method:body===undefined?'GET':'POST',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.83',...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}),session=async(id:string,expired=false)=>new SignJWT({azp:'https://fixture.example'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer.url.origin).setSubject(id).setIssuedAt().setExpirationTime(expired?Math.floor(Date.now()/1000)-120:'5m').sign(pair.privateKey),owner=await session('owner'),member=await session('reader'),expired=await session('owner',true),{read,full,fullId}=await(await call('/fixture/seed')).json() as {read:string;full:string;fullId:string},path='/api/p/p123456abcdef/preview-onboarding',original={requestId:crypto.randomUUID(),action:'prepare'};
 const disabled=await call(path,owner);expect(disabled.status).toBe(200);expect(previewOnboardingViewSchema.parse(await disabled.json())).toMatchObject({status:'disabled',canPrepare:false});expect(await(await call('/fixture/calls')).json() as number).toBe(0);
 expect((await call(path+'?unexpected=1',owner)).status).toBe(400);expect((await call(path,owner,{})).status).toBe(400);expect((await call(path,member,original)).status).toBe(403);expect((await call(path,read,original)).status).toBe(403);expect((await call(path,expired,original)).status).toBe(401);
 await call('/fixture/enable');const prepared=await call(path,full,original);expect(prepared.status).toBe(200);expect(previewOnboardingViewSchema.parse(await prepared.json())).toMatchObject({status:'active',canPrepare:false,requestId:original.requestId});const provisionedCalls=await(await call('/fixture/calls')).json() as number;const repeatedPrepare=await call(path,full,original);expect(repeatedPrepare.status).toBe(200);expect(previewOnboardingViewSchema.parse(await repeatedPrepare.json())).toMatchObject({status:'active',requestId:original.requestId});expect(await(await call('/fixture/calls')).json() as number).toBe(provisionedCalls);const ownerView=await call(path,owner);expect(previewOnboardingViewSchema.parse(await ownerView.json())).toMatchObject({requestId:original.requestId});const memberView=await call(path,member);expect(memberView.status).toBe(200);expect(previewOnboardingViewSchema.parse(await memberView.json()).requestId).toBeUndefined();
 const resumed=await call(path,full,{...original,action:'resume'});expect(resumed.status).toBe(200);expect(previewOnboardingViewSchema.parse(await resumed.json())).toMatchObject({status:'active',requestId:original.requestId});const before=await(await call('/fixture/calls')).json() as number;await call('/fixture/revoke?id='+fullId);expect((await call(path,full,{...original,action:'resume'})).status).toBe(401);expect(await(await call('/fixture/calls')).json() as number).toBe(before);
 }finally{await mf.dispose();issuer.stop(true);}
},30000);
