import {test,expect} from "bun:test";
import {Database} from "bun:sqlite";
import {mkdtemp,rm,mkdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {PreviewSourceStorage,PREVIEW_SOURCE_CACHE_BYTES,type PreviewSourceIdentity} from "../src/server/preview-source-storage";
import {captureTrustedGitSource,type TrustedGitSource} from "../src/server/trusted-git-source";
import {bindBuildManifest} from "../src/server/static-build-artifact";
class SqliteKV{
 db=new Database(":memory:");chunkWrites=0;failWrite=false;failDelete=false;loseCompletionAck=false;
 constructor(){this.db.exec("CREATE TABLE kv(key TEXT PRIMARY KEY,kind TEXT,value BLOB)");}
 async get<T>(key:string):Promise<T|undefined>{const row=this.db.query("SELECT kind,value FROM kv WHERE key=?").get(key) as {kind:string;value:Uint8Array|string}|null;return row?(row.kind==="bytes"?new Uint8Array(row.value as Uint8Array):JSON.parse(row.value as string)) as T:undefined;}
 async put(key:string,value:unknown){if(value instanceof Uint8Array){if(value.byteLength>65536)throw Error("Source chunk exceeds storage bound");this.chunkWrites++;if(this.failWrite&&key.includes(":file:"))throw Error("Synthetic uncertain source write");this.db.query("INSERT OR REPLACE INTO kv VALUES(?,?,?)").run(key,"bytes",value);}else{const encoded=JSON.stringify(value);if(new TextEncoder().encode(encoded).byteLength>65536)throw Error("Source metadata value exceeds storage bound");this.db.query("INSERT OR REPLACE INTO kv VALUES(?,?,?)").run(key,"json",encoded);}}
 async delete(key:string){if(this.failDelete)throw Error("Synthetic unknown chunk deletion");return this.db.query("DELETE FROM kv WHERE key=?").run(key).changes===1;}
 async transaction<T>(callback:(storage:SqliteKV)=>Promise<T>){this.db.exec("BEGIN");let result:T;try{result=await callback(this);this.db.exec("COMMIT");}catch(error){this.db.exec("ROLLBACK");throw error;}if(this.loseCompletionAck&&this.db.query("SELECT key FROM kv WHERE key LIKE '%:complete'").get()){this.loseCompletionAck=false;throw Error("Synthetic lost commit acknowledgment");}return result;}
 port(){return this as unknown as Pick<DurableObjectStorage,"get"|"put"|"delete"|"transaction">;}
 keys(){return(this.db.query("SELECT key FROM kv ORDER BY key").all() as Array<{key:string}>).map(row=>row.key);}
}
async function fixture(){const directory=await mkdtemp(join(tmpdir(),"flaregit-source-cache-")),git=async(...args:string[])=>{const process=Bun.spawn(["git",...args],{cwd:directory,stdout:"pipe",stderr:"pipe"});const [bytes,error,code]=await Promise.all([new Response(process.stdout).arrayBuffer(),new Response(process.stderr).text(),process.exited]);if(code!==0)throw Error(error);return new Uint8Array(bytes);};await git("init","-b","main");await git("config","user.name","Fixture");await git("config","user.email","fixture@example.test");await Bun.write(join(directory,"source.bin"),new Uint8Array(150000).fill(65));const folder="x".repeat(230);await mkdir(join(directory,folder));for(let index=0;index<511;index++)await Bun.write(join(directory,folder,`${index}.ts`),"x");await git("add",".");await git("commit","-m","Actual bounded source");const commit=new TextDecoder().decode(await git("rev-parse","HEAD")).trim(),tree=new TextDecoder().decode(await git("rev-parse","HEAD^{tree}")).trim(),identity:PreviewSourceIdentity={scope:{attemptId:crypto.randomUUID(),projectId:"p123456789abc",incarnation:crypto.randomUUID(),commit,tree,policyDigest:"c".repeat(64)},providerRepoId:"local-git-provider",canonicalRepoName:"canonical"},source=await captureTrustedGitSource({scope:identity.scope,provider:{providerRepoId:identity.providerRepoId,canonicalRepoName:identity.canonicalRepoName},authorize:async()=>{},reader:{readObject:async(kind,hash,maxBytes,signal)=>{signal.throwIfAborted();const result=Bun.spawnSync(["git","cat-file",kind,hash],{cwd:directory,stdout:"pipe",stderr:"pipe"});if(result.exitCode!==0)throw Error("Native fixture raw object read failed");const bytes=new Uint8Array(result.stdout);if(bytes.byteLength>maxBytes)throw Error("Native fixture read exceeds bound");return bytes;}}});return{directory,identity,source};}
async function newAttempt(identity:PreviewSourceIdentity,source:TrustedGitSource){const expected={...identity,scope:{...identity.scope,attemptId:crypto.randomUUID()}},manifest=await bindBuildManifest("source",expected.scope,source.files);return{identity:expected,source:{...source,sourceManifest:manifest,proof:{...source.proof,sourceDigest:manifest.digest}}};}
test("native Git source persists512 files through bounded chunks and recovers lost ACK without new writes",async()=>{const data=await fixture(),kv=new SqliteKV(),cache=new PreviewSourceStorage(kv.port());try{kv.loseCompletionAck=true;await expect(cache.write(data.identity,data.source)).rejects.toThrow("lost commit");const read={...data.identity,sourceDigest:data.source.sourceManifest.digest},recovered=await cache.read(read);expect(recovered?.sourceManifest).toEqual(data.source.sourceManifest);expect(recovered?.proof).toEqual(data.source.proof);expect(recovered?.files.find(file=>file.path==="source.bin")?.bytes).toEqual(new Uint8Array(150000).fill(65));expect(kv.keys().filter(key=>key.includes(":metadata:"))).toHaveLength(6);const charged=await kv.get<number>("preview-source-cache-bytes"),writes=kv.chunkWrites;await cache.write(data.identity,data.source);expect(kv.chunkWrites).toBe(writes);expect(await kv.get<number>("preview-source-cache-bytes")).toBe(charged);expect(await cache.read({...read,scope:{...read.scope,tree:"f".repeat(40)}})).toBeNull();expect(await cache.read({...read,providerRepoId:"foreign"})).toBeNull();const bad=structuredClone(data.source);bad.proof.blobs[0]!.hash="f".repeat(40);await expect(cache.write(data.identity,bad)).rejects.toThrow("blob bytes");const key=kv.keys().find(key=>key.includes(":file:")&&key.endsWith(":0"))!;const previous=await kv.get<Uint8Array>(key);await kv.put(key,new Uint8Array(previous!.byteLength).fill(66));await expect(cache.read(read)).rejects.toThrow();}finally{kv.db.close();await rm(data.directory,{recursive:true,force:true});}},30000);
test("uncertain source writes retain reservations and known-full capacity denies before chunk writes",async()=>{const data=await fixture(),kv=new SqliteKV(),cache=new PreviewSourceStorage(kv.port());try{kv.failWrite=true;await expect(cache.write(data.identity,data.source)).rejects.toThrow("uncertain source write");const read={...data.identity,sourceDigest:data.source.sourceManifest.digest},charged=await kv.get<number>("preview-source-cache-bytes");expect(charged).toBeGreaterThan(150000);expect(await cache.read(read)).toBeNull();await expect(cache.retireCompleted(read)).rejects.toThrow();expect(await kv.get<number>("preview-source-cache-bytes")).toBe(charged);kv.failWrite=false;await cache.write(data.identity,data.source);expect(await kv.get<number>("preview-source-cache-bytes")).toBe(charged);const another=await newAttempt(data.identity,data.source);await kv.put("preview-source-cache-bytes",PREVIEW_SOURCE_CACHE_BYTES);const writes=kv.chunkWrites;await expect(cache.write(another.identity,another.source)).rejects.toThrow("capacity reached");expect(kv.chunkWrites).toBe(writes);}finally{kv.db.close();await rm(data.directory,{recursive:true,force:true});}},30000);
test("only completed sources retire with atomic positive file deletion; proof and reservation receipts survive",async()=>{const data=await fixture(),kv=new SqliteKV(),cache=new PreviewSourceStorage(kv.port());try{await cache.write(data.identity,data.source);const read={...data.identity,sourceDigest:data.source.sourceManifest.digest},before=await kv.get<number>("preview-source-cache-bytes");kv.failDelete=true;await expect(cache.retireCompleted(read)).rejects.toThrow("unknown chunk deletion");expect(await kv.get<number>("preview-source-cache-bytes")).toBe(before);expect(await cache.read(read)).not.toBeNull();kv.failDelete=false;const retired=await cache.retireCompleted(read),remaining=await kv.get<number>("preview-source-cache-bytes");expect(retired.bytesFreed).toBeGreaterThan(150000);expect(remaining).toBe(before!-retired.bytesFreed);expect(remaining).toBeGreaterThan(0);expect(await cache.read(read)).toBeNull();expect(kv.keys().some(key=>key.includes(":file:"))).toBe(false);expect(kv.keys().some(key=>key.includes(":metadata:"))).toBe(true);expect(kv.keys().some(key=>key.endsWith(":reservation"))).toBe(true);expect(await cache.retireCompleted(read)).toEqual(retired);expect(await kv.get<number>("preview-source-cache-bytes")).toBe(remaining);await expect(cache.write(data.identity,data.source)).rejects.toThrow("retired");}finally{kv.db.close();await rm(data.directory,{recursive:true,force:true});}},30000);
