import {expect,test} from "bun:test";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {workerdChild} from "./support/workerd-child";
interface Snapshot {evidenceReservations:Array<{physical_key:string;bytes:number}>;reservations:Array<{physical_key:string;bytes:number}>;writers:Array<{closed:number;pending:string}>;retirements:Array<{physical_key:string}>;receipts:Array<{physical_key:string;keys_json:string}>}
test("native preview cleanup retains unknown writes and requires actual R2 absence before releasing storage",async()=>{
 if(await workerdChild("tests/preview-storage-cleanup-native.test.ts"))return;
 const file=`/tmp/preview-cleanup-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,"build","tests/support/preview-storage-cleanup-native-worker.ts","--target=browser","--external=cloudflare:workers","--external=node:*",`--outfile=${file}`],{stdout:"ignore",stderr:"pipe"});const [error,code]=await Promise.all([new Response(build.stderr).text(),build.exited]);if(code)throw new Error(error);const script=await Bun.file(file).text();await Bun.file(file).delete();
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"cleanup",modules:true,script,compatibilityDate:"2026-10-02",compatibilityFlags:["nodejs_compat"],bindings:{PREVIEW_STORAGE_GLOBAL_BYTES:"1000",PREVIEW_STORAGE_ACCOUNT_BYTES:"1000",EVIDENCE_STORAGE_GLOBAL_BYTES:"1000",EVIDENCE_STORAGE_ACCOUNT_BYTES:"1000"},r2Buckets:["EVIDENCE_BUCKET"],durableObjects:{REPOSITORY_CONTROLLER:{className:"CleanupNativeFixture",useSQLite:true}}}]}));
 const call=async(path:string)=>(await mf.getWorker("cleanup")).fetch(`http://fixture${path}`),snapshot=async()=>await(await call("/snapshot")).json() as Snapshot;
 try{
 const legacy=await(await call("/legacy-evidence")).json() as {cleanup:{projectId:string;legacyEvidence:boolean;legacyInventory:boolean};flatPresent:boolean;flatBody:string;scopedPresent:boolean};expect(legacy.cleanup.projectId).toBe("p987654321abc");expect(legacy.cleanup.legacyEvidence).toBe(true);expect(legacy.cleanup.legacyInventory).toBe(true);expect(legacy.flatPresent).toBe(true);expect(legacy.flatBody).toBe("legacy evidence");expect(legacy.scopedPresent).toBe(true);
 expect(await(await call("/start")).json()).toEqual({allowed:true});expect(await(await call("/writer-state")).json()).toEqual({unfinished:true});const retained=await snapshot();expect(retained.reservations).toHaveLength(1);expect(retained.writers[0]?.pending).toContain("index.html");expect(await(await call("/object")).json()).toBe(true);expect(await(await call("/ready")).json()).toBe(false);expect((await call("/finish")).status).toBe(409);expect(await snapshot()).toEqual(retained);
 expect((await call("/settle")).status).toBe(200);expect(await(await call("/writer-state")).json()).toEqual({unfinished:false});expect(await(await call("/ready")).json()).toBe(true);const unconfirmed=await call("/finish");expect(unconfirmed.status).toBe(409);expect(await unconfirmed.text()).toContain("absence is unconfirmed");expect((await snapshot()).reservations).toEqual(retained.reservations);
 expect((await call("/delete")).status).toBe(200);expect(await(await call("/object")).json()).toBe(false);expect((await call("/finish")).status).toBe(200);const retired=await snapshot();expect(retired.reservations).toHaveLength(0);expect(retired.retirements).toHaveLength(1);expect(retired.receipts).toHaveLength(1);expect(JSON.parse(retired.receipts[0]!.keys_json)).toEqual([`${retired.retirements[0]!.physical_key}/assets/foo..js`,`${retired.retirements[0]!.physical_key}/index.html`]);expect((await call("/finish")).status).toBe(200);expect(await snapshot()).toEqual(retired);
 expect((await call("/retry-writer")).status).toBe(409);expect(await(await call("/retry-reserve")).json()).toEqual({allowed:false,reason:"storage_retired"});expect((await snapshot()).reservations).toHaveLength(0);
 const fresh=await(await call("/fresh-era")).json() as {legacyInventory:boolean};expect(fresh.legacyInventory).toBe(false);
 expect(await(await call("/hold-preview")).json()).toEqual({allowed:true});
 expect(await(await call("/evidence-start")).json()).toEqual({allowed:true});const evidenceHeld=await snapshot();expect(evidenceHeld.evidenceReservations).toHaveLength(1);expect(await(await call("/evidence-ready")).json()).toBe(false);expect((await call("/evidence-finish")).status).toBe(409);expect((await snapshot()).evidenceReservations).toEqual(evidenceHeld.evidenceReservations);
 expect((await call("/evidence-settle")).status).toBe(200);expect(await(await call("/evidence-ready")).json()).toBe(true);expect((await call("/evidence-finish")).status).toBe(409);expect((await snapshot()).evidenceReservations).toEqual(evidenceHeld.evidenceReservations);expect((await call("/evidence-delete")).status).toBe(200);expect((await call("/evidence-finish")).status).toBe(200);const evidenceRetired=await snapshot();expect(evidenceRetired.evidenceReservations).toHaveLength(0);expect(evidenceRetired.reservations).toEqual(evidenceHeld.reservations);expect(evidenceRetired.reservations).toHaveLength(1);expect(evidenceRetired.receipts).toHaveLength(2);expect(evidenceRetired.retirements).toHaveLength(2);
 }finally{await mf.dispose();}
},30000);
