import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {PreviewCredentialIncidents} from "../src/server/preview-credential-incidents";
const repo="flaregit-p123456789abc",now=1000;
function fixture(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}};return{db,ledger:new PreviewCredentialIncidents(storage as unknown as DurableObjectStorage)};}
test("summary cannot expose token; immutable replay survives verified secret removal",async()=>{const{ledger,db}=fixture(),g=crypto.randomUUID();await ledger.record(g,repo,"private-token",2000,now);expect(ledger.summary(g)).toEqual({status:"pending",expiresAt:2000});expect(ledger.pendingBatch(now)[0]?.token).toBe("private-token");await expect(ledger.record(g,repo,"changed",2000,now)).rejects.toThrow("input changed");await expect(ledger.markRevoked(g,"wrong")).rejects.toThrow("mismatch");await ledger.markRevoked(g,"private-token");expect(db.query("SELECT token FROM preview_credential_incidents").get()).toEqual({token:null});await ledger.record(g,repo,"private-token",2000,now);expect(ledger.summary(g)?.status).toBe("revoked");expect(ledger.pendingBatch(now)).toHaveLength(0);});
test("attempt budget suppresses retries and expiry clears secret without claiming revocation",async()=>{const{ledger,db}=fixture(),g=crypto.randomUUID();await ledger.record(g,repo,"secret",2000,now);for(let i=0;i<4;i++)expect(ledger.markAttempt(g)).toBe(true);expect(ledger.markAttempt(g)).toBe(false);expect(ledger.pendingBatch(now)).toHaveLength(0);expect(ledger.summary(g)?.status).toBe("pending");ledger.pendingBatch(2000);expect(ledger.summary(g)).toEqual({status:"expired_unverified",expiresAt:2000});expect(db.query("SELECT token FROM preview_credential_incidents").get()).toEqual({token:null});await expect(ledger.markRevoked(g,"secret")).rejects.toThrow("unverified");});
test("bounded batches and retention ceiling enforce independent limits",async()=>{const{ledger,db}=fixture();for(let i=0;i<1000;i++)await ledger.record(crypto.randomUUID(),repo,"token",2000,now);expect(ledger.pendingBatch(now)).toHaveLength(20);await expect(ledger.record(crypto.randomUUID(),repo,"token",2000,now)).rejects.toThrow("limit");expect(db.query("SELECT COUNT(*) AS n FROM preview_credential_incidents").get()).toEqual({n:1000});});
test("invalid credential scope and lifetime reject before storage",async()=>{const{ledger}=fixture();await expect(ledger.record(crypto.randomUUID(),"other-project","token",2000,now)).rejects.toThrow("Invalid");await expect(ledger.record(crypto.randomUUID(),repo,"token",901001,now)).rejects.toThrow("Invalid");await expect(ledger.record(crypto.randomUUID(),repo,"x".repeat(16385),2000,now)).rejects.toThrow("Invalid");});

test("fresh synchronous authority validation rejects after fingerprint before secret insertion",async()=>{const{ledger,db}=fixture();let calls=0;await expect(ledger.record(crypto.randomUUID(),repo,"private-token",2000,now,()=>{calls++;throw new Error("Generation context changed");})).rejects.toThrow("context changed");expect(calls).toBe(1);expect(db.query("SELECT COUNT(*) AS n FROM preview_credential_incidents").get()).toEqual({n:0});});
