import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import type {Env} from '../src/server/env';
import {buildPreviewGeneration} from '../src/server/preview-generation-build';
import {RepositoryPreviewGenerations} from '../src/server/preview-generations';
import {PreviewCredentialIncidents} from '../src/server/preview-credential-incidents';
import {PreviewStorageLedger,previewManifestPrefix} from '../src/server/preview-storage';
import {PreviewStorageWriters} from '../src/server/preview-storage-writers';
import {createPreviewStorageManifest,type PreviewStorageManifest} from '../src/server/preview-storage-upload';
import {ManagedSpendLedger} from '../src/server/managed-spend-ledger';
import {captureTrustedGitSource} from '../src/server/trusted-git-source';
import {bindBuildManifest} from '../src/server/static-build-artifact';
import type {PreviewExecutionContext} from '../src/server/preview-execution-authority';
import type {IsolatedPreviewBuildLedger} from '../src/server/isolated-preview-build';
// Actual raw Git objects and SQLite ledgers; SDK/runtime/R2 ports are explicit
// local doubles. This verifies orchestration, never hosted isolation or billing.
async function fixture(options:{nullClaim?:boolean;throwVm?:boolean;throwScope?:boolean;throwInfo?:boolean;revokeFails?:boolean;revokeDuringInfo?:boolean;sourceMismatch?:boolean;withdrawDuringBuild?:boolean;stopUnknown?:boolean}={}){
 const root=await mkdtemp(join(tmpdir(),'preview-generation-source-'));
 const git=(...args:string[])=>{const result=Bun.spawnSync(['git','-C',root,...args]);if(result.exitCode)throw Error('Fixture Git failed');return result.stdout;};
 git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');await Bun.write(join(root,'index.html'),'<main>actual Git source</main>');git('add','.');git('commit','-qm','Source');
 const identity={projectId:'p123456789abc',incarnation:crypto.randomUUID(),commit:git('rev-parse','HEAD').toString().trim(),accountKey:'b'.repeat(12)},canonicalRepoName=`flaregit-${identity.projectId}`;
 const db=new Database(':memory:'),storage={sql:{exec(query:string,...bindings:Array<string|number|null>){if(query.includes(';')){db.exec(query);return{toArray:()=>[],one:()=>({})};}const rows=db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}} as unknown as DurableObjectStorage;
 const ledger=new RepositoryPreviewGenerations(storage),incidents=new PreviewCredentialIncidents(storage),bytesLedger=new PreviewStorageLedger(storage),writers=new PreviewStorageWriters(storage),managed=new ManagedSpendLedger(storage),record=ledger.begin(identity,'owner',null,crypto.randomUUID()).record;
 const scope={attemptId:crypto.randomUUID(),projectId:identity.projectId,incarnation:identity.incarnation,commit:identity.commit,tree:git('rev-parse','HEAD^{tree}').toString().trim(),policyDigest:'a'.repeat(64)},context:PreviewExecutionContext={snapshot:{kind:'preview-execution',...identity,tree:scope.tree,policyDigest:scope.policyDigest,actorId:'owner',canonicalRepoName,providerRepoId:'local-git-provider',target:{kind:'accepted',receiptId:crypto.randomUUID(),ref:'refs/heads/trunk',version:1},generation:record.generation,image:`registry.cloudflare.com/${'c'.repeat(32)}/untrusted@sha256:${'d'.repeat(64)}`},scope,sourceDigest:null};
 const source=await captureTrustedGitSource({scope,provider:{providerRepoId:'local-git-provider',canonicalRepoName},reader:{readObject:async(kind,hash)=>git('cat-file',kind,hash)},authorize:async()=>{}});
 const budget={globalBytes:1000000,accountBytes:1000000},original=await createPreviewStorageManifest(identity,source.sourceManifest.files.map(file=>({path:file.path,size:file.size,sha256:file.digest}))),estimate=await createPreviewStorageManifest({...identity,generation:record.generation},[{path:'index.html',size:128,sha256:source.sourceManifest.files[0]!.digest}]);bytesLedger.reserve(original,budget);bytesLedger.estimate(estimate,budget);
 const before=db.query('SELECT physical_key,bytes,manifest_hash FROM preview_storage_reservations ORDER BY physical_key').all();
 let revoked=false,isolatedGets=0,runs=0,seals=0,stops=0,tokenCreates=0,credentialRecords=0,credentialedVmGets=0,puts=0,invocationOwner:string|null=null,jobAllocated=false,stopConfirmed=false;
 const activities:string[]=[],jobs:string[]=[];const objects=new Map<string,{bytes:Uint8Array;customMetadata:Record<string,string>}>();objects.set(`${previewManifestPrefix(identity)}/index.html`,{bytes:source.files[0]!.bytes.slice(),customMetadata:{sha256:original.assets[0]!.sha256,manifestHash:original.manifestHash}});
 const active=()=>{if(options.throwScope||revoked)throw Error('Owner access changed');};
 const runId=`fixture-preview-${scope.attemptId}`;
 const isolated:IsolatedPreviewBuildLedger={claimPreviewExecutionInvocation:async(expected,id)=>{active();if(invocationOwner)return{status:'busy'};invocationOwner=id;return{status:'owned',context:expected,invocationId:id};},finishPreviewExecutionInvocation:async(expected,id)=>{if(invocationOwner!==id||expected.scope.attemptId!==scope.attemptId||Boolean(incidents.summary(record.generation)&&incidents.summary(record.generation)?.status!=='revoked')||jobAllocated&&!stopConfirmed)throw Error('Original execution cleanup unconfirmed');invocationOwner=null;},previewExecutionDispatchState:async()=> 'not_dispatched',preparePreviewExecution:async()=>{active();return structuredClone(context);},previewExecutionSnapshot:async expected=>{active();return structuredClone(expected);},capturePreviewExecutionSource:async()=>{active();if(options.throwInfo)throw Error('Artifact metadata unavailable');if(options.revokeDuringInfo){revoked=true;active();}tokenCreates++;credentialRecords++;const token='server-private-token';await incidents.record(record.generation,canonicalRepoName,token,Date.now()+60000);if(options.revokeFails){activities.push('preview.credential_cleanup_pending:Original source read credential remains pending');throw Error('Source credential cleanup unconfirmed');}await incidents.markRevoked(record.generation,token);const captured=structuredClone(source);if(options.sourceMismatch)captured.proof.commit='e'.repeat(40);return captured;},bindPreviewExecutionSource:async pending=>({...pending,sourceDigest:source.sourceManifest.digest}),assertPreviewExecutionSource:async()=>{active();},preparePreviewExecutionGrant:async()=>{active();if(options.nullClaim)throw Error('Native startup unconfirmed');const funded=managed.reserve({resourceKind:'native-optional',runId,accountKey:identity.accountKey,usdMicros:43008,maxInputBytes:1,maxOutputTokens:1,maxCalls:1,maxContainerSeconds:1200},{globalUsdMicros:1000000,accountUsdMicros:1000000,essentialGlobalUsdMicros:43008,essentialAccountUsdMicros:43008});if(!funded.allowed)throw Error('Fixture reservation denied');},authorizePreviewExecution:async()=>{active();return true;},claimPreviewExecutionDispatch:async expected=>{active();managed.consume(runId,0,0,1200);return{context:expected,phase:'dispatched'};},sealPreviewExecution:async()=>{seals++;}};
 const repository={...isolated,previewGenerationClaim:async(g:string)=>ledger.markBuilding(g),previewGenerationScope:async()=>{active();return{...identity,generation:record.generation};},previewGenerationFail:async(g:string,reason:string)=>{ledger.fail(g,reason);},previewGenerationPromote:async(g:string,hash:string)=>ledger.promote(g,identity,hash),getState:async()=>({canonicalRepoName}),logActivity:async(_actor:string,type:string,message:string)=>{activities.push(type+':'+message);}};
 const global={finalizePreviewGenerationManifest:async(manifest:PreviewStorageManifest)=>{bytesLedger.finalize(manifest,budget);return{allowed:true};},reservePreviewWriter:async(key:string,id:string)=>{writers.registerPreview(key);writers.begin(key,id);},beginPreviewPut:async(key:string,id:string,path:string)=>writers.dispatch(key,id,`${key}/${path}`),finishPreviewPut:async(key:string,id:string,path:string)=>writers.settled(key,id,`${key}/${path}`),finishPreviewWriter:async(key:string,id:string)=>writers.finish(key,id)};
 const env={REPOSITORY_CONTROLLER:{idFromName:(name:string)=>name,get:(name:string)=>name==='global'?global:repository},INTEGRATOR:{getByName:()=>{credentialedVmGets++;throw Error('Contributor code cannot run in credentialed Integrator');}},UNTRUSTED_EXECUTION:{getByName:(name:string)=>{isolatedGets++;jobs.push(name);if(options.throwVm)throw Error('Isolated VM unavailable');jobAllocated=true;return{prepare:async()=>{},run:async()=>{runs++;if(options.withdrawDuringBuild)revoked=true;const files=[{path:'index.html',kind:'file' as const,bytes:new TextEncoder().encode('<main>isolated replacement</main>')}];return{manifest:await bindBuildManifest('static',scope,files,source.sourceManifest.digest),files,acceptanceEvidence:false as const};},stop:async()=>{stops++;stopConfirmed=!options.stopUnknown;return{stopped:stopConfirmed};}};}},EVIDENCE_BUCKET:{head:async(key:string)=>{const object=objects.get(key);return object?{size:object.bytes.length,customMetadata:object.customMetadata}:null;},put:async(key:string,bytes:Uint8Array,options:{customMetadata:Record<string,string>;onlyIf:{etagDoesNotMatch:string}})=>{expect(options.onlyIf.etagDoesNotMatch).toBe('*');puts++;objects.set(key,{bytes:bytes.slice(),customMetadata:{...options.customMetadata}});return{etag:'fixture-positive-put'};}}} as unknown as Env;
 return{env,identity,record,ledger,incidents,activities,objects,jobs,managed,runId,original,before,reservations:()=>db.query('SELECT physical_key,bytes,manifest_hash FROM preview_storage_reservations ORDER BY physical_key').all(),invocationHeld:()=>invocationOwner!==null,counts:()=>({isolatedGets,runs,seals,stops,tokenCreates,credentialRecords,credentialedVmGets,puts}),close:async()=>{db.close();await rm(root,{recursive:true,force:true});}};
}
test('unconfirmed native admission preserves reservations and never allocates an isolated or credentialed VM',async()=>{const f=await fixture({nullClaim:true});try{await buildPreviewGeneration(f.env,f.identity.projectId,f.record.generation);expect(f.ledger.get(f.record.generation)?.failureReason).toBe('publication_unavailable');expect(f.counts().isolatedGets).toBe(0);expect(f.counts().credentialedVmGets).toBe(0);expect(f.reservations()).toEqual(f.before);}finally{await f.close();}});
test('scope isolated VM and source metadata failures settle generation without rejected promises or releasing reservations',async()=>{for(const option of [{throwScope:true},{throwVm:true},{throwInfo:true}]){const f=await fixture(option);try{await expect(buildPreviewGeneration(f.env,f.identity.projectId,f.record.generation)).resolves.toBeUndefined();expect(f.ledger.get(f.record.generation)?.state).toBe('failed');expect(f.counts().runs).toBe(0);expect(f.counts().credentialedVmGets).toBe(0);expect(f.reservations()).toEqual(f.before);if(!option.throwVm)expect(f.counts().tokenCreates).toBe(0);}finally{await f.close();}}});
test('owner withdrawal during metadata await prevents source credential creation',async()=>{const f=await fixture({revokeDuringInfo:true});try{await buildPreviewGeneration(f.env,f.identity.projectId,f.record.generation);expect(f.counts().tokenCreates).toBe(0);expect(f.ledger.get(f.record.generation)?.failureReason).toBe('publication_unavailable');expect(f.reservations()).toEqual(f.before);}finally{await f.close();}});
test('mismatched actual Git provenance prevents build and unknown read-key cleanup remains private',async()=>{for(const option of [{sourceMismatch:true},{revokeFails:true}]){const f=await fixture(option);try{await buildPreviewGeneration(f.env,f.identity.projectId,f.record.generation);expect(f.counts()).toMatchObject({isolatedGets:0,runs:0,tokenCreates:1,credentialRecords:1,credentialedVmGets:0,puts:0});expect(f.ledger.get(f.record.generation)?.state).toBe('failed');expect(f.reservations()).toEqual(f.before);if(option.revokeFails){expect(f.incidents.summary(f.record.generation)?.status).toBe('pending');expect(f.invocationHeld()).toBe(true);expect(JSON.stringify(f.incidents.summary(f.record.generation))).not.toContain('server-private-token');expect(f.activities.join(' ')).not.toContain('server-private-token');expect(f.activities.some(activity=>activity.startsWith('preview.credential_cleanup_pending:'))).toBe(true);}}finally{await f.close();}}});
test('generation publishes only digest-bound isolated bytes after cleanup and keeps the original physical copy',async()=>{const f=await fixture();try{await buildPreviewGeneration(f.env,f.identity.projectId,f.record.generation);const active=f.ledger.active(f.identity.commit);if(!active?.manifestHash)throw Error('Published generation manifest receipt missing');expect(active.state).toBe('ready');expect(active?.manifestHash).toMatch(/^[a-f0-9]{64}$/);expect(f.counts()).toMatchObject({isolatedGets:1,runs:1,seals:1,stops:1,credentialedVmGets:0,puts:1});const next=`build-generations/${f.identity.projectId}/${f.identity.incarnation}/${f.identity.commit}/${f.record.generation}/index.html`,saved=f.objects.get(next);expect(new TextDecoder().decode(saved?.bytes)).toBe('<main>isolated replacement</main>');expect(saved?.customMetadata.manifestHash).toBe(active.manifestHash);expect(f.objects.get(`${previewManifestPrefix(f.identity)}/index.html`)?.customMetadata.manifestHash).toBe(f.original.manifestHash);expect(f.managed.get(f.runId)?.containerSeconds).toBe(1200);expect(f.managed.get(f.runId)?.state).toBe('reserved');expect(f.invocationHeld()).toBe(false);}finally{await f.close();}});
test('owner withdrawal while building or unknown VM stop prevents all uploads and retains paid admission',async()=>{for(const option of [{withdrawDuringBuild:true},{stopUnknown:true}]){const f=await fixture(option);try{await buildPreviewGeneration(f.env,f.identity.projectId,f.record.generation);expect(f.ledger.get(f.record.generation)?.state).toBe('failed');expect(f.ledger.active(f.identity.commit)).toBeNull();expect(f.counts()).toMatchObject({runs:1,seals:1,stops:1,puts:0,credentialedVmGets:0});expect(f.reservations()).toEqual(f.before);expect(f.managed.get(f.runId)).toMatchObject({containerSeconds:1200,state:'reserved'});expect(f.invocationHeld()).toBe(Boolean(option.stopUnknown));}finally{await f.close();}}});
