import {EvidenceStorageLedger} from "../src/server/evidence-storage";
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {PreviewStorageWriters} from "../src/server/preview-storage-writers";
import {PreviewStorageLedger} from "../src/server/preview-storage";
import {createPreviewStorageManifest} from "../src/server/preview-storage-upload";
const identity={projectId:"p123456789abc",incarnation:"11111111-1111-4111-8111-111111111111",commit:"a".repeat(40),accountKey:"b".repeat(12)},key=`builds/${identity.projectId}/${identity.commit}`;
function fixture(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){if(query.includes(";")&&!bindings.length){db.exec(query);return{toArray:()=>[],one:()=>undefined};}const rows=db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}} as unknown as DurableObjectStorage;return{db,storage,writers:new PreviewStorageWriters(storage)};}
async function prepared(){const f=fixture(),manifest=await createPreviewStorageManifest(identity,[{path:"index.html",size:3,sha256:"c".repeat(64)}]);new PreviewStorageLedger(f.storage).reserve(manifest,{globalBytes:3,accountBytes:3});f.writers.registerPreview(key);return f;}
test("unknown PUT intent remains held across restart and deletion fence",async()=>{const f=await prepared(),id=crypto.randomUUID();f.writers.begin(key,id);f.writers.dispatch(key,id,`${key}/index.html`);const resumed=new PreviewStorageWriters(f.storage);resumed.fence(identity.projectId,identity.incarnation);expect(resumed.cleanupReady(key)).toBe(false);expect(()=>resumed.finish(key,id)).toThrow("unresolved");expect(()=>resumed.retire(key)).toThrow("unconfirmed");expect(()=>resumed.dispatch(key,id,`${key}/index.html`)).toThrow("fenced");expect(f.db.query("SELECT SUM(bytes) AS n FROM preview_storage_reservations").get()).toEqual({n:3});});
test("only acknowledged matching PUT can close a writer, and retirement never reopens",async()=>{const f=await prepared(),id=crypto.randomUUID();f.writers.begin(key,id);expect(()=>f.writers.dispatch(key,id,"evidence/another.json")).toThrow("outside");f.writers.dispatch(key,id,`${key}/index.html`);expect(()=>f.writers.settled(key,id,"other")).toThrow("mismatch");f.writers.settled(key,id,`${key}/index.html`);f.writers.finish(key,id);expect(f.writers.cleanupReady(key)).toBe(false);f.writers.fence(identity.projectId,identity.incarnation);expect(f.writers.cleanupReady(key)).toBe(true);f.writers.retire(key);expect(()=>f.writers.begin(key,crypto.randomUUID())).toThrow("fenced");});
test("evidence plans are strictly scoped and digest immutable",()=>{const f=fixture();new EvidenceStorageLedger(f.storage).reserve(identity,"ev_12345678-abc",9,"c".repeat(64),{globalBytes:9,accountBytes:9});const evidence=f.writers.registerEvidence(identity,"ev_12345678-abc",9,"c".repeat(64));expect(evidence).toBe(`evidence/${identity.projectId}/${identity.incarnation}/ev_12345678-abc.json`);expect(()=>f.writers.registerEvidence(identity,"../legacy",9,"c".repeat(64))).toThrow();expect(()=>f.writers.registerEvidence(identity,"ev_12345678-abc",9,"d".repeat(64))).toThrow("immutable");expect(f.writers.fence(identity.projectId,identity.incarnation)[0]?.keys).toEqual([evidence]);});
