import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import type {Env} from "../src/server/env";
import {buildPreviewGeneration} from "../src/server/preview-generation-build";
import {RepositoryPreviewGenerations} from "../src/server/preview-generations";
import {PreviewCredentialIncidents} from "../src/server/preview-credential-incidents";
const identity={projectId:"p123456789abc",incarnation:"11111111-1111-4111-8111-111111111111",commit:"a".repeat(40),accountKey:"b".repeat(12)};
// These explicit RPC/provider doubles verify local control flow, not hosted provider behavior.
function fixture(options:{nullClaim?:boolean;throwVm?:boolean;throwScope?:boolean;throwInfo?:boolean;revokeFails?:boolean;revokeDuringInfo?:boolean}={}){
 const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){if(query.includes(";")){db.exec(query);return{toArray:()=>[],one:()=>({})};}const rows=db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}} as unknown as DurableObjectStorage;
 const ledger=new RepositoryPreviewGenerations(storage),incidents=new PreviewCredentialIncidents(storage),record=ledger.begin(identity,"owner",null,crypto.randomUUID()).record;
 let revoked=false,vmGets=0,tokenCreates=0,execs=0,credentialRecords=0;const commands:string[]=[],activities:string[]=[];
 const repository={previewGenerationClaim:async(g:string)=>ledger.markBuilding(g),previewGenerationScope:async()=>{if(options.throwScope||revoked)throw new Error("Owner access changed");return{...identity,generation:record.generation};},previewGenerationFail:async(g:string,reason:string)=>{ledger.fail(g,reason);},getState:async()=>({canonicalRepoName:`flaregit-${identity.projectId}`}),logActivity:async(_actor:string,type:string,message:string)=>{activities.push(type+":"+message);},previewGenerationCredentialIncident:async(g:string,name:string,token:string,expiresAt:number)=>{credentialRecords++;await incidents.record(g,name,token,expiresAt);}};
 const global={claimNativeCompute:async()=>options.nullClaim?null:"lease",nativeComputeStatus:async()=>null,reserveManagedSpend:async()=>({allowed:true}),consumeManagedSpend:async()=>{},finishNativeCompute:async()=>{}};
 const repo={info:async()=>{if(options.throwInfo)throw new Error("Artifact unavailable");if(options.revokeDuringInfo)revoked=true;return{remote:`https://${"c".repeat(32)}.artifacts.cloudflare.net/repo`};},createToken:async()=>{tokenCreates++;return{plaintext:"server-private-token"};},revokeToken:async()=>!options.revokeFails};
 const workspace={exec:async(argv:string[])=>{execs++;commands.push(argv.join(" "));return{success:true,stdout:"d".repeat(40),stderr:""};},destroy:async()=>{},lifetimeStatus:async()=>({state:"stopped"})};
 const env={REPOSITORY_CONTROLLER:{idFromName:(name:string)=>name,get:(name:string)=>name==="global"?global:name.startsWith("account:")?{accountLifecycle:async()=>"active"}:repository},INTEGRATOR:{getByName:()=>{vmGets++;if(options.throwVm)throw new Error("VM allocation unavailable");return workspace;}},ARTIFACTS:{get:async()=>repo}} as unknown as Env;
 return{env,record,ledger,incidents,commands,activities,counts:()=>({vmGets,tokenCreates,execs,credentialRecords})};
}
test("null native claim saves unconfirmed startup without allocating a VM",async()=>{const f=fixture({nullClaim:true});await buildPreviewGeneration(f.env,identity.projectId,f.record.generation);expect(f.ledger.get(f.record.generation)?.failureReason).toBe("compute_start_unconfirmed");expect(f.counts().vmGets).toBe(0);});
test("scope VM and artifact info failures settle generation without rejected promise",async()=>{for(const option of [{throwScope:true},{throwVm:true},{throwInfo:true}]){const f=fixture(option);await expect(buildPreviewGeneration(f.env,identity.projectId,f.record.generation)).resolves.toBeUndefined();expect(f.ledger.get(f.record.generation)?.state).toBe("failed");expect(f.counts().tokenCreates).toBe(0);}});
test("owner revocation during artifact metadata await prevents token creation",async()=>{const f=fixture({revokeDuringInfo:true});await buildPreviewGeneration(f.env,identity.projectId,f.record.generation);expect(f.counts().tokenCreates).toBe(0);expect(f.ledger.get(f.record.generation)?.failureReason).toBe("publication_unavailable");});
test("checkout mismatch prevents build and failed token revocation persists private incident",async()=>{const f=fixture({revokeFails:true});await buildPreviewGeneration(f.env,identity.projectId,f.record.generation);expect(f.counts()).toEqual({vmGets:1,tokenCreates:1,execs:1,credentialRecords:1});expect(f.commands[0]).toContain(`checkout --quiet --detach '${identity.commit}'`);expect(f.commands[0]).toContain("rev-parse HEAD");expect(f.ledger.get(f.record.generation)?.state).toBe("failed");expect(f.incidents.summary(f.record.generation)?.status).toBe("pending");expect(JSON.stringify(f.incidents.summary(f.record.generation))).not.toContain("server-private-token");expect(f.activities.join(" ")).not.toContain("server-private-token");expect(f.activities.some(a=>a.startsWith("preview.credential_cleanup_pending:"))).toBe(true);});
