import {expect,mock,test} from 'bun:test';
import {Database} from 'bun:sqlite';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {gitOrThrow,PLATFORM_IDENTITY} from '../src/core/pipeline/git';
import type {CandidateGeneration,VerificationEvidence} from '../src/core/types';
import type {Ledger} from '../src/server/durable-object';
import type {Env} from '../src/server/env';
import {retainedInputSchema} from '../src/server/retained-inputs';
import {candidateBuildSnapshotSchema} from '../src/server/candidate-build-attempts';
import {isolatedExecutionContextSchema,type IsolatedExecutionContext} from '../src/server/isolated-execution-grants';
import {bindBuildManifest} from '../src/server/static-build-artifact';
import {deriveTrustedBrowserPolicy} from '../src/server/isolated-browser-policy';
import {bindBrowserPolicy} from '../src/server/external-browser-verifier';
import {ticketBookingBrowserInventory} from '../src/server/trusted-fixture-browser-policies';
import {ProtectedModelRepairAttempts,executeProtectedModelRepair,repairDigest,type ProtectedRepairPlan,type RepairPatch,type RepairAttemptIdentity} from '../src/server/protected-model-repair';
import type {TrustedGitSource} from '../src/server/trusted-git-source';
import {PROTECTED_CONFLICT_INSPECTOR,validateProtectedConflictSnapshot,type ProtectedConflictContext} from '../src/server/protected-conflict-source';
import {nativeFunding} from './support/native-funding';
mock.module('cloudflare:workers',()=>({WorkflowEntrypoint:class{constructor(_ctx:unknown,public env:Env){}},DurableObject:class{}}));
const {FlareGitIntegrationWorkflow}=await import('../src/server/workflow');
const {RepositoryController}=await import('../src/server/durable-object');
// Real Workflow control flow, native Git and durable model ledger. External model,
// isolated execution and browser ports are explicitly synthetic; no hosted proof.
for(const scenario of [{landing:'merge',conflict:false},{landing:'squash',conflict:false},{landing:'merge',conflict:true},{landing:'squash',conflict:true},{landing:'merge',conflict:true,sourceRace:true},{landing:'merge',conflict:true,textRetry:true},{landing:'squash',conflict:true,textRetry:true},{landing:'merge',conflict:true,textRetry:true,replayRace:true}] as const)test(`protected ${scenario.landing} ${scenario.conflict?'text conflict':'browser failure'} ${'sourceRace' in scenario?'source race':'textRetry' in scenario?'step retry':''} Workflow recovers one model ACK and independently verifies the new pinned SHA`,async()=>{
 const {landing,conflict}=scenario;
 const root=await mkdtemp(join(tmpdir(),'flaregit-protected-workflow-')),seed=join(root,'seed'),canonical=join(root,'canonical.git'),work=join(root,'work'),remote=`https://${'a'.repeat(32)}.artifacts.cloudflare.net/canonical.git`,db=new Database(':memory:');
 const storage={sql:{exec(query:string,...args:Array<string|number>){const rows=db.query(query).all(...args);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;
 try{
 gitOrThrow(root,['init','--bare','--initial-branch=main',canonical]);gitOrThrow(root,['clone',canonical,seed]);await Bun.write(join(seed,'index.html'),'<h1>Template</h1>');await Bun.write(join(seed,'src/pricing.ts'),'export const price = 40;\n');gitOrThrow(seed,['add','.']);gitOrThrow(seed,[...PLATFORM_IDENTITY,'commit','-m','Accepted base']);gitOrThrow(seed,['push','origin','main']);const base=gitOrThrow(seed,['rev-parse','HEAD']);gitOrThrow(seed,['checkout','-b','task/one']);await Bun.write(join(seed,'src/pricing.ts'),'export const price = 0;\n');gitOrThrow(seed,['-c','user.name=Fixture Contributor','-c','user.email=contributor@localhost','commit','-am','Broken contribution']);const contributor=gitOrThrow(seed,['rev-parse','HEAD']);gitOrThrow(seed,['push','origin','task/one']);
 const second=conflict?(()=>{gitOrThrow(seed,['checkout','main']);gitOrThrow(seed,['checkout','-b','task/two']);return true;})():false;let secondCommit:string|undefined;if(second){await Bun.write(join(seed,'src/pricing.ts'),'export const price = 20;\n');gitOrThrow(seed,['-c','user.name=Fixture Contributor','-c','user.email=contributor@localhost','commit','-am','Other frozen contribution']);secondCommit=gitOrThrow(seed,['rev-parse','HEAD']);gitOrThrow(seed,['push','origin','task/two']);}
 const policy=await bindBrowserPolicy(ticketBookingBrowserInventory({}).policy),incarnation=crypto.randomUUID(),workflowId='registered-parent';
 const frozen={kind:'git-integrity',allowedScope:['src/'],protectedPaths:['tests/'],landing,trustedBrowserFixture:'ticket-booking',trustedBrowserPolicyDigest:policy.digest};
 const candidate:CandidateGeneration={id:'candidate',attemptNumber:1,frozenRequirements:[],repairAttempts:[],status:'composing',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),expectedAcceptedBase:base,participatingTaskIds:['one'],participatingCommits:{one:contributor},frozenPolicyVersion:1,frozenVerificationPolicy:frozen,workflowInstanceId:workflowId,frozenContributorProofs:[{id:'one',commit:contributor,baseCommit:base,ref:'refs/flaregit/tasks/one',allowedScope:['src/']}]};
 const task={id:'one',goal:'Preserve pricing',allowedScope:['src/'],contributor:{name:'Contributor',id:'one'}};
 if(secondCommit){candidate.participatingTaskIds.push('two');candidate.participatingCommits.two=secondCommit;candidate.frozenContributorProofs?.push({id:'two',commit:secondCommit,baseCommit:base,ref:'refs/flaregit/tasks/two',allowedScope:['src/']});}
 db.exec('CREATE TABLE lease(id INTEGER PRIMARY KEY,holder TEXT)');
 const state={journal:[],projectId:'p123456789abc',canonicalRepoName:'canonical',defaultBranch:'main',tasks:{one:task,...(secondCommit?{two:{...task,id:'two'}}:{})},candidates:{candidate},evidence:{} as Record<string,VerificationEvidence>};
 const nativeChecks:string[]=[],browserChecks:string[]=[],buildChecks:string[]=[],pins:Array<{commit:string;revision:boolean}>=[];let modelCalls=0,modelAckLost=false,pinInterrupted=false,replayStarted=false,sourceContext:IsolatedExecutionContext|undefined,source:TrustedGitSource|undefined,plan:ProtectedRepairPlan|undefined,patch:RepairPatch|undefined,identity:RepairAttemptIdentity|undefined;
 const repairs=new ProtectedModelRepairAttempts(storage);
 const execute=async(command:string,env?:Record<string,string>)=>{if('textRetry' in scenario&&!pinInterrupted&&command.includes(' push ')&&command.includes(`refs/flaregit/candidates/${candidate.id}`))return{success:false,stdout:'',stderr:'Synthetic interrupted candidate pin write',exitCode:1};const translated=command.replaceAll('/workspace/integration',work).replaceAll(remote,canonical).replaceAll('/opt/flaregit',process.cwd());const processChild=Bun.spawn(['sh','-c',translated],{stdout:'pipe',stderr:'pipe',env:{...process.env,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',...env}});const stdout=await new Response(processChild.stdout).text(),stderr=await new Response(processChild.stderr).text(),exitCode=await processChild.exited;return{success:exitCode===0,stdout,stderr,exitCode};};
 const map=(path:string)=>path.replace('/workspace/integration',work);
 let conflictContext:ProtectedConflictContext|undefined,conflictReceipt:ReturnType<typeof validateProtectedConflictSnapshot>|undefined;
 const sandbox={exec:execute,inspectProtectedConflict:async(context:ProtectedConflictContext)=>{const child=Bun.spawn([process.execPath,'-e',PROTECTED_CONFLICT_INSPECTOR.replaceAll('/workspace/integration',work),JSON.stringify({acceptedBase:context.acceptedBase,contributorCommits:context.contributorCommits})],{stdout:'pipe',stderr:'pipe'});const stdout=await new Response(child.stdout).text();if(await child.exited!==0)throw Error(await new Response(child.stderr).text());const inspected=validateProtectedConflictSnapshot(context,JSON.parse(stdout));if(replayStarted){if('replayRace' in scenario)inspected.files[0]!.digest='e'.repeat(64);return{commandId:crypto.randomUUID(),snapshot:inspected};}conflictContext=structuredClone(context);conflictReceipt=inspected;return{commandId:crypto.randomUUID(),snapshot:conflictReceipt};},readFile:async(path:string)=>({content:await Bun.file(map(path)).text()}),readFileBytes:async(path:string)=>new Uint8Array(await Bun.file(map(path)).arrayBuffer()),writeFile:async(path:string,content:string)=>Bun.write(map(path),content),readGitObject:async(kind:string,hash:string,max:number)=>{const child=Bun.spawn(['git','-C',work,'--no-replace-objects','cat-file',kind,hash],{stdout:'pipe',stderr:'pipe'});const bytes=new Uint8Array(await new Response(child.stdout).arrayBuffer());if(await child.exited!==0||bytes.length>max)throw Error('Trusted native read failed');return bytes;},destroy:async()=>{}};
 let attemptScope:IsolatedExecutionContext|undefined,nativeId:string|undefined,nativeActive=false,forceHeld=false;const recoveryEvents:string[]=[];
 const getAttempt=()=>{if(!attemptScope)throw Error('Synthetic external attempt missing');return structuredClone(attemptScope);};
 const ledger={
 getState:async()=>structuredClone(state),prepareRetainedInput:async(taskId:string,_workflow:string,_candidate:string,id:string)=>retainedInputSchema.parse({id,version:1,projectId:state.projectId,incarnation,taskId,commit:taskId==='one'?contributor:secondCommit,base,canonicalRepoName:'canonical',workspaceRepoName:'canonical',branch:`task/${taskId}`,protectedRef:`refs/flaregit/inputs/${incarnation}/${taskId}/${taskId==='one'?contributor:secondCommit}`,protectedBaseRef:`refs/flaregit/inputs/${incarnation}/${taskId}/${base}`,workflowId,candidateId:candidate.id,actorId:'fixture-human',ownerId:'fixture-human',accountKey:'aaaaaaaaaaaa'}),recordRetainedInput:async()=>{},recordComposition:async(_id:string,values:CandidateGeneration['repairAttempts'])=>{state.candidates.candidate={...state.candidates.candidate,repairAttempts:structuredClone(values)};},requirementGatePlan:async()=>[],recordRequirementChecks:async()=>null,recordVerification:async(_id:string,commit:string,evidence:VerificationEvidence)=>{nativeChecks.push(commit);state.candidates.candidate.candidateCommit=commit;state.candidates.candidate.evidenceId=evidence.id;state.candidates.candidate.status='verified';state.evidence[evidence.id]=structuredClone(evidence);},recordCandidateProtectedPin:async(_id:string,commit:string,proof:{revision?:true;ref:string})=>{expect(gitOrThrow(canonical,['rev-parse',proof.ref],{gitDir:true})).toBe(commit);pins.push({commit,revision:proof.revision===true});},
 prepareCandidateIsolatedBuild:async(input:IsolatedExecutionContext)=>{attemptScope=isolatedExecutionContextSchema.parse(input);const{scope,sourceDigest:_source,...rest}=attemptScope;const{attemptId:_attempt,...scopeSnapshot}=scope;return{snapshot:candidateBuildSnapshotSchema.parse({...rest,scope:scopeSnapshot}),scope,sourceDigest:null,sourceManifest:null};},isolatedExecutionSnapshot:async(input:IsolatedExecutionContext)=>structuredClone(input),isolatedSourceProvider:async()=>({providerRepoId:'synthetic-canonical',canonicalRepoName:'canonical'}),bindCandidateIsolatedSource:async(_snapshot:unknown,value:TrustedGitSource)=>{attemptScope={...getAttempt(),sourceDigest:value.sourceManifest.digest};return getAttempt();},assertIsolatedSourceProvenance:async(context:IsolatedExecutionContext,proof:TrustedGitSource['proof'])=>{expect(proof.commit).toBe(context.scope.commit);},
 prepareIsolatedExecutionGrant:async(context:IsolatedExecutionContext)=>({context,phase:'paid',createdAt:Date.now(),expiresAt:Date.now()+150000,consumptionAttempted:true}),authorizeIsolatedExecution:async()=>true,claimIsolatedExecutionDispatch:async(context:IsolatedExecutionContext)=>({context,phase:'dispatched',createdAt:Date.now(),expiresAt:Date.now()+150000,consumptionAttempted:true}),sealIsolatedExecution:async()=>{},
 verifyIsolatedCandidateBrowser:async(context:IsolatedExecutionContext,value:TrustedGitSource,output:import('../src/server/static-build-artifact').BuildManifest)=>{browserChecks.push(context.scope.commit);const pricing=new TextDecoder().decode(value.files.find(file=>file.path==='src/pricing.ts')!.bytes);if(pricing.includes('price = 0')){sourceContext=structuredClone(context);source=structuredClone(value);plan={kind:'protected-repair-input',source:{kind:'committed-browser-failure',identity:{...context.scope,candidateId:candidate.id,sourceDigest:context.sourceDigest,buildDigest:output.digest}},adapter:'ticket-booking-browser',requirementsDigest:'c'.repeat(64),approvedRequirementIds:[],files:[{path:'src/pricing.ts',digest:value.sourceManifest.files.find(file=>file.path==='src/pricing.ts')!.digest}],contracts:(await deriveTrustedBrowserPolicy(frozen)).policy.cases,failureIds:[crypto.randomUUID()],failedCaseIds:['ticket_single_standard'],textConflictPaths:[],requiresIndependentVerification:true};throw Error('Synthetic external expected comparison failed');}return{version:1,scope:context.scope,sourceDigest:value.sourceManifest.digest,buildDigest:output.digest,policyDigest:context.scope.policyDigest,cases:policy.policy.cases.map(item=>({id:item.id,assertions:item.assertions.length,passed:true})),cleanup:'confirmed'};},
 recordProtectedConflictInputPin:async(_candidate:string,_workflow:string,_native:string,_command:string,_attempt:string,_round:number,proof:{ref:string;observedCommit:string})=>{if(!conflictReceipt)throw Error('Synthetic stored conflict input missing');expect(proof.observedCommit).toBe(conflictReceipt.head);expect(gitOrThrow(canonical,['rev-parse',proof.ref],{gitDir:true})).toBe(conflictReceipt.head);},protectedConflictRepairRecovery:async(_candidate:string,_workflow:string,round:number,marker:{sourceCommit:string;sourceDigest:string;planDigest:string;text:{nativeRunId:string;commandId:string;attemptId:string}},requestedNative?:string)=>{if(!plan||!conflictContext||!conflictReceipt||!identity||round!==identity.round||marker.sourceCommit!==conflictReceipt.head)throw Error('Exact synthetic historical conflict identity differs');if(requestedNative?requestedNative!==nativeId||!nativeActive:nativeActive)throw Error('Original synthetic native run remains unconfirmed');recoveryEvents.push(requestedNative?'fresh-recovery':'initial-recovery');const saved=repairs.get(identity.attemptId);return{plan:structuredClone(plan),context:structuredClone(conflictContext),scope:{projectId:state.projectId,incarnation,candidateId:candidate.id,workflowId,actorId:'fixture-human',accountKey:'aaaaaaaaaaaa'},snapshot:structuredClone(conflictReceipt),provider:{providerRepoId:'synthetic-canonical',canonicalRepoName:'canonical'},pinRef:`refs/flaregit/conflict-inputs/${candidate.id}/${conflictContext.attemptId}/head`,outcome:{phase:saved?.phase??'missing',attemptId:saved?.identity.attemptId??null,patch:saved?.patch??null},nativeProof:{coverage:true,allocations:[],commands:{pending:0}}};},
 protectedConflictContext:async(_candidate:string,_workflow:string,nativeRunId:string,attemptId:string)=>{const scope={projectId:state.projectId,incarnation,candidateId:candidate.id,workflowId,actorId:'fixture-human',accountKey:'aaaaaaaaaaaa'};return{scope,context:{...scope,nativeRunId,attemptId,acceptedBase:base,contributorCommits:candidate.participatingCommits,policyDigest:policy.digest,requirementsDigest:'c'.repeat(64)}};},protectedConflictRepairPlan:async()=>{if(!conflictContext||!conflictReceipt)throw Error('Synthetic stored native receipt missing');if(!plan){plan={kind:'protected-repair-input',source:{kind:'uncommitted-conflict-input',projectId:state.projectId,incarnation,candidateId:candidate.id,attemptId:conflictContext.attemptId,acceptedBase:base,contributorCommits:candidate.participatingCommits,sourceDigest:await repairDigest(JSON.stringify({context:conflictContext,snapshot:conflictReceipt})),policyDigest:policy.digest,requirementsDigest:'c'.repeat(64)},adapter:'ticket-booking-browser',requirementsDigest:'c'.repeat(64),approvedRequirementIds:[],files:[{path:'src/pricing.ts',digest:conflictReceipt.files.find(file=>file.path==='src/pricing.ts')!.digest}],contracts:policy.policy.cases,failureIds:[],failedCaseIds:[],textConflictPaths:['src/pricing.ts'],requiresIndependentVerification:true};}return{eligible:true,plan,context:conflictContext};},executeProtectedConflictRepair:async(_candidate:string,_workflow:string,_native:string,_command:string,_attempt:string,round:number,files:import('../src/server/static-build-artifact').BuildFile[])=>{if(!plan||plan.source.kind!=='uncommitted-conflict-input')throw Error('Missing frozen conflict source');identity={attemptId:crypto.randomUUID(),projectId:state.projectId,incarnation,candidateId:candidate.id,workflowId,actorId:'fixture-human',accountKey:'aaaaaaaaaaaa',round,sourceDigest:plan.source.sourceDigest,planDigest:await repairDigest(JSON.stringify(plan))};patch=await executeProtectedModelRepair(identity,plan,{ledger:repairs,currentPlan:async()=>structuredClone(plan!),assertCurrent:()=>{},readFailureCleanup:async()=>({source:plan!.source,failureIds:[],cleanup:'confirmed'}),readSource:async()=>Promise.all(files.map(async file=>{const content=new TextDecoder().decode(file.bytes);return{path:file.path,kind:'file' as const,content,digest:await repairDigest(content)};})),prepareModel:async()=>{},model:async()=>{modelCalls++;if('sourceRace' in scenario)await Bun.write(join(work,'index.html'),'Changed during the model await');return[{path:'src/pricing.ts',content:'export const price = 40;\n'}];}});if(!modelAckLost){modelAckLost=true;throw Error('Lost conflict model ACK');}return patch;},protectedConflictRepairOutcome:async()=>{const saved=identity?repairs.get(identity.attemptId):null;return{phase:saved?.phase??'missing',attemptId:saved?.identity.attemptId??null,patch:saved?.patch??null};},
 protectedBrowserRepairPlan:async()=>{if(!plan||!sourceContext)throw Error('Original trusted failure missing');return{eligible:true,plan:structuredClone(plan),sourceContext:structuredClone(sourceContext)};},executeProtectedBrowserRepair:async(_candidate:string,_workflow:string,round:number,provided:TrustedGitSource)=>{if(!plan||!sourceContext)throw Error('Plan missing');identity={attemptId:crypto.randomUUID(),projectId:state.projectId,incarnation,candidateId:candidate.id,workflowId,actorId:'fixture-human',accountKey:'aaaaaaaaaaaa',round,sourceDigest:sourceContext.sourceDigest,planDigest:await repairDigest(JSON.stringify(plan))};patch=await executeProtectedModelRepair(identity,plan,{ledger:repairs,currentPlan:async()=>structuredClone(plan!),assertCurrent:()=>{},readFailureCleanup:async()=>({source:plan!.source,failureIds:plan!.failureIds,cleanup:'confirmed'}),readSource:async()=>{const file=provided.files.find(file=>file.path==='src/pricing.ts')!,content=new TextDecoder().decode(file.bytes);return[{path:file.path,kind:'file',content,digest:await repairDigest(content)}];},prepareModel:async()=>{},model:async()=>{modelCalls++;return[{path:'src/pricing.ts',content:'export const price = 40;\n'}];}});if(!modelAckLost){modelAckLost=true;throw Error('Lost model RPC ACK');}return patch;},protectedRepairOutcome:async()=>{const saved=identity?repairs.get(identity.attemptId):null;return{phase:saved?.phase??'missing',attemptId:saved?.identity.attemptId??null,patch:saved?.patch??null};},protectedRepairRecovery:async(_candidate:string,_workflow:string,round:number,marker:{sourceCommit:string;sourceDigest:string;planDigest:string},requestedNative?:string)=>{if(!plan||!sourceContext||!identity||round!==identity.round||marker.sourceCommit!==sourceContext.scope.commit||marker.sourceDigest!==sourceContext.sourceDigest)throw Error('Synthetic exact historical model identity differs');if(requestedNative?requestedNative!==nativeId||!nativeActive:nativeActive)throw Error('Synthetic original native execution unconfirmed');recoveryEvents.push(requestedNative?'fresh-recovery':'initial-recovery');const saved=repairs.get(identity.attemptId);return{plan:structuredClone(plan),sourceContext:structuredClone(sourceContext),provider:{providerRepoId:'synthetic-canonical',canonicalRepoName:'canonical'},pinRef:`refs/flaregit/candidates/${candidate.id}`,outcome:{phase:forceHeld?'possible':saved?.phase??'missing',attemptId:saved?.identity.attemptId??null,patch:saved?.patch??null},nativeProof:{coverage:true,allocations:[],commands:{pending:0}}};},logActivity:async()=>{},previewStorageScope:async()=>{throw Error('Synthetic optional storage unavailable');},
 } as unknown as Ledger;
 const env={...nativeFunding(),UNTRUSTED_EXECUTION:{getByName:()=>({prepare:async()=>{},run:async(scope:import('../src/server/static-build-artifact').StaticBuildScope,manifest:import('../src/server/static-build-artifact').BuildManifest)=>{buildChecks.push(scope.commit);const files=[{path:'index.html',kind:'file' as const,bytes:new TextEncoder().encode('<h1>Explicit synthetic isolated build output</h1>')}];return{files,manifest:await bindBuildManifest('static',scope,files,manifest.digest),acceptanceEvidence:false};},stop:async()=>({stopped:true})})},ISOLATED_EXECUTION_IMAGE:`registry.cloudflare.com/${'a'.repeat(32)}/execution@sha256:${'b'.repeat(64)}`,VERIFICATION_BROWSER:{fetch},EVIDENCE_BUCKET:{}} as unknown as Env;
 const workflow=new FlareGitIntegrationWorkflow({} as ExecutionContext,env);Object.assign(workflow,{projectId:state.projectId,computeWorkflowId:workflowId,computeAccountKey:'aaaaaaaaaaaa',sandbox:async()=>{recoveryEvents.push('allocate');nativeId=crypto.randomUUID();nativeActive=true;return{...sandbox,nativeRunId:nativeId,destroy:async()=>{nativeActive=false;}};},canonicalRemote:async()=>({remote,token:'fixture-only',close:async()=>{}}),retainedRemote:async()=>({remote,token:'fixture-only',close:async()=>{}}),retainedAuthority:async()=>{},fundedRetainedCommand:async()=>{}});
 const callable=workflow as unknown as{composeRepairVerify(candidate:CandidateGeneration,params:{projectId:string;taskIds:string[];accountKey:string},stub:Ledger,workflowId:string):Promise<{ok:boolean;commit?:string}>};
 let result:{ok:boolean;commit?:string};
 if('textRetry' in scenario){let failed=false;try{await callable.composeRepairVerify(structuredClone(candidate),{projectId:state.projectId,taskIds:candidate.participatingTaskIds,accountKey:'aaaaaaaaaaaa'},ledger,workflowId);}catch{failed=true;}expect(failed).toBe(true);expect(modelCalls).toBe(1);expect(pins).toHaveLength(0);expect(buildChecks).toHaveLength(0);expect(browserChecks).toHaveLength(0);const marker=state.candidates.candidate.repairAttempts[0]?.protectedRepair;if(!marker?.resultCommit)throw Error('Mandatory native-before-pin interrupted marker missing');const originalResult=marker.resultCommit;
 const abortController={ctx:{storage},ensureRecoveryAlarm:async()=>{},legacyCandidateRerunFrozen:()=>false,legacyPreparedPublication:()=>false,load:()=>state,save:()=>{},stageEvent:()=>[],enqueueWebhookDelivery:async()=>{},logActivity:async()=>{}};
 await RepositoryController.prototype.abortPublish.call(abortController as unknown as InstanceType<typeof RepositoryController>,candidate.id,undefined,'Synthetic native-before-pin interruption','failed');expect(state.candidates.candidate.status).toBe('failed');
 pinInterrupted=true;replayStarted=true;recoveryEvents.length=0;
 try{result=await callable.composeRepairVerify(structuredClone(state.candidates.candidate),{projectId:state.projectId,taskIds:candidate.participatingTaskIds,accountKey:'aaaaaaaaaaaa'},ledger,workflowId);}catch{if(!('replayRace' in scenario))throw Error('Unexpected historical conflict replay failure');result={ok:false};}
 expect(modelCalls).toBe(1);expect(recoveryEvents.indexOf('initial-recovery')).toBeLessThan(recoveryEvents.indexOf('allocate'));if('replayRace' in scenario){expect(result.ok).toBe(false);expect(pins).toHaveLength(0);expect(nativeChecks).toHaveLength(1);return;}expect(result.commit).toBe(originalResult);expect(state.candidates.candidate.repairAttempts).toHaveLength(1);if(!conflictContext||!conflictReceipt)throw Error('Original unverified conflict input absent');expect(gitOrThrow(canonical,['rev-parse',`refs/flaregit/conflict-inputs/${candidate.id}/${conflictContext.attemptId}/head`],{gitDir:true})).toBe(conflictReceipt.head);
 }else result=await callable.composeRepairVerify(structuredClone(candidate),{projectId:state.projectId,taskIds:candidate.participatingTaskIds,accountKey:'aaaaaaaaaaaa'},ledger,workflowId);
 if('sourceRace' in scenario){expect(result.ok).toBe(false);expect(modelCalls).toBe(1);expect(nativeChecks).toHaveLength(0);expect(pins).toHaveLength(0);expect(state.candidates.candidate.repairAttempts[0]?.protectedRepair?.status).toBe('unknown');expect(gitOrThrow(canonical,['rev-parse','refs/heads/main'],{gitDir:true})).toBe(base);return;}
 const originalVerified=nativeChecks[0],repairedVerified=nativeChecks[conflict?('textRetry' in scenario?1:0):1];if(!originalVerified||!repairedVerified||!result.commit)throw Error('Mandatory real verified commit identities missing');
 expect(result.ok).toBe(true);expect(modelCalls).toBe(1);expect(patch?.acceptanceEvidence).toBe(false);expect(nativeChecks).toHaveLength(conflict?('textRetry' in scenario?2:1):2);expect(browserChecks).toEqual('textRetry' in scenario?nativeChecks.slice(1):nativeChecks);expect(buildChecks).toEqual('textRetry' in scenario?nativeChecks.slice(1):nativeChecks);if(!conflict)expect(originalVerified).not.toBe(repairedVerified);expect(result.commit).toBe(repairedVerified);expect(pins).toEqual(conflict?[{commit:repairedVerified,revision:false}]:[{commit:originalVerified,revision:false},{commit:repairedVerified,revision:true}]);expect(state.candidates.candidate.repairAttempts[0]?.patch).toContain('diff --git a/src/pricing.ts b/src/pricing.ts');expect(state.candidates.candidate.repairAttempts[0]?.protectedRepair).toMatchObject({status:'applied',modelAttemptId:patch!.attemptId,resultCommit:result.commit});expect(gitOrThrow(canonical,['rev-parse','refs/heads/main'],{gitDir:true})).toBe(base);expect(gitOrThrow(canonical,['rev-parse',`refs/flaregit/candidates/${candidate.id}`],{gitDir:true})).toBe(originalVerified);if(landing==='squash'){expect(gitOrThrow(work,['rev-parse','HEAD^'])).toBe(base);expect(gitOrThrow(work,['log','-1','--format=%B'])).toContain('Co-authored-by: Contributor <one@users.flaregit.com>');}
 if(!conflict){const saved=state.candidates.candidate.repairAttempts[0]?.protectedRepair;if(!saved)throw Error('Mandatory saved repair marker absent');saved.status='unknown';expect(state.candidates.candidate.candidateCommit).toBe(result.commit);recoveryEvents.length=0;
 const replay=await callable.composeRepairVerify(structuredClone(state.candidates.candidate),{projectId:state.projectId,taskIds:candidate.participatingTaskIds,accountKey:'aaaaaaaaaaaa'},ledger,workflowId);
 expect(replay.ok).toBe(true);expect(replay.commit).toBe(result.commit);expect(modelCalls).toBe(1);expect(nativeChecks.at(-1)).toBe(result.commit);expect(browserChecks.at(-1)).toBe(result.commit);expect(buildChecks.at(-1)).toBe(result.commit);expect(recoveryEvents.indexOf('initial-recovery')).toBeLessThan(recoveryEvents.indexOf('allocate'));expect(state.candidates.candidate.repairAttempts).toHaveLength(1);expect(state.candidates.candidate.repairAttempts[0]?.patch).toContain('diff --git a/src/pricing.ts b/src/pricing.ts');expect(state.candidates.candidate.repairAttempts[0]?.protectedRepair?.status).toBe('applied');
 forceHeld=true;recoveryEvents.length=0;const held=await callable.composeRepairVerify(structuredClone(state.candidates.candidate),{projectId:state.projectId,taskIds:candidate.participatingTaskIds,accountKey:'aaaaaaaaaaaa'},ledger,workflowId);expect(held.ok).toBe(false);expect(recoveryEvents).not.toContain('allocate');expect(modelCalls).toBe(1);
 forceHeld=false;nativeActive=true;recoveryEvents.length=0;const unknownNative=await callable.composeRepairVerify(structuredClone(state.candidates.candidate),{projectId:state.projectId,taskIds:candidate.participatingTaskIds,accountKey:'aaaaaaaaaaaa'},ledger,workflowId);expect(unknownNative.ok).toBe(false);expect(recoveryEvents).not.toContain('allocate');expect(modelCalls).toBe(1);nativeActive=false;}
 }finally{db.close();await rm(root,{recursive:true,force:true});}
},20000);
