import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {captureProtectedConflictSource,validateProtectedConflictSnapshot,PROTECTED_CONFLICT_INSPECTOR,type ProtectedConflictContext,type ProtectedConflictPorts} from '../src/server/protected-conflict-source';
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'protected-conflict-'));const git=(...args:string[])=>{const p=Bun.spawnSync(['git','-C',dir,...args]);if(p.exitCode)throw Error('Fixture Git failed');return p.stdout.toString().trim();};git('init','-q');git('config','user.name','Local fixture');git('config','user.email','fixture@example.invalid');await Bun.write(join(dir,'src/pricing.ts'),'export const price=10;\n');git('add','.');git('commit','-qm','base');const base=git('rev-parse','HEAD');git('checkout','-qb','left');await Bun.write(join(dir,'src/pricing.ts'),'export const price=11;\n');git('commit','-qam','left');const left=git('rev-parse','HEAD');git('checkout','-qb','right',base);await Bun.write(join(dir,'src/pricing.ts'),'export const price=12;\n');git('commit','-qam','right');const right=git('rev-parse','HEAD');git('checkout','-q','left');const merge=Bun.spawnSync(['git','-C',dir,'merge','--no-commit','right']);expect(merge.exitCode).not.toBe(0);const context:ProtectedConflictContext={projectId:'project123456',incarnation:crypto.randomUUID(),candidateId:'candidate',workflowId:'workflow',actorId:'owner',accountKey:'account',nativeRunId:crypto.randomUUID(),attemptId:crypto.randomUUID(),acceptedBase:base,contributorCommits:{left,right},policyDigest:'a'.repeat(64),requirementsDigest:'b'.repeat(64)};const ports:ProtectedConflictPorts={assertCurrent:()=>{},admit:async()=>({scope:{projectId:context.projectId,incarnation:context.incarnation,candidateId:context.candidateId,workflowId:context.workflowId,actorId:context.actorId,accountKey:context.accountKey},nativeRunId:context.nativeRunId,commandId:crypto.randomUUID()}),inspect:async(permit,argv)=>{expect(argv[2]).toBe(PROTECTED_CONFLICT_INSPECTOR);const script=PROTECTED_CONFLICT_INSPECTOR.replace("const root='/workspace/integration'",`const root=${JSON.stringify(dir)}`);const p=Bun.spawnSync(['bun','-e',script,argv[3]!]);if(p.exitCode)throw Error(p.stderr.toString());return{stdout:p.stdout.toString(),completedCommandId:permit.commandId};}};return{dir,context,ports,git,close:()=>rm(dir,{recursive:true,force:true})};}
test('real two-branch conflict captures native index stages and full regular file digests',async()=>{const f=await fixture();try{const result=await captureProtectedConflictSource(f.context,f.ports);expect(result.source.kind).toBe('uncommitted-conflict-input');expect(result.source.sourceDigest).toMatch(/^[a-f0-9]{64}$/);expect(result.snapshot.index.map(r=>r.stage)).toEqual([1,2,3]);expect(result.snapshot.mergeHeads).toEqual([f.context.contributorCommits.right!]);expect(result.snapshot.files[0]?.path).toBe('src/pricing.ts');expect(result.acceptanceEvidence).toBe(false);expect((await captureProtectedConflictSource(f.context,f.ports)).source.sourceDigest).toBe(result.source.sourceDigest);}finally{await f.close();}});
test('duplicate stages, foreign merge head, gitlink modes and credential paths are refused',async()=>{const f=await fixture();try{const result=await captureProtectedConflictSource(f.context,f.ports),raw=result.snapshot;expect(()=>validateProtectedConflictSnapshot(f.context,{...raw,index:[...raw.index,raw.index[0]]})).toThrow('index differs');expect(()=>validateProtectedConflictSnapshot(f.context,{...raw,mergeHeads:['f'.repeat(40)]})).toThrow('scope differs');expect(()=>validateProtectedConflictSnapshot(f.context,{...raw,index:raw.index.map(r=>({...r,mode:'160000'}))})).toThrow();expect(()=>validateProtectedConflictSnapshot(f.context,{...raw,files:[{...raw.files[0],path:'.env'}]})).toThrow();expect(()=>validateProtectedConflictSnapshot({...f.context,acceptedBase:null},raw)).toThrow();}finally{await f.close();}});
test('actual symlink replacement and forged native ownership cannot become source proof',async()=>{const f=await fixture();try{const unlink=await import('node:fs/promises');await unlink.unlink(join(f.dir,'src/pricing.ts'));await unlink.symlink('/etc/passwd',join(f.dir,'src/pricing.ts'));await expect(captureProtectedConflictSource(f.context,f.ports)).rejects.toThrow();f.ports.admit=async()=>({scope:{projectId:'other',incarnation:f.context.incarnation,candidateId:'candidate',workflowId:'workflow',actorId:'owner',accountKey:'account'},nativeRunId:f.context.nativeRunId,commandId:crypto.randomUUID()});await expect(captureProtectedConflictSource(f.context,f.ports)).rejects.toThrow('ownership differs');}finally{await f.close();}});

test('changed actual conflict bytes change source digest and withdrawn actor prevents capture',async()=>{const f=await fixture();try{const first=await captureProtectedConflictSource(f.context,f.ports);await Bun.write(join(f.dir,'src/pricing.ts'),'<<<<<<< HEAD\nchanged left\n=======\nright\n>>>>>>> right\n');const changed=await captureProtectedConflictSource(f.context,f.ports);expect(changed.source.sourceDigest).not.toBe(first.source.sourceDigest);expect(changed.snapshot.files[0]!.digest).not.toBe(first.snapshot.files[0]!.digest);f.ports.assertCurrent=()=>{throw Error('owner revoked');};await expect(captureProtectedConflictSource(f.context,f.ports)).rejects.toThrow('owner revoked');}finally{await f.close();}});

test('modify/delete conflict stages require a contributor decision before any model plan',async()=>{const f=await fixture();try{const{snapshot}=await captureProtectedConflictSource(f.context,f.ports);expect(()=>validateProtectedConflictSnapshot(f.context,{...snapshot,index:snapshot.index.filter(row=>row.stage!==3)})).toThrow('contributor decision');expect(()=>validateProtectedConflictSnapshot(f.context,{...snapshot,index:snapshot.index.filter(row=>row.stage!==2)})).toThrow('contributor decision');expect(()=>validateProtectedConflictSnapshot(f.context,{...snapshot,index:snapshot.index.map(row=>row.stage===3?{...row,mode:'100755'}:row)})).toThrow();}finally{await f.close();}});
