import { Database } from "bun:sqlite";
import { expect,test } from "bun:test";
import { PublicDirectory,projectPublicDirectory } from "../src/server/public-directory";
function store(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}};return new PublicDirectory(storage as unknown as DurableObjectStorage);}
const id="p123456abcdef";
test("directory defaults private and has explicit CAS opt-in with durable unknown delivery",()=>{const directory=store();expect(directory.state()).toEqual({enabled:false,version:0,delivery:"delivered"});expect(()=>directory.configure({enabled:true,confirmed:true,expectedVersion:0},false)).toThrow();expect(()=>directory.configure({enabled:true,confirmed:false,expectedVersion:0},true)).toThrow();directory.configure({enabled:true,confirmed:true,expectedVersion:0},true);expect(directory.pending(id)).toEqual({projectId:id,enabled:true,version:1});expect(()=>directory.configure({enabled:false,confirmed:true,expectedVersion:0},true)).toThrow();directory.configure({enabled:false,confirmed:true,expectedVersion:1},false);directory.delivered(1);expect(directory.state().delivery).toBe("pending");directory.delivered(2);expect(directory.state().delivery).toBe("delivered");});
test("index replay cannot resurrect revoked listing and holds no private identity",()=>{const directory=store();directory.register({projectId:id,enabled:true,version:1});directory.register({projectId:id,enabled:false,version:2});directory.register({projectId:id,enabled:true,version:1});expect(directory.page().rows).toEqual([]);directory.register({projectId:id,enabled:true,version:3});expect(directory.page().rows).toEqual([{projectId:id,enabled:true,version:3}]);});
test("fresh opt-in and visibility checks suppress racing revocation and mark unavailable pages",async()=>{let calls=0;const result=await projectPublicDirectory({rows:[{projectId:id,enabled:true,version:1}],query:"",repository:()=>({directoryState:async()=>({enabled:++calls===1,version:1,delivery:"delivered"}),publicGrant:async()=>({name:"Real repository",version:1,acceptedCommit:"a".repeat(40)})})});expect(result.repositories).toEqual([]);expect(result.incomplete).toBe(true);const unavailable=await projectPublicDirectory({rows:[{projectId:id,enabled:true,version:1}],query:"",repository:()=>({directoryState:async()=>{throw new Error("unavailable");},publicGrant:async()=>null})});expect(unavailable.incomplete).toBe(true);});
test("projection emits only public name accepted commit and internal repository route",async()=>{const result=await projectPublicDirectory({rows:[{projectId:id,enabled:true,version:1}],query:"real",repository:()=>({directoryState:async()=>({enabled:true,version:1,delivery:"delivered"}),publicGrant:async()=>({name:"Real repository",version:1,acceptedCommit:"a".repeat(40),canonicalRepoName:"PRIVATE-NAMESPACE",ownerId:"private-person"})})});expect(result.repositories).toEqual([{id,name:"Real repository",acceptedCommit:"a".repeat(40),href:`/#/public/${id}`}]);expect(JSON.stringify(result)).not.toContain("PRIVATE-NAMESPACE");});

test("final projection refuses publication version changes with an unchanged name and accepted head",async()=>{let reads=0;const result=await projectPublicDirectory({rows:[{projectId:id,enabled:true,version:1}],query:"",repository:()=>({directoryState:async()=>({enabled:true,version:1,delivery:"delivered"}),publicGrant:async()=>({name:"Real repository",version:++reads===3?2:1,acceptedCommit:"a".repeat(40)})})});expect(result.repositories).toEqual([]);expect(result.incomplete).toBe(true);});
