import {test,expect} from "bun:test";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {workerdChild} from "./support/workerd-child";
test("actual SQLite readback reconciles only observed ancestry, retains uncertainty and caps unfunded sweeps",async()=>{
 if(await workerdChild("tests/publication-readback.test.ts"))return;
 const file=`/tmp/flaregit-readback-${crypto.randomUUID()}.js`,p=Bun.spawn([process.execPath,"build","tests/support/publication-readback-worker.ts","--target=browser","--external=cloudflare:workers","--external=node:*",`--outfile=${file}`],{stdout:"ignore",stderr:"pipe"});const [stderr,code]=await Promise.all([new Response(p.stderr).text(),p.exited]);if(code)throw new Error(stderr);
 const script=await Bun.file(file).text();
 const mf=new Miniflare(convertV4MiniflareOptions({workers:["readback","unfunded"].map(name=>({name,modules:true,script,compatibilityDate:"2026-10-02",compatibilityFlags:["nodejs_compat"],bindings:{CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:"10000000",CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:"10000000",REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:name==="unfunded"?"0":"1000000",REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:name==="unfunded"?"0":"1000000"},durableObjects:{REPOSITORY_CONTROLLER:{className:"PublicationReadbackFixture",useSQLite:true}}}))}));
 try{const worker=await mf.getWorker("readback"),call=async(mode:string)=>{const r=await worker.fetch(`https://fixture/?mode=${mode}`);expect(r.status).toBe(200);return await r.json() as {first?:{reason:string};state?:{acceptedState:{history:unknown[];currentCommit:string};journal:Array<{state:string}>};before?:{calls:number;state:{journal:Array<{state:string}>}};after?:{calls:number};calls?:number;automatic?:Array<{attempts:number}>;outcome?:{terminal:number}};};
 const published=await call("published");expect(published.first?.reason).toBe("confirmed");expect(published.state?.acceptedState.currentCommit).toBe("c".repeat(40));expect(published.state?.acceptedState.history).toHaveLength(1);expect(published.after?.calls).toBe(published.before?.calls);
 for(const mode of ["missing","truncated"]){const b=await call(mode);expect(b.first?.reason).toBe(mode==="missing"?"not_observed":"inspection_limit");expect(b.before?.state.journal[0]?.state).toBe("PREPARED");expect(b.after?.calls).toBe(b.before?.calls);}
 const automatic=await call("automatic-missing");expect(automatic.automatic?.[0]?.attempts).toBe(4);expect(automatic.calls).toBe(12);expect(automatic.outcome?.terminal).toBe(0);
 const unfunded=await mf.getWorker("unfunded"),deniedResponse=await unfunded.fetch("https://fixture/?mode=budget");expect(deniedResponse.status).toBe(200);const denied=await deniedResponse.json() as {calls:number;automatic:Array<{attempts:number}>;outcome:{terminal:number};reports:Array<{reason:string}>};expect(denied.calls).toBe(0);expect(denied.automatic[0]?.attempts).toBe(4);expect(denied.outcome.terminal).toBe(0);expect(denied.reports[0]?.reason).toBe("capacity_unavailable");
 const revoked=await call("revoked");expect(revoked.first?.reason).toBe("scope_changed");expect(revoked.state?.journal[0]?.state).toBe("PREPARED");
 }finally{await mf.dispose();await Bun.file(file).delete();}
},30000);
