import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {workerdChild} from './support/workerd-child';
import type {CandidateGeneration,PublicationJournalEntry} from '../src/core/types';
test('bound publication recovery HTTP requires exact owner scope and explicitly confirmed immutable cancellation',async()=>{
 if(await workerdChild('tests/publication-bound-http.test.ts'))return;
 const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'publication-http',alg:'RS256',use:'sig'},issuer=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({keys:[jwk]})});
 const file='/tmp/publication-http-'+crypto.randomUUID()+'.js',build=Bun.spawn([process.execPath,'build','tests/support/publication-bound-http-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*','--outfile='+file],{stdout:'ignore',stderr:'pipe'});if(await build.exited)throw Error(await new Response(build.stderr).text());const script=await Bun.file(file).text();await Bun.file(file).delete();
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'publication-http',unsafeDirectSockets:[{host:'127.0.0.1'}],modules:true,script,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],bindings:{FIXTURE_ISSUER:issuer.url.origin,REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000',MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000'},durableObjects:{REPOSITORY_CONTROLLER:{className:'AcceptedTargetFixture',useSQLite:true}}}]}));
 try{const direct=await mf.unsafeGetDirectURL('publication-http'),call=(path:string,token?:string,body?:unknown)=>fetch(new URL(path,direct),{method:body?'POST':'GET',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.40',...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call('/fixture'+path,undefined,body);if(!response.ok)throw Error(await response.text());return await response.json() as T;};
 await json('/seed');await json('/create',{operationId:crypto.randomUUID(),name:'release',sourceCommit:'a'.repeat(40)});await json('/legacy-baseline');await json('/target-task',{id:'http-task',ref:'refs/heads/release'});const {candidate}=await json<{candidate:CandidateGeneration}>('/landing',{tasks:['http-task'],holder:'http-holder'});await json('/verify-target',{id:candidate.id,bind:true,commit:'b'.repeat(40)});const target=candidate.acceptedTarget!;await json('/review-target',{id:candidate.id,target:{ref:target.ref,acceptedCommit:target.acceptedCommit,acceptedVersion:target.acceptedVersion}});const {journal}=await json<{journal:PublicationJournalEntry}>('/prepare?id='+candidate.id);await json('/seal-target-runtime?id='+candidate.id);
 const session=(id:string)=>new SignJWT({azp:'https://fixture.example'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer.url.origin).setSubject(id).setIssuedAt().setExpirationTime('5m').sign(pair.privateKey),owner=await session('owner'),member=await session('member'),{token}=await json<{token:string}>('/token'),route='/api/p/p123456789abc/publication-recovery',endpoint=route+'/'+journal.id+'/cancel-undispatched';
 for(const credential of [undefined,member,token])expect((await call(route+'/bound',credential)).status).toBe(credential?403:401);
 const summary=await call(route+'/bound',owner);expect(summary.status).toBe(200);expect(summary.headers.get('Cache-Control')).toBe('no-store');const raw=await summary.text();for(const secret of ['accountKey','plaintext','remote','nativeId'])expect(raw).not.toContain(secret);expect(JSON.parse(raw)).toMatchObject({operations:[{journalId:journal.id,canRequestCancellation:true}]});
 const input={requestId:crypto.randomUUID(),candidateId:candidate.id,expectedRef:'refs/heads/release',expectedCommit:journal.newHead,confirmCancel:true};const before=await json<unknown>('/state-full');for(const invalid of [{...input,confirmCancel:false},{...input,extra:true},{...input,expectedCommit:'zero'},{...input,confirmCancel:undefined}])expect((await call(endpoint,owner,invalid)).status).toBe(400);for(const wrong of [{...input,expectedRef:'refs/heads/main'},{...input,candidateId:'other'},{...input,expectedCommit:'f'.repeat(40)}])expect((await call(endpoint,owner,wrong)).status).toBe(409);expect(await json<unknown>('/state-full')).toEqual(before);
 for(const credential of [member,token])expect((await call(endpoint,credential,input)).status).toBe(403);
 const saved=await call(endpoint,owner,input);expect(saved.status).toBe(200);const receipt=await saved.json();expect(receipt).toEqual({journalId:journal.id,candidateId:candidate.id,eventId:input.requestId,status:'cancelled_undispatched',ref:input.expectedRef,commit:input.expectedCommit});const replay:unknown=await (await call(endpoint,owner,input)).json();expect(replay).toEqual(receipt);
 }finally{await mf.dispose();issuer.stop(true);}
},30000);
