import{expect,test}from"bun:test";
import{Miniflare,convertV4MiniflareOptions}from"miniflare";
import{workerdChild}from"./support/workerd-child";
test("production directory RPC preserves unknown registration and alarm replay, rejects nonowners and revokes private",async()=>{
if(await workerdChild("tests/public-directory-workerd.test.ts"))return;
const bundle=`/tmp/flaregit-directory-${crypto.randomUUID()}.js`;const build=Bun.spawn([process.execPath,"build","tests/support/public-directory-worker.ts","--target=browser","--external=cloudflare:workers",`--outfile=${bundle}`],{stdout:"ignore",stderr:"pipe"});const[errors,code]=await Promise.all([new Response(build.stderr).text(),build.exited]);if(code)throw new Error(errors);const script=await Bun.file(bundle).text();await Bun.file(bundle).delete();
const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"directory",modules:true,script,compatibilityDate:"2026-10-02",durableObjects:{REPOSITORY_CONTROLLER:{className:"DirectoryFixture",useSQLite:true}}}]}));const call=async(path:string,body?:unknown)=>(await mf.getWorker("directory")).fetch(`http://fixture${path}`,body?{method:"POST",body:JSON.stringify(body)}:undefined);
try{expect((await call("/seed")).status).toBe(200);await call("/fault?enabled=true");expect((await call("/configure?actor=outsider",{enabled:true,confirmed:true,expectedVersion:0})).status).toBe(409);expect((await call("/configure",{enabled:true,confirmed:true,expectedVersion:0})).status).toBe(200);const state=await(await call("/state")).json()as{state:{delivery:string};alarm:number|null};expect(state.state.delivery).toBe("pending");expect(state.alarm).not.toBeNull();expect((await(await call("/page")).json()as{rows:unknown[]}).rows).toHaveLength(1);await call("/fault?enabled=false");expect((await(await call("/alarm")).json()as{delivery:string}).delivery).toBe("delivered");expect((await(await call("/page")).json()as{rows:unknown[]}).rows).toHaveLength(1);expect((await(await call("/private")).json()as{enabled:boolean}).enabled).toBe(false);expect((await(await call("/page")).json()as{rows:unknown[]}).rows).toHaveLength(0);}finally{await mf.dispose();}
},30000);
