import {Database} from 'bun:sqlite';
import {expect,test} from 'bun:test';
import {PublicationNativePhases} from '../src/server/publication-native-phase';
test('private batch keeps two actual SQLite workflow grants independently consumed on the same controller',()=>{const f=fixture();try{const second={...f.identity,workflowId:'workflow-b',candidateId:'candidate-b',journalId:'journal-b',commit:'4'.repeat(40),evidenceId:'evidence-b'},configB={...f.config,...second},env={...f.env,PUBLICATION_NATIVE_PHASE_JSON:undefined,C03_PRIVATE_MATRIX_ENABLED:'true',PUBLICATION_NATIVE_PHASES_JSON:JSON.stringify([f.config,configB])};const a=f.phases.install(f.identity,env),b=f.phases.install(second,env);expect(a.config.workflowId).toBe('workflow');expect(b.config.workflowId).toBe('workflow-b');const nativeA=crypto.randomUUID(),nativeB=crypto.randomUUID(),scopeB={...f.scope,workflowId:second.workflowId,candidateId:second.candidateId};f.phases.reserve(f.scope,nativeA,'publish-candidate');f.phases.reserve(scopeB,nativeB,'publish-candidate-b');expect(f.phases.claimStart(f.scope,nativeA,env).image).toBe(f.config.image);expect(f.phases.claimStart(scopeB,nativeB,env).image).toBe(configB.image);expect(()=>f.phases.reserve(f.scope,nativeB,'publish-candidate')).toThrow();expect(()=>f.phases.claimStart(scopeB,nativeB,env)).toThrow();expect(f.phases.get('workflow')?.nativeId).toBe(nativeA);expect(f.phases.get('workflow-b')?.nativeId).toBe(nativeB);}finally{f.db.close();}});
function fixture(realTime=false){const db=new Database(':memory:');let now=realTime?Date.now():1000;const storage={sql:{exec(q:string,...args:(string|number)[]){const rows=db.query(q).all(...args);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;const scope={workflowId:'workflow',candidateId:'candidate',projectId:'project',incarnation:crypto.randomUUID(),actorId:'initiator',accountKey:'account'},identity={...scope,journalId:'journal',commit:'1'.repeat(40),tree:'2'.repeat(40),evidenceId:'evidence',reviewActorId:'reviewer'},config={...identity,sourceVersion:'3'.repeat(40),image:`registry.cloudflare.com/${'a'.repeat(32)}/verifier@sha256:${'b'.repeat(64)}`,activatedAt:now-100,admissionExpiresAt:now+1000,nativeStopAt:now+1201000,maxAllocations:1,maxContainerSeconds:1200,maxCommands:64,kind:'native-essential'},env={PUBLICATION_NATIVE_PHASE_JSON:JSON.stringify(config),FLAREGIT_SOURCE_VERSION:config.sourceVersion,CF_VERSION_METADATA:{id:crypto.randomUUID()}},phases=new PublicationNativePhases(storage,()=>now);return{db,storage,scope,identity,env,phases,config,setNow:(value:number)=>{now=value;}};}
test('publisher grant binds exact controller identity and immutable current release',()=>{const f=fixture();try{expect(()=>f.phases.install(f.identity,{...f.env,PUBLICATION_NATIVE_PHASE_JSON:undefined})).toThrow();expect(()=>f.phases.install({...f.identity,reviewActorId:'other'},f.env)).toThrow();const saved=f.phases.install(f.identity,f.env);expect(f.phases.install(f.identity,f.env)).toEqual(saved);expect(()=>f.phases.install(f.identity,{...f.env,CF_VERSION_METADATA:{id:crypto.randomUUID()}})).toThrow();expect(()=>f.phases.install(f.identity,{...f.env,PUBLICATION_NATIVE_PHASE_JSON:JSON.stringify({...f.config,journalId:'other'})})).toThrow();}finally{f.db.close();}});
test('publisher allocation and start stay consumed after interruption without rebase grant',()=>{const f=fixture();try{f.phases.install(f.identity,f.env);const id=crypto.randomUUID();expect(()=>f.phases.reserve(f.scope,id,'rebase-candidate')).toThrow();f.phases.reserve(f.scope,id,'publish-candidate');expect(f.phases.reserve(f.scope,id,'publish-candidate').nativeId).toBe(id);expect(()=>f.phases.reserve(f.scope,crypto.randomUUID(),'publish-candidate')).toThrow();expect(f.phases.claimStart(f.scope,id,f.env).image).toBe(f.config.image);expect(()=>f.phases.claimStart(f.scope,id,f.env)).toThrow();expect(()=>f.phases.owns({...f.scope,candidateId:'other'},id)).toThrow();}finally{f.db.close();}});
test('publisher cannot start after admission or extend command stop',()=>{const f=fixture();try{f.phases.install(f.identity,f.env);const id=crypto.randomUUID();f.phases.reserve(f.scope,id,'publish-candidate');f.setNow(2000);expect(()=>f.phases.claimStart(f.scope,id,f.env)).toThrow();expect(f.phases.commandAllowed(f.scope,id)).toBe(true);f.setNow(1201000);expect(f.phases.commandAllowed(f.scope,id)).toBe(false);}finally{f.db.close();}});

test('publication ledger gets its own64 commands while integration reservation remains consumed',async()=>{const {IntegrationNativePhases}=await import('../src/server/integration-native-phase');const {IntegrationNativeRuntimeLedger}=await import('../src/server/integration-native-runtime');const f=fixture(true);try{
 const storage=f.storage;
 // Existing immutable integration record represents the separately closed verification phase.
 storage.sql.exec('CREATE TABLE integration_native_phases(workflow_id TEXT PRIMARY KEY,doc TEXT NOT NULL)');const original={config:{projectId:f.scope.projectId,incarnation:f.scope.incarnation,actorId:f.scope.actorId,expectedEventId:f.scope.workflowId,maxCommands:64},candidateId:f.scope.candidateId,nativeId:crypto.randomUUID(),allocatedAt:Date.now(),startClaimed:true};storage.sql.exec('INSERT INTO integration_native_phases VALUES(?,?)',f.scope.workflowId,JSON.stringify(original));
 const ledger=new IntegrationNativeRuntimeLedger(storage);ledger.declareCoverage(f.scope);const integrate=original.nativeId;storage.sql.exec('INSERT INTO integration_native_allocations VALUES(?,?,?,1)',integrate,f.scope.workflowId,'integrate-candidate');for(let i=0;i<64;i++)storage.sql.exec("INSERT INTO integration_native_commands VALUES(?,?,?,'completed')",crypto.randomUUID(),f.scope.workflowId,integrate);
 ledger.closeVerification(f.scope,{commit:f.identity.commit,tree:f.identity.tree,evidenceId:f.identity.evidenceId});f.phases.install(f.identity,f.env);const publisher=crypto.randomUUID();ledger.reserve(f.scope,publisher,'publish-candidate');
 for(let i=0;i<64;i++){const id=crypto.randomUUID();ledger.admitCommand(f.scope,publisher,id);ledger.finishCommand(f.scope,publisher,id,{outcome:'completed'});}expect(()=>ledger.admitCommand(f.scope,publisher,crypto.randomUUID())).toThrow();expect(JSON.stringify(new IntegrationNativePhases(storage).get(f.scope.workflowId))).toBe(JSON.stringify(original));expect(()=>ledger.reserve(f.scope,crypto.randomUUID(),'rebase-candidate')).toThrow();expect(f.db.query('SELECT COUNT(*) AS count FROM integration_native_commands').get()).toEqual({count:128});
 }finally{f.db.close();}});
