import { Database } from "bun:sqlite";
import { test,expect } from "bun:test";
import {RebaseResumeAttempts,assertRebaseResumeSessionDelegation,REBASE_RESUME_SESSION_DELEGATION_MS} from "../src/server/rebase-resume-attempts";
import type {RebaseApplication} from "../src/server/retained-inputs";
import type {RebaseRecoverySnapshot} from "../src/server/rebase-recovery";
function fixture(){const db=new Database(":memory:"),storage={sql:{exec(q:string,...b:Array<string|number>){const rows=db.query(q).all(...b);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;return{db,ledger:new RebaseResumeAttempts(storage)};}
const actor={userId:"current-owner",displayName:"Maintainer",viaToken:false};
const application={input:{id:crypto.randomUUID(),projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",workspaceRepoName:"workspace",taskId:"task",branch:"task/one",commit:"a".repeat(40),base:"b".repeat(40),actorId:"departed-contributor"},commit:"c".repeat(40),base:"d".repeat(40),status:"prepared"} as unknown as RebaseApplication;
const snapshot={projectId:"project",incarnation:application.input.incarnation,canonicalRepoName:"canonical",accepted:true,task:{id:"task",currentCommit:application.input.commit,baseCommit:application.input.base,workspaceRepoName:"workspace",branch:"task/one",status:"blocked"}} satisfies RebaseRecoverySnapshot;
const input=()=>({application,snapshot,actor,expectedVersion:0,requestId:crypto.randomUUID()});
test("exact request replay survives uncertain dispatch and retains immutable identity",()=>{const f=fixture();try{const request=input(),first=f.ledger.begin(request);expect(first.nativeRunId).toBe(first.workflowId);f.ledger.dispatch(first.id,1,"unknown");const replay=f.ledger.begin({...request,actor:{...actor,displayName:"Renamed"}});expect(replay.id).toBe(first.id);expect(replay.actor).toEqual(actor);expect(replay.application.input.actorId).toBe("departed-contributor");expect(()=>f.ledger.begin({...request,actor:{...actor,userId:"other-owner"}})).toThrow("another saved recovery");expect(()=>f.ledger.begin(input())).toThrow("may still be running");expect(()=>f.ledger.dispatch(first.id,1,"saved")).toThrow("cannot be reset");}finally{f.db.close();}});
test("only confirmed terminal and stopped execution permits a new generation",()=>{const f=fixture();try{const first=f.ledger.begin(input());f.ledger.dispatch(first.id,1,"observed");f.ledger.nativeIntent(first.id,1);f.ledger.terminal(first.id,1,"failed");expect(()=>f.ledger.begin(input())).toThrow("may still be running");expect(()=>f.ledger.nativeStopped(first.id,1,"different-native")).toThrow("identity changed");f.ledger.nativeStopped(first.id,1,first.nativeRunId);const second=f.ledger.begin(input());expect(second.generation).toBe(2);expect(second.nativeRunId).not.toBe(first.nativeRunId);expect(()=>f.ledger.nativeIntent(first.id,1)).toThrow("generation changed");expect(f.ledger.get(first.id)?.terminal).toBe("failed");}finally{f.db.close();}});
test("audit capacity preserves replay and refuses new attempts without deleting history",()=>{const f=fixture();try{const request=input(),first=f.ledger.begin(request);const insert=f.db.query("INSERT INTO rebase_resume_attempts(id,application_id,request_id,payload,doc) VALUES(?,?,?,?,?)");f.db.transaction(()=>{for(let i=1;i<10_000;i++)insert.run(`seed-${i}`,`app-${i}`,`request-${i}`,"{}","{}");})();expect(f.ledger.begin(request).id).toBe(first.id);expect(()=>f.ledger.begin(input())).toThrow("capacity reached");expect(f.db.query("SELECT COUNT(*) AS n FROM rebase_resume_attempts").get()).toEqual({n:10_000});}finally{f.db.close();}});

test("background session delegation is bounded, immutable on replay and independent of foreground expiry",()=>{const f=fixture();try{const request={...input(),sessionExpiresAt:Date.now()+60_000},first=f.ledger.begin(request),created=Date.parse(first.createdAt);expect(first.sessionDelegation).toEqual({version:1,expiresAt:created+REBASE_RESUME_SESSION_DELEGATION_MS});expect(()=>assertRebaseResumeSessionDelegation(first,created+120_000)).not.toThrow();expect(()=>assertRebaseResumeSessionDelegation(first,created+REBASE_RESUME_SESSION_DELEGATION_MS)).toThrow("expired");expect(()=>assertRebaseResumeSessionDelegation({...first,sessionDelegation:undefined},created)).toThrow("unavailable");expect(()=>assertRebaseResumeSessionDelegation({...first,sessionDelegation:{version:1,expiresAt:created+REBASE_RESUME_SESSION_DELEGATION_MS+1}},created)).toThrow("unavailable");expect(f.ledger.begin({...request,sessionExpiresAt:created+3_600_000}).sessionDelegation).toEqual(first.sessionDelegation);const token=f.ledger.begin({...input(),application:{...application,input:{...application.input,id:crypto.randomUUID()}},actor:{...actor,viaToken:true},credentialHash:"hash"});expect(token.sessionDelegation).toBeUndefined();}finally{f.db.close();}});
