import {test,expect} from 'bun:test';
import {Database} from 'bun:sqlite';
import {ReleaseAssets} from '../src/server/release-assets';
import type {ReleaseScope} from '../src/server/release-records';
function fixture(){const db=new Database(':memory:');const storage={sql:{exec(q:string,...values:(string|number)[]){const rows=db.query(q).all(...values);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;const scope:ReleaseScope={id:crypto.randomUUID(),projectId:'project',incarnation:crypto.randomUUID(),canonicalRepoName:'repo',authorId:'owner',source:{name:'v1',tagOperationId:crypto.randomUUID(),acceptedJournalId:'baseline',acceptedRef:'refs/heads/main',acceptedRootVersion:0,commit:'a'.repeat(40),tree:'b'.repeat(40)}};const objects=new Map<string,ArrayBuffer>();const bucket={async put(key:string,value:ArrayBuffer){if(!objects.has(key))objects.set(key,value.slice(0));},async get(key:string){const value=objects.get(key);return value?{arrayBuffer:async()=>value.slice(0)}:null;}} as unknown as R2Bucket;return{db,scope,objects,bucket,ledger:new ReleaseAssets(storage),storage};}
const bytes=new TextEncoder().encode('artifact').buffer;const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');
test('immutable digest verified assets survive lost ACK/restart and reject changed identity or corruption',async()=>{const f=fixture();try{const input={id:crypto.randomUUID(),name:'app.zip',sha256:sha,size:bytes.byteLength};const first=await f.ledger.upload(f.scope,input,bytes,f.bucket,()=>{},()=>{});expect(first.phase).toBe('verified');const resumed=new ReleaseAssets(f.storage);expect(await resumed.upload(f.scope,input,bytes,f.bucket,()=>{},()=>{throw Error('published');})).toEqual(first);await expect(resumed.upload(f.scope,{...input,name:'other.zip'},bytes,f.bucket,()=>{},()=>{})).rejects.toThrow('identity changed');expect((await resumed.download(f.scope,input.id,f.bucket,()=>{})).bytes).toEqual(bytes);f.objects.set(first.key,new TextEncoder().encode('tampered').buffer);await expect(resumed.download(f.scope,input.id,f.bucket,()=>{})).rejects.toThrow('verification failed');}finally{f.db.close();}});
test('pending unknown storage blocks publication, exact retry recovers and authority is checked after IO',async()=>{const f=fixture();try{const input={id:crypto.randomUUID(),name:'app.zip',sha256:sha,size:bytes.byteLength};const failed={...f.bucket,put:async()=>{throw Error('lost');}} as R2Bucket;await expect(f.ledger.upload(f.scope,input,bytes,failed,()=>{},()=>{})).rejects.toThrow('lost');expect(()=>f.ledger.assertPublishable(f.scope)).toThrow('pending');await f.ledger.upload(f.scope,input,bytes,f.bucket,()=>{},()=>{});f.ledger.assertPublishable(f.scope);await expect(f.ledger.download({...f.scope,incarnation:crypto.randomUUID()},input.id,f.bucket,()=>{})).rejects.toThrow('scope changed');await expect(f.ledger.download(f.scope,input.id,f.bucket,()=>{throw Error('revoked');})).rejects.toThrow('revoked');}finally{f.db.close();}});
test('digest and traversal validation happen before storing any object',async()=>{const f=fixture();try{const input={id:crypto.randomUUID(),name:'../app.zip',sha256:sha,size:bytes.byteLength};await expect(f.ledger.upload(f.scope,input,bytes,f.bucket,()=>{},()=>{})).rejects.toThrow();await expect(f.ledger.upload(f.scope,{...input,name:'app.zip',sha256:'0'.repeat(64)},bytes,f.bucket,()=>{},()=>{})).rejects.toThrow('digest differs');expect(f.objects.size).toBe(0);}finally{f.db.close();}});
