import {expect,test} from "bun:test";
import {renderToStaticMarkup} from "react-dom/server";
import {SavedRepositoryCreations} from "../src/web/components/SavedRepositoryCreations";
import {parseRepositoryCreations,restoreRepositoryCreation,initializedRepositoryCanOpen,type RepositoryCreationRecovery} from "../src/web/repository-creation-recovery";
const pending:RepositoryCreationRecovery={requestId:"11111111-1111-4111-8111-111111111111",kind:"repository",init:"readme",name:"my-project",description:"Original purpose",defaultBranch:"release",phase:"publication_possible",root:{head:"a".repeat(40),tree:"b".repeat(40)},published:false,nativeState:"unconfirmed",credentialState:"pending",canRestore:true,canOpenRegisteredRepository:false,canRetryOriginal:false};
const render=(record:RepositoryCreationRecovery)=>renderToStaticMarkup(<SavedRepositoryCreations records={[record]} busy={false} error={null} onRefresh={()=>{}} onRestore={()=>{}} onOpen={()=>{}} nextCursor={null} onNext={()=>{}}/>);
test("saved normal creation restores exact UUID/name/description/branch without a new allocation",()=>{expect(restoreRepositoryCreation(pending)).toEqual({kind:"repository",initialization:"readme",requestId:pending.requestId,name:pending.name,description:pending.description,defaultBranch:pending.defaultBranch});expect(initializedRepositoryCanOpen(pending)).toBe(false);const html=render(pending);expect(html).toContain("Local commit; publication unconfirmed");expect(html).toContain(pending.root!.head);expect(html).toContain("Restore original inputs");expect(html).not.toContain("Open repository");expect(html).not.toContain("Repository ready");});
test("only real ready initialization opens an actual repository, while unexpected secret fields are rejected",()=>{const ready:RepositoryCreationRecovery={...pending,phase:"ready",canOpenRegisteredRepository:true,published:true,nativeState:"stopped",credentialState:"revoked",canRetryOriginal:true,projectId:"p123456789abc"};expect(initializedRepositoryCanOpen(ready)).toBe(true);expect(render(ready)).toContain("Open repository");expect(parseRepositoryCreations({initializations:[pending],nextCursor:null}).initializations[0]?.canRetryOriginal).toBe(false);expect(()=>parseRepositoryCreations({initializations:[{...pending,projectId:ready.projectId}],nextCursor:null})).toThrow();expect(()=>parseRepositoryCreations({initializations:[{...pending,token:"private"}],nextCursor:null})).toThrow();expect(()=>parseRepositoryCreations({initializations:[{...pending,canRetryOriginal:true}],nextCursor:null})).toThrow();});

test("empty initialization restores its exact mode and opens only a confirmed cleanup-complete unborn repository",()=>{const empty:RepositoryCreationRecovery={...pending,init:"empty",phase:"ready",canOpenRegisteredRepository:true,root:undefined,published:false,nativeState:"stopped",credentialState:"revoked",projectId:"p123456789abc",canRetryOriginal:true};expect(restoreRepositoryCreation(empty).initialization).toBe("empty");expect(initializedRepositoryCanOpen(empty)).toBe(true);expect(initializedRepositoryCanOpen({...empty,nativeState:"unconfirmed"})).toBe(false);expect(initializedRepositoryCanOpen({...empty,root:pending.root})).toBe(false);const html=render(empty);expect(html).toContain("Empty repository · no initial commit");expect(html).toContain("Open repository");expect(html).not.toContain("Local commit");expect(parseRepositoryCreations({initializations:[{...empty,phase:"empty_verified",projectId:undefined,canRetryOriginal:false}],nextCursor:null}).initializations[0]?.init).toBe("empty");});

test("ledger-ready initialization requires explicit registered-repository witness to open",()=>{const unregistered:RepositoryCreationRecovery={...pending,phase:"ready",published:true,nativeState:"stopped",credentialState:"revoked",canRetryOriginal:true};expect(initializedRepositoryCanOpen(unregistered)).toBe(false);expect(render(unregistered)).toContain("registration unconfirmed");expect(render(unregistered)).toContain("Restore original inputs");expect(render(unregistered)).not.toContain("Open repository");expect(restoreRepositoryCreation(unregistered).requestId).toBe(unregistered.requestId);expect(initializedRepositoryCanOpen({...unregistered,projectId:"p123456789abc"})).toBe(false);expect(initializedRepositoryCanOpen({...unregistered,canOpenRegisteredRepository:true,projectId:"p123456789abc"})).toBe(true);});
