import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {RepositoryInitializationIntent} from '../src/server/repository-initialization-intents';
import type {FlareGitProjectState} from '../src/core/types';
test('native initialized repository requires real receipt facts and atomically rolls back project, owner, incarnation and receipt on bootstrap failure',async()=>{
 if(await workerdChild('tests/repository-initialization-native.test.ts'))return;
 const output=`/tmp/flaregit-repository-init-native-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/repository-initialization-native-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'repository-init',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'RepositoryInitializationFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('repository-init'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})}),json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body),value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 const input={kind:'repository',initialization:'readme',requestId:crypto.randomUUID(),name:'Normal repository',defaultBranch:'trunk',description:'A human requested README'},intent=await json<RepositoryInitializationIntent>('/prepare',input);expect(await json<unknown>('/prepare',input)).toEqual(intent);const status=await json<Record<string,unknown>>('/status?request='+input.requestId);expect(status).toMatchObject({requestId:input.requestId,phase:'prepared',canRetryOriginal:true,credentialState:'not_issued'});expect(Object.keys(status)).not.toContain('scope');expect(JSON.stringify(status)).not.toContain(intent.scope.authorEmail);expect(await json('/status?request='+input.requestId+'&actor=outsider')).toBeNull();expect((await call('/statuses?expired=true')).ok).toBe(false);expect(await json('/statuses')).toMatchObject({initializations:[status],nextCursor:null});expect((await call('/bootstrap?event='+intent.scope.eventId)).ok).toBe(false);const ready=await json<RepositoryInitializationIntent>('/facts?event='+intent.scope.eventId);expect(ready.phase).toBe('ready');expect(await json('/status?request='+input.requestId)).toMatchObject({phase:'ready',published:true,nativeState:'stopped',credentialState:'revoked',canOpenRegisteredRepository:false,canRetryOriginal:true});await json('/fault?event='+intent.scope.eventId+'&on=true');expect((await call('/bootstrap?event='+intent.scope.eventId)).ok).toBe(false);expect(await json('/raw?event='+intent.scope.eventId)).toMatchObject({projects:0,members:0,receipts:0});await json('/fault?event='+intent.scope.eventId+'&on=false');expect((await call('/bootstrap?event='+intent.scope.eventId+'&expired=true')).ok).toBe(false);const state=await json<FlareGitProjectState>('/bootstrap?event='+intent.scope.eventId);expect(state).toMatchObject({kind:'repository',defaultBranch:'trunk',acceptedBaseline:{commit:ready.commit!.head,tree:ready.commit!.tree},verificationPolicy:{kind:'git-integrity'},tasks:{}});expect(await json<unknown>('/bootstrap?event='+intent.scope.eventId)).toEqual(state);expect(await json('/raw?event='+intent.scope.eventId)).toMatchObject({projects:1,members:1,receipts:1});expect(await json('/register?event='+intent.scope.eventId)).toMatchObject([{id:intent.scope.projectId,kind:'repository',role:'owner'}]);expect(await json('/status?request='+input.requestId)).toMatchObject({canOpenRegisteredRepository:true,projectId:intent.scope.projectId});
 const emptyInput={...input,requestId:crypto.randomUUID(),name:'Unborn repository',initialization:'empty'},empty=await json<RepositoryInitializationIntent>('/prepare',emptyInput);expect(empty.scope).toMatchObject({initialization:'empty',readme:null,authorName:null,authorEmail:null,commitTimestamp:null});await json('/facts?event='+empty.scope.eventId);const unborn=await json<FlareGitProjectState>('/bootstrap?event='+empty.scope.eventId);expect(unborn.acceptedState).toEqual({kind:'unborn',currentCommit:null,acceptedAt:null,buildDigest:null,activeRequirements:[],history:[]});expect(unborn.acceptedBaseline).toBeUndefined();const first=await json<{before:{ok:boolean};state:FlareGitProjectState;registry:{roots:Array<{head:string;version:number}>}}>('/first-root?event='+empty.scope.eventId);expect(first.before.ok).toBe(false);expect(first.state.acceptedState).toMatchObject({kind:'committed',currentCommit:'d'.repeat(40)});expect(first.state.acceptedState.history).toHaveLength(1);expect(first.registry.roots).toMatchObject([{head:'d'.repeat(40),version:1}]);
 const failedEmpty=await json<RepositoryInitializationIntent>('/prepare',{...emptyInput,requestId:crypto.randomUUID(),name:'First root registry repair'});await json('/facts?event='+failedEmpty.scope.eventId);await json('/bootstrap?event='+failedEmpty.scope.eventId);const preserved=await json<{state:FlareGitProjectState;registry:{repairs:unknown[]}}>('/first-root?event='+failedEmpty.scope.eventId+'&failProjection=true');expect(preserved.state.acceptedState.currentCommit).toBe('d'.repeat(40));expect(preserved.state.journal[0]!.state).toBe('ACCEPTED');expect(preserved.state.acceptedState.history).toHaveLength(1);expect(preserved.registry.repairs.length).toBeGreaterThan(0);expect(await json('/restore-registry?event='+failedEmpty.scope.eventId)).toMatchObject({roots:[{head:'d'.repeat(40),version:1}],repairs:[]});
 const stackedEmpty=await json<RepositoryInitializationIntent>('/prepare',{...emptyInput,requestId:crypto.randomUUID(),name:'Stacked first root'});await json('/facts?event='+stackedEmpty.scope.eventId);await json('/bootstrap?event='+stackedEmpty.scope.eventId);const stack=await json<{dependency:boolean;childOnly:{reason:string};childBeforeParent:boolean;foreignParent:boolean;before:{ok:boolean};state:FlareGitProjectState}>('/stacked-root?event='+stackedEmpty.scope.eventId);expect(stack.dependency).toBe(true);expect(stack.childOnly.reason).toContain('not accepted');expect(stack.childBeforeParent).toBe(true);expect(stack.foreignParent).toBe(true);expect(stack.before.ok).toBe(false);expect(stack.state.acceptedState.currentCommit).toBe('f'.repeat(40));expect(stack.state.tasks['task-parent-root']!.status).toBe('accepted');expect(stack.state.tasks['task-child-root']!.baseCommit).toBe('d'.repeat(40));expect(stack.state.acceptedState.history[0]!.participatingTasks).toEqual(['task-child-root','task-parent-root']);
 const changedParent=await json<RepositoryInitializationIntent>('/prepare',{...emptyInput,requestId:crypto.randomUUID(),name:'Changed stacked dependency'});await json('/facts?event='+changedParent.scope.eventId);await json('/bootstrap?event='+changedParent.scope.eventId);const changed=await json<{dependency:boolean;rejected:boolean;state:FlareGitProjectState}>('/stacked-root?event='+changedParent.scope.eventId+'&driftParent=true');expect(changed.dependency).toBe(false);expect(changed.rejected).toBe(true);expect(changed.state.tasks['task-child-root']!.currentCommit).toBe('d'.repeat(40));expect(changed.state.acceptedState.currentCommit).toBeNull();expect(changed.state.journal).toEqual([]);
 const knownForkEmpty=await json<RepositoryInitializationIntent>('/prepare',{...emptyInput,requestId:crypto.randomUUID(),name:'Known fork retry status'});await json('/facts?event='+knownForkEmpty.scope.eventId);await json('/bootstrap?event='+knownForkEmpty.scope.eventId);const statuses=await json<{untouched:Record<string,unknown>;unknown:Record<string,unknown>;state:FlareGitProjectState}>('/known-fork-status?event='+knownForkEmpty.scope.eventId);expect(statuses.untouched).toMatchObject({phase:'dispatching',providerAcknowledgementKnown:true,credentialState:'revoked',canRetryOriginal:true,hasTask:false,capturedTarget:{ref:'refs/heads/trunk',acceptedCommit:null,acceptedVersion:0}});expect((statuses.untouched.input as {expectedTarget?:unknown}).expectedTarget).toBeUndefined();expect(statuses.unknown).toMatchObject({credentialState:'issuance_unknown',canRetryOriginal:false,hasTask:false});expect(statuses.state.tasks).toEqual({});expect(statuses.state.acceptedState.currentCommit).toBeNull();
 }finally{await mf.dispose();}
},30000);
