import {expect,test} from "bun:test";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {generateKeyPair,exportJWK,SignJWT} from "jose";
import {workerdChild} from "./support/workerd-child";
import {accountKeyFor} from "../src/server/projects";
import type {ReportRow} from "../src/server/durable-object";

test("native report HTTP and SQL preserve oldest backlog, immutable operator attribution and idempotent closure",async()=>{
  if(await workerdChild("tests/reports-accountability.test.ts"))return;
  const pair=await generateKeyPair("RS256"),jwk={...await exportJWK(pair.publicKey),kid:"reports-fixture",alg:"RS256",use:"sig"};
  const issuer=Bun.serve({hostname:"127.0.0.1",port:0,fetch:()=>Response.json({keys:[jwk]})});
  const file=`/tmp/flaregit-reports-${crypto.randomUUID()}.js`;
  const build=Bun.spawn([process.execPath,"build","tests/support/reports-accountability-worker.ts","--target=browser","--external=cloudflare:workers","--external=node:*",`--outfile=${file}`],{stdout:"ignore",stderr:"pipe"});
  const[error,code]=await Promise.all([new Response(build.stderr).text(),build.exited]);if(code!==0){issuer.stop(true);throw new Error(error);}
  const script=await Bun.file(file).text();await Bun.file(file).delete();
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"reports-api",unsafeDirectSockets:[{host:"127.0.0.1"}],modules:true,script,compatibilityDate:"2026-10-02",compatibilityFlags:["nodejs_compat"],bindings:{FIXTURE_ISSUER:issuer.url.origin},durableObjects:{TEST:{className:"ReportsRepository",useSQLite:true}}}]}));
  const directUrl=await mf.unsafeGetDirectURL("reports-api");
  const call=(path:string,method="GET",body?:unknown,token?:string)=>fetch(new URL(path,directUrl),{method,headers:{Connection:"close","CF-Connecting-IP":"198.51.100.25",...(token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const session=(subject:string)=>new SignJWT({azp:"https://fixture.example"}).setProtectedHeader({alg:"RS256",kid:jwk.kid}).setIssuer(issuer.url.origin).setSubject(subject).setIssuedAt().setExpirationTime("5m").sign(pair.privateKey);
  try{
    const tokens=await(await call("/fixture/bootstrap")).json() as Record<string,string>;
    const [one,two,outsider]=await Promise.all([session("operator-one"),session("operator-two"),session("outsider")]);
    expect((await call("/api/operator/reports")).status).toBe(401);
    expect((await call("/api/operator/reports","GET",undefined,tokens["operator-one"])).status).toBe(404);
    expect((await call("/api/operator/reports","GET",undefined,outsider)).status).toBe(404);
    const page = async (path:string, token:string) => await(await call(path,"GET",undefined,token)).json() as {reports:ReportRow[];nextCursor:string|null};
    expect((await call("/api/operator/reports?cursor=a&cursor=b","GET",undefined,one)).status).toBe(400);
    expect((await call("/api/reports?cursor="+"a".repeat(1001),"GET",undefined,tokens.reporter)).status).toBe(400);
    const queue=await page("/api/operator/reports",one);
    expect(queue.reports).toHaveLength(100);expect(queue.reports[0]?.id).toBe("rpt_seed-000");expect(queue.reports.at(-1)?.id).toBe("rpt_seed-099");
    const second=await page(`/api/operator/reports?cursor=${encodeURIComponent(queue.nextCursor!)}`,one);
    const third=await page(`/api/operator/reports?cursor=${encodeURIComponent(second.nextCursor!)}`,one);
    expect(second.reports[0]?.id).toBe("rpt_seed-100");expect(third.reports).toHaveLength(5);expect(third.nextCursor).toBeNull();
    expect(new Set([...queue.reports,...second.reports,...third.reports].map(row=>row.id)).size).toBe(205);
    const own=await page("/api/reports",tokens.reporter!);
    expect(own.reports.every(row => !("publication_target" in row))).toBe(true);expect(own.reports).toHaveLength(100);expect(own.reports[0]?.id).toBe("rpt_seed-204");
    const ownSecond=await page(`/api/reports?cursor=${encodeURIComponent(own.nextCursor!)}`,tokens.reporter!);
    expect(ownSecond.reports[0]?.id).toBe("rpt_seed-104");
    expect(await page("/api/reports",tokens.outsider!)).toEqual({reports:[],nextCursor:null});
    expect((await call(`/api/operator/reports?status=resolved&cursor=${encodeURIComponent(queue.nextCursor!)}`,"GET",undefined,one)).ok).toBe(false);
    expect((await call(`/api/reports?cursor=${encodeURIComponent(own.nextCursor!)}`,"GET",undefined,tokens.outsider)).ok).toBe(false);
    const route="/api/operator/reports/rpt_seed-000/resolve";
    expect((await call(route,"POST",{resolution:"Forged token closure"},tokens["operator-one"])).status).toBe(404);
    expect((await call(route,"POST",{resolution:"Forged outsider closure",operatorAccountKey:await accountKeyFor("operator-one")},outsider)).status).toBe(404);
    const competing=await Promise.all([call(route,"POST",{resolution:"First operator decision",expectedStatus:"open"},one),call(route,"POST",{resolution:"Second operator decision",expectedStatus:"open"},two)]);
    expect(competing.map(response=>response.status).sort()).toEqual([200,409]);
    const winnerIndex=competing.findIndex(response=>response.status===200),winner=await competing[winnerIndex]!.json() as ReportRow;
    const winnerSubject=winnerIndex===0?"operator-one":"operator-two",winnerToken=winnerIndex===0?one:two;
    expect(winner.resolved_by).toBe(await accountKeyFor(winnerSubject));expect(winner.resolved_at).toBeTruthy();
    await call("/fixture/rename","POST",{userId:winnerSubject});
    const retried=await call(route,"POST",{resolution:winner.resolution,expectedStatus:"open"},winnerToken);expect(retried.status).toBe(200);expect(await retried.json() as ReportRow).toEqual(winner);
    expect((await call(route,"POST",{resolution:"Changed decision"},winnerToken)).status).toBe(409);
    expect((await call(route,"POST",{resolution:winner.resolution},winnerIndex===0?two:one)).status).toBe(409);
    const resolved=await page("/api/operator/reports?status=resolved",one);expect(resolved.reports.find(row=>row.id===winner.id)).toEqual(winner);
    expect((await call("/api/operator/reports/rpt_unknown/resolve","POST",{resolution:"Unknown report"},one)).status).toBe(404);
    await call("/fixture/profile-target");
    const filedResponse=await call("/api/reports","POST",{kind:"impersonation",target:"/#/profile/reported-handle",details:"Original profile impersonation requires review"},tokens.reporter);expect(filedResponse.status).toBe(201);
    const filed=await filedResponse.json() as {id:string};await call("/fixture/reassign-handle");
    const publicationRoute=`/api/operator/reports/${filed.id}/publication`;
    const publication=await(await call(publicationRoute,"GET",undefined,one)).json() as {target:{kind:string;targetId:string;accountKey:string};state:{version:number};history:unknown[]};
    expect(publication.target).toEqual({kind:"profile",targetId:"original-profile-owner",accountKey:await accountKeyFor("original-profile-owner")});expect(publication.state.version).toBe(0);
    const moderation={action:"suppress",confirmed:true,reason:"Reviewed profile impersonation",reportId:filed.id,expectedVersion:0,idempotencyKey:"profile-decision-key",confirmedTarget:"profile:original-profile-owner"};
    expect((await call(publicationRoute,"POST",moderation,tokens["operator-one"])).status).toBe(404);
    expect((await call(publicationRoute,"POST",moderation,outsider)).status).toBe(404);
    expect((await call(publicationRoute,"POST",{...moderation,confirmedTarget:"profile:replacement-profile-owner"},one)).status).toBe(400);
    const appliedResponse=await call(publicationRoute,"POST",moderation,one);expect(appliedResponse.status).toBe(200);const applied=await appliedResponse.json() as Record<string,unknown>;
    const repeated=await call(publicationRoute,"POST",moderation,one);expect(repeated.status).toBe(200);expect(await repeated.json() as Record<string,unknown>).toEqual(applied);
    expect((await call(publicationRoute,"POST",{...moderation,idempotencyKey:"stale-profile-decision"},two)).status).toBe(409);
    const reporterPage=await page("/api/reports",tokens.reporter!);const reporterRecord=reporterPage.reports.find(row=>row.id===filed.id);expect(reporterRecord).toBeTruthy();expect(reporterRecord).not.toHaveProperty("publication_target");expect(JSON.stringify(reporterRecord)).not.toContain("original-profile-owner");expect(JSON.stringify(reporterRecord)).not.toContain(await accountKeyFor("original-profile-owner"));
  }finally{await mf.dispose();issuer.stop(true);}
},30000);
