import {test,expect} from "bun:test";
import {openRepositoryRead,RepositoryReadError,type RepositoryReadCapability,type RepositoryReadOptions} from "../src/server/repository-read-budget.js";
const hash=(n:number)=>n.toString(16).padStart(40,"0");
const commit=(value:string):ArtifactsCommitMetadata=>({hash:value,treeHash:hash(2),parents:[],message:"commit",author:{name:"Author",email:"author@example.invalid"},committer:{name:"Author",email:"author@example.invalid"},authoredAt:1,committedAt:1});
function fixture(){const calls={get:0,tree:0,commit:0,log:0,dispose:0},groups:string[]=[];let active=true;const raw:RepositoryReadCapability={info:async()=>({id:"repo",name:"repo",description:null,defaultBranch:"main",createdAt:"2026-10-03",updatedAt:"2026-10-03",lastPushAt:null,source:null,readOnly:false,remote:"https://provider.invalid/repo"}),log:async()=>{calls.log++;return[commit(hash(1))];},readCommit:async value=>{calls.commit++;return commit(value);},readTree:async()=>{calls.tree++;return[{name:"file.ts",hash:hash(3),mode:"100644",type:"blob"}];},readBlob:async()=>new Blob(["contents"]),readFile:async()=>new Blob(["contents"]),[Symbol.dispose]:()=>{calls.dispose++;}};const env={ARTIFACTS:{get:async()=>{calls.get++;return raw;}}};const options:RepositoryReadOptions={repoName:"repo",authorize:async()=>{if(!active)throw new RepositoryReadError(503,"authorization");},reserveGroup:async id=>{groups.push(id);return{allowed:true,existing:false,basis:"conservative_operation_envelope"};}};return{calls,groups,raw,env,options,revoke:()=>{active=false;}};}
test("actual get and provider attempts reserve fresh eight-call groups",async()=>{const f=fixture();using reader=await openRepositoryRead(f.env,f.options);for(let i=1;i<=15;i++)await reader.readCommit(hash(i));expect(f.calls.get).toBe(1);expect(f.calls.commit).toBe(15);expect(f.groups).toHaveLength(2);expect(new Set(f.groups).size).toBe(2);});
test("immutable request memo deduplicates concurrent reads and doesn't cache branch logs or authority",async()=>{const f=fixture();using reader=await openRepositoryRead(f.env,f.options);const [first]=await Promise.all([reader.readTree(hash(1)),reader.readTree(hash(1))]);first![0]!.name="changed";expect((await reader.readTree(hash(1)))![0]!.name).toBe("file.ts");expect(f.calls.tree).toBe(1);await reader.log({ref:"main"});await reader.log({ref:"main"});expect(f.calls.log).toBe(2);f.revoke();await expect(reader.readTree(hash(1))).rejects.toMatchObject({reason:"authorization"});expect(f.calls.tree).toBe(1);});
test("quota refusal precedes capability lookup and call bound precedes further SDK reads",async()=>{const f=fixture();await expect(openRepositoryRead(f.env,{...f.options,reserveGroup:async()=>({allowed:false,reason:"global_budget"})})).rejects.toMatchObject({status:429,reason:"global_budget"});expect(f.calls.get).toBe(0);using reader=await openRepositoryRead(f.env,{...f.options,limits:{maxProviderCalls:2}});await reader.readTree(hash(1));await expect(reader.readTree(hash(2))).rejects.toMatchObject({status:413,reason:"provider_limit"});expect(f.calls.tree).toBe(1);});
test("cache hits recheck blob-body authorization and cumulative materialization bound",async()=>{const f=fixture();using reader=await openRepositoryRead(f.env,{...f.options,limits:{maxBlobBytes:8}});const blob=await reader.readBlob(hash(1));expect(await blob!.text()).toBe("contents");await expect(blob!.arrayBuffer()).rejects.toMatchObject({status:413,reason:"blob_capacity"});f.revoke();await expect(blob!.text()).rejects.toMatchObject({reason:"authorization"});});
test("deadline disposes a capability that arrives after timeout",async()=>{const f=fixture();let resolve:((repo:RepositoryReadCapability)=>void)|undefined;const env={ARTIFACTS:{get:()=>new Promise<RepositoryReadCapability>(done=>{resolve=done;})}};const pending=openRepositoryRead(env,{...f.options,limits:{deadlineMs:20}});await expect(pending).rejects.toMatchObject({status:503,reason:"deadline"});resolve!(f.raw);await new Promise(done=>setTimeout(done,5));expect(f.calls.dispose).toBe(1);});
test("post-provider authorization failure disposes the obtained capability",async()=>{const f=fixture();const env={ARTIFACTS:{get:async()=>{f.revoke();return f.raw;}}};await expect(openRepositoryRead(env,f.options)).rejects.toMatchObject({reason:"authorization"});expect(f.calls.dispose).toBe(1);});
test("metadata bound returns explicit incomplete-inspection failure",async()=>{const f=fixture();using reader=await openRepositoryRead(f.env,{...f.options,limits:{maxMetadataBytes:20}});await expect(reader.readCommit(hash(1))).rejects.toMatchObject({reason:"metadata_capacity",status:413});});
test("large blobs retain size for existing truthful truncated-file handling",async()=>{const f=fixture();f.raw.readBlob=async()=>new Blob([new Uint8Array(5*1024*1024)]);using reader=await openRepositoryRead(f.env,f.options);expect((await reader.readBlob(hash(1)))?.size).toBe(5*1024*1024);});
test("configured diff work envelope is accepted without raising ordinary defaults",async()=>{const f=fixture();using reader=await openRepositoryRead(f.env,{...f.options,limits:{maxProviderCalls:10016,deadlineMs:120000}});await reader.readTree(hash(1));expect(f.calls.tree).toBe(1);});

test("cache miss keeps three authority fences while hits use exactly two",async()=>{const f=fixture();let checks=0;using reader=await openRepositoryRead(f.env,{...f.options,authorize:async()=>{checks++;await f.options.authorize();}});expect(checks).toBe(3);await reader.readTree(hash(1));expect(checks).toBe(6);await reader.readTree(hash(1));expect(checks).toBe(8);f.revoke();await expect(reader.readTree(hash(1))).rejects.toMatchObject({reason:"authorization"});expect(f.calls.tree).toBe(1);});
