import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {RepositoryInitializationIntent} from '../src/server/repository-initialization-intents';
import type {FlareGitProjectState} from '../src/core/types';
test('native initialized repository requires real receipt facts and atomically rolls back project, owner, incarnation and receipt on bootstrap failure',async()=>{
 if(await workerdChild('tests/repository-initialization-native.test.ts'))return;
 const output=`/tmp/flaregit-repository-init-native-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/repository-initialization-native-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'repository-init',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'RepositoryInitializationFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('repository-init'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})}),json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body),value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 const input={kind:'repository',initialization:'readme',requestId:crypto.randomUUID(),name:'Normal repository',defaultBranch:'trunk',description:'A human requested README'},intent=await json<RepositoryInitializationIntent>('/prepare',input);expect(await json<unknown>('/prepare',input)).toEqual(intent);expect((await call('/bootstrap?event='+intent.scope.eventId)).ok).toBe(false);const ready=await json<RepositoryInitializationIntent>('/facts?event='+intent.scope.eventId);expect(ready.phase).toBe('ready');await json('/fault?event='+intent.scope.eventId+'&on=true');expect((await call('/bootstrap?event='+intent.scope.eventId)).ok).toBe(false);expect(await json('/raw?event='+intent.scope.eventId)).toMatchObject({projects:0,members:0,receipts:0});await json('/fault?event='+intent.scope.eventId+'&on=false');expect((await call('/bootstrap?event='+intent.scope.eventId+'&expired=true')).ok).toBe(false);const state=await json<FlareGitProjectState>('/bootstrap?event='+intent.scope.eventId);expect(state).toMatchObject({kind:'repository',defaultBranch:'trunk',acceptedBaseline:{commit:ready.commit!.head,tree:ready.commit!.tree},verificationPolicy:{kind:'git-integrity'},tasks:{}});expect(await json<unknown>('/bootstrap?event='+intent.scope.eventId)).toEqual(state);expect(await json('/raw?event='+intent.scope.eventId)).toMatchObject({projects:1,members:1,receipts:1});expect(await json('/register?event='+intent.scope.eventId)).toMatchObject([{id:intent.scope.projectId,kind:'repository',role:'owner'}]);
 }finally{await mf.dispose();}
},30000);
