import {expect,test}from"bun:test";import{Miniflare,convertV4MiniflareOptions}from"miniflare";import{workerdChild}from"./support/workerd-child";import type{DiscussionEntry}from"../src/server/repository-discussions";
test("actual repository discussion HTTP/RPC isolates private records and binds signed scopes and CAS",async()=>{
 if(await workerdChild("tests/repository-discussions-api.test.ts"))return;const file=`/tmp/discussion-api-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,"build","tests/support/repository-discussions-api-worker.ts","--target=browser","--external=cloudflare:workers","--external=node:*",`--outfile=${file}`],{stdout:"ignore",stderr:"pipe"});const[error,code]=await Promise.all([new Response(build.stderr).text(),build.exited]);if(code)throw new Error(error);const script=await Bun.file(file).text();await Bun.file(file).delete();const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"discussion-api",modules:true,script,compatibilityDate:"2026-10-02",compatibilityFlags:["nodejs_compat"],durableObjects:{TEST:{className:"DiscussionApiRepository",useSQLite:true}}}]}));
 const call=async(path:string,method="GET",body?:unknown,token?:string,withIP=true)=>(await mf.getWorker("discussion-api")).fetch(`http://test${path}`,{method,headers:{...(withIP?{"CF-Connecting-IP":"198.51.100.40"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
 try{const tokens=await(await call("/fixture/bootstrap")).json() as Record<string,string>,owner=tokens["discussion-owner-full"],member=tokens["discussion-member-full"],outsider=tokens["discussion-outsider-full"],publicPath="/api/public/pabcdef123456/discussions",privatePath="/api/p/pabcdef123456/discussions";const input={category:"general",title:"Owned public topic",body:"Public discussion fixture",idempotencyKey:"discussion-api-123",confirmed:true};
 expect((await call(publicPath)).status).toBe(404);await call("/fixture/prepare?public=false");expect((await call(publicPath)).status).toBe(404);expect((await call(publicPath,"GET",undefined,undefined,false)).status).toBe(503);
 const privatePost=await(await call(privatePath,"POST",{...input,title:"Private discussion",body:"Never expose this private discussion",idempotencyKey:"private-discussion-123"},member)).json() as DiscussionEntry;expect(privatePost.id).toMatch(/^discussion_/);expect((await call(privatePath,"GET",undefined,outsider)).status).toBe(404);expect((await call(privatePath,"POST",input,outsider)).status).toBe(404);
 await call("/fixture/prepare");const publicText=await(await call(publicPath)).text();expect(publicText).not.toContain(privatePost.body);expect(publicText).not.toContain(privatePost.id);
 expect((await call(publicPath,"POST",{...input,confirmed:"true"},outsider)).status).toBe(409);expect((await call(publicPath,"POST",{...input,author:"Spoofed author"},outsider)).status).toBe(409);expect((await call(publicPath,"POST",input,tokens["discussion-outsider-read"])).status).toBe(403);
 const post=await(await call(publicPath,"POST",input,outsider)).json() as DiscussionEntry;expect(post.author).toBe("Verified outsider");expect((await call(publicPath,"POST",{...input,idempotencyKey:"pinned-post-123"},tokens["discussion-member-full-pinned"])).status).toBe(201);
 expect((await call(`${publicPath}/${post.id}/control`,"POST",{expectedVersion:1,locked:true},outsider)).status).toBe(409);expect((await call(`${publicPath}/${post.id}/control`,"POST",{expectedVersion:1,resolved:true},outsider)).status).toBe(200);expect((await call(`${publicPath}/${post.id}/control`,"POST",{expectedVersion:1,locked:true},owner)).status).toBe(409);const savedReplyInput={body:"Saved reply before lock",idempotencyKey:"saved-reply-before-lock",confirmed:true};const savedReply=await(await call(`${publicPath}/${post.id}/replies`,"POST",savedReplyInput,member)).json() as DiscussionEntry;expect(savedReply.id).toMatch(/^discussion_/);expect((await call(`${publicPath}/${post.id}/control`,"POST",{expectedVersion:2,locked:true},owner)).status).toBe(200);expect((await(await call(`${publicPath}/${post.id}/replies`,"POST",savedReplyInput,member)).json() as DiscussionEntry).id).toBe(savedReply.id);expect((await call(`${publicPath}/${post.id}/replies`,"POST",{body:"Locked reply",idempotencyKey:"locked-reply-123",confirmed:true},member)).status).toBe(409);
 expect((await call(`${publicPath}/${post.id}/control`,"POST",{expectedVersion:3,locked:false},tokens["discussion-owner-write"])).status).toBe(403);
 expect((await call(publicPath,"POST",{...input,category:"announcements",idempotencyKey:"write-announcement-123"},tokens["discussion-owner-write"])).status).toBe(403);
 expect((await call(`${privatePath}/settings`,"PUT",{enabled:false,confirmed:true},tokens["discussion-owner-write"])).status).toBe(403);
 await call("/fixture/race?mode=head");const changedHead=await call(publicPath);expect(changedHead.status).toBe(409);expect(await changedHead.text()).not.toContain(post.body);await call("/fixture/race?mode=version");const revoked=await call(publicPath);expect(revoked.status).toBe(409);expect(await revoked.text()).not.toContain(post.body);
 }finally{await mf.dispose();}
},30000);
