import {expect,test} from "bun:test";
import {renderToStaticMarkup} from "react-dom/server";
import {repositoryCreationRequest} from "../src/web/repository-creation-request";
import {RepositoryInitializationFields} from "../src/web/components/RepositoryInitializationFields";
test("ordinary repository creation requests genuine README initialization and preserves UUID/content on unknown ACK",()=>{let ids=0;const fields={name:"my-project",defaultBranch:"release",description:"Actual project"},first=repositoryCreationRequest(null,fields,()=>{ids++;return crypto.randomUUID();});expect(first).toMatchObject({kind:"repository",initialization:"readme",name:fields.name,defaultBranch:fields.defaultBranch,description:fields.description});expect(repositoryCreationRequest(first,fields,()=>{throw Error("Must preserve original identity");})).toBe(first);expect(ids).toBe(1);expect(()=>repositoryCreationRequest(first,{...fields,name:"different"},()=>crypto.randomUUID())).toThrow("saved repository request differs");expect(JSON.stringify(first)).not.toContain("demo");});
test("normal initialization UI offers both modes without claiming application verification",()=>{const html=renderToStaticMarkup(<RepositoryInitializationFields description="Description" defaultBranch="main" disabled={false} onDescription={()=>{}} onBranch={()=>{}}/>);expect(html).toContain("Default branch");expect(html).toContain("README");expect(html).toContain("first Git commit");expect(html).not.toContain("data-disabled");expect(html).toContain("Application behavior checks are not configured");expect(html).toContain("repository settings");expect(html).not.toContain("ticket");});
test("invalid local branch/name cannot become an unknown allocated request",()=>{expect(()=>repositoryCreationRequest(null,{name:"",defaultBranch:"main",description:""},()=>crypto.randomUUID())).toThrow();expect(()=>repositoryCreationRequest(null,{name:"project",defaultBranch:"refs/heads/main",description:""},()=>crypto.randomUUID())).toThrow();});

test("explicit empty choice freezes original UUID and remains distinct from README on retry",()=>{const fields={name:"empty-project",defaultBranch:"trunk",description:"",initialization:"empty" as const},body=repositoryCreationRequest(null,fields,()=>crypto.randomUUID());expect(body.initialization).toBe("empty");expect(repositoryCreationRequest(body,fields,()=>{throw Error("No reallocation");})).toBe(body);expect(()=>repositoryCreationRequest(body,{...fields,initialization:"readme"},()=>crypto.randomUUID())).toThrow();const html=renderToStaticMarkup(<RepositoryInitializationFields description="" defaultBranch="trunk" disabled={false} initialization="empty" allowEmpty onDescription={()=>{}} onBranch={()=>{}}/>);expect(html).toContain("Starts with no commits or files");expect(html).toContain("after review");expect(html).not.toContain("data-disabled");});
