import {test,expect}from'bun:test';
import {dispatchRepoVersionWrite,RepoVersionPersistenceError,repoTagIntent,readRepoVersionRecovery,saveRepoVersionRecovery}from'../src/web/repository-releases';
const projectId='p123456789abc',identity='owner:session',target={journalId:'baseline',acceptedRef:'refs/heads/main',acceptedRootVersion:0,commit:'a'.repeat(40),tree:'b'.repeat(40)};
test('unavailable storage prevents remote write and recovery retains original tag identity',async()=>{const values=new Map<string,string>();let unavailable=true,posts=0;const storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{if(unavailable)throw Error('quota');values.set(key,value);},removeItem:(key:string)=>{values.delete(key);}};const intent=repoTagIntent(null,'v1.0.0',target),recovery={tagIntent:intent,editor:null,releaseIntent:null},persist=()=>saveRepoVersionRecovery(storage,identity,projectId,recovery),write=async()=>{posts++;return intent.requestId;};await expect(dispatchRepoVersionWrite(persist,write)).rejects.toBeInstanceOf(RepoVersionPersistenceError);expect(posts).toBe(0);expect(intent.name).toBe('v1.0.0');unavailable=false;expect(await dispatchRepoVersionWrite(persist,write)).toBe(intent.requestId);expect(posts).toBe(1);expect(readRepoVersionRecovery(storage,identity,projectId)?.tagIntent?.requestId).toBe(intent.requestId);expect(readRepoVersionRecovery(storage,'different-owner',projectId)).toBeNull();});
test('lost response leaves original release notes and write IDs recoverable across reload',async()=>{const values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);},removeItem:(key:string)=>{values.delete(key);}},operation={operationId:crypto.randomUUID(),name:'v1.0.0',sourceCommit:target.commit,sourceTree:target.tree,phase:'confirmed' as const,createdAt:1,cleanup:'not_reported' as const,acceptedJournalId:'baseline',acceptedRef:target.acceptedRef,acceptedRootVersion:0,nativeStopped:true,credentialsComplete:true,providerVerified:true,recovery:'none' as const,observation:{object:target.commit,commit:target.commit,tree:target.tree,type:'commit' as const}},editor={release:null,operation,title:'First release',notes:'Original human notes'},intent={id:crypto.randomUUID(),editId:crypto.randomUUID(),signature:'original'},recovery={tagIntent:null,editor,releaseIntent:intent};let posts=0;await expect(dispatchRepoVersionWrite(()=>saveRepoVersionRecovery(storage,identity,projectId,recovery),async()=>{posts++;throw Error('lost response');})).rejects.toThrow('lost response');expect(posts).toBe(1);const restored=readRepoVersionRecovery(storage,identity,projectId)!;expect(restored.editor?.notes).toBe(editor.notes);expect(restored.releaseIntent).toEqual(intent);expect(await dispatchRepoVersionWrite(()=>saveRepoVersionRecovery(storage,identity,projectId,restored),async()=>{posts++;return restored.releaseIntent!.id;})).toBe(intent.id);expect(posts).toBe(2);});
test('silent lost or altered storage writes cannot dispatch a tag and failed removal is not saved',async()=>{
 const intent=repoTagIntent(null,'v1.0.0',target),value={tagIntent:intent,editor:null,releaseIntent:null};let posts=0;
 for(const saved of [null,'altered']){const storage={getItem:()=>saved,setItem:()=>{},removeItem:()=>{}};await expect(dispatchRepoVersionWrite(()=>saveRepoVersionRecovery(storage,identity,projectId,value),async()=>{posts++;})).rejects.toBeInstanceOf(RepoVersionPersistenceError);}
 expect(posts).toBe(0);
 expect(saveRepoVersionRecovery({getItem:()=>JSON.stringify(value),setItem:()=>{},removeItem:()=>{}},identity,projectId,{tagIntent:null,editor:null,releaseIntent:null})).toBe(false);
});
