import {test,expect} from "bun:test";
import {Database} from "bun:sqlite";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {RestrictedAgentAuthority,type RestrictedAgentCurrent} from "../src/server/restricted-agent-authority";
import type {AgentNativeAttemptIdentity} from "../src/server/agent-runtime-ledger";
import type {AgentExecutionEgressScope} from "../src/server/agent-execution-egress";
function store(db:Database){return{sql:{exec(query:string,...args:Array<string|number>){const rows=db.query(query).all(...args);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;}
function context(){const attempt:AgentNativeAttemptIdentity={attemptId:crypto.randomUUID(),nativeId:crypto.randomUUID(),projectId:"project",incarnation:crypto.randomUUID(),workflowId:"workflow",runId:"run",taskId:"task",actorId:"owner",accountKey:"account",phase:"apply",generation:0,snapshotDigest:"a".repeat(64)},scope:AgentExecutionEgressScope={projectId:attempt.projectId,incarnation:attempt.incarnation,workflowId:attempt.workflowId,runId:attempt.runId,taskId:attempt.taskId,actorId:attempt.actorId,accountKey:attempt.accountKey,branchGeneration:0,canonicalRepoName:"canonical",forkRepoName:"fork",remote:`https://${"a".repeat(32)}.artifacts.cloudflare.net/fork.git`,branch:"task/working",expectedTip:"b".repeat(40),access:"read"},current:RestrictedAgentCurrent={attempt,scope,taskSnapshotDigest:attempt.snapshotDigest,runGeneration:0,claim:null,remoteObservation:null,actorState:"active",accountState:"active",taskState:"active",runtimeState:"possible"};return{attempt,scope,current};}
function claimed(value:ReturnType<typeof context>,tip:string|null=null){value.current.runGeneration=1;value.current.claim={runId:value.attempt.runId,taskId:value.attempt.taskId,workflowId:value.attempt.workflowId,generation:1,snapshotDigest:value.attempt.snapshotDigest,branchGeneration:value.scope.branchGeneration,forkRepoName:value.scope.forkRepoName,branch:value.scope.branch,startingBranchHead:tip};value.current.remoteObservation={observationId:crypto.randomUUID(),projectId:value.attempt.projectId,incarnation:value.attempt.incarnation,forkRepoName:value.scope.forkRepoName,ref:`refs/heads/${value.scope.branch}`,tip};return{...value.scope,access:"write" as const,expectedTip:tip};}
test("same-run generation claim and native write-tip transition persist across SQLite reopen",async()=>{const root=await mkdtemp(join(tmpdir(),"restricted-agent-")),file=join(root,"ledger.sqlite"),v=context();let db=new Database(file);const callbacks={current:async()=>structuredClone(v.current),assertLocal:()=>{}};try{let ledger=new RestrictedAgentAuthority(store(db),callbacks);await ledger.bind(v.attempt,v.scope);const write=claimed(v);const result=await ledger.authorize(v.attempt,write);expect(result.claimTransition).toMatchObject({fromGeneration:0,toGeneration:1,claim:{runId:"run",startingBranchHead:null}});expect(result.writeBinding?.scope.expectedTip).toBeNull();db.close();db=new Database(file);ledger=new RestrictedAgentAuthority(store(db),callbacks);expect(await ledger.authorize(v.attempt,write)).toEqual(result);expect((await ledger.authorize(v.attempt,v.scope)).claimTransition).toEqual(result.claimTransition);expect((await ledger.bind(v.attempt,v.scope)).claimTransition).toEqual(result.claimTransition);v.current.actorState="revoked";await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("authority changed");expect(ledger.cleanup(v.attempt,v.scope)).toEqual(result);expect(ledger.cleanup(v.attempt,write)).toEqual(result);expect(()=>ledger.cleanup({...v.attempt,nativeId:crypto.randomUUID()},write)).toThrow("identity changed");}finally{db.close();await rm(root,{recursive:true,force:true});}});
test("other-run claims, generation jumps and changed task scope never gain transfer authority",async()=>{const db=new Database(":memory:"),v=context(),ledger=new RestrictedAgentAuthority(store(db),{current:async()=>structuredClone(v.current),assertLocal:()=>{}});try{await ledger.bind(v.attempt,v.scope);const write=claimed(v);v.current.claim!.runId="other-run";await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("Another run");v.current.claim!.runId=v.attempt.runId;v.current.runGeneration=2;await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("generation");v.current.runGeneration=1;v.current.taskSnapshotDigest="c".repeat(64);await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("authority changed");v.current.taskSnapshotDigest=v.attempt.snapshotDigest;v.current.scope.branchGeneration=1;await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("authority changed");expect(db.query("SELECT json_extract(doc,'$.claimTransition') AS claim FROM restricted_agent_authority").get()).toEqual({claim:null});}finally{db.close();}});
test("a fresh different remote head cannot overwrite the original recorded claim lease",async()=>{const db=new Database(":memory:"),v=context(),ledger=new RestrictedAgentAuthority(store(db),{current:async()=>structuredClone(v.current),assertLocal:()=>{}});try{await ledger.bind(v.attempt,v.scope);const write=claimed(v);v.current.remoteObservation!.tip="d".repeat(40);await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("observation differs");await expect(ledger.authorize(v.attempt,{...write,expectedTip:v.current.remoteObservation!.tip})).rejects.toThrow("claim does not authorize");v.current.remoteObservation!.tip=null;const original=await ledger.authorize(v.attempt,write);v.current.remoteObservation!.observationId=crypto.randomUUID();expect((await ledger.authorize(v.attempt,write)).writeBinding).toEqual(original.writeBinding);v.current.runGeneration=0;await expect(ledger.authorize(v.attempt,v.scope)).rejects.toThrow("regress");}finally{db.close();}});
test("local revocation during awaited current observation rolls back and account retirement still permits original cleanup",async()=>{const db=new Database(":memory:"),v=context();let local=true;const callbacks={current:async()=>structuredClone(v.current),assertLocal:()=>{if(!local)throw Error("local revoked");}},ledger=new RestrictedAgentAuthority(store(db),callbacks);try{const bound=await ledger.bind(v.attempt,v.scope),write=claimed(v);callbacks.current=async()=>{local=false;return structuredClone(v.current);};await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("local revoked");v.current.accountState="retired";expect(ledger.cleanup(v.attempt,v.scope)).toEqual(bound);local=true;callbacks.current=async()=>structuredClone(v.current);await expect(ledger.authorize(v.attempt,write)).rejects.toThrow("authority changed");}finally{db.close();}});
test("restricted authority timeout cannot create an initial binding",async()=>{const db=new Database(":memory:"),v=context();try{const ledger=new RestrictedAgentAuthority(store(db),{current:()=>new Promise(()=>{}),assertLocal:()=>{},timeoutMs:10});await expect(ledger.bind(v.attempt,v.scope)).rejects.toThrow("deadline");expect(db.query("SELECT COUNT(*) AS n FROM restricted_agent_authority").get()).toEqual({n:0});}finally{db.close();}});
test("post-push identity checks preserve ownership without treating a historical head as a fresh transfer lease",async()=>{const db=new Database(":memory:"),v=context(),ledger=new RestrictedAgentAuthority(store(db),{current:async()=>structuredClone(v.current),assertLocal:()=>{}});try{await ledger.bind(v.attempt,v.scope);const write=claimed(v);await expect(ledger.authorize(v.attempt,write,"identity")).rejects.toThrow("cannot create write authority");expect(ledger.originalOwnership(v.attempt)?.writeBinding).toBeNull();const original=await ledger.authorize(v.attempt,write);v.current.remoteObservation!.tip="e".repeat(40);expect(await ledger.authorize(v.attempt,write,"identity")).toEqual(original);await expect(ledger.authorize(v.attempt,write,"transfer")).rejects.toThrow("observation differs");expect(ledger.originalOwnership(v.attempt)?.writeBinding?.observation.tip).toBeNull();v.current.actorState="revoked";await expect(ledger.authorize(v.attempt,write,"identity")).rejects.toThrow("authority changed");expect(ledger.cleanup(v.attempt,write)).toEqual(original);}finally{db.close();}});
