import {Database} from 'bun:sqlite';
import {test,expect} from 'bun:test';
import {RetainedCleanupPrepayments} from '../src/server/retained-cleanup-prepayment';
import {CoreGitOperationLedger} from '../src/server/core-git-budget';
import type {RetainedInput} from '../src/server/retained-inputs';
function fixture(){const db=new Database(':memory:'),storage={sql:{exec(query:string,...args:(string|number)[]){const rows=db.query(query).all(...args);return{toArray:()=>rows};}},transactionSync:<T>(callback:()=>T)=>db.transaction(callback)()} as unknown as DurableObjectStorage;return{db,prepaid:new RetainedCleanupPrepayments(storage),core:new CoreGitOperationLedger(storage)};}
const now=Date.parse('2026-10-05T12:00:00Z');
function input():RetainedInput{const id=crypto.randomUUID(),incarnation=crypto.randomUUID();return{id,projectId:'p123456789abc',incarnation,taskId:'task',commit:'a'.repeat(40),base:'b'.repeat(40),canonicalRepoName:'canonical',workspaceRepoName:'workspace',branch:'task/task',protectedRef:`refs/flaregit/inputs/${incarnation}/task/${'a'.repeat(40)}`,protectedBaseRef:`refs/flaregit/inputs/${incarnation}/task/${'b'.repeat(40)}`,workflowId:'workflow',candidateId:'candidate',actorId:'actor',ownerId:'owner',accountKey:'a'.repeat(12),version:1};}
test('distinct acquisition slots and purposes cannot reuse cleanup group identities',()=>{const f=fixture();try{const original=input(),a=f.prepaid.prepare(original,'workspace',now+60000,'read',()=>{},now),b=f.prepaid.prepare({...original,id:crypto.randomUUID()},'workspace',now+60000,'read',()=>{},now),c=f.prepaid.prepare(original,'canonical',now+60000,'write',()=>{},now);expect(new Set([a.operationId,b.operationId,c.operationId]).size).toBe(3);expect(()=>f.prepaid.prepare(original,'workspace',now+60001,'read',()=>{},now)).toThrow('changed');}finally{f.db.close();}});
test('only existing original reserved proof confirms; foreign account and next month remain held without reservation',()=>{const f=fixture();try{const i=input(),record=f.prepaid.prepare(i,'workspace',now+60000,'read',()=>{},now);expect(()=>f.prepaid.confirm(record,null,()=>{},now)).toThrow();f.core.reserve(record.operationId,record.accountKey,{accountUsdMicros:1200,globalUsdMicros:1200},new Date(now));const proof=f.core.existingCoreReservation(record.operationId,record.accountKey,record.month),confirmed=f.prepaid.confirm(record,proof,()=>{},now);expect(confirmed.confirmed).toBe(true);expect(f.prepaid.matches(confirmed,proof,undefined,Date.parse('2026-11-01T00:00:00Z'))).toBe(false);expect(f.prepaid.matches(confirmed,proof?{...proof,accountKey:'foreign'}:null,undefined,now)).toBe(false);expect(f.core.used('2026-10')).toBe(1200);expect(f.core.used('2026-11')).toBe(0);}finally{f.db.close();}});
