import { Database } from "bun:sqlite";
import { expect, test } from "bun:test";
import { RetainedInputs, type RetainedInput } from "../src/server/retained-inputs";
test("retained input receipts require exact remote proof and preserve immutable replay", () => {
    const db = new Database(":memory:");
    const storage = { sql: { exec(query: string, ...bindings: Array<string | number>) { const rows = db.query(query).all(...bindings); return { toArray: () => rows }; } }, transactionSync<T>(callback: () => T) { return db.transaction(callback)(); } };
    const ledger = new RetainedInputs(storage as unknown as DurableObjectStorage), id = crypto.randomUUID();
    const incarnation = crypto.randomUUID();
    const scope: RetainedInput = { id, projectId: "p123456789abc", incarnation, taskId: "task", commit: "a".repeat(40), base: "b".repeat(40), canonicalRepoName: "canonical", workspaceRepoName: "workspace", branch: "main", protectedRef: `refs/flaregit/inputs/${incarnation}/task/${"a".repeat(40)}`, protectedBaseRef: `refs/flaregit/inputs/${incarnation}/task/${"b".repeat(40)}`, workflowId: "wf", candidateId: "candidate", actorId: "actor", ownerId: "owner", accountKey: "a".repeat(12), version: 1 };
    expect(() => ledger.record({ ...scope, followup: true }, { commit: scope.commit, base: scope.base })).toThrow("followup");
    expect(() => ledger.prepareApplication({ ...scope, followup: true }, "c".repeat(40), "d".repeat(40), true)).toThrow("followup");
    expect(() => ledger.record(scope, { commit: "c".repeat(40), base: scope.base })).toThrow("proof");
    expect(ledger.get(id)).toBeNull();
    const saved = ledger.record(scope, { commit: scope.commit, base: scope.base });
    expect(ledger.record(scope, { commit: scope.commit, base: scope.base })).toEqual(saved);
    expect(() => ledger.record({ ...scope, ownerId: "other" }, { commit: scope.commit, base: scope.base })).toThrow("identity changed");
    const application = ledger.prepareApplication(scope, "c".repeat(40), "d".repeat(40), true);
    expect(application.status).toBe("intent");
    expect(() => ledger.applyApplication(id, () => { })).toThrow("unconfirmed");
    expect(() => ledger.remoteVerified(id, "e".repeat(40))).toThrow("proof changed");
    ledger.remoteVerified(id, application.commit);
    let applications = 0;
    const applied = ledger.applyApplication(id, () => { applications++; });
    expect(applied.status).toBe("applied");
    expect(ledger.applyApplication(id, () => { applications++; })).toEqual(applied);
    expect(applications).toBe(1);
    expect(() => ledger.prepareApplication(scope, "e".repeat(40), application.base, true)).toThrow("identity changed");
    expect(() => ledger.record({ ...scope, protectedRef: `refs/flaregit/retained/${crypto.randomUUID()}/input` }, { commit: scope.commit, base: scope.base })).toThrow("scope changed");
});

test("unborn retention stores only actual contributor pin and frozen target with root proof",()=>{
 const db=new Database(":memory:");
 const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};
 const ledger=new RetainedInputs(storage as unknown as DurableObjectStorage),incarnation=crypto.randomUUID(),commit="a".repeat(40);
 const target={kind:"unborn" as const,projectId:"p123456789abc",incarnation,canonicalRepoName:"canonical",ref:"refs/heads/main",branch:"main",acceptedCommit:null,acceptedVersion:0 as const,policyVersion:1,policy:{kind:"git-integrity"},requirements:[] as []};
 const scope:RetainedInput={id:crypto.randomUUID(),projectId:target.projectId,incarnation,taskId:"first",commit,base:null,canonicalRepoName:"canonical",workspaceRepoName:"workspace",branch:"task/first",protectedRef:`refs/flaregit/inputs/${incarnation}/first/${commit}`,protectedBaseRef:null,acceptedTarget:target,workflowId:"workflow",candidateId:"candidate",actorId:"actor",ownerId:"owner",accountKey:"a".repeat(12),version:1};
 expect(()=>ledger.record(scope,{commit,base:null})).toThrow("root ancestry");
 expect(()=>ledger.record({...scope,acceptedTarget:undefined},{commit,base:null,rootCommit:commit,rootAncestryVerified:true})).toThrow();
 expect(()=>ledger.record({...scope,protectedBaseRef:`refs/flaregit/inputs/${incarnation}/first/${"0".repeat(40)}`},{commit,base:null,rootCommit:commit,rootAncestryVerified:true})).toThrow();
 const proof={commit,base:null,rootCommit:commit,rootAncestryVerified:true};
 const receipt=ledger.record(scope,proof);expect(receipt.base).toBeNull();expect(receipt.protectedBaseRef).toBeNull();expect(receipt.rootCommit).toBe(commit);
 expect(ledger.lookup(scope.taskId,scope.candidateId,commit,null)).toEqual(receipt);
 expect(ledger.lookup(scope.taskId,scope.candidateId,commit,"b".repeat(40))).toBeNull();
 expect(ledger.record(scope,proof)).toEqual(receipt);
 const childCommit="c".repeat(40),childScope:RetainedInput={...scope,id:crypto.randomUUID(),taskId:"child",commit:childCommit,base:commit,dependsOn:scope.taskId,stackedOn:{taskId:scope.taskId,commit,ref:scope.protectedRef},protectedRef:`refs/flaregit/inputs/${incarnation}/child/${childCommit}`,protectedBaseRef:`refs/flaregit/inputs/${incarnation}/child/${commit}`};
 expect(()=>ledger.record({...childScope,stackedOn:undefined},{commit:childCommit,base:commit,rootCommit:commit,rootAncestryVerified:true})).toThrow();
 expect(ledger.record(childScope,{commit:childCommit,base:commit,rootCommit:commit,rootAncestryVerified:true})).toMatchObject({base:commit,rootCommit:commit,stackedOn:{taskId:scope.taskId,commit}});

 expect(()=>ledger.record(scope,{...proof,rootCommit:"b".repeat(40)})).toThrow("identity changed");
});
