import { Database } from "bun:sqlite";
import { expect, test } from "bun:test";
import { RetainedInputs, type RetainedInput } from "../src/server/retained-inputs";
test("retained input receipts require exact remote proof and preserve immutable replay", () => {
    const db = new Database(":memory:");
    const storage = { sql: { exec(query: string, ...bindings: Array<string | number>) { const rows = db.query(query).all(...bindings); return { toArray: () => rows }; } }, transactionSync<T>(callback: () => T) { return db.transaction(callback)(); } };
    const ledger = new RetainedInputs(storage as unknown as DurableObjectStorage), id = crypto.randomUUID();
    const incarnation = crypto.randomUUID();
    const scope: RetainedInput = { id, projectId: "p123456789abc", incarnation, taskId: "task", commit: "a".repeat(40), base: "b".repeat(40), canonicalRepoName: "canonical", workspaceRepoName: "workspace", branch: "main", protectedRef: `refs/flaregit/inputs/${incarnation}/task/${"a".repeat(40)}`, protectedBaseRef: `refs/flaregit/inputs/${incarnation}/task/${"b".repeat(40)}`, workflowId: "wf", candidateId: "candidate", actorId: "actor", ownerId: "owner", accountKey: "a".repeat(12), version: 1 };
    expect(() => ledger.record({ ...scope, followup: true }, { commit: scope.commit, base: scope.base })).toThrow("followup");
    expect(() => ledger.prepareApplication({ ...scope, followup: true }, "c".repeat(40), "d".repeat(40), true)).toThrow("followup");
    expect(() => ledger.record(scope, { commit: "c".repeat(40), base: scope.base })).toThrow("proof");
    expect(ledger.get(id)).toBeNull();
    const saved = ledger.record(scope, { commit: scope.commit, base: scope.base });
    expect(ledger.record(scope, { commit: scope.commit, base: scope.base })).toEqual(saved);
    expect(() => ledger.record({ ...scope, ownerId: "other" }, { commit: scope.commit, base: scope.base })).toThrow("identity changed");
    const application = ledger.prepareApplication(scope, "c".repeat(40), "d".repeat(40), true);
    expect(application.status).toBe("intent");
    expect(() => ledger.applyApplication(id, () => { })).toThrow("unconfirmed");
    expect(() => ledger.remoteVerified(id, "e".repeat(40))).toThrow("proof changed");
    ledger.remoteVerified(id, application.commit);
    let applications = 0;
    const applied = ledger.applyApplication(id, () => { applications++; });
    expect(applied.status).toBe("applied");
    expect(ledger.applyApplication(id, () => { applications++; })).toEqual(applied);
    expect(applications).toBe(1);
    expect(() => ledger.prepareApplication(scope, "e".repeat(40), application.base, true)).toThrow("identity changed");
    expect(() => ledger.record({ ...scope, protectedRef: `refs/flaregit/retained/${crypto.randomUUID()}/input` }, { commit: scope.commit, base: scope.base })).toThrow("scope changed");
});
