import {expect,test} from 'bun:test';import {readReviewDraft,saveReviewDraft,clearReviewDraft,delegatedDraftIntent,type ReviewDraftScope,type ReviewDraft} from '../src/web/review-draft-recovery';
function memory(){const values=new Map<string,string>();return{values,getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);},removeItem:(key:string)=>{values.delete(key);}};}
const scope:ReviewDraftScope={identity:'account-a:session-one',projectId:'repository-one',candidateId:'candidate-one',commit:'a'.repeat(40),kind:'delegated'};
test('review notes and lost-ack intent restore only the exact account session repository candidate commit and kind',()=>{const storage=memory(),payload={expectedCommit:scope.commit,grantVersion:1,decision:'approve' as const,note:'Checked the diff'},intent=delegatedDraftIntent(null,payload),draft:ReviewDraft={note:' Checked the diff ',intent};expect(saveReviewDraft(storage,scope,draft)).toBe(true);const restored=readReviewDraft(storage,scope);expect(restored).toEqual(draft);expect(delegatedDraftIntent(restored?.intent?.kind==='delegated'?restored.intent:null,payload)).toEqual(intent);for(const changed of [{identity:'account-b:session-one'},{identity:'account-a:session-two'},{projectId:'repository-two'},{candidateId:'candidate-two'},{commit:'b'.repeat(40)},{kind:'owner' as const}])expect(readReviewDraft(storage,{...scope,...changed})).toBeNull();});
test('new grant or changed decision has a fresh event while unchanged whitespace uses the saved event',()=>{const payload={expectedCommit:scope.commit,grantVersion:1,decision:'approve' as const,note:'Checked'},old=delegatedDraftIntent(null,payload);expect(delegatedDraftIntent(old,{...payload,note:' Checked '.trim()})).toBe(old);expect(delegatedDraftIntent(old,{...payload,grantVersion:2}).eventId).not.toBe(old.eventId);expect(delegatedDraftIntent(old,{...payload,decision:'request_changes'}).eventId).not.toBe(old.eventId);expect(old.payload.grantVersion).toBe(1);});
test('owner exact note survives interruptions and only explicit confirmed cleanup removes the saved scope',()=>{const storage=memory(),owner={...scope,kind:'owner' as const},draft:ReviewDraft={note:' exact whitespace ',intent:{kind:'owner',payload:{expectedCommit:scope.commit,approved:false,note:' exact whitespace '}}};expect(saveReviewDraft(storage,owner,draft)).toBe(true);expect(readReviewDraft(storage,owner)).toEqual(draft);expect(saveReviewDraft(storage,scope,{note:'different',intent:delegatedDraftIntent(null,{expectedCommit:scope.commit,grantVersion:1,decision:'approve',note:'original'})})).toBe(false);clearReviewDraft(storage,owner);expect(readReviewDraft(storage,owner)).toBeNull();});
test('unavailable browser storage never reports a saved review draft',()=>{const unavailable={getItem:()=>{throw Error('disabled');},setItem:()=>{throw Error('disabled');},removeItem:()=>{throw Error('disabled');}};expect(saveReviewDraft(unavailable,scope,{note:'Keep this tab open',intent:null})).toBe(false);expect(readReviewDraft(unavailable,scope)).toBeNull();});

import {bindApiSession,clearVerifiedApiSession} from '../src/web/api';
test('account switch and logout purge review drafts while stale bindings cannot clear the current session',async()=>{const storage=memory(),browserStorage={...storage,get length(){return storage.values.size;},key:(index:number)=>[...storage.values.keys()][index]??null};const previous=Object.getOwnPropertyDescriptor(globalThis,'sessionStorage');Object.defineProperty(globalThis,'sessionStorage',{value:browserStorage,configurable:true});try{const unbindA=bindApiSession(scope.identity,async()=>null);saveReviewDraft(browserStorage,scope,{note:'Synthetic account A note',intent:null});const scopeB={...scope,identity:'account-b:session-two'};const unbindB=bindApiSession(scopeB.identity,async()=>null);expect(readReviewDraft(browserStorage,scope)).toBeNull();saveReviewDraft(browserStorage,scopeB,{note:'Synthetic account B note',intent:null});unbindA();await Promise.resolve();expect(readReviewDraft(browserStorage,scopeB)?.note).toBe('Synthetic account B note');unbindB();await Promise.resolve();expect(readReviewDraft(browserStorage,scopeB)?.note).toBe("Synthetic account B note");clearVerifiedApiSession();expect(readReviewDraft(browserStorage,scopeB)).toBeNull();}finally{if(previous)Object.defineProperty(globalThis,'sessionStorage',previous);else Reflect.deleteProperty(globalThis,'sessionStorage');}});

test("unconfirmed loading or remount preserves notes until verified signout",async()=>{const storage=memory(),browserStorage={...storage,get length(){return storage.values.size;},key:(index:number)=>[...storage.values.keys()][index]??null};const previous=Object.getOwnPropertyDescriptor(globalThis,"sessionStorage");Object.defineProperty(globalThis,"sessionStorage",{value:browserStorage,configurable:true});try{const release=bindApiSession(scope.identity,async()=>null);saveReviewDraft(browserStorage,scope,{note:"Synthetic interruption recovery",intent:null});release();await Promise.resolve();expect(readReviewDraft(browserStorage,scope)?.note).toBe("Synthetic interruption recovery");const releaseAgain=bindApiSession(scope.identity,async()=>null);expect(readReviewDraft(browserStorage,scope)?.note).toBe("Synthetic interruption recovery");releaseAgain();clearVerifiedApiSession();expect(readReviewDraft(browserStorage,scope)).toBeNull();}finally{if(previous)Object.defineProperty(globalThis,"sessionStorage",previous);else Reflect.deleteProperty(globalThis,"sessionStorage");}});

test("verified signedout clears prior-page recovery scopes without clearing unrelated browser state",()=>{clearVerifiedApiSession();const storage=memory(),browserStorage={...storage,get length(){return storage.values.size;},key:(index:number)=>[...storage.values.keys()][index]??null};const previous=Object.getOwnPropertyDescriptor(globalThis,"sessionStorage");Object.defineProperty(globalThis,"sessionStorage",{value:browserStorage,configurable:true});try{saveReviewDraft(browserStorage,scope,{note:"Synthetic prior-page note",intent:null});browserStorage.setItem("flaregit.conversation.synthetic-prior-page","synthetic draft");browserStorage.setItem("flaregit.signInReturn","/p/repository-one");clearVerifiedApiSession();expect(readReviewDraft(browserStorage,scope)).toBeNull();expect(browserStorage.getItem("flaregit.conversation.synthetic-prior-page")).toBeNull();expect(browserStorage.getItem("flaregit.signInReturn")).toBe("/p/repository-one");}finally{if(previous)Object.defineProperty(globalThis,"sessionStorage",previous);else Reflect.deleteProperty(globalThis,"sessionStorage");}});

test("a verified new principal purges foreign prior-page scopes while preserving its own recovery",()=>{clearVerifiedApiSession();const storage=memory(),browserStorage={...storage,get length(){return storage.values.size;},key:(index:number)=>[...storage.values.keys()][index]??null};const previous=Object.getOwnPropertyDescriptor(globalThis,"sessionStorage");Object.defineProperty(globalThis,"sessionStorage",{value:browserStorage,configurable:true});try{saveReviewDraft(browserStorage,scope,{note:"Synthetic stale account A",intent:null});const current={...scope,identity:"account-b:current-session"};saveReviewDraft(browserStorage,current,{note:"Synthetic current account B",intent:null});const release=bindApiSession(current.identity,async()=>null);expect(readReviewDraft(browserStorage,scope)).toBeNull();expect(readReviewDraft(browserStorage,current)?.note).toBe("Synthetic current account B");release();clearVerifiedApiSession();}finally{if(previous)Object.defineProperty(globalThis,"sessionStorage",previous);else Reflect.deleteProperty(globalThis,"sessionStorage");}});
