import { Database } from "bun:sqlite";
import {expect,test} from "bun:test";
import {ArtifactStorageAdmission} from "../src/server/storage-admission";
function ledger(){const db=new Database(":memory:");const storage={sql:{exec(query:string,...bindings:Array<string|number|null>){const rows=db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(callback:()=>T):T{return db.transaction(callback)();}};return new ArtifactStorageAdmission(storage as unknown as DurableObjectStorage);}
const now=new Date("2026-10-02T12:00:00Z"),policy={globalSlots:3,accountSlots:2};
test("storage admission fails closed before complete inventory and configured policy",()=>{const store=ledger();expect(store.reserve("repo","owner","canonical",policy,now)).toEqual({allowed:false,reason:"inventory_unverified"});store.reconcileCompleteInventory("namespace",[],now);expect(store.reserve("repo","owner","canonical",{...policy,globalSlots:null},now)).toEqual({allowed:false,reason:"unconfigured"});expect(store.reserve("repo","owner","canonical",policy,now)).toEqual({allowed:true,existing:false});expect(store.reserve("repo","owner","canonical",policy,now)).toEqual({allowed:true,existing:true});expect(()=>store.reserve("repo","other","canonical",policy,now)).toThrow("identity changed");});
test("existing inventory consumes global slots and cannot disappear through listing",()=>{const store=ledger();store.reconcileCompleteInventory("namespace",["canonical","retained-fork"],now);expect(store.reserve("import","customer","import",policy,now).allowed).toBe(true);expect(store.reserve("fork","customer","workspace",policy,now)).toEqual({allowed:false,reason:"global_capacity"});store.reconcileCompleteInventory("namespace",[],now);expect(store.snapshot(now).activeSlots).toBe(3);expect(()=>store.reconcileCompleteInventory("different",[],now)).toThrow("namespace changed");});
test("confirmed deletion retains daily peak and cannot silently reuse identity",()=>{const store=ledger();store.reconcileCompleteInventory("namespace",[],now);store.reserve("canonical","customer","canonical",policy,now);store.reserve("workspace","customer","workspace",policy,now);expect(()=>store.recordConfirmedDeletion("workspace",false,now)).toThrow();expect(store.snapshot(now).activeSlots).toBe(2);store.recordConfirmedDeletion("workspace",true,now);expect(store.snapshot(now).activeSlots).toBe(1);expect(store.snapshot(now).dailyPeaks.find(row=>row.owner==="*")?.slots).toBe(2);expect(()=>store.reserve("workspace","customer","workspace",policy,now)).toThrow("identity changed");expect(()=>store.reconcileCompleteInventory("namespace",["workspace"],now)).toThrow("reappeared");});
test("account slots include retained workspaces and enforce atomic named reservations",async()=>{const store=ledger();store.reconcileCompleteInventory("namespace",[],now);const results=await Promise.all(["canonical","fork-one","fork-two"].map(async name=>store.reserve(name,"customer","workspace",policy,now)));expect(results.filter(result=>result.allowed)).toHaveLength(2);expect(results.at(-1)).toEqual({allowed:false,reason:"account_capacity"});});
test("named daily liability blocks create-delete churn until the next UTC day",()=>{const store=ledger();const single={globalSlots:1,accountSlots:1};store.reconcileCompleteInventory("namespace",[],now);expect(store.reserve("first","customer","workspace",single,now).allowed).toBe(true);store.recordConfirmedDeletion("first",true,now);expect(store.reserve("second","customer","workspace",single,now)).toEqual({allowed:false,reason:"global_capacity"});const tomorrow=new Date("2026-10-03T12:00:00Z");expect(store.reserve("second","customer","workspace",single,tomorrow).allowed).toBe(true);expect(store.snapshot(tomorrow).dailyPeaks.filter(row=>row.owner==="*").map(row=>row.slots)).toEqual([1,1]);});
test("verified existing ownership adoption preserves exact allocation identity and manifest",()=>{const store=ledger();store.reconcileCompleteInventory("namespace",["canonical"],now);expect(()=>store.claimVerifiedExisting("canonical","customer","canonical",false,now)).toThrow();store.claimVerifiedExisting("canonical","customer","canonical",true,now);store.associateProject("canonical","project");expect(store.reserve("canonical","customer","canonical",policy,now)).toEqual({allowed:true,existing:true});expect(store.projectManifest("project")).toEqual([{name:"canonical",state:"reserved"}]);expect(()=>store.claimVerifiedExisting("canonical","other","canonical",true,now)).toThrow();});
