import {test,expect} from "bun:test";
import {renderToStaticMarkup} from "react-dom/server";
import {parseTagInventory,parseReleases,parseTagOperations,tagCreationRequest,type GitTag,type RepositoryRelease} from "../src/web/tags-releases";
import {TagIdentity,TagsReleasesPanel} from "../src/web/components/TagsReleasesPanel";
const tag:GitTag={name:"v1.0.0",ref:"refs/tags/v1.0.0",object:"a".repeat(40),objectType:"tag",peeledCommit:"b".repeat(40)},target={ref:"refs/heads/trunk",commit:"b".repeat(40),acceptedVersion:2,policyVersion:1};
test("tag inventory preserves raw annotated identity and never coerces noncommit tags into release commits",()=>{const blob:GitTag={name:"blob",ref:"refs/tags/blob",object:"c".repeat(40),objectType:"blob",peeledCommit:null},inventory=parseTagInventory({tags:[tag,blob],nextCursor:null,complete:true,observedAt:"2026-10-04T00:00:00.000Z"});expect(inventory.tags[0]?.object).toBe(tag.object);expect(inventory.tags[0]?.peeledCommit).toBe(tag.peeledCommit);const html=renderToStaticMarkup(<TagIdentity tag={blob}/>);expect(html).toContain("does not resolve to a commit");expect(html).toContain(blob.object);expect(()=>parseTagInventory({...inventory,tags:[{...blob,peeledCommit:tag.peeledCommit}]})).toThrow();expect(()=>parseTagInventory({...inventory,tags:[{...tag,token:"secret"}]})).toThrow();});
test("unknown tag acknowledgement preserves exact creation identity and accepted source",()=>{const first=tagCreationRequest(null,{tagName:tag.name,kind:"annotated",message:"First release",expectedTarget:target},()=>crypto.randomUUID());expect(tagCreationRequest(first,{tagName:"another",kind:"lightweight",expectedTarget:{...target,commit:"d".repeat(40)}},()=>{throw Error("No replacement");})).toBe(first);expect(()=>tagCreationRequest(null,{tagName:"bad..tag",kind:"lightweight",expectedTarget:target},()=>crypto.randomUUID())).toThrow();expect(()=>tagCreationRequest(null,{tagName:tag.name,kind:"annotated",expectedTarget:target},()=>crypto.randomUUID())).toThrow();});
test("only exact observed tag and confirmed cleanup can be marked confirmed",()=>{const operation={operationId:crypto.randomUUID(),tagName:tag.name,kind:"annotated",target,phase:"push_unknown",credentialState:"cleanup_pending",nativeState:"unconfirmed",confirmed:false,canReconcile:true,canResumeOriginal:false};expect(parseTagOperations({operations:[operation],nextCursor:null,complete:true}).operations[0]?.confirmed).toBe(false);expect(()=>parseTagOperations({operations:[{...operation,confirmed:true,tag}],nextCursor:null,complete:true})).toThrow();expect(parseTagOperations({operations:[{...operation,phase:"observed",confirmed:true,credentialState:"revoked",nativeState:"stopped",tag}],nextCursor:null,complete:true}).operations[0]?.tag?.object).toBe(tag.object);});
test("release presentation keeps people attribution revision and draft state without invented asset downloads",()=>{const release:RepositoryRelease={id:crypto.randomUUID(),tag:{ref:tag.ref,object:tag.object,peeledCommit:tag.peeledCommit},title:"First release",notes:"Original release notes",state:"draft",revision:3,author:{id:"alice",displayName:"Alice"},editor:{id:"bob",displayName:"Bob"},createdAt:"2026-10-04T00:00:00.000Z",updatedAt:"2026-10-04T01:00:00.000Z"};parseReleases({releases:[release],nextCursor:null,complete:true});const html=renderToStaticMarkup(<TagsReleasesPanel initialTab="releases" tags={[tag]} targets={[target]} operations={[]} releases={[release]} isOwner={false} loading={false} error={null} onRefresh={()=>{}} onCreateTag={async()=>{throw Error("No provider");}} onSaveDraft={async()=>release} onPublish={async()=>release}/>);expect(html).toContain("Created by Alice");expect(html).toContain("last edited by Bob");expect(html).toContain("revision 3");expect(html).toContain("Draft");expect(html).toContain(release.notes);expect(html).not.toContain("Publish release");expect(html).not.toContain("Download");expect(()=>parseReleases({releases:[{...release,state:"published"}],nextCursor:null,complete:true})).toThrow();});
