import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {TaskCreationIntents,type TaskCreationIntent} from "../src/server/task-creation-intents";
import {InitialForkCredentials,type InitialForkCredentialScope} from "../src/server/initial-fork-credentials";
import {assertTaskCreationQuiescence} from "../src/server/task-creation-quiescence";
function fixture(unborn=false){const db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=db.query(query).all(...bindings);return{toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage;
 const intent:TaskCreationIntent={eventId:crypto.randomUUID(),allocationId:crypto.randomUUID(),nativeProtocol:"sdk-only",taskId:"saved-task",actor:{userId:"creator",viaToken:false,credentialHash:null,sessionExpiresAt:Date.now()+60000},accountKey:"a".repeat(12),projectId:"p123456789abc",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",workspaceRepoName:"t-p123456789abc-saved-task",input:{goal:"Preserve original work",dependsOn:null,issue:null},selection:{acceptedTarget:null,baseCommit:"b".repeat(40),sourceRepoName:"canonical",scope:"original-source-policy-parent-snapshot"}},scope={projectId:intent.projectId,incarnation:intent.incarnation,canonicalRepoName:intent.canonicalRepoName,taskId:intent.taskId,workspaceRepoName:intent.workspaceRepoName},credentialScope:InitialForkCredentialScope={...scope,eventId:intent.eventId,allocationId:intent.allocationId,accountKey:intent.accountKey,actorId:intent.actor.userId};
 if(unborn){intent.selection.baseCommit=null;intent.selection.acceptedTarget={kind:"unborn",projectId:intent.projectId,incarnation:intent.incarnation,canonicalRepoName:intent.canonicalRepoName,ref:"refs/heads/trunk",branch:"trunk",acceptedCommit:null,acceptedVersion:0,requirements:[],policyVersion:1,policy:{}};}
 const intents=new TaskCreationIntents(storage),credentials=new InitialForkCredentials(storage);db.exec("CREATE TABLE task_fork_acknowledgements(event_id TEXT PRIMARY KEY,payload TEXT NOT NULL)");const ack={providerRepoId:"provider-id",name:intent.workspaceRepoName,description:`FlareGit creation ${intent.eventId}/${intent.allocationId}`,allocationId:intent.allocationId,sourceRepoName:intent.selection.sourceRepoName,sourceCommit:intent.selection.baseCommit,...(unborn?{emptySourceProof:{ref:"refs/heads/trunk",refs:[] as []}}:{})};
 async function complete(){intents.prepare(intent,()=>{});intents.beginFork(intent.eventId,()=>{});credentials.begin(credentialScope,()=>{});await credentials.record(credentialScope,"synthetic-initial-token");await credentials.markRevoked(credentialScope,"synthetic-initial-token",{repoName:intent.workspaceRepoName,revoked:true});db.query("INSERT INTO task_fork_acknowledgements VALUES(?,?)").run(intent.eventId,JSON.stringify(ack));intents.confirmFork(intent.eventId,{allocationId:intent.allocationId,workspaceRepoName:intent.workspaceRepoName,sourceRepoName:intent.selection.sourceRepoName,sourceCommit:intent.selection.baseCommit,providerRepoId:ack.providerRepoId,nativeState:"not_allocated",credentialsComplete:true,...(ack.emptySourceProof?{emptySourceProof:ack.emptySourceProof}:{})},()=>{});intents.commit(intent.eventId,()=>{},()=>{});}
 return{db,storage,intent,scope,credentialScope,intents,credentials,ack,complete};}
test("positive original SDK creation and exact revoked credential prove quiescence without writes",async()=>{const f=fixture();try{await f.complete();const before=f.db.query("SELECT total_changes() AS n").get();expect(assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toEqual({eventId:f.intent.eventId,allocationId:f.intent.allocationId,providerRepoId:f.ack.providerRepoId,native:"not_allocated"});expect(f.db.query("SELECT total_changes() AS n").get()).toEqual(before);expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{throw Error("Owner authority changed");})).toThrow("Owner");}finally{f.db.close();}});
test("legacy absent tables or empty current tables never prove SDK credential absence",()=>{const f=fixture();try{expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");f.db.exec("DROP TABLE initial_fork_credentials");const before=f.db.query("SELECT total_changes() AS n").get();expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");expect(f.db.query("SELECT total_changes() AS n").get()).toEqual(before);expect(f.db.query("SELECT name FROM sqlite_master WHERE name='initial_fork_credentials'").all()).toEqual([]);}finally{f.db.close();}});
test("unknown issuance, pending cleanup, missing acknowledgement and changed allocation stay unknown",async()=>{const f=fixture();try{await f.complete();for(const status of ["issuance_unknown","pending"]){f.db.query("UPDATE initial_fork_credentials SET status=?").run(status);expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");}f.db.exec("UPDATE initial_fork_credentials SET status='revoked'");f.db.query("UPDATE task_fork_acknowledgements SET payload=?").run(JSON.stringify({...f.ack,allocationId:crypto.randomUUID()}));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");f.db.query("UPDATE task_fork_acknowledgements SET payload=?").run(JSON.stringify(f.ack));f.db.query("UPDATE initial_fork_credentials SET payload=?").run(JSON.stringify({...f.credentialScope,actorId:"other-creator"}));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");f.db.exec("DELETE FROM task_fork_acknowledgements");expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");}finally{f.db.close();}});
test("repository incarnation, original workspace and incomplete creation cannot be substituted",async()=>{const f=fixture();try{await f.complete();for(const changed of [{incarnation:crypto.randomUUID()},{workspaceRepoName:"other-workspace"},{canonicalRepoName:"other-canonical"},{taskId:"other-task"}])expect(()=>assertTaskCreationQuiescence(f.storage,{...f.scope,...changed},()=>{})).toThrow("unverified");const row=f.db.query("SELECT doc FROM task_creation_intents").get() as {doc:string};f.db.query("UPDATE task_creation_intents SET doc=?").run(JSON.stringify({...JSON.parse(row.doc),phase:"fork_confirmed"}));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");}finally{f.db.close();}});

test("unborn creation quiescence requires its saved exact empty-source receipt and revoked credential",async()=>{const f=fixture(true);try{await f.complete();expect(assertTaskCreationQuiescence(f.storage,f.scope,()=>{}).eventId).toBe(f.intent.eventId);const {emptySourceProof:_proof,...missing}=f.ack;f.db.query("UPDATE task_fork_acknowledgements SET payload=?").run(JSON.stringify(missing));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");f.db.query("UPDATE task_fork_acknowledgements SET payload=?").run(JSON.stringify({...f.ack,emptySourceProof:{ref:"refs/heads/main",refs:[]}}));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");f.db.query("UPDATE task_fork_acknowledgements SET payload=?").run(JSON.stringify({...f.ack,emptySourceProof:{ref:"refs/heads/trunk",refs:["refs/heads/unexpected"]}}));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");}finally{f.db.close();}});

test("contradictory committed and empty-source acknowledgements cannot prove quiescence",async()=>{const f=fixture();try{await f.complete();f.db.query("UPDATE task_fork_acknowledgements SET payload=?").run(JSON.stringify({...f.ack,emptySourceProof:{ref:"refs/heads/trunk",refs:[]}}));expect(()=>assertTaskCreationQuiescence(f.storage,f.scope,()=>{})).toThrow("unverified");}finally{f.db.close();}});
