import {Database} from "bun:sqlite";
import {test,expect} from "bun:test";
import {TaskTargetGenerations,type TaskTargetGenerationIntent,type TaskTargetGenerationSettlement} from "../src/server/task-target-generations";
function fixture(){const db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=bindings.length===0&&query.split(";").filter(value=>value.trim()).length>1?(db.exec(query),[]):db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};return{db,ledger:new TaskTargetGenerations(storage as unknown as DurableObjectStorage)};}
function intent():TaskTargetGenerationIntent{const target={projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",ref:"refs/heads/release",branch:"release",acceptedCommit:"a".repeat(40),acceptedVersion:1,requirements:[],policyVersion:1,policy:{test:"original"}};return{eventId:crypto.randomUUID(),expectedGeneration:0,projectId:target.projectId,incarnation:target.incarnation,canonicalRepoName:target.canonicalRepoName,ownerId:"owner",actor:{userId:"owner",displayName:"Owner",viaToken:false},source:{taskId:"task",goal:"Preserve purpose",contributorId:"contributor",workspaceRepoName:"workspace",branch:"task/change",baseCommit:target.acceptedCommit,currentCommit:"b".repeat(40),requirements:[],snapshotDigest:"c".repeat(64),originalAcceptedTarget:target},target:{...target,policyVersion:2,policy:{test:"new-policy"}},change:{kind:"policy-refresh"}};}
function settled(value:TaskTargetGenerationIntent):TaskTargetGenerationSettlement{return{eventId:value.eventId,taskId:value.source.taskId,previousGeneration:value.expectedGeneration,sourceSnapshotDigest:value.source.snapshotDigest,coverage:"complete",native:"stopped",proposals:"settled",git:{kind:"unchanged",baseCommit:value.source.baseCommit,currentCommit:value.source.currentCommit}};}
test("explicit policy generation preserves creation binding and Git input, requiring positive settlement before activation",()=>{
 const{db,ledger}=fixture(),value=intent(),original=JSON.stringify(value.source.originalAcceptedTarget);try{expect(()=>ledger.prepare(value,()=>{throw Error("Owner revoked");})).toThrow("Owner revoked");expect(ledger.current("task")).toBeNull();const prepared=ledger.prepare(value,()=>{});expect(prepared.phase).toBe("prepared");expect(ledger.current("task")).toBeNull();expect(()=>ledger.activate(value.eventId,()=>({...settled(value),coverage:"unknown"} as unknown as TaskTargetGenerationSettlement),()=>{})).toThrow();expect(ledger.get(value.eventId)?.phase).toBe("prepared");const activated=ledger.activate(value.eventId,()=>settled(value),()=>{});expect(activated.activation).toMatchObject({git:"unchanged",baseCommit:value.source.baseCommit,currentCommit:value.source.currentCommit});expect(JSON.stringify(activated.source.originalAcceptedTarget)).toBe(original);expect(ledger.current("task")?.eventId).toBe(value.eventId);expect(ledger.get(value.eventId)?.target.policyVersion).toBe(2);}finally{db.close();}
});
test("stable event replay never rebinds after root advance or rewinds a newer active generation",()=>{
 const{db,ledger}=fixture(),first=intent();try{ledger.prepare(first,()=>{});const active=ledger.activate(first.eventId,()=>settled(first),()=>{});expect(()=>ledger.prepare({...first,target:{...first.target,acceptedCommit:"d".repeat(40)}},()=>{})).toThrow();const second:TaskTargetGenerationIntent={...first,eventId:crypto.randomUUID(),expectedGeneration:1,target:{...first.target,policyVersion:3,policy:{test:"third"}}};ledger.prepare(second,()=>{});ledger.activate(second.eventId,()=>settled(second),()=>{});const current=ledger.current("task");expect(ledger.activate(first.eventId,()=>{throw Error("Must not reprove completed operation");},()=>{})).toEqual(active);expect(ledger.current("task")).toEqual(current);expect(ledger.history("task").generations).toHaveLength(2);expect(ledger.get(first.eventId)?.target.policyVersion).toBe(2);}finally{db.close();}
});
test("actual rebase generation requires exact verified receipt and distinguishes changed base from metadata refresh",()=>{
 const{db,ledger}=fixture(),value=intent(),receiptId=crypto.randomUUID();try{const rebased:TaskTargetGenerationIntent={...value,target:{...value.target,acceptedCommit:"d".repeat(40)},change:{kind:"rebase",receiptId}};ledger.prepare(rebased,()=>{});expect(()=>ledger.activate(value.eventId,()=>settled(rebased),()=>{})).toThrow("rebase receipt");const proof:TaskTargetGenerationSettlement={...settled(rebased),git:{kind:"rebased",receiptId,oldBase:value.source.baseCommit,oldCommit:value.source.currentCommit,newBase:rebased.target.acceptedCommit,newCommit:"e".repeat(40),remoteVerified:true}};expect(()=>ledger.activate(value.eventId,()=>({...proof,git:{...proof.git,receiptId:crypto.randomUUID()}} as TaskTargetGenerationSettlement),()=>{})).toThrow("receipt");const record=ledger.activate(value.eventId,()=>proof,()=>{});expect(record.activation).toMatchObject({git:"rebased",baseCommit:"d".repeat(40),currentCommit:"e".repeat(40),receiptId});expect(record.source.baseCommit).toBe(value.source.baseCommit);expect(record.source.currentCommit).toBe(value.source.currentCommit);}finally{db.close();}
});
test("competing prepared generation and changed actor/creation scope cannot replace active generation",()=>{
 const{db,ledger}=fixture(),value=intent();try{expect(()=>ledger.prepare({...value,actor:{...value.actor,userId:"other"}},()=>{})).toThrow("owner");ledger.prepare(value,()=>{});const competing={...value,eventId:crypto.randomUUID(),target:{...value.target,policyVersion:3}};ledger.prepare(competing,()=>{});ledger.activate(value.eventId,()=>settled(value),()=>{});expect(()=>ledger.activate(competing.eventId,()=>settled(competing),()=>{})).toThrow("generation changed");expect(ledger.get(competing.eventId)?.phase).toBe("prepared");expect(()=>ledger.prepare({...value,eventId:crypto.randomUUID(),expectedGeneration:1,source:{...value.source,workspaceRepoName:"other"}},()=>{})).toThrow("creation binding");expect(ledger.current("task")?.eventId).toBe(value.eventId);}finally{db.close();}
});

test("stacked historical workspace base supports policy refresh while accepted target head stays unchanged",()=>{
 const{db,ledger}=fixture(),value=intent();value.source.baseCommit="3".repeat(40);value.source.currentCommit="4".repeat(40);
 try{ledger.prepare(value,()=>{});const refreshed=ledger.activate(value.eventId,()=>settled(value),()=>{});expect(refreshed.activation).toMatchObject({git:"unchanged",baseCommit:"3".repeat(40),currentCommit:"4".repeat(40)});expect(refreshed.target.acceptedCommit).toBe(value.source.originalAcceptedTarget.acceptedCommit);
 const advance:TaskTargetGenerationIntent={...value,eventId:crypto.randomUUID(),expectedGeneration:1,target:{...value.target,acceptedCommit:"d".repeat(40)}};expect(()=>ledger.prepare(advance,()=>{})).toThrow("cannot advance accepted target history");expect(ledger.current(value.source.taskId)?.eventId).toBe(value.eventId);expect(ledger.get(advance.eventId)).toBeNull();}
 finally{db.close();}
});
test("policy refresh compares the active generation root after a proven rebase, preserving original creation head",()=>{
 const{db,ledger}=fixture(),original=intent(),receiptId=crypto.randomUUID(),rebase:TaskTargetGenerationIntent={...original,target:{...original.target,acceptedCommit:"d".repeat(40)},change:{kind:"rebase",receiptId}};
 try{ledger.prepare(rebase,()=>{});ledger.activate(rebase.eventId,()=>({...settled(rebase),git:{kind:"rebased",receiptId,oldBase:rebase.source.baseCommit,oldCommit:rebase.source.currentCommit,newBase:"d".repeat(40),newCommit:"e".repeat(40),remoteVerified:true}}),()=>{});
 const refresh:TaskTargetGenerationIntent={...original,eventId:crypto.randomUUID(),expectedGeneration:1,source:{...original.source,baseCommit:"d".repeat(40),currentCommit:"e".repeat(40),snapshotDigest:"f".repeat(64)},target:{...rebase.target,policyVersion:3}};ledger.prepare(refresh,()=>{});const record=ledger.activate(refresh.eventId,()=>settled(refresh),()=>{});expect(record.activation).toMatchObject({git:"unchanged",baseCommit:"d".repeat(40),currentCommit:"e".repeat(40)});expect(record.source.originalAcceptedTarget.acceptedCommit).toBe("a".repeat(40));expect(ledger.get(rebase.eventId)?.activation?.git).toBe("rebased");}
 finally{db.close();}
});
