import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {FlareGitProjectState,ProductDecision,CandidateGeneration} from '../src/core/types';
test('native owner policy refresh preserves original task creation and enables a fresh frozen generation only after quiescence',async()=>{
 if(await workerdChild('tests/task-target-generation-native.test.ts'))return;
 const output=`/tmp/flaregit-generation-native-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/task-target-generation-native-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'generation',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'TaskTargetGenerationFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('generation'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})}),json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body),value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 await json('/seed');await json('/create',{operationId:crypto.randomUUID(),name:'release',sourceCommit:'a'.repeat(40)});for(const id of ['a','b']){await json('/target-task',{id,ref:'refs/heads/release'});await json('/requirements',{taskId:id,choice:`choice-${id}`,output:id==='a',...(id==='a'?{patch:{refunds:true}}:{})});}
 const original=await json<FlareGitProjectState>('/raw-state'),receipts=await json<unknown>('/creation-receipts');const decision=(await json<{decision:ProductDecision}>('/landing',{tasks:['a','b'],holder:'first-decision'})).decision;await json('/resolve',{decisionId:decision.id,optionId:'choice-a'});expect(await json('/landing',{tasks:['a','b'],holder:'still-old-target'})).toMatchObject({reason:expect.stringContaining('target')});
 const events:Record<string,string>={};for(const id of ['a','b']){events[id]=crypto.randomUUID();await json('/prepare-generation',{taskId:id,eventId:events[id],expectedGeneration:0});if(id==='a'){const gatewayId=crypto.randomUUID();await json('/begin-gateway',{id:gatewayId,taskId:id});expect((await call('/activate-generation?event='+events[id])).ok).toBe(false);expect((await json<FlareGitProjectState>('/state-full')).tasks.a?.targetGeneration).toBeUndefined();expect(await json<boolean>('/settle-gateway',{id:gatewayId})).toBe(true);}await json('/activate-generation?event='+events[id]);}
 const projected=await json<FlareGitProjectState>('/state-full'),raw=await json<FlareGitProjectState>('/raw-state');expect(raw.tasks.a?.acceptedTarget).toEqual(original.tasks.a?.acceptedTarget);expect(raw.tasks.a?.targetGeneration).toBeUndefined();expect(await json<unknown>('/creation-receipts')).toEqual(receipts);expect(projected.tasks.a?.targetGeneration).toMatchObject({eventId:events.a,generation:1,acceptedTarget:{policyVersion:2,policy:{refunds:true}}});expect(projected.acceptedState.currentCommit).toBe(original.acceptedState.currentCommit);
 const fresh=(await json<{candidate:CandidateGeneration}>('/landing',{tasks:['a','b'],holder:'refreshed-candidate'})).candidate;expect(fresh.acceptedTarget?.policyVersion).toBe(2);expect(fresh.participatingTargetGenerations?.a?.eventId).toBe(events.a);expect(await json('/activate-generation?event='+events.a)).toMatchObject({phase:'activated',generation:1});expect((await json<FlareGitProjectState>('/raw-state')).tasks.a?.acceptedTarget).toEqual(original.tasks.a?.acceptedTarget);
 const blocked=crypto.randomUUID();await json('/prepare-generation',{taskId:'a',eventId:blocked,expectedGeneration:1});expect((await call('/activate-generation?event='+blocked)).ok).toBe(false);expect((await json<FlareGitProjectState>('/state-full')).tasks.a?.targetGeneration?.eventId).toBe(events.a);expect((await json<FlareGitProjectState>('/state-full')).candidates[fresh.id]?.acceptedTarget).toEqual(fresh.acceptedTarget);
 const scoped=async<T>(path:string,body?:unknown)=>json<T>(path+(path.includes('?')?'&':'?')+'name=refreshed-agent',body);await scoped('/seed');await scoped('/create',{operationId:crypto.randomUUID(),name:'release',sourceCommit:'a'.repeat(40)});await scoped('/target-task',{id:'agent-task',ref:'refs/heads/release'});await scoped('/mutate-root');const agentEvent=crypto.randomUUID();await scoped('/prepare-generation',{taskId:'agent-task',eventId:agentEvent,expectedGeneration:0});await scoped('/activate-generation?event='+agentEvent);expect(await scoped('/agent-generation-proof',{taskId:'agent-task',runId:'refreshed-agent-run'})).toMatchObject({claimed:'claimed',target:{policyVersion:2},stamp:{eventId:agentEvent,generation:1},native:true,proposed:true,pushed:true});const agentRaw=await scoped<FlareGitProjectState>('/raw-state');expect(agentRaw.tasks['agent-task']?.acceptedTarget?.policyVersion).toBe(1);expect(agentRaw.tasks['agent-task']?.targetGeneration).toBeUndefined();
 }finally{await mf.dispose();}
},30000);
