import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {workerdChild} from './support/workerd-child';
import type {TaskCreationIntentRecord} from '../src/server/task-creation-intents';
test('native task intent preserves refreshed-session replay and rolls back task, writer, receipt and cached state with final phase failure',async()=>{
 if(await workerdChild('tests/task-creation-intent-native.test.ts'))return;
 const output=`/tmp/flaregit-task-intent-native-${crypto.randomUUID()}.js`,build=Bun.spawn([process.execPath,'build','tests/support/task-creation-intent-native-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*',`--outfile=${output}`],{stdout:'ignore',stderr:'pipe'});let script:string;
 try{if(await build.exited!==0)throw Error(await new Response(build.stderr).text());script=await Bun.file(output).text();}finally{if(await Bun.file(output).exists())await Bun.file(output).delete();}
 const bindings={MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000',REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000'};
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'task-intent',modules:true,script,bindings,compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],durableObjects:{REPOSITORY_CONTROLLER:{className:'TaskCreationIntentFixture',useSQLite:true}}}]}));
 try{const api=await mf.getWorker('task-intent'),call=(path:string,body?:unknown)=>api.fetch(`http://test${path}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})}),json=async<T>(path:string,body?:unknown):Promise<T>=>{const response=await call(path,body),value=await response.json();if(!response.ok)throw Error(JSON.stringify(value));return value as T;};
 await json('/seed');const input={goal:'Preserve original request',dependsOn:null,issue:null},intent=await json<TaskCreationIntentRecord>('/prepare-intent',input);const replay=await json<TaskCreationIntentRecord>('/prepare-intent',input);expect(replay).toEqual(intent);expect((await call('/prepare-intent?expired=true',input)).ok).toBe(false);await json('/begin-intent?event='+intent.eventId);expect(await json<boolean>('/ack-intent?event='+intent.eventId)).toBe(true);await json('/confirm-intent?event='+intent.eventId);await json('/fault-intent?on=true');expect((await call('/commit-intent?event='+intent.eventId)).ok).toBe(false);expect(await json('/intent-state')).toMatchObject({hasTask:false,phase:'fork_confirmed',writers:0,receipts:0});await json('/fault-intent?on=false');expect((await call('/commit-intent?event='+intent.eventId+'&expired=true')).ok).toBe(false);await json('/commit-intent?event='+intent.eventId);expect(await json('/intent-state')).toMatchObject({hasTask:true,phase:'committed',writers:1,receipts:1});expect(await json('/commit-intent?event='+intent.eventId)).toMatchObject({id:'task-new',creationReplayed:true});
 }finally{await mf.dispose();}
},30000);
