import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import {TaskCreationIntents,taskForkCompletionProofSchema,type TaskCreationIntent,type TaskForkCompletionProof} from "../src/server/task-creation-intents";
function fixture(){const db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number>){if(query.startsWith("CREATE")){db.exec(query);return {toArray:()=>[]};}const rows=db.query(query).all(...bindings);return {toArray:()=>rows};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}};const ledger=new TaskCreationIntents(storage as unknown as DurableObjectStorage),intent:TaskCreationIntent={eventId:crypto.randomUUID(),nativeProtocol:"sdk-only",allocationId:crypto.randomUUID(),taskId:"saved-task",actor:{userId:"creator",viaToken:false,credentialHash:null,sessionExpiresAt:Date.now()+60000},accountKey:"a".repeat(12),projectId:"p123456789abc",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",workspaceRepoName:"t-p123456789abc-saved-task",input:{goal:"Preserve intent",dependsOn:null,issue:null},selection:{acceptedTarget:null,baseCommit:"b".repeat(40),sourceRepoName:"canonical",scope:JSON.stringify({policyVersion:1,parent:null})}};const proof:TaskForkCompletionProof={allocationId:intent.allocationId,workspaceRepoName:intent.workspaceRepoName,sourceRepoName:intent.selection.sourceRepoName,sourceCommit:intent.selection.baseCommit,providerRepoId:"provider-id",nativeState:"not_allocated",credentialsComplete:true};return {db,ledger,intent,proof};}
test("lost fork acknowledgement resumes the exact saved allocation and atomic task commit",()=>{const f=fixture();try{let saved=0;const initial=f.ledger.prepare(f.intent,()=>{});expect(initial.phase).toBe("prepared");expect(f.ledger.prepare(f.intent,()=>{})).toEqual(initial);f.ledger.beginFork(f.intent.eventId,()=>{});expect(f.ledger.markForkUnknown(f.intent.eventId).phase).toBe("fork_unknown");expect(()=>f.ledger.beginFork(f.intent.eventId,()=>{})).toThrow("already recorded");expect(()=>f.ledger.commit(f.intent.eventId,()=>{},()=>saved++)).toThrow("unconfirmed");expect(f.ledger.confirmFork(f.intent.eventId,f.proof,()=>{}).phase).toBe("fork_confirmed");expect(()=>f.ledger.commit(f.intent.eventId,()=>{throw Error("Authority withdrawn");},()=>saved++)).toThrow("withdrawn");expect(f.ledger.get(f.intent.eventId)?.phase).toBe("fork_confirmed");f.db.exec("CREATE TABLE saved_tasks(task_id TEXT PRIMARY KEY)");expect(()=>f.ledger.commit(f.intent.eventId,()=>{},record=>{f.db.query("INSERT INTO saved_tasks VALUES(?)").run(record.taskId);throw Error("Interrupted save");})).toThrow("Interrupted");expect(f.db.query("SELECT * FROM saved_tasks").all()).toEqual([]);expect(f.ledger.get(f.intent.eventId)?.phase).toBe("fork_confirmed");expect(f.ledger.commit(f.intent.eventId,()=>{},()=>saved++).phase).toBe("committed");f.ledger.commit(f.intent.eventId,()=>{},()=>saved++);expect(saved).toBe(1);expect(f.ledger.forTask(f.intent.taskId)?.allocationId).toBe(f.intent.allocationId);}finally{f.db.close();}});
test("changed actor, policy, parent, workspace and allocation never adopt a similarly named fork",()=>{const f=fixture();try{f.ledger.prepare(f.intent,()=>{});for(const changed of [{allocationId:crypto.randomUUID()},{eventId:crypto.randomUUID()},{actor:{...f.intent.actor,userId:"other"}},{selection:{...f.intent.selection,scope:JSON.stringify({policyVersion:2,parent:{commit:"c".repeat(40)}})}},{selection:{...f.intent.selection,baseCommit:"c".repeat(40)}}])expect(()=>f.ledger.prepare({...f.intent,...changed},()=>{})).toThrow("changed");f.ledger.beginFork(f.intent.eventId,()=>{});f.ledger.markForkUnknown(f.intent.eventId);for(const changed of [{allocationId:crypto.randomUUID()},{sourceCommit:"c".repeat(40)},{workspaceRepoName:"same-name-other-repo"},{sourceRepoName:"other-parent"},{credentialsComplete:false},{nativeState:"stopped"}])expect(()=>f.ledger.confirmFork(f.intent.eventId,{...f.proof,...changed} as TaskForkCompletionProof,()=>{})).toThrow("original allocation");expect(()=>f.ledger.confirmFork(f.intent.eventId,f.proof,()=>{throw Error("No exclusive provider proof");})).toThrow("exclusive");expect(f.ledger.get(f.intent.eventId)?.phase).toBe("fork_unknown");}finally{f.db.close();}});
test("authority and historical capacity fences preserve replayable records",()=>{const f=fixture();try{expect(()=>f.ledger.prepare(f.intent,()=>{throw Error("Expired session");})).toThrow("Expired");expect(f.ledger.forTask(f.intent.taskId)).toBeNull();const original=f.ledger.prepare(f.intent,()=>{});const insert=f.db.prepare("INSERT INTO task_creation_intents VALUES(?,?,?,?)");for(let i=1;i<1000;i++)insert.run(crypto.randomUUID(),`task-${i}`,"{}","{}");expect(f.ledger.prepare(f.intent,()=>{})).toEqual(original);const different={...f.intent,eventId:crypto.randomUUID(),taskId:"another-task",workspaceRepoName:"t-p123456789abc-another-task"};expect(()=>f.ledger.prepare(different,()=>{})).toThrow("capacity");expect(f.ledger.get(f.intent.eventId)).toEqual(original);}finally{f.db.close();}});

test("unborn creation retains a genuinely absent source and requires exact empty-ref proof",()=>{const f=fixture();try{const target={kind:"unborn" as const,projectId:f.intent.projectId,incarnation:f.intent.incarnation,canonicalRepoName:f.intent.canonicalRepoName,ref:"refs/heads/trunk",branch:"trunk",acceptedCommit:null,acceptedVersion:0 as const,requirements:[] as [],policyVersion:1,policy:{}};const intent={...f.intent,selection:{...f.intent.selection,baseCommit:null,acceptedTarget:target}};expect(()=>f.ledger.prepare({...intent,selection:{...intent.selection,acceptedTarget:null}},()=>{})).toThrow("explicit unborn");expect(()=>f.ledger.prepare({...intent,selection:{...intent.selection,baseCommit:"b".repeat(40)}},()=>{})).toThrow("invent");f.ledger.prepare(intent,()=>{});f.ledger.beginFork(intent.eventId,()=>{});const proof={...f.proof,sourceCommit:null};expect(()=>f.ledger.confirmFork(intent.eventId,proof,()=>{})).toThrow("original allocation");expect(()=>f.ledger.confirmFork(intent.eventId,{...proof,emptySourceProof:{ref:"refs/heads/main",refs:[]}},()=>{})).toThrow("original allocation");expect(f.ledger.confirmFork(intent.eventId,{...proof,emptySourceProof:{ref:target.ref,refs:[]}},()=>{}).phase).toBe("fork_confirmed");expect(f.ledger.commit(intent.eventId,()=>{},record=>{expect(record.selection.baseCommit).toBeNull();}).phase).toBe("committed");}finally{f.db.close();}});

test("empty source inventory is structurally validated rather than trusting a zero length property",()=>{const f=fixture();try{const proof={...f.proof,sourceCommit:null};for(const refs of ["",{length:0},["refs/heads/other"],null])expect(taskForkCompletionProofSchema.safeParse({...proof,emptySourceProof:{ref:"refs/heads/trunk",refs}}).success).toBe(false);expect(taskForkCompletionProofSchema.safeParse({...proof,emptySourceProof:{ref:"refs/heads/trunk",refs:[]}}).success).toBe(true);}finally{f.db.close();}});

test("the Git zero OID cannot masquerade as an initial source commit",()=>{const f=fixture();try{expect(()=>f.ledger.prepare({...f.intent,selection:{...f.intent.selection,baseCommit:"0".repeat(40)}},()=>{})).toThrow("real commit");expect(taskForkCompletionProofSchema.safeParse({...f.proof,sourceCommit:"0".repeat(40)}).success).toBe(false);}finally{f.db.close();}});

test("a fork completion cannot claim both a committed source and empty history",()=>{const f=fixture();try{expect(taskForkCompletionProofSchema.safeParse({...f.proof,emptySourceProof:{ref:"refs/heads/trunk",refs:[]}}).success).toBe(false);}finally{f.db.close();}});
