import {effectiveTaskAcceptedTarget,type CommittedAcceptedTarget} from "../src/core/accepted-target";
import {Database} from "bun:sqlite";
import {test,expect} from "bun:test";
import {TaskTargetGenerations,type TaskTargetGenerationIntent,type TaskTargetGenerationSettlement} from "../src/server/task-target-generations";
function fixture(){const db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=bindings.length===0&&query.split(";").filter(value=>value.trim()).length>1?(db.exec(query),[]):db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(callback:()=>T){return db.transaction(callback)();}};return{db,ledger:new TaskTargetGenerations(storage as unknown as DurableObjectStorage)};}
function intent():TaskTargetGenerationIntent&{target:CommittedAcceptedTarget;source:TaskTargetGenerationIntent["source"]&{baseCommit:string;currentCommit:string;originalAcceptedTarget:CommittedAcceptedTarget}}{const target={projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",ref:"refs/heads/release",branch:"release",acceptedCommit:"a".repeat(40),acceptedVersion:1,requirements:[],policyVersion:1,policy:{test:"original"}};return{eventId:crypto.randomUUID(),expectedGeneration:0,projectId:target.projectId,incarnation:target.incarnation,canonicalRepoName:target.canonicalRepoName,ownerId:"owner",actor:{userId:"owner",displayName:"Owner",viaToken:false},source:{taskId:"task",goal:"Preserve purpose",contributorId:"contributor",workspaceRepoName:"workspace",branch:"task/change",baseCommit:target.acceptedCommit,currentCommit:"b".repeat(40),requirements:[],snapshotDigest:"c".repeat(64),originalAcceptedTarget:target},target:{...target,policyVersion:2,policy:{test:"new-policy"}},change:{kind:"policy-refresh"}};}
function settled(value:TaskTargetGenerationIntent):TaskTargetGenerationSettlement{return{eventId:value.eventId,taskId:value.source.taskId,previousGeneration:value.expectedGeneration,sourceSnapshotDigest:value.source.snapshotDigest,coverage:"complete",native:"stopped",proposals:"settled",git:{kind:"unchanged",baseCommit:value.source.baseCommit,currentCommit:value.source.currentCommit}};}
test("explicit policy generation preserves creation binding and Git input, requiring positive settlement before activation",()=>{
 const{db,ledger}=fixture(),value=intent(),original=JSON.stringify(value.source.originalAcceptedTarget);try{expect(()=>ledger.prepare(value,()=>{throw Error("Owner revoked");})).toThrow("Owner revoked");expect(ledger.current("task")).toBeNull();const prepared=ledger.prepare(value,()=>{});expect(prepared.phase).toBe("prepared");expect(ledger.current("task")).toBeNull();expect(()=>ledger.activate(value.eventId,()=>({...settled(value),coverage:"unknown"} as unknown as TaskTargetGenerationSettlement),()=>{})).toThrow();expect(ledger.get(value.eventId)?.phase).toBe("prepared");const activated=ledger.activate(value.eventId,()=>settled(value),()=>{});expect(activated.activation).toMatchObject({git:"unchanged",baseCommit:value.source.baseCommit,currentCommit:value.source.currentCommit});expect(JSON.stringify(activated.source.originalAcceptedTarget)).toBe(original);expect(ledger.current("task")?.eventId).toBe(value.eventId);expect(ledger.get(value.eventId)?.target.policyVersion).toBe(2);}finally{db.close();}
});
test("stable event replay never rebinds after root advance or rewinds a newer active generation",()=>{
 const{db,ledger}=fixture(),first=intent();try{ledger.prepare(first,()=>{});const active=ledger.activate(first.eventId,()=>settled(first),()=>{});expect(()=>ledger.prepare({...first,target:{...first.target,acceptedCommit:"d".repeat(40)}},()=>{})).toThrow();const second:TaskTargetGenerationIntent={...first,eventId:crypto.randomUUID(),expectedGeneration:1,target:{...first.target,policyVersion:3,policy:{test:"third"}}};ledger.prepare(second,()=>{});ledger.activate(second.eventId,()=>settled(second),()=>{});const current=ledger.current("task");expect(ledger.activate(first.eventId,()=>{throw Error("Must not reprove completed operation");},()=>{})).toEqual(active);expect(ledger.current("task")).toEqual(current);expect(ledger.history("task").generations).toHaveLength(2);expect(ledger.get(first.eventId)?.target.policyVersion).toBe(2);}finally{db.close();}
});
test("actual rebase generation requires exact verified receipt and distinguishes changed base from metadata refresh",()=>{
 const{db,ledger}=fixture(),value=intent(),receiptId=crypto.randomUUID();try{const rebased:TaskTargetGenerationIntent&{target:CommittedAcceptedTarget}={...value,target:{...value.target,acceptedCommit:"d".repeat(40)},change:{kind:"rebase",receiptId}};ledger.prepare(rebased,()=>{});expect(()=>ledger.activate(value.eventId,()=>settled(rebased),()=>{})).toThrow("rebase receipt");const proof:TaskTargetGenerationSettlement={...settled(rebased),git:{kind:"rebased",receiptId,oldBase:value.source.baseCommit,oldCommit:value.source.currentCommit,newBase:rebased.target.acceptedCommit,newCommit:"e".repeat(40),remoteVerified:true}};expect(()=>ledger.activate(value.eventId,()=>({...proof,git:{...proof.git,receiptId:crypto.randomUUID()}} as TaskTargetGenerationSettlement),()=>{})).toThrow("receipt");const record=ledger.activate(value.eventId,()=>proof,()=>{});expect(record.activation).toMatchObject({git:"rebased",baseCommit:"d".repeat(40),currentCommit:"e".repeat(40),receiptId});expect(record.source.baseCommit).toBe(value.source.baseCommit);expect(record.source.currentCommit).toBe(value.source.currentCommit);}finally{db.close();}
});
test("competing prepared generation and changed actor/creation scope cannot replace active generation",()=>{
 const{db,ledger}=fixture(),value=intent();try{expect(()=>ledger.prepare({...value,actor:{...value.actor,userId:"other"}},()=>{})).toThrow("owner");ledger.prepare(value,()=>{});const competing={...value,eventId:crypto.randomUUID(),target:{...value.target,policyVersion:3}};ledger.prepare(competing,()=>{});ledger.activate(value.eventId,()=>settled(value),()=>{});expect(()=>ledger.activate(competing.eventId,()=>settled(competing),()=>{})).toThrow("generation changed");expect(ledger.get(competing.eventId)?.phase).toBe("prepared");expect(()=>ledger.prepare({...value,eventId:crypto.randomUUID(),expectedGeneration:1,source:{...value.source,workspaceRepoName:"other"}},()=>{})).toThrow("creation binding");expect(ledger.current("task")?.eventId).toBe(value.eventId);}finally{db.close();}
});

test("stacked historical workspace base supports policy refresh while accepted target head stays unchanged",()=>{
 const{db,ledger}=fixture(),value=intent();value.source.baseCommit="3".repeat(40);value.source.currentCommit="4".repeat(40);
 try{ledger.prepare(value,()=>{});const refreshed=ledger.activate(value.eventId,()=>settled(value),()=>{});expect(refreshed.activation).toMatchObject({git:"unchanged",baseCommit:"3".repeat(40),currentCommit:"4".repeat(40)});expect(refreshed.target.acceptedCommit).toBe(value.source.originalAcceptedTarget.acceptedCommit);
 const advance:TaskTargetGenerationIntent={...value,eventId:crypto.randomUUID(),expectedGeneration:1,target:{...value.target,acceptedCommit:"d".repeat(40)}};expect(()=>ledger.prepare(advance,()=>{})).toThrow("cannot advance accepted target history");expect(ledger.current(value.source.taskId)?.eventId).toBe(value.eventId);expect(ledger.get(advance.eventId)).toBeNull();}
 finally{db.close();}
});
test("policy refresh compares the active generation root after a proven rebase, preserving original creation head",()=>{
 const{db,ledger}=fixture(),original=intent(),receiptId=crypto.randomUUID(),rebase:TaskTargetGenerationIntent={...original,target:{...original.target,acceptedCommit:"d".repeat(40)},change:{kind:"rebase",receiptId}};
 try{ledger.prepare(rebase,()=>{});ledger.activate(rebase.eventId,()=>({...settled(rebase),git:{kind:"rebased",receiptId,oldBase:rebase.source.baseCommit,oldCommit:rebase.source.currentCommit,newBase:"d".repeat(40),newCommit:"e".repeat(40),remoteVerified:true}}),()=>{});
 const refresh:TaskTargetGenerationIntent={...original,eventId:crypto.randomUUID(),expectedGeneration:1,source:{...original.source,baseCommit:"d".repeat(40),currentCommit:"e".repeat(40),snapshotDigest:"f".repeat(64)},target:{...rebase.target,policyVersion:3}};ledger.prepare(refresh,()=>{});const record=ledger.activate(refresh.eventId,()=>settled(refresh),()=>{});expect(record.activation).toMatchObject({git:"unchanged",baseCommit:"d".repeat(40),currentCommit:"e".repeat(40)});expect(record.source.originalAcceptedTarget.acceptedCommit).toBe("a".repeat(40));expect(ledger.get(rebase.eventId)?.activation?.git).toBe("rebased");}
 finally{db.close();}
});
test("unborn policy refresh preserves null base while first committed target requires an actual root rebase",()=>{const {db,ledger}=fixture();try{const seed=intent(),unborn={...seed.target,kind:"unborn" as const,acceptedCommit:null,acceptedVersion:0 as const,requirements:[] as []},value:TaskTargetGenerationIntent={...seed,source:{...seed.source,baseCommit:null,originalAcceptedTarget:unborn},target:{...unborn,policyVersion:2}};ledger.prepare(value,()=>{});const result=ledger.activate(value.eventId,()=>settled(value),()=>{});expect(result.activation?.baseCommit).toBeNull();expect(result.activation?.currentCommit).toBe(value.source.currentCommit);const firstAccepted={...seed.target,acceptedCommit:"d".repeat(40),acceptedVersion:1,policyVersion:3};const next:TaskTargetGenerationIntent={...value,eventId:crypto.randomUUID(),expectedGeneration:1,target:firstAccepted};expect(()=>ledger.prepare(next,()=>{})).toThrow("cannot advance");const receiptId=crypto.randomUUID(),rebased:TaskTargetGenerationIntent={...next,change:{kind:"rebase",receiptId}};ledger.prepare(rebased,()=>{});const applied=ledger.activate(rebased.eventId,()=>({...settled(rebased),git:{kind:"rebased",receiptId,oldBase:null,oldCommit:value.source.currentCommit,newBase:firstAccepted.acceptedCommit,newCommit:"e".repeat(40),remoteVerified:true}}),()=>{});expect(applied.activation?.baseCommit).toBe(firstAccepted.acceptedCommit);expect(value.source.originalAcceptedTarget.acceptedCommit).toBeNull();}finally{db.close();}});
test("accepted parent alignment advances an unborn target using exact publication proof without claiming rebase",()=>{const {db,ledger}=fixture();try{const seed=intent(),parent="parent-task",parentCommit="d".repeat(40),original={...seed.target,kind:"unborn" as const,acceptedCommit:null,acceptedVersion:0 as const,requirements:[] as []},value:TaskTargetGenerationIntent={...seed,source:{...seed.source,dependsOn:parent,baseCommit:parentCommit,originalAcceptedTarget:original},target:{...seed.target,acceptedCommit:parentCommit},change:{kind:"accepted-parent-alignment",parentTaskId:parent}};ledger.prepare(value,()=>{});expect(()=>ledger.activate(value.eventId,()=>settled(value),()=>{})).toThrow("publication");const proof:TaskTargetGenerationSettlement&{git:Extract<TaskTargetGenerationSettlement["git"],{kind:"aligned-parent"}>}={...settled(value),git:{kind:"aligned-parent",parentTaskId:parent,parentCandidateId:"accepted-candidate",journalId:"accepted-journal",parentTarget:{projectId:value.target.projectId,incarnation:value.target.incarnation,canonicalRepoName:value.target.canonicalRepoName,ref:value.target.ref,acceptedCommit:parentCommit,acceptedVersion:value.target.acceptedVersion},parentCheckpoint:parentCommit,acceptedCommit:parentCommit,baseCommit:parentCommit,currentCommit:value.source.currentCommit,ancestryVerified:true}};expect(()=>ledger.activate(value.eventId,()=>({...proof,git:{...proof.git,parentCheckpoint:"e".repeat(40)}} as TaskTargetGenerationSettlement),()=>{})).toThrow("publication");expect(()=>ledger.activate(value.eventId,()=>({...proof,git:{...proof.git,parentTarget:{...proof.git.parentTarget,ref:"refs/heads/other"}}} as TaskTargetGenerationSettlement),()=>{})).toThrow("publication");const record=ledger.activate(value.eventId,()=>proof,()=>{});expect(record.activation).toMatchObject({git:"aligned-parent",baseCommit:parentCommit,currentCommit:value.source.currentCommit,parentTaskId:parent,journalId:"accepted-journal"});expect(record.source.originalAcceptedTarget.acceptedCommit).toBeNull();expect(record.source.baseCommit).toBe(parentCommit);}finally{db.close();}});
test("native child based on P aligns only after P becomes the reviewed first accepted root",async()=>{
 const {mkdtemp,rm}=await import("node:fs/promises"),{tmpdir}=await import("node:os"),{join}=await import("node:path"),{gitOrThrow}=await import("../src/core/pipeline/git"),{publishUnbornRoot}=await import("../src/core/pipeline/unborn");const directory=await mkdtemp(join(tmpdir(),"flaregit-parent-alignment-")),{db,ledger}=fixture();
 try{const canonical=join(directory,"canonical.git"),work=join(directory,"work"),seed=intent();gitOrThrow(directory,["init","--bare","--quiet","-b","release",canonical]);gitOrThrow(directory,["init","--quiet","-b","task/parent",work]);await Bun.write(join(work,"README.md"),"Parent root\n");gitOrThrow(work,["add","README.md"]);gitOrThrow(work,["-c","user.name=Fixture","-c","user.email=fixture@example.test","commit","--quiet","-m","Parent source"]);const parentCommit=gitOrThrow(work,["rev-parse","HEAD"]),tree=gitOrThrow(work,["rev-parse","HEAD^{tree}"]);gitOrThrow(work,["checkout","--quiet","-b","task/child"]);await Bun.write(join(work,"child.ts"),"export const child = true;\n");gitOrThrow(work,["add","child.ts"]);gitOrThrow(work,["-c","user.name=Fixture","-c","user.email=fixture@example.test","commit","--quiet","-m","Child source"]);const childCommit=gitOrThrow(work,["rev-parse","HEAD"]),original={...seed.target,kind:"unborn" as const,acceptedCommit:null,acceptedVersion:0 as const,requirements:[] as []};
 const candidate={candidateId:"native-parent",baseline:{kind:"unborn" as const,canonicalRepoName:"canonical",providerRepoId:"local-native",repositoryIncarnation:seed.incarnation,defaultRef:original.ref,expectedHead:null},commit:parentCommit,tree};expect(publishUnbornRoot(canonical,work,candidate,{candidateId:candidate.candidateId,commit:parentCommit,tree,actorId:"reviewer",decision:"approved"},{candidateId:candidate.candidateId,commit:parentCommit,tree,passed:true}).accepted).toBe(true);
 db.exec("CREATE TABLE native_parent_acceptance(journal_id TEXT PRIMARY KEY,candidate_id TEXT,commit_id TEXT)");db.query("INSERT INTO native_parent_acceptance VALUES(?,?,?)").run("native-journal",candidate.candidateId,parentCommit);
 const value:TaskTargetGenerationIntent={...seed,source:{...seed.source,dependsOn:"parent-task",baseCommit:parentCommit,currentCommit:childCommit,originalAcceptedTarget:original},target:{...seed.target,acceptedCommit:parentCommit},change:{kind:"accepted-parent-alignment",parentTaskId:"parent-task"}};ledger.prepare(value,()=>{});
 const activated=ledger.activate(value.eventId,()=>{const accepted=db.query("SELECT * FROM native_parent_acceptance WHERE journal_id=?").get("native-journal") as {candidate_id:string;commit_id:string};expect(gitOrThrow(canonical,["rev-parse",original.ref],{gitDir:true})).toBe(accepted.commit_id);gitOrThrow(work,["merge-base","--is-ancestor",parentCommit,childCommit]);return{...settled(value),git:{kind:"aligned-parent",parentTaskId:"parent-task",parentCandidateId:accepted.candidate_id,journalId:"native-journal",parentTarget:{projectId:value.projectId,incarnation:value.incarnation,canonicalRepoName:value.canonicalRepoName,ref:original.ref,acceptedCommit:accepted.commit_id,acceptedVersion:value.target.acceptedVersion},parentCheckpoint:parentCommit,acceptedCommit:accepted.commit_id,baseCommit:parentCommit,currentCommit:childCommit,ancestryVerified:true}};},()=>{});expect(activated.activation?.git).toBe("aligned-parent");expect(gitOrThrow(work,["rev-parse","HEAD"])).toBe(childCommit);expect(activated.activation?.baseCommit).toBe(parentCommit);expect(activated.source.originalAcceptedTarget.acceptedCommit).toBeNull();
 }finally{db.close();await rm(directory,{recursive:true,force:true});}
});
test('retarget generation changes accepted branch only with exact unchanged-head ancestry proof and preserves original source',()=>{
 const {db,ledger}=fixture(),value=intent(),receiptId=value.eventId;
 const retarget:TaskTargetGenerationIntent={...value,target:{...value.target,ref:'refs/heads/new-base',branch:'new-base',acceptedCommit:'d'.repeat(40),acceptedVersion:0},change:{kind:'retarget',receiptId}};
 try{
  ledger.prepare(retarget,()=>{});expect(()=>ledger.activate(retarget.eventId,()=>settled(retarget),()=>{})).toThrow('retarget ancestry');
  const proof:TaskTargetGenerationSettlement={...settled(retarget),git:{kind:'retargeted',receiptId,oldBase:retarget.source.baseCommit,oldCommit:retarget.source.currentCommit,newBase:retarget.target.acceptedCommit!,currentCommit:retarget.source.currentCommit,ancestryVerified:true}};
  const activated=ledger.activate(retarget.eventId,()=>proof,()=>{});expect(activated.activation).toMatchObject({git:'retargeted',baseCommit:'d'.repeat(40),currentCommit:retarget.source.currentCommit});
  expect(activated.source.originalAcceptedTarget.ref).toBe('refs/heads/release');expect(activated.source.baseCommit).toBe(value.source.baseCommit);
  const projected={acceptedTarget:retarget.source.originalAcceptedTarget,baseCommit:activated.activation!.baseCommit,currentCommit:activated.activation!.currentCommit,targetGeneration:{eventId:activated.eventId,generation:activated.generation,acceptedTarget:activated.target,baseCommit:activated.activation!.baseCommit,currentCommit:activated.activation!.currentCommit}};
  expect(()=>effectiveTaskAcceptedTarget(projected)).toThrow('scope');expect(effectiveTaskAcceptedTarget({...projected,targetGeneration:{...projected.targetGeneration,retargetedFrom:{ref:'refs/heads/release',branch:'release'}}})?.ref).toBe('refs/heads/new-base');

  const refresh:TaskTargetGenerationIntent={...retarget,eventId:crypto.randomUUID(),expectedGeneration:1,source:{...retarget.source,baseCommit:'d'.repeat(40)},target:{...retarget.target,policyVersion:3},change:{kind:'policy-refresh'}};ledger.prepare(refresh,()=>{});ledger.activate(refresh.eventId,()=>settled(refresh),()=>{});expect(ledger.current('task')?.target.ref).toBe('refs/heads/new-base');
 }finally{db.close();}
});
