import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {workerdChild} from './support/workerd-child';
import {q} from '../src/server/shell';
test('retarget signed HTTP activates native-proven base, rejects duplicate live execution and retains failed cleanup for exact recovery',async()=>{
 if(await workerdChild('tests/task-retarget-http.test.ts'))return;
 const root=await mkdtemp(join(tmpdir(),'flaregit-retarget-http-')),work=join(root,'source'),remote=join(root,'fork.git'),env={...process.env,GIT_AUTHOR_NAME:'Original author',GIT_AUTHOR_EMAIL:'original@example.invalid',GIT_COMMITTER_NAME:'Original author',GIT_COMMITTER_EMAIL:'original@example.invalid'};
 const git=async(command:string)=>{const child=Bun.spawn(['sh','-c',command],{env,stdout:'pipe',stderr:'pipe'});const [stdout,stderr,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(code)throw Error(stderr);return stdout.trim();};
 let postNativePaused=false,releasePostNative:(()=>void)|undefined;
 let paused=false,pauseNext=false,release:(()=>void)|undefined,bridge:ReturnType<typeof Bun.serve>|undefined,issuer:ReturnType<typeof Bun.serve>|undefined,mf:Miniflare|undefined;
 try{
  await git(`git init -q -b main ${q(work)} && git init -q --bare ${q(remote)}`);await Bun.write(join(work,'initial'),'A');await git(`git -C ${q(work)} add . && git -C ${q(work)} commit -qm Initial`);const target=await git(`git -C ${q(work)} rev-parse HEAD`);
  await Bun.write(join(work,'accepted'),'B');await git(`git -C ${q(work)} add . && git -C ${q(work)} commit -qm Accepted`);const base=await git(`git -C ${q(work)} rev-parse HEAD`);
  await Bun.write(join(work,'authored'),'C');await git(`git -C ${q(work)} add . && git -C ${q(work)} commit -qm Authored && git -C ${q(work)} push -q ${q(remote)} HEAD:refs/heads/task/change`);const head=await git(`git -C ${q(work)} rev-parse HEAD`);
  await git(`git --git-dir ${q(remote)} update-ref refs/heads/main ${base} && git --git-dir ${q(remote)} update-ref refs/heads/release ${target}`);
  bridge=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){if(new URL(request.url).pathname==='/post-native'){postNativePaused=true;await new Promise<void>(resolve=>{releasePostNative=resolve;});return Response.json({ok:true});}const input=await request.json() as {nativeId:string;command:string};if(pauseNext){pauseNext=false;paused=true;await new Promise<void>(resolve=>{release=resolve;});}const command=input.command.replaceAll('https://'+'a'.repeat(32)+'.artifacts.cloudflare.net/workspace',remote).replaceAll('/workspace/retarget-inspection',join(root,input.nativeId)),child=Bun.spawn(['sh','-c',command],{env,stdout:'pipe',stderr:'pipe'});const [stdout,stderr,exitCode]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);return Response.json({success:exitCode===0,stdout,stderr,exitCode});}});
  const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'retarget-http',alg:'RS256',use:'sig'};issuer=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({keys:[jwk]})});
  const output=join(root,'worker.js'),build=Bun.spawn([process.execPath,'build','tests/support/task-retarget-http-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*','--outfile='+output],{stdout:'ignore',stderr:'pipe'});if(await build.exited)throw Error(await new Response(build.stderr).text());
  mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'retarget-http',unsafeDirectSockets:[{host:'127.0.0.1'}],modules:true,script:await Bun.file(output).text(),compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],bindings:{FIXTURE_ISSUER:issuer.url.origin,OWNED_NATIVE_URL:bridge.url.origin,REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:'1000000',REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:'1000000',MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:'100000000',MANAGED_ACCOUNT_MONTHLY_USD_MICROS:'100000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'100000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'100000000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'100000000'},r2Buckets:['EVIDENCE_BUCKET'],durableObjects:{REPOSITORY_CONTROLLER:{className:'TaskRetargetHttpFixture',useSQLite:true}}}]}));
  const origin=await mf.unsafeGetDirectURL('retarget-http'),session=(subject:string)=>new SignJWT({azp:'https://fixture.example'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer!.url.origin).setSubject(subject).setIssuedAt().setExpirationTime('5m').sign(pair.privateKey),owner=await session('owner'),reader=await session('reader');
  const call=(path:string,token?:string,value?:unknown)=>fetch(new URL(path,origin),{method:value===undefined?'GET':'POST',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.41',...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},...(value===undefined?{}:{body:JSON.stringify(value)})});
  const seeded=await call('/fixture/seed',undefined,{base,head,target});if(!seeded.ok)throw Error(await seeded.text());const fixture=await seeded.json() as {target:{ref:string;acceptedCommit:string;acceptedVersion:number;policyVersion:number}};
  const path='/api/p/p123456789abc/tasks/change',request={requestId:crypto.randomUUID(),expectedGeneration:0,expectedHead:head,target:fixture.target};expect((await call(path+'/retarget',reader,request)).status).toBe(403);
  pauseNext=true;const pending=call(path+'/retarget',owner,request);for(let attempt=0;attempt<200&&!paused;attempt++)await Bun.sleep(10);if(!paused){release?.();throw Error('Owned native inspection did not start');}
  expect((await call(path+'/retarget',owner,request)).status).toBe(409);expect((await call(path+'/token',owner,{})).status).toBe(403);
  expect(await(await call(path+'/retargets',owner)).json()).toMatchObject({operations:[{requestId:request.requestId,cleanupRequired:true}]});release?.();release=undefined;
  const activated=await pending;if(!activated.ok)throw Error(await activated.text());expect(await activated.json()).toMatchObject({phase:'activated',cleanupRequired:false,requiresFreshReadiness:true});
  const state=await(await call('/api/p/p123456789abc/state',owner)).json() as {tasks:Record<string,{baseCommit:string;currentCommit:string;status:string;contributor:{name:string};acceptedTarget:{ref:string};targetGeneration:{generation:number;acceptedTarget:{ref:string}}}>};expect(state.tasks.change).toMatchObject({baseCommit:target,currentCommit:head,status:'checkpointed',contributor:{name:'Original author'},acceptedTarget:{ref:'refs/heads/main'},targetGeneration:{generation:1,acceptedTarget:{ref:'refs/heads/release'}}});expect(await git(`git --git-dir ${q(remote)} rev-parse refs/heads/task/change`)).toBe(head);
  await call('/fixture/mode',undefined,{stopped:false});const targets=await(await call('/api/p/p123456789abc/contribution-targets',owner)).json() as {targets:Array<typeof fixture.target>},main=targets.targets.find(item=>item.ref==='refs/heads/main')!,second={requestId:crypto.randomUUID(),expectedGeneration:1,expectedHead:head,target:{ref:main.ref,acceptedCommit:main.acceptedCommit,acceptedVersion:main.acceptedVersion,policyVersion:main.policyVersion}};
  const held=await call(path+'/retarget',owner,second);expect(held.status).toBe(200);expect(await held.json()).toMatchObject({phase:'prepared',cleanupRequired:true});expect((await call(path+'/retarget',owner,second)).status).toBe(409);expect((await call(path+'/token',owner,{})).status).toBe(403);
  await call('/fixture/mode',undefined,{stopped:true});const recovered=await call(path+'/retargets/'+second.requestId+'/recover',owner,{});if(!recovered.ok)throw Error(await recovered.text());const recoveredOperation=await recovered.json() as {phase:string;cleanupRequired:boolean;originalRequest:typeof second};expect(recoveredOperation).toMatchObject({phase:'prepared',cleanupRequired:false,originalRequest:second});expect((await call(path+'/token',owner,{})).status).toBe(200);
  const resumed=await call(path+'/retarget',owner,recoveredOperation.originalRequest);expect(resumed.status).toBe(200);expect(await resumed.json()).toMatchObject({phase:'activated',cleanupRequired:false});expect(await git(`git --git-dir ${q(remote)} rev-parse refs/heads/task/change`)).toBe(head);
  await call('/fixture/arm-post-native',undefined,{});const recoveredDuringCommit={requestId:crypto.randomUUID(),expectedGeneration:2,expectedHead:head,target:fixture.target},late=call(path+'/retarget',owner,recoveredDuringCommit);
  for(let attempt=0;attempt<200&&!postNativePaused;attempt++)await Bun.sleep(10);if(!postNativePaused){releasePostNative?.();throw Error('Post-native authority pause was not reached');}
  const releaseLease=await call(path+'/retargets/'+recoveredDuringCommit.requestId+'/recover',owner,{});if(!releaseLease.ok)throw Error(await releaseLease.text());expect(await releaseLease.json()).toMatchObject({cleanupRequired:false,phase:'prepared'});
  expect((await call(path+'/token',owner,{})).status).toBe(200);const write=await(await call('/fixture/git-write-start',undefined,{})).json() as {id:string};
  await Bun.write(join(work,'after-recovery'),'D');await git(`git -C ${q(work)} add . && git -C ${q(work)} commit -qm AfterRecovery`);const pushed=await git(`git -C ${q(work)} rev-parse HEAD`);await git(`git -C ${q(work)} push -q ${q(remote)} HEAD:refs/heads/task/change`);const settled:unknown=await(await call('/fixture/git-write-finish',undefined,{id:write.id})).json();expect(settled).toEqual({settled:true});
  releasePostNative?.();releasePostNative=undefined;const stale=await late;expect(stale.status).toBe(200);expect(await stale.json()).toMatchObject({phase:'prepared',cleanupRequired:false});
  const unchanged=await(await call('/api/p/p123456789abc/state',owner)).json() as typeof state;expect(unchanged.tasks.change).toMatchObject({baseCommit:base,currentCommit:head,targetGeneration:{generation:2,acceptedTarget:{ref:'refs/heads/main'}}});expect(await git(`git --git-dir ${q(remote)} rev-parse refs/heads/task/change`)).toBe(pushed);
 }finally{release?.();releasePostNative?.();await mf?.dispose();bridge?.stop(true);issuer?.stop(true);await rm(root,{recursive:true,force:true});}
},60000);
