import {Database} from "bun:sqlite";
import {test,expect} from "bun:test";
import {mkdtemp,mkdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {gitOrThrow,PLATFORM_IDENTITY} from "../src/core/pipeline/git";
import {TaskTargetGenerations,type TaskTargetGenerationIntent,type TaskTargetGenerationSettlement} from "../src/server/task-target-generations";
// Local native Git proof plus real SQLite generation receipts; no hosted or human-approval claim.
test("actual rebase onto an already contained target can advance recorded base while preserving the exact HEAD",async()=>{
 const root=await mkdtemp(join(tmpdir(),"flaregit-rebase-noop-")),work=join(root,"work"),remote=join(root,"workspace.git"),db=new Database(":memory:"),storage={sql:{exec(query:string,...bindings:Array<string|number>){const rows=bindings.length===0&&query.split(";").filter(value=>value.trim()).length>1?(db.exec(query),[]):db.query(query).all(...bindings);return{toArray:()=>rows,one:()=>rows[0]};}},transactionSync<T>(fn:()=>T){return db.transaction(fn)();}} as unknown as DurableObjectStorage,ledger=new TaskTargetGenerations(storage);
 try{await mkdir(work);gitOrThrow(work,["init","-b","release"]);await Bun.write(join(work,"base.txt"),"A\n");gitOrThrow(work,["add","."]);gitOrThrow(work,[...PLATFORM_IDENTITY,"commit","-m","Initial accepted base"]);const oldBase=gitOrThrow(work,["rev-parse","HEAD"]);await Bun.write(join(work,"accepted.txt"),"B\n");gitOrThrow(work,["add","."]);gitOrThrow(work,[...PLATFORM_IDENTITY,"commit","-m","Already contained accepted target"]);const target=gitOrThrow(work,["rev-parse","HEAD"]);gitOrThrow(root,["init","--bare",remote]);gitOrThrow(work,["checkout","-b","task/change"]);gitOrThrow(work,["push",remote,"HEAD:refs/heads/task/change"]);const before=gitOrThrow(work,["rev-parse","HEAD"]);gitOrThrow(work,[...PLATFORM_IDENTITY,"rebase","--onto",target,oldBase]);const after=gitOrThrow(work,["rev-parse","HEAD"]);expect(after).toBe(before);expect(target).not.toBe(oldBase);gitOrThrow(work,["push",`--force-with-lease=refs/heads/task/change:${before}`,remote,`${after}:refs/heads/task/change`]);expect(gitOrThrow(work,["ls-remote","--refs",remote,"refs/heads/task/change"])).toBe(`${after}\trefs/heads/task/change`);const original={projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",ref:"refs/heads/release",branch:"release",acceptedCommit:oldBase,acceptedVersion:0,requirements:[],policyVersion:1,policy:{}},receiptId=crypto.randomUUID(),intent:TaskTargetGenerationIntent={eventId:crypto.randomUUID(),expectedGeneration:0,projectId:original.projectId,incarnation:original.incarnation,canonicalRepoName:original.canonicalRepoName,ownerId:"owner",actor:{userId:"owner",displayName:"Owner",viaToken:false},source:{taskId:"task",goal:"Keep already contained work",contributorId:"contributor",workspaceRepoName:"workspace",branch:"task/change",baseCommit:oldBase,currentCommit:before,requirements:[],snapshotDigest:"a".repeat(64),originalAcceptedTarget:original},target:{...original,acceptedCommit:target,acceptedVersion:1},change:{kind:"rebase",receiptId}};ledger.prepare(intent,()=>{});const proof:TaskTargetGenerationSettlement={eventId:intent.eventId,taskId:intent.source.taskId,previousGeneration:0,sourceSnapshotDigest:intent.source.snapshotDigest,coverage:"complete",native:"stopped",proposals:"settled",git:{kind:"rebased",receiptId,oldBase,oldCommit:before,newBase:target,newCommit:after,remoteVerified:true}};expect(()=>ledger.activate(intent.eventId,()=>({...proof,git:{...proof.git,remoteVerified:false}} as unknown as TaskTargetGenerationSettlement),()=>{})).toThrow();expect(ledger.current("task")).toBeNull();const activated=ledger.activate(intent.eventId,()=>proof,()=>{});expect(activated.activation).toMatchObject({git:"rebased",baseCommit:target,currentCommit:before,receiptId});expect(activated.source.originalAcceptedTarget.acceptedCommit).toBe(oldBase);expect(ledger.activate(intent.eventId,()=>proof,()=>{})).toEqual(activated);expect(gitOrThrow(remote,["rev-parse","refs/heads/task/change"],{gitDir:true})).toBe(before);
 }finally{db.close();await rm(root,{recursive:true,force:true});}
});
