import {expect,test} from "bun:test";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {gitOrThrow} from "../src/core/pipeline/git";
import {freezeCandidateGeneration} from "../src/core/pipeline/freeze";
import {verifyNativeIntegrity} from "../src/core/verification/integrity";
import type {Task} from "../src/core/types";
import type {UnbornAcceptedTarget} from "../src/core/accepted-target";
test("actual P and child C retain the pending parent base through first-batch freeze and native verification",async()=>{
 const directory=await mkdtemp(join(tmpdir(),"flaregit-stacked-first-freeze-"));try{gitOrThrow(directory,["init","--quiet","-b","task/parent"]);await Bun.write(join(directory,"README.md"),"Parent source\n");gitOrThrow(directory,["add","README.md"]);gitOrThrow(directory,["-c","user.name=Parent","-c","user.email=parent@example.test","commit","--quiet","-m","Parent root"]);const parentCommit=gitOrThrow(directory,["rev-parse","HEAD"]);gitOrThrow(directory,["checkout","--quiet","-b","task/child"]);await Bun.write(join(directory,"src/child.ts"),"export const child = true;\n");gitOrThrow(directory,["add","src/child.ts"]);gitOrThrow(directory,["-c","user.name=Child","-c","user.email=child@example.test","commit","--quiet","-m","Child work"]);const childCommit=gitOrThrow(directory,["rev-parse","HEAD"]),tree=gitOrThrow(directory,["rev-parse","HEAD^{tree}"]);
 const target:UnbornAcceptedTarget={kind:"unborn",projectId:"project",incarnation:crypto.randomUUID(),canonicalRepoName:"canonical",ref:"refs/heads/main",branch:"main",acceptedCommit:null,acceptedVersion:0,requirements:[],policyVersion:1,policy:{kind:"git-integrity"}},baseTask={goal:"Actual initial work",contributor:{id:"person",name:"Person",type:"human" as const},acceptedTarget:target,status:"ready" as const,requirements:[],workspace:{repoName:"workspace",remote:"https://fixture.invalid",branch:"task/source"},checkpoints:[],createdAt:"now",updatedAt:"now"},parent:Task={...baseTask,id:"parent",baseCommit:null,currentCommit:parentCommit,allowedScope:["README.md"]},child:Task={...baseTask,id:"child",dependsOn:parent.id,baseCommit:parentCommit,currentCommit:childCommit,allowedScope:["src/"]};
 const options={acceptedTarget:target,acceptedBaseCommit:null,policyVersion:1,verificationPolicy:target.policy,approvedRequirements:[]};const candidate=freezeCandidateGeneration({...options,tasks:[parent,child]});expect(candidate.expectedAcceptedBase).toBeNull();expect(candidate.frozenContributorProofs?.[1]).toMatchObject({baseCommit:parentCommit,stackedOn:{taskId:parent.id,commit:parentCommit,ref:"refs/flaregit/tasks/parent"}});expect(()=>freezeCandidateGeneration({...options,tasks:[child]})).toThrow("reviewed batch");expect(()=>freezeCandidateGeneration({...options,tasks:[parent,{...child,baseCommit:"b".repeat(40)}]})).toThrow("checkpoint");
 gitOrThrow(directory,["update-ref","refs/flaregit/tasks/parent",parentCommit]);gitOrThrow(directory,["update-ref","refs/flaregit/tasks/child",childCommit]);const evidence=await verifyNativeIntegrity({repoDir:directory,candidateCommit:childCommit,candidateTree:tree,expectedBase:null,acceptedTarget:target,requirementsVersion:1,policy:target.policy,protectedPaths:[".env"],allowedScope:["README.md","src/"],contributors:candidate.frozenContributorProofs!,landing:"merge"});expect(evidence.status).toBe("passed");expect(child.baseCommit).toBe(parentCommit);expect(target.acceptedCommit).toBeNull();
 }finally{await rm(directory,{recursive:true,force:true});}
});
