import {test,expect} from "bun:test";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {workerdChild} from "./support/workerd-child";
import {untrustedExecutionName} from "../src/server/untrusted-execution";
import {bindBuildManifest,type StaticBuildScope} from "../src/server/static-build-artifact";
test("actual Sandbox durably recovers bounded completed bytes after lost reply without redispatch; native port synthetic",async()=>{if(await workerdChild("tests/untrusted-output-recovery.test.ts"))return;const built=await Bun.build({entrypoints:["tests/support/untrusted-output-recovery-worker.ts"],target:"browser",external:["cloudflare:workers","node:*"]});if(!built.success)throw Error("Recovery fixture build failed");const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"output-recovery",modules:true,script:await built.outputs[0]!.text(),compatibilityDate:"2026-10-04",durableObjects:{UNTRUSTED_EXECUTION:{className:"OutputRecoveryFixture",useSQLite:true}}}]}));try{const worker=await mf.getWorker("output-recovery"),scope=():StaticBuildScope=>({attemptId:crypto.randomUUID(),projectId:"p123456789abc",incarnation:crypto.randomUUID(),commit:"a".repeat(40),tree:"b".repeat(40),policyDigest:"c".repeat(64)}),call=(action:string,original:StaticBuildScope,extra:Record<string,unknown>={})=>worker.fetch("http://test",{method:"POST",body:JSON.stringify({action,scope:original,...extra})}),original=scope();expect((await call("read",original)).status).toBe(200);expect((await call("run",original)).status).toBe(503);const recovered=await call("read",original);expect(recovered.status).toBe(200);const output=await recovered.json() as{runs:number;header:{manifestChunks:number};artifact:{scope:StaticBuildScope;cleanup:string;acceptanceEvidence:boolean;totalBytes:number;firstByte:number;manifest:{files:unknown[]}}};expect(output.runs).toBe(1);expect(output.header.manifestChunks).toBeGreaterThan(1);expect(output.artifact).toMatchObject({scope:original,cleanup:"confirmed",acceptanceEvidence:false,totalBytes:150511,firstByte:65});expect(output.artifact.manifest.files).toHaveLength(512);expect(await(await call("read",original)).json()).toEqual(output);
 const source=await bindBuildManifest("source",original,[{path:"index.html",kind:"file",bytes:new TextEncoder().encode("Synthetic source")}]),name=await untrustedExecutionName(original,source.digest);expect((await(await call("read",{...original,tree:"f".repeat(40)},{name,sourceDigest:source.digest})).json() as{artifact:unknown}).artifact).toBeNull();expect((await(await call("read",original,{sourceDigest:"0".repeat(64)})).json() as{artifact:unknown}).artifact).toBeNull();
 for(const mode of ["partial","missing","corrupt","image","unsettled"]){const input=scope();expect((await call("run",input)).status).toBe(503);await call("alter",input,{mode});const reply=await call("read",input);if(mode==="missing"||mode==="corrupt")expect(reply.status).toBe(409);else expect((await reply.json() as{artifact:unknown}).artifact).toBeNull();}
 }finally{await mf.dispose();}},30000);
