import {expect,test} from "bun:test";
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,chmodSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {gitOrThrow,PLATFORM_IDENTITY} from "../src/core/pipeline/git";
import {createCommandVerifier} from "../src/core/verification/command";
import {verifyInIsolation} from "../src/core/verification/isolated";
const secret="SYNTHETIC_OUTPUT_SECRET_12345";
function fixture(){const root=mkdtempSync(join(tmpdir(),"flaregit-diagnostic-evidence-"));chmodSync(root,0o755);const repo=join(root,"repo");mkdirSync(repo);mkdirSync(join(repo,"src"));writeFileSync(join(repo,"src/index.ts"),"export const answer=42;");gitOrThrow(repo,["init","--quiet"]);gitOrThrow(repo,["add","."]);gitOrThrow(repo,[...PLATFORM_IDENTITY,"commit","--quiet","-m","Synthetic evidence"]);const sha=gitOrThrow(repo,["rev-parse","HEAD"]);return {root,ctx:{repoDir:repo,candidateCommit:sha,expectedBase:sha,requirementsVersion:1,policy:{}}};}
test("command evidence keeps failure and safe output while removing credential-shaped output",async()=>{const f=fixture();try{const verifier=createCommandVerifier({kind:"command",test:`printf 'useful failure\\nAuthorization: Bearer ${secret}\\n' >&2; exit 7`,allowedScope:["*"]});const evidence=await verifier.verify(f.ctx);expect(evidence.status).toBe("failed");expect(evidence.candidateCommit).toBe(f.ctx.candidateCommit);expect(evidence.candidateTree).toBe(gitOrThrow(f.ctx.repoDir,["rev-parse","HEAD^{tree}"]));const message=evidence.testResults[0]!.items[0]!.message!;expect(message).toContain("exit 7");expect(message).toContain("useful failure");expect(message).toContain("[REDACTED]");expect(message).not.toContain(secret);expect(JSON.stringify(evidence.testResults)).not.toContain(secret);const passed=await createCommandVerifier({kind:"command",test:`printf 'Authorization: Bearer ${secret}\\n'`,allowedScope:["*"]}).verify(f.ctx);expect(passed.status).toBe("passed");expect(passed.testResults[0]!.items[0]!.message).toBeUndefined();}finally{rmSync(f.root,{recursive:true,force:true});}});
test("isolated observation crashes and parent diagnostic results are sanitized without changing decisions",async()=>{const f=fixture();try{const checks=join(f.root,"checks.ts"),observe=join(f.root,"observe.ts");writeFileSync(checks,`export async function runChecks(){return [{testId:'safe',description:'Safe check',passed:false,message:'useful failure Authorization: Bearer ${secret}',durationMs:0}];}`);writeFileSync(observe,"export async function observe(){return {answer:42};}");const spec={identity:"synthetic-check",suite:"Synthetic",checksModule:checks,observationModule:observe};const result=await verifyInIsolation(spec,f.ctx);expect(result.status).toBe("failed");expect(result.candidateCommit).toBe(f.ctx.candidateCommit);expect(JSON.stringify(result.testResults)).not.toContain(secret);expect(result.testResults[0]!.items.find(i=>i.testId==='safe')?.message).toContain("useful failure");writeFileSync(observe,`console.error('useful crash Authorization: Bearer ${secret}');process.exit(9);`);const crash=await verifyInIsolation(spec,f.ctx);expect(crash.status).toBe("failed");expect(JSON.stringify(crash.testResults)).not.toContain(secret);expect(JSON.stringify(crash.testResults)).toContain("useful crash");for(const output of ["Authorization: Bearer "+secret.repeat(300),"-----BEGIN PRIVATE KEY-----\n"+secret.repeat(300)+"\n-----END PRIVATE KEY-----"]){writeFileSync(observe,`console.error(${JSON.stringify(output)});process.exit(9);`);const overflow=await verifyInIsolation(spec,f.ctx);expect(overflow.status).toBe("failed");expect(JSON.stringify(overflow.testResults)).toContain("capture limit");expect(JSON.stringify(overflow.testResults)).not.toContain(secret);}}finally{rmSync(f.root,{recursive:true,force:true});}},30000);

test("oversized secret lines are omitted before truncation can remove credential delimiters",async()=>{const f=fixture();try{for(const line of ["Authorization: Bearer "+"SYNTHETIC_LONG_SECRET".repeat(1200),"-----BEGIN PRIVATE KEY-----\n"+"SYNTHETIC_PEM_SECRET".repeat(1200)+"\n-----END PRIVATE KEY-----"]){writeFileSync(join(f.ctx.repoDir,"emit.txt"),line);gitOrThrow(f.ctx.repoDir,["add","emit.txt"]);gitOrThrow(f.ctx.repoDir,[...PLATFORM_IDENTITY,"commit","--quiet","-m","Synthetic large output"]);const sha=gitOrThrow(f.ctx.repoDir,["rev-parse","HEAD"]);const evidence=await createCommandVerifier({kind:"command",test:"cat emit.txt >&2; exit 9",allowedScope:["*"]}).verify({...f.ctx,candidateCommit:sha});expect(evidence.status).toBe("failed");expect(evidence.candidateCommit).toBe(sha);const result=JSON.stringify(evidence.testResults);expect(result).toContain("exit 9");expect(result).toContain("capture limit");expect(result).not.toContain("SYNTHETIC_LONG_SECRET");expect(result).not.toContain("SYNTHETIC_PEM_SECRET");}}finally{rmSync(f.root,{recursive:true,force:true});}});
