import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {publicationInHistory} from '../src/server/publication';
import {workerdChild} from './support/workerd-child';
test('actual Workflow caller preserves prepared lost-ACK journal and reconciles original release after write authority withdrawal',async()=>{
 if(await workerdChild('tests/workflow-publication-recovery-native.test.ts'))return;
 const directory=await mkdtemp(join(tmpdir(),'flaregit-workflow-ack-'));let mf:Miniflare|undefined,bridge:ReturnType<typeof Bun.serve>|undefined;
 const git=async(...args:string[])=>{const process=Bun.spawn(['git',...args],{cwd:directory,stdout:'pipe',stderr:'pipe'});const result=await new Response(process.stdout).text();if(await process.exited!==0)throw Error('Native recovery fixture failed');return result.trim();};
 try{await git('init','-b','main');await git('config','user.name','Synthetic fixture');await git('config','user.email','fixture@example.test');await Bun.write(join(directory,'base.txt'),'Accepted base');await git('add','base.txt');await git('commit','-m','Base');const base=await git('rev-parse','HEAD');await git('branch','release');await git('checkout','release');await Bun.write(join(directory,'release.txt'),'Reviewed release');await git('add','release.txt');await git('commit','-m','Reviewed release');const commit=await git('rev-parse','HEAD'),tree=await git('rev-parse','HEAD^{tree}'),remote=join(directory,'canonical.git');await git('init','--bare',remote);await git('push',remote,base+':refs/heads/main',commit+':refs/heads/release');
 const target={projectId:'project',incarnation:crypto.randomUUID(),canonicalRepoName:'canonical',ref:'refs/heads/release',branch:'release',acceptedCommit:base,acceptedVersion:1,requirements:[],policyVersion:2,policy:{test:'bun test'}};
 const candidate={id:'candidate_frozen',acceptedTarget:target,attemptNumber:1,participatingTaskIds:['task'],participatingCommits:{task:commit},expectedAcceptedBase:base,frozenPolicyVersion:2,frozenVerificationPolicy:{test:'bun test'},frozenRequirements:[],repairAttempts:[],status:'awaiting_review',candidateCommit:commit,createdAt:'now',updatedAt:'now'};
 const journal={id:'journal_original',acceptedTarget:target,candidateId:candidate.id,candidateCommit:commit,candidateTree:tree,expectedHead:base,newHead:commit,outputDigest:'fixture',state:'PREPARED',timestamp:'now',publicationAuthority:{acceptedTarget:target,commit,tree,policyVersion:2,actor:{userId:'owner',displayName:'Original owner',viaToken:false},reviewedAt:'now',authorizedAt:'now'}};
 const state={projectId:'project',canonicalRepoName:'canonical',defaultBranch:'main',acceptedState:{currentCommit:base,history:[],activeRequirements:[]},tasks:{},candidates:{[candidate.id]:candidate},journal:[journal]};
 const observedRefs:string[]=[];bridge=Bun.serve({hostname:'127.0.0.1',port:0,fetch:async request=>{const value=await request.json() as {ref:string;commit:string;mode:string};observedRefs.push(value.ref);if(value.mode==='unavailable')return Response.json({status:'unavailable',ref:value.ref,commit:value.commit});if(value.mode==='wrong_ref')return Response.json({status:'landed',ref:'refs/heads/main',commit:value.commit,readbackScope:'native-original-ref-proof'});if(value.ref!=='refs/heads/release')throw Error('Unexpected recovery ref');const landed=await publicationInHistory(async command=>{const process=Bun.spawn(['sh','-c',command],{cwd:directory,stdout:'ignore',stderr:'ignore'});const exitCode=await process.exited;return{success:exitCode===0,exitCode};},directory,remote,'synthetic','release',value.commit);return Response.json({status:landed?'landed':'not_landed',ref:value.ref,commit:value.commit,...(landed?{readbackScope:'native-original-ref-proof'}:{})});}});
 const output=join(directory,'workflow-fixture.js'),build=Bun.spawn([process.execPath,'build','tests/support/workflow-publication-recovery-worker.ts','--target=browser','--external=cloudflare:workers','--external=node:*','--outfile='+output],{stdout:'ignore',stderr:'pipe'});const buildErrors=await new Response(build.stderr).text();if(await build.exited!==0)throw Error(buildErrors);mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'workflow-recovery',modules:true,script:await Bun.file(output).text(),compatibilityDate:'2026-10-02',compatibilityFlags:['nodejs_compat'],bindings:{NATIVE_BRIDGE:bridge.url.href}}]}));const worker=await mf.getWorker('workflow-recovery');
 const run=async(mode:string)=>{const response=await worker.fetch('http://test/run',{method:'POST',body:JSON.stringify({candidate,state,journal,commit,mode})});return response.json() as Promise<{result:{status:string;publicationPending?:boolean;error?:string};journalState:string;calls:string[]}>;};
 const pending=await run('unavailable');expect(pending.result).toMatchObject({status:'blocked',publicationPending:true});expect(pending.journalState).toBe('PREPARED');expect(pending.calls).not.toContain('abort');expect(pending.calls).not.toContain('new-write-authority');expect(pending.calls).not.toContain('credential-allocation');expect(pending.calls).not.toContain('sandbox-allocation');
 const wrongRef=await run('wrong_ref');expect(wrongRef.result).toMatchObject({status:'blocked',publicationPending:true});expect(wrongRef.result.error).toContain('another target or commit');expect(wrongRef.journalState).toBe('PREPARED');expect(wrongRef.calls).not.toContain('complete');
 const recovered=await run('readback');expect(recovered.result.status).toBe('accepted');expect(recovered.journalState).toBe('ACCEPTED');expect(recovered.calls).toContain('complete');expect(recovered.calls).not.toContain('new-write-authority');expect(recovered.calls).not.toContain('credential-allocation');expect(recovered.calls).not.toContain('sandbox-allocation');expect(observedRefs).toEqual(['refs/heads/release','refs/heads/release','refs/heads/release']);expect(await git('--git-dir='+remote,'rev-parse','refs/heads/main')).toBe(base);expect(await git('--git-dir='+remote,'rev-parse','refs/heads/release')).toBe(commit);
 }finally{await mf?.dispose();bridge?.stop(true);await rm(directory,{recursive:true,force:true});}
},30000);
