import {expect,test} from 'bun:test';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {workerdChild} from './support/workerd-child';
test('native HTTP workflow controls preserve context and registered identity; provider is synthetic',async()=>{
 if(await workerdChild('tests/workflow-control-http.test.ts'))return;
 const pair=await generateKeyPair('RS256'),jwk={...await exportJWK(pair.publicKey),kid:'workflow',alg:'RS256',use:'sig'};
 const issuer=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({keys:[jwk]})});let mf:Miniflare|undefined;
 try{const build=await Bun.build({entrypoints:['tests/support/workflow-control-http-worker.ts'],target:'browser',external:['cloudflare:workers','node:*']});if(!build.success)throw Error('Fixture build failed');mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'workflow-control',unsafeDirectSockets:[{host:'127.0.0.1'}],modules:true,script:await build.outputs[0]!.text(),compatibilityDate:'2026-10-03',compatibilityFlags:['nodejs_compat'],bindings:{FIXTURE_ISSUER:issuer.url.origin},durableObjects:{REPOSITORY_CONTROLLER:{className:'WorkflowControlFixture',useSQLite:true}}}]}));
 const direct=await mf.unsafeGetDirectURL('workflow-control'),call=(path:string,token?:string,post=false)=>fetch(new URL(path,direct),{method:post?'POST':'GET',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.26',...(token?{Authorization:'Bearer '+token}:{})}});
 const session=(subject:string)=>new SignJWT({azp:'https://fixture.example'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer.url.origin).setSubject(subject).setIssuedAt().setExpirationTime('5m').sign(pair.privateKey);
 const owner=await session('owner'),initiator=await session('initiator'),member=await session('member');
 const route=(instance:string,action?:string)=>'/api/p/p123456789abc/workflows/'+instance+(action?'/'+action:'');
 const mode=async(value:string)=>expect((await call('/fixture/mode?mode='+value)).status).toBe(200),calls=async()=>await(await call('/fixture/calls')).json() as string[],snapshot=async()=>await(await call('/fixture/snapshot')).json() as {state:unknown;comments:unknown;activity:Array<{type:string}>};
 const seeded=await call('/fixture/seed');expect(seeded.status).toBe(200);const syntheticToken=(await seeded.json() as {token:string}).token;const scenarios='/api/p/p123456789abc/scenarios';expect((await call(scenarios)).status).toBe(401);expect((await call(scenarios,member)).status).toBe(403);const inventory=await call(scenarios,owner);expect(inventory.status).toBe(200);expect(inventory.headers.get('cache-control')).toBe('no-store');const page=await inventory.json() as {runs:Array<{instanceId:string;kind:string;status:string}>;nextCursor:string;providerVerified:boolean};expect(page.runs).toHaveLength(20);expect(page.runs[0]!.instanceId).toBe('scenario-23');expect(page.runs.every(row=>row.kind==='scenario'&&row.status==='unknown')).toBe(true);expect(page.providerVerified).toBe(false);const next=await(await call(scenarios+'?cursor='+page.nextCursor,owner)).json() as {runs:unknown[];nextCursor:null};expect(next.runs).toHaveLength(4);expect(next.nextCursor).toBeNull();expect((await call(scenarios,syntheticToken)).status).toBe(200);for(const query of ['?cursor=0','?cursor=1&cursor=2','?workflow=foreign'])expect((await call(scenarios+query,owner)).status).toBe(400);expect(await calls()).toEqual([]);await mode('scenario-withdraw');const withdrawn=await call(scenarios,owner);expect(withdrawn.status).toBe(403);expect(await withdrawn.text()).not.toContain('scenario-23');await mode('running');
 const freshOwner=await session('owner');expect(await(await call(scenarios,freshOwner)).json() as typeof page).toEqual(page);
 const issueToken=async(scope:'read'|'write'|'full',repo?:string)=>{const result=await call('/fixture/scenario-token?scope='+scope+(repo?'&repo='+repo:''));expect(result.status).toBe(200);return(await result.json() as {token:string}).token;};
 for(const token of [await issueToken('read'),await issueToken('write'),await issueToken('full','pffffffffffff')]){const denied=await call(scenarios,token);expect(denied.status).toBe(403);expect(await denied.text()).not.toContain('scenario-23');}
 const revocableScenarioToken=await issueToken('full');await mode('scenario-revoke-token');const tokenChanged=await call(scenarios,revocableScenarioToken);expect(tokenChanged.status).toBe(401);expect(await tokenChanged.text()).not.toContain('scenario-23');expect(await calls()).toEqual([]);
 for(const race of ['scenario-delete','scenario-incarnation']){await mode(race);const changed=await call(scenarios,owner);expect(changed.status).toBe(403);expect(await changed.text()).not.toContain('scenario-23');expect(await calls()).toEqual([]);if(race==='scenario-delete')expect((await call('/fixture/restore-deletion')).status).toBe(200);}
 await mode('running');const recovered=await call(scenarios,freshOwner);expect(recovered.status).toBe(200);expect((await recovered.json() as {runs:unknown[]}).runs).toEqual(page.runs);
 const agentRecovery='/api/p/p123456789abc/agent-runtime/recovery';expect((await call(agentRecovery)).status).toBe(401);expect((await call(agentRecovery,member)).status).toBe(403);expect((await call(agentRecovery,await issueToken('read'))).status).toBe(403);expect((await call(agentRecovery,await issueToken('write'))).status).toBe(403);expect((await call(agentRecovery,await issueToken('full','pffffffffffff'))).status).toBe(403);
 const summary=await call(agentRecovery,owner);expect(summary.status).toBe(200);expect(summary.headers.get('cache-control')).toBe('no-store');expect(await summary.json() as {attempts:unknown[];truncated:boolean;providerVerified:boolean}).toEqual({attempts:[],truncated:false,providerVerified:false});expect((await call(agentRecovery+'?account=foreign',owner)).status).toBe(400);
 const recover=(body:unknown,token=owner)=>fetch(new URL(agentRecovery,direct),{method:'POST',headers:{Connection:'close','CF-Connecting-IP':'198.51.100.26',Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});
 for(const body of [{attemptId:'invalid'},{attemptId:crypto.randomUUID(),accountKey:'foreign'}])expect((await recover(body)).status).toBe(400);expect((await recover({attemptId:crypto.randomUUID()},member)).status).toBe(403);const unknownRecovery=await recover({attemptId:crypto.randomUUID()});expect(unknownRecovery.status).toBe(409);expect(await unknownRecovery.text()).not.toContain('synthetic secret');expect(await calls()).toEqual([]);
 await mode('agent-summary-withdraw');const deniedSummary=await call(agentRecovery,owner);expect(deniedSummary.status).toBe(409);expect(await deniedSummary.json() as {error:string}).not.toHaveProperty('attempts');await mode('running');
 const reviewSettings='/api/p/p123456789abc/review-settings',reviewPolicy='/api/p/p123456789abc/review-policy',reviewGrants='/api/p/p123456789abc/review-grants',delegated='/api/p/p123456789abc/candidates/candidate_saved/delegated-reviews';
 const reviewCall=(path:string,token:string,method:string,payload:unknown)=>fetch(new URL(path,direct),{method,headers:{Connection:'close','CF-Connecting-IP':'198.51.100.26',Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(payload)});
 expect((await call(reviewSettings,member)).status).toBe(403);expect((await call(reviewSettings,await issueToken('read'))).status).toBe(403);expect((await call(reviewSettings,await issueToken('write'))).status).toBe(403);const settings=await call(reviewSettings,owner);expect(settings.status).toBe(200);expect(settings.headers.get('cache-control')).toBe('no-store');expect(await settings.json() as unknown).toMatchObject({policy:{version:0,policy:{requiredApprovals:0,allowAuthorApproval:false}},grants:[]});
 const policyRequest={eventId:'policy-event-123',expectedVersion:0,policy:{requiredApprovals:1,allowAuthorApproval:false}};expect((await reviewCall(reviewPolicy,member,'PUT',policyRequest)).status).toBe(403);expect((await reviewCall(reviewPolicy,owner,'PUT',{...policyRequest,policy:{requiredApprovals:11,allowAuthorApproval:false}})).status).toBe(400);expect((await reviewCall(reviewPolicy,owner,'PUT',{...policyRequest,ownerId:'member'})).status).toBe(400);expect((await reviewCall(reviewPolicy,owner,'PUT',policyRequest)).status).toBe(200);expect((await reviewCall(reviewPolicy,owner,'PUT',policyRequest)).status).toBe(200);
 expect((await reviewCall(reviewGrants,member,'POST',{eventId:'grant-event-123',userId:'member',expectedVersion:0,enabled:true})).status).toBe(403);expect((await reviewCall(reviewGrants,owner,'POST',{eventId:'grant-event-123',userId:'member',expectedVersion:0,enabled:true})).status).toBe(200);
 const decision={eventId:'review-event-123',expectedCommit:'a'.repeat(40),grantVersion:1,decision:'approve'};expect((await reviewCall(delegated,await issueToken('full'),'POST',decision)).status).toBe(403);for(const payload of [{...decision,reviewerId:'owner'},{...decision,expectedCommit:'short'},{...decision,note:'x'.repeat(5001)},{...decision,grantVersion:-1}])expect((await reviewCall(delegated,member,'POST',payload)).status).toBe(400);expect((await reviewCall(delegated,member,'POST',decision)).status).toBe(409);expect(await calls()).toEqual([]);
 const migrations='/api/p/p123456789abc/conversation-migrations';expect((await call(migrations)).status).toBe(401);expect((await call(migrations,member)).status).toBe(403);expect((await call(migrations,await issueToken('read'))).status).toBe(403);expect((await call(migrations,await issueToken('write'))).status).toBe(403);
 for(const payload of [null,[],{operationId:'saved-operation',sourceUrl:'https://evil.test/private'},{operationId:'saved-operation',repositoryId:'123'},{operationId:'bad/id'},{operationId:'saved-operation',actorId:'member'}])expect((await reviewCall(migrations,owner,'POST',payload)).status).toBe(400);
 expect((await reviewCall(migrations+'/saved-operation/capture',owner,'POST',{expectedRevision:0,cursor:'forged'})).status).toBe(400);expect((await reviewCall(migrations+'/saved-operation/publish',owner,'POST',{eventId:'publish-event',expectedRevision:0,manifestHash:'short'})).status).toBe(400);expect((await reviewCall(migrations+'/saved-operation/publish',member,'POST',{eventId:'publish-event',expectedRevision:0,manifestHash:'a'.repeat(64)})).status).toBe(403);expect((await call(migrations+'?source=foreign',owner)).status).toBe(400);expect(await calls()).toEqual([]);
 await mode('conversation-funding-denied');const unfundedMigration=await reviewCall(migrations,owner,'POST',{operationId:'saved-migration'});expect(unfundedMigration.status).toBe(503);expect(await unfundedMigration.json() as unknown).toMatchObject({category:'read_budget_unconfigured'});expect(await calls()).toEqual([]);await mode('running');
 const branches='/api/p/p123456789abc/branches',branchOperations='/api/p/p123456789abc/branch-operations',publicBranches='/api/public/p123456789abc/branches',branchRequest={operationId:crypto.randomUUID(),name:'feature/new',sourceCommit:'a'.repeat(40)};
 expect((await call(branches)).status).toBe(401);expect((await reviewCall(branches,member,'POST',branchRequest)).status).toBe(403);expect((await reviewCall(branches,await issueToken('write'),'POST',branchRequest)).status).toBe(403);expect((await call(branchOperations,member)).status).toBe(403);expect((await call(branchOperations,await issueToken('read'))).status).toBe(403);
 for(const payload of [null,[],{...branchRequest,name:'main'},{...branchRequest,sourceCommit:'0'.repeat(40)},{...branchRequest,name:'refs/heads/forged'},{...branchRequest,name:'HEAD'},{...branchRequest,name:'../unsafe'},{...branchRequest,sourceCommit:'main'},{...branchRequest,operationId:'unsafe/op'},{...branchRequest,actorId:'member'},{...branchRequest,canonicalRepoName:'foreign'}])expect((await reviewCall(branches,owner,'POST',payload)).status).toBe(400);
 const reconcileBranch=branchOperations+'/'+branchRequest.operationId+'/reconcile';expect((await reviewCall(reconcileBranch,member,'POST',{expectedPhase:'unknown'})).status).toBe(403);expect((await reviewCall(reconcileBranch,owner,'POST',{expectedPhase:'prepared'})).status).toBe(400);expect((await reviewCall(reconcileBranch,owner,'POST',{expectedPhase:'unknown',sourceCommit:'b'.repeat(40)})).status).toBe(400);expect((await reviewCall(reconcileBranch,owner,'POST',{expectedPhase:'unknown'})).status).toBe(409);
 expect((await call(publicBranches)).status).toBe(404);expect((await call('/fixture/visibility?value=public')).status).toBe(200);const publicInventory=await call(publicBranches);expect(publicInventory.status).toBe(200);expect(publicInventory.headers.get('cache-control')).toBe('no-store');expect(await publicInventory.json() as unknown).toMatchObject({branches:[{name:'main',ref:'refs/heads/main',commit:'a'.repeat(40)}],truncated:false,providerVerified:false,source:'published-accepted-state'});expect((await call(publicBranches+'?ref=unaccepted')).status).toBe(400);await mode('public-branch-revoke');expect((await call(publicBranches)).status).toBe(409);expect((await call(publicBranches)).status).toBe(404);expect(await calls()).toEqual([]);await mode('running');
 const branchRecovery='/api/p/p123456789abc/branch-runtime/recovery',stopInput={attemptId:crypto.randomUUID(),operationId:crypto.randomUUID(),confirmStop:true};expect((await call(branchRecovery)).status).toBe(401);expect((await call(branchRecovery,member)).status).toBe(403);expect((await call(branchRecovery,await issueToken('read'))).status).toBe(403);expect((await call(branchRecovery,await issueToken('write'))).status).toBe(403);const branchSummary=await call(branchRecovery,owner);expect(branchSummary.status).toBe(200);expect(await branchSummary.json() as unknown).toMatchObject({attempts:[],truncated:false,providerVerified:false});expect((await call(branchRecovery+'?nativeId=foreign',owner)).status).toBe(400);
 for(const payload of [null,[],{...stopInput,confirmStop:false},{...stopInput,nativeId:'foreign'},{...stopInput,attemptId:'unsafe'}])expect((await reviewCall(branchRecovery,owner,'POST',payload)).status).toBe(400);expect((await reviewCall(branchRecovery,member,'POST',stopInput)).status).toBe(403);expect((await reviewCall(branchRecovery,owner,'POST',stopInput)).status).toBe(409);expect(await calls()).toEqual([]);await mode('branch-summary-withdraw');const withdrawnBranch=await call(branchRecovery,owner);expect(withdrawnBranch.status).toBe(409);expect(await withdrawnBranch.json() as {error:string}).not.toHaveProperty('attempts');await mode('running');
 const abandonedId=crypto.randomUUID(),abandonPath=branchOperations+'/'+abandonedId+'/abandon';expect((await call('/fixture/prepared-branch?operationId='+abandonedId)).status).toBe(200);const beforeAbandon=await snapshot();expect((await reviewCall(abandonPath,member,'POST',{expectedPhase:'prepared'})).status).toBe(403);expect((await reviewCall(abandonPath,owner,'POST',{expectedPhase:'unknown'})).status).toBe(400);expect((await reviewCall(abandonPath,owner,'POST',{expectedPhase:'prepared',force:true})).status).toBe(400);const abandoned=await reviewCall(abandonPath,owner,'POST',{expectedPhase:'prepared'});expect(abandoned.status).toBe(200);expect(await abandoned.json() as unknown).toMatchObject({operationId:abandonedId,phase:'refused',reason:'owner_abandoned_prepared'});expect((await reviewCall(abandonPath,owner,'POST',{expectedPhase:'prepared'})).status).toBe(200);expect((await snapshot()).state).toEqual(beforeAbandon.state);expect(await calls()).toEqual([]);
 expect((await call(route('agent-owned'))).status).toBe(401);const before=await snapshot();
 for(const [token,instance] of [[member,'agent-owned'],[initiator,'integration-owned']]){await mode('running');expect((await call(route(instance!,'pause'),token,true)).status).toBe(403);expect(await calls()).toEqual([]);}
 await mode('running');expect((await call(route('foreign-run','pause'),owner,true)).status).toBe(404);expect(await calls()).toEqual([]);
 await mode('pending');const pending=await call(route('agent-owned','pause'),initiator,true);expect(pending.status).toBe(200);const raw=await pending.text();expect(raw).not.toContain('synthetic secret');expect(JSON.parse(raw)).toMatchObject({instanceId:'agent-owned',kind:'agent',status:'waitingForPause',changed:true});expect((await snapshot()).state).toEqual(before.state);expect((await snapshot()).comments).toEqual(before.comments);
 expect((await(await call(route('agent-owned','pause'),initiator,true)).json() as {changed:boolean}).changed).toBe(false);expect((await calls()).filter(value=>value.startsWith('pause:'))).toHaveLength(1);expect((await call(route('agent-owned','resume'),initiator,true)).status).toBe(409);
 await mode('paused');const resumed=await call(route('integration-owned','resume'),owner,true);expect(resumed.status).toBe(200);expect(await resumed.json()).toMatchObject({instanceId:'integration-owned',kind:'integration',status:'running',changed:true});expect((await snapshot()).comments).toEqual(before.comments);expect((await snapshot()).state).toEqual(before.state);await call(route('integration-owned','resume'),owner,true);expect((await calls()).filter(value=>value.startsWith('resume:'))).toHaveLength(1);
 for(const [value,code] of [['complete',409],['missing',404],['lookup-failed',503]] as const){await mode(value);const result=await call(route('integration-owned','pause'),owner,true);expect(result.status).toBe(code);expect(await result.text()).not.toContain('synthetic secret');expect((await calls()).some(value=>value.startsWith('pause:'))).toBe(false);}
 await mode('remove-member');const revokedRead=await call(route('agent-owned'),member);expect(revokedRead.status).toBe(403);expect(await revokedRead.text()).not.toContain('instanceId');
 for(const [value,action] of [['pause-failed','pause'],['resume-failed','resume']] as const){await mode(value);const unknown=await call(route('integration-owned',action),owner,true);expect(unknown.status).toBe(503);expect(await unknown.text()).not.toContain('synthetic secret');expect((await snapshot()).activity.some(item=>item.type==='workflow.'+action+'_requested')).toBe(true);}
 await mode('revoke-at-status');const revoked=await call(route('integration-owned','pause'),owner,true);expect(revoked.status).toBe(403);expect((await calls()).some(value=>value.startsWith('pause:'))).toBe(false);
 await mode('multi-owner-revoke');const multiOwner=await call(route('integration-owned','pause'),owner,true);expect(multiOwner.status).toBe(403);expect((await calls()).some(value=>value.startsWith('pause:'))).toBe(false);
 await mode('revoke-at-audit');const auditRevoked=await call(route('integration-owned','pause'),owner,true);expect(auditRevoked.status).toBe(403);expect(await auditRevoked.text()).not.toContain('instanceId');expect((await calls()).filter(value=>value.startsWith('pause:'))).toHaveLength(1);
 await mode('pause-revoke');const revokedAfterDispatch=await call(route('integration-owned','pause'),owner,true);expect(revokedAfterDispatch.status).toBe(403);expect((await calls()).filter(value=>value.startsWith('pause:'))).toHaveLength(1);expect((await snapshot()).activity.some(item=>item.type==='workflow.pause_requested')).toBe(true);
 await mode('revoke-token');const revokedToken=await call(route('integration-owned','pause'),syntheticToken,true);expect(revokedToken.status).toBe(403);expect((await calls()).some(value=>value.startsWith('pause:'))).toBe(false);
 await mode('delete-repository');const sealed=await call(route('agent-owned'),owner);expect(sealed.status).toBe(403);expect(await sealed.text()).not.toContain('instanceId');
 await call('/fixture/restore-deletion');await mode('delete-account');const deletingAccount=await call(route('agent-owned'),owner);expect(deletingAccount.status).toBe(403);expect(await deletingAccount.text()).not.toContain('instanceId');
 }finally{await mf?.dispose();issuer.stop(true);}
},30000);
