import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {apiSessionIdentity} from '../api';
import {acceptancePolicyIntent,persistAcceptancePolicyIntent,readAcceptancePolicy,readAcceptancePolicyIntent,saveAcceptancePolicy,type AcceptancePolicyIntent,type AcceptancePolicyState} from '../acceptance-policy';
export function AcceptancePolicyPanel({projectId,isOwner=false}:{projectId:string;isOwner?:boolean}){
 const identity=apiSessionIdentity(),scope=JSON.stringify([identity,projectId,isOwner]),active=useRef(scope);active.current=scope;
 const generation=useRef(0),abort=useRef<AbortController|null>(null),lock=useRef(false),intent=useRef<AcceptancePolicyIntent|null>(null);
 const [data,setData]=useState<AcceptancePolicyState|null>(null),[readConfirmed,setReadConfirmed]=useState(false),[optIn,setOptIn]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{intent.current=null;setData(null);setReadConfirmed(false);setOptIn(false);setUncertain(false);setError('');setNotice('');lock.current=false;setBusy(false);if(identity&&isOwner){try{intent.current=readAcceptancePolicyIntent(sessionStorage,identity,projectId);if(intent.current){setUncertain(true);setOptIn(intent.current.config.mode==='verified-auto-accept');setNotice('Original policy request restored. Its save outcome is unconfirmed.');}}catch{/* Server policy remains authoritative. */}}},[identity,projectId,isOwner]);
 useEffect(()=>{const current=++generation.current,captured=scope,controller=new AbortController();abort.current=controller;setReadConfirmed(false);setBusy(true);lock.current=true;void readAcceptancePolicy(projectId,AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])).then(value=>{if(current!==generation.current||active.current!==captured)return;setData(value);setReadConfirmed(true);if(!intent.current)setOptIn(value.currentPolicy.mode==='verified-auto-accept');setError('');}).catch(()=>{if(current===generation.current&&!controller.signal.aborted)setError('Current acceptance policy could not be confirmed. New policy changes are paused until it can be read. The last saved server policy may still apply.');}).finally(()=>{if(current===generation.current){setBusy(false);lock.current=false;}});return()=>{generation.current++;controller.abort();abort.current?.abort();};},[identity,projectId,isOwner,revision]);
 const save=async()=>{if(lock.current||!isOwner||!identity||!data||!readConfirmed&&!intent.current)return;const eligible=data.eligibility.origin==='platform-fixture'?data.eligibility.protectedAdapter:null;if(!intent.current&&optIn&&!eligible)return;const config:AcceptancePolicyIntent['config']=optIn&&eligible?{mode:'verified-auto-accept',protectedAdapter:eligible}:{mode:'review-required'};intent.current=acceptancePolicyIntent(intent.current,data.currentPolicy.version,config);const pending=intent.current;let browserSaved=false;try{browserSaved=persistAcceptancePolicyIntent(sessionStorage,identity,projectId,pending);}catch{/* Exact request still retained in memory. */}const current=generation.current,captured=scope,controller=new AbortController();abort.current=controller;lock.current=true;setBusy(true);setUncertain(true);setError('');setNotice('');try{const receipt=await saveAcceptancePolicy(projectId,pending,AbortSignal.any([controller.signal,AbortSignal.timeout(30000)]));if(current!==generation.current||active.current!==captured)return;intent.current=null;persistAcceptancePolicyIntent(sessionStorage,identity,projectId,null);setUncertain(false);setData({...data,currentPolicy:receipt.currentPolicy});setReadConfirmed(true);setOptIn(receipt.currentPolicy.mode==='verified-auto-accept');setNotice(receipt.currentPolicy.version>receipt.appliedVersion?`Original request saved version ${receipt.appliedVersion}. Current policy is version ${receipt.currentPolicy.version}; the earlier mode was not restored.`:`Acceptance policy saved at version ${receipt.appliedVersion}.`);}catch{if(current===generation.current&&active.current===captured)setError(browserSaved?'Save outcome unconfirmed. The original request is saved in this browser session; retry it unchanged or check current policy.':'Save outcome unconfirmed. Keep this page open to retry the original request; browser-session saving is unavailable.');}finally{if(current===generation.current){lock.current=false;setBusy(false);}}};
 const eligible=data?.eligibility.origin==='platform-fixture'&&data.eligibility.protectedAdapter!==null,changed=data&&optIn!==(data.currentPolicy.mode==='verified-auto-accept');
 return <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Acceptance policy</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="text-xs text-muted-foreground">Human review is the default. Eligible protected workflows can accept verified contributions under the configured policy.</p>{data&&<div className="space-y-1"><p className="font-medium">{data.currentPolicy.mode==='review-required'?'Human review required':'Protected verified acceptance'}{!readConfirmed&&<span className="text-xs text-muted-foreground"> · last recorded</span>}</p><p className="text-xs text-muted-foreground break-all">Version {data.currentPolicy.version}{data.currentPolicy.authorizedBy?` · authorized by ${data.currentPolicy.authorizedBy}`:' · default policy'}{data.currentPolicy.protectedAdapter?` · ${data.currentPolicy.protectedAdapter}`:''}</p>{data.currentPolicy.updatedAt!==null&&<p className="text-xs text-muted-foreground">Updated {new Date(data.currentPolicy.updatedAt).toLocaleString()}</p>}</div>}{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}{notice&&<p role="status" className="text-xs">{notice}</p>}{isOwner&&identity&&data&&<>{eligible||data.currentPolicy.mode==='verified-auto-accept'?<label className="flex items-start gap-2 text-xs"><Input type="checkbox" className="h-4 w-4 shrink-0 p-0" checked={optIn} disabled={busy||uncertain||!readConfirmed||!eligible&&!optIn} onChange={event=>setOptIn(event.target.checked)}/><span>Opt into automatic integration and protected verified acceptance for this repository.</span></label>:<p className="text-xs text-muted-foreground">This repository does not have an eligible protected acceptance adapter. Human review remains available.</p>}{eligible&&<p className="text-xs text-muted-foreground">Ready compatible work uses configured execution limits. Exact native, source, build and browser evidence, approved requirements and required reviews must still pass. This setting does not deploy software.</p>}{(eligible||uncertain||data.currentPolicy.mode==='verified-auto-accept')&&<Button size="sm" variant="outline" disabled={busy||!uncertain&&(!changed||!readConfirmed)} onClick={()=>void save()}>{busy?'Checking policy…':uncertain?'Retry original policy request':'Save acceptance policy'}</Button>}</>}<Button size="sm" variant="ghost" disabled={busy} onClick={()=>setRevision(value=>value+1)}>Check current policy</Button></CardContent></Card>;
}
