import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {checkAgentCleanup,readAgentCleanup,type AgentCleanupReport} from '../agent-cleanup-recovery';
export function AgentCleanupRecovery({projectId}:{projectId:string}){
 const [report,setReport]=useState<AgentCleanupReport|null>(null),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const generation=useRef(0),lock=useRef(false),activeScope=useRef(projectId),controller=useRef<AbortController|null>(null);activeScope.current=projectId;
 const [revision,setRevision]=useState(0);
 useEffect(()=>{const current=++generation.current,abort=new AbortController();controller.current=abort;lock.current=true;setReport(null);setBusy('inventory');setError('');setNotice('');void readAgentCleanup(projectId,AbortSignal.any([abort.signal,AbortSignal.timeout(15000)])).then(value=>{if(current===generation.current&&activeScope.current===projectId)setReport(value);}).catch(()=>{if(current===generation.current&&!abort.signal.aborted&&activeScope.current===projectId)setError('Agent cleanup status is unavailable. Check the inventory before relying on shutdown or credential cleanup.');}).finally(()=>{if(current===generation.current&&activeScope.current===projectId){lock.current=false;setBusy(null);}});return()=>{generation.current++;abort.abort();controller.current?.abort();};},[projectId,revision]);
 const check=async(attemptId:string)=>{if(lock.current||!report?.attempts.some(row=>row.attemptId===attemptId))return;lock.current=true;const current=generation.current,scope=projectId,abort=new AbortController();controller.current=abort;setBusy(attemptId);setError('');setNotice('');const valid=()=>current===generation.current&&activeScope.current===scope;try{const result=await checkAgentCleanup(scope,attemptId,AbortSignal.any([abort.signal,AbortSignal.timeout(15000)]));if(!valid())return;setNotice(result.stopped&&result.credentialsComplete?'Workspace shutdown and credential cleanup confirmed. Saved contributions and task context remain available.':result.stopped?'Workspace shutdown confirmed. Credential cleanup remains unconfirmed; the saved attempt is retained.':'Workspace shutdown remains unconfirmed. Its saved attempt and task context are retained.');try{const next=await readAgentCleanup(scope,AbortSignal.any([abort.signal,AbortSignal.timeout(15000)]));if(valid())setReport(next);}catch{if(valid())setError('Cleanup inventory could not be refreshed. Previously listed attempts may be outdated.');}}catch{if(valid())setError('Cleanup was not confirmed. Refresh the inventory or check this same saved attempt again; no replacement workspace is created.');}finally{if(valid()){lock.current=false;setBusy(null);}}};
 if(!error&&!notice&&(!report||(!report.attempts.length&&!report.truncated)))return null;
 return <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Agent cleanup recovery</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="text-xs text-muted-foreground">Check shutdown and credentials for saved agent attempts. Contributions, conversations and repository history stay preserved.</p>{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}{notice&&<p role="status" className="text-xs">{notice}</p>}{report&&<ul className="space-y-3">{report.attempts.map(row=><li key={row.attemptId} className="border-t border-border pt-3 space-y-2"><a className="font-medium underline underline-offset-4 break-all" href={`/#/p/${encodeURIComponent(projectId)}/review?task=${encodeURIComponent(row.taskId)}`}>{row.taskId}</a><p className="text-xs text-muted-foreground">{row.phase==='proposal'?'Proposal':'Applying change'} · generation {row.generation} · {row.stopped?'Shutdown recorded':'Shutdown unconfirmed'}</p><p className="text-xs">Credential cleanup {row.credentialStatuses.some(status=>status!=='revoked')?'unconfirmed':'has no unresolved recorded credentials'}.</p><Button size="sm" variant="outline" disabled={busy!==null} onClick={()=>void check(row.attemptId)}>{busy===row.attemptId?'Checking cleanup…':'Check cleanup'}</Button></li>)}</ul>}{report?.truncated&&<p role="status" className="text-xs text-muted-foreground">Showing up to 20 pending attempts. Check these saved attempts, then refresh to see the remaining inventory.</p>}<Button size="sm" variant="ghost" disabled={busy!==null} onClick={()=>setRevision(value=>value+1)}>{busy==='inventory'?'Checking inventory…':'Refresh cleanup inventory'}</Button></CardContent></Card>;
}
