import React,{useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {apiJson,apiSessionIdentity} from '../api';
import {browserEditSchema,type BrowserEditInput} from '../../server/browser-edit';
import {z} from 'zod';
import {taskCreationTargetSchema} from '../../server/task-creation';
const hex=(buffer:ArrayBuffer)=>Array.from(new Uint8Array(buffer),byte=>byte.toString(16).padStart(2,'0')).join('');
const intentSchema=z.object({taskId:z.string().regex(/^browser-[a-f0-9-]{36}$/),goal:z.string().min(1).max(300),expectedTarget:taskCreationTargetSchema,input:browserEditSchema}).strict();
type Intent=z.infer<typeof intentSchema>;
/** Browser changes always enter the ordinary human contribution and review path. */
export function BrowserEdit({projectId,head,tree,path,content,branchName}:{projectId:string;head:string;tree:string;path?:string;content?:string;branchName?:string}){
  const [open,setOpen]=useState(false),[draft,setDraft]=useState(content??''),[target,setTarget]=useState(path??''),[message,setMessage]=useState(path?`Edit ${path}`:'Upload file'),[upload,setUpload]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{taskId:string;phase:string;commit:string|null;status?:'accepted'|'cancelled'}|null>(null),[uncertain,setUncertain]=useState(false),[recoveryBlocked,setRecoveryBlocked]=useState(false);
  const fileInput=useRef<HTMLInputElement|null>(null),intent=useRef<Intent|null>(null),lock=useRef(false),principal=useRef<string|null>(null);
  const storageKey=(identity:string)=>`flaregit:browser-edit:${identity}:${projectId}:${head}:${path??'upload'}`;
  const recover=()=>{const identity=apiSessionIdentity();if(identity&&!intent.current){try{const raw=sessionStorage.getItem(storageKey(identity));if(raw){const saved=intentSchema.parse(JSON.parse(raw));if(saved.input.expectedHead===head&&saved.input.expectedTree===tree){intent.current=saved;principal.current=identity;setUncertain(true);setTarget(saved.input.path);setMessage(saved.input.message);try{setDraft(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(saved.input.contentBase64),character=>character.charCodeAt(0))));}catch{setDraft('Binary upload preserved in the original request.');}setError('A saved contribution request needs its outcome checked. Retry the original content.');}}}catch{setRecoveryBlocked(true);setError('The saved browser contribution cannot be read. Inspect existing changes before creating another contribution.');}}setOpen(true);};
  const submit=async()=>{
    if(lock.current||recoveryBlocked||result?.phase==='terminal'||result?.phase==='confirmed')return;const identity=apiSessionIdentity();if(!identity){setError('Sign in before creating a contribution.');return;}if(principal.current&&principal.current!==identity){setError('This draft belongs to a different signed-in session.');return;}principal.current=identity;const current=()=>{if(apiSessionIdentity()!==identity)throw Error('Signed-in session changed; the original draft was not reassigned.');};lock.current=true;setBusy(true);setError('');
    try{
      if(!intent.current){
        if(upload&&upload.size>256*1024)throw Error('Browser files are limited to 256 KiB. Use Git for larger changes.');
        const inventory=await apiJson<{targets:Array<z.infer<typeof taskCreationTargetSchema>>}>(`/p/${projectId}/contribution-targets`);current();
        const match=inventory.targets.find(target=>target.acceptedCommit===head&&(!branchName||target.ref===`refs/heads/${branchName}`));
        if(!match)throw Error('This viewed revision is no longer an accepted contribution target. Refresh to its current accepted revision before editing; no change was created.');
        const {ref,acceptedCommit,acceptedVersion,policyVersion}=match,expectedTarget=taskCreationTargetSchema.parse({ref,acceptedCommit,acceptedVersion,policyVersion});
        const bytes=upload?new Uint8Array(await upload.arrayBuffer()):new TextEncoder().encode(draft);if(bytes.length>256*1024)throw Error('Browser files are limited to 256 KiB. Use Git for larger changes.');
        let expectedBlob:string|null=null;if(path&&target===path&&content!==undefined){const original=new TextEncoder().encode(content),header=new TextEncoder().encode(`blob ${original.length}\0`),object=new Uint8Array(header.length+original.length);object.set(header);object.set(original,header.length);expectedBlob=hex(await crypto.subtle.digest('SHA-1',object));}
        const contentBase64=btoa(Array.from(bytes,byte=>String.fromCharCode(byte)).join('')),input:BrowserEditInput={requestId:crypto.randomUUID(),expectedHead:head,expectedTree:tree,path:target,expectedBlob,contentBase64,contentSha256:hex(await crypto.subtle.digest('SHA-256',bytes)),message:message.trim()};
        intent.current={taskId:`browser-${crypto.randomUUID()}`,goal:message.trim(),expectedTarget,input};
      }
      current();sessionStorage.setItem(storageKey(identity),JSON.stringify(intent.current));
      setUncertain(true);const saved=intent.current;
      const creation=await apiJson<{terminal?:boolean;status?:'accepted'|'cancelled'}>(`/p/${projectId}/tasks`,{method:'POST',json:{taskId:saved.taskId,goal:saved.goal,expectedTarget:saved.expectedTarget,browserEdit:true}});
      current();if(creation.terminal){setResult({taskId:saved.taskId,phase:'terminal',commit:null,status:creation.status});setUncertain(false);sessionStorage.removeItem(storageKey(identity));return;}const outcome=await apiJson<{taskId:string;phase:string;commit:string|null}>(`/p/${projectId}/tasks/${saved.taskId}/browser-edit`,{method:'POST',json:saved.input});
      current();setResult(outcome);setUncertain(outcome.phase!=='confirmed');
      if(outcome.phase==='confirmed')sessionStorage.removeItem(storageKey(identity));
      if(outcome.phase!=='confirmed')setError('The original commit is saved but its push is unconfirmed. Retry this exact request to inspect its outcome.');
    }catch(cause){if(apiSessionIdentity()===identity)setError(cause instanceof Error?cause.message:'The original contribution outcome is unknown. Retry without changing its content.');}
    finally{lock.current=false;if(apiSessionIdentity()===identity)setBusy(false);}
  };
  return <><Button size="sm" variant="outline" onClick={recover}>{path?'Edit in contribution':'Upload file'}</Button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogHeader><DialogTitle>{path?'Edit file':'Upload file'}</DialogTitle><DialogDescription>A new human contribution records this change for the repository’s normal review and acceptance flow.</DialogDescription></DialogHeader><div className="space-y-4"><p className="text-xs text-muted-foreground">Based on viewed commit {head.slice(0,7)}.</p><label className="block text-sm space-y-2">File path<Input value={target} maxLength={1024} disabled={busy||uncertain||Boolean(result)} onChange={event=>{intent.current=null;setTarget(event.target.value);}}/></label>{path&&<label className="block text-sm space-y-2">Content<Textarea className="font-mono text-xs max-h-64" rows={8} value={draft} disabled={busy||uncertain||Boolean(result)||Boolean(upload)} onChange={event=>{intent.current=null;setDraft(event.target.value);}}/></label>}<label className="block text-sm space-y-2">{path?'Or replace with a file':'File'}<Input ref={fileInput} type="file" disabled={busy||uncertain||Boolean(result)} onChange={event=>{const file=event.target.files?.[0]??null;intent.current=null;setUpload(file);if(file&&!path)setTarget(file.name);}}/></label>{upload&&<div className="text-xs text-muted-foreground flex flex-wrap items-center gap-2"><span>Selected: {upload.name}</span>{path&&!uncertain&&!result&&<Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>{intent.current=null;setUpload(null);if(fileInput.current)fileInput.current.value='';}}>Use text instead</Button>}</div>}<label className="block text-sm space-y-2">Commit message<Input value={message} maxLength={300} disabled={busy||uncertain||Boolean(result)} onChange={event=>{intent.current=null;setMessage(event.target.value);}}/></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{result?.phase==='terminal'?<p role="status" className="text-sm">The original contribution {result.status?`was ${result.status}`:'is closed'}. Its saved history is preserved. <a className="underline" href={`/#/p/${projectId}/changes?task=${result.taskId}`}>Inspect saved history</a></p>:result?.phase==='confirmed'?<p role="status" className="text-sm">Commit {result.commit?.slice(0,7)} is recorded in your contribution. <a className="underline" href={`/#/p/${projectId}/changes?task=${result.taskId}`}>Review contribution</a></p>:<Button disabled={busy||recoveryBlocked||!target.trim()||!message.trim()||!path&&!upload} onClick={()=>void submit()}>{busy?'Saving contribution…':uncertain?'Retry original contribution':'Save contribution'}</Button>}{uncertain&&intent.current&&<a className="block text-xs underline" href={`/#/p/${projectId}/changes?task=${intent.current.taskId}`}>Inspect original contribution</a>}<Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Close</Button></div></Dialog></>;
}
