import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from '@/components/ui/collapsible';
import {apiCandidateRuntimeInspection,apiRecoverCandidateVerificationClosure} from '../api';
import {runtimeRecordSummary,canRecordVerificationClosure,type CandidateRuntimeInspection} from '../candidate-runtime-inspection';
export function CandidateRuntimeRecord({projectId,candidateId,workflowId,commit,evidenceId,readOnly=false}:{projectId:string;candidateId:string;workflowId:string;commit?:string;evidenceId?:string;readOnly?:boolean}){
 const [open,setOpen]=useState(false),[report,setReport]=useState<CandidateRuntimeInspection|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef<AbortController|null>(null),generation=useRef(0);
 useEffect(()=>{generation.current++;request.current?.abort();setOpen(false);setReport(null);setError('');setBusy(false);return()=>{generation.current++;request.current?.abort();};},[projectId,candidateId,workflowId,commit,evidenceId]);
 const recover=async()=>{if(readOnly||busy||!commit||!evidenceId)return;request.current?.abort();const controller=new AbortController();request.current=controller;const current=++generation.current;setBusy(true);setError('');try{const result=await apiRecoverCandidateVerificationClosure(projectId,candidateId,{workflowId,commit,evidenceId},AbortSignal.any([controller.signal,AbortSignal.timeout(15000)]));if(current===generation.current)setReport(result);}catch{if(current===generation.current&&!controller.signal.aborted)setError('Verification closure was not confirmed. Refresh this record before retrying the same saved verification.');}finally{if(current===generation.current)setBusy(false);}};
 const load=async()=>{request.current?.abort();const controller=new AbortController();request.current=controller;const current=++generation.current;setBusy(true);setError('');setReport(null);try{const result=await apiCandidateRuntimeInspection(projectId,candidateId,workflowId,AbortSignal.any([controller.signal,AbortSignal.timeout(15000)]));if(current===generation.current)setReport(result);}catch{if(current===generation.current&&!controller.signal.aborted)setError('Runtime records could not be confirmed. Review remains available.');}finally{if(current===generation.current)setBusy(false);}};
 return <Collapsible open={open} onOpenChange={next=>{setOpen(next);if(next&&!report&&!busy)void load();}} className="mt-3 text-xs"><CollapsibleTrigger asChild><Button variant="ghost" size="sm" className="h-7 px-0">Runtime record</Button></CollapsibleTrigger><CollapsibleContent className="space-y-2 pt-2"><p className="text-muted-foreground">Recorded ledger state. Live provider resources and credentials are not inspected by this view.</p>{busy&&<p role="status">Reading saved runtime…</p>}{error&&<p role="alert" className="text-destructive">{error}</p>}{report&&<><p className="font-medium">{runtimeRecordSummary(report)}</p>{report.commands&&<p className="text-muted-foreground">{report.commands.completed} completed · {report.commands.pending} pending acknowledgement · {report.commands.refused} refused</p>}{report.allocations&&<ul className="space-y-1">{report.allocations.map(allocation=><li key={allocation.nativeRunId} className="flex flex-wrap gap-x-2"><span className="break-all">{allocation.stage}</span><span className="text-muted-foreground">{allocation.stopped?'Stop recorded':'Stop not recorded'}</span></li>)}</ul>}{!report.coverage&&<p className="text-muted-foreground">This run has no complete runtime ledger. Its contributions and review remain preserved.</p>}<p className="text-muted-foreground">Verification closure: {report.verificationClosure.status==='closed'?'recorded':report.verificationClosure.status==='absent'?'not recorded':'unconfirmed'} · Credential revocation: {report.verificationClosure.credentials.status==='revoked'?'recorded':report.verificationClosure.credentials.status==='absent'?'no receipt':'unconfirmed'}{report.verificationClosure.credentials.count!==null?` (${report.verificationClosure.credentials.count})`:''}</p>{!readOnly&&report.verificationClosure.status==='absent'&&report.protocol===1&&commit&&evidenceId&&<><Button variant="outline" size="sm" disabled={busy||!canRecordVerificationClosure(report,commit,evidenceId)} onClick={()=>void recover()}>Record verified closure</Button>{!canRecordVerificationClosure(report,commit,evidenceId)&&<p className="text-muted-foreground">Await recorded runtime stops and command acknowledgements before recording closure.</p>}</>}<p className="text-muted-foreground">Checked {new Date(report.checkedAt).toLocaleTimeString()}</p></>}{!busy&&<Button variant="outline" size="sm" onClick={()=>void load()}>{error?'Retry runtime read':'Refresh record'}</Button>}</CollapsibleContent></Collapsible>;
}
