import React, { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Dialog, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { apiJson, ApiError } from "../api";
import type { DiscussionThread } from "../pages/Community";

type Rights={subscribed:boolean;selectedOption:string|null;canManagePoll:boolean;canConvert:boolean;canMarkAnswer:boolean;moderator:boolean};
type Snapshot=DiscussionThread&{poll?:{options:string[];closed:boolean;version:number;counts:Record<string,number>}};
export function DiscussionFeatures({repository,topic,privateScope,onThread}:{repository:string;topic:string;privateScope:boolean;onThread:(value:DiscussionThread)=>void}){
  const base=`${privateScope?'/p':'/public'}/${encodeURIComponent(repository)}/discussions/${encodeURIComponent(topic)}`;
  const controller=useRef(new AbortController()),lock=useRef(false),convertIntent=useRef<{expectedVersion:number;idempotencyKey:string;confirmed:true}|null>(null);
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[rights,setRights]=useState<Rights|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[options,setOptions]=useState(''),[choice,setChoice]=useState(''),[converting,setConverting]=useState(false),[issue,setIssue]=useState<number|null>(null);
  useEffect(()=>{const lifetime=new AbortController();controller.current=lifetime;setError('');void Promise.all([apiJson<Snapshot>(base,{signal:lifetime.signal}),apiJson<Rights>(`${privateScope?'/p':'/public'}/${repository}/discussions/permissions?topic=${encodeURIComponent(topic)}`,{signal:lifetime.signal})]).then(([value,permissions])=>{if(lifetime.signal.aborted)return;setSnapshot(value);setRights(permissions);setChoice(permissions.selectedOption??'');onThread(value);}).catch(cause=>{if(!lifetime.signal.aborted){setRights(null);setError(cause instanceof Error?cause.message:'Discussion features unavailable');}});return()=>lifetime.abort();},[base,repository,topic,privateScope,revision]);
  const act=async(suffix:string,json:object)=>{if(lock.current||!rights)return;lock.current=true;setBusy(true);setError('');try{const result=await apiJson<{issueNumber?:number}>(base+suffix,{method:'POST',json,signal:controller.current.signal});if(controller.current.signal.aborted)return;if(result.issueNumber){setIssue(result.issueNumber);setConverting(false);}setRevision(value=>value+1);}catch(cause){if(suffix==='/convert'&&cause instanceof ApiError&&[400,403,409].includes(cause.status))convertIntent.current=null;if(!controller.current.signal.aborted)setError(cause instanceof Error?cause.message:'This action was not confirmed. Refresh to inspect current state; your draft is preserved.');}finally{lock.current=false;setBusy(false);}};
  return <section className="space-y-4 border-y border-border py-5 my-5"><div className="flex flex-wrap gap-2 items-center justify-between"><h2 className="text-sm font-medium">Discussion actions</h2><Button size="sm" variant="outline" disabled={busy} onClick={()=>setRevision(value=>value+1)}>Refresh actions</Button></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{!snapshot&&!error&&<p role="status" className="text-sm text-muted-foreground">Loading discussion actions…</p>}
    {snapshot&&rights&&<><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void act('/subscription',{subscribed:!rights.subscribed})}>{rights.subscribed?'Unsubscribe':'Subscribe'}</Button>{rights.moderator&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act('/control',{expectedVersion:snapshot.topic.version,pinned:!snapshot.topic.pinned})}>{snapshot.topic.pinned?'Unpin discussion':'Pin discussion'}</Button>}{snapshot.topic.pinned&&<span className="text-xs text-muted-foreground self-center">Pinned</span>}{rights.canConvert&&!snapshot.topic.convertedIssue&&!issue&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setConverting(true)}>Convert to issue</Button>}{(issue??snapshot.topic.convertedIssue)&&<a className="text-sm underline self-center" href={`#/p/${repository}/issues?n=${issue??snapshot.topic.convertedIssue}`}>Open issue #{issue??snapshot.topic.convertedIssue}</a>}</div>
      {rights.subscribed&&<p className="text-xs text-muted-foreground">{rights.canConvert?'Replies appear in your Activity inbox while repository notifications are enabled.':'This discussion is saved in your subscriptions. Activity inbox notifications require repository membership.'}</p>}
      {snapshot.poll?<div className="space-y-3"><h3 className="font-medium text-sm">Poll{snapshot.poll.closed?' · Closed':''}</h3><RadioGroup value={choice} onValueChange={setChoice} disabled={busy||snapshot.poll.closed}>{snapshot.poll.options.map((option,index)=><div key={option} className="flex items-center gap-2"><RadioGroupItem value={option} id={`discussion-vote-${topic}-${index}`}/><Label htmlFor={`discussion-vote-${topic}-${index}`} className="flex-1 break-words">{option}</Label><span className="text-xs text-muted-foreground">{snapshot.poll?.counts[option]??0} votes</span></div>)}</RadioGroup>{!snapshot.poll.closed&&<div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy||!choice} onClick={()=>void act('/poll',{operation:'vote',option:choice})}>Save vote</Button>{rights.canManagePoll&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act('/poll',{operation:'close',expectedVersion:snapshot.poll!.version})}>Close poll</Button>}</div>}<p className="text-xs text-muted-foreground">One vote per participant. Saving another choice replaces your vote.</p></div>:rights.canManagePoll&&<form className="space-y-3" onSubmit={event=>{event.preventDefault();void act('/poll',{operation:'create',options:options.split('\n').map(option=>option.trim()).filter(Boolean),expectedVersion:snapshot.topic.version,confirmed:true});}}><Label htmlFor={`poll-options-${topic}`}>Poll choices, one per line</Label><Textarea id={`poll-options-${topic}`} value={options} onChange={event=>setOptions(event.target.value)} maxLength={2000} rows={3} disabled={busy}/><Button size="sm" variant="outline" disabled={busy||options.split('\n').filter(option=>option.trim()).length<2}>Create poll</Button></form>}
      {snapshot.topic.category==='question'&&<div className="space-y-3"><h3 className="font-medium text-sm">Answer</h3>{snapshot.topic.answerId?<div className="space-y-2"><p className="text-sm whitespace-pre-wrap break-words">{snapshot.replies.find(reply=>reply.id===snapshot.topic.answerId)?.body??'The selected answer is unavailable.'}</p>{rights.canMarkAnswer&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act('/control',{expectedVersion:snapshot.topic.version,answerId:null})}>Clear answer</Button>}</div>:<p className="text-xs text-muted-foreground">No answer selected.</p>}{rights.canMarkAnswer&&snapshot.replies.filter(reply=>!reply.removed&&reply.id!==snapshot.topic.answerId).map(reply=><div key={reply.id} className="border-l-2 border-border pl-3 space-y-2"><p className="text-sm whitespace-pre-wrap break-words">{reply.body}</p><Button size="sm" variant="outline" disabled={busy} onClick={()=>void act('/control',{expectedVersion:snapshot.topic.version,answerId:reply.id})}>Mark as answer</Button></div>)}</div>}
    </>}
    <Dialog open={converting} onOpenChange={setConverting}><DialogHeader><DialogTitle>Convert discussion to issue</DialogTitle><DialogDescription>A repository issue will retain this discussion’s title and content. The discussion stays available with its issue link.</DialogDescription></DialogHeader><p className="text-sm text-muted-foreground mb-4">{privateScope?'Member-visible discussion content remains in this repository.':'The new issue follows this repository’s issue visibility.'}</p>{error&&<p role="alert" className="text-sm text-destructive mb-3">{error}</p>}<div className="flex flex-wrap gap-2"><Button disabled={busy||!rights?.canConvert} onClick={()=>{if(!snapshot)return;if(!convertIntent.current)convertIntent.current={expectedVersion:snapshot.topic.version,idempotencyKey:crypto.randomUUID(),confirmed:true};void act('/convert',convertIntent.current);}}>{busy?'Converting…':convertIntent.current?'Retry same conversion':'Create linked issue'}</Button><Button variant="outline" disabled={busy} onClick={()=>setConverting(false)}>Cancel</Button></div></Dialog>
  </section>;
}
