import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {apiJson,ApiError,apiSessionIdentity} from '../api';
import type {IssueFilterCriteria,SavedIssueFilter,SavedIssueFilterWrite} from '../../server/issue-feature-store';
type Facets={labels:string[];assignees:string[];milestones:Array<{id:number;title:string}>};
export function IssueFilters({projectId,criteria,facets,members,onApply}:{projectId:string;criteria:IssueFilterCriteria;facets?:Facets;members?:Array<{user_id:string;label:string}>;onApply:(criteria:IssueFilterCriteria)=>void}){
 const identity=apiSessionIdentity(),[data,setData]=useState<{identity:string;scope:string;filters:SavedIssueFilter[]}|null>(null),[query,setQuery]=useState(criteria.q),[name,setName]=useState(''),[selected,setSelected]=useState('none'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false),[revision,setRevision]=useState(0);
 const boundScope=useRef(''),sequence=useRef(0),controller=useRef<AbortController|null>(null),lock=useRef(false),pending=useRef<SavedIssueFilterWrite|null>(null);
 useEffect(()=>setQuery(criteria.q),[criteria.q]);
 useEffect(()=>{const generation=++sequence.current,lifetime=new AbortController();controller.current=lifetime;setData(null);setError('');const binding=`${identity}:${projectId}`;if(boundScope.current!==binding){boundScope.current=binding;setSelected('none');setName('');pending.current=null;setUncertain(false);}
  if(identity)void apiJson<{scope:string;filters:SavedIssueFilter[]}>(`/p/${projectId}/issue-filters`,{signal:lifetime.signal}).then(value=>{if(generation===sequence.current&&identity===apiSessionIdentity()){if(pending.current&&pending.current.expectedScope!==value.scope){pending.current=null;setUncertain(false);setName('');setSelected('none');}setData({identity,scope:value.scope,filters:value.filters});}}).catch(cause=>{if(!lifetime.signal.aborted&&generation===sequence.current&&identity===apiSessionIdentity()){if(cause instanceof ApiError&&[401,403].includes(cause.status)){setName('');setSelected('none');}setError(cause instanceof Error?cause.message:'Saved issue views unavailable');}});return()=>{sequence.current++;lifetime.abort();};
 },[projectId,identity,revision]);
 const sameBinding=boundScope.current===`${identity}:${projectId}`;
 const filters=sameBinding&&data&&data.identity===identity?data.filters:[],current=filters.find(filter=>filter.id===selected);
 const mutate=async(operation:'save'|'delete')=>{
  if(lock.current||!sameBinding||!identity||!pending.current&&(data?.identity!==identity||operation==='delete'&&!current))return;const generation=sequence.current,captured=identity;lock.current=true;setBusy(true);setError('');
  try{
   if(!pending.current)pending.current=operation==='save'?{action:'save',expectedScope:data!.scope,id:current?.id??crypto.randomUUID(),name:name.trim(),filter:criteria,expectedVersion:current?.version??0}:{action:'delete',expectedScope:data!.scope,id:current!.id,expectedVersion:current!.version};
   if(captured!==apiSessionIdentity())throw Error('Signed-in session changed');
   setUncertain(true);const saved=pending.current;await apiJson(`/p/${projectId}/issue-filters`,{method:'POST',json:pending.current,signal:controller.current?.signal});
   if(generation!==sequence.current||captured!==apiSessionIdentity())return;pending.current=null;setUncertain(false);setSelected(saved.action==='save'?saved.id:'none');setName(saved.action==='save'?saved.name:'');setRevision(value=>value+1);
  }catch(cause){if(generation===sequence.current&&captured===apiSessionIdentity()){if(cause instanceof ApiError&&[401,403].includes(cause.status)){setData(null);setName('');setSelected('none');}setError(cause instanceof Error?cause.message:'Saved view outcome is unknown. Refresh before applying another change.');}}
  finally{lock.current=false;if(generation===sequence.current&&captured===apiSessionIdentity())setBusy(false);}
 };
 const apply=(next:Partial<IssueFilterCriteria>)=>{if(sameBinding&&identity===apiSessionIdentity())onApply({...criteria,...next});};
 return <section aria-label="Issue filters" className="space-y-3"><form className="flex flex-wrap gap-2" onSubmit={event=>{event.preventDefault();apply({q:query.trim()});}}><Input aria-label="Search issue title or description" placeholder="Search issues" value={sameBinding?query:''} maxLength={200} className="min-w-0 flex-1 basis-48" onChange={event=>setQuery(event.target.value)}/><Button size="sm" variant="outline">Search</Button></form><div className="flex flex-wrap gap-2">
 <Select value={sameBinding?criteria.sort:'updated-desc'} onValueChange={sort=>apply({sort:sort as IssueFilterCriteria['sort']})}><SelectTrigger className="w-full sm:w-44" aria-label="Sort issues"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="updated-desc">Recently updated</SelectItem><SelectItem value="created-desc">Newest created</SelectItem><SelectItem value="number-desc">Highest number</SelectItem><SelectItem value="number-asc">Lowest number</SelectItem></SelectContent></Select>
 <Input aria-label="Exact issue label" placeholder="Exact label" value={sameBinding?criteria.label??'':''} maxLength={50} className="w-full sm:w-40" onChange={event=>apply({label:event.target.value.trim()||undefined})}/>
 <Select value={sameBinding?criteria.assignee??'any':'any'} onValueChange={assignee=>apply({assignee:assignee==='any'?undefined:assignee})}><SelectTrigger className="w-full sm:w-44" aria-label="Filter by assignee"><SelectValue placeholder="Saved assignee"/></SelectTrigger><SelectContent><SelectItem value="any">Any assignee</SelectItem>{(members??[]).map(member=><SelectItem key={member.user_id} value={member.user_id}>{member.label||'Member'}</SelectItem>)}</SelectContent></Select>
 <Select value={sameBinding?String(criteria.milestone??'any'):'any'} onValueChange={milestone=>apply({milestone:milestone==='any'?undefined:milestone==='none'?'none':Number(milestone)})}><SelectTrigger className="w-full sm:w-44" aria-label="Filter by milestone"><SelectValue placeholder="Saved milestone"/></SelectTrigger><SelectContent><SelectItem value="any">Any milestone</SelectItem><SelectItem value="none">No milestone</SelectItem>{(facets?.milestones??[]).map(milestone=><SelectItem key={milestone.id} value={String(milestone.id)}>{milestone.title}</SelectItem>)}</SelectContent></Select>
 </div><div className="flex flex-wrap gap-2 items-center"><Select value={sameBinding?selected:'none'} disabled={busy||uncertain||data?.identity!==identity} onValueChange={value=>{setSelected(value);const saved=filters.find(filter=>filter.id===value);setName(saved?.name??'');if(saved)onApply(saved.filter);}}><SelectTrigger className="w-full sm:w-48" aria-label="Personal saved issue views"><SelectValue placeholder="Saved views"/></SelectTrigger><SelectContent><SelectItem value="none">Personal saved views</SelectItem>{filters.map(filter=><SelectItem key={filter.id} value={filter.id}>{filter.name}</SelectItem>)}</SelectContent></Select><Input aria-label="Saved issue view name" placeholder="View name" value={sameBinding?name:''} maxLength={80} className="w-full sm:w-40" disabled={busy||uncertain} onChange={event=>setName(event.target.value)}/><Button size="sm" variant="outline" disabled={busy||!pending.current&&(!name.trim()||data?.identity!==identity)} onClick={()=>void mutate('save')}>{uncertain?'Retry saved change':current?'Update view':'Save view'}</Button>{current&&<Button size="sm" variant="ghost" disabled={busy||uncertain} onClick={()=>void mutate('delete')}>Delete view</Button>}<Button size="sm" variant="ghost" disabled={busy} onClick={()=>setRevision(value=>value+1)}>Refresh views</Button></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
}
