import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {apiJson,apiSessionIdentity} from '../api';
import type {IssueLink} from '../../core/issue-relations';
import type {RepositoryController} from '../../server/durable-object';
type Page=Extract<Awaited<ReturnType<RepositoryController['issueRelationships']>>,{ok:true}>['value'];
const labels={parent:'Parent issue','sub-issue':'Sub-issues','duplicate-target':'Duplicate of',duplicate:'Duplicates'};
export function IssueRelationships({projectId,number,planningRevision,disabled,canRemove,onRemove}:{projectId:string;number:number;planningRevision:number;disabled:boolean;canRemove:boolean;onRemove:(link:IssueLink,revision:number)=>Promise<void>}){
 const identity=apiSessionIdentity(),[page,setPage]=useState<{identity:string;binding:string;value:Page}|null>(null),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),sequence=useRef(0),controller=useRef<AbortController|null>(null),basis=useRef('');
 const binding=`${identity}:${projectId}:${number}`;
 useEffect(()=>{const next=`${binding}:${planningRevision}`;if(basis.current!==next){basis.current=next;setCursor(null);setPage(null);}},[binding,planningRevision]);
 useEffect(()=>{const generation=++sequence.current,lifetime=new AbortController();controller.current=lifetime;setPage(null);setError('');setLoading(true);
  if(identity)void apiJson<Page>(`/p/${projectId}/issues/${number}/relations${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`,{signal:lifetime.signal}).then(value=>{if(generation===sequence.current&&identity===apiSessionIdentity())setPage({identity,binding,value});}).catch(cause=>{if(!lifetime.signal.aborted&&generation===sequence.current&&identity===apiSessionIdentity())setError(cause instanceof Error?cause.message:'Related issues unavailable');}).finally(()=>{if(generation===sequence.current&&identity===apiSessionIdentity())setLoading(false);});
  return()=>{sequence.current++;lifetime.abort();};
 },[projectId,number,identity,planningRevision,cursor,revision]);
 const current=page?.binding===binding&&page.identity===identity?page.value:null;
 const remove=async(link:IssueLink)=>{if(!current||disabled||loading||identity!==apiSessionIdentity())return;await onRemove(link,current.featureRevision);if(identity===apiSessionIdentity())setRevision(value=>value+1);};
 return <section aria-label="Related issues" className="space-y-3">{loading&&<p role="status" className="text-xs text-muted-foreground">Loading related issues…</p>}{error&&<div role="alert" className="space-y-2 text-sm text-destructive"><p>{error}</p><Button size="sm" variant="outline" onClick={()=>{setCursor(null);setRevision(value=>value+1);}}>Reload related issues</Button></div>}{current&&<>{current.total===0?<p className="text-xs text-muted-foreground">No linked issues.</p>:<>{Object.entries(labels).map(([kind,label])=>{const items=current.items.filter(item=>item.kind===kind);return items.length?<div key={kind} className="space-y-2"><h3 className="text-xs font-medium">{label}</h3><ul className="space-y-2">{items.map(item=><li key={`${item.link.kind}:${item.link.from}:${item.link.to}`} className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1">{item.issue?<a className="block break-words text-sm hover:underline" href={`/#/p/${encodeURIComponent(projectId)}/issues?n=${item.issue.number}`}><span className="text-muted-foreground">#{item.issue.number}</span> {item.issue.title}</a>:<span className="text-sm text-muted-foreground">Issue #{item.number} is unavailable.</span>}{item.issue&&<Badge className="mt-1" variant={item.issue.state==='open'?'success':'purple'}>{item.issue.state}</Badge>}</div>{canRemove&&current.canRemove&&item.available&&<Button size="sm" variant="ghost" disabled={disabled||loading} aria-label={`Remove ${labels[item.kind].toLowerCase()} link to issue ${item.number}`} onClick={()=>void remove(item.link)}>Remove link</Button>}</li>)}</ul></div>:null;})}<div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span>{current.offset+1}–{current.offset+current.items.length} of {current.total} links</span><div className="flex gap-2">{cursor&&<Button size="sm" variant="ghost" disabled={loading} onClick={()=>setCursor(null)}>First links</Button>}{current.nextCursor&&<Button size="sm" variant="outline" disabled={loading} onClick={()=>setCursor(current.nextCursor)}>More links</Button>}</div></div></>}</>}</section>;
}
