import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {apiJson,apiSessionIdentity} from '../api';
import {checkedTransferPreview,checkedTransferReceipt,recoverTransferIntent,persistTransferIntent,transferRequest,type IssueTransferPreview,type IssueTransferRequest,type IssueTransferReceipt} from '../issue-transfer-intent';
const phaseText:Record<IssueTransferReceipt['phase'],string>={locked:'Transfer saved',frozen:'Transfer saved',reserved:'Destination reserved',copying:'Copying attachments',ready:'Content and attachments checked',active:'Finishing transfer',completed:'Issue transferred'};
export function IssueTransfer({projectId,number,canTransfer,disabled=false,onLock,onChanged}:{projectId:string;number:number;canTransfer:boolean;disabled?:boolean;onLock:(locked:boolean)=>void;onChanged:()=>void}){
 const identity=apiSessionIdentity(),epoch=useRef(0),running=useRef(false),saved=useRef<{identity:string;request:IssueTransferRequest}|null>(null),callbacks=useRef({onLock,onChanged});callbacks.current={onLock,onChanged};
 const [destination,setDestination]=useState(''),[preview,setPreview]=useState<IssueTransferPreview|null>(null),[intent,setIntent]=useState<IssueTransferRequest|null>(null),[receipt,setReceipt]=useState<IssueTransferReceipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false),[recoveryBlocked,setRecoveryBlocked]=useState(false);
 const base=`/p/${encodeURIComponent(projectId)}/issues/${number}`;
 useEffect(()=>{const generation=++epoch.current;setPreview(null);setReceipt(null);setError(null);setOpen(false);setIntent(null);setRecoveryBlocked(false);saved.current=null;running.current=false;setBusy(false);callbacks.current.onLock(false);
  if(identity)try{const request=recoverTransferIntent(sessionStorage,{identity,projectId,number});if(request){saved.current={identity,request};setIntent(request);setDestination(request.destinationProjectId);callbacks.current.onLock(true);void apiJson<unknown>(`${base}/transfer/${request.requestId}`).then(raw=>{if(epoch.current!==generation||apiSessionIdentity()!==identity)return;const next=checkedTransferReceipt(raw,projectId,number,request);setReceipt(next);if(next.completed)callbacks.current.onChanged();}).catch(()=>{if(epoch.current===generation&&apiSessionIdentity()===identity)setError('The saved transfer could not be confirmed. Resume the original request.');});}}catch{setRecoveryBlocked(true);callbacks.current.onLock(true);setError('Saved transfer recovery is unavailable. Restore browser storage before continuing.');}
  return()=>{epoch.current++;};
 },[identity,projectId,number,base]);
 const inspect=async()=>{if(!identity||!canTransfer||disabled||recoveryBlocked||running.current||saved.current)return;const generation=epoch.current;running.current=true;setBusy(true);setError(null);try{const raw=await apiJson<unknown>(`${base}/transfer-preview?destinationProjectId=${encodeURIComponent(destination)}`);if(epoch.current!==generation||apiSessionIdentity()!==identity)return;setPreview(checkedTransferPreview(raw,projectId,number,destination));setOpen(true);}catch(cause){if(epoch.current===generation&&apiSessionIdentity()===identity)setError(cause instanceof Error?cause.message:'Transfer preview unavailable');}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}};
 const submit=async()=>{if(!identity||running.current||disabled||recoveryBlocked)return;const generation=epoch.current;let original=saved.current;if(original&&original.identity!==identity)return;
  try{if(!original){if(!preview||!canTransfer)return;const request=transferRequest(preview,crypto.randomUUID());persistTransferIntent(sessionStorage,{identity,projectId,number},request);original={identity,request};saved.current=original;setIntent(request);callbacks.current.onLock(true);}}catch(cause){setError(cause instanceof Error?cause.message:'Transfer recovery unavailable');return;}
  running.current=true;setBusy(true);setOpen(false);setError(null);
  try{const raw=await apiJson<unknown>(`${base}/transfer`,{method:'POST',json:original.request});if(epoch.current!==generation||apiSessionIdentity()!==identity)return;const next=checkedTransferReceipt(raw,projectId,number,original.request);setReceipt(next);if(next.completed)callbacks.current.onChanged();}catch(cause){if(epoch.current===generation&&apiSessionIdentity()===identity)setError(`Transfer outcome is unconfirmed. Resume this saved request. ${cause instanceof Error?cause.message:''}`);}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 };
 if(!canTransfer&&!intent&&!error)return null;
 return <section className="space-y-3"><h3 className="text-sm font-medium">Transfer issue</h3>{intent?<><p role="status" className="text-sm text-muted-foreground">{receipt?phaseText[receipt.phase]:'Original transfer saved'}. Destination: {intent.destinationProjectId}.</p>{!receipt?.completed&&<Button size="sm" variant="outline" disabled={busy||disabled} onClick={()=>void submit()}>{busy?'Transferring…':'Resume original transfer'}</Button>}</>:<div className="flex flex-wrap items-end gap-2"><div className="space-y-1"><Label htmlFor={`transfer-destination-${number}`}>Destination repository ID</Label><Input id={`transfer-destination-${number}`} value={destination} onChange={event=>{setDestination(event.target.value);setPreview(null);}} maxLength={16} disabled={busy||disabled||recoveryBlocked}/></div><Button size="sm" variant="outline" disabled={busy||disabled||recoveryBlocked||! /^[a-z0-9]{12,16}$/.test(destination)||destination===projectId} onClick={()=>void inspect()}>{busy?'Checking…':'Preview transfer'}</Button></div>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 <Dialog open={open&&preview!==null} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogHeader><DialogTitle>Transfer issue #{number}?</DialogTitle><DialogDescription>The destination’s current repository members will be able to read this issue, its comments and attachments.</DialogDescription></DialogHeader>{preview&&<div className="space-y-2 text-sm"><p className="font-medium">{preview.manifest.issue.title}</p><p>Destination: {preview.destination.projectId}</p><p>{preview.manifest.comments.length} comments · {preview.manifest.attachments.length} attachments</p>{preview.manifest.attachments.length>0&&<ul className="space-y-1">{preview.manifest.attachments.map((file,index)=><li key={`${file.name}:${index}`}>{file.name} · {(file.size/1024).toFixed(1)} KB</li>)}</ul>}</div>}<DialogFooter><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button size="sm" disabled={busy||disabled||preview===null} onClick={()=>void submit()}>Confirm transfer</Button></DialogFooter></Dialog>
 </section>;
}
