import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {apiJson,apiFetch,apiSessionIdentity} from '../api';
import {transferFinalization,recoverTransferFinalization,persistTransferFinalization,checkedTransferFinalization,type IssueTransferFinalization,recoverReadonlyCleanup,updateReadonlyCleanup,reconcileCancelledTransfer,type ReadonlyTransferCleanup,issueTransferPendingSchema,adoptPendingTransfer,type IssueTransferPendingRecovery,cancellationFromTransferStatus,recoverCancelledCleanup,saveCancelledCleanup,type CancelledTransferCleanup,checkedTransferCancellation,recoverTransferCancellation,persistTransferCancellation,transferCancellation,clearCancelledTransfer,type IssueTransferCancellation,checkedTransferPreview,checkedTransferReceipt,recoverTransferIntent,persistTransferIntent,transferRequest,type IssueTransferPreview,type IssueTransferRequest,type IssueTransferReceipt} from '../issue-transfer-intent';
const phaseText:Record<IssueTransferReceipt['phase'],string>={locked:'Transfer saved',frozen:'Transfer saved',reserved:'Destination reserved',copying:'Copying attachments',ready:'Content and attachments checked',active:'Finishing transfer',completed:'Issue transferred',cancelling:'Cancelling transfer',cancelled:'Cancellation recorded'};
export function IssueTransfer({projectId,number,canTransfer,disabled=false,pendingTransfer,onLock,onChanged}:{projectId:string;number:number;canTransfer:boolean;disabled?:boolean;pendingTransfer?:IssueTransferPendingRecovery;onLock:(locked:boolean)=>void;onChanged:()=>void}){
 const identity=apiSessionIdentity(),epoch=useRef(0),running=useRef(false),saved=useRef<{identity:string;request:IssueTransferRequest}|null>(null),callbacks=useRef({onLock,onChanged});callbacks.current={onLock,onChanged};
 const [destination,setDestination]=useState(''),[preview,setPreview]=useState<IssueTransferPreview|null>(null),[intent,setIntent]=useState<IssueTransferRequest|null>(null),[receipt,setReceipt]=useState<IssueTransferReceipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false),[recoveryBlocked,setRecoveryBlocked]=useState(false),[cancelIntent,setCancelIntent]=useState<IssueTransferCancellation|null>(null),[cancelOpen,setCancelOpen]=useState(false),[cancelConflict,setCancelConflict]=useState(false),[notice,setNotice]=useState<string|null>(null),[cleanupHistory,setCleanupHistory]=useState<CancelledTransferCleanup[]>([]),[canResume,setCanResume]=useState(true),[readonlyCleanup,setReadonlyCleanup]=useState<ReadonlyTransferCleanup[]>([]),[finalizeIntent,setFinalizeIntent]=useState<IssueTransferFinalization|null>(null),[finalizeOpen,setFinalizeOpen]=useState(false);const savedFinalize=useRef<{identity:string;request:IssueTransferFinalization}|null>(null);const savedCancel=useRef<{identity:string;request:IssueTransferCancellation}|null>(null);
 const pendingSignature=JSON.stringify(pendingTransfer??null);
 const base=`/p/${encodeURIComponent(projectId)}/issues/${number}`;
 useEffect(()=>{
  const generation=++epoch.current,current=()=>epoch.current===generation&&apiSessionIdentity()===identity;
  setPreview(null);setReceipt(null);setError(null);setOpen(false);setIntent(null);setRecoveryBlocked(false);setCancelIntent(null);setCancelOpen(false);setCancelConflict(false);setNotice(null);setFinalizeIntent(null);setFinalizeOpen(false);savedFinalize.current=null;setCleanupHistory([]);setReadonlyCleanup([]);setCanResume(true);savedCancel.current=null;saved.current=null;running.current=false;setBusy(false);callbacks.current.onLock(false);
  if(identity)void(async()=>{
   const scope={identity,projectId,number};
   try{
    setCleanupHistory(recoverCancelledCleanup(sessionStorage,scope));setReadonlyCleanup(recoverReadonlyCleanup(sessionStorage,scope));
    const pending=pendingSignature==='null'?null:issueTransferPendingSchema.parse(JSON.parse(pendingSignature));let request=recoverTransferIntent(sessionStorage,scope);
    let loaded:IssueTransferReceipt|null=null,reconciled=false,readAttempted=false;
    if(request){saved.current={identity,request};setIntent(request);setDestination(request.destinationProjectId);const priorFinalize=recoverTransferFinalization(sessionStorage,scope);if(priorFinalize){savedFinalize.current={identity,request:priorFinalize};setFinalizeIntent(priorFinalize);}const priorCancel=recoverTransferCancellation(sessionStorage,scope);if(priorCancel){savedCancel.current={identity,request:priorCancel};setCancelIntent(priorCancel);}callbacks.current.onLock(true);readAttempted=true;let raw:unknown;try{raw=await apiJson<unknown>(`${base}/transfer/${request.requestId}`);}catch{if(!current())return;if(pending&&pending.originalRequest.requestId!==request.requestId)throw Error('Old transfer terminal outcome is still unconfirmed; its original identity is preserved');setError('The original transfer outcome is unconfirmed. Resume it or confirm cancellation of the same saved request.');}if(!current())return;if(raw!==undefined)loaded=checkedTransferReceipt(raw,projectId,number,request);
     if(loaded?.phase==='cancelled'&&loaded.cancellationReceipt){reconcileCancelledTransfer(sessionStorage,scope,request,raw);request=null;loaded=null;reconciled=true;readAttempted=false;saved.current=null;savedCancel.current=null;setIntent(null);setCancelIntent(null);setCleanupHistory(recoverCancelledCleanup(sessionStorage,scope));setReadonlyCleanup(recoverReadonlyCleanup(sessionStorage,scope));callbacks.current.onLock(false);}
     else if(pending&&pending.originalRequest.requestId!==request.requestId)throw Error('The old saved transfer must be reconciled before adopting another pending transfer');
    }
    if(!request&&pending){adoptPendingTransfer(sessionStorage,scope,pending);request=pending.originalRequest;}
    setCanResume(pending?.canResumeOriginal??true);
    if(!request){if(reconciled)callbacks.current.onChanged();return;}
    saved.current={identity,request};setIntent(request);setDestination(request.destinationProjectId);callbacks.current.onLock(true);
    let cancellation=recoverTransferCancellation(sessionStorage,scope);if(cancellation){savedCancel.current={identity,request:cancellation};setCancelIntent(cancellation);}
    if(!loaded&&!readAttempted){const raw=await apiJson<unknown>(`${base}/transfer/${request.requestId}`);if(!current())return;loaded=checkedTransferReceipt(raw,projectId,number,request);}
    setReceipt(loaded);if(!loaded)return;const discovered=cancellationFromTransferStatus(request,loaded);
    if(discovered){cancellation=cancellation??discovered.request;if(cancellation.cancelId!==discovered.request.cancelId)throw Error('Original cancellation identity cannot change');persistTransferCancellation(sessionStorage,scope,cancellation);savedCancel.current={identity,request:cancellation};setCancelIntent(cancellation);setCancelConflict(discovered.refused);}
    if(loaded.completed)callbacks.current.onChanged();
   }catch(cause){if(current()){setRecoveryBlocked(true);callbacks.current.onLock(true);setError(cause instanceof Error?cause.message:'Saved transfer recovery is unavailable');}}
  })();
  return()=>{epoch.current++;};
 },[identity,projectId,number,base,pendingSignature]);
 const inspect=async()=>{if(!identity||apiSessionIdentity()!==identity||!canTransfer||disabled||recoveryBlocked||running.current||saved.current)return;const generation=epoch.current;running.current=true;setBusy(true);setError(null);try{const raw=await apiJson<unknown>(`${base}/transfer-preview?destinationProjectId=${encodeURIComponent(destination)}`);if(epoch.current!==generation||apiSessionIdentity()!==identity)return;setPreview(checkedTransferPreview(raw,projectId,number,destination));setOpen(true);}catch(cause){if(epoch.current===generation&&apiSessionIdentity()===identity)setError(cause instanceof Error?cause.message:'Transfer preview unavailable');}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}};
 const submit=async()=>{if(!identity||apiSessionIdentity()!==identity||running.current||disabled||recoveryBlocked||savedFinalize.current!==null||!canResume||(savedCancel.current!==null&&!cancelConflict))return;const generation=epoch.current;let original=saved.current;if(original&&original.identity!==identity)return;
  try{if(!original){if(!preview||!canTransfer)return;const request=transferRequest(preview,crypto.randomUUID());persistTransferIntent(sessionStorage,{identity,projectId,number},request);original={identity,request};saved.current=original;setIntent(request);callbacks.current.onLock(true);}}catch(cause){setError(cause instanceof Error?cause.message:'Transfer recovery unavailable');return;}
  running.current=true;setBusy(true);setOpen(false);setError(null);
  try{const raw=await apiJson<unknown>(`${base}/transfer`,{method:'POST',json:original.request});if(epoch.current!==generation||apiSessionIdentity()!==identity)return;const next=checkedTransferReceipt(raw,projectId,number,original.request);setReceipt(next);if(next.completed)callbacks.current.onChanged();}catch(cause){if(epoch.current===generation&&apiSessionIdentity()===identity)setError(`Transfer outcome is unconfirmed. Resume this saved request. ${cause instanceof Error?cause.message:''}`);}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 };
 const cancelTransfer=async()=>{const original=saved.current;if(!identity||apiSessionIdentity()!==identity||!original||original.identity!==identity||running.current||disabled||recoveryBlocked||savedFinalize.current!==null)return;const generation=epoch.current;
  let cancellation=savedCancel.current;try{if(!cancellation){const request=transferCancellation(original.request,crypto.randomUUID());persistTransferCancellation(sessionStorage,{identity,projectId,number},request);cancellation={identity,request};savedCancel.current=cancellation;setCancelIntent(request);}if(cancellation.identity!==identity)return;}catch(cause){setRecoveryBlocked(true);setError(cause instanceof Error?cause.message:'Cancellation recovery unavailable');return;}
  running.current=true;setBusy(true);setCancelOpen(false);setError(null);callbacks.current.onLock(true);
  try{const response=await apiFetch(`/api${base}/transfer/${original.request.requestId}/cancel`,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify(cancellation.request)}),raw:unknown=await response.json();if(epoch.current!==generation||apiSessionIdentity()!==identity)return;
    const result=checkedTransferCancellation(raw,cancellation.request);if(!result.cancelled){if(response.status!==409)throw Error('Cancellation refusal status differs');setCancelConflict(true);callbacks.current.onChanged();setError(canResume?'The destination is already active. Resume the original transfer to finish it.':'The destination is already active. The original operator must finish the transfer.');return;}
    if(!response.ok)throw Error('Cancellation acknowledgement status differs');clearCancelledTransfer(sessionStorage,{identity,projectId,number},cancellation.request,raw);setCleanupHistory(recoverCancelledCleanup(sessionStorage,{identity,projectId,number}));saved.current=null;savedCancel.current=null;setIntent(null);setCancelIntent(null);setReceipt(null);setPreview(null);setCancelConflict(false);callbacks.current.onLock(false);setNotice(result.physicalCleanup==='pending'?'Transfer cancelled. Storage cleanup is still pending.':'Transfer cancelled.');callbacks.current.onChanged();
  }catch(cause){if(epoch.current===generation&&apiSessionIdentity()===identity)setError(`Cancellation outcome is unconfirmed. Retry the original cancellation. ${cause instanceof Error?cause.message:''}`);}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 };
 const finishActive=async()=>{const original=saved.current;if(!identity||apiSessionIdentity()!==identity||!original||original.identity!==identity||running.current||disabled||recoveryBlocked)return;const generation=epoch.current;
  let finalization=savedFinalize.current;try{if(!finalization){if(!pendingTransfer?.canFinalizeActive||pendingTransfer.activeDestinationNumber===undefined||pendingTransfer.originalRequest.requestId!==original.request.requestId)throw Error('Current active destination proof is unavailable');const request=transferFinalization(original.request,pendingTransfer.activeDestinationNumber,crypto.randomUUID());persistTransferFinalization(sessionStorage,{identity,projectId,number},request);finalization={identity,request};savedFinalize.current=finalization;setFinalizeIntent(request);}if(finalization.identity!==identity)return;}catch(cause){setError(cause instanceof Error?cause.message:'Finalization recovery unavailable');return;}
  running.current=true;setBusy(true);setFinalizeOpen(false);setError(null);callbacks.current.onLock(true);
  try{const raw=await apiJson<unknown>(`${base}/transfer/${original.request.requestId}/finalize`,{method:'POST',json:finalization.request});if(epoch.current!==generation||apiSessionIdentity()!==identity)return;const result=checkedTransferFinalization(raw,{projectId,number},original.request,finalization.request);setReceipt(result);if(result.completed){setNotice('Active transfer finished.');callbacks.current.onChanged();}}
  catch(cause){if(epoch.current===generation&&apiSessionIdentity()===identity)setError(`Finalization outcome is unconfirmed. Retry the original finalization. ${cause instanceof Error?cause.message:''}`);}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 };
 const checkCleanup=async()=>{if(!identity||apiSessionIdentity()!==identity||running.current||disabled||recoveryBlocked||(!cleanupHistory.length&&!readonlyCleanup.length))return;const generation=epoch.current,owned=cleanupHistory[0]?.request,readOnly=readonlyCleanup[0]?.originalRequest;running.current=true;setBusy(true);setError(null);try{if(owned){const raw=await apiJson<unknown>(`${base}/transfer/${owned.requestId}/cancel`,{method:'POST',json:owned});if(epoch.current!==generation||apiSessionIdentity()!==identity)return;setCleanupHistory(saveCancelledCleanup(sessionStorage,{identity,projectId,number},owned,raw));}else if(readOnly){const raw=await apiJson<unknown>(`${base}/transfer/${readOnly.requestId}`);if(epoch.current!==generation||apiSessionIdentity()!==identity)return;setReadonlyCleanup(updateReadonlyCleanup(sessionStorage,{identity,projectId,number},readOnly,raw));}}catch{if(epoch.current===generation&&apiSessionIdentity()===identity)setError('Saved storage cleanup could not be confirmed. Its original identity is preserved.');}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}};
 if(!canTransfer&&!intent&&!error&&!cleanupHistory.length&&!readonlyCleanup.length)return null;
 return <section className="space-y-3"><h3 className="text-sm font-medium">Transfer issue</h3>{intent?<><p role="status" className="text-sm text-muted-foreground">{receipt?phaseText[receipt.phase]:'Original transfer saved'}. Destination: {intent.destinationProjectId}.</p>{!receipt?.completed&&canResume&&!finalizeIntent&&<Button size="sm" variant="outline" disabled={busy||disabled||(cancelIntent!==null&&!cancelConflict)} onClick={()=>void submit()}>{busy?'Transferring…':'Resume original transfer'}</Button>}{!receipt?.completed&&!cancelConflict&&!finalizeIntent&&!pendingTransfer?.canFinalizeActive&&<Button size="sm" variant="ghost" disabled={busy||disabled} onClick={()=>cancelIntent?void cancelTransfer():setCancelOpen(true)}>{cancelIntent?'Retry original cancellation':'Cancel saved transfer'}</Button>}{!receipt?.completed&&(finalizeIntent||pendingTransfer?.canFinalizeActive)&&<Button size="sm" variant="outline" disabled={busy||disabled} onClick={()=>finalizeIntent?void finishActive():setFinalizeOpen(true)}>{finalizeIntent?'Retry original finalization':'Finish active transfer'}</Button>}</>:<div className="flex flex-wrap items-end gap-2"><div className="space-y-1"><Label htmlFor={`transfer-destination-${number}`}>Destination repository ID</Label><Input id={`transfer-destination-${number}`} value={destination} onChange={event=>{setDestination(event.target.value);setPreview(null);}} maxLength={16} disabled={busy||disabled||recoveryBlocked}/></div><Button size="sm" variant="outline" disabled={busy||disabled||recoveryBlocked||! /^[a-z0-9]{12,16}$/.test(destination)||destination===projectId} onClick={()=>void inspect()}>{busy?'Checking…':'Preview transfer'}</Button></div>}{cleanupHistory.length+readonlyCleanup.length>0&&<div className="space-y-2 text-sm"><p className="text-muted-foreground">Storage cleanup remains pending for {cleanupHistory.length+readonlyCleanup.length} cancelled transfer{cleanupHistory.length+readonlyCleanup.length===1?'':'s'}.</p><Button size="sm" variant="ghost" disabled={busy||disabled||recoveryBlocked} onClick={()=>void checkCleanup()}>Check saved cleanup</Button></div>}{notice&&<p role="status" className="text-sm text-muted-foreground">{notice}</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 <Dialog open={finalizeOpen} onOpenChange={value=>{if(!busy)setFinalizeOpen(value);}}><DialogHeader><DialogTitle>Finish the active transfer?</DialogTitle><DialogDescription>The destination already contains the verified issue. This finishes the original transfer without changing its author or copying its content again.</DialogDescription></DialogHeader><DialogFooter><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setFinalizeOpen(false)}>Keep pending</Button><Button size="sm" disabled={busy||disabled} onClick={()=>void finishActive()}>Confirm finalization</Button></DialogFooter></Dialog>
 <Dialog open={cancelOpen} onOpenChange={value=>{if(!busy)setCancelOpen(value);}}><DialogHeader><DialogTitle>Cancel this transfer?</DialogTitle><DialogDescription>The original issue becomes editable only after cancellation is confirmed. A transfer with an active destination must be resumed instead.</DialogDescription></DialogHeader><DialogFooter><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setCancelOpen(false)}>Keep transfer</Button><Button size="sm" variant="destructive" disabled={busy||disabled} onClick={()=>void cancelTransfer()}>Confirm cancellation</Button></DialogFooter></Dialog>
 <Dialog open={open&&preview!==null} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogHeader><DialogTitle>Transfer issue #{number}?</DialogTitle><DialogDescription>The destination’s current repository members will be able to read this issue, its comments and attachments.</DialogDescription></DialogHeader>{preview&&<div className="space-y-2 text-sm"><p className="font-medium">{preview.manifest.issue.title}</p><p>Destination: {preview.destination.projectId}</p><p>{preview.manifest.comments.length} comments · {preview.manifest.attachments.length} attachments</p>{preview.manifest.attachments.length>0&&<ul className="space-y-1">{preview.manifest.attachments.map((file,index)=><li key={`${file.name}:${index}`}>{file.name} · {(file.size/1024).toFixed(1)} KB</li>)}</ul>}</div>}<DialogFooter><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button size="sm" disabled={busy||disabled||preview===null} onClick={()=>void submit()}>Confirm transfer</Button></DialogFooter></Dialog>
 </section>;
}
