import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {apiFetch,apiSessionIdentity} from '../api';
import {repoReleaseAssetSchema,type RepoRelease} from '../repository-releases';
export function ReleaseAssetsPanel({projectId,release,isOwner,onRefresh}:{projectId:string;release:RepoRelease;isOwner:boolean;onRefresh:()=>void}){
 const identity=apiSessionIdentity(),abort=useRef(new AbortController());useEffect(()=>()=>abort.current.abort(),[]);const assertCurrent=()=>{if(abort.current.signal.aborted||apiSessionIdentity()!==identity)throw Error('Release asset session changed');};
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const selected=useRef<File|null>(null),intent=useRef<{id:string;name:string;sha256:string;size:number}|null>(null);
 const upload=async()=>{const file=selected.current;if(!file||busy)return;setBusy(true);setError('');try{if(!file.size||file.size>5*1024*1024||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,149}$/.test(file.name))throw Error('Choose an asset up to 5 MiB with a simple filename.');const bytes=await file.arrayBuffer(),sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');const saved=(release.assets??[]).find(asset=>asset.name===file.name);if(saved&&(saved.size!==file.size||saved.sha256!==sha256))throw Error('This asset name already binds different bytes.');if(!intent.current)intent.current={id:saved?.id??crypto.randomUUID(),name:file.name,size:file.size,sha256};const request=intent.current;if(request.name!==file.name||request.size!==file.size||request.sha256!==sha256)throw Error('Retry the original selected file.');assertCurrent();const response=await apiFetch(`/api/p/${projectId}/releases/${release.scope.id}/assets/${request.id}`,{method:'PUT',body:bytes,headers:{'X-Asset-Name':request.name,'X-Asset-SHA256':request.sha256},signal:AbortSignal.any([abort.current.signal,AbortSignal.timeout(30000)])});if(!response.ok)throw Error('Upload outcome unconfirmed. Retry this original file or refresh saved assets.');const asset=repoReleaseAssetSchema.parse(await response.json());assertCurrent();if(asset.id!==request.id||asset.sha256!==request.sha256||asset.phase!=='verified')throw Error('Asset acknowledgement differs.');intent.current=null;selected.current=null;onRefresh();}catch(cause){setError(cause instanceof Error?cause.message:'Asset outcome unconfirmed');}finally{setBusy(false);}};
 const download=async(asset:NonNullable<RepoRelease['assets']>[number])=>{if(busy)return;setBusy(true);setError('');try{assertCurrent();const response=await apiFetch(`/api/p/${projectId}/releases/${release.scope.id}/assets/${asset.id}`,{signal:AbortSignal.any([abort.current.signal,AbortSignal.timeout(30000)])});if(!response.ok)throw Error('Asset unavailable');const bytes=await response.arrayBuffer(),digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(bytes.byteLength!==asset.size||digest!==asset.sha256)throw Error('Downloaded asset verification failed');assertCurrent();const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));const link=document.createElement('a');link.href=url;link.download=asset.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(cause){setError(cause instanceof Error?cause.message:'Download unavailable');}finally{setBusy(false);}};
 return <div className="space-y-2">{release.assets?.map(asset=><div key={asset.id} className="text-xs space-y-1"><Button size="sm" variant="ghost" disabled={busy||asset.phase!=='verified'} onClick={()=>void download(asset)}>{asset.name} · {asset.phase==='verified'?`${asset.size.toLocaleString()} bytes`: 'Verification pending'}</Button><p className="text-muted-foreground break-all">SHA-256 {asset.sha256}</p></div>)}{isOwner&&release.phase==='draft'&&<div className="flex flex-wrap gap-2"><Input type="file" aria-label="Release asset" disabled={busy||intent.current!==null} onChange={event=>{selected.current=event.target.files?.[0]??null;}}/><Button size="sm" variant="outline" disabled={busy} onClick={()=>void upload()}>{busy?'Verifying asset…':intent.current?'Retry original asset':'Upload asset'}</Button></div>}{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}</div>;
}
