import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {OAUTH_SCOPES} from '@/core/oauth-scopes';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Label} from '@/components/ui/label';
import {apiJson} from '../api';
const requestSchema=z.object({clientId:z.string().regex(/^[A-Za-z0-9_-]{22}$/),redirectUri:z.string().url(),scope:z.string().max(500),codeChallenge:z.string().regex(/^[A-Za-z0-9_-]{43}$/),state:z.string().max(500).optional()}).strict();
const appSchema=z.object({clientId:z.string(),name:z.string(),redirectUris:z.array(z.string()),scopes:z.array(z.enum(OAUTH_SCOPES))});
const catalog=z.object({installations:z.array(z.object({id:z.string(),clientId:z.string(),repositoryId:z.string(),scopes:z.array(z.enum(OAUTH_SCOPES)),expiresAt:z.number()})).max(10000)});
type Pending={projectId:string;request:z.infer<typeof requestSchema>;app:z.infer<typeof appSchema>};
export function RepositoryApplications({projectId}:{projectId:string}){
 const [items,setItems]=useState<z.infer<typeof catalog>['installations']>([]),[text,setText]=useState(''),[pending,setPending]=useState<Pending|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[callback,setCallback]=useState<string|null>(null);
 const controller=useRef(new AbortController()),lock=useRef(false);
 const list=async()=>{const active=controller.current;const value=catalog.parse(await apiJson<unknown>(`/oauth/installations?repositoryId=${projectId}`,{signal:AbortSignal.any([controller.current.signal,AbortSignal.timeout(15000)])}));if(controller.current===active&&!active.signal.aborted)setItems(value.installations);};
 useEffect(()=>{const active=new AbortController();controller.current=active;lock.current=false;setBusy(false);setItems([]);setText('');setPending(null);setConfirmed(false);setCallback(null);setError('');void list().catch(()=>{if(!active.signal.aborted)setError('App access could not be loaded. Refresh before continuing.');});return()=>active.abort();},[projectId]);
 const run=async(action:()=>Promise<void>)=>{if(lock.current)return;const active=controller.current;lock.current=true;setBusy(true);setError('');try{await action();}catch(cause){if(controller.current===active&&!active.signal.aborted)setError(cause instanceof Error?cause.message:'App access was not confirmed. Refresh before retrying.');}finally{if(controller.current===active&&!active.signal.aborted){lock.current=false;setBusy(false);}}};
 const inspect=()=>run(async()=>{const active=controller.current;setPending(null);setConfirmed(false);setCallback(null);const request=requestSchema.parse(JSON.parse(text));const app=appSchema.parse(await apiJson<unknown>(`/oauth/apps/${request.clientId}`,{signal:controller.current.signal}));const scopes=request.scope.split(' ').filter(Boolean);if(!app.redirectUris.includes(request.redirectUri)||!scopes.length||scopes.some(scope=>!app.scopes.includes(scope as typeof OAUTH_SCOPES[number])))throw Error('The request does not match the app’s registered permissions and callback.');if(controller.current!==active||active.signal.aborted)return;setPending({projectId,request,app});});
 const install=()=>run(async()=>{const active=controller.current;if(!pending||pending.projectId!==projectId||!confirmed)return;const value=z.object({code:z.string(),redirectTo:z.string().url()}).parse(await apiJson<unknown>('/oauth/install',{method:'POST',json:{...pending.request,repositoryId:projectId},signal:controller.current.signal}));const target=new URL(value.redirectTo),expected=new URL(pending.request.redirectUri);target.searchParams.delete('code');target.searchParams.delete('state');expected.searchParams.delete('code');expected.searchParams.delete('state');if(target.href!==expected.href)throw Error('The app callback changed. Revoke this installation before continuing.');if(controller.current!==active||active.signal.aborted)return;setCallback(value.redirectTo);await list();});
 return <Card><CardHeader><CardTitle className="text-sm">Applications</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-xs text-muted-foreground">App access applies to your account in this repository. Removing an app revokes its tokens immediately.</p>{items.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 text-xs"><div><p className="font-medium break-all">App {item.clientId}</p><p>{item.scopes.join(', ')}</p><p className="text-muted-foreground">Expires {new Date(item.expiresAt).toLocaleDateString()}</p></div><Button variant="outline" size="sm" disabled={busy} onClick={()=>void run(async()=>{await apiJson(`/oauth/installations/${item.id}?repositoryId=${projectId}`,{method:'DELETE',signal:controller.current.signal});setCallback(null);await list();})}>Remove app</Button></div>)}<div className="space-y-2 border-t border-border pt-3"><Label htmlFor={`app-request-${projectId}`}>Installation request from your app</Label><Textarea id={`app-request-${projectId}`} rows={4} maxLength={3000} value={text} disabled={busy} onChange={event=>{setText(event.target.value);setPending(null);setConfirmed(false);setCallback(null);}} placeholder="Paste the app’s JSON authorization request"/><Button size="sm" variant="outline" disabled={busy||!text} onClick={()=>void inspect()}>Review request</Button>{pending?.projectId===projectId&&<div className="space-y-2 text-sm"><p className="font-medium">{pending.app.name}</p><p className="text-xs break-all">Repository: {projectId} · Callback: {pending.request.redirectUri}</p><p className="text-xs">Permissions: {pending.request.scope}</p><div className="flex gap-2 items-center"><Checkbox id={`app-consent-${projectId}`} disabled={busy} checked={confirmed} onCheckedChange={value=>setConfirmed(value===true)}/><Label htmlFor={`app-consent-${projectId}`}>Allow these permissions for this repository</Label></div><Button size="sm" disabled={busy||!confirmed||!!callback} onClick={()=>void install()}>Install app</Button>{callback&&<Button size="sm" variant="outline" onClick={()=>window.location.assign(callback)}>Continue to app</Button>}</div>}</div>{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run(list)}>Refresh app access</Button></CardContent></Card>;
}
