import {z} from 'zod';
import {issueTransferMappingSchema} from '../server/issue-feature-store';
import {parseIssueNumber} from './issue-state-command';
import {mergeMappingPrincipalPage,checkedMappingPreview,createMappingRequest,checkedMappingReceipt} from '../web/issue-transfer-mapping-intent';
const fileSchema=z.object({projectId:z.string().regex(/^[a-z0-9]{12,16}$/),number:z.number().int().positive().max(9999999),preview:z.unknown(),choices:z.object({labels:issueTransferMappingSchema.shape.labels,assignees:issueTransferMappingSchema.shape.assignees,milestone:issueTransferMappingSchema.shape.milestone}).strict()}).strict();
export async function prepareTransferMappingCommand(input:{repositoryId:string;issue:string|undefined;confirmed:boolean;request?:string|true;file?:unknown},read:(route:string)=>Promise<unknown>){
 const number=parseIssueNumber(input.issue),route=`/p/${input.repositoryId}/issues/${number}/transfer-mapping`;
 if(input.request!==undefined&&(typeof input.request!=='string'||!z.uuid().safeParse(input.request).success))throw Error('--request requires the full original mapping UUID');
 if(!input.confirmed){if(input.request!==undefined||input.file!==undefined)throw Error('Mapping confirmation requires --confirm');let preview=checkedMappingPreview(await read(route));const visited=new Set<string>();while(!preview.principalPage.complete){const cursor=preview.principalPage.nextCursor;if(!cursor||visited.has(cursor)||visited.size>=1000)throw Error('Principal pagination is incomplete or exceeds supported work capacity; no full roster is claimed');visited.add(cursor);preview=mergeMappingPrincipalPage(preview,await read(`${route}?principalCursor=${encodeURIComponent(cursor)}`));}return{kind:'preview' as const,file:{projectId:input.repositoryId,number,preview,choices:{labels:[],assignees:[],milestone:null}}};}
 if(input.file===undefined)throw Error('--confirm requires --mapping FILE containing the exact reviewed destination preview and explicit choices');const file=fileSchema.parse(input.file);if(file.projectId!==input.repositoryId||file.number!==number)throw Error('Mapping file belongs to another destination issue');const preview=checkedMappingPreview(file.preview),request=createMappingRequest(preview,file.choices,typeof input.request==='string'?input.request:crypto.randomUUID());if(request.labels.length===0&&request.assignees.length===0&&request.milestone===null)throw Error('Select an explicit destination mapping; leaving every reference unchanged requires no write');
 return{kind:'dispatch' as const,route,request,metadata:{repositoryId:input.repositoryId,issueNumber:number,action:'map-transferred-context',requestId:request.requestId,originalRequest:request,retry:`Reuse issue transfer map for this destination issue --confirm --mapping the original file --request ${request.requestId}.`}};
}
export const transferMappingCommandReceipt=checkedMappingReceipt;
