import {IntegrationNativeRuntimeLedger} from '../../src/server/integration-native-runtime';
import {RetainedInputs} from '../../src/server/retained-inputs';
import {accountKeyFor} from '../../src/server/projects';
import {VERIFIER_IDENTITIES} from '../../src/core/verification-identities';
import {AcceptedRegistryFixture} from './accepted-branch-registry-worker';
import type {Env} from '../../src/server/env';
import type {Task,VerificationEvidence} from '../../src/core/types';
export class AcceptedTargetFixture extends AcceptedRegistryFixture {
 protected override async publicationNativeHead(_context:unknown,_scope:string,_journalId:string,ref:string,authorize:()=>Promise<void>){await authorize();await this.ctx.storage.put('observedRef',ref);return await this.ctx.storage.get('readbackMode')==='absent'?null:'e'.repeat(40);}
 protected override publicationRecoveryProvider():Pick<Env,'ARTIFACTS'>{
  const meta=(hash:string)=>({hash,treeHash:'c'.repeat(40),parents:[],message:'Synthetic ancestry',author:{name:'Fixture',email:'fixture@example.invalid'},committer:{name:'Fixture',email:'fixture@example.invalid'},authoredAt:0,committedAt:0});
  return {ARTIFACTS:{get:async()=>({log:async()=>await this.ctx.storage.get('readbackMode')==='missing'?[meta('e'.repeat(40))]:[meta('e'.repeat(40)),meta('b'.repeat(40))],readCommit:async(hash:string)=>meta(hash),[Symbol.dispose]:()=>{}})}} as unknown as Pick<Env,'ARTIFACTS'>;
 }
 override async fetch(request:Request){const url=new URL(request.url);try{
 if(url.pathname==='/target-task'){const input=await request.json() as {id:string;ref?:string;parent?:string};const state=await this.getState(),parent=input.parent?state.tasks[input.parent]:undefined,selected=input.ref?(await this.acceptedBranchRegistrySnapshot()).roots.find(root=>root.ref===input.ref):undefined,base=parent?.currentCommit??selected?.head??state.acceptedState.currentCommit;const task:Task={id:input.id,goal:'Frozen target contribution',contributor:{id:'owner',name:'Owner',type:'human'},baseCommit:base,currentCommit:base,status:'ready',allowedScope:['src/'],requirements:[],workspace:{repoName:`workspace-${input.id}`,remote:'https://fixture.invalid',branch:`task/${input.id}`},checkpoints:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...(input.parent?{dependsOn:input.parent}:{})};return Response.json(await this.createTask(task,'owner',{goal:task.goal,dependsOn:input.parent??null,issue:null},input.ref?{acceptedTargetRef:input.ref}:undefined));}
 if(url.pathname==='/landing'){const input=await request.json() as {tasks:string[];holder:string};return Response.json(await this.claimLanding({holder:input.holder,taskIds:input.tasks,preservationProtocolVersion:1}));}
 if(url.pathname==='/verify-target'){const input=await request.json() as {id:string;bind:boolean;commit?:string};const state=await this.getState(),candidate=state.candidates[input.id]!;const evidence:VerificationEvidence={id:`proof-${input.id}`,candidateCommit:input.commit??'b'.repeat(40),candidateTree:'c'.repeat(40),expectedAcceptedBase:candidate.expectedAcceptedBase,requirementsVersion:candidate.frozenPolicyVersion,policy:candidate.frozenVerificationPolicy,testBundleDigest:'test',toolchainDigest:'tool',builtOutputDigest:'output',verifierIdentity:VERIFIER_IDENTITIES['ticket-booking'],testResults:[],timestamp:new Date().toISOString(),status:'passed',...(input.bind&&candidate.acceptedTarget?{acceptedTarget:structuredClone(candidate.acceptedTarget)}:{})};await this.recordVerification(input.id,evidence.candidateCommit,evidence);const incarnation=candidate.acceptedTarget!.incarnation;for(const id of candidate.participatingTaskIds){const task=state.tasks[id]!;new RetainedInputs(this.ctx.storage).record({id:crypto.randomUUID(),version:1,projectId:state.projectId,incarnation,taskId:id,commit:task.currentCommit,base:task.baseCommit,canonicalRepoName:state.canonicalRepoName,workspaceRepoName:task.workspace.repoName,branch:task.workspace.branch,protectedRef:`refs/flaregit/inputs/${incarnation}/${id}/${task.currentCommit}`,protectedBaseRef:`refs/flaregit/inputs/${incarnation}/${id}/${task.baseCommit}`,workflowId:candidate.workflowInstanceId!,candidateId:candidate.id,actorId:task.contributor.id,ownerId:'owner',accountKey:await accountKeyFor('owner')},{commit:task.currentCommit,base:task.baseCommit});}await this.awaitReview(input.id,evidence.candidateCommit,candidate.workflowInstanceId!);return Response.json({verified:true});}
 if(url.pathname==='/review-target'){const input=await request.json() as {id:string;commit?:string;target?:{ref:string;acceptedCommit:string;acceptedVersion:number}};return Response.json(await this.recordReview(input.id,{approved:true,actor:{userId:'owner',displayName:'Owner',viaToken:false}},input.commit??'b'.repeat(40),undefined,input.target));}
 if(url.pathname==='/prepare')return Response.json(await this.preparePublish(url.searchParams.get('id')!));
 if(url.pathname==='/observe-readback'){await this.ctx.storage.put('readbackMode',url.searchParams.get('mode')??'landed');const result=await this.observeCandidatePublicationReadback(url.searchParams.get('id')!,url.searchParams.get('journal')!,url.searchParams.get('commit')!);return Response.json({...result,observedRef:await this.ctx.storage.get('observedRef')});}
 if(url.pathname==='/authorize-readback')return Response.json(await this.authorizeCandidatePublicationReadback(url.searchParams.get('id')!,url.searchParams.get('journal')!,url.searchParams.get('commit')!));
 if(url.pathname==='/check-bound'){await this.ctx.storage.put('readbackMode','landed');return Response.json(await this.checkOwnerPublicationReadback(url.searchParams.get('journal')!,url.searchParams.get('event')!,{userId:'owner',displayName:'Owner',viaToken:false},undefined,Date.now()+60000));}
 if(url.pathname==='/cancel-bound-wrapper'){const input=await request.json() as {journalId:string;candidateId:string;ref:string;commit:string;eventId:string};return Response.json(await this.cancelOwnerBoundPublication(input.journalId,input,{userId:'owner',displayName:'Owner',viaToken:false},undefined,Date.now()+60000));}
 if(url.pathname==='/publication-recoveries')return Response.json(await this.ownerBoundPublicationRecoveries({userId:'owner',displayName:'Owner',viaToken:false},undefined,Date.now()+60000));
 if(url.pathname==='/seal-target-runtime'){const state=await this.getState(),candidate=state.candidates[url.searchParams.get('id')!]!,scope={workflowId:candidate.workflowInstanceId!,candidateId:candidate.id,projectId:state.projectId,incarnation:candidate.acceptedTarget!.incarnation,actorId:'owner',accountKey:await accountKeyFor('owner')},runtime=new IntegrationNativeRuntimeLedger(this.ctx.storage);await this.registerWorkflow(scope.workflowId,'integration',undefined,'owner',1);runtime.declareCoverage(scope);runtime.seal(scope);return Response.json({sealed:true});}
 if(url.pathname==='/mark-dispatch')return Response.json(await this.markCandidatePublicationDispatch(url.searchParams.get('id')!,url.searchParams.get('journal')!,url.searchParams.get('commit')!));
 if(url.pathname==='/cancel-publication'){const input=await request.json() as {id:string;journal:string;eventId:string};return Response.json(await this.cancelUndispatchedPublication(input.id,input.journal,input.eventId,{userId:'owner',displayName:'Owner',viaToken:false},undefined,Date.now()+60000));}
 if(url.pathname==='/cancel-target'){await this.cancelTask(url.searchParams.get('id')!);return Response.json({cancelled:true});}
 if(url.pathname==='/abort-target'){const input=await request.json() as {id:string;journal:string};await this.abortPublish(input.id,input.journal,'authorization changed','failed');return Response.json(await this.getState());}
 if(url.pathname==='/authorize')return Response.json(await this.authorizeCandidatePublication(url.searchParams.get('id')!,url.searchParams.get('commit')??'a'.repeat(40)));
 if(url.pathname==='/tamper-target'){const input=await request.json() as {id:string;kind:'journal'|'evidence';version:number};const state=await this.getState(),candidate=state.candidates[input.id]!;if(input.kind==='journal'){const journal=state.journal.find(row=>row.candidateId===input.id)!;journal.acceptedTarget!.acceptedVersion=input.version;}else state.evidence[candidate.evidenceId!]!.acceptedTarget!.acceptedVersion=input.version;this.ctx.storage.sql.exec('UPDATE project SET doc=? WHERE id=1',JSON.stringify(state));return Response.json({changed:true});}
 if(url.pathname==='/complete-target'){const input=await request.json() as {journalId:string};await this.completePublish(input.journalId);return Response.json(await this.getState());}
 if(url.pathname==='/state-full')return Response.json(await this.getState());
 if(url.pathname==='/legacy-baseline'){const state=await this.getState();delete state.acceptedBaseline;this.ctx.storage.sql.exec('UPDATE project SET doc=? WHERE id=1',JSON.stringify(state));return Response.json(await this.privateRecoveryTargets());}
 if(url.pathname==='/recovery-targets')return Response.json(await this.privateRecoveryTargets());
 if(url.pathname==='/mutate-default'){const state=await this.getState();state.defaultBranch=url.searchParams.get('branch')??'renamed-primary';this.ctx.storage.sql.exec('UPDATE project SET doc=? WHERE id=1',JSON.stringify(state));return Response.json({changed:true});}
 if(url.pathname==='/restore-policy'){const state=await this.getState(),candidate=state.candidates[url.searchParams.get('id')!]!;state.verificationPolicy=candidate.frozenVerificationPolicy;state.policyVersion=candidate.frozenPolicyVersion;this.ctx.storage.sql.exec('UPDATE project SET doc=? WHERE id=1',JSON.stringify(state));return Response.json({restored:true});}
 if(url.pathname==='/mutate-root'){const state=await this.getState();state.verificationPolicy={changed:true};state.policyVersion++;this.ctx.storage.sql.exec('UPDATE project SET doc=? WHERE id=1',JSON.stringify(state));return Response.json({changed:true});}
 }catch(error){return Response.json({error:error instanceof Error?error.message:'Failure'},{status:409});}return super.fetch(request);}
}
export default {fetch:(request:Request,env:Env)=>env.REPOSITORY_CONTROLLER.getByName(new URL(request.url).searchParams.get('name')??'fixture').fetch(request)};
