// Actual controller/policy/task facts with qualified Workflow transport doubles.
// No native execution, provider calls, verified application, or Git history proof.
import {RepositoryController} from '../../src/server/durable-object';
import {UntrustedExecutionSandbox} from '../../src/server/untrusted-execution-sandbox';
import {WorkerEntrypoint} from 'cloudflare:workers';
import {bindBrowserPolicy} from '../../src/server/external-browser-verifier';
import {ticketBookingBrowserInventory} from '../../src/server/trusted-fixture-browser-policies';
import type{Env}from'../../src/server/env';
import type{Task}from'../../src/core/types';
export{UntrustedExecutionSandbox};
export class NoBrowser extends WorkerEntrypoint{override fetch(){return new Response('No browser executed in scheduling test',{status:503});}}
export class AutoIntegrationControllerFixture extends RepositoryController{
 private unknownAck=false;private known=true;private webhookFailure=false;private mutateDuringReadback=false;private sdkStatus:InstanceStatus['status']='running';
 protected override async createAutomaticWorkflow(id:string,params:Parameters<RepositoryController['createAutomaticWorkflow']>[1]){this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS fixture_sdk_creates(id TEXT PRIMARY KEY,params TEXT NOT NULL)');this.ctx.storage.sql.exec('INSERT INTO fixture_sdk_creates VALUES(?,?)',id,JSON.stringify(params));if(this.unknownAck)throw Error('Synthetic Workflow acknowledgement unknown');return [];}
 protected override async observeAutomaticWorkflow(id:string):Promise<InstanceStatus['status']>{if(this.mutateDuringReadback){this.mutateDuringReadback=false;await this.fixtureRequirementsOnlyEdit();}this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS fixture_sdk_inspections(id TEXT)');this.ctx.storage.sql.exec('INSERT INTO fixture_sdk_inspections VALUES(?)',id);return this.known?this.sdkStatus:'unknown';}
 protected override async enqueueWebhookDelivery(id:string,delay=0,sequence?:number,generation?:number){if(this.webhookFailure)throw Error('Synthetic optional webhook dispatch failure');return super.enqueueWebhookDelivery(id,delay,sequence,generation);}
 async fixtureRequirementsOnlyEdit(){const state=await this.getState(),task=state.tasks.one;if(!task)throw Error('Actual task required');task.requirements.push({id:'requirements-only-'+task.requirements.length,title:'Require changed behavior',description:'Synthetic maintainer requirement change while transport awaits',version:1,status:'approved',assertions:[],originTaskId:task.id,approvedAt:new Date().toISOString()});this.ctx.storage.sql.exec('UPDATE project SET doc=? WHERE id=1',JSON.stringify(state));}
 override async fetch(request:Request){const url=new URL(request.url),actor={userId:url.searchParams.get('actor')??'owner',displayName:'Scheduling fixture human',viaToken:false};try{
 if(url.pathname==='/seed'){const verificationPolicy={kind:'git-integrity',allowedScope:['src/'],protectedPaths:['.flaregit/'],trustedBrowserFixture:'ticket-booking',trustedBrowserPolicyDigest:(await bindBrowserPolicy(ticketBookingBrowserInventory({}).policy)).digest};await this.initialize({projectId:'p123456789abc',projectName:'Synthetic scheduling fixture',canonicalRepoName:'canonical',head:'a'.repeat(40),kind:'demo',ownerId:'owner',verificationPolicy});await this.addMember('member','member');for(const id of['one','two']){const task:Task={id,goal:'Synthetic change '+id,contributor:{id:'owner',name:'Fixture human',type:'human'},baseCommit:'a'.repeat(40),currentCommit:'a'.repeat(40),status:'working',allowedScope:['src/'],requirements:[],checkpoints:[],workspace:{repoName:'workspace-'+id,remote:'https://synthetic.invalid/'+id,branch:'task/'+id},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await this.createTask(task,'owner',undefined,{acceptedTargetRef:'refs/heads/main'},{viaToken:false,sessionExpiresAt:Date.now()+60000});}return Response.json({seeded:true});}
 if(url.pathname==='/configure'){const state=await this.acceptancePolicyState(actor,undefined,Date.now()+60000);return Response.json(await this.configureAcceptancePolicy(actor,{eventId:crypto.randomUUID(),expectedVersion:state.currentPolicy.version,config:url.searchParams.has('review')?{mode:'review-required'}:{mode:'verified-auto-accept',protectedAdapter:'ticket-booking-browser'}},Date.now()+60000));}
 if(url.pathname==='/ready'){return Response.json(await this.ingestCheckpoint({eventId:url.searchParams.get('event')??crypto.randomUUID(),taskId:url.searchParams.get('task')??'one',commit:url.searchParams.get('task')==='two'?'c'.repeat(40):'b'.repeat(40),ready:true}));}
 if(url.pathname==='/mode'){this.unknownAck=url.searchParams.has('unknown');this.known=!url.searchParams.has('unknown');this.webhookFailure=url.searchParams.has('webhook');this.mutateDuringReadback=url.searchParams.has('requirements');this.sdkStatus=url.searchParams.has('queued')?'queued':'running';return Response.json({changed:true});}
 if(url.pathname==='/requirements'){await this.fixtureRequirementsOnlyEdit();return Response.json({edited:true});}
 if(url.pathname==='/withdraw-owner'){await this.addMember('other-owner','owner');await this.addMember('owner','member');return Response.json({withdrawn:true});}
 if(url.pathname==='/webhook'){await this.addWebhook('https://synthetic.invalid/webhook',['change.ready']);return Response.json({configured:true});}
 if(url.pathname==='/snapshot'){const table=(name:string)=>this.ctx.storage.sql.exec('SELECT name FROM sqlite_master WHERE type=\'table\' AND name=?',name).toArray().length>0;return Response.json({creates:table('fixture_sdk_creates')?this.ctx.storage.sql.exec<{id:string;params:string}>('SELECT * FROM fixture_sdk_creates').toArray().map(row=>({id:row.id,params:JSON.parse(row.params)})):[],inspections:table('fixture_sdk_inspections')?this.ctx.storage.sql.exec('SELECT * FROM fixture_sdk_inspections').toArray():[],dispatches:table('auto_integration_dispatches')?this.ctx.storage.sql.exec<{doc:string}>('SELECT doc FROM auto_integration_dispatches').toArray().map(row=>JSON.parse(row.doc)):[],activities:await this.listActivity(20),tasks:Object.values((await this.getState()).tasks).map(task=>({id:task.id,status:task.status,commit:task.currentCommit}))});}
 return new Response('No fixture route',{status:404});
 }catch(error){return Response.json({error:error instanceof Error?error.message:'Fixture refused'},{status:409});}}
}
export default{fetch:(request:Request,env:Env)=>env.REPOSITORY_CONTROLLER.getByName(new URL(request.url).searchParams.get('case')??'fixture').fetch(request)};
