import {BranchCreationOperations} from '../../src/server/branch-creation-operations';
import {PrivateRecoveryOperations} from '../../src/server/private-recovery';
import {accountKeyFor,globalOf} from '../../src/server/projects';
import {RepositoryController} from '../../src/server/durable-object';
import type {ManagedEnvelope,ManagedBudget} from '../../src/server/managed-spend-ledger';
import type {Env} from '../../src/server/env';
export class BranchAuthorityFixture extends RepositoryController {
 private httpEffect="";private providerId="fixture-provider";private heads=new Map([['main','a'.repeat(40)]]);private stopConfirmed=true;private revocationConfirmed=true;private pushes=0;private minted=0;private commands=0;private stopDuringAdmission=false;private sealedIds=new Set<string>();
 async fixtureArmAdmission(){this.stopDuringAdmission=true;}
 async fixtureStopPending(){const row=this.ctx.storage.sql.exec<{id:string;operation_id:string}>("SELECT id,operation_id FROM branch_native_attempts WHERE json_extract(doc,'$.state')!='stopped' ORDER BY rowid DESC LIMIT 1").toArray()[0];if(!row)throw Error("Missing native attempt");return this.cleanupBranchAttempt(row.id,row.operation_id,{userId:"owner",displayName:"Owner",viaToken:false},undefined,Date.now()+60000);}
 override async reserveManagedSpend(input:ManagedEnvelope,budget:ManagedBudget){const result=await super.reserveManagedSpend(input,budget);if(this.stopDuringAdmission){this.stopDuringAdmission=false;const repository=this.env.REPOSITORY_CONTROLLER.getByName("fixture") as unknown as BranchAuthorityFixture;await repository.fixtureStopPending();}return result;}
 protected override branchRepositoryProvider(){return {get:async()=>({info:async()=>({name:'canonical',id:this.providerId,defaultBranch:'main',remote:`https://${'a'.repeat(32)}.artifacts.cloudflare.net/canonical`}),createToken:async(scope:'read'|'write',ttl:number)=>{this.minted++;return{plaintext:'synthetic-private-token',scope,expiresAt:new Date(Date.now()+ttl*1000).toISOString()};},revokeToken:async()=>this.revocationConfirmed,[Symbol.dispose]:()=>{}})} as unknown as Env['ARTIFACTS'];}
 protected override branchInventoryFetcher(){return async()=>{if(this.httpEffect==='provider')this.providerId='replaced-provider';if(this.httpEffect==='member')this.ctx.storage.sql.exec("DELETE FROM members WHERE user_id='member'");const packet=(text:string)=>(new TextEncoder().encode(text).length+4).toString(16).padStart(4,'0')+text;return new Response(packet('# service=git-upload-pack\n')+'0000'+[...this.heads].map(([name,commit])=>packet(`${commit} refs/heads/${name}\n`)).join('')+'0000',{headers:{'Content-Type':'application/x-git-upload-pack-advertisement'}});};}
 protected override branchNativeSandbox(nativeId:string){return {exec:async(args:string[])=>{this.commands++;if(this.sealedIds.has(nativeId))throw Error("Stopped one-shot UUID cannot rearm");const command=args[2]!;let stdout='';if(command.includes('ls-remote --heads'))stdout=[...this.heads].map(([name,commit])=>`${commit}\trefs/heads/${name}`).join('\n');else if(command.includes('ls-remote --refs')){const name=command.match(/'refs\/heads\/([^']+)'/)?.[1]??'missing';const commit=this.heads.get(name);stdout=commit?`${commit}\trefs/heads/${name}\n`:'';}else if(command.includes('rev-parse --verify'))stdout='a'.repeat(40);else if(command.includes('push --quiet')){this.pushes++;const name=command.match(/refs\/heads\/([^':]+)'?/)?.[1]??'feature';this.heads.set(name,'a'.repeat(40));}return{success:true,stdout,stderr:'',exitCode:0};},seal:async()=>{this.sealedIds.add(nativeId);},destroy:async()=>{},lifetimeStatus:async()=>({sealed:this.sealedIds.has(nativeId)?true:undefined,state:this.stopConfirmed?'stopped':'stopping'})} as unknown as ReturnType<Env['INTEGRATOR']['getByName']>;}
 override async fetch(request:Request){const url=new URL(request.url),actor={userId:url.searchParams.get('actor')??'owner',displayName:'Human fixture',viaToken:false},expiry=Date.now()+60000;try{
 if(url.pathname==='/seed'){await this.initialize({projectId:'p123456789abc',projectName:'Synthetic native branch authority fixture',canonicalRepoName:'canonical',head:'a'.repeat(40),verificationPolicy:{},ownerId:'owner'});await this.addMember('member','member');return Response.json({seeded:true});}
 if(url.pathname==='/fund-core'){const global=globalOf(this.env);return Response.json(await global.reserveCoreGitOperation(`fixture-core-${crypto.randomUUID()}`,await accountKeyFor('owner'),{accountUsdMicros:13200,globalUsdMicros:13200,readAccountUsdMicros:12000,readGlobalUsdMicros:12000}));}
 if(url.pathname==='/budget-capacity')return Response.json(await globalOf(this.env).coreGitCapacity(await accountKeyFor('owner')));
 if(url.pathname==='/exhaust-read'){const global=globalOf(this.env);for(let n=0;n<32;n++){const result=await global.reserveRepositoryReadOperation(`fixture-read-${crypto.randomUUID()}`,await accountKeyFor('owner'));if(!result.allowed)return Response.json(result);}throw Error('Fixture read cap failed to close');}
 if(url.pathname==='/race'){const global=this.env.REPOSITORY_CONTROLLER.getByName('global') as unknown as BranchAuthorityFixture;await global.fixtureArmAdmission();return Response.json({armed:true});}
 if(url.pathname==='/http-effect'){this.httpEffect=url.searchParams.get('value')??'';this.providerId='fixture-provider';await this.addMember('member','member');return Response.json({set:true});}
 if(url.pathname==='/stats')return Response.json({minted:this.minted,commands:this.commands});
 if(url.pathname==='/mode'){this.stopConfirmed=url.searchParams.get('stop')!=='false';this.revocationConfirmed=url.searchParams.get('revoke')!=='false';return Response.json({set:true});}
 if(url.pathname==='/inventory')return Response.json(await this.branchInventory(actor,undefined,expiry));
 if(url.pathname==='/create')return Response.json(await this.createBranch(await request.json() as Parameters<RepositoryController['createBranch']>[0],actor,undefined,expiry));
 if(url.pathname==='/operation')return Response.json(await this.branchOperation(url.searchParams.get('id')!,actor,undefined,expiry));
 if(url.pathname==='/reconcile')return Response.json(await this.reconcileBranchOperation(url.searchParams.get('id')!,'unknown',actor,undefined,expiry));
 if(url.pathname==='/abandon')return Response.json(await this.abandonBranchOperation(url.searchParams.get('id')!,'prepared',actor,undefined,expiry));
 if(url.pathname==='/recoveries')return Response.json(await this.branchNativeRecovery(actor,undefined,expiry));
 if(url.pathname==='/cleanup'){const input=await request.json() as {attemptId:string;operationId:string};return Response.json(await this.cleanupBranchAttempt(input.attemptId,input.operationId,actor,undefined,expiry));}
 if(url.pathname==='/finished-history'){const ledger=new BranchCreationOperations(this.ctx.storage);for(let n=0;n<21;n++){const identity={operationId:crypto.randomUUID(),projectId:'p123456789abc',incarnation:new PrivateRecoveryOperations(this.ctx.storage).incarnation(),canonicalRepoName:'canonical',actorId:'owner',accountKey:await accountKeyFor('owner'),branch:`historical-${n}`,sourceCommit:'a'.repeat(40),acceptedCommit:'a'.repeat(40)};ledger.prepare(identity,()=>{});ledger.markDispatch(identity,()=>{});ledger.observe(identity,identity.sourceCommit,()=>{});}return Response.json({seeded:true});}
 if(url.pathname==='/operations')return Response.json(await this.branchOperations(actor,undefined,expiry));
 if(url.pathname==='/state')return Response.json({accepted:(await this.getState()).acceptedState.currentCommit,pushes:this.pushes});
 return new Response('Missing fixture',{status:404});
 }catch(error){return Response.json({error:error instanceof Error?error.message:'Failure'},{status:409});}}
}
export default {fetch:(request:Request,env:Env)=>env.REPOSITORY_CONTROLLER.getByName('fixture').fetch(request)};
