// Qualified provider-fake fixture: actual workerd/SQLite control logic, no native
// VM or hosted browser execution evidence and no provider mutations.
import {C02CanaryBatch,c02CanaryPolicy,c02CanaryFixtureFiles} from '../../src/server/c02-canary-worker';
import {BrowserSessionBudget,type BrowserSessionScope} from '../../src/server/browser-session-budget';
import {bindBuildManifest,type StaticBuildScope} from '../../src/server/static-build-artifact';
import {bindBrowserPolicy} from '../../src/server/external-browser-verifier';
export class C02CleanupFixture extends C02CanaryBatch {
 private badImage=false;private closes=0;private stops=0;
 protected override browserControl(){return{closeSession:async()=>{this.closes++;return{status:'closing' as const};},getSession:async()=>null};}
 protected override async nativeCleanupJob(){this.stops++;const raw=this.ctx.storage.sql.exec<{doc:string}>('SELECT doc FROM c02_canary_batch WHERE id=1').toArray()[0];if(!raw)throw Error('Fixture batch missing');const row=JSON.parse(raw.doc) as{scope:StaticBuildScope;source:{digest:string};image:string;output:Awaited<ReturnType<typeof bindBuildManifest>>};return{stop:async()=>({stopped:true}),outputReceipt:async()=>({scope:row.scope,sourceDigest:row.source.digest,image:this.badImage?row.image+'wrong':row.image,manifest:row.output,cleanup:'confirmed' as const,acceptanceEvidence:false as const})};}
 override async fetch(request:Request){const url=new URL(request.url);try{if(url.pathname==='/seed'){const body=await request.json() as{requestId:string;expectedFailure:boolean;unknownSession?:boolean;badImage?:boolean};this.badImage=body.badImage??false;await this.status();const policy=await bindBrowserPolicy(c02CanaryPolicy()),scope={attemptId:crypto.randomUUID(),projectId:'c02syntheticcase',incarnation:crypto.randomUUID(),commit:'a'.repeat(40),tree:'b'.repeat(40),policyDigest:policy.digest},files=c02CanaryFixtureFiles(),source=await bindBuildManifest('source',scope,files),output=await bindBuildManifest('static',scope,files,source.digest),leaseId=crypto.randomUUID(),image=`registry.cloudflare.com/${'a'.repeat(32)}/synthetic@sha256:${'b'.repeat(64)}`;const browserScope:BrowserSessionScope={...scope,leaseId,accountKey:'c02-private-operator',actorId:'authenticated-canary-operator',candidateId:'synthetic-only',canonicalRepoName:'no-real-repository',targetRef:'refs/heads/synthetic-fixture',expectedBase:null,acceptedVersion:0,policyVersion:1,buildDigest:output.digest,sourceDigest:source.digest,maxSeconds:120};const budget=new BrowserSessionBudget(this.ctx.storage,{authorize:async()=>()=>{},funding:()=>({reservationUsdMicros:100000,budget:{accountUsdMicros:143008,globalUsdMicros:143008}}),attestClosure:async()=>null});await budget.admit(browserScope);await budget.beginAcquire(browserScope);if(!body.unknownSession)budget.recordAcquired(browserScope,crypto.randomUUID());this.ctx.storage.sql.exec('INSERT INTO c02_canary_batch VALUES(1,?)',JSON.stringify({requestId:body.requestId,scope,source,output,image,sourceVersion:'c'.repeat(40),workerVersion:'old-withdrawn-version',phase:'browser_possible',createdAt:Date.now()-100000,deadlineAt:Date.now()-1,nativeCleanup:false,browserCleanup:false,browserLeaseId:leaseId,browserScope,budgetHeld:true,observedDom:'Blocked',expectedVerifierFailure:body.expectedFailure}));return Response.json({fixture:'provider-fake-no-hosted-evidence'});}
 if(url.pathname==='/cleanup'){const value=await request.json() as{requestId:string};return Response.json(await this.cleanup(value.requestId));}
 if(url.pathname==='/stats')return Response.json({closes:this.closes,stops:this.stops});return new Response('Missing fixture',{status:404});}catch{return new Response('Fixture refused',{status:409});}}
}
export default{fetch:(request:Request,env:{CANARY:DurableObjectNamespace<C02CleanupFixture>})=>env.CANARY.getByName(new URL(request.url).searchParams.get('case')??'fixture').fetch(request)};
