import {RepositoryController} from "../../src/server/durable-object";
import {PublicDirectory} from "../../src/server/public-directory";
const id="p123456abcdef";
export class PeopleFixture extends RepositoryController {
 async seed(){await this.initialize({projectId:id,projectName:"Synthetic public contribution fixture",canonicalRepoName:"synthetic-only",head:"a".repeat(40),verificationPolicy:{},ownerId:"owner"});await this.addMember("human","member");const state=await this.getState();for(const type of ["human","agent"] as const)state.tasks[type]={id:type,goal:"Synthetic local fixture",contributor:{id:type,name:type,type},baseCommit:"a".repeat(40),currentCommit:"b".repeat(40),status:"ready",allowedScope:[],requirements:[],workspace:{repoName:"synthetic",remote:"https://fixture.invalid",branch:type},checkpoints:[],createdAt:"2026-10-03",updatedAt:"2026-10-03"};state.acceptedState.history=[{commit:"b".repeat(40),candidateId:"candidate",acceptedAt:"2026-10-03",participatingTasks:["human"],evidenceId:"evidence",outputDigest:"digest"},{commit:"c".repeat(40),candidateId:"agentcandidate",acceptedAt:"2026-10-03",participatingTasks:["agent"],evidenceId:"evidence",outputDigest:"digest"}];this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS git_task_writers(task_id TEXT PRIMARY KEY,user_id TEXT NOT NULL)");this.ctx.storage.sql.exec("INSERT INTO git_task_writers VALUES('human','human'),('agent','human')");this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS repository_visibility(id INTEGER PRIMARY KEY,visibility TEXT,version INTEGER,confirmed_by TEXT)");this.ctx.storage.sql.exec("INSERT INTO repository_visibility VALUES(1,'public',1,'owner')");new PublicDirectory(this.ctx.storage).configure({enabled:true,confirmed:true,expectedVersion:0},true);}
 async collision(){await this.addMember("first-0123456789ab","member");await this.addMember("second-0123456789ab","member");const state=await this.getState();for(const [taskId,userId] of [["first","first-0123456789ab"],["second","second-0123456789ab"]]){state.tasks[taskId!]={...state.tasks.human!,id:taskId!,contributor:{type:"human",id:"0123456789ab",name:"Same name"}};this.ctx.storage.sql.exec("INSERT INTO git_task_writers VALUES(?,?)",taskId!,userId!);}this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));}
 async withdraw(){new PublicDirectory(this.ctx.storage).configure({enabled:false,confirmed:true,expectedVersion:1},true);}
}
export default {async fetch(request:Request,env:{REPOSITORY_CONTROLLER:DurableObjectNamespace<PeopleFixture>}){const url=new URL(request.url),repo=env.REPOSITORY_CONTROLLER.getByName(`project:${id}`);if(url.pathname==="/seed"){await repo.seed();return new Response("ok");}if(url.pathname==="/collision"){await repo.collision();return new Response("ok");}if(url.pathname==="/withdraw"){await repo.withdraw();return new Response("ok");}if(url.pathname==="/remove"){await repo.removeMember("human");return new Response("ok");}if(url.pathname==="/private-people"){try{return Response.json(await repo.peopleAttributionSnapshot(url.searchParams.get("actor")??"human"));}catch{return new Response("Private member access unavailable",{status:403});}}if(url.pathname==="/private-assert"){return Response.json({valid:await repo.assertPeopleAttributionSnapshot(url.searchParams.get("actor")??"human",url.searchParams.get("stamp")??"")});}return Response.json(await repo.publicAcceptedActivity(url.searchParams.get("actor")??"human"));}};
