import worker from "../../src/server/worker";
import {RepositoryController} from "../../src/server/durable-object";
import {PrivateRecoveryOperations} from "../../src/server/private-recovery";
import {GitGatewayLedger} from "../../src/server/git-gateway-ledger";
import {accountKeyFor} from "../../src/server/projects";
import type {Env} from "../../src/server/env";
import type {Task} from "../../src/core/types";
const projectId="p123456789abc";
export class GatewayRecoveryHttpFixture extends RepositoryController{
 async seed(){await this.initialize({projectId,projectName:"Synthetic Git recovery",canonicalRepoName:"canonical",head:"a".repeat(40),defaultBranch:"main",ownerId:"owner",verificationPolicy:{}});const incarnation=new PrivateRecoveryOperations(this.ctx.storage).incarnation(),state=await this.getState(),task:Task={id:"change",goal:"Preserve transfer outcome",contributor:{id:"member",name:"Member",type:"human"},baseCommit:"a".repeat(40),currentCommit:"a".repeat(40),allowedScope:["src/"],status:"working",requirements:[],workspace:{repoName:"workspace",remote:"https://fixture.invalid",branch:"task/change"},checkpoints:[],createdAt:"now",updatedAt:"now"};state.tasks.change=task;this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));await this.addMember("member","member");const ledger=new GitGatewayLedger(this.ctx.storage),scope={projectId,incarnation,taskId:"change",repoName:"workspace",actorId:"member",generationStamp:"private-generation",parentTokenHash:"f".repeat(64)};ledger.declareTask(scope);for(let n=0;n<21;n++){const id=crypto.randomUUID();ledger.begin(id,scope);if(n===0){ledger.issued(id,"synthetic-private-token");ledger.dispatch(id,scope);ledger.finish(id,false,false);}}}
}
export default {async fetch(request:Request,env:Env&{FIXTURE_ISSUER:string},ctx:ExecutionContext){const path=new URL(request.url).pathname,repo=env.REPOSITORY_CONTROLLER.getByName(`project:${projectId}`) as unknown as GatewayRecoveryHttpFixture;if(path==="/fixture/seed"){await repo.seed();const account=env.REPOSITORY_CONTROLLER.getByName(`account:${await accountKeyFor("owner")}`) as unknown as GatewayRecoveryHttpFixture;await account.setProfile({handle:"owner",displayName:"Owner",bio:"",joinedAt:"now"});const tokens:Record<string,string>={};for(const scope of ["full","read","write"] as const){const token=`fgt_${await accountKeyFor("owner")}_${crypto.randomUUID().replaceAll("-","")}`;await account.createApiToken("owner",scope,token,{scope,repo:projectId});tokens[scope]=token;}return Response.json(tokens);}if(path==="/fixture/delete-owner"){await (env.REPOSITORY_CONTROLLER.getByName(`account:${await accountKeyFor("owner")}`) as unknown as GatewayRecoveryHttpFixture).beginAccountDeletion();return new Response("ok");}return worker.fetch(request,{...env,API_LIMITER:{limit:async()=>({success:true})},LOOKUP_LIMITER:{limit:async()=>({success:true})},CLERK_ISSUER:env.FIXTURE_ISSUER,CLERK_AUTHORIZED_PARTIES:"https://fixture.example"} as unknown as Env,ctx);}};
