import {RepositoryController} from "../../src/server/durable-object";
import {accountOf,accountKeyFor,projectOf} from "../../src/server/projects";
import {ImportHistoryInspection} from "../../src/server/import-history-inspection";
import {ImportHistoryAttempts} from "../../src/server/import-history-attempts";
import type {Env} from "../../src/server/env";
import type {ImportJob} from "../../src/server/import-job";
let mode="";const head="a".repeat(40),oldId="import-history-11111111-1111-4111-8111-111111111111",nextId="import-history-22222222-2222-4222-8222-222222222222";
export class HistorySuccessorFixture extends RepositoryController{
 constructor(ctx:DurableObjectState,env:Env){super(ctx,{...env,IMPORT_HISTORY_WORKFLOW:{get:async()=>({status:async()=>({status:mode==="provider-running"?"running":"errored"})})}} as unknown as Env);}
 repairFixtureJob(id:string){this.ctx.storage.sql.exec("UPDATE import_jobs SET doc=json_set(doc,'$.importedBranch','codex/selected') WHERE id=?",id);}
 raw(id:string){return JSON.stringify({inspection:this.ctx.storage.sql.exec("SELECT * FROM history_inspections WHERE id=?",id).toArray(),sides:this.ctx.storage.sql.exec("SELECT * FROM history_sides WHERE op=? ORDER BY side",id).toArray(),nodes:this.ctx.storage.sql.exec("SELECT * FROM history_nodes WHERE op=? ORDER BY side,hash",id).toArray(),frontier:this.ctx.storage.sql.exec("SELECT * FROM history_frontier WHERE op=? ORDER BY side,hash",id).toArray(),attempt:this.ctx.storage.sql.exec("SELECT * FROM history_attempts WHERE op=?",id).toArray()});}
 async prepare(id:string,key:string){await this.beginHistoryInspection(id,key,head);const attempt=await this.startHistoryInspectionAttempt(id,0);const batch=await this.importHistoryBatch(id,"source");await this.commitHistoryChunk(id,"source",{batchId:batch.batchId,revision:batch.revision,requested:batch.requested,commits:[{hash:head,tree:"b".repeat(40),parents:[]}]},{generation:attempt.generation,workflowId:attempt.workflowId});await this.pauseHistoryInspection(id,"source_unavailable",{generation:attempt.generation,workflowId:attempt.workflowId});const attempts=new ImportHistoryAttempts(this.ctx.storage);if(mode==="possible")attempts.nativeAllocationIntent(id,attempt.generation);else attempts.nativeStopped(id,attempt.generation,attempt.nativeRunId);attempts.observed(id,attempt.generation,"errored");return attempt;}
}
export default{async fetch(request:Request,env:Env){mode=new URL(request.url).searchParams.get("mode")!;const owner=`owner-${mode}`,key=await accountKeyFor(owner),account=accountOf(env,key) as unknown as HistorySuccessorFixture,id=`p${mode.replace(/-/g,"").padEnd(11,"0").slice(0,11)}`,project=projectOf(env,id) as unknown as HistorySuccessorFixture,job:ImportJob={id,ownerId:owner,name:"Synthetic",canonicalRepoName:`fixture-${id}`,source:"https://github.com/synthetic/repository",branch:"codex/selected",verificationPolicy:{kind:"command",test:"bun test"},status:"ready",historyIntent:"provider-default-no-depth-requested",importedHead:head,importedBranch:"main",createdAt:"now",updatedAt:"now",detail:"Synthetic"};await account.saveImportJob(job);await project.initialize({projectId:id,projectName:job.name,canonicalRepoName:job.canonicalRepoName,head,verificationPolicy:{},kind:"import",ownerId:owner,source:job.source});await account.claimImportHistoryOperation({protocolVersion:2,projectId:id,head,canonicalRepoName:job.canonicalRepoName,ownerId:owner,instanceId:oldId});await project.prepare(oldId,key);const before=await project.raw(oldId);await account.repairFixtureJob(id);const old=await project.getHistoryInspection(oldId);let successorId:string|null=null,duplicateId:string|null=null,error=false,nextBranch:string|null=null;try{const actor={userId:owner,displayName:"Owner",viaToken:false};const next=await account.claimImportHistorySuccessor({predecessorId:oldId,expectedGeneration:mode==="generation"?2:1,instanceId:nextId},actor,undefined,mode==="expired"?Date.now()-1:Date.now()+60000);successorId=next.instanceId;duplicateId=(await account.claimImportHistorySuccessor({predecessorId:oldId,expectedGeneration:1,instanceId:"import-history-33333333-3333-4333-8333-333333333333"},actor,undefined,Date.now()+60000)).instanceId;nextBranch=(await project.beginHistoryInspection(next.instanceId,key,head)).scope.branch;}catch{error=true;}return Response.json({error,oldBranch:old?.scope.branch,scopeChanged:old?.scopeChanged,successorId,duplicateId,nextBranch,oldRowsUnchanged:before===await project.raw(oldId),operationCount:(await account.listImportHistoryOperations()).length});}};
