import{DurableObject}from"cloudflare:workers";
import{RepositoryController}from'../../src/server/durable-object';import{FlareGitImportHistoryWorkflow as ProductionHistoryWorkflow}from'../../src/server/import-history-workflow';import{accountKeyFor}from'../../src/server/projects';import type{Env}from'../../src/server/env';import type{WorkflowStep,WorkflowEvent}from'cloudflare:workers';import type{ImportHistoryParams}from'../../src/server/import-history-workflow';
export class FlareGitImportHistoryWorkflow extends ProductionHistoryWorkflow {constructor(ctx:ExecutionContext,env:Env){super(ctx,{...env,MANAGED_ACCOUNT_MONTHLY_USD_MICROS:"0",MANAGED_GLOBAL_MONTHLY_USD_MICROS:"0",MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:"0",MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:"0"});}}
const projectId='p123456789abc',owner='synthetic-owner',operation='import-history-synthetic',tree='a'.repeat(40),sha=(n:number)=>n.toString(16).padStart(40,'0'),head=sha(301);
export class SyntheticHistoryVM extends DurableObject{async exec(argv:string[]){const command=argv[2]??"";let stdout="";if(command.includes("is-shallow"))stdout="false";else if(command.includes("rev-parse"))stdout=head;else if(command.includes("log --max-count")){const count=(await this.ctx.storage.get<number>("chunks")??0)+1;await this.ctx.storage.put("chunks",count);if(count===2)throw Error("Synthetic source interruption after persisted chunk");const roots=[...command.matchAll(/'([a-f0-9]{40})'/g)].map(match=>Number.parseInt(match[1]!,16)),top=Math.max(...roots);stdout=Array.from({length:Math.min(256,top)},(_,i)=>{const n=top-i;return `${sha(n)} ${tree}${n>1?` ${sha(n-1)}`:""}`;}).join("\n");}return{success:true,stdout,stderr:""};}async destroy(){await this.ctx.storage.put("stopped",true);}async lifetimeStatus(){return{state:await this.ctx.storage.get("stopped")?"stopped":"running"};}}
export class SyntheticBoundHistoryWorkflow extends ProductionHistoryWorkflow{constructor(ctx:ExecutionContext,env:Env){super(ctx,{...env,MANAGED_ACCOUNT_MONTHLY_USD_MICROS:"5000000",MANAGED_GLOBAL_MONTHLY_USD_MICROS:"10000000",MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:"1000000",MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:"2000000",CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:"2500000",CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:"5000000",ARTIFACTS:{get:async()=>{const snapshot=await(env.REPOSITORY_CONTROLLER.getByName(`project:${projectId}`)as unknown as HistoryWorkflowFixture).getHistoryInspection(operation);if(snapshot?.source.pending!==0||snapshot.currentAttempt?.nativeState!=="stopped")throw Error("Synthetic provider refuses reads before confirmed source workspace stop");const global=env.REPOSITORY_CONTROLLER.getByName("global")as unknown as HistoryWorkflowFixture;await global.fixtureCount("source-stopped-before-metadata");await global.fixtureCount("metadata-get");return{readCommit:async(hash:string)=>{const n=Number.parseInt(hash,16);return{hash,treeHash:tree,parents:n>1?[sha(n-1)]:[]};},[Symbol.dispose]:()=>{}};}}}as unknown as Env);}}
export class HistoryWorkflowFixture extends RepositoryController{async fixtureCount(key:string){await this.ctx.storage.put(key,(await this.ctx.storage.get<number>(key)??0)+1);}async fixtureMetrics(){return{artifactGets:await this.ctx.storage.get<number>("metadata-get")??0,sourceStoppedChecks:await this.ctx.storage.get<number>("source-stopped-before-metadata")??0};}fixtureJob(){this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS import_jobs(id TEXT PRIMARY KEY,doc TEXT NOT NULL)');this.ctx.storage.sql.exec('INSERT OR REPLACE INTO import_jobs VALUES(?,?)',projectId,JSON.stringify({id:projectId,ownerId:owner,status:'ready',source:'https://github.com/synthetic/repository.git',canonicalRepoName:'synthetic-repository',importedHead:head,importedBranch:'main'}));}}
export default{async fetch(request:Request,env:Env,ctx:ExecutionContext){const path=new URL(request.url).pathname,key=await accountKeyFor(owner),account=env.REPOSITORY_CONTROLLER.getByName(`account:${key}`)as unknown as HistoryWorkflowFixture,project=env.REPOSITORY_CONTROLLER.getByName(`project:${projectId}`)as unknown as HistoryWorkflowFixture;
try{
if(path==='/seed'){await project.initialize({projectId,projectName:'Synthetic import',canonicalRepoName:'synthetic-repository',head,verificationPolicy:{}});await project.addMember(owner,'owner');await account.fixtureJob();await account.claimImportHistoryOperation({projectId,head,canonicalRepoName:'synthetic-repository',ownerId:owner,instanceId:operation,protocolVersion:2});await project.beginHistoryInspection(operation,key,head);return Response.json(await project.startHistoryInspectionAttempt(operation,0));}
if(path==='/binding-start'||path==='/bound-start'){const a=(await project.historyInspectionAttempt(operation))!;await (path==='/bound-start'?(env as unknown as {BOUND_HISTORY:Env["IMPORT_HISTORY_WORKFLOW"]}).BOUND_HISTORY:env.IMPORT_HISTORY_WORKFLOW).create({id:a.workflowId,params:{accountKey:key,projectId,expectedHead:head,operationId:operation,attemptGeneration:a.generation}});return Response.json(a);}
if(path==='/binding-status'||path==='/bound-status'){const a=(await project.historyInspectionAttempt(operation))!;return Response.json(await(await(path==='/bound-status'?(env as unknown as {BOUND_HISTORY:Env["IMPORT_HISTORY_WORKFLOW"]}).BOUND_HISTORY:env.IMPORT_HISTORY_WORKFLOW).get(a.workflowId)).status());}
if(path==='/metrics')return Response.json(await(env.REPOSITORY_CONTROLLER.getByName('global')as unknown as HistoryWorkflowFixture).fixtureMetrics());
if(path==='/snapshot')return Response.json(await project.getHistoryInspection(operation));
if(path==='/unknown'){const a=await project.historyInspectionAttempt(operation);await project.markHistoryInspectionDispatch(operation,a!.generation);return Response.json(await project.startHistoryInspectionAttempt(operation,a!.generation));}
if(path==='/resume'){const a=await project.historyInspectionAttempt(operation);await project.observeHistoryInspectionAttempt(operation,a!.generation,'errored');return Response.json(await project.startHistoryInspectionAttempt(operation,a!.generation));}
if(path.startsWith('/run')){const a=(await project.historyInspectionAttempt(operation))!;let nativeReads=0,artifactReads=0,artifactGets=0,r2Writes=0,stopped=false;const fake={...env,MANAGED_ACCOUNT_MONTHLY_USD_MICROS:path.includes('denied')?'0':'5000000',MANAGED_GLOBAL_MONTHLY_USD_MICROS:'10000000',MANAGED_ESSENTIAL_ACCOUNT_MONTHLY_USD_MICROS:path.includes('denied')?'0':'1000000',MANAGED_ESSENTIAL_GLOBAL_MONTHLY_USD_MICROS:'2000000',CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:'2500000',CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:'5000000',EVIDENCE_BUCKET:{put:async()=>{r2Writes++;throw Error('Synthetic R2 unavailable');}},INTEGRATOR:{getByName:()=>({exec:async(argv:string[])=>{nativeReads++;const command=argv[2]??'';let stdout='';if(command.includes('is-shallow'))stdout='false';else if(command.includes('rev-parse'))stdout=head;else if(command.includes('log --max-count')){const roots=[...command.matchAll(/'([a-f0-9]{40})'/g)].map(match=>Number.parseInt(match[1]!,16));const top=Math.max(...roots);stdout=Array.from({length:Math.min(256,top)},(_,i)=>{const n=top-i;return `${sha(n)} ${tree}${n>1?` ${sha(n-1)}`:''}`;}).join('\n');}return{success:true,stdout,stderr:''};},destroy:async()=>{stopped=true;},lifetimeStatus:async()=>({state:stopped?'stopped':'running'})})},ARTIFACTS:{get:async()=>{artifactGets++;return{readCommit:async(hash:string)=>{artifactReads++;const n=Number.parseInt(hash,16);return{hash,treeHash:tree,parents:n>1?[sha(n-1)]:[]};},[Symbol.dispose]:()=>{}};}}}as unknown as Env;
let chunks=0;const step={do:async(name:string,...args:unknown[])=>{if(path.includes('interrupt')&&name.startsWith('capture-history-chunk')&&chunks++===1)throw Error('Synthetic interruption after first saved chunk');const fn=args.at(-1)as()=>Promise<unknown>;return fn();}}as unknown as WorkflowStep;const workflow=new ProductionHistoryWorkflow(ctx as unknown as ConstructorParameters<typeof ProductionHistoryWorkflow>[0],fake);let result:unknown;try{result=await workflow.run({payload:{accountKey:key,projectId,expectedHead:head,operationId:operation,attemptGeneration:a.generation},instanceId:a.workflowId}as WorkflowEvent<ImportHistoryParams>,step);}catch(error){result={error:error instanceof Error?error.message:'error'};}return Response.json({result,nativeReads,artifactReads,artifactGets,r2Writes,stopped:(await env.INTEGRATOR.getByName(a.nativeRunId).lifetimeStatus())?.state==="stopped",snapshot:await project.getHistoryInspection(operation)});}
return new Response('missing',{status:404});}catch(error){return new Response(error instanceof Error?error.message:'failure',{status:409});}}};
