import {RepositoryController} from "../../src/server/durable-object";
import {inspectSavedImport} from "../../src/server/import-read-lifecycle";
import {accountKeyFor,accountOf,projectOf,globalOf} from "../../src/server/projects";
import type {Env} from "../../src/server/env";
import type {ImportJob} from "../../src/server/import-job";
const head="a".repeat(40),tree="b".repeat(40),branch="codex/docs-community-and-delivery";let mode="",commands=0,revoked=0;
function provider(env:Env):Env{return{...env,ARTIFACTS:{get:async()=>({info:async()=>({remote:`https://${"1".repeat(32)}.artifacts.cloudflare.net/import.git`,defaultBranch:"main"}),createToken:async()=>({scope:"read",plaintext:"synthetic-read-only",expiresAt:new Date(Date.now()+60000).toISOString()}),revokeToken:async()=>{revoked++;return mode!=="credential-cleanup";},[Symbol.dispose]() {}})},INTEGRATOR:{getByName:()=>({exec:async(args:string[])=>{commands++;const command=args[2]!;if(/git .*\b(push|checkout|reset)\b/.test(command))throw new Error("Synthetic witness forbids writes");return{success:true,stdout:command.includes("ls-remote")?`${head}\trefs/heads/${branch}\n`:command.includes("^{commit}")?`${head}\n`:command.includes("^{tree}")?`${tree}\n`:"",stderr:""};},destroy:async()=>{},lifetimeStatus:async()=>({state:mode==="native-cleanup"?"unknown":"stopped"})})}} as unknown as Env;}
export class ImportReadFixture extends RepositoryController{constructor(ctx:DurableObjectState,env:Env){super(ctx,provider(env));}}
export default{async fetch(request:Request,input:Env){mode=new URL(request.url).searchParams.get("mode")!;commands=revoked=0;const env=provider(input),key=await accountKeyFor(`owner-${mode}`),account=accountOf(env,key),id=`p${mode.replace(/-/g,"").padEnd(11,"0").slice(0,11)}`,project=projectOf(env,id),job:ImportJob={id,ownerId:`owner-${mode}`,name:"Synthetic imported branch",canonicalRepoName:`flaregit-${id.slice(1)}`,source:"https://github.com/Joe-Simo/flaregit",branch,verificationPolicy:{kind:"command",test:"bun test",allowedScope:["*"],protectedPaths:[]},status:"ready",historyIntent:"provider-default-no-depth-requested",importedHead:head,importedBranch:"main",createdAt:"now",updatedAt:"now",detail:"Synthetic"};
 await account.saveImportJob(job);await globalOf(env).reconcileArtifactInventory("fixture",[]);if(mode!=="storage")await globalOf(env).reserveArtifactStorage(job.canonicalRepoName,key,"import",id,{globalSlots:100,accountSlots:10});await project.initialize({projectId:id,projectName:job.name,canonicalRepoName:job.canonicalRepoName,head,verificationPolicy:{},kind:"import",defaultBranch:"main",ownerId:job.ownerId,source:job.source});
 const before=await project.getState(),ready=await inspectSavedImport(env,job,undefined,mode==="expired"?Date.now()-1:Date.now()+60000);let repaired=false;
 if(ready.status==="ready"){if(mode==="contribution"){const task={id:"task",goal:"Synthetic",contributor:{id:job.ownerId,name:"Owner",type:"human" as const},baseCommit:head,currentCommit:head,allowedScope:[],status:"working" as const,requirements:[],workspace:{repoName:"workspace",remote:"https://private.invalid",branch:"task"},checkpoints:[],createdAt:"now",updatedAt:"now"};await project.createTask(task,job.ownerId,{goal:task.goal,dependsOn:null,issue:null});}try{await account.repairImportBranch(job,ready.defaultBranch);repaired=true;}catch{}}
 const after=await project.getState(),saved=await account.getImportJob(id),native=await globalOf(env).nativeComputeStatus(`import-read-${id}`);return Response.json({ready:ready.status,repaired,branch:after.defaultBranch,savedBranch:saved?.importedBranch,head:after.acceptedState.currentCommit,historyUnchanged:JSON.stringify(before.acceptedState)===JSON.stringify(after.acceptedState),commands,revoked,nativeActive:native?.active??false});}};
