import {RetainedInputs} from "../../src/server/retained-inputs";
import {VERIFIER_IDENTITIES} from "../../src/core/verification-identities";
import type {Task,VerificationEvidence} from "../../src/core/types";
import {runWorkflowMirrorFollowup} from "../../src/server/workflow-mirror";
import {PrivateRecoveryOperations} from "../../src/server/private-recovery";
import worker from "../../src/server/worker";
import {RepositoryController} from "../../src/server/durable-object";
import {accountKeyFor} from "../../src/server/projects";
import type {Env} from "../../src/server/env";
interface Bindings {NATIVE_FIXTURE:string;ISSUER:string;HEAD:string;TREE:string}
const first="p123456789abc",second="p223456789abc";
function provider(env:Bindings){const call=async(value:unknown)=>{const response=await fetch(env.NATIVE_FIXTURE,{method:"POST",body:JSON.stringify(value)});if(!response.ok)throw Error("Fixture provider outcome unavailable");return response.json();};return{ARTIFACTS:{get:async(name:string)=>{let disposeFault=false;return({info:async()=>({id:`fixture-${name}`,name,remote:`https://${"a".repeat(32)}.artifacts.cloudflare.net/${name}`}),createToken:async(scope:string,seconds:number)=>{const value=await call({kind:"issue",name,scope,seconds}) as {plaintext:string;scope:string;expiresAt:string;disposeFault?:boolean};disposeFault=value.disposeFault===true;return value;},revokeToken:async(token:string)=>call({kind:"revoke",name,token}),[Symbol.dispose](){if(disposeFault)throw Error("Synthetic SDK disposal failure after issuance");}});}},INTEGRATOR:{getByName:(name:string)=>({exec:async(args:string[],options?:{env?:Record<string,string>})=>call({kind:"exec",name,command:args[2],environment:options?.env}),seal:async()=>{await call({kind:"seal",name});},destroy:async()=>{await call({kind:"stop",name});},lifetimeStatus:async()=>call({kind:"lifetime",name})})}};}
export class MirrorRunHttpFixture extends RepositoryController{
 constructor(ctx:DurableObjectState,env:Env&Bindings){super(ctx,{...env,...provider(env)} as unknown as Env);}
 async seed(projectId:string,head:string,tree:string){await this.initialize({projectId,projectName:"Local mirror fixture",canonicalRepoName:projectId===first?"canonical":"canonical-two",head,defaultBranch:"trunk",ownerId:"owner",verificationPolicy:{kind:"git-integrity"}});new PrivateRecoveryOperations(this.ctx.storage).incarnation();const state=await this.getState();if(!state.acceptedBaseline)throw Error("Fixture accepted baseline missing");state.acceptedBaseline.tree=tree;this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));await this.addMember("member","member");}
 async prepareActualAutomaticAuthority(head:string,tree:string){const stamp=new Date().toISOString(),state=await this.getState(),task:Task={id:"automatic-task",goal:"Local accepted workflow mirror fixture",contributor:{id:"owner",name:"Owner",type:"human"},baseCommit:head,currentCommit:head,allowedScope:["*"],status:"ready",requirements:[],workspace:{repoName:"workspace-auto",remote:"https://fixture.invalid",branch:"task/automatic"},checkpoints:[],createdAt:stamp,updatedAt:stamp};await this.createTask(task,"owner",{goal:task.goal,dependsOn:null,issue:null});const workflowId="automatic-workflow-fixture";await this.registerWorkflow(workflowId,"integration",undefined,"owner",1);const landing=await this.claimLanding({holder:workflowId,taskIds:[task.id],preservationProtocolVersion:1});if(!("candidate" in landing)||!landing.candidate)throw Error("Automatic fixture landing unavailable");const candidate=landing.candidate,evidence:VerificationEvidence={id:"automatic-evidence",candidateCommit:head,candidateTree:tree,expectedAcceptedBase:head,requirementsVersion:1,policy:state.verificationPolicy,testBundleDigest:"fixture",toolchainDigest:"fixture",builtOutputDigest:"fixture",verifierIdentity:VERIFIER_IDENTITIES["git-integrity"],testResults:[],timestamp:stamp,status:"passed"};await this.recordVerification(candidate.id,head,evidence);const input=await this.prepareRetainedInput(task.id,workflowId,candidate.id,crypto.randomUUID());new RetainedInputs(this.ctx.storage).record(input,{commit:head,base:head});await this.awaitReview(candidate.id,head,workflowId);const review=await this.recordReview(candidate.id,{approved:true,actor:{userId:"owner",displayName:"Owner",viaToken:false}},head);if(!review.ok)throw Error(review.error);const prepared=await this.preparePublish(candidate.id);if(!prepared.ok||!prepared.journal)throw Error("Automatic fixture journal unavailable");await this.completePublish(prepared.journal.id);return{workflowId,journalId:prepared.journal.id};}
 fixtureMirrorCredentialFacts(id:string){const row=this.ctx.storage.sql.exec<{expiry:number;revoked:number}>("SELECT json_extract(doc,'$.expiresAt') AS expiry,json_extract(doc,'$.credentialRevoked') AS revoked FROM mirror_executions WHERE id=?",id).toArray()[0];return row??null;}
 async ownerRole(role:"owner"|"member"){await this.addMember("owner",role);}
}
export default{async fetch(request:Request,env:Env&Bindings,ctx:ExecutionContext){const url=new URL(request.url),repo=env.REPOSITORY_CONTROLLER.getByName(`project:${first}`) as unknown as MirrorRunHttpFixture;if(url.pathname==="/fixture/seed"){for(const id of [first,second])await(env.REPOSITORY_CONTROLLER.getByName(`project:${id}`) as unknown as MirrorRunHttpFixture).seed(id,env.HEAD,env.TREE);await(env.REPOSITORY_CONTROLLER.getByName(`account:${await accountKeyFor("owner")}`) as unknown as MirrorRunHttpFixture).setProfile({handle:"owner",displayName:"Owner",bio:"",joinedAt:"now"});return new Response("ok");}if(url.pathname==="/fixture/automatic-authority"){return Response.json(await repo.prepareActualAutomaticAuthority(env.HEAD,env.TREE));}if(url.pathname==="/fixture/automatic"){const input=await request.json() as {workflowId:string;journalId:string};return Response.json(await runWorkflowMirrorFollowup({...env,...provider(env)} as unknown as Env,repo,input.workflowId,input.journalId,"refs/heads/trunk"));}if(url.pathname==="/fixture/credential-facts"){return Response.json(await repo.fixtureMirrorCredentialFacts(url.searchParams.get("id")!));}if(url.pathname==="/fixture/revoke-owner"){await repo.ownerRole("member");return new Response("ok");}if(url.pathname==="/fixture/restore-owner"){await repo.ownerRole("owner");return new Response("ok");}const original=globalThis.fetch;globalThis.fetch=Object.assign(async(input:Parameters<typeof fetch>[0],init?:Parameters<typeof fetch>[1])=>{const incoming=new URL(input instanceof Request?input.url:String(input));if(incoming.hostname!=="github.com")return original(input,init);const response=await original(env.NATIVE_FIXTURE,{method:"POST",body:JSON.stringify({kind:"advertisement",target:`${incoming.origin}${incoming.pathname.replace(/\/info\/refs$/,"")}`})});return new Response(await response.text(),{status:response.status,headers:{"Content-Type":"application/x-git-upload-pack-advertisement"}});},{preconnect:original.preconnect});try{return await worker.fetch(request,{...env,...provider(env),API_LIMITER:{limit:async()=>({success:true})},LOOKUP_LIMITER:{limit:async()=>({success:true})},CLERK_ISSUER:env.ISSUER,CLERK_AUTHORIZED_PARTIES:"https://fixture.example"} as unknown as Env,ctx);}finally{globalThis.fetch=original;}}};
