import { RepositoryController } from "../../src/server/durable-object";
import type {DirectoryRegistration} from "../../src/server/public-directory";
export class DirectoryFixture extends RepositoryController {
  failAfterRegistration(enabled:boolean){this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS directory_fault(id INTEGER PRIMARY KEY,enabled INTEGER)");this.ctx.storage.sql.exec("INSERT INTO directory_fault VALUES(1,?) ON CONFLICT(id) DO UPDATE SET enabled=excluded.enabled",Number(enabled));}
  override async registerDirectory(input:DirectoryRegistration){await super.registerDirectory(input);if(this.ctx.storage.sql.exec<{enabled:number}>("SELECT enabled FROM directory_fault WHERE id=1").toArray()[0]?.enabled)throw new Error("Unknown registration response");}
  async runAlarm(){await this.alarm();}
  async alarmTime(){return this.ctx.storage.getAlarm();}
}
interface FixtureEnv{REPOSITORY_CONTROLLER:DurableObjectNamespace<DirectoryFixture>}
export default {async fetch(request:Request,env:FixtureEnv){const url=new URL(request.url),repo=env.REPOSITORY_CONTROLLER.get(env.REPOSITORY_CONTROLLER.idFromName("project:p123456abcdef")),global=env.REPOSITORY_CONTROLLER.get(env.REPOSITORY_CONTROLLER.idFromName("global"));try{switch(url.pathname){case"/seed":await global.failAfterRegistration(false);await repo.initialize({projectId:"p123456abcdef",projectName:"Real directory fixture",canonicalRepoName:"private-canonical",head:"a".repeat(40),verificationPolicy:{},ownerId:"owner"});await repo.setRepositoryVisibility("public",true,"owner");return Response.json({});case"/fault":await global.failAfterRegistration(url.searchParams.get("enabled")==="true");return Response.json({});case"/configure":return Response.json(await repo.configureDirectory(await request.json(),url.searchParams.get("actor")??"owner"));case"/state":return Response.json({state:await repo.directoryState(),alarm:await repo.alarmTime()});case"/page":return Response.json(await global.directoryPage());case"/alarm":await repo.runAlarm();return Response.json(await repo.directoryState());case"/private":await repo.setRepositoryVisibility("private",false,"owner");return Response.json(await repo.directoryState());default:return new Response("Missing",{status:404});}}catch{return new Response("Refused",{status:409});}}};
