import {RefReadCredentialIncidents} from "../../src/server/ref-read-credential-incidents";
import {RepositoryController} from "../../src/server/durable-object";
import {PrivateRecoveryOperations} from "../../src/server/private-recovery";
import {accountKeyFor,globalOf} from "../../src/server/projects";
import type {Env} from "../../src/server/env";
import type {FlareGitProjectState} from "../../src/core/types";
const base="a".repeat(40),commit="c".repeat(40),tree="d".repeat(40),head="e".repeat(40),journalId="jrnl_12345678-1234-1234-1234-123456789abc";
export class PublicationReadbackFixture extends RepositoryController {
 async seed(mode:string){await this.initialize({projectId:"p123456789abc",projectName:"Synthetic readonly Git ancestry",canonicalRepoName:"canonical",head:base,ownerId:"current-owner",verificationPolicy:{}});new PrivateRecoveryOperations(this.ctx.storage).incarnation();await this.ctx.storage.put({mode,providerCalls:0});const state=await this.getState();state.tasks.task={id:"task",goal:"Synthetic",contributor:{id:"old-owner",name:"Old owner",type:"human"},baseCommit:base,currentCommit:"b".repeat(40),allowedScope:["*"],status:"integrating",requirements:[],workspace:{repoName:"fork",remote:"https://fixture.invalid",branch:"work"},checkpoints:[],createdAt:"now",updatedAt:"now"};
 if(mode==="newer")state.acceptedState.currentCommit=head;
 state.candidates.candidate={id:"candidate",attemptNumber:1,participatingTaskIds:["task"],participatingCommits:{task:"b".repeat(40)},expectedAcceptedBase:base,frozenPolicyVersion:1,frozenVerificationPolicy:{},frozenRequirements:[],repairAttempts:[],candidateCommit:commit,status:"verified",evidenceId:"proof",workflowInstanceId:"workflow",createdAt:"now",updatedAt:"now",review:{approved:true,by:"Old owner",actor:{userId:"old-owner",displayName:"Old owner",viaToken:false},at:"now",commit}};
 state.evidence.proof={id:"proof",candidateCommit:commit,candidateTree:tree,status:"passed"} as FlareGitProjectState["evidence"][string];state.journal.push({id:journalId,candidateId:"candidate",candidateCommit:commit,candidateTree:tree,expectedHead:base,newHead:commit,outputDigest:"synthetic",state:"PREPARED",timestamp:"now"});this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS integration_dispatch_receipts(event_id TEXT PRIMARY KEY,payload TEXT NOT NULL,actor_id TEXT,outcome TEXT,terminal INTEGER NOT NULL DEFAULT 0)");this.ctx.storage.sql.exec("INSERT INTO integration_dispatch_receipts VALUES('workflow','[]','old-owner','awaiting_review',0)");}
 protected override async publicationNativeHead(_context:unknown,_scope:string,_journalId:string,_ref:string,authorize:()=>Promise<void>){await authorize();return head;}
 protected override publicationRecoveryProvider():Pick<Env,"ARTIFACTS"> {
  const meta=(hash:string)=>({hash,treeHash:hash===commit?tree:base,parents:[],message:"Synthetic provider ancestry",author:{name:"Fixture",email:"fixture@example.invalid"},committer:{name:"Fixture",email:"fixture@example.invalid"},authoredAt:0,committedAt:0});
  const called=async()=>{const n=Number(await this.ctx.storage.get("providerCalls")??0)+1;await this.ctx.storage.put("providerCalls",n);if(await this.ctx.storage.get("mode")==="revoked"&&n===2)await this.addMember("current-owner","member");};
  const capability={log:async(options?:{ref?:string;offset?:number;limit?:number})=>{await called();const mode=await this.ctx.storage.get("mode");if(options?.limit===1)throw new Error("Mutable SDK ref observations are not authority");if(mode==="missing"||mode==="automatic-missing"||mode==="revoked")return [meta(head),meta(base)];if(mode==="truncated")return Array.from({length:100},(_,i)=>meta((Number(options?.offset??0)+i+1).toString(16).padStart(40,"0")));return [meta(head),meta(commit),meta(base)];},readCommit:async(hash:string)=>{await called();return await this.ctx.storage.get("mode")==="wrong-tree"?{...meta(hash),treeHash:base}:meta(hash);},[Symbol.dispose]:()=>{}};
  return {ARTIFACTS:{get:async()=>{await called();return capability;}}} as unknown as Pick<Env,"ARTIFACTS">;
 }
 async check(requestId:string){return this.checkOwnerPublicationReadback(journalId,requestId,{userId:"current-owner",displayName:"Current owner",viaToken:false},undefined,Date.now()+60000);}
 async mutateScope(mode:"incarnation"|"canonical"){if(mode==="incarnation")this.ctx.storage.sql.exec("UPDATE private_recovery_incarnation SET value=? WHERE id=1",crypto.randomUUID());else{const state=await this.getState();state.canonicalRepoName="different-private-repository";this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));}}
 async credentialProof(){const ledger=new RefReadCredentialIncidents(this.ctx.storage),id=crypto.randomUUID(),expiry=Date.now()+60000,context={kind:"publication" as const,operationId:journalId,projectId:"p123456789abc",incarnation:crypto.randomUUID(),repoName:"canonical",actorId:"current-owner",accountKey:"account",snapshotDigest:"a".repeat(64),ref:"refs/heads/main"};const first=ledger.begin(id,context,expiry,()=>{}),duplicate=ledger.begin(id,context,expiry,()=>{});let changedDenied=false;try{ledger.begin(id,{...context,repoName:"other"},expiry,()=>{});}catch{changedDenied=true;}const unknown=ledger.summary(id),unknownHeld=ledger.hasPending();await ledger.record(id,"canonical","fixture-secret",Number.NaN);const receipt=ledger.summary(id);await ledger.record(id,"canonical","fixture-secret",Number.NaN);let mismatchDenied=false;try{await ledger.markRevoked(id,"wrong-secret");}catch{mismatchDenied=true;}await ledger.markRevoked(id,"fixture-secret");return {first,duplicate,changedDenied,unknown,unknownHeld,receipt,mismatchDenied,revoked:ledger.summary(id),held:ledger.hasPending(),pending:ledger.pendingBatch().length};}
 async credentialDeniedProof(){const ledger=new RefReadCredentialIncidents(this.ctx.storage),id=crypto.randomUUID(),expiry=Date.now()+60000;ledger.begin(id,{kind:"task-ready",operationId:id,projectId:"p123456789abc",incarnation:crypto.randomUUID(),repoName:"canonical",actorId:"current-owner",accountKey:await accountKeyFor("current-owner"),snapshotDigest:"a".repeat(64),ref:"refs/heads/main"},expiry,()=>{});await ledger.record(id,"canonical","retained-fixture-secret",expiry);const wakeBefore=ledger.nextWake();for(let i=0;i<6;i++)await this.alarm();const row=this.ctx.storage.sql.exec<{attempts:number;automatic_sweeps:number;token:string|null}>("SELECT attempts,automatic_sweeps,token FROM ref_read_credential_incidents WHERE id=?",id).one();return {wakeBefore:wakeBefore!==null,wakeAfter:ledger.nextWake(),attempts:row.attempts,sweeps:row.automatic_sweeps,secretRetained:row.token!==null,status:ledger.summary(id)?.status,held:ledger.hasPending(),batch:ledger.pendingBatch().length,manualAvailable:ledger.credentialForRevocation(id)!==null};}
 async callCount(){return Number(await this.ctx.storage.get("providerCalls")??0);}
 async runAlarms(){for(let i=0;i<6;i++)await this.alarm();}
 async snapshot(){return {state:await this.getState(),calls:await this.ctx.storage.get("providerCalls"),reports:await this.ownerPublicationReadbacks({userId:"current-owner",displayName:"Owner",viaToken:false},undefined,Date.now()+60000),outcome:this.ctx.storage.sql.exec("SELECT outcome,terminal FROM integration_dispatch_receipts").one(),automatic:this.ctx.storage.sql.exec("SELECT attempts FROM publication_readbacks").toArray()};}
}
export default {async fetch(request:Request,env:Env){const mode=new URL(request.url).searchParams.get("mode")!,repo=env.REPOSITORY_CONTROLLER.getByName(`project:${mode}`) as unknown as PublicationReadbackFixture;try{await repo.seed(mode);if(mode==="credential-budget")return Response.json(await repo.credentialDeniedProof());if(mode==="credentials")return Response.json(await repo.credentialProof());if(mode==="budget"){const key=await accountKeyFor("current-owner");await globalOf(env).reserveRepositoryReadOperation("saturate-owner",key);await repo.runAlarms();return Response.json(await repo.snapshot());}if(mode==="automatic-missing"){await repo.runAlarms();return Response.json(await repo.snapshot());}const requestId=crypto.randomUUID(),first=await repo.check(requestId);if(first.reason==="confirmed"&&["rotate-incarnation","rotate-canonical"].includes(mode)){const callsBefore=await repo.callCount();await repo.mutateScope(mode==="rotate-incarnation"?"incarnation":"canonical");let denied=false;try{await repo.check(requestId);}catch{denied=true;}return Response.json({denied,callsBefore,callsAfter:await repo.callCount()});}
 if(first.reason==="confirmed"){const before=await repo.snapshot(),replay=await repo.check(requestId),after=await repo.snapshot();return Response.json({first,replay,before,after,state:await repo.getState()});}if(mode==="revoked")return Response.json({first,state:await repo.getState()});const before=await repo.snapshot(),replay=await repo.check(requestId),after=await repo.snapshot();return Response.json({first,before,replay,after});}catch(error){return Response.json({error:error instanceof Error?error.message:"Fixture failure"},{status:500});}}};
