import {admitNativeCompute} from "../../src/server/native-compute";
import {taskSourceInspectionScopeSchema} from "../../src/server/task-source-inspections";
import {TaskCreationIntents} from "../../src/server/task-creation-intents";
import worker from "../../src/server/worker";
import {RepositoryController} from "../../src/server/durable-object";
import {accountKeyFor} from "../../src/server/projects";
import type {Env} from "../../src/server/env";
interface FixtureBindings{NATIVE_FIXTURE:string;FIXTURE_ISSUER:string}
function provider(env:FixtureBindings){const call=async(body:unknown)=>{const result=await fetch(env.NATIVE_FIXTURE,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!result.ok)throw Error("Synthetic provider outcome unknown");return result.json();};return{ARTIFACTS:{list:async()=>call({kind:"list"}),create:async(name:string,options:{description?:string;setDefaultBranch?:string})=>call({kind:"create",name,options}),get:async(name:string)=>({info:async()=>call({kind:"info",name}),fork:async(destination:string,options:{description:string;defaultBranchOnly:boolean})=>call({kind:"fork",name,destination,options}),readCommit:async(commit:string)=>call({kind:"read-commit",name,commit}),readTree:async(tree:string)=>call({kind:"read-tree",name,tree}),readBlob:async(blob:string)=>{const value=await call({kind:"read-blob",name,blob}) as {content:string};return new Blob([value.content]);},createToken:async(scope:string,options:{ttlSeconds:number})=>call({kind:"read-token",name,scope,options}),revokeToken:async(token:string)=>call({kind:"revoke",name,token}),[Symbol.dispose]() {}})},INTEGRATOR:{getByName:(name:string)=>({exec:async(args:string[],options?:{env?:Record<string,string>})=>call({kind:"exec",nativeName:name,command:args[2],environment:options?.env}),seal:async()=>{await call({kind:"seal",nativeName:name});},destroy:async()=>{await call({kind:"destroy",nativeName:name});},lifetimeStatus:async()=>call({kind:"lifetime",nativeName:name})})}};}
export class ReadmeCreationHttpFixture extends RepositoryController{
 private fixtureBridge:string;
 fixtureManagedReservation(runId:string){const row=this.ctx.storage.sql.exec<{charged:number;seconds:number;calls:number}>("SELECT charged,json_extract(doc,'$.containerSeconds') AS seconds,json_extract(doc,'$.calls') AS calls FROM managed_spend WHERE run_id=?",runId).toArray()[0];return row??null;}
 async seedLegacyUntouchedSpentInspection(taskId:string){const intent=new TaskCreationIntents(this.ctx.storage).forTask(taskId);if(!intent||intent.phase!=="dispatching")throw Error("Known original SDK fork required");const row=this.ctx.storage.sql.exec<{doc:string}>("SELECT doc FROM task_source_inspections WHERE json_extract(doc,'$.scope.eventId')=? AND json_extract(doc,'$.scope.purpose')='workspace' ORDER BY rowid DESC LIMIT 1",intent.eventId).toArray()[0];if(!row)throw Error("Untouched inspection scope missing");const raw=JSON.parse(row.doc) as {scope:unknown;provider:unknown;credentialPossible:boolean;credential:unknown;nativeName:unknown};const scope=taskSourceInspectionScopeSchema.parse(raw.scope);if(scope.projectId!==intent.projectId||scope.incarnation!==intent.incarnation||scope.repositoryName!==intent.workspaceRepoName||raw.provider!==null||raw.credentialPossible||raw.credential!==null||raw.nativeName!==null)throw Error("Legacy premetadata inspection must have no READ/native dispatch");delete scope.protocol;raw.scope=scope;const key=`${scope.eventId}:workspace${scope.attemptId?`:${scope.attemptId}`:""}`;this.ctx.storage.sql.exec("UPDATE task_source_inspections SET doc=? WHERE id=?",JSON.stringify(raw),key);const runId=`unborn-workspace-${scope.attemptId??scope.eventId}`;await admitNativeCompute(this.env,intent.accountKey,runId);const global=this.env.REPOSITORY_CONTROLLER.getByName("global") as unknown as ReadmeCreationHttpFixture;return{runId,reservation:await global.fixtureManagedReservation(runId)};}
 fixtureWorkspaceInspectionRun(taskId:string){const intent=new TaskCreationIntents(this.ctx.storage).forTask(taskId);if(!intent)throw Error("Original task intent missing");const row=this.ctx.storage.sql.exec<{doc:string}>("SELECT doc FROM task_source_inspections WHERE json_extract(doc,'$.scope.eventId')=? AND json_extract(doc,'$.scope.purpose')='workspace' ORDER BY rowid DESC LIMIT 1",intent.eventId).toArray()[0];if(!row)throw Error("Original inspection missing");const value=JSON.parse(row.doc) as {scope:unknown;nativeName:string|null};const scope=taskSourceInspectionScopeSchema.parse(value.scope);return{runId:`unborn-workspace-${scope.attemptId??scope.eventId}`,nativeName:value.nativeName};}

 override async inspectTaskCreationUnborn(...args:Parameters<RepositoryController["inspectTaskCreationUnborn"]>){if(args[1]==="workspace"){const intent=new TaskCreationIntents(this.ctx.storage).get(args[0]);await fetch(this.fixtureBridge,{method:"POST",body:JSON.stringify({kind:"before-workspace-inspection",name:intent?.workspaceRepoName})});}return super.inspectTaskCreationUnborn(...args);}

 override async observeTaskReadyGitHead(...args:Parameters<RepositoryController["observeTaskReadyGitHead"]>){const original=globalThis.fetch;globalThis.fetch=Object.assign(async(input:Parameters<typeof fetch>[0],init?:Parameters<typeof fetch>[1])=>{const url=new URL(input instanceof Request?input.url:String(input));if(!url.hostname.endsWith(".artifacts.cloudflare.net"))return original(input,init);const response=await original(this.fixtureBridge,{method:"POST",body:JSON.stringify({kind:"advertisement",name:url.pathname.split("/")[1]})});if(!response.ok)return response;const value=await response.json() as {advertisement:string};return new Response(value.advertisement,{headers:{"Content-Type":"application/x-git-upload-pack-advertisement"}});},{preconnect:original.preconnect});try{return await super.observeTaskReadyGitHead(...args);}finally{globalThis.fetch=original;}}
async recordActualFixtureCheckpoint(taskId:string,commit:string){const state=await this.getState(),task=state.tasks[taskId];if(!task||task.baseCommit!==null||task.contributor.type!=="human")throw Error("Fixture parent root scope changed");using repo=await this.env.ARTIFACTS.get(task.workspace.repoName);const actual=await repo.readCommit(commit);if(!actual||actual.hash!==commit||(task.currentCommit===null?actual.parents.length!==0:actual.parents[0]!==task.currentCommit))throw Error("Actual fixture root object unavailable");task.currentCommit=commit;task.status="checkpointed";this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));}
constructor(ctx:DurableObjectState,env:Env&FixtureBindings){super(ctx,{...env,...provider(env)} as unknown as Env);this.fixtureBridge=env.NATIVE_FIXTURE;}}
export default{async fetch(request:Request,env:Env&FixtureBindings,ctx:ExecutionContext){if(new URL(request.url).pathname==="/fixture/legacy-spent-inspection"){const value=await request.json() as {projectId:string;taskId:string};return Response.json(await (env.REPOSITORY_CONTROLLER.getByName(`project:${value.projectId}`) as unknown as ReadmeCreationHttpFixture).seedLegacyUntouchedSpentInspection(value.taskId));}if(new URL(request.url).pathname==="/fixture/inspection-run"){const value=await request.json() as {projectId:string;taskId:string;originalRunId:string};const project=env.REPOSITORY_CONTROLLER.getByName(`project:${value.projectId}`) as unknown as ReadmeCreationHttpFixture,global=env.REPOSITORY_CONTROLLER.getByName("global") as unknown as ReadmeCreationHttpFixture,current=await project.fixtureWorkspaceInspectionRun(value.taskId);return Response.json({current,original:await global.fixtureManagedReservation(value.originalRunId),successor:await global.fixtureManagedReservation(current.runId)});}if(new URL(request.url).pathname==="/fixture/checkpoint"){const value=await request.json() as {projectId:string;taskId:string;commit:string};await (env.REPOSITORY_CONTROLLER.getByName(`project:${value.projectId}`) as unknown as ReadmeCreationHttpFixture).recordActualFixtureCheckpoint(value.taskId,value.commit);return new Response("ok");}if(new URL(request.url).pathname==="/fixture/seed"){const account=env.REPOSITORY_CONTROLLER.getByName(`account:${await accountKeyFor("owner")}`) as unknown as ReadmeCreationHttpFixture;await account.setProfile({handle:"owner",displayName:"Human Owner",bio:"",joinedAt:"now"});return new Response("ok");}return worker.fetch(request,{...env,...provider(env),API_LIMITER:{limit:async()=>({success:true})},LOOKUP_LIMITER:{limit:async()=>({success:true})},CLERK_ISSUER:env.FIXTURE_ISSUER,CLERK_AUTHORIZED_PARTIES:"https://fixture.example"} as unknown as Env,ctx);}};
