import {RetainedInputs} from '../../src/server/retained-inputs';
import {VERIFIER_IDENTITIES} from '../../src/core/verification-identities';
import type {Task,VerificationEvidence} from '../../src/core/types';
import {RepositoryController} from '../../src/server/durable-object';
import {accountKeyFor,accountOf,projectOf} from '../../src/server/projects';
import type {Env} from '../../src/server/env';
import type {RepositoryCreationRequest} from '../../src/server/repository-creation-request';
export class RepositoryInitializationFixture extends RepositoryController{
 constructor(ctx:DurableObjectState,env:Env){super(ctx,env);env.INTEGRATOR={getByName:()=>({lifetimeStatus:async()=>({state:'stopped',sealed:true})})} as unknown as Env['INTEGRATOR'];}
 async firstRoot(){const state=await this.getState(),stamp=new Date().toISOString(),task:Task={id:'task-first-root',goal:'First human contribution',contributor:{id:'owner',name:'Owner',type:'human'},baseCommit:null,currentCommit:null,allowedScope:['*'],status:'checkpointed',requirements:[],workspace:{repoName:'workspace-first',remote:'https://fixture.invalid',branch:'task/first'},checkpoints:[],createdAt:stamp,updatedAt:stamp};const created=await this.createTask(task,'owner',{goal:task.goal,dependsOn:null,issue:null},{acceptedTargetRef:`refs/heads/${state.defaultBranch}`});const context=await this.repositoryReadContext('owner',task.id);await this.ingestMemberCheckpoint({eventId:'first-checkpoint',taskId:task.id,commit:'d'.repeat(40),ready:true},'owner',context,undefined,Date.now()+60000);await this.registerWorkflow('first-root-workflow','integration',undefined,'owner',1);const landing=await this.claimLanding({holder:'first-root-workflow',taskIds:[task.id],preservationProtocolVersion:1});if(!('candidate'in landing)||!landing.candidate)throw Error(JSON.stringify(landing));const candidate=landing.candidate,evidence:VerificationEvidence={id:'first-root-evidence',candidateCommit:'d'.repeat(40),candidateTree:'e'.repeat(40),expectedAcceptedBase:null,requirementsVersion:1,policy:state.verificationPolicy,testBundleDigest:'git-integrity',toolchainDigest:'native-git',builtOutputDigest:'first-root-output',verifierIdentity:VERIFIER_IDENTITIES['git-integrity'],testResults:[],timestamp:stamp,status:'passed',acceptedTarget:created.acceptedTarget};await this.recordVerification(candidate.id,evidence.candidateCommit,evidence);const input=await this.prepareRetainedInput(task.id,'first-root-workflow',candidate.id,crypto.randomUUID());new RetainedInputs(this.ctx.storage).record(input,{commit:evidence.candidateCommit,base:null,rootCommit:evidence.candidateCommit,rootAncestryVerified:true});await this.awaitReview(candidate.id,evidence.candidateCommit,'first-root-workflow');const before=await this.preparePublish(candidate.id);const reviewed=await this.recordReview(candidate.id,{approved:true,actor:{userId:'owner',displayName:'Owner',viaToken:false}},evidence.candidateCommit,undefined,{ref:created.acceptedTarget!.ref,acceptedCommit:null,acceptedVersion:0});if(!reviewed.ok)throw Error(reviewed.error);const prepared=await this.preparePublish(candidate.id);if(!prepared.ok||!prepared.journal)throw Error(prepared.error??"Prepared journal missing");await this.completePublish(prepared.journal.id);return{before,prepared,state:await this.getState(),registry:await this.acceptedBranchRegistrySnapshot()};}
 async fault(on:boolean){this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS repository_initialization_receipts(event_id TEXT PRIMARY KEY,payload TEXT NOT NULL)");if(on)this.ctx.storage.sql.exec("CREATE TRIGGER reject_initialized_receipt BEFORE INSERT ON repository_initialization_receipts BEGIN SELECT RAISE(ABORT,'synthetic initialized receipt failure'); END");else this.ctx.storage.sql.exec('DROP TRIGGER IF EXISTS reject_initialized_receipt');}
 async raw(){return{projects:this.ctx.storage.sql.exec('SELECT id FROM project').toArray().length,members:this.ctx.storage.sql.exec('SELECT user_id FROM members').toArray().length,receipts:this.ctx.storage.sql.exec("SELECT name FROM sqlite_master WHERE type='table' AND name='repository_initialization_receipts'").toArray().length?this.ctx.storage.sql.exec('SELECT event_id FROM repository_initialization_receipts').toArray().length:0};}
}
export default{async fetch(request:Request,env:Env){const url=new URL(request.url),actor='owner',account=accountOf(env,await accountKeyFor(actor)),credential={viaToken:false,sessionExpiresAt:Date.now()+(url.searchParams.get('expired')==='true'?-1000:60000)};try{
 if(url.pathname==='/statuses')return Response.json(await account.repositoryInitializationStatuses(url.searchParams.get('actor')??actor,credential,{limit:1,cursor:url.searchParams.get('cursor')??undefined}));
 if(url.pathname==='/status')return Response.json(await account.repositoryInitializationStatusByRequest(url.searchParams.get('request')!,url.searchParams.get('actor')??actor,credential));
 if(url.pathname==='/prepare')return Response.json(await account.prepareRepositoryInitialization(await request.json() as RepositoryCreationRequest,actor,credential));
 const event=url.searchParams.get('event')!,record=await account.repositoryInitializationRecord(event,actor,{viaToken:false,sessionExpiresAt:Date.now()+60000});if(!record)throw Error('Saved initialization unavailable');const project=projectOf(env,record.scope.projectId) as unknown as RepositoryInitializationFixture;
 if(url.pathname==='/first-root')return Response.json(await project.firstRoot());
 if(url.pathname==='/facts'){await account.beginRepositoryInitializationCreate(event,actor,credential);await account.recordRepositoryCreated(event,{id:'provider-init',name:record.scope.canonicalRepoName,remote:`https://${'a'.repeat(32)}.artifacts.cloudflare.net/repo`},'synthetic-canonical-token');if(record.scope.initialization==="empty")await account.confirmRepositoryInitializationCredentialRevoked(event);await account.beginRepositoryInitializationNative(event,`${record.scope.initialization==="empty"?"empty":"readme"}-${event}`,actor,credential);if(record.scope.initialization==="empty"){await account.beginRepositoryInitializationReadCredential(event,actor,credential);await account.recordRepositoryInitializationReadCredential(event,"synthetic-empty-read",Date.now()+60000,"read");await account.confirmRepositoryInitializationEmpty(event,{repositoryId:"provider-init",canonicalRepoName:record.scope.canonicalRepoName,defaultRef:`refs/heads/${record.scope.defaultBranch}`,refs:[],symbolicHead:`refs/heads/${record.scope.defaultBranch}`});await account.confirmRepositoryInitializationReadCredentialRevoked(event,"synthetic-empty-read");await account.confirmRepositoryInitializationStopped(event);await account.confirmRepositoryInitializationCredentialRevoked(event);return Response.json(await account.completeRepositoryInitialization(event,actor,credential));}const commit={head:'a'.repeat(40),tree:'b'.repeat(40),defaultBranch:record.scope.defaultBranch};await account.recordRepositoryInitializationCommit(event,commit);await account.markRepositoryInitializationPushPossible(event,actor,credential);await account.confirmRepositoryInitializationPublished(event,commit);await account.confirmRepositoryInitializationStopped(event);await account.confirmRepositoryInitializationCredentialRevoked(event);return Response.json(await account.completeRepositoryInitialization(event,actor,credential));}
 if(url.pathname==='/fault'){await project.fault(url.searchParams.get('on')==='true');return Response.json({armed:true});}
 if(url.pathname==='/bootstrap')return Response.json(await project.initializeRepositoryReceipt(record,credential));
 if(url.pathname==='/raw')return Response.json(await project.raw());
 if(url.pathname==='/register'){await account.registerInitializedRepository(event,actor,credential);return Response.json(await account.listProjects());}
 return new Response('Missing fixture',{status:404});
 }catch(error){return Response.json({error:error instanceof Error?error.message:'Fixture failure'},{status:409});}}};
