import worker from "../../src/server/worker";
import {RepositoryController} from "../../src/server/durable-object";
import {accountKeyFor} from "../../src/server/projects";
import {CoreGitOperationLedger} from "../../src/server/core-git-budget";
import type {CandidateGeneration,Task} from "../../src/core/types";
import type {Env} from "../../src/server/env";
const projectId="p123456789abc", hash="a".repeat(40), tree="b".repeat(40), blob="c".repeat(40);
let finalRace="";
export class RepositoryReadFixture extends RepositoryController {
 override async repositoryReadContext(...args:Parameters<RepositoryController["repositoryReadContext"]>){const context=await super.repositoryReadContext(...args);if(mode==="frozen-old-context"&&args[2])delete context.candidateInputCommit;return context;}
 async armFinalRace(value:string){await this.ctx.storage.put("finalRace",value);}
 override async accountLifecycle(){const value=await this.ctx.storage.get<string>("finalRace");if(value){await this.ctx.storage.delete("finalRace");if(value==="expiry")await new Promise(resolve=>setTimeout(resolve,2200));else if(value==="token")this.revokeFixtureToken();else await (this.env.REPOSITORY_CONTROLLER as unknown as DurableObjectNamespace<RepositoryReadFixture>).getByName(`project:${projectId}`).mutate("membership");}return super.accountLifecycle();}
 override async ingestMemberCheckpoint(...args:Parameters<RepositoryController["ingestMemberCheckpoint"]>){if(finalRace){const value=finalRace;finalRace="";await (this.env.REPOSITORY_CONTROLLER as unknown as DurableObjectNamespace<RepositoryReadFixture>).getByName(`account:${await accountKeyFor("owner")}`).armFinalRace(value);}return super.ingestMemberCheckpoint(...args);}
 async restoreToken(accountKey:string){if(this.ctx.storage.sql.exec<{n:number}>("SELECT COUNT(*) AS n FROM api_tokens").one().n===0)await this.createApiToken("owner","Synthetic read fixture",`fgt_${accountKey}_${"x".repeat(32)}`,{scope:"full"});}
 async seed(){this.ctx.storage.sql.exec("INSERT INTO project VALUES(1,?)",JSON.stringify({projectId,projectName:"Synthetic read fixture",canonicalRepoName:"synthetic",acceptedBaseline:{commit:hash,tree,acceptedAt:"2026-10-03"},acceptedState:{currentCommit:hash,history:[]},journal:[],tasks:{},candidates:{},verificationPolicy:{}}));await this.addMember("owner","owner");await this.addMember("member","member");this.ctx.storage.sql.exec("CREATE TABLE repository_visibility(id INTEGER PRIMARY KEY,visibility TEXT,version INTEGER,confirmed_by TEXT)");this.ctx.storage.sql.exec("INSERT INTO repository_visibility VALUES(1,'public',1,'owner')");const task:Task={id:"working",goal:"Synthetic pushed work",contributor:{id:"member",name:"Member",type:"human"},baseCommit:hash,currentCommit:hash,allowedScope:[],status:"working",requirements:[],workspace:{repoName:"synthetic-workspace",remote:"https://private.invalid",branch:"task/working"},checkpoints:[],createdAt:"2026-10-03",updatedAt:"2026-10-03"};await this.createTask(task,"member",{goal:task.goal,dependsOn:null,issue:null});}
 setFunding(accountKey:string,allowed:boolean){new CoreGitOperationLedger(this.ctx.storage);this.ctx.storage.sql.exec("DELETE FROM core_git_operations");if(!allowed)this.ctx.storage.sql.exec("INSERT INTO core_git_operations VALUES(?,?,?,?,?)","fixture-exhausted",accountKey,new Date().toISOString().slice(0,7),100000000,"read");}
 async frozenInput(recorded:boolean){const state=await this.getState();state.tasks.frozen={...state.tasks.working!,id:"frozen",currentCommit:"d".repeat(40),status:"accepted",workspace:{...state.tasks.working!.workspace,repoName:"synthetic-retained-input"}};state.acceptedState.currentCommit="9".repeat(40);const candidate:CandidateGeneration={id:"candidate-frozen",attemptNumber:1,participatingTaskIds:["frozen"],participatingCommits:{frozen:"e".repeat(40)},expectedAcceptedBase:"9".repeat(40),frozenPolicyVersion:1,frozenVerificationPolicy:{},frozenRequirements:[],repairAttempts:[],status:"accepted",candidateCommit:"9".repeat(40),createdAt:"2026-10-03",updatedAt:"2026-10-03",...(recorded?{frozenContributorProofs:[{id:"frozen",commit:"e".repeat(40),baseCommit:hash,ref:"refs/flaregit/tasks/frozen",allowedScope:[]}]}:{})};state.candidates["candidate-frozen"]=candidate;this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));}
 async taskSnapshot(){const task=(await this.getState()).tasks.working!;return {currentCommit:task.currentCommit,status:task.status,checkpoints:task.checkpoints};}
 readReservations(){return this.ctx.storage.sql.exec<{account_key:string;category:string}>("SELECT account_key,category FROM core_git_operations").toArray();}
 async reset(){this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS repository_deletion(id INTEGER PRIMARY KEY)");this.ctx.storage.sql.exec("DELETE FROM repository_deletion");await this.addMember("member","member");this.ctx.storage.sql.exec("UPDATE repository_visibility SET visibility='public',version=1");const state=await this.getState();state.acceptedState.currentCommit=hash;this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS repository_deletion(id INTEGER PRIMARY KEY)");this.ctx.storage.sql.exec("DELETE FROM repository_deletion");}
 resetAccount(){this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS account_lifecycle(id INTEGER PRIMARY KEY,status TEXT NOT NULL)");this.ctx.storage.sql.exec("DELETE FROM account_lifecycle");}
 revokeFixtureToken(){this.ctx.storage.sql.exec("DELETE FROM api_tokens");}
 async mutate(mode:string){if(mode==="input-map"||mode==="input-base"){const state=await this.getState();const candidate=state.candidates["candidate-frozen"]!;if(mode==="input-map")candidate.participatingCommits.frozen="8".repeat(40);else candidate.frozenContributorProofs![0]!.baseCommit="7".repeat(40);this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));}if(mode==="membership")this.ctx.storage.sql.exec("DELETE FROM members WHERE user_id='member'");if(mode==="visibility")this.ctx.storage.sql.exec("UPDATE repository_visibility SET visibility='private',version=2");if(mode==="head"){const state=await this.getState();state.acceptedState.currentCommit="d".repeat(40);this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));await this.getState();}}
}
interface FixtureEnv{TEST:DurableObjectNamespace<RepositoryReadFixture>;FIXTURE_ISSUER:string}
let gets=0,reads=0,mode="",race="",funded=true;let refs:string[]=[];let repoNames:string[]=[];let commitReads:string[]=[];
export default {async fetch(request:Request,env:FixtureEnv,ctx:ExecutionContext){
 const url=new URL(request.url),project=env.TEST.getByName(`project:${projectId}`),key=await accountKeyFor("owner");
 if(url.pathname==="/fixture/bootstrap"){await project.seed();const token=`fgt_${key}_${"x".repeat(32)}`;await env.TEST.getByName(`account:${key}`).createApiToken("owner","Synthetic read fixture",token,{scope:"full"});return Response.json({token});}
 if(url.pathname==="/fixture/config"){await project.reset();await env.TEST.getByName(`account:${key}`).resetAccount();await env.TEST.getByName(`account:${key}`).restoreToken(key);finalRace=url.searchParams.get("finalRace")??"";mode=url.searchParams.get("mode")??"";race=url.searchParams.get("race")??"";funded=url.searchParams.get("funded")!=="false";await env.TEST.getByName("global").setFunding(key,funded);gets=0;reads=0;refs=[];repoNames=[];commitReads=[];if(mode.startsWith("frozen"))await project.frozenInput(!mode.includes("legacy"));return new Response("ok");}
 if(url.pathname==="/fixture/task")return Response.json(await project.taskSnapshot());
 if(url.pathname==="/fixture/counts")return Response.json({gets,reads,refs,repoNames,commitReads,reservations:await env.TEST.getByName("global").readReservations()});
 const afterRead=async()=>{reads++;if(mode==="expiry"&&reads===1)await new Promise(resolve=>setTimeout(resolve,2100));if(race){const next=race;race="";if(next==="repository")await project.beginRepositoryDeletion();else if(next==="account")await env.TEST.getByName(`account:${key}`).beginAccountDeletion();else if(next==="token")await env.TEST.getByName(`account:${key}`).revokeFixtureToken();else await project.mutate(next);}if(mode==="unavailable")throw new Error("Synthetic provider unavailable");};
 const commit={hash,treeHash:tree,message:"Synthetic commit",author:{name:"Fixture",email:"fixture@example.test"},parents:[],committedAt:1};
 const repo={async log(options:{ref?:string}){if(options.ref)refs.push(options.ref);await afterRead();return[mode.startsWith("ready")?{...commit,hash:"e".repeat(40),treeHash:"f".repeat(40)}:commit];},async readCommit(requested:string){commitReads.push(requested);await afterRead();if(mode.startsWith("frozen")){if(requested==="e".repeat(40))return mode==="frozen-missing"?null:{...commit,hash:requested,treeHash:"f".repeat(40),parents:["7".repeat(40)]};if(requested==="7".repeat(40))return {...commit,hash:requested,treeHash:"6".repeat(40)};return commit;}if(mode==="ready-base-unavailable"&&requested===hash)return null;return mode.startsWith("ready")&&requested==="e".repeat(40)?{...commit,hash:requested,treeHash:"f".repeat(40)}:commit;},async readTree(requested:string){await afterRead();if(mode.startsWith("frozen")&&requested===tree)return[];if(mode.startsWith("ready")&&requested===tree)return[];return mode==="metadata"?Array.from({length:10000},(_,index)=>({name:`${"x".repeat(500)}-${index}`,type:"blob",hash:blob,mode:"100644"})):(mode.startsWith("diff")||mode.startsWith("ready"))?Array.from({length:mode==="diff5000"||mode==="ready5000"?5000:5001},(_,index)=>({name:`file-${index}.txt`,type:"blob",hash:blob,mode:"100644"})):[{name:"readme.md",type:"blob",hash:blob,mode:"100644"}];},async readBlob(){await afterRead();return new Blob([mode==="oversize"?new Uint8Array(5*1024*1024):"synthetic private contents"]);},[Symbol.dispose]() {}};
 const deny=()=>{throw new Error("Synthetic read fixture forbids provider writes");};
 return worker.fetch(request,{REPOSITORY_CONTROLLER:env.TEST,API_LIMITER:{limit:async()=>({success:true})},LOOKUP_LIMITER:{limit:async()=>({success:true})},CLERK_ISSUER:env.FIXTURE_ISSUER,CLERK_AUTHORIZED_PARTIES:"https://fixture.example",REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:funded?"100000000":"0",REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:funded?"100000000":"0",CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:funded?"100000000":"0",CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:funded?"100000000":"0",INTEGRATOR:{getByName:deny},ARTIFACTS:{get:async(name:string)=>{gets++;repoNames.push(name);return repo;}},EVIDENCE_BUCKET:{put:deny,createMultipartUpload:deny}} as unknown as Env,ctx);
}};
