import{DurableObject}from'cloudflare:workers';import{AgentSandbox,AGENT_CA_PROBE}from'../../src/server/integrator';import type{Env}from'../../src/server/env';import type{AgentNativeAttemptIdentity}from'../../src/server/agent-runtime-ledger';import type{AgentExecutionEgressScope}from'../../src/server/agent-execution-egress';import type{AgentEgressWorkerProps}from'../../src/server/agent-egress-worker';
const image='registry.cloudflare.com/'+'a'.repeat(32)+'/restricted-agent@sha256:'+'b'.repeat(64);
export class RelayRootFixture extends DurableObject{async sealAgentRelay(){await this.ctx.storage.put('sealed',true);}async agentRelayCleanupStatus(){return {credentialsComplete:await this.ctx.storage.get('unclean')!==true};}async unclean(){await this.ctx.storage.put('unclean',true);}}
export class RestrictedAgentFixture extends AgentSandbox{
 private running=false;private active=true;private ca=0;private trace:string[]=[];
 protected override nativeContainer():Container{return this.fake();}
 private fake(){const self=this;return{get running(){return self.running},start(options:ContainerStartupOptions){self.trace.push('start:'+String(options.enableInternet));if(options.enableInternet!==false||options.image!==image)throw Error('Unsafe synthetic start');self.running=true;},inspect:async()=>self.running?{image,labels:{}}:null,exec:async(argv:string[],options?:ContainerExecOptions)=>{const isProbe=argv[0]==='/bin/sh';if(isProbe&&JSON.stringify(argv)!==JSON.stringify(AGENT_CA_PROBE))throw Error('Unexpected CA probe');self.trace.push(isProbe?'ca-probe':'app-exec');if(!isProbe&&options?.env?.GIT_SSL_CAINFO!=='/etc/cloudflare/certs/cloudflare-containers-ca.crt')throw Error('CA configuration missing');const code=isProbe?self.ca:0;return{exitCode:Promise.resolve(code),output:async()=>({exitCode:code,stdout:new Uint8Array(),stderr:new Uint8Array()})} as unknown as ExecProcess;},destroy:async()=>{self.trace.push('destroy');self.running=false;},interceptAllOutboundHttp:async()=>{self.trace.push('http')},interceptOutboundHttps:async(host:string)=>{if(host!=='*')throw Error('Wrong TLS intercept');self.trace.push('https');}} as unknown as Container;}
 protected override restrictedLoopback(_props:AgentEgressWorkerProps):Fetcher{return {} as Fetcher;}
 protected override async restrictedCurrent(props:AgentEgressWorkerProps){if(props.scope.expectedTip!==(props.scope.access==='read'?'a'.repeat(40):null))throw Error('Synthetic recorded tip differs');return {...props.scope,actorActive:this.active,accountActive:true,taskActive:true};}
 async probe(attempt:AgentNativeAttemptIdentity,scope:AgentExecutionEgressScope,mode:string){this.running=mode==='legacy';this.ca=mode==='missing-ca'||mode==='interrupted-cleanup'?1:0;let configured=false,refused=false,credentialsRevoked: boolean|undefined;
 try{configured=(await this.configureRestrictedAgent(attempt,scope)).configured;if(mode==='withdraw')this.active=false;if(mode==='disable')this.env.AGENT_RESTRICTED_EGRESS_ENABLED=undefined;if(mode==='promote'||mode==='wrong-tip'){await this.configureRestrictedAgent(attempt,{...scope,access:'write',expectedTip:mode==='wrong-tip'?'b'.repeat(40):null});}if(mode==='wrong-identity'){await this.configureRestrictedAgent({...attempt,generation:2},{...scope,access:'write',expectedTip:null});}await this.exec(['/usr/bin/true']);if(mode==='cleanup'||mode==='cleanup-changed'){if(mode==='cleanup-changed'){this.env.AGENT_RESTRICTED_EGRESS_ENABLED=undefined;this.env.ISOLATED_AGENT_IMAGE=undefined;}credentialsRevoked=(await this.cleanupRestrictedAgent(attempt)).credentialsRevoked;}}catch{refused=true;if(mode==='interrupted-cleanup')credentialsRevoked=(await this.cleanupRestrictedAgent(attempt)).credentialsRevoked;}return{configured,refused,trace:this.trace,credentialsRevoked,provider:'synthetic'};}
 constructor(ctx:DurableObjectState,env:Env){super(ctx,{...env});}
}
export default{async fetch(request:Request,env:Omit<Env,'AGENT'|'REPOSITORY_CONTROLLER'>&{AGENT:DurableObjectNamespace<RestrictedAgentFixture>;REPOSITORY_CONTROLLER:DurableObjectNamespace<RelayRootFixture>}){const input=await request.json() as {mode:string};const nativeId=crypto.randomUUID(),attempt:AgentNativeAttemptIdentity={attemptId:crypto.randomUUID(),nativeId,projectId:'p123456789abc',incarnation:crypto.randomUUID(),workflowId:'workflow',runId:'run',taskId:'task-one',actorId:'owner',accountKey:'account_a',phase:'apply',generation:1,snapshotDigest:'c'.repeat(64)},scope:AgentExecutionEgressScope={projectId:attempt.projectId,incarnation:attempt.incarnation,workflowId:attempt.workflowId,runId:attempt.runId,taskId:attempt.taskId,actorId:attempt.actorId,accountKey:attempt.accountKey,canonicalRepoName:'canonical',forkRepoName:'fork',remote:'https://'+'a'.repeat(32)+'.artifacts.cloudflare.net/namespace/fork.git',branch:'task/task-one',branchGeneration:1,expectedTip:'a'.repeat(40),access:'read'};return Response.json(await env.AGENT.get(env.AGENT.idFromName('agent-'+nativeId)).probe(attempt,scope,input.mode));}};
