import {RepositoryController} from "../../src/server/durable-object";
import type {Env} from "../../src/server/env";
import type {Task} from "../../src/core/types";
import {RefReadCredentialIncidents} from "../../src/server/ref-read-credential-incidents";
const commit="a".repeat(40),head="b".repeat(40),projectId="p123456789abc";
let revocations=0,issuances=0;
export class TaskReadyFixture extends RepositoryController{
 async seed(){this.ctx.storage.sql.exec("INSERT INTO project VALUES(1,?)",JSON.stringify({projectId,projectName:"Synthetic task read",canonicalRepoName:"synthetic",acceptedState:{currentCommit:commit,history:[]},journal:[],tasks:{},candidates:{},verificationPolicy:{}}));await this.addMember("owner","owner");await this.addMember("member","member");this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS private_recovery_incarnation(id INTEGER PRIMARY KEY,value TEXT NOT NULL)");this.ctx.storage.sql.exec("INSERT INTO private_recovery_incarnation VALUES(1,'11111111-1111-4111-8111-111111111111')");const task:Task={id:"working",goal:"Synthetic",contributor:{id:"member",name:"Member",type:"human"},baseCommit:commit,currentCommit:commit,allowedScope:[],status:"checkpointed",requirements:[],workspace:{repoName:"synthetic-workspace",remote:"https://private.invalid",branch:"task/working"},checkpoints:[],createdAt:"now",updatedAt:"now"};await this.createTask(task,"member",{goal:task.goal,dependsOn:null,issue:null});}
 async inspect(mode:string){issuances=revocations=0;const repo={info:async()=>({remote:`https://${"1".repeat(32)}.artifacts.cloudflare.net/repo.git`}),createToken:async()=>{issuances++;if(mode==="issuance")throw new Error("synthetic secret failure");if(mode==="revoked")this.ctx.storage.sql.exec("DELETE FROM members WHERE user_id='member'");return{scope:"read",plaintext:"synthetic-read-only",expiresAt:new Date(Date.now()+60000).toISOString()};},revokeToken:async()=>{revocations++;return mode!=="cleanup";},[Symbol.dispose]() {}};
 Object.assign(this.env,{ARTIFACTS:{get:async()=>repo},CORE_GIT_ACCOUNT_MONTHLY_USD_MICROS:mode==="budget"?"0":"100000000",CORE_GIT_GLOBAL_MONTHLY_USD_MICROS:"100000000",REPOSITORY_READ_ACCOUNT_MONTHLY_USD_MICROS:"1000000",REPOSITORY_READ_GLOBAL_MONTHLY_USD_MICROS:"1000000"});
 globalThis.fetch=Object.assign(async()=>{const packet=(s:string)=>(s.length+4).toString(16).padStart(4,"0")+s;const ref=mode==="wrong-ref"?"refs/tags/task/working":"refs/heads/task/working";return new Response(packet("# service=git-upload-pack\n")+"0000"+packet(`${head} ${ref}\0multi_ack\n`)+"0000",{headers:{"Content-Type":"application/x-git-upload-pack-advertisement"}});},{preconnect:globalThis.fetch.preconnect});
 const context=await this.repositoryReadContext("member","working");if(mode==="contributor"){const state=await this.getState();state.tasks.working!.contributor.id="other";this.ctx.storage.sql.exec("UPDATE project SET doc=? WHERE id=1",JSON.stringify(state));await this.getState();}let observed:string|null=null,error=false;try{observed=await this.observeTaskReadyGitHead("working","member",context,undefined,mode==="expired"?Date.now()-1:Date.now()+60000,mode==="changed-head"?commit:undefined);}catch{error=true;}
 const incidents=new RefReadCredentialIncidents(this.ctx.storage);const rows=this.ctx.storage.sql.exec<{id:string}>("SELECT id FROM ref_read_credential_incidents").toArray();return{observed,error,issuances,revocations,statuses:rows.map(row=>incidents.summary(row.id)?.status),task:(await this.getState()).tasks.working!.currentCommit};}
}
export default{async fetch(request:Request,env:Env){const mode=new URL(request.url).searchParams.get("mode")!;const repo=env.REPOSITORY_CONTROLLER.getByName(`project:${mode}`) as unknown as TaskReadyFixture;await repo.seed();return Response.json(await repo.inspect(mode));}};
