import {ProductDecisionFixture} from './product-decision-native-worker';
import type {Task} from '../../src/core/types';
import type {Env} from '../../src/server/env';
const initialRepositories=new Map<string,{id:string;description:string}>();
export class TaskTargetGenerationFixture extends ProductDecisionFixture{
 constructor(ctx:DurableObjectState,env:Env){super(ctx,env);env.ARTIFACTS={get:async(name:string)=>({info:async()=>({id:initialRepositories.get(name)?.id,name,description:initialRepositories.get(name)?.description}),revokeToken:async(token:string)=>token==='synthetic-generation-initial-token',[Symbol.dispose]:()=>{}})} as unknown as Artifacts;}
 override async fetch(request:Request){const url=new URL(request.url);try{
  if(url.pathname==='/legacy-target-task'){const source=new URL(request.url);source.pathname='/target-task';return super.fetch(new Request(source,request));}
  if(url.pathname==='/target-task'){const input=await request.json() as {id:string;ref:string};const row=(await this.contributionTargets('owner')).targets.find(target=>target.ref===input.ref);if(!row)throw Error('Ready target unavailable');const body={goal:'Frozen target contribution',dependsOn:null,issue:null,expectedTarget:{ref:row.ref,acceptedCommit:row.acceptedCommit,acceptedVersion:row.acceptedVersion,policyVersion:row.policyVersion}},credential={viaToken:false,sessionExpiresAt:Date.now()+60000};const intent=await this.prepareTaskCreationIntent(input.id,'owner',body,credential);await this.beginTaskCreationFork(intent.eventId,'owner',credential);const description=`FlareGit creation ${intent.eventId}/${intent.allocationId}`,providerRepoId=`provider-${input.id}`;initialRepositories.set(intent.workspaceRepoName,{id:providerRepoId,description});await this.recordTaskCreationForkAcknowledgement(intent.eventId,{providerRepoId,name:intent.workspaceRepoName,description},'synthetic-generation-initial-token');if(!await this.revokeTaskCreationForkToken(intent.eventId))throw Error('Exact initial credential revocation unavailable');await this.confirmTaskCreationFork(intent.eventId,{allocationId:intent.allocationId,workspaceRepoName:intent.workspaceRepoName,sourceRepoName:intent.selection.sourceRepoName,sourceCommit:intent.selection.baseCommit,providerRepoId,nativeState:'not_allocated',credentialsComplete:true},'owner',credential);const task:Task={id:input.id,goal:body.goal,contributor:{id:'owner',name:'Owner',type:'human'},baseCommit:intent.selection.baseCommit,currentCommit:intent.selection.baseCommit,status:'working',allowedScope:['src/'],requirements:[],workspace:{repoName:intent.workspaceRepoName,remote:'https://fixture.invalid',branch:`task/${input.id}`},checkpoints:[],createdAt:'2026-10-04',updatedAt:'2026-10-04'};await this.commitTaskCreationIntent(intent.eventId,task,'owner',credential);if(!task.currentCommit)throw Error("Committed target generation fixture requires an actual checkpoint");await this.ingestCheckpoint({eventId:crypto.randomUUID(),taskId:input.id,commit:task.currentCommit,ready:true});return Response.json((await this.getState()).tasks[input.id]);}
  if(url.pathname==='/agent-generation-proof'){const input=await request.json() as {taskId:string;runId:string};const task=(await this.getState()).tasks[input.taskId]!;await this.registerWorkflow(input.runId,'agent',input.taskId,'owner');const claimed=await this.claimAgentRun({runId:input.runId,taskId:input.taskId,startingCommit:task.currentCommit,startingBranchHead:task.currentCommit,branch:task.workspace.branch,goal:task.goal,context:{comments:[]},allowedScope:task.allowedScope,protectedPaths:[]});const native=await this.beginAgentNativeAttempt({workflowId:input.runId,runId:input.runId,taskId:input.taskId,phase:'proposal',attemptId:crypto.randomUUID(),nativeId:crypto.randomUUID()});const proposed=await this.saveAgentProposal(input.runId,input.taskId,{'src/new.ts':'export const refreshed = true;'}),pushed=await this.markAgentPushed(input.runId,input.taskId,'d'.repeat(40));return Response.json({claimed:claimed.kind,target:claimed.run.acceptedTarget,stamp:claimed.run.targetGeneration,native:!!native,proposed,pushed});}
  if(url.pathname==='/begin-gateway'){const input=await request.json() as {id:string;taskId:string};return Response.json(await this.beginGitGatewayAttempt(input.id,input.taskId,true,'owner',null));}
  if(url.pathname==='/settle-gateway'){const input=await request.json() as {id:string};await this.recordGitGatewayCredential(input.id,'synthetic-private-gateway-token',Date.now()+60000,'write');return Response.json(await this.finishGitGatewayAttempt(input.id,{transportFinished:false,credentialRevoked:true}));}
  if(url.pathname==='/prepare-generation'){const input=await request.json() as {taskId:string;eventId:string;expectedGeneration:number};return Response.json(await this.prepareTaskTargetGeneration(input.taskId,input.eventId,input.expectedGeneration,{kind:'policy-refresh'},{userId:'owner',displayName:'Owner',viaToken:false},undefined,Date.now()+60000));}
  if(url.pathname==='/activate-generation')return Response.json(await this.activateTaskTargetGeneration(url.searchParams.get('event')!,{userId:'owner',displayName:'Owner',viaToken:false},undefined,Date.now()+60000));
  if(url.pathname==='/raw-state'){return Response.json(JSON.parse(this.ctx.storage.sql.exec<{doc:string}>('SELECT doc FROM project WHERE id=1').one().doc));}
  if(url.pathname==='/creation-receipts')return Response.json(this.ctx.storage.sql.exec('SELECT task_id,payload FROM task_creation_receipts ORDER BY task_id').toArray());
  return super.fetch(request);
 }catch(error){return Response.json({error:error instanceof Error?error.message:'Fixture failure'},{status:409});}}
}
export default{fetch(request:Request,env:Env){const url=new URL(request.url);return(env.REPOSITORY_CONTROLLER.getByName(url.searchParams.get('name')??'task-generations') as unknown as TaskTargetGenerationFixture).fetch(request);}};
