import worker from "../../src/server/worker";
import {RepositoryController} from "../../src/server/durable-object";
import {PrivateRecoveryOperations} from "../../src/server/private-recovery";
import {AcceptedBranchRoots} from "../../src/server/accepted-branch-roots";
import {accountKeyFor} from "../../src/server/projects";
import type {Env} from "../../src/server/env";
const projectId="p123456789abc",actor="contributor",base="a".repeat(40),names=new Set<string>(["canonical"]),calls:string[]=[],descriptions=new Map<string,string>();let demoteOnFork=false,loseForkAck=false,failCleanup=false;
export class TargetCreationHttpFixture extends RepositoryController{
 constructor(ctx:DurableObjectState,env:Env){super(ctx,{...env,ARTIFACTS:{get:async(name:string)=>({info:async()=>{const value=await this.providerInfo(name);await this.ctx.storage.put("infoRead",value);return value;},revokeToken:async()=>{calls.push("revoke-initial");return !failCleanup;},[Symbol.dispose]() {}})}} as unknown as Env);}
 async providerInfo(name:string){return await this.ctx.storage.get<{id:string;name:string;description:string|null;remote:string}>(`provider:${name}`)??{id:`fixture-${name}`,name,description:null,remote:"https://"+"a".repeat(32)+".artifacts.cloudflare.net/repo.git"};}
 async providerCreated(name:string,description:string){await this.ctx.storage.put(`provider:${name}`,{id:`fixture-${name}`,name,description,remote:"https://"+"a".repeat(32)+".artifacts.cloudflare.net/repo.git"});}
 async armLostReceipts(){await this.ctx.storage.put("lostReceipts",2);}
 override async recordTaskCreationForkToken(eventId:string,token:string){await super.recordTaskCreationForkToken(eventId,token);const remaining=await this.ctx.storage.get<number>("lostReceipts")??0;if(remaining>0){await this.ctx.storage.put("lostReceipts",remaining-1);throw Error("Synthetic lost credential receipt acknowledgement");}}
 async armLostCommit(){await this.ctx.storage.put("lostCommit",true);}
 override async commitTaskCreationIntent(...args:Parameters<RepositoryController["commitTaskCreationIntent"]>){const result=await super.commitTaskCreationIntent(...args);if(await this.ctx.storage.get("lostCommit")){await this.ctx.storage.delete("lostCommit");throw Error("Synthetic lost task commit acknowledgement");}return result;}
 async seed(){await this.initialize({projectId,projectName:"Synthetic target creation",canonicalRepoName:"canonical",head:base,defaultBranch:"main",ownerId:"owner",verificationPolicy:{}});await this.addMember(actor,"member");await this.addMember("other-member","member");const incarnation=new PrivateRecoveryOperations(this.ctx.storage).incarnation(),roots=new AcceptedBranchRoots(this.ctx.storage),state=await this.getState();roots.initializePrimary({projectId,incarnation,canonicalRepoName:"canonical",ref:"refs/heads/main"},{commit:base,requirements:[]},()=>{});roots.createRoot({operationId:crypto.randomUUID(),projectId,incarnation,canonicalRepoName:"canonical",actorId:"owner",accountKey:await accountKeyFor("owner"),branch:"release",sourceCommit:base,acceptedCommit:base,phase:"confirmed",observedCommit:base,createdAt:1},{observedHead:base,sourceCommit:base,acceptedCommit:base,ancestryVerified:true,nativeStopped:true,credentialsRevoked:true},{commit:base,requirements:[]},()=>{});return state.defaultBranch;}
 async advance(){const incarnation=new PrivateRecoveryOperations(this.ctx.storage).incarnation();new AcceptedBranchRoots(this.ctx.storage).publish({projectId,incarnation,canonicalRepoName:"canonical",ref:"refs/heads/release",operationId:crypto.randomUUID(),expectedHead:base,expectedVersion:0,commit:"b".repeat(40),requirementsSnapshot:{commit:"b".repeat(40),requirements:[]}},()=>{});}
 async snapshot(){const tables=this.ctx.storage.sql.exec<{name:string}>("SELECT name FROM sqlite_master WHERE type='table'").toArray().map(row=>row.name);return{tasks:(await this.getState()).tasks,calls,phases:tables.includes("task_creation_intents")?this.ctx.storage.sql.exec("SELECT json_extract(doc,'$.phase') AS phase FROM task_creation_intents").toArray():[],allocationProof:tables.includes("task_creation_intents")&&tables.includes("artifact_allocation_fences")?this.ctx.storage.sql.exec("SELECT json_extract(i.doc,'$.taskId') AS taskId,json_extract(i.doc,'$.phase') AS creationPhase,a.phase AS allocationPhase,a.operation_id=json_extract(i.doc,'$.allocationId') AS exactAllocation FROM task_creation_intents i LEFT JOIN artifact_allocation_fences a ON a.name=json_extract(i.doc,'$.workspaceRepoName')").toArray():[],infoRead:await this.ctx.storage.get("infoRead"),credentialStates:tables.includes("initial_fork_credentials")?this.ctx.storage.sql.exec("SELECT json_extract(i.doc,'$.taskId') AS taskId,c.status,c.attempts FROM initial_fork_credentials c JOIN task_creation_intents i ON c.event_id=i.event_id").toArray():[],tables:tables.filter(name=>/fork|creation|artifact/.test(name))};}
}
export default{async fetch(request:Request,env:Env&{FIXTURE_ISSUER:string},ctx:ExecutionContext){const path=new URL(request.url).pathname,repo=env.REPOSITORY_CONTROLLER.getByName(`project:${projectId}`) as unknown as TargetCreationHttpFixture;if(path==="/fixture/seed"){await repo.seed();const account=env.REPOSITORY_CONTROLLER.getByName(`account:${await accountKeyFor(actor)}`) as unknown as TargetCreationHttpFixture;await account.setProfile({handle:actor,displayName:"Contributor",bio:"",joinedAt:"now"});return Response.json({actor});}if(path==="/fixture/snapshot")return Response.json(await repo.snapshot());if(path==="/fixture/advance"){await repo.advance();return new Response("ok");}if(path==="/fixture/unknown-fork"){loseForkAck=true;return new Response("ok");}if(path==="/fixture/fail-cleanup"){failCleanup=true;return new Response("ok");}if(path==="/fixture/restore-cleanup"){failCleanup=false;return new Response("ok");}if(path==="/fixture/double-lost-receipt"){await repo.armLostReceipts();return new Response("ok");}if(path==="/fixture/lost-commit"){await repo.armLostCommit();return new Response("ok");}if(path==="/fixture/demote-fork"){demoteOnFork=true;return new Response("ok");}const artifacts={list:async()=>({repos:[...names].map(name=>({name}))}),get:async(name:string)=>({info:async()=>({id:`fixture-${name}`,name,description:descriptions.get(name)??null,remote:"https://"+"a".repeat(32)+".artifacts.cloudflare.net/repo.git"}),fork:async(repoName:string,options:{defaultBranchOnly?:boolean;description?:string})=>{calls.push(`fork:${repoName}:${options.defaultBranchOnly}`);if(names.has(repoName))throw Error("Already exists");names.add(repoName);descriptions.set(repoName,options.description??"");await repo.providerCreated(repoName,options.description??"");if(demoteOnFork){demoteOnFork=false;await repo.removeMember(actor);}if(loseForkAck){loseForkAck=false;throw Error("Synthetic missing SDK fork acknowledgement");}return{id:`fixture-${repoName}`,name:repoName,description:options.description??null,remote:"https://"+"a".repeat(32)+".artifacts.cloudflare.net/repo.git",token:"synthetic-fork-token"};},readCommit:async(hash:string)=>({hash}),revokeToken:async()=>{calls.push("revoke-initial");return !failCleanup;},[Symbol.dispose]() {}})};return worker.fetch(request,{...env,ARTIFACTS:artifacts,ARTIFACT_STORAGE_NAMESPACE:"fixture",ARTIFACT_STORAGE_GLOBAL_SLOTS:"32",ARTIFACT_STORAGE_ACCOUNT_SLOTS:"10",API_LIMITER:{limit:async()=>({success:true})},LOOKUP_LIMITER:{limit:async()=>({success:true})},CLERK_ISSUER:env.FIXTURE_ISSUER,CLERK_AUTHORIZED_PARTIES:"https://fixture.example"} as unknown as Env,ctx);}};
