import worker from '../../src/server/worker';
import {RepositoryController} from '../../src/server/durable-object';
import {accountKeyFor,accountOf} from '../../src/server/projects';
import type {Env} from '../../src/server/env';
const id='p123456789abc',calls:string[]=[];let mode='running',status='running',scopeReads=0;let scenarioTokenId='';
export class WorkflowControlFixture extends RepositoryController {
 async prepareBranchForAbandon(operationId:string){return this.prepareBranchCreation({operationId,name:'feature/prepared',sourceCommit:'a'.repeat(40)},{userId:'owner',displayName:'Synthetic owner',viaToken:false},undefined,Date.now()+60000);}
 override async branchNativeRecovery(...args:Parameters<RepositoryController["branchNativeRecovery"]>){const result=await super.branchNativeRecovery(...args);if(mode==='branch-summary-withdraw'){mode='running';await this.addMember('owner','member');}return result;}

 override async conversationMigrationSource(...args:Parameters<RepositoryController["conversationMigrationSource"]>){if(mode==='conversation-funding-denied')return{projectId:id,incarnation:'12345678-1234-1234-1234-123456789abc',ownerId:'owner',accountKey:await accountKeyFor('owner'),sourceUrl:'https://github.com/synthetic/repository'};return super.conversationMigrationSource(...args);}

 override async agentNativeRecoverySummary(...args:Parameters<RepositoryController["agentNativeRecoverySummary"]>){const result=await super.agentNativeRecoverySummary(...args);if(mode==='agent-summary-withdraw'){mode='running';await this.addMember('owner','member');}return result;}

 override async ownerScenarioRuns(...args:Parameters<RepositoryController["ownerScenarioRuns"]>){const report=await super.ownerScenarioRuns(...args);if(mode==='scenario-withdraw'){mode='running';await this.addMember('owner','member');}else if(mode==='scenario-delete'){mode='running';await this.beginRepositoryDeletion();}else if(mode==='scenario-incarnation'){mode='running';this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS private_recovery_incarnation (id INTEGER PRIMARY KEY,value TEXT NOT NULL)");this.ctx.storage.sql.exec("INSERT OR REPLACE INTO private_recovery_incarnation (id,value) VALUES (1,?)",crypto.randomUUID());}else if(mode==='scenario-revoke-token'){mode='running';await accountOf(this.env,await accountKeyFor('owner')).revokeApiToken(scenarioTokenId);}return report;}

 override async logActivity(actor:string,type:string,summary:string,options?:{exceptUser?:string}){const result=await super.logActivity(actor,type,summary,options);if(mode==="revoke-at-audit"&&type==="workflow.pause"){await this.addMember("owner","member");mode="running";}return result;}
 override async assertRepositoryReadContext(...args:Parameters<RepositoryController["assertRepositoryReadContext"]>){if(mode==='public-branch-revoke'){mode='running';await this.setRepositoryVisibility('private',true,'owner');}const allowed=await super.assertRepositoryReadContext(...args);if(mode==="multi-owner-revoke"&&++scopeReads===5){await this.addMember("owner","member");mode="running";}return allowed;}
 async seed(){await this.initialize({projectId:id,projectName:'Synthetic workflow control fixture',canonicalRepoName:'synthetic',head:'a'.repeat(40),verificationPolicy:{},ownerId:'owner'});await this.addMember('initiator','member');await this.addMember('member','member');await this.registerWorkflow('agent-owned','agent',undefined,'initiator');await this.registerWorkflow('integration-owned','integration',undefined,'owner');for(let n=0;n<24;n++)await this.registerWorkflow('scenario-'+n,'scenario',undefined,'owner');await this.addComment({subject:'change:preserved',author:'Owner',body:'Synthetic saved context'});}
 restoreDeletionFence(){this.ctx.storage.sql.exec("DELETE FROM repository_deletion");}
 async issueScenarioToken(token:string,scope:'read'|'write'|'full',repoId?:string){return this.createApiToken('owner','Synthetic scenario token',token,{scope,...(repoId?{repo:repoId}:{})});}
 async issueSyntheticToken(token:string){const issued=await this.createApiToken("owner","Synthetic workflow token",token,{scope:"full"});await this.ctx.storage.put("syntheticTokenId",issued.id);}
 async revokeSyntheticToken(){const id=await this.ctx.storage.get<string>("syntheticTokenId");if(!id)throw Error("Missing synthetic token");await this.revokeApiToken(id);}
 async snapshot(){return {state:await this.getState(),comments:await this.listComments('change:preserved'),activity:await this.listActivity(60)};}
}
interface FixtureEnv{REPOSITORY_CONTROLLER:DurableObjectNamespace<WorkflowControlFixture>;FIXTURE_ISSUER:string}
export default {async fetch(request:Request,env:FixtureEnv,ctx:ExecutionContext){const url=new URL(request.url),repo=env.REPOSITORY_CONTROLLER.getByName('project:'+id);
 if(url.pathname==='/fixture/seed'){await repo.seed();const key=await accountKeyFor('owner'),token='fgt_'+key+'_'+ 'x'.repeat(32);await env.REPOSITORY_CONTROLLER.getByName('account:'+key).issueSyntheticToken(token);return Response.json({token});}
 if(url.pathname==='/fixture/scenario-token'){const key=await accountKeyFor('owner'),token='fgt_'+key+'_'+crypto.randomUUID().replaceAll('-','');const issued=await env.REPOSITORY_CONTROLLER.getByName('account:'+key).issueScenarioToken(token,url.searchParams.get('scope')==='read'?'read':url.searchParams.get('scope')==='write'?'write':'full',url.searchParams.get('repo')??undefined);scenarioTokenId=issued.id;return Response.json({token});}
 if(url.pathname==='/fixture/mode'){mode=url.searchParams.get('mode')??'running';status=mode==='resume-failed'?'paused':['paused','complete'].includes(mode)?mode:'running';calls.length=0;scopeReads=0;if(mode==='multi-owner-revoke')await repo.addMember('aaa-owner','owner');await repo.addMember('owner','owner');await repo.addMember('member','member');return Response.json({ok:true});}
 if(url.pathname==='/fixture/restore-deletion'){await repo.restoreDeletionFence();return Response.json({ok:true});}
 if(url.pathname==='/fixture/prepared-branch')return Response.json(await repo.prepareBranchForAbandon(url.searchParams.get('operationId')!));
 if(url.pathname==='/fixture/visibility'){await repo.setRepositoryVisibility(url.searchParams.get('value')==='public'?'public':'private',true,'owner');return Response.json({ok:true});}
 if(url.pathname==='/fixture/calls')return Response.json(calls);
 if(url.pathname==='/fixture/snapshot')return Response.json(await repo.snapshot());
 const binding={get:async(instance:string)=>{calls.push('get:'+instance);if(mode==='missing')throw Error('Instance does not exist');if(mode==='lookup-failed')throw Error('synthetic secret provider error');return {status:async()=>{calls.push('status:'+instance);if(mode==='revoke-at-status'){await repo.addMember('owner','member');mode='running';}if(mode==='remove-member'){await repo.removeMember('member');mode='running';}if(mode==='revoke-token'){await env.REPOSITORY_CONTROLLER.getByName('account:'+await accountKeyFor('owner')).revokeSyntheticToken();mode='running';}if(mode==='delete-repository'){await repo.beginRepositoryDeletion();mode='running';}if(mode==='delete-account'){await env.REPOSITORY_CONTROLLER.getByName('account:'+await accountKeyFor('owner')).beginAccountDeletion();mode='running';}return {status,output:'synthetic secret output',error:{message:'synthetic secret provider error'}};},pause:async()=>{calls.push('pause:'+instance);if(mode==='pause-failed')throw Error('synthetic secret pause failure');if(mode==='pause-revoke'){await repo.addMember('owner','member');}status=mode==='pending'?'waitingForPause':'paused';},resume:async()=>{calls.push('resume:'+instance);if(mode==='resume-failed')throw Error('synthetic secret resume failure');status='running';}};}};
 return worker.fetch(request,{...env,API_LIMITER:{limit:async()=>({success:true})},CLERK_ISSUER:env.FIXTURE_ISSUER,CLERK_AUTHORIZED_PARTIES:'https://fixture.example',AGENT_WORKFLOW:binding,INTEGRATION_WORKFLOW:binding,SCENARIO_WORKFLOW:binding} as unknown as Env,ctx);
}};
