import {FlareGitIntegrationWorkflow} from '../../src/server/workflow';
import type {WorkflowEvent,WorkflowStep} from 'cloudflare:workers';
import type {IntegrationParams} from '../../src/server/workflow';
import type {CandidateGeneration,FlareGitProjectState,PublicationJournalEntry} from '../../src/core/types';
import type {Env} from '../../src/server/env';
interface FixtureEnv {NATIVE_BRIDGE:string}
interface Payload {candidate:CandidateGeneration;state:FlareGitProjectState;journal:PublicationJournalEntry;commit:string;mode:string}
/** Controlled scheduler/provider boundaries; production Workflow caller and CAS logic run unchanged. */
export default {async fetch(request:Request,env:FixtureEnv,ctx:ExecutionContext){const input=await request.json() as Payload;const state=structuredClone(input.state),journal=structuredClone(input.journal);state.journal=[journal];const calls:string[]=[],activities:string[]=[];
 const stub={admitIntegrationDispatch:async()=>({terminal:false}),recordIntegrationDispatchOutcome:async(_id:string,status:string)=>{calls.push('outcome:'+status);},recordWorkflowOutcome:async()=>{},getState:async()=>state,logActivity:async(_actor:string,type:string)=>{activities.push(type);},awaitReview:async()=>{calls.push("checks-frozen");},candidateAcceptance:async()=>{calls.push("acceptance-decision");return{mode:input.mode==="policy"?"maintainer-policy":"human-review-required"};},abortPublish:async()=>{calls.push('abort');journal.state='ABORTED';},authorizeCandidatePublication:async()=>{calls.push('new-write-authority');return false;},observeCandidatePublicationReadback:async(_candidate:string,_journal:string,commit:string)=>{calls.push('readback:'+input.candidate.acceptedTarget!.ref);const response=await fetch(env.NATIVE_BRIDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:input.candidate.acceptedTarget!.ref,commit,mode:input.mode})});return response.json();},completePublish:async(_id:string,scope?:string)=>{if(scope!=='native-original-ref-proof')throw Error('Readback proof required');calls.push('complete');journal.state='ACCEPTED';},getMirror:async()=>({target:null,enabled:false,hasToken:false,runs:[]})};
 const fakeEnv={...env,REPOSITORY_CONTROLLER:{idFromName:(name:string)=>name,get:()=>stub,getByName:()=>stub},ARTIFACTS:{get:async()=>{calls.push('credential-allocation');throw Error('No write capability may be created');}},INTEGRATOR:{getByName:()=>{calls.push('sandbox-allocation');throw Error('No workspace may be allocated');}}} as unknown as Env;
 const step={do:async(name:string,...args:unknown[])=>{if(name==='claim-landing-0')return{candidate:input.candidate};if(name==='compose-repair-verify')return{ok:true,commit:input.commit,evidenceId:'fixture-evidence',branch:input.candidate.acceptedTarget!.branch};if(name==='prepare-publish')return{ok:true,journal};const callback=args.at(-1) as()=>Promise<unknown>;return callback();},waitForEvent:async()=>{calls.push("human-review-event");return{payload:{approved:true,by:"Original owner"}};}} as unknown as WorkflowStep;
 const workflow=new FlareGitIntegrationWorkflow(ctx as unknown as ConstructorParameters<typeof FlareGitIntegrationWorkflow>[0],fakeEnv);
 const result=await workflow.run({instanceId:'fixture-workflow',payload:{projectId:input.state.projectId,taskIds:input.candidate.participatingTaskIds}} as WorkflowEvent<IntegrationParams>,step);
 return Response.json({result,journalState:journal.state,calls,activities});
}};
