import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, BookOpen, GitBranch, MessageSquare, Search, Users, UserRoundCheck } from "lucide-react";
import { useAuth } from "@clerk/clerk-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiJson } from "../api";
import { appendCommunityItems } from "../community-page-items";
import { ThemeSelector } from "../ThemeProvider";
import { CloudflareBadgeFooter } from "../components/CloudflareBadge";
const link = (workspace: boolean, view = "") => workspace ? `/#/community${view ? `?view=${view}` : ""}` : `/community${view ? `#view=${view}` : ""}`;
type Person = { handle: string; displayName: string; bio: string; version: number; href: string };
type Contribution = { kind: "accepted-contribution"; actor: { handle: string; displayName: string; href: string }; repository: { id: string; name: string; href: string }; commit: string; acceptedAt: string; href: string };
type Page<T> = { items: T[]; nextCursor: string | null; checked: number; incomplete: boolean; scope: string };
type PeoplePage = Omit<Page<Person>, "items"> & { people: Person[] };
async function peopleRead(path: string): Promise<Page<Person>> { const response = await fetch(`/api${path}`, { credentials: "omit", cache: "no-store" }); if (!response.ok) throw new Error("People unavailable"); const value = await response.json() as PeoplePage; return { ...value, items: value.people }; }
export function CommunitySections({ workspace, view }: { workspace: boolean; view: string }) { return <nav className="community-workspace-sections" aria-label="Community sections">{[{ id: "activity", label: "Activity", icon: MessageSquare }, ...(workspace ? [{ id: "following", label: "Following", icon: UserRoundCheck }] : []), { id: "repositories", label: "Repositories", icon: GitBranch }, { id: "people", label: "People", icon: Users }, { id: "help", label: "Help & feedback", icon: BookOpen }].map(item => <a key={item.id} href={link(workspace, item.id === "activity" ? "" : item.id)} aria-current={view === item.id ? "page" : undefined}><item.icon size={16} />{item.label}</a>)}</nav>; }
function usePages<T>(endpoint: string, read: (path: string) => Promise<Page<T>>, identity: (item: T) => string) {
 const [page, setPage] = useState<Page<T> | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [moreBusy, setMoreBusy] = useState(false), [moreError, setMoreError] = useState(""), [revision, setRevision] = useState(0);
 const generation = useRef(0), lock = useRef(false);
 useEffect(() => { const current = ++generation.current; lock.current = false; setPage(null); setLoading(true); setError(""); setMoreError(""); setMoreBusy(false); void read(endpoint).then(value => { if (generation.current === current) setPage({ ...value, items: appendCommunityItems([], value.items, identity) }); }).catch(() => { if (generation.current === current) setError("This view could not be loaded. Refresh to try again."); }).finally(() => { if (generation.current === current) setLoading(false); }); return () => { generation.current++; }; }, [endpoint, read, revision]);
 function more() { if (!page?.nextCursor || lock.current) return; const current = generation.current; lock.current = true; setMoreBusy(true); setMoreError(""); void read(`${endpoint}${endpoint.includes("?") ? "&" : "?"}cursor=${encodeURIComponent(page.nextCursor)}`).then(value => { if (generation.current === current) setPage(previous => previous ? { ...value, incomplete: previous.incomplete || value.incomplete, checked: previous.checked + value.checked, items: appendCommunityItems(previous.items, value.items, identity) } : value); }).catch(() => { if (generation.current === current) setMoreError("More results could not be loaded. Your current view is preserved."); }).finally(() => { if (generation.current === current) { lock.current = false; setMoreBusy(false); } }); }
 return { page, loading, error, moreBusy, moreError, more, refresh: () => { generation.current++; lock.current = false; setPage(null); setLoading(true); setMoreBusy(false); setRevision(value => value + 1); } };
}
function PageTail<T>({ state }: { state: ReturnType<typeof usePages<T>> }) { return <>{state.page && !state.loading && !state.error && <p className="community-scope">{state.page.scope}{state.page.incomplete ? " Some records could not be checked; refresh for a new view." : ""}</p>}{state.moreError && <p role="alert" className="community-error">{state.moreError}</p>}{state.page?.nextCursor && <Button size="sm" variant="outline" disabled={state.moreBusy} onClick={state.more}>{state.moreBusy ? "Loading more…" : state.moreError ? "Retry this page" : "Load more"}</Button>}</>; }
function CommunityFrame({ workspace, view, title, description, onSignIn, children }: { workspace: boolean; view: string; title: string; description: string; onSignIn?: () => void; children: React.ReactNode }) { useEffect(() => { document.title = `${view === "following" ? "Following" : "People"} · Community · FlareGit`; }, [view]); const Content = workspace ? "section" : "main"; return <div className={`repository-community community-social-home ${workspace ? "community-workspace" : ""}`}>{!workspace && <a href="#repository-community-main" onClick={event => { event.preventDefault(); document.getElementById("repository-community-main")?.focus(); }} className="community-skip">Skip to content</a>}{!workspace && <header><a href="/" className="community-brand"><GitBranch size={21} /><strong>FLAREGIT</strong></a><nav><a href="/community">Community</a><a href="/docs">Docs</a></nav><div><ThemeSelector compact /><Button size="sm" variant="outline" onClick={onSignIn ?? (() => window.location.assign("/#/community?view=people&signin=1"))}>Sign in</Button></div></header>}<Content id="repository-community-main" tabIndex={-1}><div className="repository-community-heading"><div><p className="repository-community-eyebrow">THE PEOPLE BEHIND THE CODE</p><h1>{title}</h1><p>{description}</p></div>{workspace && <a href="/#/account">Your public profile <ArrowUpRight size={14} /></a>}</div><CommunitySections workspace={workspace} view={view} />{children}{!workspace && <footer className="community-footer"><a href="/docs">Docs</a><a href="/#/report">Report abuse</a><CloudflareBadgeFooter /></footer>}</Content></div>; }
const personIdentity = (person: Person) => person.handle;
export function CommunityPeople({ workspace, onSignIn }: { workspace: boolean; onSignIn?: () => void }) { const [search, setSearch] = useState(""), [query, setQuery] = useState(""); const state = usePages(`/community/people?q=${encodeURIComponent(query)}`, peopleRead, personIdentity); return <CommunityFrame workspace={workspace} view="people" title="Find your people" description="Meet contributors who chose to share their profiles." onSignIn={onSignIn}><div className="community-activity-layout"><section><form className="repository-community-search" onSubmit={event => { event.preventDefault(); setQuery(search.trim().slice(0, 200)); }}><Search size={16} /><Input value={search} maxLength={200} onChange={event => setSearch(event.target.value)} aria-label="Search people" placeholder="Search names, handles and biographies" /><Button type="submit" variant="outline" size="sm">Search</Button></form><div className="community-conversation-heading"><h2>{query ? `People matching “${query}”` : "People in the community"}</h2><Button variant="ghost" size="sm" disabled={state.loading} onClick={state.refresh}>Refresh</Button></div>{state.loading && <p role="status" className="community-empty">Loading people…</p>}{state.error && <p role="alert" className="community-error">{state.error}</p>}{!state.loading && !state.error && state.page?.items.map(person => <article className="community-person-row" key={person.handle}><span className="community-person-mark" aria-hidden>{person.displayName.trim().slice(0, 1).toUpperCase() || "·"}</span><div><a href={person.href}><h2>{person.displayName}</h2><span>@{person.handle}</span></a>{person.bio && <p>{person.bio}</p>}</div>{workspace ? <SignedInFollow handle={person.handle} /> : <a className="community-person-signin" href="/#/community?view=people&signin=1">Sign in to follow</a>}</article>)}{!state.loading && !state.error && state.page?.items.length === 0 && <div className="community-social-empty"><Users size={28} /><h3>{query ? "No matching people" : "A community starts with people"}</h3><p>{query ? "Try another name or handle." : "Profiles appear here only when their owners publish them and opt into discovery."}</p>{workspace && <a href="/#/account">Manage your profile <ArrowUpRight size={14} /></a>}</div>}<PageTail state={state} /></section><aside className="community-social-rail"><h2>People, then contributions</h2><p>Open a profile to see accepted contributions its owner has shared.</p><p className="community-rail-note">Following is a private preference. It doesn’t give anyone access to private repositories.</p>{workspace && <a href={link(true, "following")}><UserRoundCheck size={16} /><div><strong>The people you follow</strong><p>Accepted public work in one view.</p></div><ArrowUpRight size={13} /></a>}</aside></div></CommunityFrame>; }
type FollowState = { following: boolean; version: number; canFollow: boolean };
function SignedInFollow({ handle, onChanged }: { handle: string; onChanged?: () => void }) { const { userId } = useAuth(); return userId ? <FollowControl key={`${userId}:${handle}`} handle={handle} onChanged={onChanged} /> : null; }
function FollowControl({ handle, onChanged }: { handle: string; onChanged?: () => void }) {
 const [state, setState] = useState<FollowState | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0); const pending = useRef<{ following: boolean; expectedVersion: number; idempotencyKey: string } | null>(null), lock = useRef(false), active = useRef(true);
 useEffect(() => { active.current = true; let current = true; setError(""); void apiJson<FollowState>(`/following/${encodeURIComponent(handle)}`).then(value => { if (current) { setState(value); pending.current = null; } }).catch(() => { if (current) setError("Follow state unavailable."); }); return () => { current = false; active.current = false; }; }, [handle, revision]);
 async function save() {
  if (!state || lock.current || (!state.canFollow && !state.following)) return;
  pending.current ??= { following: !state.following, expectedVersion: state.version, idempotencyKey: crypto.randomUUID() };
  lock.current = true; setBusy(true); setError(""); let acknowledged = false;
  try {
   const receipt = await apiJson<{ following: boolean; version: number; replayed: boolean }>(`/following/${encodeURIComponent(handle)}`, { method: "PUT", json: pending.current });
   acknowledged = true;
   if (!active.current) return;
   pending.current = null; setState({ ...state, following: receipt.following, version: receipt.version, canFollow: false });
   try { const current = await apiJson<FollowState>(`/following/${encodeURIComponent(handle)}`); if (active.current) { setState(current); onChanged?.(); } }
   catch { if (active.current) { setError("Follow change saved. Current profile availability could not be confirmed; refresh state."); onChanged?.(); } }
  } catch { if (active.current) setError(acknowledged ? "Follow change saved. Refresh to check its current state." : "Result unknown. Retry the same request or refresh."); }
  finally { lock.current = false; if (active.current) setBusy(false); }
 }
 return <div className="community-follow-control"><Button size="sm" variant={state?.following ? "outline" : "orange"} disabled={busy || !state || (!state.canFollow && !state.following)} onClick={() => void save()}>{busy ? "Saving…" : pending.current ? "Retry follow change" : state?.following ? "Following · Unfollow" : state?.canFollow ? "Follow" : state ? "Unavailable" : "Loading…"}</Button>{error && <><p role="alert">{error}</p><Button variant="ghost" size="sm" disabled={busy} onClick={() => { setState(null); setRevision(value => value + 1); }}>Refresh state</Button></>}</div>;
}
const followingRead = (path: string) => apiJson<Page<Contribution>>(path);
const contributionIdentity = (item: Contribution) => `${item.actor.handle}:${item.repository.id}:${item.commit}:${item.acceptedAt}`;
export function CommunityFollowing() { const { userId } = useAuth(); return userId ? <FollowingFeed key={userId} /> : <p role="status" className="community-empty">Sign in to see the people you follow.</p>; }
function FollowingFeed() { const state = usePages("/community/following-activity", followingRead, contributionIdentity); return <CommunityFrame workspace view="following" title="The people you follow" description="Accepted contributions from their currently public repositories."><div className="community-activity-layout"><section><div className="community-conversation-heading"><h2>Accepted public work</h2><Button size="sm" variant="ghost" disabled={state.loading} onClick={state.refresh}>Refresh</Button></div>{state.loading && <p role="status" className="community-empty">Loading following activity…</p>}{state.error && <p role="alert" className="community-error">{state.error}</p>}{!state.loading && !state.error && state.page?.items.map(item => <article className="community-activity-item" key={contributionIdentity(item)}><span className="community-person-mark" aria-hidden>{item.actor.displayName.trim().slice(0, 1).toUpperCase() || "·"}</span><div><div className="community-activity-byline"><a href={item.actor.href}>{item.actor.displayName}</a><span>contributed to</span><a href={item.repository.href}>{item.repository.name}</a></div><time dateTime={item.acceptedAt}>Accepted {new Date(item.acceptedAt).toLocaleDateString()}</time><a className="community-activity-post" href={item.href}><span className="community-activity-kind"><GitBranch size={15} />Accepted contribution</span><code title={item.commit}>{item.commit.slice(0, 12)}</code><span className="community-activity-open">View accepted revision <ArrowUpRight size={13} /></span></a></div></article>)}{!state.loading && !state.error && state.page?.items.length === 0 && <div className="community-social-empty"><UserRoundCheck size={28} /><h3>Keep up with the people you follow</h3><p>No accepted contributions are available in this view yet. Follow contributors to see the public work they share.</p><a href={link(true, "people")}>Find people <ArrowUpRight size={14} /></a></div>}<PageTail state={state} /></section><FollowingPeople onChanged={state.refresh} /></div></CommunityFrame>; }

type FollowedPerson = Person & { relationshipVersion: number; unavailable?: boolean };
async function followingPeopleRead(path: string): Promise<Page<FollowedPerson>> { const value = await apiJson<{ following: FollowedPerson[]; nextCursor: string | null; checked?: number; incomplete: boolean }>(path); return { items: value.following, nextCursor: value.nextCursor, checked: value.checked ?? value.following.length, incomplete: value.incomplete, scope: "Your private following preferences. Unavailable profiles expose only the handle you originally followed." }; }
const followedIdentity = (person: FollowedPerson) => person.handle;
function FollowingPeople({ onChanged }: { onChanged: () => void }) { const state = usePages("/following", followingPeopleRead, followedIdentity); return <aside className="community-social-rail community-following-people"><div className="community-conversation-heading"><h2>Following</h2><Button variant="ghost" size="sm" disabled={state.loading} onClick={state.refresh}>Refresh</Button></div>{state.loading && <p role="status">Loading follows…</p>}{state.error && <p role="alert" className="community-error">{state.error}</p>}{!state.loading && !state.error && state.page?.items.map(person => <div className="community-following-person" key={person.handle}>{person.unavailable ? <div><strong>@{person.handle}</strong><p>Profile unavailable. You can remove this follow.</p></div> : <a href={person.href}><strong>{person.displayName}</strong><p>@{person.handle}</p></a>}<SignedInFollow handle={person.handle} onChanged={() => { state.refresh(); onChanged(); }} /></div>)}{!state.loading && !state.error && state.page?.items.length === 0 && <p>You aren’t following anyone in this view.</p>}<PageTail state={state} /><a href={link(true, "people")}><Users size={16} /><strong>Find people</strong><ArrowUpRight size={13} /></a></aside>; }

type DiscoverySetting = { enabled: boolean; version: number; delivery: "pending" | "delivered"; outdated?: boolean };
export function ProfileDiscoverySettings({ published, suppressed, profileVersion, disabled, onBusyChange }: { published: boolean; suppressed: boolean; profileVersion: number; disabled: boolean; onBusyChange: (busy: boolean) => void }) {
 const [state, setState] = useState<DiscoverySetting | null>(null), [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [revision, setRevision] = useState(0), [unknown, setUnknown] = useState(false);
 const active = useRef(true), lock = useRef(false), generation = useRef(0);
 useEffect(() => { active.current = true; generation.current++; let current = true; setState(null); setError(""); setNotice(""); setConfirmed(false); void apiJson<DiscoverySetting>("/profile/discovery").then(value => { if (current) { setState(value); setUnknown(false); } }).catch(() => { if (current) setError("Discovery settings could not be loaded. Refresh before changing them."); }); return () => { current = false; active.current = false; generation.current++; }; }, [profileVersion, revision]);
 async function save(enabled = !state?.enabled) { if (!state || lock.current || disabled || unknown || (enabled && (!published || suppressed || !confirmed))) return; const current = generation.current; lock.current = true; setBusy(true); onBusyChange(true); setError(""); setNotice(""); try { const value = await apiJson<DiscoverySetting>("/profile/discovery", { method: "PUT", json: { enabled, confirmed: true, expectedVersion: state.version } }); if (active.current && generation.current === current) { setState(value); setConfirmed(false); setNotice(value.enabled ? "Discovery preference saved." : "Discovery disabled."); } } catch { if (active.current && generation.current === current) { setUnknown(true); setError("The saved result is unknown. Refresh the current setting before changing it again."); } } finally { lock.current = false; onBusyChange(false); if (active.current) setBusy(false); } }
 return <section className="space-y-3 border-t border-border pt-4 mt-4"><h2 className="text-sm font-medium">Community discovery</h2><p className="text-xs leading-6 text-muted-foreground">Listing your public profile makes your handle, name and biography searchable in Community. People can privately follow your accepted contributions from currently public repositories. Private repositories and sign-in details remain excluded.</p>{!published && <p className="text-xs text-muted-foreground">Publish your profile above before enabling discovery.</p>}{suppressed && <p className="text-xs text-muted-foreground">Discovery is unavailable while your public profile is suppressed.</p>}{state && <p className="text-xs text-muted-foreground">Setting: {state.enabled ? "enabled" : "disabled"}.{state.outdated ? " Your profile changed; renew discovery publication to share the current profile." : ""}{state.delivery === "pending" ? " Directory delivery is pending. Refresh to check delivery." : " Directory delivery confirmed for the saved setting."}</p>}{state && (!state.enabled || state.outdated) && published && !suppressed && <label className="flex items-start gap-2 text-xs leading-5"><input className="mt-1 accent-orange-600" type="checkbox" checked={confirmed} disabled={disabled || busy || unknown} onChange={event => setConfirmed(event.target.checked)} /><span>I confirm that anyone may find my published profile in Community and follow its public accepted contributions.</span></label>}{!state && !error && <p role="status" className="text-xs text-muted-foreground">Loading discovery setting…</p>}{error && <p role="alert" className="text-xs text-destructive">{error}</p>}{notice && <p role="status" className="text-xs text-muted-foreground">{notice}</p>}<div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" disabled={disabled || busy || !state || unknown || (!state.enabled && (!published || suppressed || !confirmed))} onClick={() => void save()}>{busy ? "Saving…" : state?.enabled ? "Disable discovery" : "List my profile in Community"}</Button>{state?.enabled && state.outdated && <Button type="button" size="sm" variant="orange" disabled={disabled || busy || unknown || !published || suppressed || !confirmed} onClick={() => void save(true)}>Renew discovery publication</Button>}<Button type="button" size="sm" variant="ghost" disabled={disabled || busy} onClick={() => setRevision(value => value + 1)}>Refresh setting</Button></div></section>;
}
