import {useEffect,useRef,useState} from "react";
import {useAuth} from "@clerk/clerk-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {reservationDeadline,ReservationTimeout} from "../reservation-deadline";
import {apiJson} from "../api";
import {appendReservationPage,reservationFailurePage,parseReservationPage,reservationMoney,reservationSubtotal,type ReservationPage} from "../reservation-view";
const currentMonth=()=>new Date().toISOString().slice(0,7);
const resourceLabels={"native-essential":"Essential native capacity","native-optional":"Optional native capacity","managed-agent":"Managed agent capacity","optional-unclassified":"Unclassified optional capacity","legacy-unclassified":"Legacy unclassified capacity"} as const;
export function ReservationRows({page}:{page:ReservationPage}){return <><p className="text-sm">Original reservations shown: <strong>{reservationMoney(reservationSubtotal(page))}</strong><span className="text-muted-foreground"> · {page.entries.length} {page.entries.length===1?"attempt":"attempts"} · not current liability or an invoice</span></p>{page.entries.length===0?<p className="text-sm text-muted-foreground">No recorded reservations for this month.</p>:<ul className="divide-y divide-border">{page.entries.map(row=><li key={row.attemptDigest} className="py-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><code title={row.attemptDigest} className="font-mono text-xs">Attempt {row.attemptDigest.slice(0,12)}</code><span>{row.accountingState} · {reservationMoney(row.reservationUsdMicros)} original reservation</span></div><dl className="mt-2 flex flex-wrap gap-x-6 gap-y-2 text-xs"><div><dt className="text-muted-foreground">Admitted capacity slots</dt><dd>{row.admittedCalls}</dd></div><div><dt className="text-muted-foreground">Admitted container seconds</dt><dd>{row.admittedContainerSeconds}</dd></div><div><dt className="text-muted-foreground">Dispatch</dt><dd>{row.dispatchAttempted?"Attempted":"Not recorded"}</dd></div><div><dt className="text-muted-foreground">Reserved resource</dt><dd>{row.resourceKind?resourceLabels[row.resourceKind]:"Unclassified capacity"}</dd></div><div><dt className="text-muted-foreground">Workflow attribution</dt><dd>Unattributed</dd></div>{row.recordedReconciliationUsdMicros!==null&&<div><dt className="text-muted-foreground">Recorded reconciliation</dt><dd>{reservationMoney(row.recordedReconciliationUsdMicros)} · invoice unverified</dd></div>}</dl></li>)}</ul>}</>;}
export function OperatorReservations(){const {userId}=useAuth();return userId?<ReservationPanel key={userId}/>:null;}
function ReservationPanel(){const [expanded,setExpanded]=useState(false),[month,setMonth]=useState(currentMonth),[page,setPage]=useState<ReservationPage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const saved=useRef<ReservationPage|null>(null),active=useRef<AbortController|null>(null),sequence=useRef(0),pending=useRef(false);useEffect(()=>()=>{sequence.current++;active.current?.abort();},[]);
 const reset=(value:string)=>{sequence.current++;active.current?.abort();pending.current=false;setBusy(false);setMonth(value);saved.current=null;setPage(null);setError(null);};
 const load=async(more=false)=>{if(pending.current||!/^\d{4}-(?:0[1-9]|1[0-2])$/.test(month))return;if(more&&(!page?.nextCursor||page.entries.length>=500))return;pending.current=true;setBusy(true);setError(null);const request=++sequence.current,controller=new AbortController();active.current=controller;const requestedMonth=month;try{const query=new URLSearchParams({month:requestedMonth,...(more?{cursor:page!.nextCursor!}:{})});const result=parseReservationPage(await reservationDeadline(()=>apiJson<unknown>(`/operator/reservation-attribution?${query}`,{signal:controller.signal}),controller),requestedMonth);if(request!==sequence.current||controller.signal.aborted)return;const next=appendReservationPage(more?saved.current:null,result);reservationSubtotal(next);saved.current=next;setPage(next);}catch(cause){if(request===sequence.current&&(!controller.signal.aborted||cause instanceof ReservationTimeout)){saved.current=reservationFailurePage(saved.current,cause);setPage(saved.current);setError(cause instanceof Error?cause.message:"Reservations unavailable");}}finally{if(request===sequence.current){pending.current=false;setBusy(false);}}};
 return <section className="border-t border-border pt-6 space-y-3" aria-labelledby="reservation-heading"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id="reservation-heading" className="font-semibold">Execution reservations</h2><Button variant="outline" size="sm" aria-expanded={expanded} aria-controls="reservation-panel" onClick={()=>setExpanded(value=>!value)}>{expanded?"Hide reservations":"View reservations"}</Button></div>{expanded&&<div id="reservation-panel" className="space-y-4"><p className="text-sm text-muted-foreground">Admitted capacity protects the execution budget. Measured usage and invoice costs remain unknown.</p><div className="flex flex-wrap items-end gap-2"><label className="text-sm space-y-1"><span className="block">Month (UTC)</span><Input type="month" value={month} onChange={event=>reset(event.target.value)} className="w-44" /></label><Button size="sm" variant="outline" disabled={busy} onClick={()=>void load()}>{page?"Refresh":"Load reservations"}</Button><Button size="sm" variant="ghost" onClick={()=>reset(currentMonth())}>Current month</Button></div>{error&&<p role="alert" className="text-sm text-destructive">Reservations could not be refreshed. {page?"The last loaded view remains below. ":""}{error}</p>}{busy&&<p role="status" className="text-xs text-muted-foreground">Loading reservations…</p>}{page&&<><ReservationRows page={page}/><p className="text-xs text-muted-foreground">A fixed set of attempts is paged; each page reflects its current recorded counters. Refresh starts a new set.</p>{page.nextCursor&&<Button variant="outline" size="sm" disabled={busy||page.entries.length>=500} onClick={()=>void load(true)}>{page.entries.length>=500?"500-attempt display limit":"Load more reservations"}</Button>}{page.entries.length>=500&&page.nextCursor&&<p className="text-xs text-muted-foreground">More reservations exist. This view is incomplete.</p>}</>}</div>}</section>;
}
