import React, { useEffect, useRef, useState } from 'react';
import { useUser } from '@clerk/clerk-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { changeOrganization, createOrganization, readOrganizations, type OrganizationSnapshot, type OrganizationRole, type RepositoryRole } from '../organization-api';

function RoleSelect({value,onChange,repository=false,disabled=false}:{value:string;onChange:(value:string)=>void;repository?:boolean;disabled?:boolean}) {
  return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="w-32" aria-label={repository?'Repository permission':'Organization role'}><SelectValue/></SelectTrigger><SelectContent>{(repository?['read','write','admin']:['member','owner']).map(role=><SelectItem key={role} value={role}>{role}</SelectItem>)}</SelectContent></Select>;
}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) {
  const id=React.useId();return <div className="space-y-1.5 min-w-0 flex-1"><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={event=>onChange(event.target.value)} maxLength={256} required/></div>;
}
function ChildTeams({organization,team,owner,disabled,onChange}:{organization:OrganizationSnapshot;team:OrganizationSnapshot['teams'][number];owner:boolean;disabled:boolean;onChange:(childId:string,present:boolean)=>void}) {
  const [selected,setSelected]=useState('');
  const available=organization.teams.filter(candidate=>candidate.id!==team.id&&!team.childTeams.includes(candidate.id));
  const selectionAvailable=available.some(candidate=>candidate.id===selected);
  return <div className="space-y-3">
    <h4 className="text-sm font-medium">Child teams</h4>
    <p className="text-xs text-muted-foreground">Members of child teams inherit this team's repository access.</p>
    {team.childTeams.length===0&&<p className="text-sm text-muted-foreground">No child teams.</p>}
    <ul className="space-y-2">{team.childTeams.map(childId=><li key={childId} className="text-sm flex gap-3 items-center"><span className="flex-1 break-all">{organization.teams.find(candidate=>candidate.id===childId)?.name??childId}</span>{owner&&<Button variant="ghost" size="sm" disabled={disabled} onClick={()=>onChange(childId,false)}>Remove child team</Button>}</li>)}</ul>
    {owner&&available.length>0&&<form className="flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();if(selectionAvailable)onChange(selected,true);}}>
      <Select value={selectionAvailable?selected:''} onValueChange={setSelected} disabled={disabled}><SelectTrigger className="w-full sm:w-64" aria-label={`Child team for ${team.name}`}><SelectValue placeholder="Choose a child team"/></SelectTrigger><SelectContent>{available.map(candidate=><SelectItem key={candidate.id} value={candidate.id}>{candidate.name}</SelectItem>)}</SelectContent></Select>
      <Button type="submit" variant="outline" disabled={disabled||!selectionAvailable}>Add child team</Button>
    </form>}
  </div>;
}
export function Organizations() {
  const {user}=useUser();
  const [organizations,setOrganizations]=useState<OrganizationSnapshot[]>([]),[selected,setSelected]=useState(''),[loaded,setLoaded]=useState(false),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const [name,setName]=useState(''),[inviteUser,setInviteUser]=useState(''),[inviteRole,setInviteRole]=useState<OrganizationRole>('member'),[teamId,setTeamId]=useState(''),[teamName,setTeamName]=useState(''),[teamUser,setTeamUser]=useState(''),[repositoryId,setRepositoryId]=useState(''),[subjectId,setSubjectId]=useState(''),[subjectKind,setSubjectKind]=useState<'user'|'team'>('team'),[grantRole,setGrantRole]=useState<RepositoryRole>('read');
  const [uncertain,setUncertain]=useState(false);
  const lock=useRef(false),sequence=useRef(0);
  const disabled=busy||uncertain;
  const reload=async()=>{const request=++sequence.current;try{const next=await readOrganizations();if(request===sequence.current){setOrganizations(next);setLoaded(true);setError(null);setUncertain(false);}}catch(cause){if(request===sequence.current)setError(cause instanceof Error?cause.message:'Organizations could not be loaded');}};
  useEffect(()=>{void reload();return()=>{sequence.current++;};},[]);
  const organization=organizations.find(item=>item.id===selected)??organizations[0];
  const owner=organization?.viewerRole==='owner'||(organization?.members.some(member=>member.userId===user?.id&&member.role==='owner')??false);
  const run=async(action:()=>Promise<OrganizationSnapshot>)=>{if(lock.current||uncertain)return;lock.current=true;setBusy(true);setError(null);sequence.current++;try{const next=await action();setOrganizations(current=>[...current.filter(item=>item.id!==next.id),next]);setSelected(next.id);}catch(cause){setUncertain(true);setError(`${cause instanceof Error?cause.message:'Change could not be confirmed'}. Refresh before trying again.`);}finally{lock.current=false;setBusy(false);}};
  const mutate=(path:string,method:'POST'|'PUT'|'DELETE',values:Record<string,unknown>={})=>organization&&run(()=>changeOrganization(organization,path,method,values));
  const encoded=(id:string)=>encodeURIComponent(id);
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 sm:py-8 space-y-8">
    <header><h1 className="text-2xl font-semibold tracking-tight">Organizations</h1><p className="text-sm text-muted-foreground mt-2">Manage membership, teams, and repository access.</p></header>
    {error&&<div role="alert" className="border border-destructive/40 rounded-md p-3 text-sm flex flex-wrap items-center gap-3"><span className="flex-1">{error}</span><Button variant="outline" size="sm" disabled={busy} onClick={()=>void reload()}>Refresh</Button></div>}
    <form className="flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();if(name.trim())void run(()=>createOrganization(name.trim()));}}><TextField label="Organization name" value={name} onChange={setName}/><Button type="submit" disabled={disabled||!name.trim()}>Create organization</Button></form>
    {!loaded&&!error&&<p role="status" className="text-sm text-muted-foreground">Loading organizations…</p>}
    {loaded&&!organizations.length&&<p className="text-sm text-muted-foreground">You do not belong to an organization yet.</p>}
    {organization&&<>
      <Select value={organization.id} onValueChange={setSelected}><SelectTrigger aria-label="Organization" className="max-w-sm"><SelectValue/></SelectTrigger><SelectContent>{organizations.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select>
      {organization.accessSyncPending&&<div role="status" className="flex flex-wrap items-center gap-3 text-sm"><span>Repository access updates need confirmation.</span>{owner&&<Button variant="outline" disabled={busy||uncertain} onClick={()=>void mutate('/reconcile','POST')}>Confirm access updates</Button>}</div>}
      <section className="space-y-4"><h2 className="text-lg font-semibold">Members</h2><ul className="divide-y divide-border">{organization.members.map(member=><li key={member.userId} className="py-3 flex flex-wrap items-center gap-3"><span className="flex-1 text-sm break-all">{member.userId}</span>{owner?<><RoleSelect value={member.role} disabled={disabled} onChange={role=>void mutate(`/members/${encoded(member.userId)}`,'PUT',{role})}/><Button variant="outline" size="sm" disabled={disabled} onClick={()=>void mutate(`/members/${encoded(member.userId)}`,'DELETE')}>Remove</Button></>:<span className="text-sm text-muted-foreground">{member.role}</span>}</li>)}</ul>
      {owner&&<form className="flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();void mutate('/invitations','POST',{userId:inviteUser.trim(),role:inviteRole});}}><TextField label="Invite user ID" value={inviteUser} onChange={setInviteUser}/><RoleSelect value={inviteRole} onChange={role=>setInviteRole(role as OrganizationRole)}/><Button type="submit" disabled={disabled||!inviteUser.trim()}>Invite member</Button></form>}</section>
      {organization.invitations.length>0&&<section className="space-y-4"><h2 className="text-lg font-semibold">Invitations</h2><ul className="divide-y divide-border">{organization.invitations.map(invitation=><li key={invitation.id} className="py-3 flex flex-wrap items-center gap-3"><div className="flex-1 min-w-0"><p className="text-sm break-all">{invitation.userId} · {invitation.role}</p><p className="text-xs text-muted-foreground">Expires {new Date(invitation.expiresAt).toLocaleString()}</p></div>{invitation.userId===user?.id&&<Button size="sm" disabled={disabled||invitation.expiresAt<=Date.now()} onClick={()=>void mutate(`/invitations/${encoded(invitation.id)}/accept`,'POST')}>Accept</Button>}{owner&&<Button variant="outline" size="sm" disabled={disabled} onClick={()=>void mutate(`/invitations/${encoded(invitation.id)}`,'DELETE')}>Revoke</Button>}</li>)}</ul></section>}
      <section className="space-y-4"><h2 className="text-lg font-semibold">Teams</h2>{!organization.teams.length&&<p className="text-sm text-muted-foreground">No teams yet.</p>}{organization.teams.map(team=><div key={team.id} className="border-t border-border pt-4 space-y-3"><div className="flex items-center gap-3"><div className="flex-1"><h3 className="text-sm font-medium">{team.name}</h3><p className="text-xs text-muted-foreground break-all">{team.id}</p></div>{owner&&<Button variant="outline" size="sm" disabled={disabled} onClick={()=>void mutate(`/teams/${encoded(team.id)}`,'DELETE')}>Delete team</Button>}</div><ul className="space-y-2">{team.members.map(userId=><li key={userId} className="text-sm flex gap-3 items-center"><span className="flex-1 break-all">{userId}</span>{owner&&<Button variant="ghost" size="sm" disabled={disabled} onClick={()=>void mutate(`/teams/${encoded(team.id)}/members/${encoded(userId)}`,'PUT',{present:false})}>Remove</Button>}</li>)}</ul>{owner&&<form className="flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();void mutate(`/teams/${encoded(team.id)}/members/${encoded(teamUser.trim())}`,'PUT',{present:true});}}><TextField label={`Member user ID for ${team.name}`} value={teamUser} onChange={setTeamUser}/><Button type="submit" variant="outline" disabled={disabled||!teamUser.trim()}>Add to team</Button></form>}<ChildTeams organization={organization} team={team} owner={owner} disabled={disabled} onChange={(childId,present)=>void mutate(`/teams/${encoded(team.id)}/children/${encoded(childId)}`,'PUT',{present})}/></div>)}{owner&&<form className="flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();void mutate('/teams','POST',{teamId:teamId.trim(),name:teamName.trim()});}}><TextField label="Team ID" value={teamId} onChange={setTeamId}/><TextField label="Team name" value={teamName} onChange={setTeamName}/><Button type="submit" disabled={disabled||!teamId.trim()||!teamName.trim()}>Create team</Button></form>}</section>
      <section className="space-y-4"><h2 className="text-lg font-semibold">Repository access</h2><ul className="divide-y divide-border">{organization.grants.map(grant=><li key={`${grant.repositoryId}:${grant.subject.kind}:${grant.subject.id}`} className="py-3 flex flex-wrap items-center gap-3"><div className="flex-1 min-w-0 text-sm"><a className="break-all underline underline-offset-4" href={`#/p/${encodeURIComponent(grant.repositoryId)}`}>{grant.repositoryId}</a><p className="text-muted-foreground break-all">{grant.subject.kind} {grant.subject.id} · {grant.role}</p></div>{owner&&<Button variant="outline" size="sm" disabled={disabled} onClick={()=>void mutate('/grants','DELETE',{repositoryId:grant.repositoryId,subject:grant.subject})}>Revoke access</Button>}</li>)}</ul>{!organization.grants.length&&<p className="text-sm text-muted-foreground">No repository grants.</p>}{owner&&<form className="flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();void mutate('/grants','PUT',{repositoryId:repositoryId.trim(),subject:{kind:subjectKind,id:subjectId.trim()},role:grantRole});}}><TextField label="Repository ID" value={repositoryId} onChange={setRepositoryId}/><div className="space-y-1.5"><Label>Grant access to</Label><Select value={subjectKind} onValueChange={value=>setSubjectKind(value as 'user'|'team')}><SelectTrigger aria-label="Grant subject type"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="team">Team</SelectItem><SelectItem value="user">User</SelectItem></SelectContent></Select></div><TextField label={subjectKind==='team'?'Team ID':'User ID'} value={subjectId} onChange={setSubjectId}/><RoleSelect value={grantRole} repository onChange={role=>setGrantRole(role as RepositoryRole)}/><Button type="submit" disabled={disabled||!repositoryId.trim()||!subjectId.trim()}>Grant access</Button></form>}</section>
    </>}
  </div>;
}
