import {enum as enumSchema,int,literal,maxLength,minLength,minimum,nullable,object,optional,string,union,uuid,type infer as Infer} from 'zod/mini';
import {apiJson} from './api';
const version=int().check(minimum(0)),adapter=enumSchema(['ticket-booking-browser','shipping-calculator-browser']);
const configSchema=union([object({mode:literal('review-required')}),object({mode:literal('verified-auto-accept'),protectedAdapter:adapter})]);
const policySchema=object({mode:enumSchema(['review-required','verified-auto-accept']),protectedAdapter:optional(adapter),version,authorizedBy:nullable(string().check(minLength(1),maxLength(256))),updatedAt:nullable(int().check(minimum(0)))});
const stateSchema=object({currentPolicy:policySchema,eligibility:object({origin:enumSchema(['platform-fixture','imported','ordinary']),protectedAdapter:nullable(adapter)})});
const intentSchema=object({eventId:uuid(),expectedVersion:version,config:configSchema});
export type AcceptancePolicy=Infer<typeof policySchema>;
export type AcceptancePolicyState=Infer<typeof stateSchema>;
export type AcceptancePolicyIntent=Infer<typeof intentSchema>;
export function checkedAcceptancePolicy(value:unknown):AcceptancePolicy{const policy=policySchema.parse(value);if((policy.mode==='verified-auto-accept')!==(policy.protectedAdapter!==undefined)||(policy.version===0?(policy.mode!=='review-required'||policy.authorizedBy!==null||policy.updatedAt!==null):(policy.authorizedBy===null||policy.updatedAt===null)))throw Error('Acceptance policy evidence is incomplete');return policy;}
export async function readAcceptancePolicy(projectId:string,signal:AbortSignal):Promise<AcceptancePolicyState>{const state=stateSchema.parse(await apiJson<unknown>(`/p/${projectId}/acceptance-policy`,{signal}));return{...state,currentPolicy:checkedAcceptancePolicy(state.currentPolicy)};}
export function acceptancePolicyIntent(previous:AcceptancePolicyIntent|null,expectedVersion:number,config:AcceptancePolicyIntent['config']):AcceptancePolicyIntent{return previous??intentSchema.parse({eventId:crypto.randomUUID(),expectedVersion,config});}
export async function saveAcceptancePolicy(projectId:string,intent:AcceptancePolicyIntent,signal:AbortSignal){const result=object({appliedPolicy:policySchema,appliedVersion:version,currentPolicy:policySchema}).parse(await apiJson<unknown>(`/p/${projectId}/acceptance-policy`,{method:'PUT',json:intentSchema.parse(intent),signal}));const appliedPolicy=checkedAcceptancePolicy(result.appliedPolicy),currentPolicy=checkedAcceptancePolicy(result.currentPolicy);if(result.appliedVersion!==intent.expectedVersion+1||appliedPolicy.version!==result.appliedVersion||currentPolicy.version<result.appliedVersion||appliedPolicy.mode!==intent.config.mode||(intent.config.mode==='verified-auto-accept'&&appliedPolicy.protectedAdapter!==intent.config.protectedAdapter))throw Error('Acceptance policy save receipt changed scope');return{appliedPolicy,appliedVersion:result.appliedVersion,currentPolicy};}
interface PolicyStorage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
const recoveryKey=(identity:string,projectId:string)=>`flaregit.review.${JSON.stringify([identity,projectId,'acceptance-policy'])}`;
export function readAcceptancePolicyIntent(storage:PolicyStorage,identity:string,projectId:string):AcceptancePolicyIntent|null{try{const raw=storage.getItem(recoveryKey(identity,projectId));return raw&&raw.length<2000?intentSchema.parse(JSON.parse(raw)):null;}catch{return null;}}
export function persistAcceptancePolicyIntent(storage:PolicyStorage,identity:string,projectId:string,intent:AcceptancePolicyIntent|null):boolean{try{if(intent)storage.setItem(recoveryKey(identity,projectId),JSON.stringify(intentSchema.parse(intent)));else storage.removeItem(recoveryKey(identity,projectId));return true;}catch{return false;}}
