import {array,boolean,enum as enumSchema,int,literal,maxLength,minLength,minimum,object,optional,regex,string,uuid,type infer as Infer} from 'zod/mini';import {apiJson} from './api';import {isSafeRef} from '@/core/sanitize';
const sha=string().check(regex(/^[a-f0-9]{40}$/)),name=string().check(minLength(1),maxLength(200)),version=int().check(minimum(0));
const branchSchema=object({name,ref:string().check(minLength(1),maxLength(220)),commit:sha});
const inventorySchema=object({branches:array(branchSchema).check(maxLength(200)),truncated:boolean(),defaultBranch:name,acceptedCommit:sha,providerVerified:literal(true)});
const operationSchema=object({operationId:uuid(),projectId:string().check(minLength(1),maxLength(128)),branch:name,sourceCommit:sha,acceptedCommit:sha,phase:enumSchema(['prepared','unknown','confirmed','refused']),reason:optional(enumSchema(['existing_ref','different_ref','owner_abandoned_prepared'])),createdAt:version,observedCommit:optional(sha),acceptedRoot:optional(object({status:enumSchema(["ready","pending_unverified","pending_repair","unregistered"]),head:optional(sha),version:optional(version)})),cleanup:object({nativeState:enumSchema(["unconfirmed","stopped","not_allocated"]),credentialStatus:enumSchema(["issuance_unknown","pending","revoked","not_issued"]),recoveryRequired:boolean()})});
export type BranchInventory=Infer<typeof inventorySchema>;export type SavedBranchOperation=Infer<typeof operationSchema>;
export interface BranchSelection{name:string;commit:string;accepted:boolean}
export interface BranchIntent{signature:string;operationId:string;name:string;sourceCommit:string}
export function checkedBranchInventory(value:unknown):BranchInventory{const inventory=inventorySchema.parse(value);if(!isSafeRef(inventory.defaultBranch)||new Set(inventory.branches.map(branch=>branch.name)).size!==inventory.branches.length||inventory.branches.some(branch=>!isSafeRef(branch.name)||branch.ref!==`refs/heads/${branch.name}`))throw Error('Observed branch inventory did not match its refs');return inventory;}
export function checkedBranchOperation(value:unknown,expected?:{operationId:string;name:string;sourceCommit:string},projectId?:string):SavedBranchOperation{const operation=operationSchema.parse(value);if((projectId&&operation.projectId!==projectId)||!isSafeRef(operation.branch)||operation.branch.startsWith('refs/')||(expected&&(operation.operationId!==expected.operationId||operation.branch!==expected.name||operation.sourceCommit!==expected.sourceCommit))||(operation.phase==='confirmed'&&operation.observedCommit!==operation.sourceCommit)||(operation.phase==='refused'&&!operation.reason)||(operation.acceptedRoot?.status==='ready'&&(!operation.acceptedRoot.head||operation.acceptedRoot.version===undefined||/^0{40}$/.test(operation.acceptedRoot.head)))||(operation.cleanup.recoveryRequired!==(operation.cleanup.nativeState==='unconfirmed'||['issuance_unknown','pending'].includes(operation.cleanup.credentialStatus))))throw Error('Saved branch operation was not confirmed');return operation;}
export function acceptedBranchSelection(inventory:BranchInventory):BranchSelection{return{name:inventory.defaultBranch,commit:inventory.acceptedCommit,accepted:true};}
export function observedBranchSelection(inventory:BranchInventory,branch:Infer<typeof branchSchema>):BranchSelection{const saved=inventory.branches.find(value=>value.name===branch.name&&value.ref===branch.ref&&value.commit===branch.commit);if(!saved)throw Error('Branch observation changed');return{name:saved.name,commit:saved.commit,accepted:saved.name===inventory.defaultBranch&&saved.commit===inventory.acceptedCommit};}
export function branchIntent(previous:BranchIntent|null,projectId:string,branchName:string,sourceCommit:string):BranchIntent{if(!isSafeRef(branchName)||(branchName.startsWith('refs/')||branchName==='HEAD'))throw Error('Use a supported Git branch name');sha.parse(sourceCommit);if(/^0{40}$/.test(sourceCommit))throw Error('A committed accepted source is required');const signature=JSON.stringify([projectId,branchName,sourceCommit]);return previous?.signature===signature?previous:{signature,operationId:crypto.randomUUID(),name:branchName,sourceCommit};}
export async function readBranchInventory(projectId:string,signal:AbortSignal){return checkedBranchInventory(await apiJson<unknown>(`/p/${projectId}/branches`,{signal}));}
const operationsSchema=object({operations:array(operationSchema).check(maxLength(20)),truncated:boolean(),pendingTruncated:boolean(),historyHasMore:boolean()});
export async function readBranchOperations(projectId:string,signal:AbortSignal){const value=operationsSchema.parse(await apiJson<unknown>(`/p/${projectId}/branch-operations`,{signal}));const operations=value.operations.map(operation=>checkedBranchOperation(operation,undefined,projectId));if(new Set(operations.map(operation=>operation.operationId)).size!==operations.length)throw Error('Saved branch operations repeated an identity');return{...value,operations};}
export async function readBranchOperation(projectId:string,operation:SavedBranchOperation,signal:AbortSignal){return checkedBranchOperation(await apiJson<unknown>(`/p/${projectId}/branch-operations/${operation.operationId}`,{signal}),{operationId:operation.operationId,name:operation.branch,sourceCommit:operation.sourceCommit},projectId);}
export async function createBranchReference(projectId:string,intent:BranchIntent,signal:AbortSignal){return checkedBranchOperation(await apiJson<unknown>(`/p/${projectId}/branches`,{method:'POST',json:{operationId:intent.operationId,name:intent.name,sourceCommit:intent.sourceCommit},signal}),intent,projectId);}
export async function reconcileBranchReference(projectId:string,operation:SavedBranchOperation,signal:AbortSignal){if(operation.phase!=='unknown')throw Error('Only an uncertain saved push can be inspected without dispatch');return checkedBranchOperation(await apiJson<unknown>(`/p/${projectId}/branch-operations/${operation.operationId}/reconcile`,{method:'POST',json:{expectedPhase:'unknown'},signal}),{operationId:operation.operationId,name:operation.branch,sourceCommit:operation.sourceCommit},projectId);}
export async function continuePreparedBranch(projectId:string,operation:SavedBranchOperation,signal:AbortSignal){if(operation.phase!=='prepared')throw Error('Only the saved prepared request can begin creation');return createBranchReference(projectId,{signature:JSON.stringify([projectId,operation.branch,operation.sourceCommit]),operationId:operation.operationId,name:operation.branch,sourceCommit:operation.sourceCommit},signal);}
const recoveryAttemptSchema=object({attemptId:uuid(),operationId:uuid(),kind:enumSchema(['inventory','create']),nativeState:enumSchema(['possible','stopped']),executionEnded:boolean(),createdAt:version,credentialStatus:enumSchema(['issuance_unknown','pending','revoked','not_issued'])});
const recoverySchema=object({attempts:array(recoveryAttemptSchema).check(maxLength(20)),truncated:boolean(),providerVerified:literal(false)});
export type BranchRecoveryAttempt=Infer<typeof recoveryAttemptSchema>;export type BranchRecovery=Infer<typeof recoverySchema>;
export async function readBranchRecovery(projectId:string,signal:AbortSignal):Promise<BranchRecovery>{const value=recoverySchema.parse(await apiJson<unknown>(`/p/${projectId}/branch-runtime/recovery`,{signal}));if(new Set(value.attempts.map(attempt=>attempt.attemptId)).size!==value.attempts.length)throw Error('Branch recovery inventory repeated an attempt');return value;}
export async function cleanupBranchExecution(projectId:string,attempt:BranchRecoveryAttempt,signal:AbortSignal){const result=object({attemptId:uuid(),operationId:uuid(),nativeStopped:boolean(),credentialsComplete:boolean()}).parse(await apiJson<unknown>(`/p/${projectId}/branch-runtime/recovery`,{method:'POST',json:{attemptId:attempt.attemptId,operationId:attempt.operationId,confirmStop:true},signal}));if(result.attemptId!==attempt.attemptId||result.operationId!==attempt.operationId)throw Error('Branch cleanup receipt changed its saved scope');return result;}
export async function abandonPreparedBranch(projectId:string,operation:SavedBranchOperation,signal:AbortSignal){if(operation.phase!=='prepared'||operation.cleanup.recoveryRequired)throw Error('Only stopped, undispatched prepared requests may be abandoned');const result=checkedBranchOperation(await apiJson<unknown>(`/p/${projectId}/branch-operations/${operation.operationId}/abandon`,{method:'POST',json:{expectedPhase:'prepared'},signal}),{operationId:operation.operationId,name:operation.branch,sourceCommit:operation.sourceCommit},projectId);if(result.phase!=='refused'||result.reason!=='owner_abandoned_prepared')throw Error('Prepared branch abandonment was not confirmed');return result;}

/** A confirmed Git ref and its recorded accepted baseline are distinct facts. */
export function acceptedBranchBaselineLabel(operation:SavedBranchOperation):string{if(operation.phase!=="confirmed")return "Git reference confirmation remains pending.";switch(operation.acceptedRoot?.status){case "ready":return "Recorded branch baseline available.";case "pending_unverified":return "Git reference confirmed; its original requirements snapshot is unavailable.";case "pending_repair":return "Git reference confirmed; accepted baseline registry repair is pending.";case "unregistered":return "Git reference confirmed; no accepted branch baseline is recorded.";default:return "Git reference confirmed; accepted baseline status is unavailable.";}}
export async function checkRecordedBranchBaseline(projectId:string,operation:SavedBranchOperation,signal:AbortSignal){if(operation.phase!=='confirmed'||!['pending_repair','unregistered'].includes(operation.acceptedRoot?.status??''))throw Error('Only an explicitly pending confirmed baseline may be checked');return checkedBranchOperation(await apiJson<unknown>(`/p/${projectId}/branch-operations/${operation.operationId}/reconcile`,{method:'POST',json:{expectedPhase:'confirmed'},signal}),{operationId:operation.operationId,name:operation.branch,sourceCommit:operation.sourceCommit},projectId);}
