import {array,boolean,enum as enumSchema,int,literal,maxLength,minLength,minimum,nullable,object,regex,strictObject,string,tuple,union,uuid,type infer as Infer} from 'zod/mini';import {apiFetch,apiRetryAfterSeconds} from './api';

export const migrationFailureCategories=['source_rate_limited','source_unavailable','source_inaccessible','source_timeout','source_identity_changed','source_invalid','read_budget_exhausted','read_budget_unconfigured','owner_scope_changed','migration_unconfirmed'] as const;
export type MigrationFailureCategory=typeof migrationFailureCategories[number];
export class ConversationMigrationError extends Error{constructor(readonly category:MigrationFailureCategory,readonly status:number,readonly retryAfter:number|null){super('Conversation migration was not confirmed');}}
export function migrationFailureMessage(error:unknown):string{if(error instanceof ConversationMigrationError){const text:Record<MigrationFailureCategory,string>={source_rate_limited:'GitHub has limited this source request. Saved migration progress is preserved.',source_unavailable:'The GitHub source could not be read. Saved migration progress is preserved.',source_inaccessible:'The GitHub source is inaccessible. Saved progress is preserved; refresh before continuing.',source_identity_changed:'The GitHub source identity changed. Refresh the saved migration before continuing.',source_invalid:'The imported source cannot be captured through this GitHub migration path.',source_timeout:'The GitHub source read did not finish in time. Refresh saved progress before continuing.',read_budget_exhausted:'The repository read budget is exhausted. Saved migration progress is preserved.',read_budget_unconfigured:'The repository read budget is not configured. Saved migration progress is preserved.',owner_scope_changed:'Owner access or the imported source changed. Refresh before continuing.',migration_unconfirmed:'Migration progress was not confirmed. Refresh the saved operation before continuing.'};return text[error.category]+(error.retryAfter!==null?` Retry after ${error.retryAfter} seconds.`:'');}if(error instanceof DOMException&&(error.name==='TimeoutError'||error.name==='AbortError'))return 'This bounded migration action did not finish in time. Refresh saved progress before continuing.';return 'Migration progress was not confirmed. Refresh the saved operation before continuing.';}
export function migrationActionSignal(signal:AbortSignal,deadline:AbortSignal):AbortSignal{return AbortSignal.any([signal,deadline,AbortSignal.timeout(30000)]);}
export function migrationReadSignal(signal:AbortSignal,deadline?:AbortSignal):AbortSignal{return AbortSignal.any([signal,...(deadline?[deadline]:[]),AbortSignal.timeout(15000)]);}
async function migrationJson(path:string,init:RequestInit&{json?:unknown}):Promise<unknown>{const {json,...request}=init;const response=await apiFetch(`/api${path}`,{...request,...(json!==undefined?{body:JSON.stringify(json),headers:{'Content-Type':'application/json',...request.headers}}:{})});const value:unknown=await response.json().catch(()=>null);if(!response.ok){const named=value&&typeof value==='object'&&'category' in value?value.category:null;const category=migrationFailureCategories.find(item=>item===named)??'migration_unconfirmed';const header=apiRetryAfterSeconds(response.headers.get('Retry-After'));const bodyDelay=value&&typeof value==='object'&&'retryAfterSeconds' in value&&typeof value.retryAfterSeconds==='number'&&Number.isSafeInteger(value.retryAfterSeconds)&&value.retryAfterSeconds>=0&&value.retryAfterSeconds<=3600?value.retryAfterSeconds:null;const delay=header!==null&&header<=3600?header:bodyDelay;throw new ConversationMigrationError(category,response.status,delay);}return value;}

const id=string().check(minLength(1),maxLength(200),regex(/^[A-Za-z0-9_-]+$/)),count=int().check(minimum(0)),providerId=string().check(regex(/^[1-9][0-9]{0,19}$/)),hash=string().check(regex(/^[a-f0-9]{64}$/));
const githubUrl=string().check(maxLength(2048),regex(/^https:\/\/github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+(?:\/(?:issues|pull)\/[1-9][0-9]*(?:#issuecomment-[1-9][0-9]*)?)?\/?$/));
const exclusions=tuple([literal('inline-review-comments'),literal('timelines'),literal('discussions'),literal('reactions'),literal('attachments')]);
const scopeSchema=strictObject({operationId:id,projectId:string().check(regex(/^[a-z0-9]{12,16}$/)),incarnation:uuid(),ownerId:string().check(minLength(1),maxLength(256)),provider:literal('github'),repositoryId:providerId,repositoryNodeId:string().check(minLength(1),maxLength(256)),sourceUrl:githubUrl});
const snapshotSchema=strictObject({scope:scopeSchema,status:enumSchema(['pending','complete','incomplete']),revision:count,cursor:nullable(string().check(maxLength(8192))),issues:count,pullRequests:count,comments:count,missing:count,capturedPages:count,scopeOfCompletion:literal('supplied-issues-and-issue-comments-pagination-only'),published:literal(false)});
const publicationSchema=strictObject({operationId:id,manifestHash:hash,revision:count,phase:enumSchema(['issues','comments','complete']),issueCursor:union([providerId,literal('0')]),commentCursor:union([providerId,literal('0')]),nativeIssues:count,nativeComments:count,archivedPullRequests:count,archivedPullRequestComments:count,sourceMissing:count,excluded:exclusions,atomicSourceSnapshot:literal(false)});
const stateSchema=strictObject({snapshot:snapshotSchema,publication:nullable(publicationSchema)}),collectionSchema=strictObject({operations:array(stateSchema).check(maxLength(32)),truncated:boolean()});
const manifestSchema=strictObject({hash,revision:count,scope:scopeSchema,status:enumSchema(['pending','complete','incomplete']),counts:strictObject({issues:count,pullRequests:count,comments:count,missing:count}),scopeOfCompletion:literal('supplied-issues-and-issue-comments-pagination-only'),excluded:exclusions,atomicSourceSnapshot:literal(false),published:literal(false)});
const actor=object({login:string().check(minLength(1),maxLength(100))}),previewBase={providerId,sourceUrl:githubUrl,actor,body:string().check(maxLength(2000)),createdAt:string(),updatedAt:string(),identity:literal('external-unclaimed'),nativeUserId:literal(null)};
const previewIssue=object({...previewBase,kind:enumSchema(['issue','pull_request']),title:string().check(maxLength(1024))}),previewComment=object({...previewBase,parentKind:enumSchema(['issue','pull_request'])});
const manifestReportSchema=strictObject({manifest:manifestSchema,missing:array(object({kind:string().check(maxLength(100)),sourceId:string().check(maxLength(200)),reason:string().check(maxLength(1000))})).check(maxLength(20)),issuePreview:array(previewIssue).check(maxLength(10)),commentPreview:array(previewComment).check(maxLength(10))});
export type ConversationMigrationState=Infer<typeof stateSchema>;export type ConversationMigrationManifest=Infer<typeof manifestReportSchema>;
function scopeMatches(value:Infer<typeof scopeSchema>,projectId:string,operationId?:string){if(value.projectId!==projectId||(operationId&&value.operationId!==operationId))throw Error('Saved conversation migration scope changed');}
export function checkedMigrationState(value:unknown,projectId:string,operationId?:string):ConversationMigrationState{const state=stateSchema.parse(value);scopeMatches(state.snapshot.scope,projectId,operationId);const receipt=state.publication;if(receipt&&(receipt.operationId!==state.snapshot.scope.operationId||receipt.revision!==state.snapshot.revision||receipt.nativeIssues>state.snapshot.issues||receipt.archivedPullRequests>state.snapshot.pullRequests||receipt.nativeComments+receipt.archivedPullRequestComments>state.snapshot.comments||receipt.sourceMissing!==state.snapshot.missing||(receipt.phase==='complete'&&(receipt.nativeIssues!==state.snapshot.issues||receipt.archivedPullRequests!==state.snapshot.pullRequests||receipt.nativeComments+receipt.archivedPullRequestComments!==state.snapshot.comments))))throw Error('Native publication progress did not match captured scope');return state;}
export function checkedMigrationManifest(value:unknown,state:ConversationMigrationState):ConversationMigrationManifest{const report=manifestReportSchema.parse(value),snapshot=state.snapshot;scopeMatches(report.manifest.scope,snapshot.scope.projectId,snapshot.scope.operationId);if(JSON.stringify(report.manifest.scope)!==JSON.stringify(snapshot.scope)||report.manifest.revision!==snapshot.revision||report.manifest.status!==snapshot.status||report.manifest.counts.issues!==snapshot.issues||report.manifest.counts.pullRequests!==snapshot.pullRequests||report.manifest.counts.comments!==snapshot.comments||report.manifest.counts.missing!==snapshot.missing)throw Error('Captured manifest changed; refresh before publication');const sourcePath=new URL(snapshot.scope.sourceUrl).pathname.replace(/\/$/,'');for(const origin of [...report.issuePreview,...report.commentPreview])if(!new URL(origin.sourceUrl).pathname.startsWith(`${sourcePath}/issues/`)&&!new URL(origin.sourceUrl).pathname.startsWith(`${sourcePath}/pull/`))throw Error('Preview origin differs from the captured repository');return report;}
export async function readConversationMigrations(projectId:string,signal:AbortSignal){const value=collectionSchema.parse(await migrationJson(`/p/${projectId}/conversation-migrations`,{signal}));const operations=value.operations.map(state=>checkedMigrationState(state,projectId));if(new Set(operations.map(state=>state.snapshot.scope.operationId)).size!==operations.length)throw Error('Migration inventory repeated an identity');return {...value,operations};}
export async function readConversationMigration(projectId:string,operationId:string,signal:AbortSignal){id.parse(operationId);return checkedMigrationState(await migrationJson(`/p/${projectId}/conversation-migrations/${operationId}`,{signal}),projectId,operationId);}
export async function beginConversationMigration(projectId:string,operationId:string,signal:AbortSignal){id.parse(operationId);const snapshot=snapshotSchema.parse(await migrationJson(`/p/${projectId}/conversation-migrations`,{method:'POST',json:{operationId},signal}));scopeMatches(snapshot.scope,projectId,operationId);return snapshot;}
export async function captureConversationMigration(projectId:string,state:ConversationMigrationState,signal:AbortSignal){const operationId=state.snapshot.scope.operationId;return checkedMigrationState(await migrationJson(`/p/${projectId}/conversation-migrations/${operationId}/capture`,{method:'POST',json:{expectedRevision:state.snapshot.revision},signal}),projectId,operationId);}
export async function readConversationManifest(projectId:string,state:ConversationMigrationState,signal:AbortSignal){return checkedMigrationManifest(await migrationJson(`/p/${projectId}/conversation-migrations/${state.snapshot.scope.operationId}/manifest`,{signal}),state);}
export interface MigrationPublishIntent{scope:string;eventId:string}
export function migrationPublishIntent(previous:MigrationPublishIntent|null,state:ConversationMigrationState,manifest:ConversationMigrationManifest):MigrationPublishIntent{const scope=JSON.stringify([state.snapshot.scope.projectId,state.snapshot.scope.operationId,manifest.manifest.hash,manifest.manifest.revision,state.publication?.phase??null,state.publication?.issueCursor??null,state.publication?.commentCursor??null]);return previous?.scope===scope?previous:{scope,eventId:crypto.randomUUID()};}
export async function publishConversationManifest(projectId:string,manifest:ConversationMigrationManifest,eventId:string,signal:AbortSignal){uuid().parse(eventId);const result=publicationSchema.parse(await migrationJson(`/p/${projectId}/conversation-migrations/${manifest.manifest.scope.operationId}/publish`,{method:'POST',json:{eventId,expectedRevision:manifest.manifest.revision,manifestHash:manifest.manifest.hash},signal}));if(result.operationId!==manifest.manifest.scope.operationId||result.manifestHash!==manifest.manifest.hash||result.revision!==manifest.manifest.revision)throw Error('Native publication was not confirmed');return result;}
