import {array,boolean,enum as enumSchema,int,maxLength,minLength,maximum,minimum,nullable,object,optional,regex,strictObject,string,uuid,type infer as Infer} from 'zod/mini';
import {apiJson} from './api';
const principal=string().check(minLength(1),maxLength(256),regex(/^[^\x00-\x1f\x7f]+$/));
const identity=string().check(minLength(1),maxLength(200),regex(/^[A-Za-z0-9_-]+$/));
const version=int().check(minimum(0)),sha=string().check(regex(/^[a-f0-9]{40}$/));
const policySchema=strictObject({requiredApprovals:int().check(minimum(0),maximum(10)),allowAuthorApproval:boolean()});
const policyStateSchema=strictObject({version,policy:policySchema});
const grantSchema=strictObject({userId:principal,version,enabled:boolean()});
const settingsSchema=strictObject({policy:policyStateSchema,grants:array(grantSchema).check(maxLength(100)),truncated:boolean()});
const scopeSchema=strictObject({candidateId:identity,commit:sha,tree:sha,base:nullable(sha),verificationPolicyVersion:version,reviewPolicyVersion:version,authorIds:array(principal).check(maxLength(100))});
const decisionSchema=enumSchema(['approve','request_changes','withdraw']);
const reviewSchema=strictObject({eventId:identity,scope:scopeSchema,reviewerId:principal,grantVersion:version,decision:decisionSchema,note:string().check(maxLength(5000)),at:int().check(minimum(0))});
const gateSchema=strictObject({passed:boolean(),required:int().check(minimum(0),maximum(10)),approvedBy:array(principal).check(maxLength(100)),blockingReviewers:array(principal).check(maxLength(100)),reason:optional(string().check(maxLength(500)))});
const reportSchema=strictObject({scope:scopeSchema,policy:policySchema,gate:gateSchema,history:strictObject({reviews:array(reviewSchema).check(maxLength(100)),truncated:boolean()}),viewerGrant:nullable(grantSchema),canReview:boolean()});
export type DelegatedSettings=Infer<typeof settingsSchema>;
export type DelegatedReport=Infer<typeof reportSchema>;
export type DelegatedDecision=Infer<typeof decisionSchema>;
export type ReviewPolicy=Infer<typeof policySchema>;
export interface ReviewIntent {scope:string;eventId:string}
export function reviewIntent(previous:ReviewIntent|null,scope:string):ReviewIntent{return previous?.scope===scope?previous:{scope,eventId:crypto.randomUUID()};}
export function checkedDelegatedSettings(value:unknown):DelegatedSettings{const parsed=settingsSchema.parse(value);if(new Set(parsed.grants.map(grant=>grant.userId)).size!==parsed.grants.length)throw Error('Reviewer grants repeated an identity');return parsed;}
export function checkedDelegatedReport(value:unknown,expected:{candidateId:string;commit:string;base:string|null;verificationPolicyVersion:number;tree?:string}):DelegatedReport{const report=reportSchema.parse(value);if(report.scope.candidateId!==expected.candidateId||report.scope.commit!==expected.commit||report.scope.base!==expected.base||report.scope.verificationPolicyVersion!==expected.verificationPolicyVersion||(expected.tree&&report.scope.tree!==expected.tree)||report.gate.required!==report.policy.requiredApprovals||report.canReview!==Boolean(report.viewerGrant?.enabled)||new Set(report.gate.approvedBy).size!==report.gate.approvedBy.length||new Set(report.gate.blockingReviewers).size!==report.gate.blockingReviewers.length||(report.gate.passed?(report.gate.approvedBy.length<report.gate.required||report.gate.blockingReviewers.length!==0||Boolean(report.gate.reason)):(report.gate.approvedBy.length>=report.gate.required&&report.gate.blockingReviewers.length===0&&!report.gate.reason)))throw Error('Delegated review scope was not confirmed');return report;}
export async function readDelegatedSettings(projectId:string,signal:AbortSignal){return checkedDelegatedSettings(await apiJson<unknown>(`/p/${projectId}/review-settings`,{signal}));}
export async function saveReviewPolicy(projectId:string,value:{eventId:string;expectedVersion:number;policy:ReviewPolicy},signal:AbortSignal){uuid().parse(value.eventId);const result=policyStateSchema.parse(await apiJson<unknown>(`/p/${projectId}/review-policy`,{method:'PUT',json:value,signal}));if(result.version!==value.expectedVersion+1||JSON.stringify(result.policy)!==JSON.stringify(value.policy))throw Error('Review policy save was not confirmed');return result;}
export async function saveReviewGrant(projectId:string,value:{eventId:string;userId:string;expectedVersion:number;enabled:boolean},signal:AbortSignal){uuid().parse(value.eventId);const result=grantSchema.parse(await apiJson<unknown>(`/p/${projectId}/review-grants`,{method:'POST',json:value,signal}));if(result.userId!==value.userId||result.enabled!==value.enabled||result.version!==value.expectedVersion+1)throw Error('Reviewer grant save was not confirmed');return result;}
export async function saveDelegatedReview(projectId:string,candidateId:string,value:{eventId:string;expectedCommit:string;grantVersion:number;decision:DelegatedDecision;note:string},signal:AbortSignal){uuid().parse(value.eventId);const result=reviewSchema.parse(await apiJson<unknown>(`/p/${projectId}/candidates/${candidateId}/delegated-reviews`,{method:'POST',json:value,signal}));if(result.eventId!==value.eventId||result.scope.candidateId!==candidateId||result.scope.commit!==value.expectedCommit||result.grantVersion!==value.grantVersion||result.decision!==value.decision||result.note!==value.note)throw Error('Review save was not confirmed');return result;}
export function reviewHistoryLabel(report:DelegatedReport,index:number):string{const row=report.history.reviews[index];if(!row)return 'Unavailable';const latest=report.history.reviews.find(review=>review.reviewerId===row.reviewerId);if(latest?.eventId!==row.eventId||row.scope.commit!==report.scope.commit)return 'Historical';if(row.decision==='withdraw')return 'Withdrawn';if(row.decision==='approve'&&report.gate.approvedBy.includes(row.reviewerId))return 'Counts toward required approvals';if(row.decision==='request_changes'&&report.gate.blockingReviewers.includes(row.reviewerId))return 'Changes requested';return 'No longer counts';}
export const reviewMembersSchema=array(object({user_id:principal,role:string(),label:nullable(string()),added_at:string()})).check(maxLength(100));
