import {z} from 'zod';
const project=z.string().regex(/^[a-z0-9]{12,16}$/),issue=z.number().int().positive().max(9999999),revision=z.number().int().nonnegative().safe(),digest=z.string().regex(/^[a-f0-9]{64}$/);
export const issueTransferRequestSchema=z.object({destinationProjectId:project,expectedRevision:revision,requestId:z.uuid(),confirmed:z.literal(true),expectedManifestDigest:digest,expectedDestinationIncarnation:z.uuid()}).strict();
export type IssueTransferRequest=z.infer<typeof issueTransferRequestSchema>;
export const issueTransferPreviewSchema=z.object({manifestDigest:digest,source:z.object({projectId:project,incarnation:z.uuid(),number:issue,stateRevision:revision}),destination:z.object({projectId:project,incarnation:z.uuid(),audience:z.literal('repository-members')}),audienceVersion:z.literal('repository-members-v1'),manifest:z.object({issue:z.object({title:z.string().max(200),body:z.string().max(20000)}),comments:z.array(z.unknown()).max(1000),features:z.unknown(),attachments:z.array(z.object({name:z.string().max(255),size:z.number().int().nonnegative().max(5*1024*1024)})).max(10)})});
export type IssueTransferPreview=z.infer<typeof issueTransferPreviewSchema>;
const cancellationStatusSchema=z.object({requestId:z.uuid(),cancelId:z.uuid(),cancelled:z.literal(true),sourceUnlocked:z.literal(true),physicalCleanup:z.enum(['pending','confirmed']),canReplayCancellation:z.boolean()});
export const issueTransferReceiptSchema=z.object({requestId:z.uuid(),manifestDigest:digest,audienceVersion:z.literal('repository-members-v1'),phase:z.enum(['locked','frozen','reserved','copying','ready','active','completed','cancelling','cancelled']),cancelled:z.boolean().optional(),cancelId:z.uuid().optional(),cancellationRefused:z.literal('destination-active').optional(),cancellationReceipt:cancellationStatusSchema.optional(),source:z.object({projectId:project,number:issue}),destination:z.object({projectId:project,number:issue.optional()}),audience:z.literal('repository-members'),completed:z.boolean()}).refine(value=>value.completed===(value.phase==='completed')&&(value.phase!=='cancelled'||value.cancelled===true));
export type IssueTransferReceipt=z.infer<typeof issueTransferReceiptSchema>;
export function transferRequest(preview:IssueTransferPreview,requestId:string):IssueTransferRequest{return issueTransferRequestSchema.parse({destinationProjectId:preview.destination.projectId,expectedRevision:preview.source.stateRevision,requestId,confirmed:true,expectedManifestDigest:preview.manifestDigest,expectedDestinationIncarnation:preview.destination.incarnation});}
export function checkedTransferPreview(raw:unknown,projectId:string,number:number,destinationProjectId:string){if(new TextEncoder().encode(JSON.stringify(raw)).length>2*1024*1024)throw Error('Transfer preview exceeds capacity');const preview=issueTransferPreviewSchema.parse(raw);if(preview.source.projectId!==projectId||preview.source.number!==number||preview.destination.projectId!==destinationProjectId||projectId===destinationProjectId)throw Error('Transfer preview belongs to another issue or destination');return preview;}
export function checkedTransferReceipt(raw:unknown,projectId:string,number:number,request:IssueTransferRequest){const receipt=issueTransferReceiptSchema.parse(raw);if(receipt.requestId!==request.requestId||receipt.manifestDigest!==request.expectedManifestDigest||receipt.audienceVersion!=='repository-members-v1'||receipt.source.projectId!==projectId||receipt.source.number!==number||receipt.destination.projectId!==request.destinationProjectId)throw Error('Original transfer receipt differs');return receipt;}
export interface TransferIntentScope{identity:string;projectId:string;number:number}
interface Storage{getItem(key:string):string|null;setItem(key:string,value:string):void}
const key=(scope:TransferIntentScope)=>`flaregit.issue-draft.${JSON.stringify([scope.identity,scope.projectId,scope.number,'transfer'])}`;
export function recoverTransferIntent(storage:Storage,scope:TransferIntentScope){const raw=storage.getItem(key(scope));if(raw===null)return null;if(raw.length>2000)throw Error('Saved transfer exceeds capacity');return issueTransferRequestSchema.parse(JSON.parse(raw));}
export function persistTransferIntent(storage:Storage,scope:TransferIntentScope,request:IssueTransferRequest){const prior=recoverTransferIntent(storage,scope),value=issueTransferRequestSchema.parse(request);if(prior&&JSON.stringify(prior)!==JSON.stringify(value))throw Error('Original transfer request cannot change');const serialized=JSON.stringify(value);storage.setItem(key(scope),serialized);if(storage.getItem(key(scope))!==serialized)throw Error('Browser recovery is unavailable');}

export const issueTransferCancelSchema=z.object({requestId:z.uuid(),cancelId:z.uuid(),expectedManifestDigest:digest,expectedDestinationIncarnation:z.uuid(),confirmed:z.literal(true),originalRequest:issueTransferRequestSchema.optional()}).strict().refine(value=>value.requestId!==value.cancelId&&(!value.originalRequest||value.originalRequest.requestId===value.requestId&&value.originalRequest.expectedManifestDigest===value.expectedManifestDigest&&value.originalRequest.expectedDestinationIncarnation===value.expectedDestinationIncarnation));
export type IssueTransferCancellation=z.infer<typeof issueTransferCancelSchema>;
const cancellationReceipt=z.object({requestId:z.uuid(),cancelId:z.uuid(),cancelled:z.literal(true),replayed:z.boolean(),sourceUnlocked:z.literal(true),physicalCleanup:z.enum(['pending','confirmed'])});
const cancellationConflict=z.object({requestId:z.uuid(),cancelId:z.uuid(),cancelled:z.literal(false),reason:z.literal('destination-active'),phase:z.literal('active'),sourceUnlocked:z.literal(false)});
export function transferCancellation(original:IssueTransferRequest,cancelId:string){return issueTransferCancelSchema.parse({requestId:original.requestId,cancelId,expectedManifestDigest:original.expectedManifestDigest,expectedDestinationIncarnation:original.expectedDestinationIncarnation,confirmed:true,originalRequest:original});}
export function checkedTransferCancellation(raw:unknown,request:IssueTransferCancellation){const result=z.union([cancellationReceipt,cancellationConflict]).parse(raw);if(result.requestId!==request.requestId||result.cancelId!==request.cancelId)throw Error('Original cancellation receipt differs');return result;}
const cancelKey=(scope:TransferIntentScope)=>`flaregit.issue-draft.${JSON.stringify([scope.identity,scope.projectId,scope.number,'transfer-cancel'])}`;
export function recoverTransferCancellation(storage:Storage,scope:TransferIntentScope){const raw=storage.getItem(cancelKey(scope));if(raw===null)return null;if(raw.length>2000)throw Error('Saved cancellation exceeds capacity');const cancel=issueTransferCancelSchema.parse(JSON.parse(raw)),original=recoverTransferIntent(storage,scope);if(!original||cancel.requestId!==original.requestId||cancel.expectedManifestDigest!==original.expectedManifestDigest||cancel.expectedDestinationIncarnation!==original.expectedDestinationIncarnation)throw Error('Saved cancellation original transfer differs');return cancel;}
export function persistTransferCancellation(storage:Storage,scope:TransferIntentScope,cancel:IssueTransferCancellation){const history=recoverCancelledCleanup(storage,scope);if(history.length>=20&&!history.some(entry=>entry.request.cancelId===cancel.cancelId))throw Error('Saved cancellation cleanup capacity reached');const original=recoverTransferIntent(storage,scope);if(!original||cancel.requestId!==original.requestId||cancel.expectedManifestDigest!==original.expectedManifestDigest||cancel.expectedDestinationIncarnation!==original.expectedDestinationIncarnation||cancel.originalRequest&&JSON.stringify(cancel.originalRequest)!==JSON.stringify(original))throw Error('Cancellation must preserve the original transfer');const prior=recoverTransferCancellation(storage,scope);if(prior&&JSON.stringify(prior)!==JSON.stringify(cancel))throw Error('Original cancellation cannot change');const serialized=JSON.stringify(cancel);storage.setItem(cancelKey(scope),serialized);if(storage.getItem(cancelKey(scope))!==serialized)throw Error('Browser cancellation recovery is unavailable');}
export function clearCancelledTransfer(storage:Storage&{removeItem(key:string):void},scope:TransferIntentScope,request:IssueTransferCancellation,rawReceipt:unknown){const receipt=checkedTransferCancellation(rawReceipt,request);if(!receipt.cancelled)throw Error('Active destination transfer cannot be cancelled');saveCancelledCleanup(storage,scope,request,receipt);storage.removeItem(cancelKey(scope));if(storage.getItem(cancelKey(scope))!==null)throw Error('Saved cancellation could not be cleared');storage.removeItem(key(scope));if(storage.getItem(key(scope))!==null)throw Error('Original transfer could not be cleared');return receipt;}

const cleanupKey=(scope:TransferIntentScope)=>`flaregit.issue-draft.${JSON.stringify([scope.identity,scope.projectId,scope.number,'transfer-cleanup'])}`;
const cleanupSchema=z.array(z.object({request:issueTransferCancelSchema,receipt:cancellationReceipt}).strict()).max(20);
export type CancelledTransferCleanup=z.infer<typeof cleanupSchema>[number];
export function recoverCancelledCleanup(storage:Storage,scope:TransferIntentScope){const raw=storage.getItem(cleanupKey(scope));if(raw===null)return [] as CancelledTransferCleanup[];if(raw.length>20000)throw Error('Saved cleanup recovery exceeds capacity');const entries=cleanupSchema.parse(JSON.parse(raw));if(new Set(entries.map(entry=>entry.request.cancelId)).size!==entries.length)throw Error('Duplicate saved cleanup identity');for(const entry of entries)checkedTransferCancellation(entry.receipt,entry.request);return entries;}
export function saveCancelledCleanup(storage:Storage,scope:TransferIntentScope,request:IssueTransferCancellation,raw:unknown){const receipt=checkedTransferCancellation(raw,request);if(!receipt.cancelled)throw Error('Cancellation must be confirmed before recording cleanup');const entries=recoverCancelledCleanup(storage,scope),old=entries.find(entry=>entry.request.cancelId===request.cancelId);if(old&&JSON.stringify(old.request)!==JSON.stringify(request))throw Error('Original cleanup request cannot change');const next=entries.filter(entry=>entry.request.cancelId!==request.cancelId);if(receipt.physicalCleanup==='pending')next.push({request,receipt});const serialized=JSON.stringify(cleanupSchema.parse(next));storage.setItem(cleanupKey(scope),serialized);if(storage.getItem(cleanupKey(scope))!==serialized)throw Error('Saved cleanup recovery is unavailable');return next;}

/** A server-discovered cancellation reuses its original UUID; never creates a replacement after another client cancelled. */
export function cancellationFromTransferStatus(original:IssueTransferRequest,receipt:IssueTransferReceipt){if(receipt.requestId!==original.requestId||receipt.manifestDigest!==original.expectedManifestDigest)throw Error('Cancellation discovery differs from original transfer');if(!receipt.cancelId||!['cancelling','cancelled','active'].includes(receipt.phase)||receipt.phase==='active'&&receipt.cancellationRefused!=='destination-active')return null;return{request:transferCancellation(original,receipt.cancelId),refused:receipt.phase==='active'&&receipt.cancellationRefused==='destination-active'};}

export const issueTransferPendingSchema=z.object({originalRequest:issueTransferRequestSchema,canResumeOriginal:z.boolean(),canCancel:z.literal(true),canFinalizeActive:z.boolean().optional(),activeDestinationNumber:issue.optional()}).strict();
export type IssueTransferPendingRecovery=z.infer<typeof issueTransferPendingSchema>;
export function adoptPendingTransfer(storage:Storage,scope:TransferIntentScope,raw:unknown){const pending=issueTransferPendingSchema.parse(raw);if(pending.originalRequest.destinationProjectId===scope.projectId)throw Error('Pending transfer destination differs');persistTransferIntent(storage,scope,pending.originalRequest);return pending;}

const statusCleanupKey=(scope:TransferIntentScope)=>`flaregit.issue-draft.${JSON.stringify([scope.identity,scope.projectId,scope.number,'transfer-cleanup-status'])}`;
const statusCleanupSchema=z.array(z.object({originalRequest:issueTransferRequestSchema,cancellationReceipt:cancellationStatusSchema}).strict()).max(20);
export type ReadonlyTransferCleanup=z.infer<typeof statusCleanupSchema>[number];
export function recoverReadonlyCleanup(storage:Storage,scope:TransferIntentScope){const raw=storage.getItem(statusCleanupKey(scope));if(raw===null)return [] as ReadonlyTransferCleanup[];if(raw.length>20000)throw Error('Readonly cleanup history exceeds capacity');const entries=statusCleanupSchema.parse(JSON.parse(raw));for(const entry of entries)if(entry.originalRequest.requestId!==entry.cancellationReceipt.requestId)throw Error('Readonly cleanup identity changed');return entries;}
export function updateReadonlyCleanup(storage:Storage,scope:TransferIntentScope,originalRequest:IssueTransferRequest,raw:unknown){const status=checkedTransferReceipt(raw,scope.projectId,scope.number,originalRequest),proof=status.cancellationReceipt;if(status.phase!=='cancelled'||status.cancelled!==true||!proof||proof.requestId!==originalRequest.requestId||proof.cancelId!==status.cancelId)throw Error('Terminal source unlock was not proven');const entries=recoverReadonlyCleanup(storage,scope),next=entries.filter(entry=>entry.originalRequest.requestId!==originalRequest.requestId);if(proof.physicalCleanup==='pending')next.push({originalRequest,cancellationReceipt:proof});const serialized=JSON.stringify(statusCleanupSchema.parse(next));storage.setItem(statusCleanupKey(scope),serialized);if(storage.getItem(statusCleanupKey(scope))!==serialized)throw Error('Readonly cleanup recovery unavailable');return next;}
/** A current authenticated terminal projection can reconcile another actor's cancellation without sending that actor's mutation. */
export function reconcileCancelledTransfer(storage:Storage&{removeItem(key:string):void},scope:TransferIntentScope,originalRequest:IssueTransferRequest,raw:unknown){const current=recoverTransferIntent(storage,scope);if(!current||JSON.stringify(current)!==JSON.stringify(originalRequest))throw Error('Only the exact saved transfer may be reconciled');const status=checkedTransferReceipt(raw,scope.projectId,scope.number,originalRequest),proof=status.cancellationReceipt,owned=recoverTransferCancellation(storage,scope);if(status.phase!=='cancelled'||status.cancelled!==true||!proof||proof.requestId!==originalRequest.requestId||proof.cancelId!==status.cancelId)throw Error('Terminal source unlock was not proven');if(proof.canReplayCancellation&&owned?.cancelId===proof.cancelId)saveCancelledCleanup(storage,scope,owned,{requestId:proof.requestId,cancelId:proof.cancelId,cancelled:true,replayed:true,sourceUnlocked:true,physicalCleanup:proof.physicalCleanup});else updateReadonlyCleanup(storage,scope,originalRequest,raw);storage.removeItem(cancelKey(scope));if(storage.getItem(cancelKey(scope))!==null)throw Error('Saved cancellation could not be cleared');storage.removeItem(key(scope));if(storage.getItem(key(scope))!==null)throw Error('Saved old transfer could not be cleared');}
export const issueTransferFinalizeSchema=z.object({requestId:z.uuid(),finalizeId:z.uuid(),expectedManifestDigest:digest,expectedDestinationIncarnation:z.uuid(),destinationNumber:issue,confirmed:z.literal(true)}).strict().refine(value=>value.requestId!==value.finalizeId);
export type IssueTransferFinalization=z.infer<typeof issueTransferFinalizeSchema>;
export function transferFinalization(original:IssueTransferRequest,destinationNumber:number,finalizeId:string){return issueTransferFinalizeSchema.parse({requestId:original.requestId,finalizeId,expectedManifestDigest:original.expectedManifestDigest,expectedDestinationIncarnation:original.expectedDestinationIncarnation,destinationNumber,confirmed:true});}
const finalizeKey=(scope:TransferIntentScope)=>`flaregit.issue-draft.${JSON.stringify([scope.identity,scope.projectId,scope.number,'transfer-finalize'])}`;
export function recoverTransferFinalization(storage:Storage,scope:TransferIntentScope){const raw=storage.getItem(finalizeKey(scope));if(raw===null)return null;if(raw.length>2000)throw Error('Saved finalization exceeds capacity');const request=issueTransferFinalizeSchema.parse(JSON.parse(raw)),original=recoverTransferIntent(storage,scope);if(!original||request.requestId!==original.requestId||request.expectedManifestDigest!==original.expectedManifestDigest||request.expectedDestinationIncarnation!==original.expectedDestinationIncarnation)throw Error('Saved finalization original transfer differs');return request;}
export function persistTransferFinalization(storage:Storage,scope:TransferIntentScope,request:IssueTransferFinalization){const original=recoverTransferIntent(storage,scope);if(!original||JSON.stringify(transferFinalization(original,request.destinationNumber,request.finalizeId))!==JSON.stringify(issueTransferFinalizeSchema.parse(request)))throw Error('Finalization must preserve the original transfer');const prior=recoverTransferFinalization(storage,scope);if(prior&&JSON.stringify(prior)!==JSON.stringify(request))throw Error('Original finalization cannot change');const value=JSON.stringify(request);storage.setItem(finalizeKey(scope),value);if(storage.getItem(finalizeKey(scope))!==value)throw Error('Browser finalization recovery is unavailable');}
export function checkedTransferFinalization(raw:unknown,scope:Pick<TransferIntentScope,'projectId'|'number'>,original:IssueTransferRequest,request:IssueTransferFinalization){const receipt=checkedTransferReceipt(raw,scope.projectId,scope.number,original),proof=z.object({finalizeId:z.uuid(),actorId:z.string().min(1).max(256),completed:z.boolean(),replayed:z.boolean()}).parse((raw as {finalization?:unknown})?.finalization);if(request.requestId!==original.requestId||request.expectedManifestDigest!==original.expectedManifestDigest||request.expectedDestinationIncarnation!==original.expectedDestinationIncarnation||receipt.destination.number!==request.destinationNumber||proof.finalizeId!==request.finalizeId||proof.completed!==receipt.completed)throw Error('Original finalization receipt differs');return{...receipt,finalization:proof};}
