import {z} from 'zod';
import {issueTransferMappingSchema,type IssueTransferMapping} from '../server/issue-feature-store';
const id=z.number().int().positive().safe(),text=z.string().max(256),label=z.string().min(1).max(50),pairs=z.array(z.object({source:text.min(1),destination:text.min(1)})).max(50),labels=z.array(z.object({source:label,destination:label,targetKind:z.enum(['existing','create'])})).max(50);
const milestone=z.object({id,title:z.string().max(100),dueDate:z.string().optional()}).nullable();
export const mappingOriginSchema=z.object({version:z.literal(1),labels:z.array(label).max(50),assignees:z.array(text.min(1)).max(20),milestone,relations:z.array(z.object({kind:z.enum(['duplicate-of','sub-issue-of']),from:id,to:id})).max(10000)});
export const mappingPrincipalPageSchema=z.object({complete:z.boolean(),nextCursor:z.string().min(1).max(4096).nullable(),generation:z.string().min(1).max(256)}).strict().refine(value=>value.complete===(value.nextCursor===null));
export const mappingPreviewSchema=z.object({canMap:z.literal(true),origin:mappingOriginSchema,originDigest:z.string().regex(/^[a-f0-9]{64}$/),featureRevision:z.number().int().nonnegative().safe(),principalGeneration:z.string().min(1).max(256),principalPage:mappingPrincipalPageSchema,currentTriage:z.object({labels:z.array(label).max(50),assignees:z.array(text.min(1)).max(20),milestone:id.nullable()}),effects:z.object({labels:z.literal('add-and-retain-existing'),assignees:z.literal('add-and-retain-existing'),milestone:z.literal('replace-only-when-selected')}),mappingAvailability:z.object({labels:z.array(z.object({source:label,destination:label,targetKind:z.enum(['existing','create']),available:z.boolean()})).max(50),assignees:z.array(z.object({source:text.min(1),destination:text.min(1),available:z.boolean()})).max(20),milestone:z.object({id,available:z.boolean()}).nullable()}),catalog:z.object({labels:z.array(label).max(50000),milestones:z.array(z.object({id,title:z.string().max(100)})).max(1000),principals:z.array(text.min(1)).max(10000)}),applied:z.object({labels,assignees:pairs,milestone:id.nullable()}),unmapped:z.object({labels:z.array(label).max(50),assignees:z.array(text.min(1)).max(20),milestone,relations:z.array(z.unknown()).max(10000)})});
export type TransferMappingPreview=z.infer<typeof mappingPreviewSchema>;
export function checkedMappingPreview(raw:unknown){if(new TextEncoder().encode(JSON.stringify(raw)).length>4*1024*1024)throw Error('Mapping preview exceeds capacity');const preview=mappingPreviewSchema.parse(raw);if(preview.principalPage.generation!==preview.principalGeneration)throw Error('Principal page generation differs from preview');return preview;}
export function createMappingRequest(preview:TransferMappingPreview,choices:Pick<IssueTransferMapping,'labels'|'assignees'|'milestone'>,requestId:string){const request=issueTransferMappingSchema.parse({requestId,confirmed:true,originDigest:preview.originDigest,expectedRevision:preview.featureRevision,principalGeneration:preview.principalGeneration,...choices});if(request.labels.some(pair=>!preview.origin.labels.includes(pair.source)||pair.targetKind==='existing'&&!preview.catalog.labels.includes(pair.destination))||request.assignees.some(pair=>!preview.origin.assignees.includes(pair.source)||!preview.catalog.principals.includes(pair.destination))||request.milestone!==null&&(!preview.origin.milestone||!preview.catalog.milestones.some(value=>value.id===request.milestone)))throw Error('Mapping must select retained source references and current destination entries');return request;}
export function checkedMappingReceipt(raw:unknown,request:IssueTransferMapping){const result=z.object({requestId:z.uuid(),featureRevision:z.number().int().nonnegative().safe()}).parse(raw);if(result.requestId!==request.requestId||result.featureRevision<=request.expectedRevision)throw Error('Original mapping receipt differs');return result;}
export interface MappingScope{identity:string;projectId:string;number:number}
interface Storage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
const key=(scope:MappingScope)=>`flaregit.issue-draft.${JSON.stringify([scope.identity,scope.projectId,scope.number,'transfer-mapping'])}`;
export function recoverMapping(storage:Storage,scope:MappingScope){const raw=storage.getItem(key(scope));if(raw===null)return null;if(raw.length>128*1024)throw Error('Saved mapping exceeds capacity');return issueTransferMappingSchema.parse(JSON.parse(raw));}
export function persistMapping(storage:Storage,scope:MappingScope,request:IssueTransferMapping){const value=issueTransferMappingSchema.parse(request),prior=recoverMapping(storage,scope);if(prior&&JSON.stringify(prior)!==JSON.stringify(value))throw Error('Original mapping request cannot change');const serialized=JSON.stringify(value);storage.setItem(key(scope),serialized);if(storage.getItem(key(scope))!==serialized)throw Error('Browser mapping recovery is unavailable');}
export function clearConfirmedMapping(storage:Storage,scope:MappingScope,request:IssueTransferMapping,raw:unknown){checkedMappingReceipt(raw,request);const original=recoverMapping(storage,scope);if(!original||JSON.stringify(original)!==JSON.stringify(request))throw Error('Saved original mapping differs');storage.removeItem(key(scope));if(storage.getItem(key(scope))!==null)throw Error('Saved mapping receipt could not be cleared');}

const compactPrincipalPageSchema=z.object({canMap:z.literal(true),originDigest:z.string().regex(/^[a-f0-9]{64}$/),featureRevision:z.number().int().nonnegative().safe(),principalGeneration:z.string().min(1).max(256),catalog:z.object({principals:z.array(text.min(1)).max(50)}).strict(),principalPage:mappingPrincipalPageSchema}).strict();
/** Pages only extend the same frozen destination proof; append keeps selected UID indices stable. */
export function mergeMappingPrincipalPage(preview:TransferMappingPreview,raw:unknown){if(preview.principalPage.complete||preview.principalPage.nextCursor===null)throw Error('Principal roster is already complete');const page=compactPrincipalPageSchema.parse(raw);if(page.originDigest!==preview.originDigest||page.featureRevision!==preview.featureRevision||page.principalGeneration!==preview.principalGeneration||page.principalPage.generation!==preview.principalGeneration)throw Error('Destination roster or mapping preview changed; reload before selecting new values');if(page.principalPage.nextCursor===preview.principalPage.nextCursor)throw Error('Principal cursor did not advance');const principals=[...new Set([...preview.catalog.principals,...page.catalog.principals])];if(principals.length>10000)throw Error('Loaded principal catalog exceeds supported capacity; no complete roster is claimed');return{...preview,catalog:{...preview.catalog,principals},principalPage:page.principalPage};}
