import {z} from 'zod';import type {CandidateGeneration,PublicationJournalEntry} from '@/core/types';
const journalId=z.string().regex(/^jrnl_[a-f0-9-]{36}$/),sha=z.string().regex(/^[a-f0-9]{40}$/).refine(value=>!/^0{40}$/.test(value));
export const preparedPublicationRequestSchema=z.object({journalId,expectedCommit:sha}).strict();export type PreparedPublicationRequest=z.infer<typeof preparedPublicationRequestSchema>;
const receiptSchema=z.union([z.object({publicationRequested:z.literal(true),workflowId:z.string(),journalId,accepted:z.literal(false),status:z.string().optional(),acknowledgementRecovered:z.boolean().optional()}).strict(),z.object({publicationRequested:z.literal(false),accepted:z.literal(true),duplicate:z.literal(true),receipt:z.object({commit:sha,ref:z.string(),journalId,candidateId:z.string(),evidenceId:z.string(),tree:sha}).strict()}).strict()]);
export function checkedPreparedPublicationReceipt(raw:unknown,candidateId:string,request:PreparedPublicationRequest){const receipt=receiptSchema.parse(raw);if(receipt.accepted){if(receipt.receipt.commit!==request.expectedCommit||receipt.receipt.journalId!==request.journalId||receipt.receipt.candidateId!==candidateId)throw Error('Accepted publication receipt differs');}else if(receipt.journalId!==request.journalId||receipt.workflowId!==`pub-${request.journalId}`)throw Error('Prepared publication request differs');return receipt;}
export function preparedPublicationRequest(candidate:CandidateGeneration,journal:readonly PublicationJournalEntry[]|undefined){if(candidate.preservationProtocolVersion!==1||!candidate.review?.approved||candidate.review.commit!==candidate.candidateCommit||!candidate.candidateCommit)return null;const rows=journal?.filter(row=>row.candidateId===candidate.id&&row.state==='PREPARED'&&row.newHead===candidate.candidateCommit&&row.publicationAuthority?.kind==='human-review'&&row.publicationAuthority.commit===candidate.candidateCommit&&row.publicationAuthority.actor.userId===candidate.review?.actor?.userId)??[];if(rows.length!==1)return null;const parsed=preparedPublicationRequestSchema.safeParse({journalId:rows[0]!.id,expectedCommit:candidate.candidateCommit});return parsed.success?parsed.data:null;}
export interface PublicationRecoveryStorage{getItem(key:string):string|null;setItem(key:string,value:string):void}
const intentSchema=z.object({request:preparedPublicationRequestSchema,state:z.enum(['unknown','paused','requested','accepted'])}).strict();export type PreparedPublicationIntent=z.infer<typeof intentSchema>;
const key=(identity:string,projectId:string,candidateId:string,journalId:string)=>`flaregit.prepared-publication.${JSON.stringify([identity,projectId,candidateId,journalId])}`;
export function readPreparedPublicationIntent(storage:PublicationRecoveryStorage,identity:string,projectId:string,candidateId:string,request:PreparedPublicationRequest){const raw=storage.getItem(key(identity,projectId,candidateId,request.journalId));if(!raw)return null;if(raw.length>2048)throw Error('Saved publication recovery is invalid');const saved=intentSchema.parse(JSON.parse(raw));if(JSON.stringify(saved.request)!==JSON.stringify(request))throw Error('Original publication journal differs');return saved;}
export function savePreparedPublicationIntent(storage:PublicationRecoveryStorage,identity:string,projectId:string,candidateId:string,intent:PreparedPublicationIntent){const prior=readPreparedPublicationIntent(storage,identity,projectId,candidateId,intent.request);if(prior?.state==='accepted'&&intent.state!=='accepted')throw Error('Accepted publication receipt is already retained');const value=JSON.stringify(intentSchema.parse(intent));storage.setItem(key(identity,projectId,candidateId,intent.request.journalId),value);if(storage.getItem(key(identity,projectId,candidateId,intent.request.journalId))!==value)throw Error('Browser publication recovery was not saved');}
export function clearPreparedPublicationRecovery(keepIdentity:string|null){try{const prefix='flaregit.prepared-publication.',keys=Array.from({length:sessionStorage.length},(_,index)=>sessionStorage.key(index));for(const value of keys)if(value?.startsWith(prefix)&&(!keepIdentity||!value.startsWith(`${prefix}[${JSON.stringify(keepIdentity)},`)))sessionStorage.removeItem(value);}catch{/* Exact server journal remains the recovery identity. */}}

export function preparedPublicationFailure(cause:unknown):'paused'|'unknown'{return typeof cause==='object'&&cause!==null&&'status' in cause&&cause.status===503&&'message' in cause&&typeof cause.message==='string'&&cause.message.startsWith('Publication is paused until a separate execution grant is configured.')?'paused':'unknown';}
