import {array,boolean,enum as enumSchema,int,literal,maxLength,minLength,minimum,nullable,object,optional,regex,string,uuid,type infer as Infer} from 'zod/mini';import {apiJson} from './api';import {isSafeRef} from '@/core/sanitize';
const id=string().check(minLength(1),maxLength(128),regex(/^[A-Za-z0-9_-]+$/)),journalId=string().check(regex(/^jrnl_[a-f0-9-]{36}$/)),sha=string().check(regex(/^[a-f0-9]{40}$/));
const operationSchema=object({candidateId:id,journalId,ref:string().check(maxLength(220)),commit:sha,state:literal('PREPARED'),dispatchMarker:enumSchema(['never','possible','unverified']),recoveryStatus:enumSchema(['inspection_required','cleanup_required','cancellation_check_available']),nativeState:enumSchema(['stopped','held','unverified']),nativeSealed:nullable(boolean()),credentialsSettled:boolean(),canRequestCancellation:boolean(),observedOutcome:enumSchema(['not_checked','landed','not_landed','unavailable']),checkedAt:optional(string())});
const snapshotSchema=object({operations:array(operationSchema).check(maxLength(20)),truncated:boolean()});
const outcomeSchema=object({journalId,reason:enumSchema(['awaiting_readback','confirmed','not_observed','inspection_limit','scope_changed','capacity_unavailable','provider_unavailable']),head:optional(sha),checkedAt:string(),automaticAttempts:int().check(minimum(0)),canCheck:boolean()});
export type BoundPublicationOperation=Infer<typeof operationSchema>;export type BoundPublicationSnapshot=Infer<typeof snapshotSchema>;
export interface PublicationRecoveryIntent{scope:string;eventId:string}
export function publicationRecoveryIntent(previous:PublicationRecoveryIntent|null,projectId:string,operation:BoundPublicationOperation,kind:'check'|'cancel'):PublicationRecoveryIntent{const scope=JSON.stringify([projectId,operation.candidateId,operation.journalId,operation.ref,operation.commit,kind]);return previous?.scope===scope?previous:{scope,eventId:crypto.randomUUID()};}
export function checkedPublicationSnapshot(value:unknown):BoundPublicationSnapshot{const snapshot=snapshotSchema.parse(value);if(new Set(snapshot.operations.map(operation=>operation.journalId)).size!==snapshot.operations.length)throw Error('Publication recovery repeated a saved journal');for(const operation of snapshot.operations){const positive=operation.dispatchMarker==='never'&&operation.nativeState==='stopped'&&operation.nativeSealed===true&&operation.credentialsSettled;if(!operation.ref.startsWith('refs/heads/')||!isSafeRef(operation.ref)||/^0{40}$/.test(operation.commit)||operation.canRequestCancellation!==positive||(operation.recoveryStatus==='cancellation_check_available')!==positive)throw Error('Publication cancellation proof was not confirmed');}return snapshot;}
export function publicationOutcomeMessage(outcome:BoundPublicationOperation['observedOutcome']):string{switch(outcome){case'landed':return 'Git outcome was observed as landed; check the accepted journal before relying on finalization.';case'not_landed':return 'The requested Git outcome was not observed. This does not prove cancellation or permit another push.';case'unavailable':return 'Git outcome is unavailable. The publication remains pending.';default:return 'Git outcome has not been checked. The saved publication remains pending.';}}
export async function checkPublicationGitOutcome(projectId:string,operation:BoundPublicationOperation,eventId:string,signal:AbortSignal){uuid().parse(eventId);const outcome=outcomeSchema.parse(await apiJson<unknown>(`/p/${projectId}/publication-recovery/${operation.journalId}/check`,{method:'POST',json:{requestId:eventId},signal}));if(outcome.journalId!==operation.journalId)throw Error('Publication outcome belongs to another saved journal');return outcome;}
export async function readBoundPublicationRecovery(projectId:string,signal:AbortSignal){return checkedPublicationSnapshot(await apiJson<unknown>(`/p/${projectId}/publication-recovery/bound`,{signal}));}
export async function cancelUndispatchedPublication(projectId:string,operation:BoundPublicationOperation,eventId:string,signal:AbortSignal){if(!operation.canRequestCancellation||operation.dispatchMarker!=='never'||operation.nativeState!=='stopped'||operation.nativeSealed!==true||!operation.credentialsSettled)throw Error('Undispatched publication cancellation requires positive recorded proof');uuid().parse(eventId);const result=object({journalId,candidateId:id,eventId:uuid(),status:literal('cancelled_undispatched'),ref:string(),commit:sha}).parse(await apiJson<unknown>(`/p/${projectId}/publication-recovery/${operation.journalId}/cancel-undispatched`,{method:'POST',json:{requestId:eventId,candidateId:operation.candidateId,expectedRef:operation.ref,expectedCommit:operation.commit,confirmCancel:true},signal}));if(result.journalId!==operation.journalId||result.candidateId!==operation.candidateId||result.eventId!==eventId||result.ref!==operation.ref||result.commit!==operation.commit)throw Error('Publication cancellation receipt changed its saved scope');return result;}
interface RecoveryStorage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
const intentStorageKey=(identity:string,projectId:string,operation:BoundPublicationOperation,kind:'check'|'cancel')=>`flaregit.review.${JSON.stringify([identity,projectId,operation.candidateId,operation.commit,'publication',operation.journalId,operation.ref,kind])}`;
/** Metadata-only request recovery shares the authenticated browser-session purge namespace. */
export function readPublicationRecoveryIntent(storage:RecoveryStorage,identity:string,projectId:string,operation:BoundPublicationOperation,kind:'check'|'cancel'):PublicationRecoveryIntent|null{try{const raw=storage.getItem(intentStorageKey(identity,projectId,operation,kind));if(!raw||raw.length>5000)return null;const value=object({scope:string().check(maxLength(2000)),eventId:uuid()}).parse(JSON.parse(raw));return value.scope===JSON.stringify([projectId,operation.candidateId,operation.journalId,operation.ref,operation.commit,kind])?value:null;}catch{return null;}}
export function savePublicationRecoveryIntent(storage:RecoveryStorage,identity:string,projectId:string,operation:BoundPublicationOperation,kind:'check'|'cancel',intent:PublicationRecoveryIntent):boolean{try{uuid().parse(intent.eventId);if(intent.scope!==JSON.stringify([projectId,operation.candidateId,operation.journalId,operation.ref,operation.commit,kind]))return false;storage.setItem(intentStorageKey(identity,projectId,operation,kind),JSON.stringify(intent));return true;}catch{return false;}}
export function clearPublicationRecoveryIntent(storage:RecoveryStorage,identity:string,projectId:string,operation:BoundPublicationOperation,kind:'check'|'cancel'):void{try{storage.removeItem(intentStorageKey(identity,projectId,operation,kind));}catch{/* The confirmed server receipt remains authoritative. */}}
