import {array,boolean,enum as enumSchema,int,literal,maxLength,minLength,minimum,nullable,object,optional,regex,string,uuid,type infer as Infer} from 'zod/mini';import {apiJson} from './api';import {isSafeRef} from '@/core/sanitize';
const id=string().check(minLength(1),maxLength(200)),sha=string().check(regex(/^[a-f0-9]{40}$/)),revision=int().check(minimum(1)),timestamp=string(),tagType=enumSchema(['commit','tag','tree','blob']);
const tagSchema=object({name:id,ref:id,object:sha,objectType:tagType,peeledCommit:nullable(sha)}),targetSchema=object({journalId:id,acceptedRef:string().check(maxLength(220)),acceptedRootVersion:int().check(minimum(0)),commit:sha,tree:sha});
const operationSchema=object({operationId:uuid(),name:id,sourceCommit:sha,sourceTree:sha,phase:enumSchema(['prepared','unknown','confirmed','refused']),createdAt:int().check(minimum(0)),reason:optional(enumSchema(['existing_ref','different_ref','owner_abandoned_prepared'])),observation:optional(object({object:sha,commit:optional(sha),tree:optional(sha),type:optional(enumSchema(['commit','tag']))})),cleanup:literal('not_reported'),acceptedJournalId:id,acceptedRef:string().check(maxLength(220)),acceptedRootVersion:int().check(minimum(0)),nativeStopped:boolean(),credentialsComplete:boolean(),providerVerified:boolean(),recovery:enumSchema(['reconcile_only','resume_prepared','none']),currentTagVerified:optional(boolean())});
const sourceSchema=object({name:id,tagOperationId:uuid(),acceptedJournalId:id,acceptedRef:string().check(maxLength(220)),acceptedRootVersion:int().check(minimum(0)),commit:sha,tree:sha});
const releaseSchema=object({scope:object({id:uuid(),projectId:id,incarnation:uuid(),canonicalRepoName:id,authorId:string().check(minLength(1),maxLength(256)),source:sourceSchema}),title:string().check(minLength(1),maxLength(200)),notes:string().check(maxLength(16000)),revision,phase:enumSchema(['draft','published']),createdAt:timestamp,updatedAt:timestamp,publishedAt:optional(timestamp),publishedBy:optional(string()),tag:optional(object({object:sha,type:enumSchema(['commit','tag']),commit:sha,tree:sha})),editHistory:optional(array(object({id:uuid(),revision,editorId:string(),at:timestamp})).check(maxLength(100)))});
export type RepoGitTag=Infer<typeof tagSchema>;export type RepoTagTarget=Infer<typeof targetSchema>;export type RepoTagOperation=Infer<typeof operationSchema>;export type RepoRelease=Infer<typeof releaseSchema>;
export function checkedRepoTagOperation(value:unknown,expected?:{name:string;target:RepoTagTarget}):RepoTagOperation{const op=operationSchema.parse(value);if(!isSafeRef(op.name)||op.name.startsWith('refs/')||op.name==='HEAD'||!op.acceptedRef.startsWith('refs/heads/')||!isSafeRef(op.acceptedRef)||(op.acceptedJournalId==='baseline'?op.acceptedRootVersion!==0:op.acceptedRootVersion===0)||/^0{40}$/.test(op.sourceCommit)||(expected&&(op.name!==expected.name||op.sourceCommit!==expected.target.commit||op.sourceTree!==expected.target.tree||op.acceptedJournalId!==expected.target.journalId||op.acceptedRef!==expected.target.acceptedRef||op.acceptedRootVersion!==expected.target.acceptedRootVersion))||op.providerVerified!==(op.phase==='confirmed')||(op.phase==='confirmed'&&(!op.observation||op.observation.object!==op.sourceCommit||op.observation.type!=='commit'||op.observation.commit!==op.sourceCommit||op.observation.tree!==op.sourceTree))||(op.recovery==='resume_prepared'&&(op.phase!=='prepared'||!op.nativeStopped||!op.credentialsComplete)))throw Error('Saved tag scope was not confirmed');return op;}
export function checkedRepoRelease(value:unknown,projectId:string):RepoRelease{const release=releaseSchema.parse(value);if(release.scope.projectId!==projectId||(release.scope.source.acceptedJournalId==='baseline'?release.scope.source.acceptedRootVersion!==0:release.scope.source.acceptedRootVersion===0)||/^0{40}$/.test(release.scope.source.commit)||/^0{40}$/.test(release.scope.source.tree)||!isSafeRef(release.scope.source.name)||release.scope.source.name.startsWith('refs/')||!release.scope.source.acceptedRef.startsWith('refs/heads/')||!isSafeRef(release.scope.source.acceptedRef)||!Number.isFinite(Date.parse(release.createdAt))||!Number.isFinite(Date.parse(release.updatedAt))||(release.phase==='published'&&(!release.publishedAt||!Number.isFinite(Date.parse(release.publishedAt))||!release.publishedBy||!release.tag||release.tag.commit!==release.scope.source.commit||release.tag.tree!==release.scope.source.tree||(release.tag.type==='commit'&&release.tag.object!==release.tag.commit))))throw Error('Release identity or publication receipt was not confirmed');return release;}
export async function readRepoTags(projectId:string,signal:AbortSignal){const value=object({tags:array(tagSchema).check(maxLength(200)),truncated:boolean()}).parse(await apiJson<unknown>(`/p/${projectId}/tags`,{signal}));if(new Set(value.tags.map(tag=>tag.ref)).size!==value.tags.length||value.tags.some(tag=>!isSafeRef(tag.name)||tag.ref!==`refs/tags/${tag.name}`||(tag.objectType==='commit'&&tag.peeledCommit!==tag.object)||(['tree','blob'].includes(tag.objectType)&&tag.peeledCommit!==null)))throw Error('Native tag inventory was not confirmed');return value;}
export async function readRepoTagTargets(projectId:string,signal:AbortSignal){const value=object({targets:array(targetSchema).check(maxLength(20)),truncated:boolean()}).parse(await apiJson<unknown>(`/p/${projectId}/tag-targets`,{signal}));if(value.targets.some(target=>(target.journalId==='baseline'?target.acceptedRootVersion!==0:target.acceptedRootVersion===0)||!target.acceptedRef.startsWith('refs/heads/')||!isSafeRef(target.acceptedRef)||/^0{40}$/.test(target.commit)))throw Error('Accepted tag sources were not confirmed');return value;}
export async function readRepoTagOperations(projectId:string,signal:AbortSignal){const value=object({operations:array(operationSchema).check(maxLength(20)),truncated:boolean()}).parse(await apiJson<unknown>(`/p/${projectId}/tag-operations`,{signal}));return{...value,operations:value.operations.map(op=>checkedRepoTagOperation(op))};}
export async function readRepoReleases(projectId:string,signal:AbortSignal){const value=object({releases:array(releaseSchema).check(maxLength(20)),truncated:boolean(),assetsSupported:literal(false)}).parse(await apiJson<unknown>(`/p/${projectId}/releases`,{signal}));return{...value,releases:value.releases.map(release=>checkedRepoRelease(release,projectId))};}
export interface RepoTagIntent{requestId:string;name:string;target:RepoTagTarget}
export function repoTagIntent(previous:RepoTagIntent|null,name:string,target:RepoTagTarget):RepoTagIntent{if(previous)return previous;if(!isSafeRef(name)||name==='HEAD'||name.startsWith('refs/'))throw Error('Use a supported short Git tag name');return{requestId:crypto.randomUUID(),name,target:{...target}};}
export async function createRepoTag(projectId:string,intent:RepoTagIntent,signal:AbortSignal){const target=intent.target;return checkedRepoTagOperation(await apiJson<unknown>(`/p/${projectId}/tags`,{method:'POST',json:{requestId:intent.requestId,name:intent.name,selected:{journalId:target.journalId,acceptedRef:target.acceptedRef,acceptedRootVersion:target.acceptedRootVersion},sourceCommit:target.commit,sourceTree:target.tree},signal}),intent);}
export async function recoverRepoTag(projectId:string,operation:RepoTagOperation,kind:'reconcile'|'cleanup'|'resume',requestId:string,signal:AbortSignal){const value=checkedRepoTagOperation(await apiJson<unknown>(`/p/${projectId}/tag-operations/${operation.operationId}/${kind}`,{method:'POST',json:{requestId,...(kind==='cleanup'?{confirmStop:true}:{})},signal}));if(value.operationId!==operation.operationId||value.name!==operation.name||value.sourceCommit!==operation.sourceCommit||value.sourceTree!==operation.sourceTree)throw Error('Tag recovery changed its original scope');return value;}
export async function readRepoRelease(projectId:string,id:string,signal:AbortSignal){const release=checkedRepoRelease(await apiJson<unknown>(`/p/${projectId}/releases/${id}`,{signal}),projectId);if(release.scope.id!==id)throw Error('Recorded release identity changed');return release;}
export async function saveRepoRelease(projectId:string,value:{id:string;tagOperationId:string;title:string;notes:string},signal:AbortSignal){const release=checkedRepoRelease(await apiJson<unknown>(`/p/${projectId}/releases`,{method:'POST',json:value,signal}),projectId);if(release.scope.id!==value.id||release.scope.source.tagOperationId!==value.tagOperationId||release.title!==value.title.trim()||release.notes!==value.notes)throw Error('Release draft save was not confirmed');return release;}
export async function editRepoRelease(projectId:string,release:RepoRelease,value:{editId:string;expectedRevision:number;title:string;notes:string},signal:AbortSignal){const result=object({record:releaseSchema,appliedRevision:revision,replayed:boolean()}).parse(await apiJson<unknown>(`/p/${projectId}/releases/${release.scope.id}`,{method:'PATCH',json:value,signal}));const checked=checkedRepoRelease(result.record,projectId);if(checked.scope.id!==release.scope.id||JSON.stringify(checked.scope.source)!==JSON.stringify(release.scope.source))throw Error('Release edit changed its Git source');if(result.appliedRevision!==value.expectedRevision+1||checked.revision<result.appliedRevision||(!result.replayed&&checked.revision!==result.appliedRevision)||(checked.revision===result.appliedRevision&&(checked.title!==value.title.trim()||checked.notes!==value.notes)))throw Error('Release edit receipt was not confirmed');return{record:checked,appliedRevision:result.appliedRevision,replayed:result.replayed};}
export async function publishRepoRelease(projectId:string,release:RepoRelease,signal:AbortSignal){const result=checkedRepoRelease(await apiJson<unknown>(`/p/${projectId}/releases/${release.scope.id}/publish`,{method:'POST',json:{expectedRevision:release.revision,confirmPublish:true},signal}),projectId);if(result.scope.id!==release.scope.id||result.phase!=='published'||JSON.stringify(result.scope.source)!==JSON.stringify(release.scope.source))throw Error('Release publication was not confirmed');return result;}

export interface RepoReleaseEditor{release:RepoRelease|null;operation:RepoTagOperation;title:string;notes:string}
export interface RepoReleaseWriteIntent{signature:string;id:string;editId:string}
export interface RepoVersionRecovery{tagIntent:RepoTagIntent|null;editor:RepoReleaseEditor|null;releaseIntent:RepoReleaseWriteIntent|null}
const recoverySchema=object({tagIntent:nullable(object({requestId:uuid(),name:id,target:targetSchema})),editor:nullable(object({release:nullable(releaseSchema),operation:operationSchema,title:string().check(maxLength(200)),notes:string().check(maxLength(16000))})),releaseIntent:nullable(object({signature:string().check(maxLength(20000)),id:uuid(),editId:uuid()}))});
interface RecoveryStorage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
const recoveryKey=(identity:string,projectId:string)=>`flaregit.review.${JSON.stringify([identity,projectId,'repository-versions'])}`;
export function readRepoVersionRecovery(storage:RecoveryStorage,identity:string,projectId:string):RepoVersionRecovery|null{try{const raw=storage.getItem(recoveryKey(identity,projectId));if(!raw||raw.length>100000)return null;const value=recoverySchema.parse(JSON.parse(raw));if(value.tagIntent){const intent=value.tagIntent;if(!isSafeRef(intent.name)||intent.name.startsWith('refs/')||intent.name==='HEAD'||!isSafeRef(intent.target.acceptedRef)||!intent.target.acceptedRef.startsWith('refs/heads/')||(intent.target.journalId==='baseline'?intent.target.acceptedRootVersion!==0:intent.target.acceptedRootVersion===0))return null;}if(value.editor){checkedRepoTagOperation(value.editor.operation);if(value.editor.release)checkedRepoRelease(value.editor.release,projectId);if(value.editor.release&&value.editor.release.scope.source.tagOperationId!==value.editor.operation.operationId)return null;}return value;}catch{return null;}}
export function saveRepoVersionRecovery(storage:RecoveryStorage,identity:string,projectId:string,value:RepoVersionRecovery):boolean{try{const raw=JSON.stringify(value);if(!readRepoVersionRecovery({getItem:()=>raw,setItem:()=>{},removeItem:()=>{}},identity,projectId))return false;const key=recoveryKey(identity,projectId);if(!value.tagIntent&&!value.editor&&!value.releaseIntent){storage.removeItem(key);return storage.getItem(key)===null;}storage.setItem(key,raw);return storage.getItem(key)===raw;}catch{return false;}}

export async function readRepoTagOperation(projectId:string,id:string,signal:AbortSignal){const value=checkedRepoTagOperation(await apiJson<unknown>(`/p/${projectId}/tag-operations/${id}`,{signal}));if(value.operationId!==id)throw Error('Recorded tag request identity changed');return value;}

export class RepoVersionPersistenceError extends Error {constructor(){super('Browser recovery storage is unavailable. No new request was sent. Keep this form and retry when session storage is available.');}}
/** Persist the original identity and content before allowing a remote write. */
export async function dispatchRepoVersionWrite<T>(persist:()=>boolean,write:()=>Promise<T>):Promise<T>{if(!persist())throw new RepoVersionPersistenceError();return write();}
