import {isSafeRef} from "@/core/sanitize";
export interface ReviewDraftScope{identity:string;projectId:string;candidateId:string;commit:string;kind:'owner'|'delegated'}
export interface DelegatedDraftIntent{kind:'delegated';eventId:string;payload:{expectedCommit:string;grantVersion:number;decision:'approve'|'request_changes'|'withdraw';note:string}}
export interface OwnerDraftIntent{kind:'owner';payload:{expectedCommit:string;approved:boolean;note:string;expectedTarget?:{ref:string;acceptedCommit:string|null;acceptedVersion:number}}}
export interface ReviewDraft{note:string;intent:DelegatedDraftIntent|OwnerDraftIntent|null}
interface DraftStorage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
const sha=/^[a-f0-9]{40}$/,uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
const keyFor=(scope:ReviewDraftScope)=>`flaregit.review.${JSON.stringify([scope.identity,scope.projectId,scope.candidateId,scope.commit,scope.kind])}`;
export function readReviewDraft(storage:DraftStorage,scope:ReviewDraftScope):ReviewDraft|null{try{const raw=storage.getItem(keyFor(scope));if(!raw||raw.length>30000||!sha.test(scope.commit))return null;const value:unknown=JSON.parse(raw);if(!value||typeof value!=='object')return null;const draft=value as Record<string,unknown>;if(draft.identity!==scope.identity||draft.projectId!==scope.projectId||draft.candidateId!==scope.candidateId||draft.commit!==scope.commit||draft.kind!==scope.kind||typeof draft.note!=='string'||draft.note.length>(scope.kind==='owner'?500:5000))return null;const intent=draft.intent;if(intent===null)return{note:draft.note,intent:null};if(!intent||typeof intent!=='object'||!('kind'in intent)||intent.kind!==scope.kind||!('payload'in intent)||!intent.payload||typeof intent.payload!=='object')return null;const payload=intent.payload;if(!('expectedCommit'in payload)||payload.expectedCommit!==scope.commit||!('note'in payload)||payload.note!==(scope.kind==='owner'?draft.note:draft.note.trim()))return null;if(intent.kind==='owner'){if(!('approved'in payload)||typeof payload.approved!=='boolean')return null;let expectedTarget:OwnerDraftIntent['payload']['expectedTarget'];if('expectedTarget'in payload){const target=payload.expectedTarget;if(!target||typeof target!=='object'||!('ref'in target)||typeof target.ref!=='string'||!target.ref.startsWith('refs/heads/')||!isSafeRef(target.ref)||!('acceptedCommit'in target)||target.acceptedCommit!==null&&(typeof target.acceptedCommit!=='string'||!sha.test(target.acceptedCommit)||/^0{40}$/.test(target.acceptedCommit))||!('acceptedVersion'in target)||typeof target.acceptedVersion!=='number'||!Number.isSafeInteger(target.acceptedVersion)||target.acceptedVersion<0||target.acceptedCommit===null&&target.acceptedVersion!==0)return null;expectedTarget={ref:target.ref,acceptedCommit:target.acceptedCommit,acceptedVersion:target.acceptedVersion};}return{note:draft.note,intent:{kind:'owner',payload:{expectedCommit:scope.commit,approved:payload.approved,note:payload.note,...(expectedTarget?{expectedTarget}:{})}}};}if(!('eventId'in intent)||typeof intent.eventId!=='string'||!uuid.test(intent.eventId)||!('grantVersion'in payload)||typeof payload.grantVersion!=='number'||!Number.isSafeInteger(payload.grantVersion)||payload.grantVersion<0||!('decision'in payload)||!['approve','request_changes','withdraw'].includes(String(payload.decision)))return null;return{note:draft.note,intent:{kind:'delegated',eventId:intent.eventId,payload:{expectedCommit:scope.commit,grantVersion:payload.grantVersion,decision:payload.decision as DelegatedDraftIntent['payload']['decision'],note:payload.note}}};}catch{return null;}}
export function saveReviewDraft(storage:DraftStorage,scope:ReviewDraftScope,draft:ReviewDraft):boolean{try{if(!sha.test(scope.commit)||draft.note.length>(scope.kind==='owner'?500:5000))return false;const value=JSON.stringify({...scope,...draft});const probe={getItem:()=>value,setItem:()=>{},removeItem:()=>{}};if(!readReviewDraft(probe,scope))return false;storage.setItem(keyFor(scope),value);return true;}catch{return false;}}
export function clearReviewDraft(storage:DraftStorage,scope:ReviewDraftScope):void{try{storage.removeItem(keyFor(scope));}catch{/* Confirmed server receipts remain authoritative. */}}
export function delegatedDraftIntent(previous:DelegatedDraftIntent|null,payload:DelegatedDraftIntent['payload']):DelegatedDraftIntent{return previous&&JSON.stringify(previous.payload)===JSON.stringify(payload)?previous:{kind:'delegated',eventId:crypto.randomUUID(),payload:{...payload}};}
export function clearSessionReviewDrafts(identity:string):void{try{const prefix=`flaregit.review.[${JSON.stringify(identity)},`;const keys=Array.from({length:sessionStorage.length},(_,index)=>sessionStorage.key(index));for(const key of keys)if(key?.startsWith(prefix))sessionStorage.removeItem(key);}catch{/* Unavailable storage is never evidence of a successful browser save. */}}
/** A loaded signed-out state must also purge drafts left by a prior page lifetime. */
export function clearVerifiedSessionRecovery():void{try{const keys=Array.from({length:sessionStorage.length},(_,index)=>sessionStorage.key(index));for(const key of keys)if(key?.startsWith('flaregit.review.')||key?.startsWith('flaregit.conversation.')||key?.startsWith('flaregit.mirror.'))sessionStorage.removeItem(key);}catch{/* Storage availability does not change authentication authority. */}}
/** The newly verified principal also excludes recovery left by another page lifetime. */
export function clearOtherSessionRecovery(identity:string):void{try{const prefixes=['flaregit.review.','flaregit.conversation.','flaregit.mirror.'];const keys=Array.from({length:sessionStorage.length},(_,index)=>sessionStorage.key(index));for(const key of keys){const prefix=prefixes.find(value=>key?.startsWith(value));if(prefix&&key&&!key.startsWith(`${prefix}[${JSON.stringify(identity)},`))sessionStorage.removeItem(key);}}catch{/* Restoration still checks the complete exact scope. */}}
