import {z} from 'zod';
export interface ReplayScope {identity:string;projectId:string}
export interface ReplayStorage {getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
const intentSchema=z.object({deliveryId:z.string().regex(/^dlv_[a-z0-9-]+$/),request:z.object({idempotencyKey:z.uuid(),expectedGeneration:z.number().int().nonnegative().safe()}).strict()}).strict();
const recordsSchema=z.array(intentSchema).max(50).refine(records=>new Set(records.map(record=>record.deliveryId)).size===records.length);
export type WebhookReplayIntent=z.infer<typeof intentSchema>;
const key=(scope:ReplayScope)=>'flaregit.webhook-replays.'+JSON.stringify([scope.identity,scope.projectId]);
export function readWebhookReplays(storage:ReplayStorage,scope:ReplayScope):WebhookReplayIntent[]{const raw=storage.getItem(key(scope));if(raw===null)return [];if(raw.length>65536)throw Error('Replay recovery data exceeds its browser limit.');return recordsSchema.parse(JSON.parse(raw));}
export function prepareWebhookReplay(deliveryId:string,generation:number):WebhookReplayIntent{return intentSchema.parse({deliveryId,request:{idempotencyKey:crypto.randomUUID(),expectedGeneration:generation}});}
export function saveWebhookReplay(storage:ReplayStorage,scope:ReplayScope,intent:WebhookReplayIntent):WebhookReplayIntent[]{const checked=intentSchema.parse(intent),records=readWebhookReplays(storage,scope),original=records.find(record=>record.deliveryId===checked.deliveryId);if(original&&JSON.stringify(original)!==JSON.stringify(checked))throw Error('The original replay request must be reconciled before another replay.');const next=recordsSchema.parse(original?records:[...records,checked]),raw=JSON.stringify(next);storage.setItem(key(scope),raw);if(storage.getItem(key(scope))!==raw)throw Error('Replay recovery could not be saved. No request was sent.');return next;}
export function acknowledgeWebhookReplay(storage:ReplayStorage,scope:ReplayScope,intent:WebhookReplayIntent):WebhookReplayIntent[]{const records=readWebhookReplays(storage,scope),original=records.find(record=>record.deliveryId===intent.deliveryId);if(original&&JSON.stringify(original)!==JSON.stringify(intent))throw Error('Saved replay identity changed.');const remaining=records.filter(record=>record.deliveryId!==intent.deliveryId),raw=JSON.stringify(remaining);storage.setItem(key(scope),raw);if(storage.getItem(key(scope))!==raw)throw Error('Replay was confirmed but browser recovery could not be cleared.');return remaining;}
